### ISSUE TITLE
Running interop tests is way too difficult

### ISSUE THREAD

**Issue by ctiller** [grpc/grpc#10016]
I either need to:
1. maintain a build environment for every wrapped language
2. steal commands built by python scripts and type them in manually

Suggest a 'run_interop_server.py', 'run_interop_client.py' that can take care of building and running a docker image for me.

**Comment by ejona86** [comment]
+1. I need to be able to manually run the tests, and it doesn't seem readily possible to do that.

I think the "build" and "run" should be split though. Rebuilding before each run is maddening.

Could we have the Dockerfiles specify an `ENTRYPOINT` so that we could simply use `docker run` to execute them? Any arguments would be passed directly to the language's interop test binary, so we could specify which tests and similar. The "run" script would then be pretty trivial, and it would allow testing across versions.

**Comment by jtattermusch** [comment]
@ejona86 I feel your pain,  but it's much more complicated than that (because run_interop_tests.py is pretty complex now and there are reasons why things are done in a certain way, it's not so straigthforward to do what you are suggesting - even though it sounds it shouldn't be hard). I tried to do my best and came up with something that should hopefully cover your needs in https://github.com/grpc/grpc/pull/10037 (and at the same time it should be usable for interop testing against older releases).
Also, I ran out time I can spend on this, so this will have to do.
