### ISSUE TITLE
cloud_to_cloud:MANY_LANGUAGES:http2_server interop tests flake

### ISSUE THREAD

**Issue by jtattermusch** [grpc/grpc#10056]
https://grpc-testing.appspot.com/job/gRPC_interop_pull_requests/11967/

Tests seem to be timing out.
```
tests.cloud_to_cloud:java:http2_server:rst_during_data
tests.cloud_to_cloud:python:http2_server:ping
tests.cloud_to_cloud:java:csharpcoreclr_server:large_unary
tests.cloud_to_cloud:go:http2_server:rst_after_data
tests.cloud_to_cloud:python:http2_server:goaway
tests.cloud_to_cloud:c++:http2_server:rst_during_data
tests.cloud_to_cloud:python:http2_server:max_streams
tests.cloud_to_cloud:python:http2_server:rst_after_data
tests.cloud_to_cloud:c++:http2_server:goaway
tests.cloud_to_cloud:go:http2_server:goaway
tests.cloud_to_cloud:php:java_server:large_unary
tests.cloud_to_cloud:java:http2_server:rst_after_data
tests.cloud_to_cloud:go:http2_server:max_streams
tests.cloud_to_cloud:java:csharp_server:custom_metadata
tests.cloud_to_cloud:java:http2_server:goaway
tests.cloud_to_cloud:c++:http2_server:ping
tests.cloud_to_cloud:java:http2_server:ping
tests.cloud_to_cloud:java:http2_server:rst_after_header
tests.cloud_to_cloud:c++:http2_server:max_streams
tests.cloud_to_cloud:go:http2_server:rst_after_header
tests.cloud_to_cloud:java:http2_server:max_streams
tests.cloud_to_cloud:python:http2_server:rst_during_data
tests.cloud_to_cloud:go:http2_server:ping
tests.cloud_to_cloud:python:http2_server:rst_after_header
tests.cloud_to_cloud:c++:http2_server:rst_after_header
tests.cloud_to_cloud:c++:http2_server:rst_after_data
tests.cloud_to_cloud:go:http2_server:rst_during_data
```

**Comment by adelez** [comment]
I wish there's a tool in Jenkins to show history of each individual test. I guess with Kokoro, we can do that since they support Sponge.

**Comment by ericgribkoff** [comment]
#10100 will fix the problem, which was due to the use of the `--net=host` flag when running the http2 server docker image along with hard-coding the ports `8080-8085`. If multiple Jenkins jobs were running at the same time, starting the http2 server would silently fail because the ports were already bound. Obfuscating this issue was the occasional instance where docker job <span>#</span>2's http2 server failed to start, but while it's http2 interop tests were running it was able to successfully connect to the http2 server started for docker job <span>#</span>1.

#10100 passed on Jenkins, but locally it *always* fails the first two C++ http2 interop tests (regardless of which two those are) due to another issue: the http2 server, at start up, is in some weird quasi-state where the C++ client can connect to it and begin the test, but the server is not actually responding with valid Http2 frames (verified via wireshark). I've added a healthcheck of the server that gates running the http2 interop tests, and will try to get this added to the PR by the end of the day.

**Comment by ericgribkoff** [comment]
Fixed by https://github.com/grpc/grpc/pull/10100.

**Comment by apolcyn** [comment]
does #10100 need to be cherry-picked to v1.2.x?

failures noticed in pr: #10230 against v1.2.x, log in https://grpc-testing.appspot.com/job/gRPC_interop_pull_requests/12399/#showFailuresLink

**Comment by apolcyn** [comment]
seen again in #10269 against v1.2.x. log in https://grpc-testing.appspot.com/job/gRPC_interop_pull_requests/12524/#showFailuresLink
