### ISSUE TITLE
Some Jenkins workers should run test infrastructure with Python 3 and some with Python 2

### ISSUE THREAD

**Issue by nathanielmanistaatgoogle** [grpc/grpc#10117]
As long as we want our testing scripts themselves to be runnable with both Python 2 and Python 3 (and I _think_ we do) we should consider having the test infrastructure itself mix both Python 2 and Python 3.

Otherwise we risk regressing compatibility fixes like [pull request 10115](https://github.com/grpc/grpc/pull/10115). Right?

**Comment by jtattermusch** [comment]
1. I don't see why we would need to have our testing scripts compatible with both python versions (in the long run, I'd like to get rid of these scripts rather than investing more work into them).

2. the title of this PR doesn't state what's the goal ("Setup continous tests to make sure run_tests.py is compatible with both python 2 and python 3"), but rather suggests a technical solution (and it's a bad one unfortunately - we have better ways to setup such tests). So yes, we can definitely setup some tests, but I'd need to see answer to question 1) first.

**Comment by jtattermusch** [comment]
Also, please don't double assign work items - it's hard to get sense of ownership then. I can certainly consult on how the solution could look like (if it really turns out that's what we need and I'm not convinced), but I definitely don't have cycles to actually put this in place - therefore I'm unassigning myself.

**Comment by ctiller** [comment]
I disagree that we want our infrastructure scripts runnable under both
interpreters: we get to choose one here, and we should choose just one
(anything else is burning cycles that could more profitably be spent
elsewhere).

If Python folks want to move the world to Python 3, then the burden should
be on them to do so. Python 2.7 is working just fine, and if it ain't
broke...

**Comment by muxi** [comment]
Did we make a decision on this issue?

**Comment by matt-kwong** [comment]
I don't think I we should support both 2 and 3 for our testing scripts. I'm fine with supporting one or the either; we currently only support Python 2. 

@nathanielmanistaatgoogle, do you have any strong opinions on this? If not, I'll close this issue.

**Comment by nathanielmanistaatgoogle** [comment]
@ctiller and I have discussed this a few times and I think the current working forecast is "Python 2 is ending; one day we will decide that we have to convert testing and tools scripts to Python 3 and on that day we'll do it all at once".

No need to leave this open; I am strongly _looking forward_ to never seeing Python 2 again but I _opine_ that switching our scripts can wait another... eighteen months? Twenty-four would be pushing it.
