### ISSUE TITLE
Proxy settings in c#

### ISSUE THREAD

**Issue by vds7** [grpc/grpc#10173]
I'm trying to use the dotnet version (windows)  of google speech api that relies on grpc.io, everything works correctly when I use an unproxied test network, but connection fails when I try to use my company network
How can I configure grpc in order to use a forward proxy?
I already tried to set environment variables http_proxy and https_proxy (also tried in uper case) but I had no luck.
Am I missing something?

**Comment by jtattermusch** [comment]
I don't think gRPC supports anything like HTTP_PROXY and HTTPS_PROXY environment variables (how did you hear about that?).  https://github.com/grpc/grpc/blob/master/doc/environment_variables.md

Also, gRPC protocol is using HTTP/2 (as opposed to HTTP1.1 - which might be what your proxy actually supports). More work would be needed to get the scenario working - you can file a feature request for gRPC as a whole to support proxies (it's not a C# specific feature) and you'll need to provide more technical details, but AFAIK we have no plans in that direction.
Meanwhile, I will close this issue because it's not an actual problem with gRPC.
