### ISSUE TITLE
Protobuf enums in node.js

### ISSUE THREAD

**Issue by jonywtf** [grpc/grpc#1019]
Hi! I have a trouble with protobuf enums in nodejs
my protobuf file:
```proto
    message Mobile {
        required string phone = 1;
        required string name = 2;
    }
    message MobileResponse {
        enum Res {
            SUCCESS = 1;
            UNKNOWN_ERROR = 2;
            PHONE_IS_BAD = 3;
            SMS_LIMIT = 4;
        }
        required Res res = 1;
    }

    service Sessions {
        rpc regByMobile(Mobile) returns (MobileResponse ) {}
    }
```

regByMobile server callback
```coffeescript
    regByMobile = (call, callback) ->
        callback null, {result: "SUCCESS"}
```

on client:
```coffeescript
    app.rpc.regByMobile mobile, (err, res) ->
        if err?
            console.log "err: ", err
        else
            console.log "res: ", res
```

__console.log "res: ", res__ output:
```javascript
{ result: 1 }
```

I thought that the result should be: __{ result: "SUCCESS" }__
I want to get the string value. How can I do this?
Help me please. Thank you!

**Comment by jonywtf** [comment]
Can we enable [Reflection](https://github.com/dcodeIO/ProtoBuf.js/wiki/Reflection) for enums in nodejs grpc? And get enums as string value by default.

**Comment by jonywtf** [comment]
@murgatroid99 please add commit https://github.com/zhiqingchen/ProtoBuf.js/commit/9a164b8a21d35929f13bedb82294dc9a2f1f362a to your https://github.com/murgatroid99/ProtoBuf.js repo. This commit return enum value as string

**Comment by murgatroid99** [comment]
I will look into adding reflection to enums. But I am not going to break the API of ProtoBuf.js unless there is a major need.

**Comment by nicolasnoble** [comment]
Wouldn't it be possible to do this without breaking the API ? For instance, adding an option in the decode method.

**Comment by murgatroid99** [comment]
When I talked about breaking the API, I was specifically referring to the commit I was asked to add to my fork of the repo. What you're suggesting would work, but I think there are better solutions to this. I think this should be done by adding reflection capabilities to enums so that one could easily get the name from the number.

In any case, [dcodeIO/Protobuf.js](https://github.com/dcodeIO/ProtoBuf.js) just became active again, and I have switched the dependency (pending a merge) to the protobufjs npm package. So, I would suggest opening an issue or sending a pull request on that repository.
