### ISSUE TITLE
ObjC Improvement

### ISSUE THREAD

**Issue by muxi** [grpc/grpc#10193]
More feedback on the usability of the ObjC library, copied from an email of Eduardo's:

> In particular, right now I'm really not happy about how GRPCProtoCall forces us into writing code around every RPC that is hard to share so I'm trying to find a solution for that. 

Eduardo - I see three things being accomplished in your gRPC wrapper:
Flattening the fields of the request proto into method parameters.
The Google cloud API libraries do this for the Cloud languages. I think all/most gRPC libraries should just do it out of the box, but I see how it can be controversial.
Intercepting all errors for logging them, modifying them, etc.
ObjC gRPC should totally facilitate this; it's a common use case.
Supporting `nil` response handlers.
But I think this is just defensive programming, and not something you actually want?

Setting headers common to all RPCs right before starting them.
This you can do equally with gRPC's Call object, no?
Wrapping a passed handler block, to process errors and do some things common to all responses.
We should facilitate this.
Thanks for the feedback! It's very valuable to make gRPC better for everyone.

**Comment by rikuayanokozy** [comment]
I'm using gRPC in production, and I've made react-native binding for gRPC.
I don't think the gRPC-Objc is production ready.

## GRPCChannel
The GRPCChannel and GRPCHost are private. I think it would be better if we can create a GRPCChannel like grpc-java, with ability to manage state of the channel and customize the channel arguments.
### Channel arguments
I found some hardcoded channel args and have no way to change externally, See https://github.com/grpc/grpc/blob/ed64818520f2b4b8d47ce14abbd656505a2b6ef1/src/objective-c/GRPCClient/private/GRPCHost.m#L238.

If we wanna to create an insecure connection, we have to import `GRPCCall+Tests.h` and call `[GRPCCall useInsecureConnectionsForHost:host]` before we make the call. To revert that, we need to call `[GRPCCall resetHostSettings]`, and it will reset all host settings and close all connections.

Also, there is no way to set timeout and hostnameOverride, see https://github.com/grpc/grpc/issues/9555.
### Manage state of channel
There is no way to shutdown specify channel. If we want to shutdown a channel, we must shutdown all channels:
```
// internally called [GRPCHost flushChannelCache] to disconnect all connections.
[GRPCCall closeOpenConnections];
```
## GRPCCall
### Call options
The deadline hard coded to infinity in https://github.com/grpc/grpc/blob/46357c882df1afc28f7a5228c40fde522093fa32/src/objective-c/GRPCClient/private/GRPCChannel.m#L200. We need an external timer to cancel the call.
### Misc
I think it would be better if we use delegate instead of block callback.

**Comment by Toldy** [comment]
@rikuayanokozy I'm using gRPC in production too. I think that the TCP connections that remain open will cause me problem of scalability.
Did you implement a temporary solution in your production app?
