### ISSUE TITLE
HTTP code 413 reported as GRPC code 14 - Unavailable

### ISSUE THREAD

**Issue by timanovsky** [grpc/grpc#10213]
Which means it is retriable. It should be `InvalidArgument Code = 3`

See also https://issuetracker.google.com/u/1/issues/36119546

**Comment by ejona86** [comment]
It seems very broken to be reported as `UNAVAILABLE`. I would have expected it to be either `UNKNOWN` or `INTERNAL`. Based on the [HTTP → gRPC status code mapping](https://github.com/grpc/grpc/blob/master/doc/http-grpc-status-mapping.md) it should be `UNKNOWN`.

The linked issue says that max message size triggers `INVALID_ARGUMENT`. However, that is broken as well, since [the library should never generate `INVALID_ARGUMENT`](https://github.com/grpc/grpc/blob/master/doc/statuscodes.md). It doesn't seem like we defined what the status code for max message size failures should be. Java [uses `INTERNAL`](https://github.com/grpc/grpc-java/blob/89bc2cd/core/src/main/java/io/grpc/internal/MessageDeframer.java#L347)

**Comment by apolcyn** [comment]
adding ruby label since this is happening in the grpc-ruby gem
cc @swcloud

@timanovsky is there a repro example or a certain datastore API where this shows up?

**Comment by ejona86** [comment]
I've determined this is not a gRPC client library bug. The bug seems to be on the server-side.

**Comment by apolcyn** [comment]
closing as this is stale and doesn't seem to be a client bug.
