### ISSUE TITLE
Server should look for "host" header field if ":authority" pseudo-header field is not present

### ISSUE THREAD

**Issue by tatsuhiro-t** [grpc/grpc#1022]
HTTP/2 specification clearly says that ":authority" is only mandatory if method is "CONNECT". (https://tools.ietf.org/html/draft-ietf-httpbis-http2-17#section-8.1.2.3)  Other than that, ":authority" is not mandatory and if it is omitted,  server should look for "host" instead.
Currently, server only looks for ":authority" and ignores "host" header field entirely.
If gRPC is meant to be a custom protocol, then it is fine, but it is far more beneficial to conform to the HTTP/2 spec and interoperate other implementations.

Related to this issue, another issue exists in gRPC.  If ":authority" is not present in request, then even if server sees END_STREAM, the request just hangs and nothing happens.
This implies that server implementation is a bit lazy with regard to validating request header fields.

**Comment by louiscryan** [comment]
Hey. 

So I think this is a place where the spec is slightly ambiguous and more guidance should be provided to implementers.  From that same section

"Clients  that generate HTTP/2 requests directly SHOULD use the ":authority"  pseudo-header field instead of the "Host" header field."

which is the case here. What the spec does not say anything about is an intermediary converting from HTTP/1.1 to HTTP2 though my read is that it should conform to the above and MUST convert Host->:authority given that Host is always present in HTTP/1.1

Have you seen any clarification on this from the spec group.

FYI - Nice work on nghttp!

**Comment by tatsuhiro-t** [comment]
My understanding is that "Client that generate HTTP/2 request directly..." is meant for endpoint that generates requests for their own (e.g., web browser).   This excludes intermediaries which forward requests on behalf of upstream clients.
So web browser is a client that generate HTTP/2 request directly, so it use ":authority" and can omit host entirely.
OTOH, intermediaries forward HTTP/1 request with origin-form to HTTP/2 link, MUST omit ":authority" and use "host" header field.
