### ISSUE TITLE
Mismatched soname for libgrpc++

### ISSUE THREAD

**Issue by ahenriksson** [grpc/grpc#10299]
A symlink to libgrpc++.so.1.2.0 is [created in the Makefile](https://github.com/grpc/grpc/blob/eeb3b24f7ed2d2a560d94d7c87a5d99fb19d6e35/Makefile#L4141) with the name libgrpc++.so.1. However, the soname of this library is set to libgrpc++.so.3 on the line above. This causes programs linked with libgrpc++ to fail with the error
`./tests: error while loading shared libraries: libgrpc++.so.3: cannot open shared object file: No such file or directory`

Creating the symlink manually fixes the problem (but I haven't checked if grpc actually works). I'm using OpenSUSE Leap 42.2, with source from the 'v1.2.0' git tag.

Note: I know very little about sonames, so this could be completely wrong. :-)

**Comment by nicolasnoble** [comment]
Eep, yes, thanks for the report.

**Comment by sesse** [comment]
FWIW, there's the same problem for libgrpc++_cronet.so.

**Comment by llchan** [comment]
It seems that this issue is still present in other places in the [v1.3.1 Makefile](https://github.com/grpc/grpc/blob/v1.3.1/Makefile#L2597). I also checked master and it's still present there, with `libgrpc++.so.4` instead of `libgrpc++.so.3`. Can we make these use the vars so that they are guaranteed to match the soname?

**Comment by llchan** [comment]
There are several PRs addressing this issue (#13500, #11558, #10923, etc). Is there something fundamental blocking them from being merged? Happy to help if there's anything I can do, just seems redundant to open yet another PR.

**Comment by clemensg** [comment]
A month ago I created a PR (#16832) to fix the same error but got no response either. Now I see that I was not the only one who tried fixing it. Looks like nobody from the maintainers cares.. All issues and PRs are assigned to @nicolasnoble and then they rot..

**Comment by jtattermusch** [comment]
I just merged https://github.com/grpc/grpc/pull/16832 which should fix the problem. The good news is this we made it on time for the v1.17.x branch cut so the fix is going to be available in the v1.17.0 release (coming in about two weeks).

Sorry it took so long, we are trying our best to review things on time, but this time we really screwed up by failing to address 3 separate PRs for the same issue. I think partially the problem was coming from the fact that we are maintaining multiple build systems and each one is pretty complex (and requires a specific knowledge set that not everyone on the team has), so engineers on the team are careful in accepting build system changes (that have the potential to break lots of things and aren't always easy to test). We are thinking of how we can improve the process so things like this don't happen again.
