### ISSUE TITLE
Y U NO SQUASH PRS?

### ISSUE THREAD

**Issue by therc** [grpc/grpc#10363]
Trying to follow the gRPC commit history is a futile exercise. Sometimes a single PR has 10+ commits. That's a lot of noise. It also makes GH's release comparison feature a lot less useful, because this way you're much more likely to go over the limit of 250 commits max per diff.

Compare and contrast to the Kubernetes project, where reviewers are adamant (quite the understatement) about whole sets of changes getting rebased into one commit (or, rarely, two, and only for specific scenarios).

Can we have either a new policy of rebasing changes before merging? Or allowing squashing in the project's GitHub UI? See
https://github.com/blog/2141-squash-your-commits

**Comment by nicolasnoble** [comment]
I would agree that a series of commits such as {"testing this", "nope, didn't work, let's try that instead", "oh, typo", "nope, that was actually right"} is indeed noise. But having a single 10k loc commit isn't helping either. Some would actually rather point at the advantage of having more than one commit per PR as a plus in readability, in order to be able to decompose a heavy PR into multiple subcommits that are all logically divided, and proceed through the code review in a logical manner.

The current opinion I have, and the one I've been trying to preach around here, is to decompose commits to the order of {"fixing bug", "adding test for fix", "adding documentation for the fix"}.

But the fact of the matter is, this is more of a holy war discussion than an actual problem, akin to "vi vs emacs", and I don't believe this repository is a useful place to have it.

**Comment by therc** [comment]
Should I move this to the list, then? The 10K LOC example is probably the exception in Kubernetes that I was referring to. Kubernetes uses auto-generated code and it was checked in, until recently. It was customary, when an API definition change resulted in massive diffs in the autogen code, to have all of that in a commit of its own, while the changes in hand-written logic that dealt with the new spec would be a separate one. Similar exceptions are given for large refactoring changes, to make reviews easier under GH's horrible UI.

I disagree that this is a holy war. It's code hygiene like the Style Guide and it only takes a "decider" to make the call. Kubernetes is a much larger project than gRPC and, despite all of its growing pains, squashing has been the least troubles. This from the guy that has "I rebase code all the time" under "What I do" on the Kubernetes Slack. :-)

Personally, I do not care which policy gets picked (one commit, up to three, etc.), as long as there is one.
