### ISSUE TITLE
Building c-ares with vsprojects fails: ares_build.h not found

### ISSUE THREAD

**Issue by sagamusix** [grpc/grpc#10403]
When building grpc Git using the SLN provided in `vsprojects` using Visual Studio 2017, building the c-ares project fails, even after running `third_party/cares/cares/buildconf.bat` which generates `ares_build.h`. I think the issue might be that `ares_setup.h` uses angle brackets for including that file rather than quotes. Hopefully this should only be a matter of adding an include path for this file in the project settings.

**Comment by amarcionek** [comment]
I can confirm this issue. Adding _$(SolutionDir)\..\third_party\cares_ to the Additional Include Directories fixes it. However, then the file **ares_rules.h** is not found.  Adding _$(SolutionDir)\..\third_party\cares\cares_ to the Additional Include Directories fixes that as well.

**Comment by amarcionek** [comment]
I should also note that since the projects default to Treat Warnings As Errors (/WX) , I had to add the following to Disable Specific Warnings: 4996;4273. Since this is an external dependency, the warning can't be fixed unless c-ares is updated and used here. My understanding is there is a way to set certain warnings to be disabled in CMakeLists. I don't understand how, but it seems prudent to do so here.

**Comment by apolcyn** [comment]
At a glance, I think this may have been fixed by https://github.com/grpc/grpc/pull/10361
