### ISSUE TITLE
php: generated class name is case unmatched

### ISSUE THREAD

**Issue by flisky** [grpc/grpc#10424]
protoc --version: `libprotoc 3.2.0`

test proto:
```
syntax = "proto3";

package rpc.v1;

service svc {
  rpc test (requestMessage) returns (responseMessage) {}
}

message requestMessage {
  string field = 1;
}

message responseMessage {
  string field = 1;
}
```

`protoc --php_out=. --grpc_out=.` output:

```
└── Rpc
    └── V1
        ├── requestMessage.php
        ├── responseMessage.php
        └── svcClient.php
```

However,  svcClient requires `\Rpc\V1\RequestMessage` and `\Rpc\V1\ResponseMessage`

**Comment by ZhouyihaiDing** [comment]
The upper case is converted by the [grpc plugin](https://github.com/grpc/grpc/blob/d8feec29f54afb52a48b5a3025826570af85b0cb/src/compiler/php_generator.cc#L63).
I think this is because the [protobuf style guide](https://developers.google.com/protocol-buffers/docs/style) recommends use **CamelCase** for the message name.

**Comment by ZhouyihaiDing** [comment]
And also, the [psr coding style](https://www.php-fig.org/psr/psr-1/#1-overview) also suggests using CamelCase to define the class name.
