### ISSUE TITLE
Python install exception

### ISSUE THREAD

**Issue by ScARje** [grpc/grpc#10538]
"We could not diagnose your build failure. Please file an issue at http://www.github.com/grpc/grpc with `[Python install]` in the title."

[log.txt](https://github.com/grpc/grpc/files/908056/log.txt)

**Comment by nicolasnoble** [comment]
Compiling the python extension from source from Windows is pretty difficult at the moment, which is why we are providing binaries. The log doesn't show the command you ran, nor the architecture you're running this for. Could you please provide that information so we could understand why it's trying to build from source ?

@kpayson64 do we provide 32 bits python pre-compiled binaries for Windows ?

**Comment by kpayson64** [comment]
We provide both 32 and 64 bit Windows binaries.

If you are using an old version of pip, there is a good chance it will try to build from source.

I'd recommend trying ```pip install --upgrade pip``` and then try installing grpc.

**Comment by makdharma** [comment]
Closing this bug. @ScARje please reopen when you have more information.
