### ISSUE TITLE
Pre-compiled gem x86-linux contains 64 bit binary

### ISSUE THREAD

**Issue by sbrun** [grpc/grpc#10628]
Hello,
I tried to install and use Ruby grpc on i386 (with Kali Linux) but the pre-compiled gem x86-linux contains 64 bit binary:
```
gem install grpc
[...]
file /var/lib/gems/2.3.0/gems/grpc-1.2.2-x86-linux/src/ruby/lib/grpc/grpc_c.so 
/var/lib/gems/2.3.0/gems/grpc-1.2.2-x86-linux/src/ruby/lib/grpc/grpc_c.so: ELF 64-bit LSB shared object, x86-64, version 1 (SYSV), dynamically linked, BuildID[sha1]=47308a07a6d4cbc9e3e83f7e9aeccafc9348d3ed, not stripped
```

**Comment by nicolasnoble** [comment]
That's not the proper file. You should look at the subfolder for your version of ruby, which seems to be 2.3. The presence of that file you're pointing at is an unfortunate side-effect of ruby's weird compilation environment.

```
$ file src/ruby/lib/grpc/grpc_c.so  # wrong file
src/ruby/lib/grpc/grpc_c.so: ELF 64-bit LSB shared object, x86-64, version 1 (SYSV), dynamically linked, BuildID[sha1]=47308a07a6d4cbc9e3e83f7e9aeccafc9348d3ed, not stripped
$ file src/ruby/lib/grpc/2.3/grpc_c.so  # proper file
src/ruby/lib/grpc/2.3/grpc_c.so: ELF 32-bit LSB shared object, Intel 80386, version 1 (SYSV), dynamically linked, BuildID[sha1]=a1f5b63bd515f766ce897ee0667676cfc650bf1b, not stripped
```

**Comment by rhertzog** [comment]
Thanks @nicolasnoble , it looks like that you are right but this is the first gem that I see with this problem so I don't think that you can blame ruby only, you must be doing something non-conventional that result into this.

And this breaks some automatic Debian packaging system because it is unable to find the required x86-64 libraries on the i386 system where the gem is installed... which is what triggered us to file this bug.

At the very least you could possibly add some work-around rule in the build system that would remove the undesired file after build, no? Thanks for considering.

**Comment by nicolasnoble** [comment]
We literally have no control over the build system, really. This is a side-effect of rake-compiler, which is basically what provides pre-compiled binaries that works cross-platform. That's... how it works. You wouldn't see this otherwise, indeed.

What I am saying is that it's a single external command that builds all of the .so files for all the versions, drops that "default" one here, and then packages everything. We haven't done anything that would do that otherwise, and I have no idea how we could add any level of workaround into a single-command black-box build system.

**Comment by mehrdada** [comment]
We are trying to clean up the gRPC issue tracker and it seems like there is no actionable step to take on this issue at this point. Please feel free to re-open if there's a path forward on this issue; thanks!
