### ISSUE TITLE
Allow node grpc plugin to generate empty .js files when there are no services in .proto files

### ISSUE THREAD

**Issue by sayrer** [grpc/grpc#10646]
This would come in handy with my Bazel setup, because we have a mix of .proto files that may or may not have services in them.

If it's ok to make it an option, or to make it the default, I can write the patch.

**Comment by sayrer** [comment]
@murgatroid99 do you want to write this, or ok to submit a patch?

**Comment by haikalpribadi** [comment]
Just ran into this problem. I realise that this issue has been open for more than a year now. Any plans on fixing it, @grpc team?

**Comment by vmax** [comment]
@murgatroid99 
There's [`grpc/grpc-node`](https://github.com/grpc/grpc-node) repo, in which the issue is fixed yet it seems the plugin for node codegen is still vendored [in this repo](https://github.com/grpc/grpc/blob/master/src/compiler/node_generator.cc). How do I best approach using the fixed version?

**Comment by murgatroid99** [comment]
The newest version of the `grpc-tools` package now has this change.
