### ISSUE TITLE
Create vcpkg for C/C++ on Windows

### ISSUE THREAD

**Issue by jtattermusch** [grpc/grpc#10699]
Seems as a better alternative to NuGet packages: https://github.com/Microsoft/vcpkg

**Comment by Retik** [comment]
There is already a grpc package on vcpkg, it just needs to be updated to 1.2.x

**Comment by ras0219-msft** [comment]
I've pushed the update to 1.2.3 in Microsoft/vcpkg@75cdbd3.

We need the targets files that were removed in c019e05, so I locally revert that commit; I'm not sure where you'd like gRPC to be in the future w.r.t. cmake integration so if you intend to not provide it I'll remove the patch.

**Comment by kkm000** [comment]
This is an interesting topic. The biggest problem with NuGet native packages is that they are... well, big. I have a build script that patches CMakeFile (the recent going back and forth with gRPC_INSTALL did not cut it for packaging, unfortunately), runs CMake, builds and packages things for our internal use, even adding .props and  .targets and a XAML property sheet so that proto files become a first class citizen in Visual Studio when the package is imported into a project.

But. I am building only with VS2017 (aka toolset v141), only 64 bit, static libraries against dynamic CRT, and two configurations, Debug and Release. The whole packaged thing is about 220MB in size. Now, if you are shooting for a general use package, this has to be extended to 32-bit, and to other toolsets (since C++ ABI is entirely incompatible between Microsoft toolsets). It is possible to build C-only libraries against older toolsets and use them with the never ones though, and package only C++ libraries per toolset, but that would require a whole lot of tinkering, if not bending over backwards.

Building DLLs would maybe cut the size, but then there is less flexibility (with static libraries one can override default library spec and build against static CRT if they want). And I am not really sure how much space this would save.

Maybe a more practical solution would be building multiple packages, each for its own bitness and toolset? This will keep each at ~200MB, which is ok, but will probably confuse more users. Indeed, a package can (and should) include safeguards producing an error, and suggesting the correct package to be installed for user's build. NuGet is of no help downloading the "right" native package based on current project, as it can do for CLR projects. Everything is lumped under the "native" framework id.

I do not understand what exactly vcpkg does, but from my looking at the documentation, it seems that it builds libraries  from source. For gRPC this is not a good option (user needs perl, yasm, Go,...)

In any case, I've been there and done exactly that, and will be happy to contribute to this work, if the project decides to proceed with it. We have some crazily complex builds, and I have more experience than I would sometimes wish with MsBuild and the build system Microsoft created around it,

**Comment by jtattermusch** [comment]
Currently there's no ETA for this, we can reopen once we get to it.
