### ISSUE TITLE
Support for Android NDK

### ISSUE THREAD

**Issue by rolandomar** [grpc/grpc#10700]
Hi all,
Is there any support for Android NDK available or planned?

Thanks,
Rolando Martins

**Comment by makdharma** [comment]
It is neither available nor planned, but we have reports of C++ gRPC server and client working just fine when compiled with NDK toolchain.

**Comment by rolandomar** [comment]
Do you have any links/references to makefiles for compiling gRPC under NDK?

**Comment by makdharma** [comment]
@nicolasnoble has the best info on this topic.

**Comment by navidR** [comment]
Any bews on this?

**Comment by makdharma** [comment]
Hi - Compile with NDK is not officially supported, but known to work. Have you tried it?

**Comment by navidR** [comment]
Hi - Not yet, the thing is I am working on an official project for a small company so I want a project with official support for NDK in long term. Bad news to hear it does not support ndk officially, I really like it.

**Comment by makdharma** [comment]
You are welcome to contribute a pull request though.

**Comment by spinorx** [comment]
I got it to build with NDK.  See:  https://github.com/grpc/grpc/pull/13011 .  When run on device I get UNAVAILABLE (14) status code.

I am motivated to make it work on android with NDK since I want to share C++ common model between iOS and Android.  Any pointers to help debug this will be appreciated :)

**Comment by kt81** [comment]
Hi @spinorx .
I'm strongly interested in your work.
I would like to try it and will do debugging. Could you share the instructions to build it?

**Comment by Zomata** [comment]
@nicolasnoble @makdharma Could you give more information on how to compile gRPC using NDK?

**Comment by spinorx** [comment]
@kt81 @Zomata - https://github.com/spinorx/grpc_andr_ios  Has sample for both iOS and Android.

**Comment by ericgribkoff** [comment]
https://github.com/grpc/grpc/pull/14193 added an example gRPC C++ Android app: https://github.com/grpc/grpc/tree/master/examples/android/helloworld

**Comment by zpeleg** [comment]
Has anyone got grpc to work in a terminal executable on Android? We are trying to do that and getting linker failure because our executable is trying to use the system's protobuf instead of the statically compiled one (or vice versa, not sure).

We have posted more details on [SO](https://stackoverflow.com/questions/52203862/building-an-android-executable-grpc-server-that-uses-protocol-buffers-without-a).
