### ISSUE TITLE
Can't npm install grpc on raspberry pi 2

### ISSUE THREAD

**Issue by Vikaton** [grpc/grpc#10863]
![2017-04-26-165011_1261x884_scrot](https://cloud.githubusercontent.com/assets/9522710/25446499/b982877c-2a7f-11e7-8382-3e0b932a2c82.png)

I tried running `npm install grpc` and I get this error when the install process says its going to compile with node-gyp

Any help?

**Comment by murgatroid99** [comment]
We do not currently distribute ARM packages, and I don't know if the gRPC Node package builds on ARM. There should be more error output in above what's shown in your screenshot. If it's failing because you don't have a C compiler, you might be able to get a compiler/linker/etc. package and fix the problem. If it's failing because of a build error, you're probably out of luck.

**Comment by murgatroid99** [comment]
We have added experimental support for ARM processors (which Raspberry Pi uses) in gRPC 1.4.1. You may be able to install it on your Raspberry Pi. Please tell us if you have any further problems.
