### ISSUE TITLE
Confusion around use/guarantees of grpc.RpcError in Python

### ISSUE THREAD

**Issue by davechallis** [grpc/grpc#10885]
Modifying the Python `helloworld` example to add exception handling produces some confusing results.

Changing modifying the `run()` function from https://github.com/grpc/grpc/blob/master/examples/python/helloworld/greeter_client.py to

    def run():
      channel = grpc.insecure_channel('localhost:50051')
      stub = helloworld_pb2_grpc.GreeterStub(channel)
      try:      
        response = stub.SayHello(helloworld_pb2.HelloRequest(name='you'))
      except grpc.RpcError as err:
        print('Type:', type(err))
        print('Attributes:', dir(err))
      print("Greeter client received: " + response.message)

and then running the above client while the server is not running produces the following output:

    Type: <class 'grpc._channel._Rendezvous'>
    Attributes: ['__abstractmethods__', '__cause__', '__class__', '__context__', '__del__', '__delattr__', 
    '__dict__', '__dir__', '__doc__', '__eq__', '__format__', '__ge__', '__getattribute__', '__gt__', '__hash__', 
    '__init__', '__init_subclass__', '__iter__', '__le__', '__lt__', '__module__', '__ne__', '__new__', '__next__', 
    '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__setstate__', '__sizeof__', '__str__', 
    '__subclasshook__', '__suppress_context__', '__traceback__', '__weakref__', '_abc_cache', 
    '_abc_negative_cache', '_abc_negative_cache_version', '_abc_registry', '_call', '_deadline', '_next', 
    '_repr', '_response_deserializer', '_state', 'add_callback', 'add_done_callback', 'args', 'cancel', 
    'cancelled', 'code', 'details', 'done', 'exception', 'initial_metadata', 'is_active', 'next', 'result', 'running', 
    'time_remaining', 'traceback', 'trailing_metadata', 'with_traceback']

Looking at the source code for `RpcError`, it's defined as:

    class RpcError(Exception):
        """Raised by the gRPC library to indicate non-OK-status RPC termination."""

So I'm wondering a few things:

1. What is this `_Rendezvous` class, and where is it defined? It doesn't appear in the package documentation (http://www.grpc.io/grpc/python/search.html?q=Rendezvous). A lot of its attributes potentially look very useful, but I'm just guessing as to what they actually do or represent.

2. Are there any guarantees about which of these attributes will always be available when RpcError is caught? E.g. if I start relying on using `err.code()` to get the error type, are there other RpcError subclasses that can be raised which don't contain this attribute?

3. Is there a list of all the possible subclasses of RpcError that can be raised? (i.e. in case I'd want different exception handling for each).

I couldn't see anything in the examples or documentation, but basically, I'd like to use something like:

    try:
       # ... some gRPC call ...
    except grpc.RpcError as err:
        if err.code() == grpc.StatusCode.UNAVAILABLE:
            print('Service unavailable')
       # ... handling for different codes here ...

but this looks unsafe, since `RpcError` doesn't define any attributes (beyond those inherited from `Exception`). Currently I'm using the following code, but I'm hoping there's a better option:

    try:
        # ...some gRPC call ...
    except grpc.RpcError as err:
        code = err.code() if hasattr(err, 'code') else None
        if code == grpc.StatusCode.UNAVAILABLE:
            print('Service unavailable')
       # ... handling for different codes here ...

**Comment by nathanielmanistaatgoogle** [comment]
It's true that `grpc.RpcError` specifies no useful data or behavior, but what you're missing in the documentation is that [the exception raised out of an RPC invocation isn't just a `grpc.RpcError`; it's also a `grpc.Call`](http://www.grpc.io/grpc/python/grpc.html#grpc.UnaryUnaryMultiCallable.__call__). Therefore it is legitimate (and part of the intended use case) to use the object _raised out of an RPC invocation_ according to the `grpc.Call` interface that it implements. You may notice that the object presents a few other attributes that don't fit `grpc.RpcError` or `grpc.Call` as well - because these are not guaranteed by the system that raised the object to your system, they are not legitimate to call.

A much simpler example of this kind of specification-implementation would be a function that is specified to return a sequence and that has an implementation that returns a `list`. Callers of the function can call the method, introspect the returned value, see that it's a `list`, wonder why it wasn't documented as a `list`, use it according to the `list` type rather than the sequence type... and then see their code break when they update the function's library and the function's implementation changes from returning a `list` to returning some other sequence implementation. Proper implementation of a system that calls that function uses objects returned by the function only according to the sequence type that the objects are specified and guaranteed to implement.

**Comment by davechallis** [comment]
Perfect, thank you, knowing it's also a grpc.Call make things very clear.
