### ISSUE TITLE
Add MAINTAINERS file to list project leads

### ISSUE THREAD

**Issue by caniszczyk** [grpc/grpc#10893]
The CNCF expect projects to list their project leads via a MAINTAINERS or OWNERS file.

Can this be done for the main grpc/grpc project at least?

**Comment by jtattermusch** [comment]
CC @zinuga

**Comment by jtattermusch** [comment]
@caniszczyk   can you point us to MAINTAINERS file for some existing CNCF projects? (e.g. kubernetes doesn't have one).

**Comment by caniszczyk** [comment]
@jtattermusch that's because k8s was still finalizing it's governance, they are almost there

For now, I recommend looking at as examples:
https://github.com/prometheus/prometheus/blob/master/MAINTAINERS.md
https://github.com/fluent/fluentd/blob/master/MAINTAINERS.md
https://github.com/coredns/coredns/blob/master/MAINTAINERS

**Comment by bgrant0607** [comment]
A single file and a single role isn't adequate for large projects.

Markdown isn't friendly to automation. Kubernetes will likely use yaml rather than markdown.

I envision the following:

1. Extend our OWNERS files, which currently contain reviewers and approvers, to also include maintainers, admins, and other roles. This would be a per-repo mechanism.
2. Support sync'ing github teams (and perhaps org members and owners) from checked-in files, such as the OWNERS files. Github team memberships aren't transparent, auditable, etc.
3. Specify somewhere who comprises the top-level leadership body. This will be the Steering Committee in Kubernetes.

**Comment by jtattermusch** [comment]
Thanks for the insight, @bgrant0607. I quite like the idea of having OWNERS files. Do you have an automatized way to enforce the rules in OWNERS files (= PR not mergeable or check fails if no owner approval present)?

**Comment by caniszczyk** [comment]
@bgrant0607 @jtattermusch it really depends how complicated gRPC wants to get with its structure, I feel it's simpler than k8s so something like the new "CODEOWNERS" format from GitHub would actually work well: https://github.com/blog/2392-introducing-code-owners

**Comment by caniszczyk** [comment]
@jtattermusch you can take advantage of the new CODEOWNERS support in GitHub or use an external tool like PullApprove (https://about.pullapprove.com/) to enforce review before changes get merged in. I'm leaning towards CODEOWNERS since it's built into GitHub but I've yet to play with it extensively to fully vouch for it.

**Comment by ctiller** [comment]
I've added a fairly straight forward conversion from OWNERS files as specced at https://github.com/bkeepers/OWNERS to CODEOWNERS for GitHub.

Happy to play with the format down the track to better align with Kubernetes.

**Comment by ctiller** [comment]
Suspect this can be closed?

**Comment by jtattermusch** [comment]
@caniszczyk  is introducing the OWNERS files sufficient in terms of the CNCF MAINTAINERS.md requirement?  If so, we can close this issue.

**Comment by caniszczyk** [comment]
@jtattermusch yes, this meets the requirements
