### ISSUE TITLE
pylint_code.sh failing sanity, not actually fixing code

### ISSUE THREAD

**Issue by vjpai** [grpc/grpc#11046]
Please answer these questions before submitting your issue. 
 
### Should this be an issue in the gRPC issue tracker?

Yes 

### What version of gRPC and what language are you using?
 
gRPC at master, C++
 
### What operating system (Linux, Windows, …) and version?
 
Linux
 
### What runtime / compiler are you using (e.g. python version or version of gcc)
 
Python 2.7 

### What did you do?

tools/distrib/pylint_code.sh is reporting a sanity failure, but running it at the command line is not actually fixing anything.

```
$ tools/distrib/pylint_code.sh 
++ dirname tools/distrib/pylint_code.sh
+ cd tools/distrib/../..
+ DIRS=src/python/grpcio/grpc
+ VIRTUALENV=python_pylint_venv
+ virtualenv python_pylint_venv
New python executable in python_pylint_venv/bin/python
Installing setuptools, pip...done.
++ realpath python_pylint_venv/bin/python
+ PYTHON=/.../home/vpai/Git/grpc/python_pylint_venv/bin/python
+ /.../home/vpai/Git/grpc/python_pylint_venv/bin/python -m pip install pylint==1.6.5
Requirement already satisfied (use --upgrade to upgrade): pylint==1.6.5 in ./python_pylint_venv/lib/python2.7/site-packages
Cleaning up...
+ for dir in '$DIRS'
+ /.../home/vpai/Git/grpc/python_pylint_venv/bin/python -m pylint --rcfile=.pylintrc -rn src/python/grpcio/grpc
************* Module grpc
C: 69, 0: Line too long (111/100) (line-too-long)
+ exit 16
```

### What did you expect to see?
 
The code should have been fixed.

### What did you see instead?
 
A failure with exit code 16 and `git status` says that the code was not actually fixed.

**Comment by nathanielmanistaatgoogle** [comment]
While `pylint` is able to point out issues in code it's not smart enough to make fixes. That running it repeatedly yields the same output and doesn't change anything is expected.

`yapf` is the tool that we use to both detect _and fix_ formatting problems in code.

**Comment by vjpai** [comment]
Thanks @nathanielmanistaatgoogle , can I suggest that pylint suggests doing so on failure?

**Comment by nathanielmanistaatgoogle** [comment]
Suggests doing what, specifically? Editing the code to alleviate the problems it has found?

I also had a good sixty seconds wondering why it wasn't making the fixes you thought it should have, but then I remembered that `pylint` detects a wide range of issues (up to and including bugs) and figured it was just bad luck (and unverified documentation changes) that resulted in a formatting-complaints-only run.

**Comment by vjpai** [comment]
Suggests running the appropriate command and/or script to fix the problems that it has found. Right now, the output (as you saw above) doesn't even say which file to edit.

**Comment by nathanielmanistaatgoogle** [comment]
It did tell you both the file and line number at which it found a problem; it just told you in a Python-specific way. `pylint`'s assumption that its readers will be able to see "`Module grpc`" and translate it into "either a file named `grpc.py` at top-level or a file named `__init__.py` in a directory named `grpc`" is probably reasonable, and the fault is mine for using the tool where non-Python-reading engineers will see `pylint`'s output.

I'm not being snarky; it is a fault, but it's a tiny one and one not worth coding around (especially when we should be staying lint-clean rather than spending substantial time reading lint errors).

My apologies for the bump in the road. [Sanity rules](https://nbcprofootballtalk.files.wordpress.com/2015/04/homer.jpg)!
