### ISSUE TITLE
bazel cc_grpc_library not working as expected

### ISSUE THREAD

**Issue by fardream** [grpc/grpc#11176]
Hi,

I've been trying to use the cc_grpc_library rule for Bazel version 0.4.5 (which introduced the native proto_library support).
However, it looks like the document on the cc_grpc_library is different from what it is actually doing:
The document in bazel/cc_grpc_library.bzl mentions the following
```
  Arguments:
      srcs: a single proto_library, which wraps the .proto files with services.
```
In reality, this srcs is passed to native.proto_library's srcs argument, which requires a list of *.proto or *.protodevel
```
  native.proto_library(
      name = proto_target,
      srcs = srcs,
      deps = proto_deps,
      **kwargs
  )
```
Is this expected or this cc_grpc_library is not yet ready for projects outside gRPC?

Thanks

**Comment by nicolasnoble** [comment]
The semantic of the argument probably mutated without the associated documentation update, thanks for bringing that up. Since proto_library had issues with Bazel we had to change this around, indeed. Our goal eventually became to provide a replacement of proto_library, waiting for proper Bazel support.

In all cases, you should be able to use `grpc_proto_library` instead, and we should make sure this rule stays the same moving forward. It's supposed to be used as a replacement of `proto_library` and provides both the generation of the .pb.{cc,h} and .grpc.pb.{cc,h} files. You can see an example of that at the root of the example folder.
