### ISSUE TITLE
PHP: grpc.so: undefined symbol: pthread_once

### ISSUE THREAD

**Issue by SurferJeffAtGoogle** [grpc/grpc#11232]
### What version of gRPC and what language are you using?
 
Using PHP 5.6, and whichever version of gRPC is built by pecl.
 
### What operating system (Linux, Windows, …) and version?
 
Goobuntu 14.04 LTS

### What runtime / compiler are you using (e.g. python version or version of gcc)
 
```
$ pecl help version
PEAR Version: 1.10.1
PHP Version: 5.6.30
Zend Engine Version: 2.6.0
Running on: Linux rennie.mtv.corp.google.com 4.4.0-75-generic #96~14.04.1-Ubuntu SMP Thu Apr 20 11:06:30 UTC 2017 x86_64

$ gcc -v
Using built-in specs.
COLLECT_GCC=gcc
COLLECT_LTO_WRAPPER=/usr/lib/gcc/x86_64-linux-gnu/4.8/lto-wrapper
Target: x86_64-linux-gnu
Configured with: ../src/configure -v --with-pkgversion='Ubuntu 4.8.4-2ubuntu1~14.04.3' --with-bugurl=file:///usr/share/doc/gcc-4.8/README.Bugs --enable-languages=c,c++,java,go,d,fortran,objc,obj-c++ --prefix=/usr --program-suffix=-4.8 --enable-shared --enable-linker-build-id --libexecdir=/usr/lib --without-included-gettext --enable-threads=posix --with-gxx-include-dir=/usr/include/c++/4.8 --libdir=/usr/lib --enable-nls --with-sysroot=/ --enable-clocale=gnu --enable-libstdcxx-debug --enable-libstdcxx-time=yes --enable-gnu-unique-object --disable-libmudflap --enable-plugin --with-system-zlib --disable-browser-plugin --enable-java-awt=gtk --enable-gtk-cairo --with-java-home=/usr/lib/jvm/java-1.5.0-gcj-4.8-amd64/jre --enable-java-home --with-jvm-root-dir=/usr/lib/jvm/java-1.5.0-gcj-4.8-amd64 --with-jvm-jar-dir=/usr/lib/jvm-exports/java-1.5.0-gcj-4.8-amd64 --with-arch-directory=amd64 --with-ecj-jar=/usr/share/java/eclipse-ecj.jar --enable-objc-gc --enable-multiarch --disable-werror --with-arch-32=i686 --with-abi=m64 --with-multilib-list=m32,m64,mx32 --with-tune=generic --enable-checking=release --build=x86_64-linux-gnu --host=x86_64-linux-gnu --target=x86_64-linux-gnu
Thread model: posix
gcc version 4.8.4 (Ubuntu 4.8.4-2ubuntu1~14.04.3) 
```
 
### What did you do?

Followed instructions here:
https://github.com/grpc/grpc/tree/master/src/php

Ran `sudo /usr/local/bin/pecl install grpc` and it worked.  Updated php.ini, looking good until:

```
$ php
php: symbol lookup error: /usr/local/lib/php/extensions/no-debug-non-zts-20131226/grpc.so: undefined symbol: pthread_once
```
 
### What did you expect to see?

php not crash
 
### What did you see instead?
 
```
$ php
php: symbol lookup error: /usr/local/lib/php/extensions/no-debug-non-zts-20131226/grpc.so: undefined symbol: pthread_once
```

Make sure you include information that can help us debug (full error message, exception listing, stack trace, logs).

**Comment by stanley-cheung** [comment]
Can you run these two commands please?

```
ldd $(which php) | grep pthread
dpkg -l | grep pthread
```

**Comment by stanley-cheung** [comment]
Progress:
- The `ldd $(which php) | grep pthread` command returns nothing. That led me to think that somehow the 5.6.30 compiled PHP executable is not properly linked to `libpthread.so`
- I cannot reproduce the issue even if I used the exact same `.configure` command to compile 5.6.30 PHP myself. My `ldd` command returns this
```
$ ldd $(which php) | grep pthread
	libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007f73d1c5e000)
```

- I noticed a bit of discrepancy in the bug description. You have `--prefix=/usr/local/php` in your `.configure` command, but you mentioned that you ran `/usr/local/bin/pecl`. I found that with that `--prefix` clause, I have to run the `pecl` binary from `/usr/local/php/bin/php`. And that also installs the `grpc.so` extension to `/usr/local/php/lib/php/extensions/no-debug-non-zts-20131226/grpc.so`, instead of `/usr/local/lib/php/extensions/no-debug-non-zts-20131226/grpc.so` listed above. Not sure if they matter. Can you make sure you use the matching `pecl` binary to compile the `grpc` extension?

**Comment by SurferJeffAtGoogle** [comment]
How do I confirm it's the matching pecl?  There's no pecl in ls
/usr/local/php/bin
phar  phar.phar  php  php-cgi  php-config  phpdbg  phpize

**Comment by stanley-cheung** [comment]
User has resolved the issue. After re-compiling PHP, the `php` binary is now properly linked with `libpthread.so.0` so now the grpc extension is loaded without issue
