### ISSUE TITLE
Cannot build grpc.dll on Windows

### ISSUE THREAD

**Issue by KindDragon** [grpc/grpc#11261]
### What version of gRPC and what language are you using?
 gRPC 1.3.1
 
### What operating system (Linux, Windows, …) and version?
 Windows 10
 
### What runtime / compiler are you using (e.g. python version or version of gcc)
 Visual C++ 2015
 
### What did you do?
Try build vsprojects/grpc.sln (project grpc_dll)
 
### What did you expect to see?
`grpc_dll.dll` in output folder
 
### What did you see instead?
 Linker error:
```
grpc.def : error LNK2001: unresolved external symbol census_set_trace_mask
grpc.def : error LNK2001: unresolved external symbol census_trace_mask
grpc.def : error LNK2001: unresolved external symbol census_trace_print
grpc.def : error LNK2001: unresolved external symbol grpc_slice_buf_cmp
```
Because grpc source code only declare this symbols in `include\grpc`, but doesn't have implementation
 
### Anything else we should know about your project / environment?
Nope

**Comment by coryan** [comment]
Hey, any thoughts on when this would be fixed?  We would like to support DLL on Windows for the Google Cloud C++ Client Libraries (https://github.com/GoogleCloudPlatform/google-cloup-cpp)

**Comment by nicolasnoble** [comment]
I would heavily recommend against using gRPC as a DLL itself, since its API changes fairly often (see #15274 as an example), and DLL users are expecting a stable API.

Nonetheless, I'm surprised this is something still active, because it'd mean our ruby artifact build should be broken. I'm fairly certain we fixed duplicate issues. Are you sure this is still broken ?

**Comment by jozefizso** [comment]
Did you try to use the grpc lib from the [vcpkg](https://github.com/Microsoft/vcpkg)?

**Comment by coryan** [comment]
@jozefizso vcpkg explicitly disables dynamic linking:

https://github.com/Microsoft/vcpkg/blob/14708a09a9ade27dce3329ee8453a8a2724f94b6/ports/grpc/portfile.cmake#L2

**Comment by nicolasnoble** [comment]
With good reasons IMHO.

**Comment by coryan** [comment]
@nicolasnoble I am confused.  You say that the API changes fairly often, yet the blog post announcing 1.0 says you will use semantic versioning:

> Languages moving to 1.0 include C++, Java, .... they will follow semantic versioning from here."

https://grpc.io/blog/gablogpost

Which one is it?

Can you point me to the build that creates your ruby artifacts?  Maybe I am configuring things incorrectly because the steps I followed did not work.  It is also possible I missed the document describing how to build with shared libraries on Windows.

For what is worth, I did this:

```console
git clone -b v1.11.x https://github.com/grpc/grpc.git
cd grpc
git submodule update --init --recursive
cmake -H. -B.build -DBUILD_SHARED_LIBS=ON
cmake --build .build -- /m
```

That produces many errors, e.g.:

```console
       "C:\Users\coryan\source\grpc\.build\ALL_BUILD.vcxproj" (default target) (1) ->
       "C:\Users\coryan\source\grpc\.build\grpc++_error_details.vcxproj" (default target) (95) ->
       "C:\Users\coryan\source\grpc\.build\grpc_cpp_plugin.vcxproj" (default target) (96) ->
       "C:\Users\coryan\source\grpc\.build\grpc_plugin_support.vcxproj" (default target) (97) ->
         php_generator.obj : error LNK2019: unresolved external symbol "class std::basic_string<char,struct std::char_t
       raits<char>,class std::allocator<char> > __cdecl google::protobuf::compiler::php::GeneratedClassName(class googl
       e::protobuf::Descriptor const *)" (?GeneratedClassName@php@compiler@protobuf@google@@YA?AV?$basic_string@DU?$cha
       r_traits@D@std@@V?$allocator@D@2@@std@@PBVDescriptor@34@@Z) referenced in function "void __cdecl grpc_php_genera
       tor::`anonymous namespace'::PrintMethod(class google::protobuf::MethodDescriptor const *,class google::protobuf:
       :io::Printer *)" (?PrintMethod@?A0x883a4f3b@grpc_php_generator@@YAXPBVMethodDescriptor@protobuf@google@@PAVPrint
       er@io@45@@Z) [C:\Users\coryan\source\grpc\.build\grpc_plugin_support.vcxproj]
         C:\Users\coryan\source\grpc\.build\Debug\grpc_plugin_support.dll : fatal error LNK1120: 1 unresolved externals
        [C:\Users\coryan\source\grpc\.build\grpc_plugin_support.vcxproj]

    814 Warning(s)
    22 Error(s)
```

**Comment by nicolasnoble** [comment]
So, several things to say here. gRPC has two layers. The surface API which is in C++/Ruby/Python/NodeJS etc follows semantic versioning, and is still at version 1.0 If you are using C++, this code is in the library named "grpc++". And the internal or core layer is the layer that's being used by all these surface APIs. This one isn't meant to be used directly by the end user, and its API which is basically the glue between the core and all of the surface APIs changes frequently. This core library is called "grpc".

If you build "grpc.dll" you only get this core internal API, which isn't meant to be used directly by the end user. Additionally, C++'s lack of ABI means that using "grpc++.dll" safely is impossible.

The Ruby extension DLL is built from here: https://github.com/grpc/grpc/blob/master/Rakefile#L129 and bounces here: https://github.com/grpc/grpc/blob/master/Rakefile#L84

The point of this build is Ruby's build system is fairly out of whack, so our only option is to load the core API as a DLL inside of the Ruby extension. Otherwise we would link it statically, like we do with all the other languages. Nonetheless, it means the core DLL builds properly.


Now, more interestingly, the original bug was about the core grpc.dll not able to link properly - which as I said, is called "grpc.dll" and has been fixed a while back.

The small error snippet you pasted has nothing to do with "grpc.dll" - which still builds properly evidently due to the Ruby artifacts building. Since you haven't sent the whole list of errors, I can't say without reasonable doubt that issue is now a completely different one than the original issue being discussed here, but I highly suspect it.

**Comment by coryan** [comment]
Thanks. I have created #15333 to discuss the specific issue of building with shared libraries for C++ on Windows.

> Additionally, C++'s lack of ABI means that using "grpc++.dll" safely is impossible

I am not sure what you mean by that.  Do you mean that gRPC does not have a stable ABI for C++?  Again, that would contradict your promises to use semantic versioning.  Or you mean this as the fact that C++ the language does not define an ABI?

> Nonetheless, it means the core DLL builds properly.

If that is the case please consider closing this bug.

**Comment by nicolasnoble** [comment]
I mean that exposing C++ in a DLL is highly unadvisable. That's not just with gRPC, but with any project in general. Yes, this is tied to the language.

Let's continue this discussion in #15333.
