### ISSUE TITLE
how to change backoff parameters

### ISSUE THREAD

**Issue by sulliwane** [grpc/grpc#11277]
If my grpc server is down, and my client sends a series of 3 unary call, the first unary call fails instantly , the second fails only after 20 more seconds, and the third after another 20 more seconds.

Is this behavior the "[backoff behavior](https://github.com/grpc/grpc/blob/master/doc/connection-backoff.md)" described [on this page](https://github.com/grpc/grpc/blob/master/doc/connection-backoff.md) ?

## How to alter the backoff parameters from python client?

I tried these with no effect:
```python
    channel_args = (
        ('grpc.initial_reconnect_backoff_ms', 10000),
        ('grpc.max_reconnect_backoff_ms', 1000),
    )
    secure_channel = grpc.secure_channel(
        server_url,
        channel_creds,
        options=channel_args,
    )
```

Many thanks!

note: ubuntu 16.04, python 3.6, grpcio 1.3.0

**Comment by virusdefender** [comment]
+1 

I have the same issue

**Comment by dgquintas** [comment]
We have polished, and hopefully clarified, the backoff behaviour since this question was posed (in https://github.com/grpc/grpc/pull/13121 back in Nov 2017). The [documentation](https://github.com/grpc/grpc/blob/000ec4533d906ae7b9f8163871fcad72e8a4e1ac/doc/connection-backoff.md) was also updated. 

It should be easy, but admittedly a bit confusing, to explain the behaviour in light of the pseudocode algorithm in the documentation. Let me know if you have any issues doing so. Closing for now, but please reopen if necessary.
