### ISSUE TITLE
C# example fails to build on OSX

### ISSUE THREAD

**Issue by tbillington** [grpc/grpc#11549]
### What version of gRPC and what language are you using?

Tried both grpc [master](https://github.com/grpc/grpc/tree/6beba3c50e2ac9032da196b9bbf8b2f5484cb924) and `origin/v1.3.x` (specified by grpc.io) as of writing this issue 
 
### What operating system (Linux, Windows, …) and version?
 
OSX 10.12.5
 
### What runtime / compiler are you using (e.g. python version or version of gcc)
 
.NET Command Line Tools (1.0.4)
 
### What did you do?

Going through the tutorial at http://www.grpc.io/docs/quickstart/csharp.html#build-the-example

1. Cloned the repo.
2. `cd grpc/examples/csharp/helloworld-from-cli`
3. `git checkout origin/v1.3.x`
4. `dotnet restore`

Also tried the same steps with `master` branch, same result.

### What did you expect to see?
 
Not sure, probably not an error though :)
 
### What did you see instead?
 
```
MSBUILD : error MSB1003: Specify a project or solution file. The current working directory does not contain a project or solution file.
```
 
### Extra

I also tried the command that is to be done when `dotnet restore` succeeds: `dotnet build **/project.json`. The output from that was:

```
Microsoft (R) Build Engine version 15.1.1012.6693
Copyright (C) Microsoft Corporation. All rights reserved.

MSBUILD : error MSB1008: Only one project can be specified.
Switch: GreeterClient/project.json

For switch syntax, type "MSBuild /help"
```

**Comment by tania-m** [comment]
OS Version: MAC OS X 10.11.6
grpc version: master
Tooling: .NET Command Line Tools (1.0.4) 

Regarding the packages issue: With a clean install of the latest .Net Core version on, dotnet restore did work for me. Make sure Greeter.sln is present, and that Nuget works properly (can restore packages). Also try to empty any cache before restoring.

Regarding the compilation issue: project.json files are not needed anymore to build a dotNet Core project. "dotnet build" in hello-world-cli root is enough to get a built version !cf https://docs.microsoft.com/en-us/dotnet/core/tools/project-json-to-csproj).

**Comment by tbillington** [comment]
@tania-m How are you getting NuGet? I'm using the one provided by `dotnet nuget`.

Our setups look very similar.

**Comment by tania-m** [comment]
Nuget is the package manager for .Net stuff. It comes with the dotNet Core installation when you install it, so you should be all set with dotnet's nuget. 

Since I can't reproduce your issues, here some guesses/ideas about what to do:
- Check that the .sln and .csproj files are all where they should be when you try to restore. (What is bugging me is that you get a MSBUILD error).
- Try to run dotnet-restore in each subdirectory.
- Try to bypass caches: Remove any files that dotnet-restore might have gotten. Also remove any files that might have been added only locally ("clean the project") and run `dotnet-restore --nocache` (cf https://docs.microsoft.com/en-us/dotnet/core/tools/dotnet-restore)
- Make a clean install of DotNet Core's latest version on your Mac.

**Comment by jtattermusch** [comment]
I just verified that `dotnet restore` on branches master and v1.4.x works fine (assuming you have an up-to-date version of dotnet installed).

What you are seeing on v1.3.x branch is a symptom of missing and older version of dotnet SDK installed. Examples in v1.3.x are pre-csproj support (project.json style) examples, so in order to build them, you need the exact dotnet SDK version that is listed in global.json file - `1.0.0-preview2-003131`. If you don't have that version installed, dotnet SDK just ignores global.json (I think that's actually a dotnet SDK issue) and tries the default newest version of dotnet SDK installed - and the new versions of dotnet SDK don't support the project.json projects anymore - hence the error you are seeing. In v1.4.x (there'll be an official release very soon) you won't have this problem as the examples already use the new .csproj and .sln files.

```
# list installed dotnet SDK versions
ls /usr/local/share/dotnet/sdk/
1.0.0-preview1-002702	1.0.0-preview2-003121	1.0.1
```
