### ISSUE TITLE
Add a recursion limit during JSON parsing

### ISSUE THREAD

**Issue by newsoft** [grpc/grpc#11649]
Steps to repro:
```
$ make CONFIG=asan json_fuzzer_test_one_entry
$ python -c "print '['*140000" > /tmp/poc.json
$ bins/asan/json_fuzzer_test_one_entry /tmp/poc.json

ASAN:DEADLYSIGNAL
=================================================================
==16778==ERROR: AddressSanitizer: stack-overflow on address 0x7ffe4fdc7ff8 (pc 0x00000051862e bp 0x7ffe4fdc8010 sp 0x7ffe4fdc7f70 T0)
...    
SUMMARY: AddressSanitizer: stack-overflow
```
grpc_json_destroy() is recursively called over the 140,000 child nodes, and this makes ASAN unhappy. 

https://github.com/grpc/grpc/blob/master/src/core/lib/json/json.c#L34

There is no limit to the amount of '[' one can send, especially with the help of compression. I guess this would hit the stack guard page at some point and make the process crash.

Most parsers have hard-coded limits to avoid this kind of "bomb", should we consider adding some to the gRPC JSON parser?

**Comment by nicolasnoble** [comment]
Hmm, right, there's indeed a recursion point here in the destructor. No other location has something like that by the way. It's probably possible (if not desirable) to remove the recursion here. However this would only migrate the problem towards memory allocation instead of a call stack overflow.

Adding a limit on the size of the json tree is easily doable by starting to count the number of nodes into its root tree state: https://github.com/grpc/grpc/blob/master/src/core/lib/json/json_string.c#L40 - once json_create_and_link has reached a certain threshold, then no other link operation should take place, and json_reader_read_char should return GRPC_JSON_READ_CHAR_ERROR to fail the inner parser.
