### ISSUE TITLE
Metadata value; null-terminated vs. sized

### ISSUE THREAD

**Issue by soltanmm** [grpc/grpc#1167]
There's a lack of consensus on the treatment of null-bytes in metadata values as far as I can tell. There should be documentation [here](https://github.com/grpc/grpc/blob/master/include/grpc/grpc.h#L187) clarifying how the metadata should be treated.

Note that GRPC _appears_ to Do The Right Thing™ and respect the length for the metadata value when copying [here](https://github.com/grpc/grpc/blob/master/src/core/surface/call.c#L1184) (thus allowing null-bytes in the value). That such is not written anywhere as a guarantee isn't particularly comfortable.

And then there's what to do about metadata key [suffixes](https://github.com/grpc/grpc/blob/2e165e34010e44f20c6ecea63b20a6996810313f/src/core/transport/chttp2/bin_encoder.c#L276). The purpose of this should be documented.

**Comment by louiscryan** [comment]
The HTTP2 spec forbids null as a value in header values which is why we require that arbitrary binary sequences (including ones with nulls) are encoded as base-64 on the wire and use the '-bin' suffix on the header name.

Feel free to suggest clarification to 
https://github.com/grpc/grpc-common/blob/master/PROTOCOL-HTTP2.md

**Comment by soltanmm** [comment]
I don't think people should need to jump across repositories to get an idea of the semantics of our code.

**Comment by ctiller** [comment]
#554 should address this.
