### ISSUE TITLE
Jenkins has been hosed since the middle of last week

### ISSUE THREAD

**Issue by markdroth** [grpc/grpc#11851]
Jenkins has been seriously hosed since the middle of last week.  It is failing to run tests on PRs.

@nicolasnoble looked at this on Friday and indicated that it was due to the recent code-owners changes, which were triggering a huge number of github notifications to Jenkins, thus overloading it.  @jtattermusch looked at this morning and believed that it was a quota problem of some sort.

I don't know exactly what's going on, but I do know that we cannot merge PRs until this is fixed, so it's effectively blocking our development.  We need this fixed ASAP.

Some example PRs where tests are not running:

#11454
#11733 (although this one seems to be moving forward now that we manually asked Jenkins to test it)

We need to get back to a state where pushing commits to a PR always causes all tests to run.  Thanks!

**Comment by ctiller** [comment]
If this is a quota issue and we can catalogue which jobs are consuming quota, I'm happy to look through said list (with anyone else that's interested) and prioritize things so that we can disable some stuff temporarily.

**Comment by jtattermusch** [comment]
I am looking at Jenkins log https://grpc-testing.appspot.com/log/all
and it says:
```
Jul 17, 2017 10:17:10 AM INFO org.jenkinsci.plugins.ghprb.GhprbPullRequest updatePR
Pull request #11,454 was updated/initialized on grpc/grpc at 7/17/17 10:11 AM by Mark D. Roth (PR update)
```
so it seems to at least know about the PR change.

**Comment by matt-kwong** [comment]
Every few minutes, Jenkins logs show that all open pull requests are processed and non-test triggering changes are found. E.g.
```
Jul 17, 2017 12:51:09 PM INFO org.jenkinsci.plugins.ghprb.GhprbPullRequest updatePR
Pull request #7,588 was updated on repo grpc/grpc but there aren't any new comments nor commits; that may mean that commit status was updated.
```
These updates that are being sent to Jenkins from a GitHub webhook, and these irrelevant webhook events are blocking GitHub from sending relevant events. I'm investing the irrelevant events, which I suspect might be related to use recently adapting GitHub owners. 

I've temporarily switched from Jenkins watching GitHub webhook events to polling for changes. This looks like it's improving response time, but there is now a long queue of jobs that have not been triggered since this issue started last week.

**Comment by matt-kwong** [comment]
The culprit was likely found. Switching back to using webhooks to trigger tests and will continue to monitor logs for webhook spam.

**Comment by matt-kwong** [comment]
Switched back to polling; webhook events are still slow to process. It looks like the state of Jenkins is much better and responsive to PR creations/updates.
