### ISSUE TITLE
#define version number to indicate features, API, etc

### ISSUE THREAD

**Issue by vjpai** [grpc/grpc#11872]
Please answer these questions before submitting your issue. 
 
### Should this be an issue in the gRPC issue tracker?
 
Yes

### What version of gRPC and what language are you using?
 
C++
 
### What operating system (Linux, Windows, …) and version?
 
N/A
 
### What runtime / compiler are you using (e.g. python version or version of gcc)
 
N/A
 
### What did you do?

Tried writing code that would work in different versions of gRPC
 
### What did you expect to see?
 
Being able to know whether it would build/run statically

### What did you see instead?
 
They only way to tell gRPC version is through grpc::Version() so it has to be linked in

**Comment by dgquintas** [comment]
@vjpai still thinking this would be useful?

**Comment by kerrick-lyft** [comment]
This would be useful. For example, around version v1.9.1 (not sure the exact version), grpc/support/thd.h was moved to grpc/support/thd_id.h. If a project wants to support GRPC versions both before and after this change, they need some what to tell whether they should `#include <grpc/support/thd.h>` or `#include <grpc/support/thd_id.h>`. (Unfortunately, adding the `#define` now won't fix this problem because it has already happened, but will help in the future with issues like this).

**Comment by chwarr** [comment]
The need for this still exists, so I don't think this should be closed as stale.
WontFix or the like is appropriate if the determination is that this isn't something that is going to happen.

**Comment by stanley-cheung** [comment]
We acknowledge this to be a valid feature request but since no one has come forward to implement this, we are going to close it for now while maintaining the label/Help wanted to indicate that this can be picked up as future work.
