### ISSUE TITLE
--auto_set_flakes flakes True by default in run_tests.py?

### ISSUE THREAD

**Issue by jtattermusch** [grpc/grpc#11943]
Introduced in https://github.com/grpc/grpc/pull/11423

It looks like the `--auto_set_flakes` flag is always ON, even for master builds, which doesn't seem right.

Other problems:
-- it should somehow report which tests were marked as flaky (at least when requested)
-- because it's always on, it should work for Kokoro builds as well, which doesn't seem to be the case (I'm seeing the same flakes on kokoro over and over).

**Comment by jtattermusch** [comment]
CC @dgquintas

**Comment by adelez** [comment]
It works on Kokoro for Linux: https://sponge.corp.google.com/target?id=7d91db9b-b63a-408c-b594-440258cf2c4e&target=grpc/ubuntu/pull_request/grpc_c_asan&searchFor=&show=ALL&sortBy=STATUS
"Setting bins/asan/h2_full+pipe_test resource_quota_server GRPC_POLL_STRATEGY=epollsig to flaky
Setting bins/asan/h2_http_proxy_test resource_quota_server GRPC_POLL_STRATEGY=epollsig to flaky
Setting bins/asan/h2_census_nosec_test resource_quota_server GRPC_POLL_STRATEGY=poll to flaky"

It doesn't work on Kokoro for Win and Mac because the results are not saved to BQ yet. @matt-kwong said it should work on Windows and will turn it on shortly, but not on Mac because of permission problem.

**Comment by matt-kwong** [comment]
> It doesn't work on Kokoro for Win and Mac because the results are not saved to BQ yet. @matt-kwong said it should work on Windows and will turn it on shortly, but not on Mac because of permission problem.

Jan's recent PRs should enable flaky test detection for Windows. I plan to open PRs today to enable it for Macs.

> It looks like the --auto_set_flakes flag is always ON, even for master builds, which doesn't seem right.

I think we can just set `--auto_set_flakes` to `False` in master builds. This way, it's still enabled by default for when someone runs tests locally. If that sounds reasonable, I'll update Jenkins/Kokoro master builds.

> -- it should somehow report which tests were marked as flaky (at least when requested)

Would prefixing the test name with `(Flaky)` make sense? It'll help for when a flaky test fails all 5 runs, and a developer is trying to figure out if their code is causing the issue.
