### ISSUE TITLE
Request Blocked when sending large messages.

### ISSUE THREAD

**Issue by kdhee09** [grpc/grpc#12031]
Please answer these questions before submitting your issue. 
 
### What version of gRPC and what language are you using?
 C# .net core 2.0, grpc 1.4.1
 
### What operating system (Linux, Windows, …) and version?
 Windows 7
 
### What runtime / compiler are you using (e.g. python version or version of gcc)
 VS2017 
 
### What did you do?
When call "GetFeature3" and return is started.
Another client Request is blocked(ex.GetFeature). until finish the "GetFeature3"
Is there a problem with this code?

public override Task<Feature> GetFeature(Point request, ServerCallContext context)
{
    Feature result = new Feature { Name = "", Location = request };
    System.Console.WriteLine("GetFeature return start");

    return Task.FromResult(result);
}

public override async Task<TestByte> GetFeature3(Test request, ServerCallContext context)
{
	// "test.zip" 1GB file
    string filename = "test.zip";
    TestByte result = new TestByte();
    byte[] temp = null;

    using (FileStream SourceStream = File.Open(filename, FileMode.Open))
    {
        temp = new byte[SourceStream.Length];
        await SourceStream.ReadAsync(temp, 0, (int)SourceStream.Length);
    }

    result.Message = pb.ByteString.CopyFrom(temp);
    System.Console.WriteLine("GetFeature3 return start");

    return result;
}
 
### What did you expect to see?
 Another request("GetFeature") should be not hang.

**Comment by ProLoDs** [comment]
Hi,
protobuf or grpc is not made for large data transmission. 
Chunking the file into smaller parts is the way to go. 
Greetings

**Comment by kdhee09** [comment]
Thanks. i will try chunking.

**Comment by apolcyn** [comment]
Want to mention that you should still be capable of sending a large messages though - what's seen here should be avoidable.

In grpc C# releases so far (note this will change in the next release), I/O polling and user callbacks run on the same threads - so user callbacks should avoid synchronous blocking and offload CPU intensive work to separate threads, otherwise a sort of deadlock can happen - I suspect that the second RPC just happening to land on the same server-side thread as the first one (which is taking some time).

But note in the next release (as of https://github.com/grpc/grpc/pull/11930), user callbacks won't run on the same threads as the one's polling I/O - I suspect that what's seen here could be fixed in the next release.

**Comment by apolcyn** [comment]
^ on a closer look, there might be nothing that can be done differently with the user callback to avoid that if response marshaling is what's taking a long time - but still I think #11930 could fix this.

**Comment by kdhee09** [comment]
Thank you for the clear answer.

I hope it is fixed.

**Comment by zamber** [comment]
@kdhee09 is this still reproducing for you?

**Comment by dheekim-sgs** [comment]
I tested it today on 1.7.1.
This problem has been fixed.
Thank you.

**Comment by kdhee09** [comment]
I tested it today on C# .net core 2.0, grpc 1.7.1.
This problem has been fixed.
Thank you.
