### ISSUE TITLE
Homebrew gRPC package

### ISSUE THREAD

**Issue by nathanielmanistaatgoogle** [grpc/grpc#1210]
@jgeewax recommends that installing gRPC be as simple as `sudo brew install grpc`.

**Comment by tbetbetbe** [comment]
I have a WIP gRPC brew here: https://github.com/tbetbetbe/homebrew-grpc

**Comment by jcanizales** [comment]
Tim, someone pinged @louiscryan with a brew they had created for protoc, but I can't find the issue. Are you aware / coordinating with that guy?

**Comment by tbetbetbe** [comment]
FYI: the WIP homebrew repo has moved into the grpc org as is ready for testing: grpc/homebrew-grpc#11. The repo also contains an install script that installs the grpc python, ruby and nodejs packages.

Until gRPC reaches 1.0 and protobuf v3 leave alpha, we'll be maintaining the formula in the custom repo rather than submitting it officially.

**Comment by chai2010** [comment]
+1

**Comment by ctiller** [comment]
@a11r, @jayantkolhe - should this be Beta?

**Comment by tbetbetbe** [comment]
Closing this, it's resolved
- we will be maintaining gRPC in our own homebrew tap
- [taps](https://github.com/Homebrew/homebrew/blob/master/share/doc/homebrew/brew-tap.md) are a formal way of providing homebrew packages, and are easier for us to maintain than having the brew in the main homebrew repo
- because of the lack of predictability around protobuf releases (the key gRPC dependency), the tap will likely always be necessary
