### ISSUE TITLE
"h2_http_proxy_test max_concurrent_streams" end2end test does not work with epoll1

### ISSUE THREAD

**Issue by sreecha** [grpc/grpc#12201]
Repro:
The following will fail (after a few successful runs).

`tools/run_tests/run_tests.py -lc -cdbg -r "h2_http_proxy_test max_concurrent_streams" --force_use_pollers=epoll1 -ninf -S`

(Note: `force_use_pollers` option will be enabled once the PR https://github.com/grpc/grpc/pull/11936 is merged)

---

**Root cause**:
file: `test/core/end2end/tests/max_concurrent_streams.c`
Function: `test_max_concurrent_streams`

## max_concurrent_streams test: ##
1. Server: Request one call(tag 101) 
2. Client: call_start_batch for the following 4 batches 
   - Call 1
     -- Batch 1:  OP_SEND_INITIAL_METADATA,  OP_SEND_CLOSE_FROM_CLIENT  (tag 301) 
     -- Batch 2:  OP_RECV_STATUS_ON_CLIENT, OP_RECV_INITIAL_METADATA    (tag 302) 
    - Call 2
     -- Batch 1:  OP_SEND_INITIAL_METADATA, OP_SEND_CLOSE_FROM_CLIENT  (tag 401) 
     -- Batch 2: OP_RECV_STATUS_ON_CLIENT, OP_RECV_INITIAL_METADATA     (tag 402) 
 3. Call **completion_queue_next** in a loop until either 301 or 401 (but NOT both - because that would be a bug - max concurrent streams is set to “1”) and 101 is complete. 

**_Let us assume 301 (client sent call 1) and 101 (server received call 1) is complete_**
4. Server does call_start_batch with:  (tag 201) 
    - OP_SEND_INITIAL_METADATA 
    - OP_RECV_CLOSE_ON_SERVER and 
    - OP_SEND_STATUS_FROM_SERVER 

5. Call **completion_queue_next** (via cq_verify() helper) and expect tags **102** (_server finished call 1_), **302** (_client finished call 1_) and **401** (_client started call 2_) to complete 
6. Server request another call  (tag **201**) 
7. Server does call_start_batch with:  (tag **202**) 
    - OP_SEND_INITIAL_METADATA 
    - OP_RECV_CLOSE_ON_SERVER and 
    - OP_SEND_STATUS_FROM_SERVER 
8. Call **completion_queue_next** (via cq_verify helper) and expect tags **201** (_server received call 2_), **202** (_server finished call 2_) and **402** (_client finished call 2_) to complete 
  
## What is the failure?: ##
After step 4 but before step 5, the following happens in **some cases** where http2 proxy thread is making progress in the background even though we are not calling **completeion_queue_next** in max_concurrent_streams test:
 - Server sends the batch (**201**) 
 - Client receives server status for call 1 and finishes call 1 (tag **302**) 
 - Client starts Call 2 (tag **401**) 
 - Server receives the call 2 and starts parsing it 
    - Server has not released the first stream yet.. Therefore rejects the second stream with max-concurrent-streams error. 
- Client receives the closure and hence Call 2 batches (**401** and **402**) both complete (with a status of stream cancelled)

**Comment by markdroth** [comment]
This analysis looks plausible to me.  However, neither the `h2_http_proxy` fixture (which I wrote) nor the `max_concurrent_streams` test (which I did not write) seem to be making logically bad assumptions; it's just that the epoll1 code is tickling them in a way that they aren't working in combination.

Also, even if we decided that the `h2_http_proxy` code was somehow at fault, I'm not sure what can be done to fix it.  The proxy code needs to do polling, and that polling needs to happen in a different thread; there is simply no way to avoid that with this code.  The only alternative I can see would be to completely replace the current proxy code with an external proxy binary (e.g., maybe run some python implementation in the port server binary).  But it would be a shame to have to do that, because the `h2_http_proxy` fixture has historically helped us identify timing-related problems in the past, and we'd lose that signal if we replaced it.

I suggest that you talk to whoever wrote the `max_concurrent_streams` test to see if there's a way to change that particular test to avoid the problem.

**Comment by sreecha** [comment]
Yes, neither the proxy fixture nor the test is making unreasonable assumptions. 

The problem here is that the proxy fixtures (not just h2_http_proxy,the other proxy fixtures too), are assuming that their pollsets are isolated from the tests' pollsets. This was an incorrect assumption - even though it was true until epoll1..

Looking at [gen_build_yaml.py](https://github.com/grpc/grpc/blob/master/test/core/end2end/gen_build_yaml.py), i see that every fixture has a `includes_proxy` attribute (default `False`) and every test has a `proxyable` attribute which if set to `False` will not run the test against proxy fixtures.

`h2_http2_proxy` does not have `includes_proxy = True`.  I thought this was ok since unlike other proxies, the http proxy works transparently without the client/server's knowledge (and thereby should work with every test). 

- May be we should set `include_proxy` to `True` for `h2_http_proxy` ? 
- `max_concurrent_streams` test could be rewritten (i think..haven't put thought in to it) but unfortunately I do not have time at the moment to do this in a reasonable timeframe. I will ask around if someone can take this ..

**Comment by markdroth** [comment]
I don't think it makes sense to apply the same attribute for a gRPC-level proxy as for a TCP-level proxy.  They are two totally different things, and just because something will not work with a gRPC-level proxy does not mean that it won't work with a TCP-level proxy (as evidenced by all of the tests that currently run in `h2_http_proxy` but not in `h2_proxy`).

**Comment by sreecha** [comment]
makes sense. I'll ask someone else to work on fixing `max_concurrent_streams` test

**Comment by yashykt** [comment]
This does not seem like a bug in the max_concurrent_test, but instead it seems like a bug on the server side. Currently, the server closes the stream due to there being no more streams available, which should not be the case since the previous stream should be closed and removed by the server at this point.

**Comment by yashykt** [comment]
Fixed in #12463
