### ISSUE TITLE
C#: Support CancellationToken in IAsyncStreamReader.MoveNext()

### ISSUE THREAD

**Issue by mamaso** [grpc/grpc#12355]
Using Grpc.Core 1.4.1

MoveNext does not support cancellation, even though cancellation tokens are accepted as a parameter, which makes it more difficult than necessary to gracefully exit a streaming call on server shutdown:

```c#
public override async Task EventStream(IAsyncStreamReader<StreamingMessage> requestStream, IServerStreamWriter<StreamingMessage> responseStream, ServerCallContext context)
{
  // immediately throws InvalidOperationException 'Cancellation of individual reads is not supported.'
  while(await requestStream.MoveNext(context.CancellationToken))) {
  ...
  } 
}
```

In order to handle cancellation, I need a wrapper like:
```c#
var cancelSource = new TaskCompletionSource<bool>();
context.CancellationToken.Register(() => cancelSource.SetResult(false));

Func<Task<bool>> messageAvailable = async () => {
  var requestTask = requestStream.MoveNext(CancellationToken.None);
  var completed = await Task.WhenAny(cancelSource.Task, requestTask);
  return completed.Result;
}

while(await messageAvailable()) {
...
}
// ensure not leaking tasks
cancelSource.TrySetResult(false);
```

**Comment by jtattermusch** [comment]
On hard server shutdown (server,KillAsync()) all pending calls will be cancelled, which will result in cancelling all their active operations.

For soft server shutdown (server.ShutdownAsync()), all existing calls will continue to be handled normally but no new calls will be accepted.

**Comment by jskeet** [comment]
I've just run into this from a client-side perspective. Not supporting cancellation for an async call that can block for arbitrary amounts of time is *really* unfortunate IMO.

It also makes it impossible to use cleanly with a lot of the LINQ support in System.Interactive.Async. The situation I have is that I'd like to wrap the `IAsyncStreamReader<T>` (which derives from `IAsyncEnumerator<T>` in an `IAsyncEnumerable<T>` so that I can use `Select`, `Where` etc. I can perform the wrapping easily with `AsyncEnumerable.Create`, but the core of Rx passes a cancellation token to `MoveNext` even if the caller doesn't, so that if the iterator is disposed, any current `MoveNext()` call can be cancelled. Obviously, this doesn't work with gRPC.

I understand the reasoning behind "If you want to cancel the read, cancel the whole call" - but the piece of code responsible for the overall call isn't necessarily the same code that's responsible for each call to MoveNext.

I think it would be much cleaner if the whole call were automatically cancelled if the cancellation token passed to `MoveNext()` were cancelled. (And yes, `MoveNext()` would still fail if the cancellation token passed to the original call were cancelled, too.)

**Comment by jskeet** [comment]
Relevant Rx code: https://github.com/Reactive-Extensions/Rx.NET/blob/96ecc4309716813ff6479601fdf68100e18e2dce/Ix.NET/Source/System.Interactive.Async/AsyncIterator.cs#L35

I *may* be able to work around all of this using linked token sources, but it's going to be really painful to do, and would be better done in gRPC, I think.

**Comment by jtattermusch** [comment]
I will look into the possibility of allowing a cancellable token as MoveNext argument and cancelling the entire call if MoveNext's cancellationToken gets cancelled.

**Comment by jtattermusch** [comment]
Support has been added in #12822.
