### ISSUE TITLE
cmake: Doing "install" on Windows does not install important files

### ISSUE THREAD

**Issue by mdyring** [grpc/grpc#12384]
Please answer these questions before submitting your issue. 
 
### Should this be an issue in the gRPC issue tracker?
Yes
 
### What version of gRPC and what language are you using?
Tried v1.4.7 and v1.6.0
 
### What operating system (Linux, Windows, …) and version?
 Windows 10
 
### What runtime / compiler are you using (e.g. python version or version of gcc)
 Visual Studio 2015
 
### What did you do?
cmake -GNinja -DCMAKE_INSTALL_PREFIX="%INSTALL_PREFIX%" -DCMAKE_BUILD_TYPE=release -DgRPC_MSVC_STATIC_RUNTIME=ON .
cmake --build . --target install
	
### What did you expect to see?
Libs, binaries and header files installed under the specified prefix. 
  
### What did you see instead?
Only partial install. 

Few examples of things missing: 
bin\grpc_*_plugin.exe (so. all plugins)
lib\grpc++.lib
lib\grpc.lib
lib\gpr.lib

However some things turned up where expected:
lib\libprotobuf.lib
lib\zlib.lib
include\grpc++\grpc++.h

**Comment by mdyring** [comment]
As a side note, it doesn't appear that grpc++ is built for the install target either

**Comment by mdyring** [comment]
Side note #2: crypto.lib and ssl.lib from boringssl are not installed either.

I receive the warning below, perhaps this is related.. But AFAICT I am following the guidelines for Windows builds.

CMake Warning at CMakeLists.txt:120 (message):
  gRPC_INSTALL will be forced to FALSE because gRPC_ZLIB_PROVIDER is "module"

**Comment by jtattermusch** [comment]
Installing using cmake is currently work-in-progress, but one things you need to do it to use
gRPC_ZLIB_PROVIDER, gRPC_SSL_PROVIDER and gRPC_CARES_PROVIDER to =package (after installing them separately to you prefix path) - that's something you've been warned about by the message: `gRPC_INSTALL will be forced to FALSE because gRPC_ZLIB_PROVIDER is "module"`

gRPC should not install the third_party libraries for you as part of "grpc install" (and it actually cannot do that, because cmake prevents installing targets from subdirectories). We will update the documentation once the necessary steps on windows are tested (we just added similar test for linux: see https://github.com/grpc/grpc/blob/master/test/distrib/cpp/run_distrib_test_cmake.sh for the steps to install on linux - windows is going to be similar).

**Comment by mdyring** [comment]
Since they are included as submodules and built alongside gRPC, personally I'd expect to see a working build (including third party dependencies) in the install directory.

But if that is not possible with cmake, I thank you for the hint and will try to build/install the third_party libs separately. :-)

Should I open a new issue re. "it doesn't appear that grpc++ is built for the install target either"?

**Comment by jtattermusch** [comment]
@mdyring  I think we are aware of the problem with cmake install. The best thing we can do is to come up with a test that tries to do cmake install and builds helloworld subsequently. That's the only way to ensure that cmake will continue working as expected without someone constantly needed to check it.

Adding such test is in my work queue, but I have some higher priority things right now, so there's no ETA unfortunately.

**Comment by aajtodd** [comment]
So I hit this issue as well. I tried mirroring the script for Linux to build all the third party dependencies first then build gRPC. However then I hit #11616 and/or #12230. (I was building 1.6.0 so the fix for 12230 was not available). 

I started with visual studio 15 generator then switched to Ninja to see if it got any further (it did not although it seems to install the grpc headers at least).

Starter script is below if it helps anyone. Boringssl is commented out because as far as I can tell it has no install target. 


```bat
@echo on

setlocal

if "%1" == "" goto usage

:check_platform
if /i %1 == x86       goto x86
if /i %1 == amd64     goto amd64
if /i %1 == x64       goto amd64
goto usage

:x86
set PREFIX="C:\opt (x86)\grpc"
REM set GENERATOR="Visual Studio 14 2015"
REM set INSTALLTARGET=INSTALL
REM set EXTRA_BUILDARGS="-- /maxcpucount"
set GENERATOR="Ninja"
set INSTALLTARGET=install
set EXTRA_BUILDARGS=


goto build_third_party

:amd64
set PREFIX="C:\opt\grpc"
REM set GENERATOR="Visual Studio 14 2015 Win64"
REM set INSTALLTARGET="INSTALL"
REM set EXTRA_BUILDARGS="-- /maxcpucount"
set GENERATOR="Ninja"
set INSTALLTARGET=install
set EXTRA_BUILDARGS=


goto build_third_party

:build_third_party
set BUILDDIR="build-%1"

REM Install c-ares
cd third_party/cares/cares
git fetch origin
git checkout cares-1_13_0
if %errorlevel% neq 0 exit /b %errorlevel%
mkdir -p %BUILDDIR%
cd %BUILDDIR%
cmake -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=%PREFIX% -G%GENERATOR% ..
if %errorlevel% neq 0 exit /b %errorlevel%
cmake --build . --config Release %EXTRA_BUILDARGS%
if %errorlevel% neq 0 exit /b %errorlevel%
cmake --build . --target %INSTALLTARGET% --config Release
if %errorlevel% neq 0 exit /b %errorlevel%
cd ../../../..
REM wipe out to prevent influencing the grpc build
rm -rf third_party/cares/cares

:build_zlib
REM Install zlib
cd third_party\zlib
mkdir -p %BUILDDIR%
cd %BUILDDIR%
cmake -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=%PREFIX% -G%GENERATOR% ..
if %errorlevel% neq 0 exit /b %errorlevel%
cmake --build . --config Release %EXTRA_BUILDARGS%
if %errorlevel% neq 0 exit /b %errorlevel%
cmake --build . --target %INSTALLTARGET% --config Release
if %errorlevel% neq 0 exit /b %errorlevel%
cd ../../..
REM wipe out to prevent influencing the grpc build
rm -rf third_party/zlib

:build_protobuf
REM Install protobuf
cd third_party\protobuf
mkdir -p %BUILDDIR%
cd %BUILDDIR%
cmake -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=%PREFIX% -Dprotobuf_BUILD_TESTS=OFF -G%GENERATOR% ..\cmake
if %errorlevel% neq 0 exit /b %errorlevel%
cmake --build . --config Release %EXTRA_BUILDARGS%
if %errorlevel% neq 0 exit /b %errorlevel%
cmake --build . --target %INSTALLTARGET% --config Release
if %errorlevel% neq 0 exit /b %errorlevel%
cd ../../..
REM wipe out to prevent influencing the grpc build
rm -rf third_party/protobuf

REM :build_boringssl
REM cd third_party\boringssl
REM mkdir -p %BUILDDIR%
REM cd %BUILDDIR%
REM cmake -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=%PREFIX% -G%GENERATOR% ..
REM if %errorlevel% neq 0 exit /b %errorlevel%
REM cmake --build . --config Release %EXTRA_BUILDARGS%
REM if %errorlevel% neq 0 exit /b %errorlevel%
REM cmake --build . --target %INSTALLTARGET% --config Release
REM if %errorlevel% neq 0 exit /b %errorlevel%
REM cd ../../..
REM REM wipe out to prevent influencing the grpc build
REM rm -rf third_party/boringssl
REM goto :eof

:build_grpc
REM Install gRPC
mkdir -p %BUILDDIR%
cd %BUILDDIR%
cmake -DCMAKE_BUILD_TYPE=Release -DCMAKE_PREFIX_PATH=%PREFIX% -DCMAKE_INSTALL_PREFIX=%PREFIX% -DgRPC_INSTALL=ON -DgRPC_PROTOBUF_PROVIDER=package -DgRPC_ZLIB_PROVIDER=package -DgRPC_CARES_PROVIDER=package -DgRPC_SSL_PROVIDER=package ..
if %errorlevel% neq 0 exit /b %errorlevel%
cmake --build . --config Release %EXTRA_BUILDARGS%
if %errorlevel% neq 0 exit /b %errorlevel%
cmake --build . --target INSTALL --config Release
if %errorlevel% neq 0 exit /b %errorlevel%

goto :eof

:usage
echo Error in script usage. The correct usage is:
echo     %0 [option]
echo
echo where [option] is: x86 ^| amd64
echo 
echo For example:
echo     %0 x86
echo     %0 x64
goto :eof
```

**Comment by jtattermusch** [comment]
As explained in #13841, the problems you are seeing are due to an incorrect use of cmake (gRPC_*_PROVIDER needs to be set to "package").

@aajtodd 's script seems correct (thanks!), here's the version of a script we are using ourselves to testing installation gRPC using cmake on windows: https://github.com/grpc/grpc/blob/2b0ab320c12cb807cf05b3295b7017d0ccbf66f5/test/distrib/cpp/run_distrib_test_cmake.bat#L57

**Comment by jtattermusch** [comment]
I've verified that all the files you are mentioning are being installed correctly  once the cmake file is used correctly (see comments above). So I'll close this issue (but we will continue trying to make the cmake install process more intuitive).
