### ISSUE TITLE
grpc not define PROTOBUF_USE_DLLS [MSVC, BUILD_SHARED_LIBS]

### ISSUE THREAD

**Issue by KindDragon** [grpc/grpc#12424]
### Should this be an issue in the gRPC issue tracker?
 
Yes
 
### What version of gRPC and what language are you using?
 
 1.6.0 C++

### What operating system (Linux, Windows, …) and version?
 
 Windows 10

### What runtime / compiler are you using (e.g. python version or version of gcc)
 
MSVC2017
 
### What did you do?

I am trying to build protobuf and grpc with BUILD_SHARED_LIBS=1
 
### What did you expect to see?
 
I want to get grpc.dll
 
### What did you see instead?
 
grpc compilation failing because of missed compiler define `PROTOBUF_USE_DLLS`

You can use instead CMake targets `protobuf::libprotobuf-lite`, `protobuf::libprotobuf`, `protobuf::libprotoc`, `protobuf::protoc` to solve this issue. They automatically define `PROTOBUF_USE_DLLS` when needed.

**Comment by jtattermusch** [comment]
This might still be an issue?

**Comment by KyleFromKitware** [comment]
As far as I can tell, the source files are indeed being compiled with `-DPROTOBUF_USE_DLLS`. However, I am seeing the following, which may or may not be related:

```
LINK : fatal error LNK1104: cannot open file 'grpc_plugin_support.lib'
```

**Comment by jtattermusch** [comment]
Let's verify that gRPC builds fine on Windows with BUILD_SHARED_LIBS=ON  (and include the commands ran here). Once we check that, we can close this issue. Otherwise let's investigate why the build is broken.

**Comment by KyleFromKitware** [comment]
A number of link errors are happening because of symbols not being visible in the `.lib` file. Setting `CMAKE_WINDOWS_EXPORT_ALL_SYMBOLS` helps with this, but `upb` and `grpc_core` are still failing to expose a few things that are needed. I'm investigating why right now.

**Comment by KyleFromKitware** [comment]
In both cases, the unresolved symbols are variables rather than functions/methods. I can't say exactly why the link resolution is failing, but typically, the way to make this work is to use `__declspec(dllexport)` and `__declspec(dllimport)` to expose symbols across the DLL barrier. CMake provides a very nice module, [`GenerateExportHeader`](https://cmake.org/cmake/help/latest/module/GenerateExportHeader.html), to automate this process, but of course that won't work when building with Bazel.

Adding this is certainly possible, but non-trivial. It will involve auditing which symbols we want to expose across the DLL boundary.
