### ISSUE TITLE
cmake build c++ Helloworld failed

### ISSUE THREAD

**Issue by pekof** [grpc/grpc#12442]
Tried to build c++ Helloworld on windows and linux both failed.

Found Protobuf: D:/2test/git/vcpkg/installed/x86-windows-static/tools/protoc.exe (found version "3.4.0") 
Using protobuf 3.4.0
Using gRPC 1.4.1
CMake Error at D:/2test/git/vcpkg/installed/x86-windows-static/share/protobuf/protobuf-config.cmake:79 (message):
  Error: protobuf_generate could not find any .proto files
Call Stack (most recent call first):
  D:/2test/git/vcpkg/installed/x86-windows-static/share/protobuf/protobuf-module.cmake:19 (protobuf_generate)
  CMakeLists.txt:25 (protobuf_generate_cpp)

**Comment by bonezhang** [comment]
@nathanielmanistaatgoogle   hi, has this issue fixed?  thanks.

**Comment by nathanielmanistaatgoogle** [comment]
@bonezhang: I suspect that's a question to be answered by @nicolasnoble (or the next assignee to whom he routes this issue).

**Comment by Mr-Grieves** [comment]
I am also experiencing the same issue. Using Protobuf 3.4.1, gRPC 1.6.2.

It seems that it is an issue with setting the gRPC/Protobuf targets. In addition to the above mentioned error, I am also experiencing issue [#10759](https://github.com/grpc/grpc/issues/10759). I suspect they are related...

**Comment by jtattermusch** [comment]
I just created a PR that adds test to verify that gRPC and can be installed using cmake on windows and helloworld example can be build afterwards.

**Comment by whiplash86** [comment]
I'm still not any further. Since the PR still isn't merged yet, I cloned grpc's master branch and merged the PR into my working copy. If I then execute the build pipeline, I get the same error as Cristinavieira when trying to build the helloworld or any other example via CMake. If I execute the new run_distrib_test.bat manually it either fails for the grpc x86 build because it's looking for the protobuf installation inside C:\Program Files\grpc\.. instead of C:\Program Files (x86)\grpc\.. and if I build grpc as x64 target, it (expectedly?) fails with a x86/x64 target mismatch when trying to link the grpc_cpp_plugin. If I try to execute tools/run_tests/run_test.py, it complains about module six.moves not being found.

I'm also confused by the fact that run_distrib_test.bat suggests providing most 3rd party libs as package which isn't mentioned in any way by the windows build instructions and not done if I just run CMake in the top-level directory. All in all pretty frustrating as I spend days now getting this to work. Is there maybe an older release which works out of the box? I really don't have the time to spend that much time tangling with the build system.

**Comment by whiplash86** [comment]
Update: run_distrib_test.bat failing with an x64/x86 conflict was an error on my part I guess. I installed a different grpc build to C:\Program Files (x86)\grpc and the distrib test found protobuf there instead of taking the one build by the script itself.
Now the script successfully generates the Hello World example but fails when trying to execute its custom build command (for running the protoc compiler on helloworld.proto). It looks like the problem lies in the example's CMakeLists.txt, line 19 following:

> if(Protobuf_FOUND)
>   \# Protobuf_FOUND is set for package type "CONFIG"
>   set(_PROTOBUF_LIBPROTOBUF protobuf::libprotobuf)
>   set(_PROTOBUF_PROTOC protobuf::protoc)
> elseif(PROTOBUF_FOUND)
>   \# PROTOBUF_FOUND is set for package type "MODULE"
>   set(_PROTOBUF_LIBPROTOBUF ${PROTOBUF_LIBRARIES})
>   set(_PROTOBUF_PROTOC ${PROTOBUF_PROTOC_EXECUTABLE})
>   include_directories(${PROTOBUF_INCLUDE_DIRS})
> else()
>   message(WARNING "Failed to locate libprotobuf and protoc!")
> endif()

For me the script executes the if branch which results in the custom command being 'protobuf::libprotobuf \<args\>' instead of sth like 'C:/path/to/protoc/protoc.exe \<args\>'. Any idea what's wrong here?

**Comment by whiplash86** [comment]
@jtattermusch Can I get any sort of reaction on this? The build is basically broken for months now and it's really hindering our productivity.

**Comment by jtattermusch** [comment]
@whiplash86 , which version of grpc are you using for your experiments? there's been some improvements in the recent versions (my guess is you might be hitting a problem fixed here: https://github.com/grpc/grpc/pull/12411, and the fix is available starting from v1.7.0)

Can you try with `v1.9.0-pre2` ? We now have a continuous test that verifies that run_distrib_test.bat works and that test is passing consistently, so I'm reasonable sure things work.

**Comment by whiplash86** [comment]
@jtattermusch 
I was working on `v1.8.4` or `v1.8.x` before, as well as `master`. With `v1.9.0-pre2` it works now. I'm only getting tons of warnings from wire_format_lite.h:

```
D:\develop64\grpc\testinstall\include\google/protobuf/wire_format_lite.h(863): warning C4146: unary minus operator applied to unsigned type, result still unsigned [D:\develop64\grpc\examples\cpp\helloworld\cmake\build\greeter_server.vcxproj]
D:\develop64\grpc\testinstall\include\google/protobuf/wire_format_lite.h(874): warning C4146: unary minus operator applied to unsigned type, result still unsigned [D:\develop64\grpc\examples\cpp\helloworld\cmake\build\greeter_server.vcxproj]
```

**Comment by jtattermusch** [comment]
@whiplash86 , that warning you're getting seems to be protobuf specific, consider filing an issue with https://github.com/google/protobuf/

**Comment by whiplash86** [comment]
Just for completeness: Has already been opened:
[https://github.com/google/protobuf/issues/3947](url)
