### ISSUE TITLE
cloud_to_prod_auth:default:php7:compute_engine_creds interop failure

### ISSUE THREAD

**Issue by markdroth** [grpc/grpc#12490]
From #12297:

https://grpc-testing.appspot.com/job/gRPC_interop_pull_requests/16517/testReport/junit/(root)/tests/cloud_to_prod_auth_default_php7_compute_engine_creds/

Output:

```
Fatal error: Uncaught DomainException: Could not load the default credentials. Browse to https://developers.google.com/accounts/docs/application-default-credentials for more information in /var/local/git/grpc/src/php/vendor/google/auth/src/ApplicationDefaultCredentials.php:148
Stack trace:
#0 /var/local/git/grpc/src/php/tests/interop/interop_client.php(579): Google\Auth\ApplicationDefaultCredentials::getCredentials('https://www.goo...')
#1 /var/local/git/grpc/src/php/tests/interop/interop_client.php(618): _makeStub(Array)
#2 /var/local/git/grpc/src/php/tests/interop/interop_client.php(693): interop_main(Array)
#3 {main}
  thrown in /var/local/git/grpc/src/php/vendor/google/auth/src/ApplicationDefaultCredentials.php on line 148
```

**Comment by jtattermusch** [comment]
Removing P1 label, comparably less important than other P1s we have.

**Comment by jtattermusch** [comment]
Not seeing this on last master runs.

**Comment by yashykt** [comment]
Seen again at #15527

**Comment by ZhouyihaiDing** [comment]
The error is thrown with 
`Google\Auth\ApplicationDefaultCredentials::getCredentials('https://www.goo...')`, which is the library provided by [`Google\Auth`](https://github.com/google/google-auth-library-php/blob/master/src/ApplicationDefaultCredentials.php#L148). I don't think we can do something in the Grpc part.

**Comment by stanley-cheung** [comment]
Let's figure out why though - is it because some machines don't have the credentials file stored correctly?

**Comment by ZhouyihaiDing** [comment]
Credentials file is supposed to be installed correctly because according the logs,
`cloud_to_prod_auth:php7:default:per_rpc_creds` and `cloud_to_prod_auth:php7:default:oauth2_auth_token` are passed, which means they all passed the line `Google\Auth\ApplicationDefaultCredentials::getCredentials('https://www.googleapis.com/auth/xapi.zoo');`.

I loop run `ApplicationDefaultCredentials::getCredentials` 100,000 times and it doesn't throw the error. Seems like this flaky is hard to reproduce.

**Comment by jtattermusch** [comment]
To give some insight:
- this is "compute_engine_creds"  interop tests. It is supposed to use "GCE" flavor of application default credentials. That flavor can only be used on a GCE VM where a "default service account" is available, so trying to reproduce locally is probably pointless (because you are testing a different codepath).

- ApplicationDefaultCredentials are "automagic" in a sense that it chooses the right credentials for your environment.  The autodetection steps are described in https://cloud.google.com/docs/authentication/production#auth-cloud-implicit-php.   On GCE VM, unless you override with an environment variable, it checks if the GCE metadata server is available (by hitting and artificial URL that is only available inside GCE network) and if so, it gets the credentials from there. If that check fails, the library assumes it's not running on GCE and tries to use other source of credentials - and if none are available, it will just fail (probably the error message you are seeing).

- The `Uncaught DomainException: Could not load the default credentials` error message you are seeing likely means that the auth library tried to contact the GCE metadata server to obtain the default service account, it timed out doing so (which is basically the rootcause of the problem) and because there was no other credential sources available (and that's intended for a test that's supposed to test GCE credential), it just failed.

- the key difference between `per_rpc_creds` and `oauth2_auth_token` test is that those are using a pre-installed service account key JSON file so they won't experience this flakiness.  But the point of `compute_engine_creds` test is NOT to use that json file and authenticate using the default service account.

- I think what's "broken" here is the autodetection mechanism itself in ApplicationDefaultCredentials (it's basically probabilistic, because it relies on a successfuly connecting to the metadata server). Perhaps increasing the timeout in the auth library would help. Besides this, it seems there's little we can do about this on the gRPC side.

**Comment by jtattermusch** [comment]
The timeout for checking that we are on GCE in PHP auth library seems to be 0.3s https://github.com/google/google-auth-library-php/blob/42e26564c0bc4333d7219780d8a6c4cb16879695/src/Credentials/GCECredentials.php#L140

Perhaps other languages use longer timeout?
Java seems to be using 0.5sec (and does retry).
https://github.com/google/google-auth-library-java/blob/cbc6c1062d5fe1920c6a641a4d63769b56267eb0/oauth2_http/java/com/google/auth/oauth2/ComputeEngineCredentials.java#L76

**Comment by stanley-cheung** [comment]
Just to confirm, running `compute_engine_creds` locally will actually fail right? That was my understanding

**Comment by ZhouyihaiDing** [comment]
Thank you, @jtattermusch ! This really helps me a lot! That explains my confusion. I was wrong because I thought since we do `export export GOOGLE_APPLICATION_CREDENTIALS`, it was the same we run it locally or on GCE because it will use `ServiceAccountCredentials` instead of `GCECredentials`. The thing is `compute_engine_creds` shouldn't export that.

Then it is most likely caused by the timeout from `GCECredentials`. I can manually reduce it to `0.001` and reproduce the same error. I [create a PR](https://github.com/google/google-auth-library-php/pull/195) to `google/auth` to add retry and 500ms timeout.

@stanley-cheung , it will fail if we doesn't do `export` locally. By the way, the `google/auth` for running interop tests seems too old. I guess we can use the latest by #15646?

**Comment by stanley-cheung** [comment]
Sure.

**Comment by stanley-cheung** [comment]
Just re-checking recent test runs and these tests are passing consistently recently now

`2019-03-19 19:10:27,907 PASSED: cloud_to_prod_auth:php7:default:compute_engine_creds:tls [time=1.4sec, retries=0:0]`
