### ISSUE TITLE
performance test: "Error uploading result to bigquery" 

### ISSUE THREAD

**Issue by ZhouyihaiDing** [grpc/grpc#12904]
https://github.com/grpc/grpc/pull/12677/files#diff-57f3f006800f519161034225f389cad2R385
Someone should run the update script.

**Comment by jtattermusch** [comment]
The resolution for this is to use the https://github.com/grpc/grpc/blob/master/tools/run_tests/performance/patch_scenario_results_schema.py script

See an older issue (https://github.com/grpc/grpc/issues/11919) for reference.
Btw, we keep doing the same thing over and over, we should find a way to prevent this from happening in the future.

**Comment by ZhouyihaiDing** [comment]
Do we need to add "upload bigquery" and "build failed" checking for every PR? @jtattermusch 
This issue happened 2 times again after I posted this issue. Each time it took several days before someone discover it.
Or do we run patch_scenario_results_schema.py before running the benchmark?
The latest data in the dashboard is run on Oct, 18th.

**Comment by jtattermusch** [comment]
I think having a way to check if a PR will break uploading to bigquery would be pretty useful.
Do you have any suggestions how would such "sanity" test look like?

I think running patch_scenario_results_schema.py automatically (and blindly) is too much of a risk that we'll end up with a very messy (or broken) schema. Having a check that the schema is up to date so that we find out before merging would be better IMHO.

**Comment by ZhouyihaiDing** [comment]
The issue itself has been solved. 
It's that we need to think about a way to prevent it from happening in the future. I'll try to look into it with the idea about the sanity test later.
