### ISSUE TITLE
bins/opt/h2_http_proxy_test resource_quota_server assertion failure

### ISSUE THREAD

**Issue by dgquintas** [grpc/grpc#13124]

**Comment by y-zeng** [comment]
Also seen under asan.

**Comment by jtattermusch** [comment]
This is also happening for other pollers:
```
bins/dbg/h2_http_proxy_test resource_quota_server GRPC_POLL_STRATEGY=poll-cv
bins/dbg/h2_http_proxy_nosec_test resource_quota_server GRPC_POLL_STRATEGY=poll
```

Currently it's failing 100% of master builds (dbg and opt).

**Comment by jtattermusch** [comment]
Multiple tests failing 100% of cases in both dbg and opt -> raising to P0.

**Comment by jtattermusch** [comment]
Any updates here? It seems to be happening in almost all test runs.

**Comment by sreecha** [comment]
Looking into this today. Will update EOD

**Comment by sreecha** [comment]
I have been looking at this today. I am able to get a local repro; This fails in all polling engines and pretty much all fixtures (except a few that do not use http2 transport).  Haven't been able to root case it yet.
Actively investigating..

**Comment by sreecha** [comment]
Update from investigation on 11/1/2017: 

Took @ctiller's help in debugging this. Made progress but still haven't fully root caused it. I do not have a clear understanding of what is going on but here are some details:

The test fails because the client receives `GRPC_STATUS_UNKNOWN` from the server which is unexpected.

The reason server is sending that status is because:
Server transport's read failed with the following error (because client seems to have closed the connection):

```{"created":"@1509590467.380786907","description":"Endpoint read failed","file":"src/core/ext/transport/chttp2/transport/chttp2_transport.cc","file_line":2523,"occurred_during_write":1,"referenced_errors":[{"created":"@1509590467.380785410","description":"Socket closed","fd":7,"file":"src/core/lib/iomgr/tcp_posix.cc","file_line":430,"target_address":"ipv6:[::1]:22484"}]}```

(Note that the above error does not have any error code).

On getting this failure, the server transport marks the stream closed and it *seems* like the server generates a trailing metadata with the error code it tries to extract from the above (and since there is none, it is set to `GRPC_STATUS_UNKNOWN`)
--

Things that aren't clear to me:
- I also do not know why the server is sending trailing metadata to the client even after - as per error msg - the client closed the connection.

 - Comparing test success and test failure messages, I see that in success cases, the server transport gets 'Endpoint read failed'  error only when there are no more pending streams to close. 
In the failure cases (like the one I described above), the server transport gets the 'Endpoint read failure' when the streams are pending; whats interesting here is that ALL the 100 streams are pending (and in the test, the client only creates 100 calls.. So NONE of the calls completed by the time server transport got the error.). This is very odd.  I verified this in several failed test runs..

I will investigate more..

**Comment by sreecha** [comment]
I root caused the issue (with help from @ctiller)

Note: I deleted my previous comment because I was way off (and the comment made some incorrect/misleading assumptions :)).

__Some background info:__
- Server's chttp2 transport code calls resource quota functions periodically i.e `post_benign_reclaimer` and `post_destructive_reclaimer` both of which call `grpc_resource_user_post_reclaimer`.

`grpc_resource_user_post_reclaimer` checks if there is shortage of memory and if so, it calls the reclaimers (i.e `benign_reclaimer_locked` and `destructive_reclaimer_locked`).

The benign reclaimer does nothing if there are any open streams. However, if there aren't any open streams, the reclaimer sends a GOAWAY and closes the transport.

The destructive reclaimer checks for any open streams and if there any, it randomly picks one and cancels them. If there are more streams, it calls `post_destructive_reclaimer` (i.e to check for memory pressure and then call destructive reclaimer again if needed)

__Root cause:__
This is what is happening:
- The client initiates 100 requests (i.e 100 streams)

- The server starts receiving and processing them. Right around the time the server receives and processes a few requests (like ~10 or so), the benign and destructive reclaimers kick in.  The destructive reclaimer quickly ends up cancelling all the open streams. 
Sometimes, due to weird timing, if the benign reclaimer is called at this point (where the number of active streams on the server is zero but there are still many pending streams from client yet to be accepted and processed), the benign reclaimer just proceeds to send a GOAWAY and closes the end point. 

- The client receives a goaway and also end of stream. The client's read end point returns an error saying `Endpoint read failed`. The client then cancels all outstanding calls and returns error to the application.  

- Currently, the error code returned to the application is `GRPC_STATUS_UNKNOWN` (this is because the client does not know why the end point failed. The error message does not have any grpc or http error code).  

The `resource_quota_server` test does not expect `GRPC_STATUS_UNKNOWN` code and hence failing.

__Fix:__
The fix is relatively simple. When client receives `Endpoint read failed` error, check if the client also received a GOAWAY frame and if so, append that error (along with the HTTP2 error code received along with the GOWAY frame) to the `Endpoint read failed` error. 
Since the error message now has an error code, the code that bubbles up this error code to the application returns the appropriate error code (in this case `GRPC_RESOURCE_EXHAUSTED`)

**Comment by jtattermusch** [comment]
@sreecha  great job rootcausing the issue, this looks like a tough one!

**Comment by jtattermusch** [comment]
I am actually still seeing this on upstream/master after #13259 has been merged.
Based on the data, it looks like it *has been fixed* on `opt` configuration,
but it's *still happening* at the same rate for `dbg`.

E.g.
https://sponge.corp.google.com/target?id=02948f4d-d731-40eb-a9fa-8918f8c8ce16&target=github/grpc/c_linux_dbg_native&searchFor=&show=ALL&sortBy=STATUS
https://sponge.corp.google.com/target?id=70c75be1-d066-4244-b30d-809b269eaf82&target=github/grpc/c_linux_dbg_native&searchFor=&show=ALL&sortBy=STATUS

**Comment by sreecha** [comment]
Hmm..looks like this is now happening only on `h2_http_proxy` fixture :(..  I will take a look.

**Comment by sreecha** [comment]
Found the root cause for why this is failing with `h2_http_proxy_test` fixture.

The http proxy fixture is shutting down both its endpoints (one for talking to client and the other for talking to server) whenever there is an error from either the client or the server. In this case, when the server sends a go-away frame and closes the channel, the proxy is shutting down the both endpoints.

The client may not get the goaway frame sent by the server (since the proxy may have shut down the end point before relaying the goaway frame to the client).

As a result, the client's read is failing with `socket closed` error (since the proxy shutdown the endpoint on the other side) but the error does not have any grpc/http error codes. The previous fix I made does not work here because the client is never even receiving the goaway frame.

**Comment by dgquintas** [comment]
Awesome work @sreecha ! This will have a huge impact in reducing the amount of failures.

**Comment by jtattermusch** [comment]
Is this fixed now when https://github.com/grpc/grpc/pull/13579 is merged?

**Comment by dgquintas** [comment]
Doesn't look like it, according to [this](https://bigquery.cloud.google.com/results/grpc-testing:bquijob_3c894d16_16028e55742?pli=1). Closing. Thanks @sreecha !
