### ISSUE TITLE
cmake/build/Debug/grpc_completion_queue_test.exe TIMEOUT

### ISSUE THREAD

**Issue by dgquintas** [grpc/grpc#13219]
https://sponge.corp.google.com/target?id=935a7eea-db02-4795-9a09-747af66528cd&target=github/grpc/c_windows_dbg_native&searchFor=&show=FAILED&sortBy=STATUS

```
Timeout
D1031 19:48:56.050000000  3176 test_config.c:388] test slowdown factor: sanitizer=1, fixture=1, poller=1, total=1
D1031 19:48:56.066000000  3176 dns_resolver.cc:306] Using native dns resolver
I1031 19:48:56.066000000  3176 completion_queue_test.c:67] test_no_op
I1031 19:48:56.066000000  3176 completion_queue_test.c:87] test_pollset_conversion
I1031 19:48:56.066000000  3176 completion_queue_test.c:109] test_wait_empty
```

**Comment by jtattermusch** [comment]
CC @jtattermusch

**Comment by jtattermusch** [comment]
happening in ~50% of runs.

**Comment by jtattermusch** [comment]
I analyzed in a debugger, and it's pretty similar to what we've been seeing in https://github.com/grpc/grpc/issues/12394.

The test hangs in (only for cq_polling_type=GRPC_CQ_NON_POLLING)
https://github.com/grpc/grpc/blob/ef68fe7239a89095f1eaa89c1dd28b2b7be2a3c7/test/core/surface/completion_queue_test.c#L117
(basically call cq_next on empty completion queue and timeout immediately)

https://github.com/grpc/grpc/blob/ef68fe7239a89095f1eaa89c1dd28b2b7be2a3c7/src/core/lib/surface/completion_queue.cc#L950
In the instance I debugged, grpc_exec_ctx_now() returns 7 and deadline_millis is 8, so the cq_next cycle never breaks (and it also explains why it's sometimes passing - if we get lucky and the two timestamps are equal, cq_next will return normally). All other instances where it hung I saw the difference in millis was 1.

Still investigating.

**Comment by jtattermusch** [comment]
Ok, I think I found the problem:

In
https://github.com/grpc/grpc/blob/ef68fe7239a89095f1eaa89c1dd28b2b7be2a3c7/src/core/lib/surface/completion_queue.cc#L950, exec_ctx->now_is_valid is false, so grpc_exec_ctx_now needs to refresh the timestamp here:
https://github.com/grpc/grpc/blob/ef68fe7239a89095f1eaa89c1dd28b2b7be2a3c7/src/core/lib/surface/completion_queue.cc#L890

it's done using `timespec_to_atm_round_down`.  But, when cq_next started, we set the deadline_millis and rounded up:
https://github.com/grpc/grpc/blob/ef68fe7239a89095f1eaa89c1dd28b2b7be2a3c7/src/core/lib/surface/completion_queue.cc#L890

So if we get lucky and round_up = round_down, the test passes. Otherwise it hangs forever.

**Comment by jtattermusch** [comment]
Btw, I think the issue exists on linux too, but we are not seeing it as the granularity of timestamp increments is much finer than on Windows (so we need to get really unlucky to hit the condition in the test).
