### ISSUE TITLE
Passing GPR_TIMESPAN as a timeout to C core doesn't work anymore.

### ISSUE THREAD

**Issue by jtattermusch** [grpc/grpc#13275]
We ran into that in https://github.com/grpc/grpc/issues/12886.

Passing GPR_TIMESPAN to C core with a semantics of "timeout" has worked in the past, and it seems it stopped working after https://github.com/grpc/grpc/pull/12677.

Not urgent, but might be worth fixing in the future.

**Comment by jtattermusch** [comment]
CC @ctiller  @ZhouyihaiDing

**Comment by markdroth** [comment]
Sree, this seems related to your work on `grpc_millis`.

**Comment by sreecha** [comment]
What C-Core API are we referring to here?  (@ZhouyihaiDing / @jtattermusch)  ?

(I tried reading #12886 but its a big PR)

**Comment by jtattermusch** [comment]
@sreecha   I think the idea was to be able to use a GPR_TIMESPAN (=timeout) in C-core APIs that accept deadline (and then C core can internally convert to a GPR_CLOCK_MONOTONIC or whatever is used under the hood).

**Comment by sreecha** [comment]
This does not look like an issue anymore.

I looked at the implementation of `grpc_channel_watch_connectivity_state` and all the other functions (see below) in `grpc.h` that take `gpr_timespec`. All these functionsconvert `gpr_timespec` to `grpc_millis` using ` grpc_timespec_to_millis_round_up/down` which does the right thing! (i.e handles timespec of type `GPR_TIMESPAN` )

  - `grpc_completion_queue_next`
  - `grpc_completion_queue_pluck`
  - `grpc_channel_watch_connectivity_state`
  - `grpc_channel_create_call`
  - `grpc_channel_create_registered_call`
  - `grpc_server_request_registered_call`

**Comment by sreecha** [comment]
The original issue might be that 1 millisec was too less (when we changed the internal representation of deadline to `grpc_millis` from `gpr_timespec`, we increased the granularity to milliseconds - this was intentional.  Also timer threads are not super accurate (and may be off by a few milliseconds).. This is what might have caused the previous test to fail.

I don't think the issue is related to handling `GPR_TIMESPAN`

If there is a repro of some failure that I can look at, please let me know. Else, I suggest we close this bug.

**Comment by jtattermusch** [comment]
@sreecha  I think you might be right, but AFAIK we don't have any tests that would verify that passing GPR_TIMESPAN to C core APIs works well. Without test coverage we can't really say much.

Perhaps it would be a good noogler project to add some basic test coverage for this.

**Comment by sreecha** [comment]
What would really help is the exact repro of the case that stopped working after the `grpc_millis` change ..so that we can see if there is a bug somewhere.

I know that writing unit tests is a good idea but at this point we are not really sure if there is a bug here (and as such, I wonder if our time is better spent on other higher priority failures)..
