### ISSUE TITLE
Install of grpcio with Python throws "Unknown target CPU" message at s390x platform

### ISSUE THREAD

**Issue by claudefalbriard** [grpc/grpc#13369]
**System Information**
. OS Platform and Distribution: s390x SuSE SLES 12 SP2
. grpcio package installed via pip3
. Python version: 2.7 and 3.4

**Error Message**
When doing a build / install of the grpcio package under the IBM system z platform (architecture s390x) on Linux SuSE SLES 12, I get the following error message at the make step: 

```
    In file included from third_party/boringssl/include/openssl/rsa.h:60:0,
                     from ./src/core/lib/security/credentials/jwt/json_token.h:23,
                     from ./src/core/lib/security/credentials/jwt/jwt_credentials.h:23,
                     from src/core/lib/security/credentials/google_default/google_default_credentials.c:31:
    third_party/boringssl/include/openssl/base.h:106:2: error: #error "Unknown target CPU"
     #error "Unknown target CPU"
      ^
```
Is there a solution available through the OpenSSL package? Any hint how fix this error is welcome.

**Comment by hsaliak** [comment]
At this moment, s390x is an unsupported platform. However, this issue seems to be from the `setup.py` pulling in a boringssl dependency. Assuming that there is a system openssl in place, you might be able to patch `setup.py` to use that.

It would be nice to actually have setup.py support the option of using the system openssl if preferred. The `Makefile` in core already supports this (ie, it tries to use the system openssl if available), but in this case, we would want this to be an option. 

Hope this helps!

**Comment by nicolasnoble** [comment]
That one's going to be a bummer. While the Makefile is able to detect if you have a system OpenSSL that works properly and will try to use it, the python build system isn't going for this and will always try to use the embedded SSL provided, as @hsaliak mentioned.
