### ISSUE TITLE
Broken bazel test: //test/core/bad_ssl:bad_ssl_cert_server

### ISSUE THREAD

**Issue by jtattermusch** [grpc/grpc#13607]
```
E1130 00:36:49.964151926      15 server_common.cc:42]        assertion failed: addr
Aborted (core dumped)
```

https://source.cloud.google.com/results/invocation/05f9065e-93e5-4b35-ad1f-ab6bfa8b383a/targets/%2F%2Ftest%2Fcore%2Fbad_ssl:bad_ssl_cert_server?page=log

**Comment by adelez** [comment]
Friendly ping?

**Comment by adelez** [comment]
Hi David, could you please triage and assign this bug to a proper owner? Thanks!

**Comment by yashykt** [comment]
I took a look. The current bazel rule is outdated and does not make sense. It just runs a server. The actual test is bad_ssl_cert_test which does not have a rule, and adding a rule for that does not seem possible without changing the test.

The way this test is written, they start a server as a separate process, and then run the test. For this to work as a test, we would need the ability to add a binary (for the server) as a dependency to the test. But, that is not allowed from what I read in the bazel rules.
So, the options I see are -
1) Rewrite the test so that it works with bazel
2) Simply not covering this test with bazel

Adding @nicolasnoble

**Comment by adelez** [comment]
Thank you for looking! Adding the binary as data dependency should work.

**Comment by yashykt** [comment]
Update: using it as a data dependency worked. I didn't expect data dependencies to allow cc_binary

**Comment by adelez** [comment]
It's now failing with https://source.cloud.google.com/results/invocations/de9624c7-15ba-4216-8e18-ba8d44247728/targets/%2F%2Ftest%2Fcore%2Fbad_ssl:bad_ssl_cert_test/log
