### ISSUE TITLE
wait_for_ready=false RPCs should fail when name resolution fails

### ISSUE THREAD

**Issue by muxi** [grpc/grpc#13627]
After DNS cache is flushed and network has 100% packet loss rate, a gRPC call initiated at this time will hang waiting for DNS to succeed.

**Comment by dgquintas** [comment]
Would https://github.com/grpc/grpc/issues/9481 be related?

**Comment by markdroth** [comment]
I don't think #9481 is actually a problem.  The issue here is not that we keep trying to resolve; it's that the RPC never returns.

This may be tangentially related to #12897.  Although from my conversation with Muxi earlier today, he indicated that this was a case where the call was going to be a long-running streaming RPC and thus has no deadline, so it wouldn't actually be affected by that bug anyway.  In that use-case, I don't think there's anything to do except have the application cancel the call if they don't receive initial metadata by some particular time.

**Comment by muxi** [comment]
@markdroth Receiving initial metadata seems to me not the correct criteria for DNS resolution failure (or any other connection-time failure). In some calls the server might just wait (for a long time) to receive all messages and EOS from client then reply initial metadata after that, and I believe (correct me if I am wrong) that is a legitimate use case.

In my understanding the way this should work is: when DNS fails, any pending call waiting for this DNS resolution whose `wait_for_ready` is not set should fail with UNAVAILABLE. More generally speaking, I think any `wait_for_ready=false` call waiting for a channel to connect should fail when the channel's state is set to TRANSIENT_FAILURE. Should this be the case?

**Comment by markdroth** [comment]
If we have not yet connected to the server, why does the application care whether the problem is a DNS lookup failure or a connection-level failure?  I don't know of a use-case where the difference between those actually matters.

In the use-case you describe where the server does not send initial metadata until reading all of the client messages, I agree that there's no easy way for the application to tell that there's a problem.  But I think that's true regardless of whether it's a name resolution failure or a server that simply loses track of the call due to a bug.  There's no clear way for the application to determine what's wrong, so if it cares about this, it's going to have to apply some sort of deadline.

It's not clear to me whether or not `wait_for_ready` should actually apply to name resolution failures.  We could probably make a change to do that, but I'm not sure it's the right thing to do, especially since there would be some implications for our internal resolver design.  We should probably talk with @a11r about this when he gets back.

**Comment by muxi** [comment]
You are right that there should not be a difference between DNS lookup failure or connection failure.

From [its doc](https://github.com/grpc/grpc/blob/master/doc/wait-for-ready.md), `wait_for_ready` depends on checking channel state. Since name resolution failure sets channel to TRANSIENT_FAILURE, I believe `wait_for_ready` is already applied to name resolution.

I think the actual issue is, if a channel's state **transits to** TRANSIENT_FAILURE (e.g. due to name resolution failure, connect() timeout, etc.) the calls without `wait_for_ready` should fail with the channel state transition. Without this behavior, a call may initiates a channel connection (IDLE->CONNECTING) then wait for a long time for name resolution retries, connect() retries, etc.

Yes we should talk with @a11r about this.

**Comment by markdroth** [comment]
Currently, name resolution failure does *not* cause the channel's state to be set to TRANSIENT_FAILURE.

Note that it's not actually the case that `wait_for_ready=false` RPCs are failed based on the channel's state being TRANSIENT_FAILURE; in actuality, both setting the channel state to TRANSIENT_FAILURE and returning failure for `wait_for_ready=false` RPCs are triggered by the same underlying error condition.  And since our current resolver design is that the resolver handles errors internally instead of reporting them to the client channel, neither of those things happens on resolver errors.

**Comment by muxi** [comment]
Hmm that is interesting to know. I am seeing some different behavior in my logs.

> Currently, name resolution failure does not cause the channel's state to be set to TRANSIENT_FAILURE.
My logs were showing periodical state transitions like this:
```
D1202 10:25:01.196120000 2954387456 connectivity_state.c:172]          SET: 0x7c170f38 client_channel: IDLE --> TRANSIENT_FAILURE [new_lb+resolver] error=0x7c495d70 {"created":"@1512239101.193867000","description":"No load balancing policy","file":"/Users/mikelehen/src/firebase-ios-sdk/Firestore/Example/Pods/gRPC-Core/src/core/ext/filters/client_channel/client_channel.c","file_line":561}
```
```
D1202 10:25:32.202904000 2954387456 connectivity_state.c:172]          SET: 0x7c170f38 client_channel: TRANSIENT_FAILURE --> TRANSIENT_FAILURE [new_lb+resolver] error=0x7c170c90 {"created":"@1512239132.200605000","description":"No load balancing policy","file":"/Users/mikelehen/src/firebase-ios-sdk/Firestore/Example/Pods/gRPC-Core/src/core/ext/filters/client_channel/client_channel.c","file_line":561}
```

> both setting the channel state to TRANSIENT_FAILURE and returning failure for wait_for_ready=false RPCs are triggered by the same underlying error condition.
Even with the channel state transitions above, the call remained pending.

Does that look like a bug?

**Comment by markdroth** [comment]
What version of gRPC are you using?  That's clearly not anything near master, since the files have ".c" suffix instead of ".cc", which means it's from before the C++ build change.  Can you try again with the code from master?

With the current code, that error message should not occur.  If you're seeing that, it means that the resolver *did* return, but it returned no data, which should never happen.  If it is still happening with the current code, then I can look into what's going on.

**Comment by muxi** [comment]
I'll try that. The code I was using was v1.7.1.

**Comment by muxi** [comment]
Tried master at 7fbbc23. Behavior is the same:

* Channel transited to TRANSIENT_FAILURE
* Call stayed pending after channel went to TRANSIENT_FAILURE

```
D1205 16:27:32.653163000 123145519419392 client_channel.cc:259]        chand=0x7feedfe2f840: setting connectivity state to TRANSIENT_FAILURE
D1205 16:27:32.653245000 123145519419392 connectivity_state.cc:169]    SET: 0x7feedfe2f8e0 client_channel: IDLE --> TRANSIENT_FAILURE [new_lb+resolver] error=0x7feedfc43510 {"created":"@1512520052.653062000","description":"No load balancing policy","file":"/Users/mxyan/grpc/grpc/src/core/ext/filters/client_channel/client_channel.cc","file_line":600}
```
```
D1205 16:28:09.008378000 123145519419392 client_channel.cc:259]        chand=0x7feedfe2f840: setting connectivity state to TRANSIENT_FAILURE
D1205 16:28:09.008469000 123145519419392 connectivity_state.cc:169]    SET: 0x7feedfe2f8e0 client_channel: TRANSIENT_FAILURE --> TRANSIENT_FAILURE [new_lb+resolver] error=0x7feedfc43690 {"created":"@1512520089.008294000","description":"No load balancing policy","file":"/Users/mxyan/grpc/grpc/src/core/ext/filters/client_channel/client_channel.cc","file_line":600}
```

**Comment by markdroth** [comment]
Can you please show me what code you're running to trigger this and share the complete trace log?

**Comment by muxi** [comment]
This is `EmptyUnaryRPC` [test](https://github.com/grpc/grpc/blob/1d4e99508409be052bd129ba507bae1fbe7eb7fa/src/objective-c/tests/InteropTests.m#L106-L122) running on iOS simulator. Precondition is flushing DNS cache and setting the network packet loss rate to 100% with Network Link Conditioner. I can help with setting this up for you if needed.

Complete trace log is pasted [here](https://docs.google.com/document/d/1Mzt99hSOVybeZ6HOzVmE8tESIGJJaE-QxRk0y7rql_A/edit?usp=sharing).

**Comment by markdroth** [comment]
Thanks, that trace was very useful.

It looks like the DNS resolver is actually returning a NULL result to the client channel, even when it retries.  I didn't realize it was doing that, and the client channel code is definitely not expecting that, which is why we're getting an unusual result here.

I'll talk to @a11r when he gets back about the right way to handle `wait_for_ready` here.  If the answer is that DNS failures should not cause `wait_for_ready=false` RPCs to fail, then I'll change the DNS resolver to not return a result in this case.  Alternatively, if the answer is that DNS failures *should* cause `wait_for_ready=false` RPCs to fail, then I'll instead change the client_channel code to do that when it sees the NULL result from the resolver.

**Comment by muxi** [comment]
Sounds good, thanks Mark.

**Comment by markdroth** [comment]
Abhishek has agreed that a name resolution failure should immediately terminate RPCs with wait_for_ready=true.  I'll need to update the C-core code accordingly.

I'm pretty swamped at the moment and can't give an ETA on this yet, but I will get to it at some point.
