### ISSUE TITLE
New Failure: alarm_test.exe

### ISSUE THREAD

**Issue by dgquintas** [grpc/grpc#13693]
- Test: alarm_test.exe
- Poll Strategy: None
- URL: https://kokoro2.corp.google.com/job/grpc/job/windows/job/master/job/grpc_basictests_opt/636

**Comment by jtattermusch** [comment]
https://sponge.corp.google.com/target?id=bddb149a-d243-49d5-a2ae-a35698b556a4&target=github/grpc/c_windows_opt_native&searchFor=&show=FAILED&sortBy=STATUS

**Comment by jtattermusch** [comment]
During the invocation of grpc_completion_queue_shutdown(grpc_completion_queue * cq)  the number pending events is sometimes >1 (so there seems to be a race with an unfinished cq_event from the test).
In 
https://github.com/grpc/grpc/blob/e1e562eb171c81fad24176e898cc4e722bee227b/src/core/lib/surface/completion_queue.cc#L1001
because there is a pending operation, `cq_finish_shutdown_next` is postponed until that pending operation finishes  and the test fails because cq_next with inf_past deadline returns TIMEOUT instead of SHUTDOWN.

**Comment by jtattermusch** [comment]
I think I have a good understanding of what's going on:

There's effectively a race condition between cq_end_op_for_next() (which delivers the alarm notification in alarm_test) and grpc_completion_queue_next()  (which is expected to deliver SHUTDOWN event in no-polling mode in the test).

Timer thread:  (invoking alarm_cb, which invokes cq_end_op_for_next()):
1. cq_end_op_for_next()   first publishes the alarm notification on the completion queue in https://github.com/grpc/grpc/blob/e1e562eb171c81fad24176e898cc4e722bee227b/src/core/lib/surface/completion_queue.cc#L653
2. later in the code, it checks if pending_event count in the completion queue has dropped to zero and if so, it finalizes the shut down procedure the completion queue.
https://github.com/grpc/grpc/blob/e1e562eb171c81fad24176e898cc4e722bee227b/src/core/lib/surface/completion_queue.cc#L677

The test thread:
1. alarm is setup and awaited with cq_next().
2. when alarm_cb runs on the timer thread, and pushes the event to cq_next(), the event is read by cq_next here: https://github.com/grpc/grpc/blob/e1e562eb171c81fad24176e898cc4e722bee227b/src/core/lib/surface/completion_queue.cc#L885
3. the grpc_completion_queue_shutdown is invoked because the test has finished and "awaited" by a no-polling cq_next ( the deadline is set to inf_past).
4. the cq_next checks https://github.com/grpc/grpc/blob/e1e562eb171c81fad24176e898cc4e722bee227b/src/core/lib/surface/completion_queue.cc#L904 and sees there's still a pending event because cq_end_op_for_next() from the timer thread haven't yet updated the pending event count. Therefore, the shutdown event is not generated and actually shutting down the cq is left to the in-progress cq_end_op_for_next(). 
The shutdown will actually happen there correctly, but the no-polling cq_next() has already returned TIMEOUT instead of SHUTDOWN and that fails the test.

If cq_next is not required to return SHUTDOWN immediately, this is trivially fixable by adding a deadline in the future in the test.
If that behavior is required, we have a race condition in  completion queue that needs to be fixed.

```
D0115 16:08:43.333000000 19868 dns_resolver.cc:294] Using native dns resolver
I0115 16:08:43.333000000 19868 init.cc:154] grpc_init(void)
I0115 16:08:43.333000000 19868 alarm_test.cc:54] test_alarm
I0115 16:08:43.333000000 19868 completion_queue.cc:431] grpc_completion_queue_create_internal(completion_type=0, polling_type=0)
I0115 16:08:43.333000000 19868 completion_queue.cc:866] grpc_completion_queue_next(cq=00451E10, deadline=gpr_timespec { tv_sec: 2, tv_nsec: 2238552, clock_type: 0 }, reserved=00000000)
D0115 16:08:44.333000000  3488 alarm.cc:89] alarm_cb invoked.
I0115 16:08:44.334000000  3488 completion_queue.cc:633] cq_end_op_for_next(cq=00451E10, tag=00000001, error="No Error", done=00B31390, done_arg=00451F10, storage=00451F58)
I0115 16:08:44.334000000 19868 completion_queue.cc:975] RETURN_EVENT[00451E10]: OP_COMPLETE: tag:00000001 OK
I0115 16:08:44.334000000 19868 completion_queue.cc:1270] grpc_completion_queue_shutdown(cq=00451E10)
```

**Comment by jtattermusch** [comment]
@sreecha  @ncteisen  is the race  between cq_next and cq_end_op_for_next something we know about? If we are counting on the no-polling behavior of cp_next to work reliably (I'm don't think the API explicitly guarantees this behavior, but I can understand that some users might think it's reasonable for it to work), we'd need to fix this somehow. Any ideas?

**Comment by jtattermusch** [comment]
Here's a reliable repro of the problem for linux: https://github.com/grpc/grpc/pull/14022

**Comment by sreecha** [comment]
Thanks @jtattermusch . 

>> is the race between cq_next and cq_end_op_for_next something we know about?

Of late, I have been seeing an assert() in cq-destroy code path that makes me suspect that there is a race condition that we are not aware of.  However, In this particular case, I do *not* think it is a bug.. see my comments below..

>>The shutdown will actually happen there correctly, but the no-polling cq_next() has already returned TIMEOUT instead of SHUTDOWN and that fails the test.
>> If cq_next is not required to return SHUTDOWN immediately, this is trivially fixable by adding a deadline in the future in the test

It is perfectly reasonable for `cq_next()` to return a TIMEOUT in which case, the caller should call it one more time to get a result (SHUTDOWN or an actual event). So in this case, its the test that has to be corrected either by adding a deadline or calling cq_next() again (perhaps in a loop) until the result is a SHUTDOWN

**Comment by jtattermusch** [comment]
The fix is here: https://github.com/grpc/grpc/pull/14005
