### ISSUE TITLE
helloworld example question

### ISSUE THREAD

**Issue by torfhub** [grpc/grpc#13702]
helloworld example

#server.py
def SayHello(self, request, context):
  return request

Q:
SayHello() must return a HelloReply object
so, why does this still work ?

**Comment by jakobr-google** [comment]
Depends on your definition of 'work', but here's my take:

Python is dynamically typed, so no-one is checking that you're actually returning a HelloReply like you're supposed to. The gRPC library probably just wants something that it can serialize. HelloRequest and HelloReply are both protobuf message objects, so they implement the same serialization interface, and the server will happily return the object to the client.

The definitions of HelloRequest and HelloReply both have a string at tag 1, so they'll look the same on the wire (assuming binary wire format): The server will serialize request.name as tag 1, and the client will deserialize tag 1 as reply.message.

So it 'works' because Python (by design) doesn't enforce the contract, and because the message schemas happen to match.

**Comment by torfhub** [comment]
thank you for the explanation !
