### ISSUE TITLE
Enable build of grpc++ using make and without building c-ares

### ISSUE THREAD

**Issue by vjpai** [grpc/grpc#13761]
Please answer these questions before submitting your issue. 
 
### Should this be an issue in the gRPC issue tracker?
 
Yes

### What version of gRPC and what language are you using?
 
master, C++
 
### What operating system (Linux, Windows, …) and version?
 
An embedded system (sorry, don't know the details)
 
### What runtime / compiler are you using (e.g. python version or version of gcc)
 
An embedded build system that uses make rather than bazel
 
### What did you do?

Tried to build
 
### What did you expect to see?
 
Successful build

### What did you see instead?
 
c-ares won't even build in this platform and this is a problem since the Makefile-based build depends on c-ares even if it doesn't actually get used. This is contract to the bazel BUILD for which cares can be stubbed out as a dummy dependence and the grpc_no_ares config_setting will suppress the use of c-ares in the actual code. It would be nice to be able to build a library version that didn't depend on or use c-ares.

**Comment by isaachier** [comment]
What about CMake?

**Comment by vjpai** [comment]
I should clarify that I'm the proxy filing this issue for someone else who doesn't use Github and that in that person's environment, make is the only build option. No cmake or bazel. I haven't tried to see if this is possible with cmake. I know it's doable with bazel because I've [configured it](https://github.com/tensorflow/tensorflow/blob/master/tools/bazel.rc#L25) in [TensorFlow](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/workspace.bzl#L681).

**Comment by isaachier** [comment]
"I haven't tried to see if this is possible with cmake." What do you mean by "this?" Are you referring to the ability to set options? Are you asking if there is a preconfigured option in gRPC?

The issue I have with this request in the first place is that it asks for two very different things in one issue. My focus here will only be about the idea of making a standalone makefile. Make on its own is rarely used for projects with more than a few directories/build targets. For large projects supporting many platforms, you will usually see the use of makefile generators that generate platform-specific makefiles. autotools is still the dominant makefile generator, but CMake is growing in numbers. From what I know, bazel does not generate makefiles, but does the entire build from start to finish.

If you want to use makefiles to build gRPC in order to avoid installing cmake or bazel on a given platform, you might be able to use CMake to help you generate the makefile, but I am honestly not sure and would not suggest it.
