### ISSUE TITLE
gRPC 1.8.2 Python 3 TypeError

### ISSUE THREAD

**Issue by ewang** [grpc/grpc#13866]
Please answer these questions before submitting your issue. 

### What version of gRPC and what language are you using?
Server: gRPC-go 1.4.0
Client: gRPC 1.8.2
 
### What operating system (Linux, Windows, …) and version?
Mac OS X 10.11.6
 
### What runtime / compiler are you using (e.g. python version or version of gcc)
 Python 3.6.2, libprotoc 3.5.0
 
### What did you do?
Attempt to connect to gRPC server via Python client
 
### What did you expect to see?
No errors
 
### What did you see instead?
Got following error with Python 3.6.2; works fine with Python 2.

```
E1221 17:17:10.464218000 140735306604544 ev_epollex_linux.cc:1482]     Skipping epollex becuase GRPC_LINUX_EPOLL is not defined.
E1221 17:17:10.464247000 140735306604544 ev_epoll1_linux.cc:1261]      Skipping epoll1 becuase GRPC_LINUX_EPOLL is not defined.
E1221 17:17:10.464251000 140735306604544 ev_epollsig_linux.cc:1761]    Skipping epollsig becuase GRPC_LINUX_EPOLL is not defined.
TypeError: expected bytes, str found
Exception ignored in: 'grpc._cython.cygrpc.SSLChannelCredentials.c'
TypeError: expected bytes, str found
E1221 17:17:10.466025000 140735306604544 composite_credentials.cc:258] assertion failed: channel_creds != nullptr && call_creds != nullptr && reserved == nullptr
Abort trap: 6
```

**Comment by ewang** [comment]
Reading the certs file with mode `b` fixes it; but this seems like a breaking behavior that wasn't in the release notes.

**Comment by mehrdada** [comment]
Apologies for the confusion and not being more clear in the release notes. I believe the following entry under 1.8.0 tried to communicate this particular change in behavior--although it does not directly mention credentials, it transitively covers that as part of metadata--but I can totally empathize how it can go unnoticed. (to further clarify, the old behavior was never intended to be supported and happened to work because the type distinction was previously loosely enforced):

"More strict enforcement of type-correctness of metadata values. (#13672)"
