### ISSUE TITLE
Python source dist and wheels differ in behavior

### ISSUE THREAD

**Issue by dhermes** [grpc/grpc#13906]
For example, installing on Ubuntu via:

```
pip install 'grpcio==1.8.2'
```

the spinlock bug fixed by #13665 is still present, but building from the source dist

```
pip install 'grpcio==1.8.2' --no-binary=grpcio
```

the bug is resolved.

(I realize #13665 ~~will be reverted~~ [has been reverted][1], but this issue is just reporting that your process of building wheels may be broken.)

/cc @jonparrott @lukesneeringer

[1]: https://github.com/grpc/grpc/pull/13898

**Comment by mehrdada** [comment]
@dhermes This behavior difference is likely due to an inherent problem with `manylinux` binary wheels. `manylinux` platform, for which we distribute binaries, does not support the system calls required for more advanced polling strategies, thereby falling back to simple `poll` syscall. I don't think there's much that can be done here for the behavior difference. The particular bug itself, of course, will hopefully get fixed, but I don't think there's much (or at least anything trivial) we can do to activate `epoll` on `manylinux`.

You can try forcing the `GRPC_POLL_STRATEGY=poll` environment variable on your built-from-source version and see if it manifests the problem to confirm my strong suspicion.

**Comment by dhermes** [comment]
Thanks @mehrdada. I'm running my [example][1] with `GRPC_POLL_STRATEGY=poll`. It's been running for 10 minutes, so I'll know in about 50 minutes if the spinlock has occurred.

[1]: https://github.com/dhermes/google-cloud-pubsub-performance/tree/master/no-messages-too

**Comment by mehrdada** [comment]
Closing. Please let us know if there are other differences between the binary and source that do not fall into the poll strategy category.

**Comment by jonparrott** [comment]
Can we re-open this? 

`epoll` was introduced in [glibc 2.3.2](http://man7.org/linux/man-pages/man7/epoll.7.html#VERSIONS), manylinux1 supports [`glibc <= 2.5`](https://www.python.org/dev/peps/pep-0513/#the-manylinux1-policy) so it should be possible to enable epoll without breaking manylinux1 compatibility.

**Comment by mehrdada** [comment]
@jonparrott Thanks for letting us know. I made an issue for that: https://github.com/grpc/grpc/issues/13949

**Comment by mehrdada** [comment]
@jonparrott I tried https://github.com/grpc/grpc/pull/13951.

`epoll_create1` is not available on `manylinux1` and that's what gRPC uses.

**Comment by jonparrott** [comment]
@mehrdada does this use the official manylinux1 docker image?

**Comment by mehrdada** [comment]
@jonparrott I think it does. Note that `epoll_create` is different from `epoll_create1`. The latter requires a newer glibc than 2.5 (I think 2.9)

**Comment by jonparrott** [comment]
yeah it's 2.9.

Ugh, epoll.
