### ISSUE TITLE
ERR! Pre-built binaries not found for grpc@1.7.3 and node@6.12.2 (node-v48 ABI, musl) 

### ISSUE THREAD

**Issue by stephenplusplus** [grpc/grpc#13928]
###### Copied from original issue: https://github.com/googleapis/gax-nodejs/issues/168

<a href="/plantsmiles"><img src="https://avatars2.githubusercontent.com/u/6740546?s=88&v=4" height=44 width=44 align=left></a>@plantsmiles<br>January 5, 2018 1:51 PM

I'm running `@google-cloud/language` which uses this project as direct dependency. I have not problem running `nom install` on my host computer, but this application is served in docker.

All of a sudden when building my docker images 

```
> grpc@1.7.3 install /usr/src/app/node_modules/grpc
> node-pre-gyp install --fallback-to-build --library=static_library

node-pre-gyp ERR! Tried to download(403): https://storage.googleapis.com/grpc-precompiled-binaries/node/grpc/v1.7.3/node-v48-linux-x64-musl.tar.gz 
node-pre-gyp ERR! Pre-built binaries not found for grpc@1.7.3 and node@6.12.2 (node-v48 ABI, musl) (falling back to source compile with node-gyp) 
```

This has been working for weeks.. I do not understand why `https://storage.googleapis.com/grpc-precompiled-binaries/node/grpc/v1.7.3/node-v48-linux-x64-musl.tar.gz ` would all of a sudden would lock down that link?  Going to it in a browser 

```
<Error>
<Code>AccessDenied</Code>
<Message>Access denied.</Message>
<Details>
Anonymous users does not have storage.objects.get access to grpc-precompiled-binaries/node/grpc/v1.7.3/node-v48-linux-x64-musl.tar.gz.
</Details>
</Error>
```

Doesn't make any sense to me .. Any ideas?

**Comment by stephenplusplus** [comment]
cc @plantsmiles

**Comment by murgatroid99** [comment]
The error you are seeing is slightly misleading. The file simply does not exist. For that version of gRPC we separated the binaries for glibc and musl (Alpine) because people were reporting issues with trying to run the glibc binary on Alpine. But we did not actually publish the Alpine binaries until grpc 1.8.0.

Whenever the precompiled binary isn't present, the installation should simply fall back to building from source, but unfortunately the base Alpine images don't come with the necessary tools to do so. You would need to install the `python` and `build-base` packages to build from source.

**Comment by plantsmiles** [comment]
Thanks for the response, kinda a bummer.. For anyone else with this issue I added

```RUN apk --no-cache add --virtual native-deps \
  build-essential python && \
  npm install --quiet node-gyp -g &&\
  npm install --quiet && \
  apk del native-deps```

Which fixed the docker build for me.

**Comment by stephenplusplus** [comment]
This issue was moved to https://github.com/grpc/grpc-node/issues/187.
