### ISSUE TITLE
grpc > 1.8.0 gems not published to rubygems

### ISSUE THREAD

**Issue by rurounijones** [grpc/grpc#13940]
Please answer these questions before submitting your issue. 
 
### Should this be an issue in the gRPC issue tracker?

I believe so in that this should be actionable.

### What version of gRPC and what language are you using?

1.8.0
 
### What operating system (Linux, Windows, …) and version?
 
Ubuntu Linux 16.04
 
### What runtime / compiler are you using (e.g. python version or version of gcc)
 
ruby 2.3.6
 
### What did you do?

Attempted to install the rubygem for grpc 1.8.3 which contains a bug fix which should allow grpc to shutdown gracefully (In retrospect, I may be wrong on that one, I don't think that change made it into 1.8.3, but the point still stands).
 
### What did you expect to see?

Installation of the rubygem corresponding to the grpc 1.8.3 release 
 
### What did you see instead?

Version not found error as no release later than 1.8.0 has been been pushed to rubygems, see https://rubygems.org/gems/grpc and https://rubygems.org/gems/grpc-tools

### Anything else we should know about your project / environment?

None.

Potential off-topic questions:
* How are rubygems published?
  * I am assuming it is manual, could it be automated as part of a pipeline?
* Is there a known delay between releasing and publishing to rubygems?
* Is there a release policy? (I couldn't find anything)

**Comment by apolcyn** [comment]
the 1.8.3 gem was just published. I believe that the relevant bug fix for ruby in that release is https://github.com/grpc/grpc/pull/13882

> How are rubygems published?
> I am assuming it is manual, could it be automated as part of a pipeline?

Package builds are automated but we still manually push the gems. I don't think there are any plans to change this since it's less error-prone if the decision to push a package is manual.

> Is there a known delay between releasing and publishing to rubygems?

They should be available as soon as we publish them

> Is there a release policy? (I couldn't find anything)

In general, we release a new minor version ~every 6 weeks, and this minor version release is done across all languages. Once the minor version is released, e.g., 1.8.0, there might be some bug fixes that will be applied on top of it and get published as patch releases. Where things might get a little weird is some bug fixes might only apply to e.g. one language, and in that case we increase the patch number for the whole repo, release the patch for that language, but then usually don't release the patch for other languages (so you can wind up with e.g., ruby-1.8.3 and c#-1.8.0). In this case, the 1.8.3 ruby package should have been released, but there was just a delay.

**Comment by rurounijones** [comment]
Many thanks for the publish and many thanks for the insight into the release process, apolcyn :+1:
