### ISSUE TITLE
gRPC tls with Objective-c & Go

### ISSUE THREAD

**Issue by MikeSilvis** [grpc/grpc#13960]
Hi!

I'm trying to establish a tls connection with a golang server using the objective-c cocoapod (but bridged to swift).

I'm having a difficult time finding real documentation and what could potentially be my issue and why i keep receiving the error: `Handshake failed with fatal error SSL_ERROR_SSL: `. 

Below is my implementation:

``` swift
        let url = Bundle.main.url(
            forResource: GTConstantsManager.sharedInstance.string(key: "grpc_cert_path"),
            withExtension: "crt"
        )

        let cert = try! String(contentsOf: url!, encoding: .utf8)

        print("Path for file: \(GTMobi.certPath)")
        print("Host is: \(GTMobi.host)")
        print("Cert is : \(cert)")


        try! GRPCCall.setTLSPEMRootCerts(
            cert,
            forHost: GTMobi.host
        )

          // I've tried both of these functions to estalish a connection
//        try! GRPCCall.setTLSPEMRootCerts(
//            cert,
//            withPrivateKey: nil,
//            withCertChain: nil,
//            forHost: GTMobi.host
//        )
```

And then from my logs locally: 

```
Path for file: mobile-grpc-staging.gametime.co
Host is: mobile-grpc-staging.gametime.co:8000
Cert is : { removed for security }
E0109 11:16:57.330699000 123145475719168 ssl_transport_security.c:970] Handshake failed with fatal error SSL_ERROR_SSL: error:1000007d:SSL routines:OPENSSL_internal:CERTIFICATE_VERIFY_FAILED.
E0109 11:16:57.351562000 123145475719168 ssl_transport_security.c:970] Handshake failed with fatal error SSL_ERROR_SSL: error:1000007d:SSL routines:OPENSSL_internal:CERTIFICATE_VERIFY_FAILED.
Responded with error: Optional(Error Domain=io.grpc Code=13 "(null)")
```

I was able to verify my cert is being loaded correctly from disk, and our android app is connecting. Any further help, or steps to diagnose would be great.

Also do i need to set up anything specific on my Go server to work with iOS? Our Go Client and Android client both are working correctly. My cert was generated using https://github.com/square/certstrap

Thanks,
Mike

**Comment by dcow** [comment]
Have you made sure the hostname checks out? Overriding the hostname is supported with `grpc-java` but it looks like it's behind the private/GRPCHost API here.

**Comment by phacops** [comment]
Hi, I'm working with @MikeSilvis on this.

Hostname is correct. It works without additional config from a Go client (besides importing the certificate as a root CA).

**Comment by phacops** [comment]
So, we finally made it working by supplying the root CA instead of the actual server certificate.

I've read the gRPC objective-c implementation is using the gRPC C implementation under the hood so openssl is used for TLS. Could it openssl is confused because both certificates have the same subject?

**Comment by dcow** [comment]
@phacops adding 

    GRPC_TRACE=all

to the environment (or if you're using xcode, `name: GRPC_TRACE value: all` in the scheme's run configuration) will get tell gRPC to print more error information.

**Comment by muxi** [comment]
Would love to know more about this issue. Surprising to know that `serverName` does not work. What exactly did you mean by `overrideAuthority`?

**Comment by dcow** [comment]
@muxi sorry I meant `setHostnameOverride` on `GRPCHost`. (I'm working between `grpc-java` and `grpc` and `grpc-go` which can be slightly confusing at times). As far as I traced `serverName` looks like it's used strictly by SNI whereas `setHostnameOverride` is used to configure what name (from SAN or CN) is to be used during the hostname verification step (in openssl). I could be remembering incorrectly, in which case I must have encountered some other issue using `serverName` on the rpc call itself instead of overriding the hostname on the channel itself.

**Comment by sashabaranov** [comment]
@phacops I'm also passing root CA (generated from certstrap) and still getting

```
E0125 20:30:10.710446000 123145562537984 ssl_transport_security.cc:976] Handshake failed with fatal error SSL_ERROR_SSL: error:1000007d:SSL routines:OPENSSL_internal:CERTIFICATE_VERIFY_FAILED.
```

Basically I do:

```swift
do {
    try GRPCCall.setTLSPEMRootCerts(CA_CERT, forHost:HOST)
} catch {
    print("Error setting up ssl")
}

client = MYClient.init(host: HOST + ":50052")
```

**Comment by muxi** [comment]
@jboeuf - It looks like the [per-call override of hostname](https://github.com/grpc/grpc/blob/32b9bddb27f9ac8aeb57b83ab7d7f7cd5946b564/src/core/lib/surface/channel.cc#L269) is not taken into consideration in TLS. The overridden hostname seems only [depends on `GRPC_SSL_TARGET_NAME_OVERRIDE_ARG`](https://github.com/grpc/grpc/blob/32b9bddb27f9ac8aeb57b83ab7d7f7cd5946b564/src/core/lib/security/credentials/ssl/ssl_credentials.cc#L59), which [is a test-only argument](https://github.com/grpc/grpc/blob/master/include/grpc/impl/codegen/grpc_types.h#L245). That does not look right to me but I hope to confirm if this is by design or not. Thanks!

**Comment by dcow** [comment]
FWIW for anyone who isn't using gRPC solely on the public internet or fully configured "site", we depend on the ability to specify hostname. Really, we depend on being able to use TLS to meet our own requirements and specifications. It's not really a "test only" feature despite gRPC having such an opinion. It's simply an extra step the client can use to increase confidence in a remote server's identity especially in a "web TLS" scenario where DNS is a valid assumption. However, if someone pwns your DNS (which is rather likely if you're being targeted), then it doesn't matter.

In our case, we own application logic on both client and server and we use mutual tls with custom trust anchors, so being able to control what names we accept from the certificate (and not forcing a DNS lookup) is a requirement. We will likely put IPv6 link locals in the SAN at some point (and we may eventually run private DNS "site"s for users), but the world isn't quite there just yet. And sadly no such thing exists for IPv4. (Well, that's not entirely true, there are v4 _link-local_ addresses but you don't use them quite the same way--although we _are_ interested in a solution that allows TLS to work correctly over MDNS, which would still require clients to have control over the expected properties of the server's certificate.)

**Comment by dcow** [comment]
@phacops I was able to use a certificate with the same subject and issuer; the CA and leaf certificates are even signed with the same key (so subjectPublicKeyInfo, authorityKeyId and subjectKeyId are the same, too). OpenSSL has no trouble verifying leaf certificates of that nature. Generally, it's okay for CAs to _self-issue_ certificates that can be used for TLS and there is no requirement that subjects be distinct. Practically, it's conceivable that such a limitation could have made its way into implementations of path validation, and since gRPC uses the OpenSSL API, in theory it could implement its own opinionated path construction/validation algorithm. However, I verified gRPC has no issue handling chains of this nature. 

> So, we finally made it work by supplying the root CA instead of the actual server certificate.

I can also confirm that OpenSSL will *not* verify certificates where the server leaf cert itself is a trust anchor instead of the actual certificate authority that issued the cert. There are a few things here. For a certificate to be a CA it should have the relevant basicConstraint set to `true`. But in absence of such extension, it could be a _potential ca_. A certificate must also have the appropriate keyUsage in order to be a ca. However, I think the real issue is that rfc5280 describes a path construction algorithm that requires at minimum two certificates. You _must_ have a trusted issuer and a subject leaf cert that needs verification (allowing any chain in between). I don't know if it's on purpose or not, but the algorithm is specified that way. If the issuer of a presented leaf cert does not exist as a trusted anchor (assuming no intermediate path) then openssl will fail to verify the cert throwing error: `20 X509_V_ERR_UNABLE_TO_GET_ISSUER_CERT_LOCALLY: unable to get local issuer certificate`.  In theory you'd be just fine trusting end certs individually, but in practice, requiring a slightly more complex relationship has a few advantages (namely you can roll leaf certs without as much churn, and that you end up with better separation of responsibilities between what the CA key can do and what end entity keys can do, for example).

**Comment by jboeuf** [comment]
@muxi The host is checked for each call:
https://github.com/grpc/grpc/blob/32b9bddb27f9ac8aeb57b83ab7d7f7cd5946b564/src/core/lib/security/transport/security_connector.cc#L876

@jiangtaoli2016 FYI.

**Comment by muxi** [comment]
@jboeuf - I see that makes sense. Thank you! That code is not executed for now, so something else is wrong I think.

@dgquintas - From my debug run, [`maybe_prepend_client_auth_filter`](https://github.com/grpc/grpc/blob/785dda80dc1115df5af903b6fe9a15db90ea33b1/src/core/lib/surface/init_secure.cc#L39) is registered [here](https://github.com/grpc/grpc/blob/785dda80dc1115df5af903b6fe9a15db90ea33b1/src/core/lib/surface/init_secure.cc#L70) but the function never got invoked during subchannel create process, so the filter `client_auth_filter` never get inserted into the call stack of a subchannel. Does that look like a bug or an expected behavior?

**Comment by dgquintas** [comment]
The way to get to that function is from [here](https://github.com/grpc/grpc/blob/b1f5d59b4fb567cdcc6786122d7bfcbd698f9af0/src/core/lib/surface/init.cc#L144), which is always invoked always, as part of the init. However, there are two implementations of it, one if [init_secure.cc](https://github.com/grpc/grpc/blob/b1f5d59b4fb567cdcc6786122d7bfcbd698f9af0/src/core/lib/surface/init_secure.cc#L69) and another one in [init_unsecure.cc](https://github.com/grpc/grpc/blob/b1f5d59b4fb567cdcc6786122d7bfcbd698f9af0/src/core/lib/surface/init_unsecure.cc#L23). The latter is empty, only the former ends up invoking `maybe_prepend_client_auth_filter`. So I think it's a compilation problem (linking, actually): the unsecure version is probably being used.

**Comment by muxi** [comment]
Sorry I just found I was not clear and caused confusion.

The function `grpc_register_security_filters()` in `init_secure.cc` was indeed always invoked by `grpc_init()`. However inside this function, it calls [`grpc_channel_init_register_stage`](https://github.com/grpc/grpc/blob/785dda80dc1115df5af903b6fe9a15db90ea33b1/src/core/lib/surface/init_secure.cc#L70) which only **registers** `maybe_prepend_client_auth_filter` (also in `init_secure.cc`) not invoke it. I guess after this registration `maybe_prepend_client_auth_filter` is supposed to be invoked during subchannel creation, but some debug shows it never gets invoked.

**Comment by dgquintas** [comment]
I see. The logic of that function is quite simple. It saves the function pointer for later use in [`grpc_channel_init_create_stack`](https://github.com/grpc/grpc/blob/b1f5d59b4fb567cdcc6786122d7bfcbd698f9af0/src/core/lib/surface/channel_init.cc#L101). I don't see any way it wouldn't be invoked. Would it be possible to ensure that `grpc_channel_init_create_stack` is also getting invoked? That should definitely happen [here](https://github.com/grpc/grpc/blob/b1f5d59b4fb567cdcc6786122d7bfcbd698f9af0/src/core/ext/filters/client_channel/subchannel.cc#L568), as part of `publish_transport_locked()`, which is invoked the moment the connection is established ([here](https://github.com/grpc/grpc/blob/b1f5d59b4fb567cdcc6786122d7bfcbd698f9af0/src/core/ext/filters/client_channel/subchannel.cc#L628)). Putting logging messages all around those steps would allow us to see where the chain is broken.

**Comment by muxi** [comment]
Thanks @dgquintas. After more tests it seems that `grpc_channel_init_create_stack` calls `maybe_prepend_client_auth_filter` when I connect to host `grpc-test.sandbox.googleapis.com`. If I connect to a server with IP address, `maybe_prepend_client_auth_filter` is not called.

**Comment by muxi** [comment]
When we connect to a server with IP address, only a channel is created but not a subchannel, while `maybe_prepend_client_auth_filter` is registered to `GRPC_CLIENT_SUBCHANNEL`. That looks like why the prepend function never got called.

**Comment by dcow** [comment]
> When we connect to a server with IP address, only a channel is created but not a subchannel, while maybe_prepend_client_auth_filter is registered to GRPC_CLIENT_SUBCHANNEL. That looks like why the prepend function never got called.

That explanation would align with my experience.

**Comment by dgquintas** [comment]
How can anything happen if no subchannel (the actual physical connection)
is created?

**Comment by congdufs** [comment]
Hello, I have the same problem, have you resolved it? Thank you.

**Comment by MikeSilvis** [comment]
@congdufs to resolve this issue we actually did not need to manually set a certificate on the client. Instead you just need to ensure the server has a signed ssl certificate

**Comment by muxi** [comment]
To use a self signed certificate, please use [`useTestCertsPath `](https://github.com/grpc/grpc/blob/master/src/objective-c/GRPCClient/GRPCCall+Tests.h#L34). `serverName` is only for overriding the `:authority` header of the calls. It does not affect TLS behavior (but will be checked against TLS certificate name and will fail if it does not match).

**Comment by muxi** [comment]
I think this issue can be closed since the current behavior is expected. Let me know if you still have any concern about it.

**Comment by congdufs** [comment]
@muxi I also try to use a self signed certificate and call the API like this
`self.host = host;
  self.port = port;
  self.hostAddress = [NSString stringWithFormat:@"%@:%@", self.host, self.port];
  NSString *cerPath = [[NSBundle mainBundle] pathForResource:@"server" ofType:@"cer"];
  [GRPCCall useTestCertsPath:cerPath testName:host forHost:self.hostAddress];`
but I still keep receiving the error: Handshake failed with fatal error SSL_ERROR_SSL. Do you have any idea? Thank you very much.

**Comment by congdufs** [comment]
@muxi I also try to use a self signed certificate and call the API like this
`self.host = host;
self.port = port;
self.hostAddress = [NSString stringWithFormat:@"%@:%@", self.host, self.port];
NSString *cerPath = [[NSBundle mainBundle] pathForResource:@"server" ofType:@"cer"];
[GRPCCall useTestCertsPath:cerPath testName:host forHost:self.hostAddress];`
but I still keep receiving the error: Handshake failed with fatal error SSL_ERROR_SSL. Do you have any idea? Thank you very much.

**Comment by congdufs** [comment]
@muxi I also try to use a self signed certificate and call the API like this
`self.host = host;
self.port = port;
self.hostAddress = [NSString stringWithFormat:@"%@:%@", self.host, self.port];
NSString *cerPath = [[NSBundle mainBundle] pathForResource:@"server" ofType:@"cer"];
[GRPCCall useTestCertsPath:cerPath testName:self.host forHost:self.hostAddress];`
but I still keep receiving the error: Handshake failed with fatal error SSL_ERROR_SSL. Do you have any idea? Thank you very much.

**Comment by dcow** [comment]
@congdufs I'm pretty sure it needs to be a pem cert.

**Comment by congdufs** [comment]
@dcow I log in  with grpc successfully for the first time, then I log out and keep the app entering background for about 2 hours, I log in again and receive: Error Domain=io.grpc Code=2 "Stream removed" UserInfo={NSLocalizedDescription=Stream removed, io.grpc.TrailersKey={}}. Do you have any idea? Thank you so much.
