### ISSUE TITLE
Core library broken on iOS due to the use of thread-local storage

### ISSUE THREAD

**Issue by jcanizales** [grpc/grpc#1398]
The use of `GPR_TLS_DECL` in [this commit](https://github.com/grpc/grpc/commit/1be373cf1209db007dc6e05bee86ab7fbb96dd8c) breaks the library for iOS. Thread-local storage is not supported by iOS.

**Comment by ctiller** [comment]
__thread isn't supported by iOS, but it seems pthread_setspecific is?
at least going by this:
https://developer.apple.com/library/ios/documentation/System/Conceptual/ManPages_iPhoneOS/man3/pthread_setspecific.3.html

Can you arrange for GPR_PTHREAD_TLS to be defined in port_platform.h instead of GPR_GCC_TLS, and let me know the outcome?

**Comment by murgatroid99** [comment]
It looks like that fixes the problem.

**Comment by jcanizales** [comment]
`pthread_setspecific`: Awesome! We can use it in `cpu_iphone.c` to do the same that `__thread` does in `cpu_posix.c`.

**Comment by murgatroid99** [comment]
To be clear, I got it to work by changing the definitions in `port_platform.h` as suggested
