### ISSUE TITLE
Grpc/Protobuf Unloadable Create Descriptor from .proto in run-time

### ISSUE THREAD

**Issue by Disturbing** [grpc/grpc#14067]
### What version of gRPC and what language are you using?
 
 1.8.3

### What operating system (Linux, Windows, …) and version?
 
 Windows 10

### What runtime / compiler are you using (e.g. python version or version of gcc)
 
dotnet 2.0.3
 
### What did you expect to see?
 
I'd like to load a .proto file and create a Descriptor class in runtime.

**Comment by jtattermusch** [comment]
From what I understand this is not grpc related, it's a protobuf issue (Consider filing on https://github.com/google/protobuf/ instead).

I'm not sure what is it that doesn't work. If you are trying to create an instance of Descriptor from .proto file (textual), that is actually not supported by protobuf (and it has nothing to do with gRPC itself). 
You need at least binary form of the FileDescriptor (can be obtained by running protoc), but instantiating a FileDescriptor from binary data is only supported by some languages (C++, Java, ...), it's not supported in C# because C# doesn't support proto2.

One related thing you might be looking for is the protobuf type "Any" https://developers.google.com/protocol-buffers/docs/proto3#any
