### ISSUE TITLE
Why StartCall didn't trigger the rpc call , instead , it is the CompletionQueue:Next() which actually does this.

### ISSUE THREAD

**Issue by ppLorins** [grpc/grpc#14104]
In the grpc\examples\cpp\helloworld\greeter_async_client.cc example , I  guess that the `rpc->StartCall` will send the rpc package to the server side , but I found only after `cq->next()` that server will start processing the request , seems that it's the `cq->next()` call that actually send the rpc request packages out , instead of `rpc->startCall` .     So , what 's the relationship between the two ?

I think that `rpc->StartCall()` is the right choice to be the trigger , but the fact may be not .

platform :　win 10 
grpc version: 1.8.x

**Comment by vjpai** [comment]
Hi there,
In the future, let me suggest that (as stated in the issue template), this is the sort of question that is better suited for the grpc-io mailing list as it's a question about library implementation rather than a bug report or feature request.
The gRPC core doesn't promise to do the (potentially blocking) network activity for RPCs unless it knows that that work is being waited on by a Next. This is to avoid the need to use library-owned threads just to push the network activity further; instead, the core can use the application threads to push the work along each time they call Next. The C++ API is just a thin wrapping around the core, and it also makes no promises about when the network activity actually starts, just that the Next/AsyncNext operations will actually catch the result of a completed tagged operation.
Hope that helps!

**Comment by ppLorins** [comment]
@vjpai  Understood , that helps me understand  further  about the core.

**Comment by danielin917** [comment]
Does Grpc allow you to send an asynchronous rpc without having to call the the blocking function cq.Next()?

**Comment by danielin917** [comment]
AsyncNext() is available if you do not want to have to do the blocking call to Next().
