### ISSUE TITLE
gRPC claims to work with Ruby >= 2.0.0 but it does not.

### ISSUE THREAD

**Issue by lclutz** [grpc/grpc#14163]
I tried using gRPC version 1.8.3 with Ruby version 2.0.0 (gem version 2.4.8). According to the information on rubygems gRPC should be compatible with Ruby versions >= 2.0.0 (https://rubygems.org/gems/grpc/). 

### What did you do?

I ran `gem install grpc`.
  
### What did you expect to see?
 
I expected the gem to install without error.
 
### What did you see instead?

```
ERROR:  Error installing grpc:
        jwt requires Ruby version >= 2.1.
```

**Comment by apolcyn** [comment]
grpc does work with ruby 2.0.0, but the application needs to pin dependencies on its own.

Here is an example of that: https://github.com/grpc/grpc/blob/master/test/distrib/ruby/distribtest.gemspec

The problem here is just that grpc doesn't pin it's dependency on `jwt`.... and so `gem install grpc` attempts to grab the latest available version of `jwt` and then fails.

**Comment by lclutz** [comment]
@apolcyn  You are right. Thank you very much for your help.
