### ISSUE TITLE
gRPC Python Protoc Plug-In should not generate nearly-empty _pb2_grpc.py files for message-only .proto files

### ISSUE THREAD

**Issue by fengli79** [grpc/grpc#14172]
If a proto file given to the gRPC python codegen doesn't contains any service, an empty py file is generated.

It only contains:
```
# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc
```

Suggest to remove it.

**Comment by nathanielmanistaatgoogle** [comment]
Something into which to look that may have consequences for this issue is whether or not Bazel allows the output files generated by a rule to exist or not-exist according to the content of the input files. If not, and I suspect not, fulfilling this issue would erect an obstacle to [building gRPC Python with Bazel](https://github.com/grpc/grpc/issues/8079), which although a long-term goal is something we very much want.

**Comment by nathanielmanistaatgoogle** [comment]
Closing this; I've thought about it for a long time and I just don't think it's a good idea. There's no harm to having an empty file be generated; applications can simply not use it. [Also the file might not be empty forever.](https://github.com/grpc/grpc/issues/3898)

It's somewhat analogous to the API design decision of "if you write a function that returns a list of results, and a particular call of the function has no results, return an empty list rather than returning `null` and creating special cases for your users ".
