### ISSUE TITLE
grpclb server-side load reporting

### ISSUE THREAD

**Issue by longXboy** [grpc/grpc#14195]
Is there any plan to move keepalive  mechanism to grpc load balance layer?Also the ping frame will carry more informations such as weight、server cpu load...In this way,the load balance can dynamiclly kick off unhealthy server node or tune the weight.

https://github.com/grpc/proposal/blob/master/A8-client-side-keepalive.md

**Comment by markdroth** [comment]
The client-side keepalive mechanism is completely disjoint from grpclb.  The former is primarily about maintaining the health of the HTTP/2 connection between the client and the server, and since it's specific to that individual HTTP/2 connection, it can't really be used to communicate with the grpclb balancer, which uses a separate HTTP/2 connection.

That having been said, if your goal is to communicate server load information to your grpclb balancer, then the right way to do that is via server-side load reporting, which allows servers to communicate their load information directly to the balancer.  @AspirinSJL is currently working on an OSS implementation of this.

**Comment by AspirinSJL** [comment]
Hi @longXboy, looks like your question has been answered (please let me know if not). 

As Mark said, I've been working on the feature of server-side load reporting (#14793, #15196, #15570), which covers the functionalities you mentioned for a ping frame. 

I'm closing this issue regarding your original question, but please re-open it if you have any further question. Thanks!
