### ISSUE TITLE
Consider what to do in LB policies upon GOAWAY

### ISSUE THREAD

**Issue by dgquintas** [grpc/grpc#14207]
After #13932, subchannels don't go into `GRPC_CHANNEL_SHUTDOWN` anymore. Therefore, LB policies only see subchannels going into `GRPC_CHANNEL_TRANSIENT_FAILURE` no matter the circumstance. In particular, there's no way to distinguish between a [GOAWAY](https://github.com/grpc/grpc/blob/master/doc/PROTOCOL-HTTP2.md#goaway-frame) and other (retriable) types of failure.

A possibility is to reintroduce `GRPC_CHANNEL_SHUTDOWN` as a visible subchannel connectivity state, to be used in the GOAWAY case. 

(Note to self: changes to `subchannel.cc` would happen around [here]( https://github.com/grpc/grpc/blob/aba7a817faae1d222bde24c5c7fc5172c221360c/src/core/ext/filters/client_channel/subchannel.cc#L538)).

CC @AspirinSJL @markdroth

**Comment by markdroth** [comment]
I suspect this is not really an issue.  It's true that we can't differentiate between a GOAWAY and (e.g.) the TCP connection unexpectedly failing, but I'm not sure we really need to, because we can treat those cases the same way.  We *can* differentiate between those two cases and the case where a connection attempt fails, and that's what's really important.
