### ISSUE TITLE
Generate C# gRPC services as interfaces

### ISSUE THREAD

**Issue by Horusiath** [grpc/grpc#14213]
Current state of C# gRPC services code generation builds proto contracts as abstract classes to be extended by the end user. Same thing concerns client code generation. 

```csharp
// C# code generated for server from RouteGuide.proto file
public abstract partial class RouteGuideBase 
{
    // methods defined in proto file
}

// C# code generated for client from RouteGuide.proto file
public partial class RouteGuideClient : grpc::ClientBase<RouteGuideClient> 
{
    // methods defined in proto file
}
```

However it seems, that more natural way of working with code-based contract representation in C# is via interface implementation - this is also reasonable choice, as C# base class generated by proto.exe doesn't contain any code except set of virtual methods defined in gRCP proto file, which have no actual implementation.

Another case is client code implementation - at the present moment client is generated as a class. This makes harder to abstract over it. It would be great if a client could implement an interface contract (the same as used by proposed server implementation). This way we could abstract over it i.e. to use dependency injection and make unit testing easier.

Proposed code gen:

```csharp
// C# code generated for server from RouteGuide.proto file
public partial interface IRouteGuide // keep I prefix for C# naming convention
{
    // methods defined in proto file
}

// C# code generated for client from RouteGuide.proto file - implements the same interface as server
public partial class RouteGuideClient : grpc::ClientBase<RouteGuideClient>,  IRouteGuide 
{
    // methods defined in proto file
}
```

This proposition is not a breaking change, it could be implemented as an optional parameter to gRPC C# code gen.

PS: personally I'd like to participate in implementing such a feature, but I'd need help (I haven't contributed to gRPC so far). Is there any support channel for new contributors?

**Comment by jtattermusch** [comment]
@Horusiath  we actually used to generate interfaces, but deliberately changed to abstract classes, because interfaces aren't backward compatible when new methods are added - and that's one of the most common changes we anticipate with .proto service definitions (the problem with interfaces is that they don't allow providing default implementation, so regenerating a .proto file with new service methods added will result in breaking the build - as the user-written implementations don't implement the new methods).
The change from interfaces has been done here: https://github.com/grpc/grpc/pull/5928 (and there are links to the original issue).
Closing this issue as "working is intended".
