### ISSUE TITLE
gRPC client caches connection through LB after version 1.8, so LB happens

### ISSUE THREAD

**Issue by mradmila** [grpc/grpc#14260]
Please answer these questions before submitting your issue. 
 
### Should this be an issue in the gRPC issue tracker?
 Yes.

Create new issues for bugs and feature requests. An issue needs to be actionable. General gRPC discussions and usage questions belong to:
- [grpc.io mailing list](https://groups.google.com/forum/#!forum/grpc-io)
- [StackOverflow, with `grpc` tag](http://stackoverflow.com/questions/tagged/grpc)
 
*Please don't double post your questions in more locations; we are monitoring both channels, and the time spent de-duplicating questions is better spent answering more user questions.*
 
### What version of gRPC and what language are you using?
1.8+, Python, basic hello world example
 
### What operating system (Linux, Windows, …) and version?
Linux, Ubuntu 16.04
 
### What runtime / compiler are you using (e.g. python version or version of gcc)
 Python 2.7.12
 
### What did you do?
If possible, provide a recipe for reproducing the error. Try being specific and include code snippets if helpful.

Ran a helloworld client test in a loop hitting 3 servers in K8s through a load-balancer (tried L4 and L7). Before grpc 1.8, I get multiple servers to respond; after 1.8, client caches the connection and hits the same server every time. From a new process, of course, everything is load-balanced in both versions. Note that loop is at the top level and channel is not reused, on purpose.
 
### What did you expect to see?
 Load-balanced results by default, perhaps a policy setting to cache.
 
### What did you see instead?
 Same server responding every time.

Make sure you include information that can help us debug (full error message, exception listing, stack trace, logs).
 
### Anything else we should know about your project / environment?
There were some changes by Mark Roth (commit bf6a86a293325b528dc10ee10ed9d1242b87a642 etc.) in the area that look like they could affect this logic, but I haven't had time to debug all the way through.

Before (different subchannels, 1640,2440,etc.):
I0131 21:33:55.635618530   13122 pick_first.c:415]           Pick First 0x7f8a0c001060 created subchannel 0x7f8a0c001640 for address uri ipv4:<mylb:myport>
I0131 21:33:55.645766408   13122 pick_first.c:415]           Pick First 0x7f8a0c001ad0 created subchannel 0x7f8a0c002440 for address uri ipv4:<mylb:myport>
I0131 21:33:55.654217606   13122 pick_first.c:415]           Pick First 0x7f8a0c002840 created subchannel 0x7f8a0c003250 for address uri ipv4:<mylb:myport>
I0131 21:33:55.662930816   13122 pick_first.c:415]           Pick First 0x7f8a0c003650 created subchannel 0x7f8a0c004090 for address uri ipv4:<mylb:myport>
I0131 21:33:55.673806829   13122 pick_first.c:415]           Pick First 0x7f8a0c002980 created subchannel 0x7f8a0c004e50 for address uri ipv4:<mylb:myport>

After (same subchannel, 1660):
D0131 22:00:04.302650555   14899 subchannel_list.cc:145]     [pick_first 0x7f8204000c10] subchannel list 0x7f82040011c0 index 0: Created subchannel 0x7f8204001660 for address uri ipv4:<mylb:myport>
D0131 22:00:04.313368565   14899 subchannel_list.cc:145]     [pick_first 0x7f8204001dd0] subchannel list 0x7f8204002280 index 0: Created subchannel 0x7f8204001660 for address uri ipv4:<mylb:myport>
D0131 22:00:04.319383651   14899 subchannel_list.cc:145]     [pick_first 0x7f82040024c0] subchannel list 0x7f8204000df0 index 0: Created subchannel 0x7f8204001660 for address uri ipv4:<mylb:myport>
D0131 22:00:04.324686203   14899 subchannel_list.cc:145]     [pick_first 0x7f8204003070] subchannel list 0x7f8204002440 index 0: Created subchannel 0x7f8204001660 for address uri ipv4:<mylb:myport>
D0131 22:00:04.330035757   14899 subchannel_list.cc:145]     [pick_first 0x7f8204003850] subchannel list 0x7f8204002a80 index 0: Created subchannel 0x7f8204001660 for address uri ipv4:<mylb:myport>

@markdroth: Can you please comment/take a look?

**Comment by markdroth** [comment]
Are you using a secure channel?  If so, I suspect that what you're seeing here is the effect of #12767.  Prior to that PR, we were (incorrectly) failing to share subchannels to the same backend between channels when a security connector is in place.  Now, we do share the subchannels, which is what we were always supposed to do.

Note that subchannel sharing only occurs when the subchannels are for the same address and have exactly the same set of channel args.  So in a case like yours where you don't actually want the sharing, an easy way to disable the sharing is to supply a different meaningless channel arg to each channel.  For example, use a channel arg key like "my_channel_index" and set the value to an integer whose value is incremented each time through the loop.

Please let me know if you have any questions about any of this.

**Comment by mradmila** [comment]
I am using an insecure channel. Yes, the address of the LB and the port are exactly the same every time, but I guess I could provide some meaningless identifier for the request. Wouldn't that do the opposite, create the subchannel every time? Then the burden is on client to create some pool?

I guess the meta-question is: how does one get proper server side load-balancing? I was going through default k8s load-balancer, and also using Envoy. Surely we don't want to overload one server from a client that produces a lot of work, especially if we have multiple servers to work with? What do you recommend as a standard way of doing this N clients to M servers through an LB where N << M?

**Comment by mradmila** [comment]
Server is doing the heavy-lifting, of course... client is lightweight.

**Comment by mradmila** [comment]
Hey Mark, I left some notes on GitHub. Can you please comment/offer some guidance? Perhaps an example on what other people do in this situation?

Thanks,

Marko

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by markdroth** [comment]
> I am using an insecure channel.

If you're using an insecure channel, then #12767 wouldn't have had any effect.  But in that case, subchannel sharing should have been working all along, so I'm not sure why you saw any behavior change in 1.8.  But in any case, the behavior you're seeing now is the intended behavior, and using channel args to disable sharing should work around it.

> Yes, the address of the LB and the port are exactly the same every time, but I guess I could provide some meaningless identifier for the request. Wouldn't that do the opposite, create the subchannel every time? Then the burden is on client to create some pool?

Yes, that will cause each channel to create its own subchannel.  I thought that was what you were asking about, but based on the above question, I suspect that I'm misunderstanding something.

My understanding of the problem you've reported here was that the client created multiple channels to the same server and that resulted in all of the channels sharing the same subchannel rather than having each channel create its own subchannel.  But if you don't want the client to have to create a pool of channels, then why are you concerned about the behavior when there are multiple channels in the first place?

Wait -- maybe you're trying to create a separate channel each time through the loop, where the channel is destroyed by the end of the loop, rather than having multiple channels exist at the same time?  If so, my suspicion is that the channel in each iteration of the loop is actually living longer than the end of the loop.  This seems particularly likely to me, given that you are depending upon python's garbage collection to actually destroy the channel, and it might not be happening when you expect.  But I can't say for sure without seeing your code.

In any case, if your concern is that we will cache subchannels even after a channel is destroyed and then reuse those subchannels for a channel created later, the answer is that we should not do that (unless of course there is a third channel to the same server that existed before the first channel was destroyed and continued to exist until after the second channel was created).

However, it's also worth pointing out here that the intended use of the channel API is to create a single channel and leave it existing as long as you're going to need to use it.  You should not be creating a single channel for each RPC (or even small group of RPCs) you send, destroying it, and then creating another one a short time later.  Instead, just create it once, use it whenever you need to, and destroy it when the client is completely finished.

> I guess the meta-question is: how does one get proper server side load-balancing? I was going through default k8s load-balancer, and also using Envoy. Surely we don't want to overload one server from a client that produces a lot of work, especially if we have multiple servers to work with? What do you recommend as a standard way of doing this N clients to M servers through an LB where N << M?

The exact way that you want to set this up depends heavily on your environment and requirements.  Keep in mind, though, that even if clients split their load across multiple connections, you aren't actually guaranteed to spread load evenly across your backends, because you can't guarantee that Envoy will always send multiple connections from the same client to different backends.

An alternative would be to use a gRPC-level proxy (as opposed to an HTTP/2 proxy), which could spread the traffic out across the backends on a per-call (rather than per-connection) basis using either round_robin or grpclb.  That approach requires a bit more infrastructure, but it will probably yield better balancing (especially if you use grpclb with a balancer that knows the load of the individual backends).

**Comment by mradmila** [comment]
Thanks for your prompt replies. Perhaps it's worth-while popping back one level. My actual app, naturally, is not helloworld, but it exhibits the same behavior. I open a channel to the server pool for each request (which is perhaps silly), through LB (L4 or L7), which is a simple VIP from the client's perspective. Whether I use Python or C# did not seem to matter, unless I explicitly shutdown the channel (in C# by calling channel.ShutdownAsync, in which case I get different servers responding). I now tried caching the channel in Python, in 1.7.3, and I get the same behavior as 1.8 (connections go to the same server every time). This confirms your suspicion about Python and garbage collection.

I will likely end up using gRPC-level proxy at the end, but I am trying to understand how the whole system works, and what are my options. It seems like in 1.7.3 there was a mechanism that was cleaning up channels more proactively, in both C# and Python, and in 1.8 there is more caching happening behind the screens for multiple created channels (using the same subchannel I guess).

I do want to make sure that for streaming calls, since my app has state, I don't get multiple servers randomly responding (ping pong). That should never happen, correct?

Again, thanks a lot for your time and comments.

**Comment by markdroth** [comment]
> I do want to make sure that for streaming calls, since my app has state, I don't get multiple servers randomly responding (ping pong). That should never happen, correct?

Correct.  An individual RPC, whether unary or streaming, will always be to a single server.

**Comment by mradmila** [comment]
Sorry, another really quick question: there is no code today in grpc client that will say something like: "there are already 100 **concurrent** channels pounding on the same underlying connection/subchannel, let me pump in a few more subchannels and internally load-balance"?

**Comment by markdroth** [comment]
No, there is no such functionality today.  We've had some discussions about possibly supporting something like that in the context of avoiding HTTP/2 `MAX_CONCURRENT_STREAMS` limits (see #11704), but we have not yet agreed on anything.
