### ISSUE TITLE
TSAN failure in AsyncEnd2end/AsyncEnd2endTest.ShutdownThenWait/15 GRPC_POLL_STRATEGY=poll 

### ISSUE THREAD

**Issue by ncteisen** [grpc/grpc#14388]
Happens about 1% of the time

https://sponge.corp.google.com/target?id=b5cedbcc-ebd1-4f2b-abfd-b9911e6aee91&target=github/grpc/cpp_linux_tsan_native&searchFor=&show=ALL&sortBy=STATUS

https://sponge.corp.google.com/target?id=51ef4728-3f82-47c0-bcaf-1c065c0e06cd&target=github/grpc/cpp_linux_tsan_native&searchFor=&show=ALL&sortBy=STATUS

Test code that overrides poll_funtion is racing with pollset_work, which is actually calling that function

**Comment by vjpai** [comment]
Ok, the underlying issue is that we shouldn't be able to change `grpc_poll_function` while gRPC is active. The `async_end2end_test` assumed that it could do this at test SetUp and TearDown because there were not supposed to be other things lingering at those times. However, along the way, we introduced a timer thread. In this case, the timer thread hadn't yet finished polling at the time that the test wanted to shutdown (and change the poll function).

To fix this, I suggest need a new iomgr internal API for "set_poll_function" with the caveat that it only copies values into `grpc_poll_function` at `grpc_init`/`grpc_shutdown` time. When called, it just buffers up a value that'll actually get set into the global variable in the future.

Alternatively, we should stop testing this issue. This is a deep internal API thing and I'm not sure what it reveals.

**Comment by yang-g** [comment]
@vjpai, do you remember what we are trying to test with the overridden polling function?

**Comment by vjpai** [comment]
Nope, no idea. Let's kill it. The only thing that we need is a test somewhere that AsyncNext with timeout of 0 doesn't actually block.

While we're at it, do we have any justification for testing spin on the Verifier at all? The effect is to make AsyncNext have timeout of 0, but not sure why we would want that.

**Comment by vjpai** [comment]
Here was the original motivation, in a comment from Craig on one of my PRs.

"Removing the assert makes this a much weaker test... The original test provided guarantees that we never blocked calling code, which is important for many use cases (imagine a UI thread that wants to do some grpc work)... Overriding that here means that we're no longer providing such a guarantee."

That said, note that poll override only ever worked for POLL_STRATEGY=poll, not all the other variants that we've supported, and never worked for Windows. I think this (along with spin verifier) belongs in a test, but not in the async_end2end_test. Something separate that just tests this feature.
