### ISSUE TITLE
Client Side C++ exception in ClientContext destructor.

### ISSUE THREAD

**Issue by fronneburg** [grpc/grpc#14462]
If the ClientContext object's "recv_initial_metadata_" member has entries in its "map_", the ClientContext destructor crashes when trying to free the pair of string_ref's in the map.

**Comment by yang-g** [comment]
You will have to be more concrete on what is crashing and how. Or you can provide an example code to reproduce the issue. I do not see how a crash can happen as you described as string_ref is essentially a pointer and an integer.

Usually when we saw issues like this before, it is because memory corruption in other places, or maybe reusing a ClientContext or something.
