### ISSUE TITLE
Ruby user-agent grows longer with each new stub instantiated

### ISSUE THREAD

**Issue by duelinmarkers** [grpc/grpc#14477]
### What version of gRPC and what language are you using?

grpc-ruby/1.9.1
 
### What operating system (Linux, Windows, …) and version?
 
Linux 3.16.0-5-amd64 Debian 3.16.51-3+deb8u1 (2018-01-08) x86_64 GNU/Linux
 
### What runtime / compiler are you using (e.g. python version or version of gcc)
 
ruby 2.4.2p198 (2017-09-14 revision 59899) [x86_64-linux]
 
### What did you do?

We have a Ruby gRPC client test script that starts getting an error we'd never seen before after running for a while: `#<GRPC::ResourceExhausted: 8:to-be-sent initial metadata size exceeds peer limit>`. If we keep running it, it goes on to fail differently: `#<GRPC::Cancelled: 1:unknown cause>` with trailing metadata of `:status 431`. HTTP 431 is "Request Header Fields Too Large."

The test creates a new stub on each iteration. We tracked the issue down to the user-agent header growing by one "grpc-ruby/1.9.1 " prefix with each new stub. So requests from the first stub have `user-agent=grpc-ruby/1.9.1 grpc-c/5.0.0 (linux; chttp2; glossy)`. Requests from the second stub have `user-agent=grpc-ruby/1.9.1 grpc-ruby/1.9.1 grpc-c/5.0.0 (linux; chttp2; glossy)`, and so on.
 
### What did you expect to see?
 
`user-agent=grpc-ruby/1.9.1 grpc-c/5.0.0 (linux; chttp2; glossy)` all the way.
 
### What did you see instead?
 
Requests from the second stub have `user-agent=grpc-ruby/1.9.1 grpc-ruby/1.9.1 grpc-c/5.0.0 (linux; chttp2; glossy)`, and so on.

**Comment by apolcyn** [comment]
@duelinmarkers this is a guess: are you able to see if this leak still occurs on the `1.10.pre1` on `pre2` releases? 

I am wondering if this was possibly fixed by a PR that made it into the `1.10` branch (https://github.com/grpc/grpc/pull/14501).

If not, do you have any tips to reproduce beyond creating multiple stubs from the same process?
I am trying to reproduce this with the [greeter server](https://github.com/grpc/grpc/blob/master/examples/ruby/greeter_server.rb) and [client](https://github.com/grpc/grpc/blob/master/examples/ruby/greeter_client.rb) but it is not easily reproducing.

**Comment by jasonchangliu** [comment]
@apolcyn (I'm working with @duelinmarkers on this) We still see the issue on `1.10.pre1` and `pre2`. I've narrowed it down to an issue when we've specified channel_credentials. So, with a ruby client and java server, we've found that we only observe the user-agent growth issue when using SSL and goes away when SSL is removed, everything else the same. This is why the greeter server and client example isn't able to reproduce it.

**Comment by duelinmarkers** [comment]
I tracked this down to (1) the fact that we're reusing the same `channel_args` Hash to create each stub and (2) this code that mutates the input `channel_args` each time a new stub is created.

https://github.com/grpc/grpc/blob/59ea0ae3ebcca0aef5a15c5aa5b4d27b7f3fc9c4/src/ruby/lib/grpc/generic/client_stub.rb#L38-L43

I think it would be best for the grpc library to `channel_args.dup` before mutating it in `setup_channel`. If others agree we can submit a PR for this. For now we'll work around it by `.dup`ing the `channel_args` from our config when creating new stubs.

**Comment by apolcyn** [comment]
@duelinmarkers thanks for tracking this down. I agree that this API could be made safer by duping the channel args that are passed into it, but I'm not jumping on it just yet since I'm wondering if this kind of thing could break anyone.

However I <i>think</i> that duping the channel args internally is non-breaking, because it looks like the only thing it would prevent is the case when someone <i>wanted</i> their using string to get a `" grpc-ruby/#{VERSION}"` added to it on each new stub, which is unlikely.
