### ISSUE TITLE
Ruby clients raises `run_batch failed somehow` continuously  when a server is restarted suddenly

### ISSUE THREAD

**Issue by ahmadsherif** [grpc/grpc#14499]
Please answer these questions before submitting your issue. 
 
### What version of gRPC and what language are you using?
gRPC v1.8.3 and/or v1.9.1 for a Ruby client
 
### What operating system (Linux, Windows, …) and version?
 Linux, `uname -r => 4.14.13-1-ARCH`
 
### What runtime / compiler are you using (e.g. python version or version of gcc)
 ruby 2.4.1p111 (2017-03-22 revision 58053) [x86_64-linux]
gcc version 7.3.0 (GCC)
 
### What did you do?
An active Go server (i.e. serving requests from clients) is restarted.
 
### What did you expect to see?
We expected some transient errors on the clients then they should've been able to call the server once it's been up and running again.
 
### What did you see instead?
Some of the Ruby clients using grpc 1.8.3 start raising an exception with the message: "call#run_batch failed somehow", while clients running grpc 1.9.1 are stuck in [a loop](https://github.com/grpc/grpc/blob/91847795319dd0022e69f5d14b673d59e17a6de9/src/ruby/ext/grpc/rb_completion_queue.c#L45-L53). The loop is not the problem and it's probably a manifestation of the problem below.

### Reproducing steps / Debugging info

We couldn't make a minimal implementation to show the problem but we debugged the problem for some time, here are our findings that you may find helpful:

We did the debugging on one of the client running grpc 1.9.1 and we think (because the codebase is kinda complex to grok fully) that the problem is one of the subchannels (`grpc_subchannel`) is being reused over and over even when its `state_tracker.current_state_atm` is `4` or `GRPC_CHANNEL_SHUTDOWN`.

Digging further we found that this _unfortunate_ subchannel is not being unref-ed properly. In [this gist](https://gist.github.com/ahmadsherif/650efba28def7a2d7a8788cb4a1d2b56) we see how a _good_ subchannel is being ref-ed and unref-ed over its lifetime. In [another gist](https://gist.github.com/ahmadsherif/72ee699823949931219acf9d927bff23), however, we see that the _unfortunate_ subchannel is not being completely unref-ed and it continues to be so. 

We think that right after this [`[strong-unref]`](https://gist.github.com/ahmadsherif/72ee699823949931219acf9d927bff23#file-bad-subchannel-ref-unref-L35), [`on_resolver_result_changed_locked`](https://github.com/grpc/grpc/blob/91847795319dd0022e69f5d14b673d59e17a6de9/src/core/ext/filters/client_channel/client_channel.cc#L385) got executed (on another thread perhaps) and one of its effects is creating a new `subchannel_list` which creates a new `subchannel` which reuses existing subchannels (like our unfortunate one) which bumps the strong ref count on said subchannel. [Here is the backtrace](https://gist.github.com/ahmadsherif/92e5bc46da145f756acf33471d3bb017) we obtained when adding a watchpoint on `subchannel->ref_pairs` to see where the ref increment originates.

Finally, as a proof that this whole subchannel thing is the source of our problem, we compiled grpc with [this naive patch](https://gist.github.com/ahmadsherif/b861c70f048fffab2065df2287e7aced) and our clients are working properly under continuous server restarts, but that's not a solution and it probably leaks subchannels left and right :smile: .

cc/ @suprememoocow @jacobvosmaer

**Comment by jacobvosmaer** [comment]
To add a little context how this affects us (GitLab): since we upgraded our Ruby gRPC clients to 1.8.3 we see that the moment new gRPC server processes get deployed, a large number of clients start throwing GRPC::Unavailable errors with the message `14:Endpoint read failed`. They do not recover if we force them to create a new GRPC client stub; the only thing that works is to restart the client process.

As a workaround we are adding an exception handler in our application that will restart the current Ruby process the moment a `14:Endpoint read failed` exception is caught. This is a heavy-handed and desperate workaround.

If we were to upgrade to grpc 1.9, where the process just hangs instead of throwing an exception, things would be even worse because a hung Ruby process is harder to detect and react to than an exception.

So we are now stuck on grpc 1.8 in our Ruby clients.

If there is any way we can help diagnosing or fixing this issue please let us know. Thanks in advance!

**Comment by ahmadsherif** [comment]
We tried gRPC 1.10 and it seems to fix our issue, so I guess we can close this one. Thanks, guys.
