### ISSUE TITLE
Some release & debug libraries have the same name (VisualStudio / C++)

### ISSUE THREAD

**Issue by nweidmann** [grpc/grpc#14623]
### What version of gRPC and what language are you using?

Master C++ 
 
### What operating system (Linux, Windows, …) and version?
 
Windows
 
### What runtime / compiler are you using (e.g. python version or version of gcc)
 
 VisualStudio 2015

### What did you do?

Built gRPC (according to https://github.com/grpc/grpc/blob/master/INSTALL.md) using:

1. cmake .. -GNinja -DCMAKE_BUILD_TYPE=Release
2. cmake .. -GNinja -DCMAKE_BUILD_TYPE=Debug
 
### What did you expect to see?
 
A set of libraries to be used for release builds and a another set of libraries for debug builds.

I expected to have all debug libraries with different names as their release version.

### What did you see instead?
 
Most debug libraries have exactly the same name as their release version and only a few have a 'd' in their name:

Here the libs used for a simple project:

Release: grpc++.lib, grpc.lib, gpr.lib, libprotobuf.lib, crypto.lib, ssl.lib, zlib.lib
Debug: grpc++.lib, grpc.lib, gpr.lib, libprotobufd.lib, crypto.lib, ssl.lib, zlibd.lib

As you can see only libprotobufd.lib & zlibd.lib have different names.

### Anything else we should know about your project / environment?

The fact that most of the libraries have the same name, means that I have to have 2 sets of VisualStudio build environments.

1 with path to release libraries for release builds.
1 with path to debug libraries for debug builds.

**Comment by jtattermusch** [comment]
Pragmatically, different projects use different naming conventions for the libraries they generated.
In cmake world there is no consensus about whether the debug libraries on windows should have the "d" suffix or not. Protobuf and zlib (both are our dependencies and they are entirely separate projects) choose to use the "d" suffix for debug libraries, but other projects (like boringssl and grpc itself do not, as well as c-ares which your are not mentioning). I don't think we can be responsible for unifying the suffix conventions for projects that are out of our control.

I understand the pain around setting up your builds that use both grpc and protobuf and that it potentially adds complexity to your build files. On the other hand, this really depends on the way your CMakeLists.txt is designed and there are ways to write it in a way so that you don't run into the problem you are mentioning (again, there's no "standardized" way to write it in the cmake world).

Specifically:
- if you are adding grpc to your project using add_subdirectory(  ), you can refer to the grpc targets directly as `gRPC::grpc++` and similar - no need to use the filenames of the actual libraries.

- if you are adding grpc to your project via find_package(gRPC CONFIG), you can also refer to the grpc targets directly.

- if you are using ExternalProject_Add, I'd advise you to use the "superbuild" technique so you avoid recreating the grpc targets manually (as `IMPORTED` targets).

Seeing an example of your CMakeLists.txt would be helpful (it seems like you are manually importing the grpc and protobuf libraries using the resulting filenames).

Some very useful examples how to use gRPC with cmake are here:
https://github.com/grpc/grpc/blob/master/examples/cpp/helloworld/CMakeLists.txt
https://github.com/grpc/grpc/blob/master/examples/cpp/helloworld/cmake_externalproject/CMakeLists.txt
(as you can see, none of the examples suffers from the "inconsistent suffix" problem).
