### ISSUE TITLE
exception thrown from stub code results in server crash

### ISSUE THREAD

**Issue by nweidmann** [grpc/grpc#14622]
### What version of gRPC and what language are you using?

Master C++ 
 
### What operating system (Linux, Windows, …) and version?
 
 Windows

### What runtime / compiler are you using (e.g. python version or version of gcc)
 
VisualStudio 2015
 
### What did you do?

stub method throws exception:

throw std::exception("Hello");
 
### What did you expect to see?
 
I expected the client application to get a status != OK with the message "Hello"
 
### What did you see instead?

Server crash.
 
### Anything else we should know about your project / environment?

This works perfectly in the Java server implementation. Server does not crash and the client get a bad status.

**Comment by vjpai** [comment]
When you say "stub code", do you mean the method handler in the service? We
do catch exceptions in the C++ sync server and return them with a failed
status, but we cannot return the content of the exception since it might be
private to the server. You are certainly welcome to wrap your method
handler internal code in a catch block if you need to see the exception
content.

So the crash is surprising to me; can you try running the exception_test on
your system? It's one of our build targets for testing.

**Comment by nweidmann** [comment]
Yes, I mean the method handler in my service.

Regarding the fact that you "cannot" return the content of the exception I partially disagree.
I agree regarding unknown exception types, but you could at least catch std::exception and send it's message back to the client application...

I know that the correct way of doing it would be to handle all exception within the application code, but gRPC should guard itself from baldy implemented application code.

I ran my test in debug and there is NO try / catch anywhere in the gRPC framework if you following the stack dump.

Here is my code:

grpc::Status getData(grpc::ServerContext* context, const MyService::DataRequest* request, MyService::DataReply* response) 
{
   throw std::exception("Hello");
}

And the call stack:

1. grpc::internal::RpcMethodHandler<gRPC::TestService::Service,gRPC::DataRequest,gRPC::DataReply>::RunHandler(const grpc::internal::MethodHandler::HandlerParameter & param)
2. grpc::Server::SyncRequest::CallData::Run(std::shared_ptr<grpc::Server::GlobalCallbacks> global_callbacks)
3. grpc::Server::SyncRequestThreadManager::DoWork(void * tag, bool ok)
4. grpc::ThreadManager::MainWorkLoop()
5. grpc::ThreadManager::WorkerThread::Run()

Why not have a try / catch around:

status = func_(....) in grpc::internal::RpcMethodHandler<gRPC::TestService::Service,gRPC::DataRequest,gRPC::DataReply>::RunHandler

Thanks for your help,

Nicolas

**Comment by vjpai** [comment]
I know your post listed that you're at master, but we do have a try/catch block in master (see https://github.com/grpc/grpc/blob/master/include/grpcpp/impl/codegen/method_handler_impl.h#L40),
 which is called from the top function in your stack trace (see https://github.com/grpc/grpc/blob/master/include/grpcpp/impl/codegen/method_handler_impl.h#L67 ). It has been this way for more than a month now (ever since #13815 ). These are protected in code blocks, but the default value is to allow exceptions for all Windows platforms and for Posix platforms where the compiler defines `__EXCEPTIONS`. Can you check the commit that you're at?

As for the suggestion that we return the error message specified in `std::exception` back to the client, our original plan was to do that, but it was pointed out in the [discussion thread for the exception handling proposal](https://groups.google.com/d/msg/grpc-io/u1XmQPAi3fA/lcaIHEegBQAJ) that it's very unsafe to do that. We have no control over what the server method handler has in its exceptions, particularly since the exception could be arbitrary levels deep in a call chain.

**Comment by nweidmann** [comment]
I had a lot lately to do and didn't update for a few weeks...

I updated today and everything works fine !

I have read the discussion thread, and the reason you are not forwarding (application) std::exception messages from within the gRPC framework makes 100% sense!

Thanks a lot for your help.

I will close this case.

Have a nice day,

Nicolas
