### ISSUE TITLE
channel_ready_future().result() should return the channel, not None

### ISSUE THREAD

**Issue by michaelsafyan** [grpc/grpc#14778]
### What version of gRPC and what language are you using?
The Google internal version (which I believe tracks the latest release here).
 
### What operating system (Linux, Windows, …) and version?
 Linux
 
### What runtime / compiler are you using (e.g. python version or version of gcc)
Python 2.7 
 
### What did you do?

    def NewChannel(self):
        channel_credentials = self._FetchCredentials()
        channel = grpc.secure_channel(
            'localhost:{}'.format(self._port), channel_credentials)
        return grpc.channel_ready_future(channel).result()

### What did you expect to see?
 
I was expecting the result of "NewChannel" to be the channel, itself.
 
### What did you see instead?

Apparently, channel_ready_future's "result" is always None. Apparently the correct code (with the gRPC code as it is right now) is:

    def NewChannel(self):
        channel_credentials = self._FetchCredentials()
        channel = grpc.secure_channel(
            'localhost:{}'.format(self._port), channel_credentials)
        grpc.channel_ready_future(channel).result()
        return channel
 
However, this is because the behavior of ChannelReadyFuture violates the principle of least surprise; a future whose name is described with the name of some other noun should be returning an object of that noun type on completion; a "channel ... future" should be returning a channel.

**Comment by nathanielmanistaatgoogle** [comment]
This is something we considered and deliberately decided against, because we (1) don't like APIs that give to the user something they already have (the channel, in this case) and (2) your ellipsis captures too much; it's not the channel that the `Future` is "computing" but rather the "readiness of the channel" (which is more of a "state of the world" than a simple value that can be returned).

Something that's worth exploring is how much the semantics of the object returned by `channel_ready_future` really matter - when we were building gRPC Python the forecast was that channel connectivity would be something of an edge case and that the vast majority of users would, wanting to make an RPC but not having a channel, just construct a channel and use it to invoke an RPC without intermediately waiting for the channel to be ready. Help us understand what you're doing and why you need to block until the channel is ready in a separate statement of code?
