### ISSUE TITLE
C# grpc client - No RpcException raised when call deadline exceeded for server to client streaming

### ISSUE THREAD

**Issue by vishal-uttamchandani** [grpc/grpc#14799]
**Environment**
OS: windows
Language: C#
Version: Grpc 1.10.0, Grpc.Core 1.10.0
Reference project to demo this issue can be found [here](https://github.com/vishal-uttamchandani/grpc-noexception)

Somewhat related issue #2685. But this one mentions the status to be either "Internal" or "DeadlineExceeded". I am getting "Ok" as the status.

**Issue**
No RpcException is raised once the deadline is exceeded for the call. Instead, the call just silently fails
 
**Scenario**
I created a reference project to demonstrate the issue. 
- Client sets a call deadline of 5 seconds to fetch messages from the server
- Server streams 20 messages to the client
- On receiving each message client simulates a delay of 1 second before moving on to processing the next message
- After 5 messages (as expected because of the deadline set), the call silently fails with status as OK.

**Expected**
RpcException with status DeadlineExceeded

**Actual**
Status is OK and no exception received

**Comment by jtattermusch** [comment]
I ran your example and I confirm I am seeing the same behavior you are.

Nevertheless, you example is kind of an edge case:
- your server sends all 20 responses immediately after the server side handler is invoked and returns immediately after that. That means that the server-side logic will send the call trailers and OK status very shortly after the call has started (e.g. much sooner than in 5 seconds). The messages and the final status will all be sent to the client almost immediately because the messages you are sending are very small and all the data fits into the current flow control window, so it is allowed to go on the wire.

- the client processes one message per second, which looks like that should lead to a deadline exceeded, after 5secs, but in reality, the call internally receives all the messages and the final status almost immediately - again this is because the messages being sent are very small and they have already been sent by the server at once or in very fast succession.  So as far as grpc internals are concerned, the call has finished in well under 5secs (as all the responses and status was received quickly) and you are just reading the already-received messages that gRPC has buffered for you (and you are doing that at a rate of 1msg per sec).

- the OK status is received from the server well within the deadline, which I guess is the more precise definition of what it means for a call to "finish on time".

Here's what would change the behavior of the client:
- if you were sending large messages, the grpc flow control mechanism would kick in and you would actually the the call fail with deadline_exceeded, because the flow control wouldn't allow all the messages to be written on the wire immediately and the server would wait for the response to be processed at the client side.

- if the server was explicitly waiting to receiving messages from the client (as "confirmations"), the call would end with deadline_exceeded as well, because the OK status wouldn't be received within the deadline (and that would be guaranteed by waiting on the confirmations). So depending on your application logic, you might need to adjust the semantics of how the server and the client exchange messages with each other.

**Comment by jtattermusch** [comment]
As supporting evidence here's a log of the client with `GRPC_TRACE=http` enabled:

It clearly shows that the call status is received by the time you have received `Message 1` (see end of the log) on the client.
```
D0406 13:32:11.743171 0 C:\jenkins\workspace\gRPC_build_artifacts\platform\windows\workspace_csharp_ext_windows_x86\src\core\ext\transport\chttp2\transport\chttp2_transport.cc:2512: ipv4:127.0.0.1:50051: Complete BDP ping err="No Error"
I0406 13:32:11.744174 0 C:\jenkins\workspace\gRPC_build_artifacts\platform\windows\workspace_csharp_ext_windows_x86\src\core\ext\transport\chttp2\transport\parsing.cc:624: parsing initial_metadata
D0406 13:32:11.744174 0 C:\jenkins\workspace\gRPC_build_artifacts\platform\windows\workspace_csharp_ext_windows_x86\src\core\ext\transport\chttp2\transport\hpack_parser.cc:635: Decode: ':status: 200', elem_interned=1 [3], k_interned=1, v_interned=1
I0406 13:32:11.744174 0 C:\jenkins\workspace\gRPC_build_artifacts\platform\windows\workspace_csharp_ext_windows_x86\src\core\ext\transport\chttp2\transport\parsing.cc:406: HTTP:1:HDR:CLI: :status: 32 30 30 '200'
D0406 13:32:11.744174 0 C:\jenkins\workspace\gRPC_build_artifacts\platform\windows\workspace_csharp_ext_windows_x86\src\core\ext\transport\chttp2\transport\hpack_parser.cc:635: Decode: 'content-type: application/grpc', elem_interned=1 [3], k_interned=1, v_interned=1
I0406 13:32:11.744174 0 C:\jenkins\workspace\gRPC_build_artifacts\platform\windows\workspace_csharp_ext_windows_x86\src\core\ext\transport\chttp2\transport\parsing.cc:406: HTTP:1:HDR:CLI: content-type: 61 70 70 6c 69 63 61 74 69 6f 6e 2f 67 72 70 63 'application/grpc'
D0406 13:32:11.744174 0 C:\jenkins\workspace\gRPC_build_artifacts\platform\windows\workspace_csharp_ext_windows_x86\src\core\ext\transport\chttp2\transport\hpack_parser.cc:635: Decode: 'grpc-accept-encoding: identity,deflate,gzip', elem_interned=1 [3], k_interned=1, v_interned=1
I0406 13:32:11.744174 0 C:\jenkins\workspace\gRPC_build_artifacts\platform\windows\workspace_csharp_ext_windows_x86\src\core\ext\transport\chttp2\transport\parsing.cc:406: HTTP:1:HDR:CLI: grpc-accept-encoding: 69 64 65 6e 74 69 74 79 2c 64 65 66 6c 61 74 65 2c 67 7a 69 70 'identity,deflate,gzip'
D0406 13:32:11.744174 0 C:\jenkins\workspace\gRPC_build_artifacts\platform\windows\workspace_csharp_ext_windows_x86\src\core\ext\transport\chttp2\transport\hpack_parser.cc:635: Decode: 'accept-encoding: identity,gzip', elem_interned=1 [3], k_interned=1, v_interned=1
I0406 13:32:11.744174 0 C:\jenkins\workspace\gRPC_build_artifacts\platform\windows\workspace_csharp_ext_windows_x86\src\core\ext\transport\chttp2\transport\parsing.cc:406: HTTP:1:HDR:CLI: accept-encoding: 69 64 65 6e 74 69 74 79 2c 67 7a 69 70 'identity,gzip'
D0406 13:32:11.746179 0 C:\jenkins\workspace\gRPC_build_artifacts\platform\windows\workspace_csharp_ext_windows_x86\src\core\ext\transport\chttp2\transport\chttp2_transport.cc:1635: perform_stream_op[s=07B919DC]:  RECV_MESSAGE
D0406 13:32:11.746179 0 C:\jenkins\workspace\gRPC_build_artifacts\platform\windows\workspace_csharp_ext_windows_x86\src\core\ext\transport\chttp2\transport\chttp2_transport.cc:1345: perform_stream_op_locked:  RECV_MESSAGE; on_complete = 07B9195C
D0406 13:32:11.746179 0 C:\jenkins\workspace\gRPC_build_artifacts\platform\windows\workspace_csharp_ext_windows_x86\src\core\ext\transport\chttp2\transport\chttp2_transport.cc:1190: complete_closure_step: t=029F6130 07B9195C refs=0 flags=0x0000 desc=op->on_complete err="No Error" write_state=IDLE
I0406 13:32:11.747181 0 C:\jenkins\workspace\gRPC_build_artifacts\platform\windows\workspace_csharp_ext_windows_x86\src\core\ext\transport\chttp2\transport\parsing.cc:629: parsing trailing_metadata
D0406 13:32:11.747181 0 C:\jenkins\workspace\gRPC_build_artifacts\platform\windows\workspace_csharp_ext_windows_x86\src\core\ext\transport\chttp2\transport\hpack_parser.cc:635: Decode: 'grpc-status: 0', elem_interned=1 [3], k_interned=1, v_interned=1
I0406 13:32:11.747181 0 C:\jenkins\workspace\gRPC_build_artifacts\platform\windows\workspace_csharp_ext_windows_x86\src\core\ext\transport\chttp2\transport\parsing.cc:487: HTTP:1:TRL:CLI: grpc-status: 30 '0'
D0406 13:32:11.747181 0 C:\jenkins\workspace\gRPC_build_artifacts\platform\windows\workspace_csharp_ext_windows_x86\src\core\ext\transport\chttp2\transport\hpack_parser.cc:635: Decode: 'grpc-message: ', elem_interned=1 [1], k_interned=1, v_interned=1
I0406 13:32:11.747181 0 C:\jenkins\workspace\gRPC_build_artifacts\platform\windows\workspace_csharp_ext_windows_x86\src\core\ext\transport\chttp2\transport\parsing.cc:487: HTTP:1:TRL:CLI: grpc-message:
Message: 1
```

**Comment by vishal-uttamchandani** [comment]
@jtattermusch So to summarize, depending upon the size of messages the grpc flow control behaves differently ?  I was curious to see if other implementations have a similar issue. So I implemented the same scenario is Go and it did actually raise the deadline exceeded exception after processing 5 messages. 

I have added executable to the project so that it can be easily run from mac or windows. Project can be found [here](https://github.com/vishal-uttamchandani/grpc-deadline-exceeded)

Thanks for looking into this. Much appreciated.

**Comment by tomcain** [comment]
@jtattermusch I believe this should still be considered a bug in the C# grpc library. As per your explanation, the grpc client did indeed receive all of the streamed messages within the deadline, however the client code, within it's stream processing loop, took longer than the deadline to process the messages.

If you consider the grpc call to be successful simply after the internal grpc buffer has received all the streamed messages, then the client code should be allowed to process all of the messages in the buffer regardless of deadline. Currently, the grpc flow control simply stops sending messages to the client code.

If, instead, you consider the grpc call to be successful after both the internal grpc buffer has received all of the streamed messages, AND after the client code has processed all of the messages (i.e. exited the stream processing loop), then the "deadline exceeded" exception should be raised accordingly if it is exceeded while in the grpc loop in the client code.

I also don't believe this is an edge case> The example that @vishal-uttamchandani put together is a simplification of the problem that was used to produce the issue consistently. I believe this is a race condition that could definitely occur with larger messages as well.

**Comment by jtattermusch** [comment]
In any case, this issue is almost certainly coming from C core and therefore is not just C# specific, but should be reproducible in all C core  based languages.

CC @srini100

**Comment by jtattermusch** [comment]
@markdroth, what is our take on interpretation of the deadline semantics? (this item is either a bug or "working as intended" depending on that).
