### ISSUE TITLE
http2 exception, cause=io.netty.handler.codec.http2.Http2Exception: First received frame was not SETTINGS. Hex dump for first 5 bytes: 1503010002

### ISSUE THREAD

**Issue by huang7230468** [grpc/grpc#14866]
Today ,  I want to test fabric network ,so I get the demo what used the grpc ,when I try ,append the error , I know the problem is frame or setting, but I don`t konw how to do resolve it ; Please help me ,thanks you !!!
The following content is the error

_**Caused by: org.hyperledger.fabric.sdk.exception.ProposalException: getConfigBlock for channel firstChannel failed with peer peer0.org1.example.com.  Status FAILURE, details: Sending proposal to peer0.org1.example.com failed because of: gRPC failure=Status{code=INTERNAL, description=http2 exception, cause=io.netty.handler.codec.http2.Http2Exception: First received frame was not SETTINGS. Hex dump for first 5 bytes: 1503010002**_

**Comment by ericgribkoff** [comment]
This is probably more appropriate for the https://github.com/grpc/grpc-java repo, since it involves Netty. The error message indicates that you are probably either connecting to a non-gRPC server ,or trying to connect via plaintext when the server expects TLS. Can you provide details about how you're constructing your client channel, and what server you are trying to connect to?
