### ISSUE TITLE
Support custom path prefix in gRPC service URL

### ISSUE THREAD

**Issue by sandersaares** [grpc/grpc#14900]
I have multiple instances of my gRPC server app running on my servers. My deployment model would be greatly simplified if I could route requests to these based on path, as follows:

* myserver/path1/myApi/call1 goes to instance1
* myserver/path2/myApi/call1 goes to instance2

Now that nginx supports gRPC routing, this seems trivial to set up from the routing side. Alas, it does not seem to work. Possibly this is a gRPC client limitation? I am unable to get (or do not know where to get) detailed information about why my connections fail if I try this. I assume it is not supported.

Using subdomains is not an appropriate workaround for me, as that is hard to automate.

Using custom ports for each service is my only option but this is very cumbersome and yet again, not easily automatable.

I therefore request the ability to specify a custom path be added, so that nginx could be used for convenient routing in such a situation.

To be clear, the idea is not to have gRPC client or server behave differently, just to provide the path to nginx as a routing tag, to be stripped after routing. In a manner analogous to using a different hostname or port.

**Comment by ericgribkoff** [comment]
Can you post the nginx config (or just the gRPC-relevant parts) that you are using? Also, how are you setting `path1` and `path2` for the client calls in your example - are the two paths coming from different proto service definitions?

**Comment by sandersaares** [comment]
Here is an example nginx config I would like to use for this:

```
	server {
		listen 82 http2 default_server;

		# Instance 1 in Docker container 1
		location /foo/ {
			grpc_pass grpc://10.0.4.235:5124;
		}
		# Instance 1 in Docker container 2
		location /bar/ {
			grpc_pass grpc://10.0.4.236:5124;
		}
	}
```

The way I would like to use it (C# example here) is by specifying the path in the Channel constructor, where one would normally use just the host:port pair, as `new Channel("localhost:82/foo")`. This currently creates a channel without throwing any exceptions but no traffic seems to reach nginx if a path is present, as far as I can tell.

**Comment by ericgribkoff** [comment]
Your use case makes sense. But I think you want to set this up using `:authority` rather than URI paths. The host used to create the channel does not go into the path used by gRPC (the channel builder arg should not include the "/foo" portion from your example). Instead, HTTP/2 paths are specified in a [`:path`](https://tools.ietf.org/html/rfc7540#section-8.1.2.3) header field, and gRPC clients generate these from the proto service definition in the form `protoPackage.serviceName.methodName` (see [here](https://github.com/grpc/grpc/blob/master/doc/PROTOCOL-HTTP2.md#requests)).

I believe that you can accomplish your goal via setting the `default_authority` channel option, which is similar to setting a virtual hostname: it looks like you can set this in C# [here](https://github.com/grpc/grpc/blob/5253c8f9a899450397a5e46e4923d01ac9a66a27/src/csharp/Grpc.Core/ChannelOptions.cs#L152) and it will be used as the `:authority` HTTP/2 header. I am most familiar with our java implementation, and there are some comments on the use of the override authority feature in the [javadoc](https://github.com/grpc/grpc-java/blob/9be41ba0e84d85b9c9a96992d8158c2e95cb3050/core/src/main/java/io/grpc/ManagedChannelBuilder.java#L135). At least with Java, using this with TLS will require the overridden authority to still appear on your server's cert - I believe the same is true for wrapped languages (including C#), but if you plan to use this in production this should be verified.

I'm still getting up to speed with nginx's gRPC support, but it should support routing requests based on the `:authority` HTTP/2 header. Let me know if this approach works for you, or if you encounter any issues.

**Comment by sandersaares** [comment]
I confirm that setting `default_authority` and configuring nginx with individual `server` blocks for each route appears to work great. Thank you for the assistance!

**Comment by ericgribkoff** [comment]
Great, glad that worked for you! I'll mark this issue as closed.

**Comment by NicolasDorier** [comment]
@sandersaares  Can you share how you used authority routing in the nginx config?

**Comment by sandersaares** [comment]
@NicolasDorier here is an example for the "abc" authority. For multiple authority strings, I just add multiple server blocks.

```
 server {
                listen 82 http2;
                server_name abc;

                location / {
                        grpc_pass grpc://172.31.250.1:82;
                }
        }
```

**Comment by NicolasDorier** [comment]
Ah so you need different port for each :/

**Comment by sandersaares** [comment]
No, you can have multiple server blocks use the same port.

**Comment by NicolasDorier** [comment]
This is awesome, thanks a lot.
