### ISSUE TITLE
Expose C# API to set env-driven variables via code

### ISSUE THREAD

**Issue by sandersaares** [grpc/grpc#14963]
I wish to configure `GRPC_VERBOSITY` from my C# code, as my deployment model does not make it easy to use environment variables. I see a `gpr_set_log_verbosity` function in the C core but this does not appear to be exposed to C# anywhere, as far as I can tell.

I request that such a member be added to the API. I would like to be able to configure all the environment variable driven options from C# code. The `GrpcEnvironment` class would seem like a good host for this functionality.

**Comment by jtattermusch** [comment]
Did you try this workaround?
before calling any gRPC methods, just set the environment variables programmatically by `SetEnvironmentVariable(string variable, string value)`?
https://msdn.microsoft.com/en-us/library/z46c489x(v=vs.110).aspx

In addition to that, for filtering out some C-core logs in the C# layer, you can also use some stuff from https://github.com/grpc/grpc/tree/master/src/csharp/Grpc.Core/Logging (e.g. see `LogLeverFilterLogger`).

**Comment by sandersaares** [comment]
I tried - it worked on Windows but had no effect on Linux. I assume `SetEnvironmentVariable` only updated some cached list on Linux netcore.

**Comment by jtattermusch** [comment]
I think we could expose the `gpr_set_log_verbosity` function. Do you have suggestions where in the API it would make sense to expose it?

**Comment by sandersaares** [comment]
It seems to be a global setting, so perhaps GrpcEnvironment? Very much related to this are also the `GRPC_TRACE` values that actually control what goes into the log, which should also be settable for this to be optimally useful.

**Comment by Falco20019** [comment]
Just to add some more context on why it's not working:
[`SetEnvironmentVariable(string variable, string value)`](https://docs.microsoft.com/en-us/dotnet/api/system.environment.setenvironmentvariable?view=netcore-2.2#System_Environment_SetEnvironmentVariable_System_String_System_String_System_EnvironmentVariableTarget_) is the overload for [`SetEnvironmentVariable (string variable, string value, EnvironmentVariableTarget target)`](https://docs.microsoft.com/en-us/dotnet/api/system.environment.setenvironmentvariable?view=netcore-2.2#System_Environment_SetEnvironmentVariable_System_String_System_String_System_EnvironmentVariableTarget_) with `EnvironmentVariableTarget.Process`. So all changes using the simple call are in-process only. There are `EnvironmentVariableTarget` values for `Machine` and `User` too, but those are not supported on Linux/Mac and won't ever be due to technical limitations (see https://github.com/dotnet/corefx/issues/32685 & https://github.com/dotnet/corefx/issues/33745).

I'm looking forward to have them in `GrpcEnvironment`.

**Comment by lobster2012-user** [comment]
As I understand it, only the native call 'setenv' will help us (at your own risk and fear, given the lack of security, the call in different streams)

**Comment by lobster2012-user** [comment]
Slightly edited the current code, made the changes described above. In windows, everything works, it did not launch in linux.

**Comment by jtattermusch** [comment]
This is still an issue.

**Comment by Falco20019** [comment]
Just got another user issue about this: https://github.com/jaegertracing/jaeger-client-csharp/issues/174

**Comment by jtattermusch** [comment]
We acknowledge this to be a valid feature request but since no one has come forward to implement this, we are going to close it for now while maintaining the label/Help wanted to indicate that this can be picked up as future work
