### ISSUE TITLE
C# Grpc.Tools package on Nuget UX issue: non-executable protoc/plugin binaries

### ISSUE THREAD

**Issue by mehrdada** [grpc/grpc#14975]
The Kokoro package build process somehow loses the executable flag on `protoc` between artifact build and package build. Therefore the tools packages will just bundle non-executable protoc.

This does not affect Python because `protoc` executable is not there at all and its source is compiled with the plugin source as a singular Python extension.

**Comment by mehrdada** [comment]
cc @apolcyn 

@matt-kwong: Any idea why this happens? We are thinking of explicitly adding a `chmod` to package build scripts to work around this, but do you think something else might be easier?

**Comment by matt-kwong** [comment]
My understanding is that the build artifacts job uploads to GCS, and then the build packages pulls from GCS. Was this not an issue when we used Kokoro for v1.10.x?

**Comment by mehrdada** [comment]
It is an issue for the 1.10 as well :(, but no one noticed. Do distribtests happen to test the tools package as well as the grpc package?

**Comment by matt-kwong** [comment]
I'm not sure. @jtattermusch would be better equipped to answer that. 

I think we can go with the `chmod` workaround if we want to do the release before Jan can look into this on Monday.

**Comment by jtattermusch** [comment]
@mehrdada , currently no distribtests (AFAIK C#, python, php, ruby) are testing the Tools packages - that's an enhancement we always wanted to add but never did so. Currently all that most of the distribtests do is to install the package and try to create a channel (which verifies that the native library gets loaded correctly - see e.g. https://github.com/grpc/grpc/blob/d81271f16dfa31274dddcf34e8695f73f616abbe/test/distrib/csharp/DistribTest/Program.cs)

Ideally we would also like to test the codegen phase and run a simple example (like helloworld) using that generated code.

The only difference is C++, which has a distribtests that also does the codegen (both helloworld and routeguide), but C++ is different than other languages as it doesn't really have any packaging system.

**Comment by mehrdada** [comment]
The Ruby part of this issue is resolved. I decreased the priority to P2 and made the issue focus on C# only.

**Comment by jtattermusch** [comment]
This might have to do with https://github.com/NuGet/NuGet.Client/pull/1346.

**Comment by jtattermusch** [comment]
@mehrdada   I spent some time looking into this and it seems that the problem with protoc and grpc_csharp_ext packaged in  Grpc.Tools for C#  having non-executable flags is a problem of the nuget tool, rather than something coming from  kokoro artifact copying.

AFAIK, nuget packages are just zip files and they don't have any notion of executable flag (and the Grpc.Tools package is being packaged on windows machine anyway). the nuget command line tool is supposed to add executable flag when unpacking the archive on unix platforms (and that might have been broken in the past (NuGet/NuGet.Client#1346). 

Have you seen any other C# problem with Grpc.Tools  (e.g.  failing to build the Grpc.Tools package in the build_packages step), or you just saw that protoc  doesn't have the executable flag set on linux after unpacking?

**Comment by mehrdada** [comment]
@jtattermusch I noticed that the executable flag gets removed by Nuget when archiving. I think if there are any issues it is in Nuget domain to fix. I'm closing this.
