### ISSUE TITLE
go: gRPC routing without specifying port

### ISSUE THREAD

**Issue by JCzz** [grpc/grpc#15186]
New to gRPC - question/issue:

Also on stackoverflow.com: https://stackoverflow.com/questions/50005666/go-grpc-routing-without-specifying-port

Having a gRPC client, how do you use routing?

My gRPC server is at this local path 10.0.1.6/hw.

It is running and listening in a Kubernetes pod and it is working internally, if I run it in a pod. But I am now accessing it via url.

But how do I test that it actually is working with the routing without a port number?

```
const (
    address     = "10.0.1.6:80/hw"
    defaultName = "World"
)

var (
    conn *grpc.ClientConn
    c    pb.GreeterClient
)

func setupRPC() {

    var err error
    conn, err = grpc.Dial(address, grpc.WithInsecure())
    c = pb.NewGreeterClient(conn)
    if err != nil {
        log.Fatalf("did not connect: %v", err)
    }

}
```
I get this error:

could not greet: rpc error: code = Unavailable desc = all SubConns are in TransientFailure, latest connection error: connection error: desc = "transport: Error while dialing dial tcp: lookup tcp/80/hw: nodename nor servname provided, or not known"
Do you know how? Or how to test gRPC endpoints?

**Comment by lyuxuan** [comment]
Hi @JCzz,
For the way you dial, we (grpc) will simply pass the target "10.0.1.6:80/hw" to golang standard library for creating a connection, like this [`net.DialContext(ctx,"tcp","10.0.1.6:80/hw")`](https://golang.org/pkg/net/#Dialer.DialContext). The error you got really originated inside golang net dialing function and more specifically - the name resolution mechanism it used. I tried locally, and the error I got is "unknown port" (golang default resolver behavior) instead of "nodename nor servname provided, or not known". You can try file an issue for Kubernetes to see if they do anything special regarding name resolution. 

PS: grpc-go has a sub repository, https://github.com/grpc/grpc-go. It's better to file go specific issues there. Thanks!

**Comment by JCzz** [comment]
Hi @lyuxuan
Thank you for you insight, I will go and fille an issue on Kubernetes.

Thanks and this can be closed
