### ISSUE TITLE
protoc plugins not installed by install target

### ISSUE THREAD

**Issue by Ozaq** [grpc/grpc#15228]
### What version of gRPC and what language are you using?
v1.11.0 (bd44e485f69d70ca4095cea92decd98de3892aa6)
 
### What operating system (Linux, Windows, …) and version?
Windows 7
 
### What runtime / compiler are you using (e.g. python version or version of gcc)
Visual Studio 15.5.1
 
### What did you do?
Followed the build instructions from Install.md (build & install with ninja)
 
### What did you expect to see?
Install directory should contain protoc plugins such as grpc_cpp_plugin.exe
 
### What did you see instead?
No protoc plugins have been installed. I can see they have all been build and are located in the .build folder.

**Comment by Ozaq** [comment]
After reading further I have come to the understanding that due to #10759 gRPC_INSTALL is set to OFF when using ny dependency from git-submodules. Unfortunately this means that the installation guide is incorrect. Further it seems impossible to build & install on Windows with BoringSSL since the package variant does only search for openssl. 

I am aware that I can still build and create my own installation script but that's a lot of work :(

**Comment by jtattermusch** [comment]
@Ozaq I agree with your assesment, but it is unclear to me what can be done about this. 
In cmake world, it is incorrect to perform installation of your submodules  while performing cmake install (and cmake actually wouldn't allow it, which is why autodisabling of gRPC_INSTALL has been introduced in the past) - you should install all your dependencies separately and then install grpc. This process can be simplified by e.g. using cmake's ExternalProject_Add feature.

Here are examples of various (tested) ways how to install gRPC with cmake
https://github.com/grpc/grpc/tree/master/test/distrib/cpp Each of these approaches has its limitations, so you have to choose which 
I think the solution that might be best for your case it to use the cmake "superbuild" approach.

**Comment by Ozaq** [comment]
@jtattermusch I understand that there is no easy solution, but it was very surprising to have to read that kind of information from the cmake files (and the issue tracker). The part that irritated me most was that install does seemingly succeed just that there are some files missing. I would rather prefer the install targets to be completely disabled so that I do not get the impression there is a working install step.

**Comment by jtattermusch** [comment]
@Ozaq   thanks for the feedback, I think you have a point - we are working on improving the cmake  (and/or build instructions in gereral) instructions so that there's no confusion.
