### ISSUE TITLE
Running tests with Python3.5 and 3.6 actually runs with 2.7

### ISSUE THREAD

**Issue by nathanielmanistaatgoogle** [grpc/grpc#15253]
On my machine (Ubuntu 17.04) with both `/usr/bin/python3.5` and `/usr/bin/python3.6` available, an invocation of `./tools/run_tests/run_tests.py --language=python --compiler=all_the_cpythons --newline_on_success` brings about the creation of `py35_native` and `py36_native` directories. That's great.

But then the Pythons in those virtual environments turn out to be symlinks to `python2`: `py35_native/bin/python --version` prints "Python 2.7.13".

If there's some problem constructing the `py35` and `py36` environments, then construction should fail rather than silently fall back to Python 2.

**Comment by matt-kwong** [comment]
That's something we do in [`build_python.sh` ](https://github.com/grpc/grpc/blob/master/tools/run_tests/helper_scripts/build_python.sh#L140). This was added 2 years ago in #6791, and I'm okay with removing this because it leads to misleading results. 

Just making sure though, after looking at the context from that lengthy PR, do you still prefer to get rid of the fallback?

**Comment by nathanielmanistaatgoogle** [comment]
@matt-kwong: after reviewing the context... yes, I think it's the right call to fail if the appropriate Python interpreter isn't available rather than use another Python interpreter.
