### ISSUE TITLE
Python grpcio 1.12.0 no longer depends on protobuf (breaking change)

### ISSUE THREAD

**Issue by mbyio** [grpc/grpc#15406]
### What version of gRPC and what language are you using?
 
Python, 1.12.0
 
### What operating system (Linux, Windows, …) and version?
 
Linux, Mac OS X

Window was not tested.
 
### What runtime / compiler are you using (e.g. python version or version of gcc)
 
Python 2.7 and Python 3.6
 
### What did you do?

We have a library that just specifies installing `grpcio>=1.8.2, <2.0.0`. A specific test case would be `pip install grpcio 1.12.0`.
 
### What did you expect to see?

I expected to get the latest version of grpcio and to have no breaking changes.
 
### What did you see instead?

A breaking change (broke our CI builds).
 
The `protobuf` package is no longer installed. A look inside the generated wheel for Mac indicates that it is no longer listed as a requirement. Since our library was not using protocol buffers outside of GRPC, it now no longer builds since the compiled protobuf files are no longer importable (they try to import the `protobuf` package).
 
### Anything else we should know about your project / environment?

If this was intended, it's not a big deal, but I would suggest that the GRPC documentation should be updated since IMO it isn't clear that the `grpcio` library does not itself use protobufs (at least by default).

**Comment by levi-rs** [comment]
This is a breaking change for my CI pipeline as well. I believe I can work around it by explicitly pip install `protobuf`, but I would like to know if this is an intentional, or if it will be resolved in a future patch.

**Comment by mehrdada** [comment]
This was intentional and documented in release notes: https://github.com/grpc/grpc/releases/tag/v1.12.0

I apologize for the inconvenience it may have caused, but as a matter of correctness, one should list all their dependencies of their packages directly, and not rely on transitive dependencies to pull it for them. The fact that `grpcio` used to depend on `protobuf` was just an implementation detail of `grpcio`.

There are valid use cases for `grpcio` package without pulling the `protobuf` dependency and we wanted to free the users from having to pull both packages when all they need is `grpcio`. That's why the change is made.

Finally, if you have CI infrastructure set up, please please consider testing with the latest release candidate package on PyPI frequently, which we ship usually a week or two before the final release, to help us catch problems early, and to prevent issues on your side as well.

Cheers!

**Comment by levi-rs** [comment]
Thank you for the update, mehrdada.
