### ISSUE TITLE
Python `grpc_tools.protoc` creating `*pb2.py` files from `proto3` files

### ISSUE THREAD

**Issue by tatiana** [grpc/grpc#15444]
### What version of gRPC and what language are you using?
```
grpcio==1.12.0
grpcio-tools==1.12.0
protobuf==3.5.2.post1
```
 
### What operating system (Linux, Windows, …) and version?
```
      System Version: macOS 10.12.6 (16G1314)
      Kernel Version: Darwin 16.7.0
```

### What runtime / compiler are you using (e.g. python version or version of gcc)
 ```
Python 3.6.4 (v3.6.4:d48ecebad5, Dec 18 2017, 21:07:28) 
[GCC 4.2.1 (Apple Inc. build 5666) (dot 3)] on darwin
````
 
### What did you do?

Create the following file `sample.proto`, using `proto3` syntax:
```
syntax = "proto3";

message Hello {
  string target = 1;
}
```

Run:
```
python -m grpc_tools.protoc --proto_path=./ --python_out=./ sample.proto
ls
``` 

### What did you expect to see?

I'd expect to see either a file named:
- `sample_pb3.py`
- `sample_pb.py`

And not `pb2`, since I specified `syntax = "proto3"`.

### What did you see instead?

It generates a file named `sample_pb2.py`. 

### Extra

I understand to "fix" this behaviour would potentially introduce a breaking change. However, it is misleading as it is, and I'd like to hear your feedback.

**Comment by nevali** [comment]
the C/C++ plug-in generates files named e.g., `sample.pb.c`, so I was quite surprised to see the Python output have a different naming scheme.

**Comment by nathanielmanistaatgoogle** [comment]
It's unfortunate that our documentation doesn't make clear that the `3` in `syntax = "proto3";` has nothing to do with the `2` in `sample_pb2.py`. I think what's going on with those numbers is actually kind of cool. Let me bore you with the story:

There are two degrees of freedom in the system. One is the Protocol Buffers Language version, which is the one indicated by `syntax = "proto3";`. What that means is "parse this `.proto` file according to the rules and meanings of Protocol Buffers Language version 3". Language version 3 includes things that Language version 2 didn't have (like maps, I think?) and Language version 3 also removes at least a few things that Language version 2 had (field presence and required fields, I think?). The other degree of freedom is the (generated) Protocol Buffers Python API version. That number specifies the rules for the generated code. You may know that in Protocol Buffers Python API version 2 the way to get the `i`th element of a repeated field is `my_message.my_field[i]`, but you probably didn't know that in Protocol Buffers Python API version 1 the way to get it was to call the field as a function: `my_message.my_field(i)`. In API version 2, the way to assign a non-repeated field is `my_message.my_field = my_value`, but in API version 1, the way to assign a non-repeated field was `my_message.set_my_field(my_value)`.

Why have you never heard of Protocol Buffers Python API version 1? Why don't you have to pass something like `--python_out=api_version:2,.` to `protoc` to generate `_pb2.py` files, or why can you not pass something like `--python_out=api_version:1,.` to `protoc` to generate `_pb1.py` files? Because API version 1 never escaped Google. And we're happy about that; everyone who has used both has been pretty clear that version 2 is the better API.

So out in the open source world, you get one degree of freedom in actual practice, and you see the effect of a second, hidden degree of freedom. What would it take to generate `_pb.py` or `_pb1.py` files? Releasing the currently-Google-internal API version 1, which, eww, yuck; we're finally giving it the death it deserves all these years after version 2 became available. What would it take to generate `_pb3.py` files? Implementing a new API for the Python code generated by `protoc`. A lot of developers are really happy with Protocol Buffers Python API version 2, so... it would take a lot for an API version 3 to happen.

@haberman, @xfxyjwf, @anandolee: did I miss anything important? What did I get wrong?
