### ISSUE TITLE
bins/msan/server_fuzzer_one_entry: server fuzzer assertion 

### ISSUE THREAD

**Issue by AspirinSJL** [grpc/grpc#15458]
https://source.cloud.google.com/results/invocations/883a4224-a262-40f1-93d6-5d2a5e5d6381/targets/github%2Fgrpc%2Fc_linux_msan_native/tests

```
D0518 17:44:29.769866816   31719 ev_posix.cc:145]            Using polling engine: none
D0518 17:44:29.777853260   31719 dns_resolver.cc:339]        Using native dns resolver
E0518 17:44:29.801172761   31719 server_fuzzer.cc:109]       assertion failed: ev.type == GRPC_OP_COMPLETE
```

**Comment by jtattermusch** [comment]
CC @dgquintas  I think you were looking into this before, do you have any insights?

**Comment by jtattermusch** [comment]
This is failing for 10% of builds on master, raising to P1.

**Comment by jtattermusch** [comment]
There's actually two different inputs failing:
https://source.cloud.google.com/results/invocations/f8c9ff45-28de-4cc8-ac48-2b4dd42f16ac

and https://source.cloud.google.com/results/invocations/b3e7528d-b4cf-40ea-bc16-9008038ccf98

**Comment by dgquintas** [comment]
What I've found out is that, for msan builds (it doesn't repro for asan, for example, neither for opt, etc), the completion queue [on this line](https://github.com/grpc/grpc/blob/2266fd4f51735e39b5298c1b6cb688206edd2726/test/core/end2end/fuzzers/server_fuzzer.cc#L107) contains events of type TIMEOUT instead of COMPLETE. Apparently @jtattermusch already encountered this problem in the past. My guess is that the delays introduced by msan affects when things are put into the completion queue, so that when we go and do a cq_next at a point where the event should logically be in the CQ, it still is not. @sreecha , do you think this is a plausible scenario?

**Comment by jtattermusch** [comment]
have we tried to debug with gdb?

**Comment by yashykt** [comment]
Do we have a way to reproduce this?

**Comment by jtattermusch** [comment]
@yashykt  yes, just run the test under msan locally.

**Comment by yashykt** [comment]
Here's what happens on a normal run -
1) The server requests a call with a tag of 1.
2) The data provided by the fuzzer is written to the server.
3) The server performs a cq_next to perform the READ_INITIAL_METADATA op. The op completes and the cq returns GRPC_OP_COMPLETE with the tag of 1.
4) The server performs another cq_next which ends in a GRPC_QUEUE_TIMEOUT.
5) The server then begins shutdown by calling grpc_server_shutdown_and_notify and then cancels all calls.
6) It performs another cq_next and expects to receive GRPC_OP_COMPLETE with the shutdown tag.
7) Finally, it shuts down its completion queues and performs another cq_next expecting the GRPC_QUEUE_SHUTDOWN result.

In the error case, a deadline timer is started after reading the initial metadata. This deadline timer fires and the timer thread grabs a few references to the call stack and tries to perform a CANCEL op. While this is progress, the server tries to complete steps 5 and 6, but since the timer thread is owning references to the callstack, the server thread cannot finish shutting down with a single non-polling completion queue. It needs to wait for the timer thread to give up the references before finishing.

**Comment by yashykt** [comment]
@jtattermusch (message stuck in drafts)
Thanks! It failed quite early with an antagonist setting of 20 :D
