### ISSUE TITLE
macos/grpc_basictests_opt: src/php/bin/run_tests.sh  flaky

### ISSUE THREAD

**Issue by jtattermusch** [grpc/grpc#15582]
Saw 2 timeouts and 1 failure recently on master:

https://source.cloud.google.com/results/invocations/896e4788-1052-4f2e-9e17-a9839aad33ed/targets/github%2Fgrpc%2Fphp_macos_opt_native/tests
https://source.cloud.google.com/results/invocations/6e8ce23f-2cb0-4442-93b6-12a1c5ac8f04/targets/github%2Fgrpc%2Fphp_macos_opt_native/tests
https://source.cloud.google.com/results/invocations/e5561538-9967-4144-bc16-9301cf8830cb/targets/github%2Fgrpc%2Fphp_macos_opt_native/tests

**Comment by ZhouyihaiDing** [comment]
They are all macos tests. Can you please tell me where I can see if this flaky happens in linux tests recently?

**Comment by ZhouyihaiDing** [comment]
Thanks! It happens on both linux and macos tests.

**Comment by ZhouyihaiDing** [comment]
I can only reproduce the TIMEOUT, which I think is the same cause for the issue #14165, and supposed to be solved by #15594.
The cause is all php tests are run in one process, and some tests uses `localhost:0` to create connections with random port. The problem is:
- Some tests forget to destroy the server by `grpc_server_destroy` after the test, which leaves the connection remain `ESTABLISHED`.
- Some tests doesn't force the client creates a new Channel. If 2 tests random to the same port, the channel in the second test will reuse the channel, which will cause the problem similar to #13474.

I think the flaky problem can also be solved by #15594. I can't reproduce it but I can come up with the situation it is flaky. For example, if 2 tests random to the same port, the second channel will reuse the channel created by the first test. If the first test do something makes the channel to status `CONECTING`, `CLOSED`, the second test will have problems during assert. If the flaky disappears for next 2 weeks, I think it is solved.

**Comment by ZhouyihaiDing** [comment]
Timeout still exists. `macos` tests:
https://source.cloud.google.com/results/invocations/8f3529cd-0b55-4eca-88a9-c44154bcb2a4
https://source.cloud.google.com/results/invocations/bed085e7-91d0-4548-9750-9a81e7519f10

**Comment by stanley-cheung** [comment]
php_macos_dbg_native and php_macos_opt_native have been consistently green now

https://fusion.corp.google.com/projectanalysis/current/KOKORO/prod:grpc%2Fcore%2Fpull_request%2Fmacos%2Fgrpc_basictests_dbg
