### ISSUE TITLE
why the 'repeated' type is readonly ? C# 

### ISSUE THREAD

**Issue by 893949088** [grpc/grpc#15622]

**Comment by jtattermusch** [comment]
This is a actually a protobuf  related question, not grpc.
Generally speaking, when exposing a list-like property in C#, sometimes the right API choice is to make the list-like object itself not settable (which is what you mean by "read only" I think) and providing 'Add' and 'AddRange` and other methods (implementing IList), because with that approach there are fewer moving pieces in the system and it sometimes simplifies the implementation. Protobuf happens to do that as well (as do many other popular C# APIs).

Btw, our issue template clearly states that you shouldn't file question as github issue. Please follow the issue template instructions in the future.
