### ISSUE TITLE
Deadline not work properly

### ISSUE THREAD

**Issue by fancl20** [grpc/grpc#15702]
### What version of gRPC and what language are you using?
 v1.10.0
 
### What operating system (Linux, Windows, …) and version?
 Debian 8
 
### What runtime/compiler are you using (e.g. python version or version of gcc)
 clang 4.0
 
### What did you do?

Set a deadline and process sync call.

### What did you expect to see?
 
When the server is broken, call return after deadline exceeded. 

### What did you see instead?
 
Call blocked over 1min waiting for the server writing a large core dump (over 60G).
 
### Anything else we should know about your project/environment?

**Comment by ncteisen** [comment]
Can you provide a reproduction for this bug? Perhaps by adding to our C++ end2end suite?

**Comment by fancl20** [comment]
Trigger this seems similar to unplug the network cable.

**Comment by ncteisen** [comment]
Can you try running and setting GRPC_CLIENT_CHANNEL_BACKUP_POLL_INTERVAL_MS? See https://github.com/grpc/grpc/blob/master/doc/environment_variables.md for more details on that

**Comment by fancl20** [comment]
GRPC_CLIENT_CHANNEL_BACKUP_POLL_INTERVAL_MS seems to work. The bug still can't stable reproduced so I can't confirm it works.

**Comment by ncteisen** [comment]
Sounds good, I will close for now. 

This solution obviously has a race condition (if a server restarts, and then client makes another RPC before the backup poll occurs). This is something that will eventually be fixed by [transparent retries](https://github.com/grpc/proposal/blob/master/A6-client-retries.md#transparent-retries)
