### ISSUE TITLE
Stabilize and document compression support API in gRPC-Python on client and server side

### ISSUE THREAD

**Issue by srini100** [grpc/grpc#15741]
There is test code to show how compression on client and server side can be done in gRPC-Python. This should be documented in user manual with example code.

Compression in Python is supported via metadata arguments. https://github.com/grpc/grpc/blob/master/src/python/grpcio_tests/tests/unit/_compression_test.py

**Comment by mehrdada** [comment]
I'm a bit reluctant to document the feature as is. We should probably consider exposing some of the common channel args via a nicer API and document *that* instead.

**Comment by ericgribkoff** [comment]
Right now it appears that the only way to use compression with Python API is to pull in non-public internal constants or hard-code literals from the core layer. We need to decide how we're going to make the components of this API public, and add/finish at least one missing piece (per-message compression disabling).  See this recent StackOverflow question, for which we do not yet have very good answers: https://stackoverflow.com/questions/53233339/what-is-the-state-of-compression-support-in-grpc-for-python

As noted in the TODOs on https://github.com/grpc/grpc/blob/master/src/python/grpcio_tests/tests/unit/_compression_test.py, our unit tests are using literals to represent core's compression levels and algorithms, as these are not exposed by our Python layer. We also do not have any public way of setting `GRPC_WRITE_NO_COMPRESS` for per-message disabling of compression. It is in our Cython layer ([here](https://github.com/grpc/grpc/blob/2cec9c5344014db548448bd7fbbe04e7c33635be/src/python/grpcio/grpc/_cython/_cygrpc/records.pyx.pxi#L60)) and we have a non-public [`disable_next_message_compression`](https://github.com/grpc/grpc/blob/b741454fe45e1a868ff967c557be9caddc3a569a/src/python/grpcio/grpc/_server.py#L238) API that is, anyways, effectively a no-op.

Since these are all pass-through configuration options that are handled by core, this should all be easy to do - it's just a matter of determining what the Python user API should look like, and then wiring up the configuration options.

**Comment by gnossen** [comment]
Closed by https://github.com/grpc/grpc/pull/18564
