### ISSUE TITLE
Run pylint on examples/python

### ISSUE THREAD

**Issue by mehrdada** [grpc/grpc#15768]
Pylint has been hugely beneficial to the gRPC Python codebase (https://github.com/grpc/grpc/issues/261). It should be expanded to cover examples as well.

**Comment by lidizheng** [comment]
An interesting thing about this is that the indentation of complex `with` clause is different between `pylint` and `yapf`.

Here is the code that makes `pylint` happy `yapf` sad:
``` Python
with grpc.insecure_channel(
    target='localhost:50051',
    options=[('grpc.lb_policy_name', 'pick_first'),
             ('grpc.enable_retries', 0), ('grpc.keepalive_timeout_ms',
                                          10000)]) as channel:
    pass
```

Here is the code that makes `pylint` sad `yapf` happy:
```Python
with grpc.insecure_channel(
        target='localhost:50051',
        options=[('grpc.lb_policy_name', 'pick_first'),
                 ('grpc.enable_retries', 0), ('grpc.keepalive_timeout_ms',
                                              10000)]) as channel:
    pass
```

And seems is due to a bug in `pylint` [Message C0330 reported for PEP-8 compliant 8-space hanging indent #741](https://github.com/PyCQA/pylint/issues/741). Update to latest `pylint` doesn't solve this problem.

**Comment by lidizheng** [comment]
@srini100 Since `yapf` is already checking the style of codes in examples folder, the format and style is already ensured. I agree that `pylint` can achieve higher level grammar check for packages, but files in examples folder are relatively small. So I think we can close this issue for now.

**Comment by lidizheng** [comment]
Resolved with https://github.com/grpc/grpc/pull/17280.
