### ISSUE TITLE
[gRPC C++] Support True Custom Serialization and Generic

### ISSUE THREAD

**Issue by ncteisen** [grpc/grpc#15764]
This change intends to add support for several critical use cases:
- Only one method needs customs serialization, the rest use proto
- Generic users still benefit from our codegen
- Custom serialization is supported between arbitrary C++ class and ByteBuffer
- Imbalanced generic support (request is proto, response is custom ByteBuffer)

This project will occur in several steps:
- [x] Server supports per-method true generic
- [ ] Server supports per-method imbalanced generic
- [ ] Client supports per-method true generic
- [ ] Client supports per-method imbalanced generic
- [ ] Write documentation for C++ generated code

**Comment by ncteisen** [comment]
Redirected to @vjpai in case you continue the work for unbalanced raw API.

**Comment by wesm** [comment]
We recently had the requirement of doing parsing-by-hand of a protocol buffer to avoid unnecessary copying of a binary payload, while still allowing clients to read the protobuf without any memory optimizations. 

It's a bit of a gross hack since the serde path needs to be specialized before even the generated gRPC service is compiled:

https://github.com/apache/arrow/pull/3633
