### ISSUE TITLE
nanopb warnings when running "bazel build :all"

### ISSUE THREAD

**Issue by jtattermusch** [grpc/grpc#15832]
Running `bazel build :all` under the repo root

/nanopb:pb_common.c
/nanopb:pb_decode.c
/nanopb:pb_encode.c

```
WARNING: /home/jtattermusch/grpc/BUILD:1972:1: in srcs attribute of cc_library rule //:grpc_nanopb: please do not import '//third_party/nanopb:pb_common.c' directly. You should either move the file to this package or depend on an appropriate rule there. Since this rule was created by the macro 'grpc_generate_one_off_targets', the error might have been caused by the macro implementation in /home/jtattermusch/grpc/bazel/grpc_build_system.bzl:172:12

WARNING: /home/jtattermusch/grpc/BUILD:1972:1: in srcs attribute of cc_library rule //:grpc_nanopb: please do not import '//third_party/nanopb:pb_decode.c' directly. You should either move the file to this package or depend on an appropriate rule there. Since this rule was created by the macro 'grpc_generate_one_off_targets', the error might have been caused by the macro implementation in /home/jtattermusch/grpc/bazel/grpc_build_system.bzl:172:12

WARNING: /home/jtattermusch/grpc/BUILD:1972:1: in srcs attribute of cc_library rule //:grpc_nanopb: please do not import '//third_party/nanopb:pb_encode.c' directly. You should either move the file to this package or depend on an appropriate rule there. Since this rule was created by the macro 'grpc_generate_one_off_targets', the error might have been caused by the macro implementation in /home/jtattermusch/grpc/bazel/grpc_build_system.bzl:172:12
```

The build still succeeds, but getting warnings is annoying and usually indicates a real problem.

**Comment by jtattermusch** [comment]
CC @nicolasnoble

**Comment by jtattermusch** [comment]
I took a brief look and I don't understand why there are 2 almost identical nanopb build files:
https://github.com/grpc/grpc/blob/1c6d6ba851b6d65ce8757b468b21b0235f9b5312/third_party/nanopb.BUILD
and 
https://github.com/grpc/grpc/blob/1c6d6ba851b6d65ce8757b468b21b0235f9b5312/third_party/nanopb/BUILD

**Comment by jtattermusch** [comment]
A similar issue has been reported in https://github.com/grpc/grpc/issues/15609, but this issue still exist after https://github.com/grpc/grpc/pull/15595 has been merged.

**Comment by dgquintas** [comment]
I can't repro:

```
$ git log -1
commit 3acf8e62079e727ae1925be759fa917f10e982bb (HEAD -> master, upstream/master)
Merge: 24416c7a19 1645e1c55f
Author: David G. Quintas <dgq@google.com>
Date:   Fri Jun 22 16:04:32 2018 -0700

$ bazel build :all
INFO: Analysed 79 targets (41 packages loaded).
INFO: Found 79 targets...
INFO: Elapsed time: 201.492s, Critical Path: 112.65s
INFO: 338 processes, remote.
INFO: Build completed successfully, 349 total actions
```

**Comment by nicolasnoble** [comment]
BTW the duplication exists because we need to override nanopb's BUILD file. More to the point: the //third_party/nanopb directory is technically an external module (even though we have a code drop here), because it can potentially be duplicated with other people's nanopb import, and we need to start treating it as such. Also the original BUILD file is still there because it's just a literal code drop.

Long story short:

 - nanopb is a code drop because of its nature: it doesn't exist as debian packages for instance, so a submodule-less build wouldn't work properly on non-bazel builds.
 - bazel builds with nanopb can be an issue if other people also need nanopb.
 - therefore, we keep nanopb as a code drop, but we start treating it as a bazel external so that external projects that depend on grpc can have a single nanopb target for both grpc and their own dependency.

**Comment by nicolasnoble** [comment]
Also, to reconcile @dgquintas' and @jtattermusch's reports: please compare your versions of bazel.

**Comment by dgquintas** [comment]
```
$ bazel version
Build label: 0.14.1
...
Build time: Fri Jun 8 12:17:35 2018 (1528460255)
Build timestamp: 1528460255
Build timestamp as int: 1528460255
```

**Comment by dgquintas** [comment]
It's likely that what's needed is using a more recent version of bazel.

**Comment by jtattermusch** [comment]
I tried again and I also wasn't able to repro (I tried bazel 0.14.1 and 0.15).
