### ISSUE TITLE
C++ perf dashboard doesn't have data

### ISSUE THREAD

**Issue by adelez** [grpc/grpc#15898]
https://performance-dot-grpc-testing.appspot.com/explore?dashboard=5685265389584384

**Comment by jtattermusch** [comment]
https://github.com/grpc/grpc/blob/64712bfa47484933bbbf6ff0fd0682768b695d0c/tools/internal_ci/linux/grpc_full_performance_master.sh#L26

The SQL query for said dashboard look like this:
```
SELECT
	summary.latency50 / 1000 as value,
    metadata.created as date,
    scenario.name as scenario
FROM
	[grpc-testing:performance_test.performance_experiment]
WHERE
	metadata.created >= DATE_ADD(CURRENT_TIMESTAMP(), -1, "WEEK") AND
    metadata.jobName = "gRPC_performance_experiment" AND
    (scenario.name = "cpp_protobuf_sync_unary_ping_pong_secure" OR
    scenario.name = "cpp_protobuf_sync_unary_ping_pong_insecure" OR
    scenario.name = "cpp_protobuf_async_unary_ping_pong_secure" OR 
    scenario.name = "cpp_protobuf_async_unary_ping_pong_insecure" OR 
    scenario.name = "netperf_tcp_rr")
    
     
ORDER BY
	date;
```

The problem is in the  `metadata.jobName = "gRPC_performance_experiment"`  - that restricts displayed results to those generated by job with name `gRPC_performance_experiment` - which is the name of an old Jenkins job that doesn't exist anymore.

**Comment by jtattermusch** [comment]
I removed the  `metadata.jobName = "gRPC_performance_experiment" AND` for SQL queries in that dashboard (it seemed safe as we currently don't have another job generating the data into `grpc-testing:performance_test.performance_experiment` and `grpc-testing:performance_test.performance_experiment_32core`

**Comment by jtattermusch** [comment]
FYI @sreecha , @lyuxuan  (and @ctiller) as you all own dashboards cloned from the C++ dashboard - if they are still in use, you can fix them by removing `metadata.jobName = "gRPC_performance_experiment" AND` as described above. We can also delete the dashboards if you are not using them anymore.
