### ISSUE TITLE
Subchannel call context not the same in filter initialization and batch starting

### ISSUE THREAD

**Issue by hcaseyal** [grpc/grpc#15927]
When a filter is registered on the subchannel, the context that is passed to init_call_elem() through args->context is the subchannel context. However, the context that is passed to start_transport_stream_op_batch through batch->payload->context is the call context. This happens in the non-retry case (common case), but doesn't appear to happen in the retry case (uncommon).

Expected behavior: 
The context that is passed to a filter should be consistent across all of the filter's methods. 

There are a couple of proposed solutions:
1) Pass in subchannel context in all batches and propagate anything in parent context to subchannel context when we create it.
2) Find a different approach for what we’re using the subchannel context for

**Comment by markdroth** [comment]
More context:

We ran into this problem when trying to change the client_auth filter to set the auth context in `init_call_elem()` instead of in `start_transport_stream_op_batch()` in #15879.

The problem is that the client_channel code creates a separate context for the subchannel call.  It passes this context down to `init_call_elem()`, but it does not alter the context passed down in each batch in the non-retry case.  Thus, the filters in the subchannel stack see a different context in `init_call_elem()` than in `start_transport_stream_op_batch()`.

There are a few possible approaches to fix this, none of them particularly appealing:

- Fix client_channel code to reset the context passed down with each batch to be the subchannel context even in the non-retry case.  This would not be a complete solution, because any filter can alter the context at any time, and we would need a way to propagate those changes between the subchannel context and the parent context.
- Stop using a separate context for the subchannel stack.  The only reason we did this was to support client-side load reporting in grpclb, in which we need to pass down a refcounted client stats object to each subchannel stack (see #10821).  There are two possible options here:
  - Instead of using context, pass down the client stats object via metadata.  The problem with this is that we don't currently have a clean way to pass down non-string data via metadata.
  - Alternatively, we could just set the client stats object in the parent context and pass that down.  This would work fine today for both non-retry and retry cases, but it would not work later when we go to implement hedging.

We'll need to think about the best way to fix this.

**Comment by markdroth** [comment]
I'm going to solve this by passing down the client stats object in user data attached to the LB token metadata element.

There will still be future work needed here when we later to go to implement hedging support, but we can deal with that when the time comes.
