### ISSUE TITLE
Publish 32-bit Windows Python 3.7 wheels

### ISSUE THREAD

**Issue by mehrdada** [grpc/grpc#15968]
Python 3.7 is not preinstalled on Kokoro images for macOS and Windows yet, therefore we fetch and install it in our prepare script. We currently only do that for 64-bit version of Python 3.7 on Windows.

This issue tracks a work item to add a 32-bit Python3.7 entry to the list of artifact targets after Kokoro image comes preinstalled with Python 3.7.

`disposition/on hold`: pending Kokoro image supplying Python 3.7

**Comment by ultrasound1372** [comment]
I am attempting to install your package and am getting the same error mentioned in #15948, except I'm not using apache beam, but rather the assistant sample sdk. I am not installing the lot of visual studio just to run the damn thing. I am on 3.7 32bit because when you're on windows, really it's recommended to always only use 32 bit versions. If you use 64 bit versions, loads of dependencies won't work, at least that is the practice I have been taught for all python installations. When in doubt, install 32 bit. Exact same error as mentioned in the above issue.

**Comment by mehrdada** [comment]
@ultrasound1372 we are planning to ship Python 3.7 32-bit binary packages as soon as our Windows CI machines install it.

**Comment by mehrdada** [comment]
32-bit Python 3.7 binary wheels for Windows are now uploaded on PyPI.
