### ISSUE TITLE
Support SO_REUSEADDR/SO_EXCLUSIVEADDRUSE for Windows (C#) servers

### ISSUE THREAD

**Issue by l33ds** [grpc/grpc#16005]
### What version of gRPC and what language are you using?
 gRPC v1.12.0 using C#
 
### What operating system (Linux, Windows, …) and version?
 Windows Server 2012
 
### What runtime / compiler are you using (e.g. python version or version of gcc)
 gRPC v1.12.0 
 
### What did you do?
Create a simple server while a different application is listening on the same port (vmware-hostd.exe, TCP port 443) using:
```
_server =
                new Grpc.Core.Server(new List<ChannelOption>
                {
                    new ChannelOption(ChannelOptions.MaxReceiveMessageLength, ...),
                    new ChannelOption(ChannelOptions.MaxSendMessageLength, ...),
                })
                {
                    Services = {...},
                    Ports = {new ServerPort(IPAddress.Any.ToString(), ..., ...) }
                };
...
_server.Start();
```
 
### What did you expect to see?
 Some error like "bind failed: Address already in use" (with a flag that would enforce not accepting multiple holders of the same bound port)
 
### What did you see instead?
The server was running "normally", but did not get any client requests. Instead, all clients connected successfully to the server (one of them) but failed at further communication
 
### Anything else we should know about your project / environment?
I understand there is some support in similar flags (you can set `SoReuseport`) and some differences between different platforms, but it's not very clear to me as to whether or not it's possible or not to set this flag in Windows or other platforms (and if not possible - why?)

**Comment by l33ds** [comment]
Hey, I'd love to know if that's possible. Did I understand the situation correctly, it's just another flag that could be exported to the user?

**Comment by nicolasnoble** [comment]
First, `SO_REUSEADDR` is a flag that lets you bind local addresses quicker when they've been freed previously by another process. This isn't about sharing ports across processes, this is about stealing sockets from one process to another basically.

Second, the flag you're thinking about, `SO_REUSEPORT`, is a Linux-exclusive thing. There's no Windows equivalent for it unfortunately.

Third, if I am reading you correctly, you want to listen on the same port as a different application. Listening on the same exact port as a *different* application doesn't make any sense whatsoever. The primary purpose of `SO_REUSEPORT` is to create a cluster of stateless process for a single application, in order to easily parallelize the processing of incoming requests by using the TCP kernel layer as a sort of round robin load balancer across multiple processes. If requests are randomly served by different applications, no application semantic would make sense in form or function.

**Comment by hcaseyal** [comment]
@l33ds With regard to you not seeing the error "bind failed: Address already in use", we do indicate  indicate non success by returning 0 from bind(), and the error message should be in the logs. What might have happened in your observation of the clients connecting "successfully" to the server is that the client didn't error out, but was left in a reconnection loop.

For example, if you have an invalid certificate, the client will continue attempting to connect forever, and forever failing with the ssl mismatch error.

**Comment by l33ds** [comment]
@nicolasnoble @hcaseyal Thanks for your responses, I think I didn't get the message through. I want the Server to fail (exception, return value etc.) when trying to listen to addr:port that is already listened by a different process. Are you saying that the way to do it is `SO_REUSEPORT` but it's impossible on Windows? That's not what I understand from this: https://docs.microsoft.com/en-us/windows/desktop/winsock/using-so-reuseaddr-and-so-exclusiveaddruse
Thanks and sorry if I'm misunderstanding anything

**Comment by nicolasnoble** [comment]
The failure is there and reported. The failure is indicated by the `bind` call returning 0.

**Comment by l33ds** [comment]
@nicolasnoble I don't see the failure you're describing. In my program, `_server.Start()` succeeds and does not trigger any exception :(
