### ISSUE TITLE
Deadline ServerWriter.write

### ISSUE THREAD

**Issue by NorbertUseGithub** [grpc/grpc#16064]
Hi, I am not usre if I am at the right place here, But I have an Issue using ServerWriter.write to write a stream from Server to Client.
We are using C++
We are creating a measurement system where the Server Permanently sends Data Packages via stream to the client. Data Rate is up to 20 kHz Packet size in 4 kilo byte or even larger (may be with less data rate)
Connection is established as peer to peer connection. using an ethernet cable
Generally everything is working fine.
But we run into a Problem when there is an "Connection Issue".
Of course it is not normal operation, but it should be handled gracefully.
When someone unplugs the Network cable while stream is active the thread that sends the data hangs in ServerWriter.Write. Is there any chance to set a deadline for ServerWriter.write?

Help on this really would be appreciated.

**Comment by NorbertUseGithub** [comment]
Oh, I forgot to metion, we are running on Windows (client side)
and Linux (server side)

**Comment by sreecha** [comment]
@NorbertUseGithub,
There is no straightforward way to pass a timeout to `ServerWriter::Write` API. 

However you could do one of the two things:
- Use the Async API (i.e Use [Async Write ](https://grpc.io/grpc/cpp/classgrpc_1_1_server_async_writer.html#a467f70c7460ceb7738fb938b3bf93c85) and pass a timeout to completion queue [AsyncNext](https://grpc.io/grpc/cpp/classgrpc_1_1_completion_queue.html#a290ddf3d96e6d1d5886580e60b0602b4) . 

- If you want to continue to use Sync API (i.e `ServerWriter::Write`), you have perhaps have a different thread call [`ServerContext.TryCancel()`](https://grpc.io/grpc/cpp/classgrpc_1_1_server_context.html#a8569c71704f03f3b1089745228c70e3b) to cancel the RPC after some timeout.  This will cause your `SeverWriter::Write()` to return with a `false` since the call is cancelled.
'
Hope this helps.
