### ISSUE TITLE
BoringSSL conflicts with BB Dynamics OpenSSL

### ISSUE THREAD

**Issue by bond-** [grpc/grpc#16181]
### What version of gRPC and what language are you using?
Version in: https://github.com/GoogleCloudPlatform/ios-docs-samples/blob/master/speech/Swift/Speech-gRPC-Streaming/googleapis.podspec
 
### What operating system (Linux, Windows, …) and version?
 iOS
 
### What runtime / compiler are you using (e.g. python version or version of gcc)
https://github.com/GoogleCloudPlatform/ios-docs-samples/issues/85
 
### What did you do?
If possible, provide a recipe for reproducing the error. Try being specific and include code snippets if helpful.
Include Blackberry Dynamics framework with FIPS module and Google Speech pod in the same iOS App project
 
### What did you expect to see?
No conflicts between BoringSSL and OpenSSL
 
### What did you see instead?
App crash

Make sure you include information that can help us debug (full error message, exception listing, stack trace, logs).
Refer to the log on: https://github.com/GoogleCloudPlatform/ios-docs-samples/issues/85

- Is BoringSSL really required?
- Can this be fixed?

**Comment by muxi** [comment]
I think it is duplicate of #6111. I'll fix it when I got a chance. Thanks for reporting.

**Comment by 24601** [comment]
See possible solution/workaround I posted in #1574. It is not optimal but seems to work and is pretty easy and painless. Ideally, BoringSSL wouldn't be broken, really...

**Comment by nicolasnoble** [comment]
I don't think you referenced the proper issue number.

**Comment by nicolasnoble** [comment]
Also, boringssl is kind of a drop in replacement for openssl. It's not broken in the sense that it's not easy to have the same library twice in the same binary. Or in other words, nothing's broken in boringssl, only the iOS build that doesn't make it easy for two versions of the same library to coexist.

**Comment by 24601** [comment]
@nicolasnoble - thanks for the heads up, right issue number, wrong project :). Fixed the link. 

I hear what you're saying and understand the issue, so, yes, in that sense it's not "broken", but coming from a "customer of GOOG's SDKs and services" perspective it *IS* "broken". BoringSSL is an *internal* dependency of many GOOG frameworks used to consume (sometimes) very expensive and critical services offered by GOOG. No GOOG customer *chooses* to depend on BoringSSL, this is an internal dependency introduced by GOOG's design decisions. It is also marketed/discusses as a "drop in replacement" for OpenSSL. 

Clearly, the bevy of issues people are having means it is neither transparent nor a drop-in replacement.

Other libraries looking for certain OpenSSL headers don't see the same in BoringSSL and certain methods return different values for the same, idempotent (sp?) calls (e.g. I had a few cases where BoringSSL would not return the same value for a given call on SSL/TLS stuff than OpenSSL would, thus breaking the dependent code). I'd be FINE if BoringSSL *truly* was a drop-in that didn't break things like SIP stacks, etc that rely on lower level SSL calls. But it does. A lot. 

Also, it's a really, really porky dependency. The NPM module is like 30MB, because BoringSSL packages the tests in the NPM packages. That's a separate issue, though. 

I think GOOG should look at this from a "what does broken mean to our customers and users" perspective. I know there are tons of technical reasons and ways to define broken which clearly absolve BoringSSL of any blame, but when my devs see red on builds and it's because an internal dependency required to use GOOG libraries is breaking builds, well, we call it broken :). Especially when it's a library published so we can have the privilege of paying GOOG to use the services! 

Yes, we *could* just revert back to low level REST APIs and not have to use GOOG provided libraries, but again this is about productivity in consuming services and where I spend my dev budget. 

It's even more "broken" when I/my devs have to spend time fixing stuff like this/working around stuff like this instead of it "just working". That's the whole promise of managed services like Firebase (that heavily relies on the gRPC library), that we focus on the stuff we need to get our business logic implemented and not this stuff, right? 

I think @wilhuff is *spot on* when he suggests (in https://github.com/grpc/grpc/issues/6111): 

```The best path forward (but overwhelmingly the most work) would be to drop our BoringSSL/OpenSSL requirement altogether on iOS and other Apple platforms and use SecureTransport (or CFSocketStream). These are provided by the OS and designed to be compatible across iOS releases. If there's a vulnerability, Apple can ship an update and everyone will be transparently updated without requiring everyone to rebuild.```

It is the most work, but I think it's also the most customer-friendly. Because the problem of static & dynamic libs/frameworks on Swift is *NOT* going to be solved soon and isn't a bug as much as an architectural decision (don't worry, I'm over in AAPL's bug reporter being equally tough on them about the mess that is Swift, even at rev 4....). 

That being said, if there is a work effort at some point put together on this, as heavy Google Cloud users, I would be open to allocating resources perhaps at some point to get it done, although, given we're paying a lot of money for the services these things like gRPC and the like access, while they are open source projects we want to support and not just come to bug trackers/issue trackers to complain about, these also aren't just small open source projects, gRPC is making GOOG a *BUNCH* of money, and if you guys need me to go push on our Gcloud rep to get people to make that linkage between this discussion and revenue numbers to get certain things addressed, let me know. We aren't the biggest fish, but I'm more than happy to make our problem known to the revenue-collecting side of the business where they might be able to prioritize internal resources for a fix if they hear it enough...

**Comment by bond-** [comment]
@24601 
> if you guys need me to go push on our Gcloud rep to get people to make that linkage between this discussion and revenue numbers to get certain things addressed, let me know

I am trying to push this through my enterprise too. Can you push this from your side too?
