### ISSUE TITLE
grpc asynchronous bi-directional server (Java/Python)

### ISSUE THREAD

**Issue by huaiweicheng** [grpc/grpc#16234]
Here is my scenario. The grpc server is an asynchronous sever which subscribes data from other source. Also it provides a subscribe function to its client, thus it could push the data to the grpc client once it receives data from other source. The server is implemented in Java.

```
@Override
public StreamObserver<Message> subscribe (
        StreamObserver<Message> responseObserver) {
    return new StreamObserver<Message>() {

        @Override
        public void onNext(Message message) {
            api.subscribe(message.value, Message -> {
                synchronized (responseObserver) {
                    ...
                    ...
                    // get data from other source

                    responseObserver.onNext(Converter.create().toProtobuf(Message.class, data));
                }
            });
        }

        @Override
        public void onError(Throwable t) {
            log.warn("Encountered error in sub", t);
        }

        @Override
        public void onCompleted() {
            responseObserver.onCompleted();
        }
    };
}
```
I wanna use python to implement a grpc client to subscribe from this server. However, it appears weird once python subscribe data, it immediately shutdown without waiting for the asynchronous return from Java server. However, the Java client could run forever and waiting for the asynchronous data from the server.

Proto

```
message Message{
    string value = 1;
}
service test {
    rpc subscribe(stream Message) returns (stream Message) {}
}
```
The Python client Code(not working)

```
def gen_message():
    yield test.Message(value="2")

def run():
    channel = grpc.insecure_channel('localhost:50051')
    stub = test_grpc.MessengerStub(channel)

    stream = stub.subscribe(gen_message())
    try:
        for e in stream:
            print(e)
    except grpc._channel._Rendezvous as err:
        print(err)

run()
```

The Java Code(working)

```
StreamObserver<Message> requestObserver = stub.subscribe(new StreamObserver<Message>() {
    @Override
    public void onNext(Message message) {
        System.out.println(message)
    }

    @Override
    public void onError(Throwable t) {
        t.printStackTrace();
    }

    @Override
    public void onCompleted() {

    }
});
Message message = Message.newBuilder().build();
requestObserver.onNext(message);
```

I have been got confused. How to implement the same feature in python client? Thanks~

p.s. If the server is an while True server other than asynchronous server, the python client works. I suspects that the python client does not know the "asynchronous" server and once its stream has no new data it close the connection.

**Comment by mehrdada** [comment]
Do you get any exception printed or does it just succeed as the iteration ends?

**Comment by huaiweicheng** [comment]
no exceptions.
What I wanna get is a continuous asynchronous grpc sever pushing data to client.
The python client ends while Java client waits for the asynchronous data pushing.
Which means, the code below does not have the chance to execute if using the python client since the connection was closed.

```
api.subscribe(message.value, Message -> {
                synchronized (responseObserver) {
                    ...
                    ...
                    // get data from other source

                    responseObserver.onNext(Converter.create().toProtobuf(Message.class, data));
                }
            });
```

**Comment by mehrdada** [comment]
Can you try running the Python client under `GRPC_TRACE=api,channel,client_channel,flowctl GRPC_VERBOSITY=debug` environment and share the results (also you can run both the successful and failing client and see if something sounds off?)

**Comment by huaiweicheng** [comment]
The log is so long...  I use  a method of sleeping in the request stream to solve the problem in an ugly way. The only difference 
Failed:

    def gen_message():
        yield test.Message(value="2")

![image](https://user-images.githubusercontent.com/4011117/44017364-931e06aa-9f0a-11e8-8cb3-67b4a53fd0de.png)


Succeed:

    def sleepfunc():
        while True:
            time.sleep(1)
    def gen_message():
        yield test.Message(value="2")
        yield sleepfunc()
![image](https://user-images.githubusercontent.com/4011117/44017390-b4eb858c-9f0a-11e8-94a9-a1b8231878d1.png)

The failed log shows that **grpc_call_unref**, does that mean the client cancel the RPC?

**Comment by JamesXiao** [comment]
Same issue here,  in a bi-direction stream grpc function:
1. grpc client send req to grpc server
2. grpc server pass the msg to other module, and wait for async response (could happen any time for multiple times)
2.5 wait for the other module's response(s), maybe immediately, or 1 seconds, or 3 minutes or couple of hours later
3. other module do respond to grpc server.
4. grpc server forward the response to grpc client via the stream.

In the bi-direction streaming scenario, client should be keeping the connection and waiting for data from server, and dot not close the stream actively unless it meets failure or complete event.

Both C# and JAVA client has the expected behavior as described above, while only the python client exists prematurely, just after step 2.

**Comment by srini100** [comment]
@JamesXiao, @huaiweicheng, Can you provide minimal repro code example? I don't see this issue. If you take the simple [routeguide](https://github.com/grpc/grpc/tree/master/examples/python/route_guide) example, the client waits for server response after finishing its stream. To simulate your scenario, just put some arbitrary about of sleep on the server side before it starts responding. Client waits however long it take. This is assuming that the TCP connection is not broken by intermediate routers due to long period of inactivity.

**Comment by srini100** [comment]
Closing since no response from poster. Will help if someone can post a minimal reproduction of this issue.
