### ISSUE TITLE
Makefile does not install pkg-config file for libaddress_sorting

### ISSUE THREAD

**Issue by jtattermusch** [grpc/grpc#16345]
See https://github.com/grpc/grpc/issues/15166.

**Comment by coryan** [comment]
I created a little test that links things statically, you may need to adapt it to your needs. The [attached tarball](https://github.com/grpc/grpc/files/2290878/test.tar.gz) has a simple `Makefile`, and a `Dockerfile` to reproduce all the build steps.

There is some good news (maybe), the `libgrpc++.a` library seems to include the contents of the `libaddress_sorting.a` library. If that was intentional, then you would not need to add `libaddress_sorting` to any pkg-config files.

Do not hesitate to contact me if you have more questions (I am a Googler btw, so you should be able to find me inside Google too).
