### ISSUE TITLE
"@poller=XYZ" classifier seems to be ignored for some Foundry tests

### ISSUE THREAD

**Issue by jtattermusch** [grpc/grpc#16479]
This got revealed when working on https://github.com/grpc/grpc/pull/16478

bazel generates test variants with `@poller=XYZ` suffix, but it seems that the right poller is not always used.
Here the test is called `...@poller=poll`, but logs say ` Using polling engine: epollex` (which is a debug message, so it's only visible if #16478 is in place).

```
exec ${PAGER:-/usr/bin/less} "$0" || exit 1
Executing tests from //test/core/end2end:h2_proxy_test@simple_cacheable_request@poller=poll
-----------------------------------------------------------------------------
D0828 08:42:08.516498572      19 test_config.cc:391]         test slowdown factor: sanitizer=1, fixture=1, poller=1, total=1
D0828 08:42:08.518597506      19 ev_posix.cc:170]            Using polling engine: epollex
D0828 08:42:08.519636084      19 dns_resolver.cc:338]        Using native dns resolver
I0828 08:42:08.519993015      19 simple_cacheable_request.cc:39] Running test: test_cacheable_request_response_with_metadata_and_payload/chttp2/fullstack+proxy
```

The test report:
https://source.cloud.google.com/results/invocations/ba912256-bc77-48f8-9102-b313d978eba3/targets/%2F%2Ftest%2Fcore%2Fend2end:h2_proxy_test@simple_cacheable_request@poller%3Dpoll/log

This is probably only happening for a subset of tests, as I saw some other tests setting GRPC_POLL_STRATEGY correctly (e.g. https://source.cloud.google.com/results/invocations/d913b5a6-36c6-4a3c-9c5a-b3b7a578b88a/targets/%2F%2Ftest%2Fcore%2Fclient_channel%2Fresolvers:dns_resolver_test@poller%3Depollsig/log)

**Comment by jtattermusch** [comment]
Perhaps something is wrong with `https://github.com/grpc/grpc/blob/35501ad1df5799be17cc41894a0dc1d3ed43a8f0/test/core/end2end/generate_tests.bzl#L263`?  I don't see the   `export GRPC_POLL_STRATEGY=xyz`  in the test log anywhere.

**Comment by billfeng327** [comment]
The problem is with the shell script [end2end_test.sh](https://github.com/grpc/grpc/blob/master/test/core/end2end/end2end_test.sh).
If you compare with the [run_with_poller.sh](https://github.com/grpc/grpc/blob/35501ad1df5799be17cc41894a0dc1d3ed43a8f0/test/core/util/run_with_poller.sh), you could see that a '-z' is needed before the poller argument, yet the bazel file does not seem to include it.

**Comment by billfeng327** [comment]
See this PR
https://github.com/grpc/grpc/pull/16481

**Comment by billfeng327** [comment]
confirmed that the problem is fixed. Below is the output for the same mismatching test (//test/core/end2end:h2_proxy_test@simple_cacheable_request@poller=poll):
https://source.cloud.google.com/results/invocations/dc8f559a-96c1-409b-9228-c10972b47160/targets/%2F%2Ftest%2Fcore%2Fend2end:h2_proxy_test@simple_cacheable_request@poller%3Dpoll/log

As displayed, the polling engine is now matching.

**Comment by adelez** [comment]
Thanks for fixing this, Bill!
