### ISSUE TITLE
Auto-Generated C# Code has wrong namespace casing that breaks the build

### ISSUE THREAD

**Issue by MirzaMerdovic** [grpc/grpc#16514]
### What version of gRPC and what language are you using?
 Grpc and GrpcTools 1.14.1 (_I tried 1.14; 1.13.1 and 1.13 result is the same_)
 
### What operating system (Linux, Windows, …) and version?
 Windows 10 Enterprise 64-bit (10.0, Build 14393)
 
### What runtime / compiler are you using (e.g . python version or version of gcc)
 C# .NET Standard 2.0
 
### What did you do?
I wrote an example that can be found on GitHub [repo](https://github.com/MirzaMerdovic/protogeneration-issue.git) hopefully it will be clear enough.
 
### What did you expect to see?
 Auto generated contract should have correct syntax
 
### What did you see instead?
 Namespace casing of imported proto types is wrong and it's breaking the build.

![proto_codegen_error](https://user-images.githubusercontent.com/16725633/44847297-50a42d80-ac53-11e8-966a-59080472de1a.png)
and it should be 
`global::Contracts.Grpc.Alpha.ContractAlphaReflection.Descriptor `

**Comment by jtattermusch** [comment]
This issue actually belongs to https://github.com/protocolbuffers/protobuf repository

**Comment by jtattermusch** [comment]
Indeed,
https://github.com/MirzaMerdovic/protogeneration-issue/blob/2ece89b638690e4f53ef4303de25baea4d06608d/protogen/ContractBeta/ContractBeta.g.cs#L36

should point to 

https://github.com/MirzaMerdovic/protogeneration-issue/blob/2ece89b638690e4f53ef4303de25baea4d06608d/protogen/ContractAlpha/ContractAlpha.g.cs#L15

My guess is that this is happening because the filename is `ContractAlpha.proto', but it's being imported as `contractalpha.proto` (which works on windows as the case in file name doesn't matter) from the other .proto.

**Comment by MirzaMerdovic** [comment]
@jtattermusch I tried your suggestion and it works. 
Thanks for the help! and sorry for the mess I made by posting this to a wrong place.

**Comment by jtattermusch** [comment]
@MirzaMerdovic thanks for filing, it's an interesting corner case.
