### ISSUE TITLE
Add JavaScript examples with protobuf.js

### ISSUE THREAD

**Issue by MOZGIII** [grpc/grpc#16548]
Hi, please add JavaScript usage examples with protobuf.js.

I'm mostly interested in static codegen with TypeScript - to have typed rpc and message definitions.
I have this implemented currently as a hack for gRPC version 1.10.1, but I want to upgrade. Having typed definitions helps a lot, so I don't want to throw that away.

This is *grpc-node* specific, however since examples live in this repo, I'm creating an issue here.

**Comment by nicolasnoble** [comment]
grpc-node only supports two things:

-) static codegen in Javascript using protoc, [demonstrated here](https://github.com/grpc/grpc/tree/master/examples/node/static_codegen).
-) dynamic (runtime loading that is) codegen using protobufjs, [demonstrated here](https://github.com/grpc/grpc/tree/master/examples/node/dynamic_codegen).

Beside these two usage cases, we don't have typescript static codegen in protoc, and there's no support for protobufjs' static codegen, so no example can be provided that would do what you're asking for, hence me closing this issue, since we can't implement it.

If you have some working code however to accomplish something along the lines of what I've described above, we're interested in your potential contributions to the project.

**Comment by nicolasnoble** [comment]
Also, on the discussion of protobufjs static codegen support, I'd invite you to chime in into https://github.com/grpc/grpc-node/issues/528.
