### ISSUE TITLE
Please add the license file to the Python tarballs

### ISSUE THREAD

**Issue by bochecha** [grpc/grpc#16732]
I'm packaging python-grpcio for Fedora.

One of the packaging guidelines requests that all packages come with a file containing the full text of their license.

I see you already have a `LICENSE` file in the repository. Could it be added to the Python tarballs with future releases ?

**Comment by mehrdada** [comment]
@bochecha I am curious what your update plan would be for Fedora packages? gRPC has a 6-week release cycle and we are somewhat hesitant of actively having lots of old versions lying around on slow update schedules and think if we don't manage that might ruin the UX more than availability in package managers, so that requires careful thought.

**Comment by bochecha** [comment]
@mehrdada is there any guarantee of stability between gRPC upgrades?

If it doesn't break apps using it, then we could very well upgrade the package in Fedora whenever you release something. :slightly_smiling_face:

**Comment by bochecha** [comment]
In Fedora we usually aren't shy about updating things, even in stable release.

We're trying not to break apps though, so if a future gRPC release was incompatible with the previous ones, we might decide not to upgrade any more in released Fedoras. (but obviously we would update in next Fedoras)

In any case, if you're trying not to break API, this is probably going to be just fine. :)

**Comment by mehrdada** [comment]
cc @lidizheng
