### ISSUE TITLE
Case of filed names not preserved.

### ISSUE THREAD

**Issue by F483** [grpc/grpc#16779]
I created an isolated example project [here](https://github.com/F483/grpc-inconsistency).

**Source proto**

```
message TestInput {
  string fieldAlpha = 1;
  string fieldBeta = 2;
  string FieldGamma = 3;
}
```

**Compiled code:**

```
proto.test.TestInput.toObject = function(includeInstance, msg) {
  var f, obj = {
    fieldalpha: jspb.Message.getFieldWithDefault(msg, 1, ""),
    fieldbeta: jspb.Message.getFieldWithDefault(msg, 2, ""),
    fieldgamma: jspb.Message.getFieldWithDefault(msg, 3, "")
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
```

**Comment by F483** [comment]
I linked the entire test project, the command is listed in package.json, its the same as provided in the example code.

I also noticed that `map<string, string> details = 2; ` compiles to `detailsMap: Array<[string, string]>`.

The whole point of an API is to have clearly defined names to access services. Having the library changing the names you provide is clearly a bug.

I have lots of existing data structures I want to transfer and if I have to build an extra adapter layer around every grpc message, I might as well not use it.

**Comment by nicolasnoble** [comment]
I'd like to insist on what @murgatroid99 is saying: this isn't really anything that gRPC has any control on, which is the reason I'm going to close this issue. We just happen to showcase how to use protobuf in our code and examples because it's another Google product, but it's not mandatory, You can in fact send plain json and bypass the whole serialization layer if you wish, or you can use another serialization protocol. Or in other words, this issue really doesn't belongs in the grpc, but as @murgatroid99 said, it belongs in protobuf, as there's nothing we could change in our codebase that could affect what you're (reasonably) complaining about. Any meaningful change to address your concern would be done in protobuf.

I'd also add that for nodejs, we're showcasing both protoc and protobufjs as serialization layers, and protobufjs won't rename your fields the way protoc does. See https://github.com/grpc/grpc/tree/master/examples/node/dynamic_codegen for an example, and https://www.npmjs.com/package/protobufjs for an description of this serialization layer.
