### ISSUE TITLE
Grpc.Core nuget package causes linux and osx libs to be copied to output

### ISSUE THREAD

**Issue by wojciechrak** [grpc/grpc#16923]
### What version of gRPC and what language are you using?
 Grpc.Core.1.7.1 nuget package, C#
 
### What operating system (Linux, Windows, …) and version?
 Windows 10
 
### What runtime / compiler are you using (e.g. python version or version of gcc)
 .NET 4.7
 
### What did you do?
Add Grpc.Core nuget package to project, build.
 
### What did you expect to see?
 Required dll's are copied to output directory (/bin/Debug)
 
### What did you see instead?
 Dll's are copied, but so are linux and osx files:
* libgrpc_csharp_ext.x64.so
* libgrpc_csharp_ext.x86.so
* libgrpc_csharp_ext.x64.dylib
* libgrpc_csharp_ext.x86.dylib

### Anything else we should know about your project / environment?
I assume this is due to `Grpc.Core.targets` file in /build/net45 folder inside nuget package.

We have a fairly large solution and Grpc.Core is added to one of the common libraries, causing these files to spread across many folders. These 4 files make together about 23Mb so it adds up quickly.

**Comment by jtattermusch** [comment]
What kind of project are you using? A "Classic" .csproj   or dotnet SDK projects?

You're right that this is because Grpc.Core.targets file (https://github.com/grpc/grpc/blob/340bffa55560f02944dd81413aa764081a60f329/src/csharp/Grpc.Core/build/net45/Grpc.Core.targets#L4), but this is working as intended. The idea is that when you build a legacy .csproj project, the resulting build should be portable and work on all platforms - Linux, Windows and Mac. They only way to achieve that is to copy all native libraries that gRPC C# depends on.

If you need a more file-grained control of target platforms and not so much of copying native libraries around, use a "dotnet SDK" project targeting netcoreapp2.x, as the native library support there is much better - the right version of native library will be copied and there's also "dotnet publish" command where you can build for a specific platform (and thus only copying the right native libraries to a target that's deployable).

**Comment by jtattermusch** [comment]
What kind of project are you using? A "Classic" .csproj   or dotnet SDK projects?

You're right that this is because Grpc.Core.targets file (https://github.com/grpc/grpc/blob/340bffa55560f02944dd81413aa764081a60f329/src/csharp/Grpc.Core/build/net45/Grpc.Core.targets#L4), but this is working as intended. The idea is that when you build a legacy .csproj project, the resulting build should be portable and work on all platforms - Linux, Windows and Mac. They only way to achieve that is to copy all native libraries that gRPC C# depends on.

If you need a more file-grained control of target platforms and not so much of copying native libraries around, use a "dotnet SDK" project targeting netcoreapp2.x, as the native library support there is much better - the right version of native library will be copied and there's also "dotnet publish" command where you can build for a specific platform (and thus only copying the right native libraries to a target that's deployable).

**Comment by wojciechrak** [comment]
We are using both "classic" and "SDK" .csprojs.
Good to know this doesn't affect the latter, another reason to migrate faster.
Thanks for clarification.
