### ISSUE TITLE
Unable to re-establish connection after network disconnect

### ISSUE THREAD

**Issue by lucifercr07** [grpc/grpc#16974]
### What version of gRPC and what language are you using?
 1.12, C++
 
### What operating system (Linux, Windows, …) and version?
 Ubuntu 16.04
 
### What runtime / compiler are you using (e.g. python version or version of gcc)
 gcc 5.4.0
 
### What did you do?
After grpc connection established for streaming channel, Disconnected the network connection and re-established again, the server was able to detect the failure to access the client, but the client doesn't disconnect with any error code neither receives any message from server.
 
### What did you expect to see?
Client should have received the messages after network connection re-established or should have broken the channel with error code. 
 
### What did you see instead?
Neither the client disconnects with error nor it start receiving message after network re-established.
Client remains stuck in while loop.

**Comment by srini100** [comment]
How are you causing network breakage? Default linux TCP timeout can be as large as 15-20mins. Client side socket won't fail until TCP timeout happens. For faster connection breakage detection, you should enable keepalive on the channel. In your case, since server is detecting the breakage and stopping the stream, client will have to restart the RPC after it also detects connection breakage.

**Comment by lucifercr07** [comment]
Causing network breakage by disconnecting the VM's network.

**Comment by srini100** [comment]
Default TCP time is quite long so you should use [keepalive](https://github.com/grpc/grpc/blob/master/doc/keepalive.md) if you want to detect connection breakage sooner.

**Comment by lucifercr07** [comment]
One more question, if the client disconnects due to network disconnection or some other issue, is there someway for server to know about client disconnect?
Any param which server can read for it's responseObserver to determine client has disconnected or stream is broken?

**Comment by srini100** [comment]
If the network breakage is such that only TCP timeout can detect it then server will take that long to call onError() of the responseObserver. You can use keepalive on the server side too in order to detect network breakage early. I will close this issue since there does not seem to be a bug here. You seem to be using grpc-java so if you think there is a bug please open an issue in [java repo](https://github.com/grpc/grpc-java/) with a minimal repro.
