### ISSUE TITLE
GRPC cross-compilation fails with protoc

### ISSUE THREAD

**Issue by prathrahate** [grpc/grpc#17052]
I am trying to cross compile gRPC-1.12.0 from source for armv8.
I am able to link protoc to grpc but compilation of gRPC is failing as it is trying to use protoc binary generated for arm on x86.
 
 I am using x86_64 as a host with Ubuntu 16.04.

 I am using gcc-linaro-5.4-2017.05 cross compiler toolchain.

I am using cmake for cross compiling gRPC. I am doing this with help of conan package manager.

My cmake command is as follows:
cmake .  -DgRPC_INSTALL=ON -Dprotobuf_BUILD_TESTS=OFF

Following is the error is see:
[ 35%] Building CXX object CMakeFiles/grpc++.dir/src/cpp/server/server_builder.cc.o
[ 35%] Building CXX object CMakeFiles/grpc++.dir/src/cpp/server/server_cc.cc.o
[ 35%] Building CXX object CMakeFiles/grpc++.dir/src/cpp/server/server_context.cc.o
[ 35%] Building CXX object CMakeFiles/grpc++.dir/src/cpp/server/server_credentials.cc.o
[ 35%] Building CXX object CMakeFiles/grpc++.dir/src/cpp/server/server_posix.cc.o
[ 35%] Building CXX object CMakeFiles/grpc++.dir/src/cpp/thread_manager/thread_manager.cc.o
[ 35%] Building CXX object CMakeFiles/grpc++.dir/src/cpp/util/byte_buffer_cc.cc.o
[ 35%] Building CXX object CMakeFiles/grpc++.dir/src/cpp/util/status.cc.o
[ 35%] Building CXX object CMakeFiles/grpc++.dir/src/cpp/util/string_ref.cc.o
[ 35%] Building CXX object CMakeFiles/grpc++.dir/src/cpp/util/time_cc.cc.o
[ 35%] Building CXX object CMakeFiles/grpc++.dir/src/cpp/codegen/codegen_init.cc.o
[ 35%] Linking CXX static library lib/libgrpc++.a
[ 35%] Built target grpc++
**[ 35%] _Running gRPC C++ protocol buffer compiler on src/proto/grpc/status/status.proto_
/home/user/.conan/data/protobuf/3.5.0/stable/package/7ec030835ab71d1d2ea72adf6ee0b05ee71915d2/bin/protoc: 1: /home/user/.conan/data/protobuf/3.5.0/stable/package/7ec030835ab71d1d2ea72adf6ee0b05ee71915d2/bin/protoc: ELF�P@@*@@@@@@@��@@@@8%8%8%8%A8%A��X%X%AX%APP@@DDP�td: not found
/home/user/.conan/data/protobuf/3.5.0/stable/package/7ec030835ab71d1d2ea72adf6ee0b05ee71915d2/bin/protoc: 1: /home/user/.conan/data/protobuf/3.5.0/stable/package/7ec030835ab71d1d2ea72adf6ee0b05ee71915d2/bin/protoc: Syntax error: word unexpected (expecting ")")
CMakeFiles/grpc++_error_details.dir/build.make:63: recipe for target 'gens/src/proto/grpc/status/status.grpc.pb.cc' failed
make[2]: *** [gens/src/proto/grpc/status/status.grpc.pb.cc] Error 2
CMakeFiles/Makefile2:629: recipe for target 'CMakeFiles/grpc++_error_details.dir/all' failed
make[1]: *** [CMakeFiles/grpc++_error_details.dir/all] Error 2
Makefile:127: recipe for target 'all' failed
make: *** [all] Error 2**
How can make gRPC to use native protoc (x86_64) binary when cross-compiling??

**Comment by BlackFrog1** [comment]
I am using [Yocto Project](https://en.wikipedia.org/wiki/Yocto_Project) on Ubuntu 17.10 inside a Docker container to cross-compile for armv8.  The recipe I am using is for version 1.14.1 which patches the build process.  You might have to do the same thing,

Recipe for grpc 1.14.1: http://layers.openembedded.org/layerindex/recipe/86424/
Fix libraries installation for Linux: http://cgit.openembedded.org/meta-openembedded/tree/meta-networking/recipes-devtools/grpc/grpc/0001-CMakeLists.txt-Fix-libraries-installation-for-Linux.patch?h=master
Fix grpc_cpp_plugin path during cross: http://cgit.openembedded.org/meta-openembedded/tree/meta-networking/recipes-devtools/grpc/grpc/0001-CMakeLists.txt-Fix-grpc_cpp_plugin-path-during-cross.patch?h=master

Below is the Dockerfile I use:
<pre>
FROM ubuntu:17.10
ENV DEBIAN_FRONTEND noninteractive

# Make sure the package repository is up to date
RUN apt-get update && \
    apt-get install -y apt-utils && \
    apt-get -y upgrade

# Set the locale 
RUN apt-get install -y locales && \
    locale-gen en_US.UTF-8  
ENV LANG='en_US.UTF-8' LANGUAGE='en_US:en' LC_ALL='en_US.UTF-8'

# Install packages we cannot leave without...
RUN apt-get install -y git tig mc sudo openssh-server
# Make sure the directory exists, otherwise sshd will not start
RUN mkdir -p /var/run/sshd
RUN apt-get install -y screen

# Android Repo needs
RUN apt-get install -y curl git python3 python3.6

RUN apt-get install -y gawk wget git-core diffstat unzip \
        texinfo gcc-multilib build-essential chrpath \
        socat cpio python python3 python3-pip python3-pexpect \
        xz-utils debianutils iputils-ping libsdl1.2-dev xterm 
# add the apt-get clean

# ADD https://commondatastorage.googleapis.com/git-repo-downloads/repo /usr/local/bin/
ADD https://storage.googleapis.com/git-repo-downloads/repo /usr/local/bin/
RUN chmod 755 /usr/local/bin/*

# All builds will be done by user teamcity because Yocto doesn't allow builds to be run as root
RUN groupadd -g 2000 build \
  && useradd -u 5000 -ms /bin/bash teamcity -G sudo,build
USER teamcity
# All my meta/layer and recipes are located in our on-premise source control
COPY ssh_buildprivate /home/teamcity/.ssh/id_rsa
COPY ssh_buildpublic /home/teamcity/.ssh/id_rsa.pub
COPY ssh_know_hosts /home/teamcity/.ssh/known_hosts


WORKDIR /home/teamcity

ENTRYPOINT ["/bin/bash"]

# Expose sshd port
EXPOSE 22
</pre>

![grpc build](https://user-images.githubusercontent.com/550820/48099827-ef6a7e80-e1ee-11e8-8c94-8d830da04689.png)

**Comment by jtattermusch** [comment]
It looks like https://github.com/grpc/grpc/pull/11795 should fix this?

**Comment by Croydon** [comment]
Same error got reported to our Conan recipe so I'm guessing it is now fixed

https://github.com/inexorgame/conan-grpc/issues/11
