### ISSUE TITLE
C++ bindings don't handle "address already in use" error.

### ISSUE THREAD

**Issue by stefanseefeld** [grpc/grpc#17075]
Using the C++ example code (https://github.com/grpc/grpc/blob/master/examples/cpp/helloworld/greeter_async_server.cc#L48-L66) I observe the application crashing whenever I use a port that is already in use.
The app generates this output:
```
E1031 09:38:38.665407803   31533 server_chttp2.cc:40]        {"created":"@1541003918.665302896","description":"No address added out of total 1 resolved","file":"/home2/shenderson/GRPC/Google/grpc/git/grpc/src/core/ext/transport/chttp2/server/chttp2_server.cc","file_line":307,"referenced_errors":[{"created":"@1541003918.665293235","description":"Failed to add any wildcard listeners","file":"/home2/shenderson/GRPC/Google/grpc/git/grpc/src/core/lib/iomgr/tcp_server_posix.cc","file_line":324,"referenced_errors":[{"created":"@1541003918.665262621","description":"Unable to configure socket","fd":5,"file":"/home2/shenderson/GRPC/Google/grpc/git/grpc/src/core/lib/iomgr/tcp_server_utils_posix_common.cc","file_line":214,"referenced_errors":[{"created":"@1541003918.665254234","description":"OS Error","errno":98,"file":"/home2/shenderson/GRPC/Google/grpc/git/grpc/src/core/lib/iomgr/tcp_server_utils_posix_common.cc","file_line":192,"os_error":"Address already in use","syscall":"listen"}]},{"created":"@1541003918.665292121","description":"Unable to configure socket","fd":5,"file":"/home2/shenderson/GRPC/Google/grpc/git/grpc/src/core/lib/iomgr/tcp_server_utils_posix_common.cc","file_line":214,"referenced_errors":[{"created":"@1541003918.665286553","description":"OS Error","errno":98,"file":"/home2/shenderson/GRPC/Google/grpc/git/grpc/src/core/lib/iomgr/tcp_server_utils_posix_common.cc","file_line":192,"os_error":"Address already in use","syscall":"listen"}]}]}]}
```, 
but  there doesn't seem to a way for the user to handle this error.

(I'm running gRPC 1.14.0 on Linux.)

**Comment by nicolasnoble** [comment]
What's the crash exactly?

**Comment by stefanseefeld** [comment]
I observe a segfault (immediately following the above error output).

**Comment by nicolasnoble** [comment]
Could you share reproduction code?

**Comment by stefanseefeld** [comment]
As per my original post, it's this repo's own examples/cpp/hello_world/greeter_server example that crashes: https://github.com/grpc/grpc/blob/master/examples/cpp/helloworld/greeter_server.cc

**Comment by nicolasnoble** [comment]
Ah, sorry, I had skipped this part.

The hello world example isn't very complete in terms of handling errors and return values. It's a balance between showing an extremely minimal piece of code demonstrating how to do an RPC, and showing a much more complete piece of code taking care of catching errors and acting on them.

In this specific case, the problem is that `AddListeningPort` shall return 0, as specified in [its documentation](https://github.com/grpc/grpc/blob/master/include/grpcpp/impl/codegen/server_interface.h#L126). The example code is ignoring the return value of 0, and goes on with trying to listen anyway, which causes an assert to fire.

The correct way would be to assign and inspect the return value of `AddListeningPort` which indicates the error you've seen in the logs.

**Comment by stefanseefeld** [comment]
I see ! Is there a way to retrieve the actual error (once I detect that '0' return value) ?
It would be great to improve the example by covering this error condition (or to add some notes with references).
Thanks either way !

**Comment by stefanseefeld** [comment]
Minor follow-up:
You pointed me at the `ServerInterface::AddListeningPort()` function. But the example code doesn't expose that directly. It turns out the right function to check is `ServerBuilder::BuildAndStart()`, which returns a `nullptr_t` on error. And I confirm: using that allows me to handle the error a bit better.
I'm still not sure how I could retrieve the actual error condition (so I can report it back to the caller).
Perhaps you know how to do that ?

**Comment by nicolasnoble** [comment]
CC @vjpai - I think there was a conscious decision here not to expose this, but I can't be 100% certain.

**Comment by stefanseefeld** [comment]
Perhaps there is a policy not to use exceptions (which would be the easiest way to propagate such info back to the caller) for some reason. But *some* mechanism is required to inform the caller why the call failed.

**Comment by mehrdada** [comment]
`AddListeningPort` also takes an optional `int*` argument that gets populated with the port upon binding. However the API is misleading in that you have to check the value of the pointer argument you pass **after** calling `BuildAndStart`, not right after `AddListeningPort`, since the binding does not happen right then.

**Comment by joexue** [comment]
Do we have a solution/work around here? We would not like it just to crash the program.
