### ISSUE TITLE
gRPC does not support `npm link`

### ISSUE THREAD

**Issue by rocketraman** [grpc/grpc#17118]
This is a followup to https://github.com/grpc/grpc/issues/10786.

That issue was closed, but the gRPC lib still seems to have some type of non-standard behavior in the case of using `npm link` with node 10 and npm 6.4.1.

I have a library that exposes grpc message and service definitions. This library has a `peerDependency` of grpc 1.15.1.

I have a consumer application that imports this library via `npm link`. It has a dependency of *the same version of grpc*, 1.15.1.

However, when attempting to create a channel with `grpc.credentials.createInsecure() `, there is a `TypeError:`

```
/home/raman/source/myproject/lib-proto/node_modules/grpc/src/client.js:400
      this.$channel = new grpc.Channel(address, credentials, channel_options);
                      ^

TypeError: Channel's second argument must be a ChannelCredentials
    at ServiceClient.Client (/home/raman/source/myproject/lib-proto/node_modules/grpc/src/client.js:400:23)
    at new ServiceClient (/home/raman/source/myproject/lib-proto/node_modules/grpc/src/client.js:823:12)
    at Module../src/resolvers/transports/grpc.js (/home/raman/source/myproject/api-broker/build/bundle.js:1101:29)
    at __webpack_require__ (/home/raman/source/myproject/api-broker/build/bundle.js:20:30)
    at Module../src/server.js (/home/raman/source/myproject/api-broker/build/bundle.js:2700:84)
    at __webpack_require__ (/home/raman/source/myproject/api-broker/build/bundle.js:20:30)
    at /home/raman/source/myproject/api-broker/build/bundle.js:84:18
    at Object.<anonymous> (/home/raman/source/myproject/api-broker/build/bundle.js:87:10)
    at Module._compile (internal/modules/cjs/loader.js:686:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
Waiting for the debugger to disconnect...
```

The workaround of exporting `grpc` from the library and importing it from the library instead of from `grpc` works, but really shouldn't be necessary.

**Comment by nicolasnoble** [comment]
We've successfully used npm link in the past. Would you mind sharing what you're doing exactly, if possible with a small reproduction case that exhibits the issue?

**Comment by murgatroid99** [comment]
The use of `npm link` here almost definitely means that the consumer application is using two separate instances of gRPC, and they are constructing a `ChannelCredentials` object using one of those instances and passing it to the other instance. This does not work with gRPC because of how the native module does type checking. In normal situations, npm would avoid this problem by consolidating compatible dependencies on the same library, so that there wouldn't actually be different instances.

**Comment by rocketraman** [comment]
No, I am not constructing `ChannelCredentials` on both sides, at least not explicitly. On the library side `@myorg/lib-proto`:

```
// these are produced by protoc.js
var messages = require('foo/MyService_pb')
var services = require('foo/MyService_grpc_pb')

module.exports.myServiceProtos = {
  messages,
  services
}
```

and on the consumer side, with the library side `npm link`ed:

```
import grpc from 'grpc'
import { myServiceProtos } from '@myorg/lib-proto'
import TimestampProtos from 'google-protobuf/google/protobuf/timestamp_pb'

const myServiceClient = new myServiceProtos.services.MyServiceClient(serviceHostPort, grpc.credentials.createInsecure())
```

Calling `grpc.credentials.createInsecure()` is what throws the exception.

**Comment by rocketraman** [comment]
I'll also note the workaround I am using is, on the library side to add to the same `index.js`:

```
var grpc = require('grpc')
module.exports.grpc = grpc
```

and then on the consumer side to do:

```
import { grpc, myServiceProtos } from '@myorg/lib-proto'
```

instead of importing grpc directly. This seems wrong though -- I've never had to do anything similar for any other node package.

**Comment by murgatroid99** [comment]
What I'm saying is that the instance of grpc that you get from `import grpc from 'grpc'` in the second code block is different from the instance of grpc used by `@myorg/lib-proto`, and that is the problem. That is why re-exporting grpc solves the problem. The reason that you have different grpc instances in the first place is that you are using npm link.

**Comment by rocketraman** [comment]
> The reason that you have different grpc instances in the first place is that you are using npm link.

So is this a bug / limitation of npm then?

**Comment by murgatroid99** [comment]
This is a consequence of the way you are using npm, and how that interacts with the API you have chosen to expose. You have chosen in your API to directly export a grpc `Client` object without either also exporting the `credentials` API or handling credentials internally within your library. This choice is why your library's user needs to have a separate dependency on grpc. As previously mentioned, you cannot use objects created in one instance of grpc with another instance, which is why you are experiencing this problem when using `npm link`, which prevents npm from de-duplicating those dependencies.

The correct solution here is not to export grpc APIs in your own API, but to handle things somehow in your own library so that your users don't have to depend on grpc to use it.

**Comment by stefanobaghino-da** [comment]
I see the point you are trying to make, but I'd like to point out the use case in particular, as reported by @rocketraman:

> the entire extent of the code is an index.js file that exposes the generated files from protoc as a module

In the case where you want to just neatly package the generated code, you have to rely on the user depending on gRPC to, for instance, pass the credentials to the services.

Still, authors of such packages would probably like to have a way to ensure that the produced artifact works as expected, but `npm link` is not a viable option in this case.

I've worked around the problem using `npm pack` instead of `npm link`, but it's probably uncommon to use it for this (I followed the advice in this [blog post](https://medium.com/@vcarl/problems-with-npm-link-and-an-alternative-4dbdd3e66811)).

Perhaps there's no way to allow the usage of `npm link` for this use case, but do you think it would be worth to spend a few words on the documentation regarding this, so that authors of "thin packages" are aware of this and how to work in this case?

**Comment by murgatroid99** [comment]
There is another solution I've been thinking about that would help those kind of thin packages. The protoc-based code generator would have an option to output a package definition object instead of a `Client` constructor, essentially following the `@grpc/proto-loader` model. With this option, the library would not depend on grpc at all, and instead the user would load the output into whatever grpc library they depend on. We are going to need this option anyway for code generated that way to be compatible with the newer `@grpc/grpc-js`.
