### ISSUE TITLE
Firestore broken by nanopb version mismatch

### ISSUE THREAD

**Issue by muxi** [grpc/grpc#17145]
Firestore got broken recently on a nanopb version mismatch problem (see #https://github.com/firebase/firebase-ios-sdk/pull/2046). There's a workaround in place for now but we should probably check if gRPC should has an internal namespaced version of nanopb (at least on iOS, like what we did for BoringSSL)

**Comment by wilhuff** [comment]
There are several parts to the the Firestore breakage:

The first is that gRPC builds nanopb with `PB_FIELD_16BIT` but Firestore builds with `PB_FIELD_32BIT`. Firestore must do so because it's for compatibility with Firebase Analytics, which is only distributed as a binary, and //third_party/nanopb in google3 is forced to `PB_FIELD_32BIT`.

Note that the public nanopb podspec (that gRPC depends upon) also uses `PB_FIELD_32BIT`: https://github.com/google/nanopb-podspec/blob/master/nanopb/0.3.9.1/nanopb.podspec#L19. This means that gRPC is already internally broken even without consideration for Firestore.

The second problem is conflicting definitions of Timestamp, but that's not the real source of conflict. If we solved the above and merely namespaced the nanopb generated code in gRPC you'd be done.

Unlike BoringSSL/OpenSSL, there's no conflict on the nanopb library itself (except for the alignment on compilation flags) so it seems unnecessary to vendor the nanopb runtime.

In my ideal world we could also solve this by not shipping the server bits by default to gRPC clients. For example if there were a gRPC/Server subspec, and only it had the Timestamp generated code and dependency on nanopb, we'd also avoid this problem (though I still think we should align on `sizeof(pb_field_t)`.

**Comment by wilhuff** [comment]
My bad, actually it looks like the client load balancing extension is the thing that uses timestamp, so the server is not involved.

What I was trying to say is that gRPC is out of step with itself: it will compile [timestamp.pb.c](https://github.com/grpc/grpc/blob/master/gRPC-Core.podspec#L821) with `PB_FIELD_16BIT` but the host workspace will compile the nanopb runtime with `PB_FIELD_32BIT` (via [nanopb cocoapod](https://github.com/grpc/grpc/blob/master/gRPC-Core.podspec#L185). I think this means that client_channel/lb_policy/grpclb is broken on iOS, completely independent of the Firestore breakage.

There are three different podpsecs mentioning PB_FIELD_:

https://github.com/google/nanopb-podspec/blob/master/nanopb/0.3.9.1/nanopb.podspec#L19
https://github.com/firebase/firebase-ios-sdk/blob/master/FirebaseFirestore.podspec#L71
https://github.com/grpc/grpc/blob/master/gRPC-Core.podspec#L96

gRPC uses `PB_FIELD_16BIT` while the others use `PB_FIELD_32BIT`. Additionally, binaries produced from google3 will also use `PB_FIELD_32BIT`.

Therefore one change is just to use PB_FIELD_32BIT everywhere.

Secondarily there's the problem that even though the nanopb cocoapod prevents us from colliding on the nanopb runtime, we're still colliding on generated code. For now that's a solved problem because we're generating the nanopb code in a C++ namespace private to Firestore, so this doesn't need solving, though others might also run into this.

**Comment by muxi** [comment]
Now that makes sense. Thanks Gil. We'll look into it.

**Comment by yihuazhang** [comment]
@muxi 

The macro `PB_FIELD_16BIT` in gRPC library is defined for the reason that when compiling ALTS handshake proto using nanopb, the generated file contains structs or tag numbers that are larger than its default size. So we need to define the nanopb type (`pb_size_t` or `pb_ssize_t`) with a larger-size type by defining either `PB_FIELD_16BIT` or `PB_FIELD_32BIT` (https://github.com/grpc/grpc/blob/master/third_party/nanopb/pb.h#L205). So, it's fine to use the latter since it will use the larger size for nanopb type, but we need to ensure all uses of `PB_FIELD_16BIT` are correctly replaced by `PB_FIELD_32BIT` in gRPC library (e.g., `setup.py` and `bazel/grpc_build_system.bzl').
