### ISSUE TITLE
Automatically Resolve Transitive Test Dependencies in Bazel Tests

### ISSUE THREAD

**Issue by gnossen** [grpc/grpc#17177]
[`requirements.bazel.txt` ](https://github.com/grpc/grpc/blob/master/requirements.bazel.txt)currently lists out *all* dependencies of the bazel tests. Unfortunately, this makes adding dependencies and updating versions quite error-prone, as we must update transitive dependencies by hand.

This has already caused [failing master builds.](https://github.com/grpc/grpc/issues/17170) It will likely cause failing builds in the future.

**Comment by gnossen** [comment]
@ghostwriternr Thoughts?

**Comment by ghostwriternr** [comment]
Hey @gnossen !
This is an issue that I faced myself too (even started a discussion at [rules_python #125](https://github.com/bazelbuild/rules_python/issues/125). I suppose we can now confirm that rules_python **does** expect implicit dependencies to be stated explicitly (also reported at [#70](https://github.com/bazelbuild/rules_python/issues/70), [#110](https://github.com/bazelbuild/rules_python/issues/70)).

As it stands, I don't know of any _existing solution_ to this. A good start would be to look at [#90](https://github.com/bazelbuild/rules_python/pull/90) from the creator of [TriggerMail/rules_pyz - one of the other popular third-party projects that tries to solve some aspects of Bazel for Python](https://github.com/TriggerMail/rules_pyz). The PR was unfortunately not merged because it was only partially working.
