### ISSUE TITLE
Undesired reconnection backoff triggered due to subchannel connection failures

### ISSUE THREAD

**Issue by ryanpbrewster** [grpc/grpc#17282]
### What version of gRPC and what language are you using?
grpc-node v1.16.1 
 
### What operating system (Linux, Windows, …) and version?
 Linux + macOS
 
### What runtime / compiler are you using (e.g. python version or version of gcc)
 node v8.9.4
 
### What did you do?
Runnable repro: https://github.com/ryanpbrewster/grpc-node-example
 
### What did you expect to see?
 Creating a new connection should happen quickly
 
### What did you see instead?
Exponential backoff kicked in despite the server being reachable from the client. The client is connecting with two subchannels, one for ipv4 and one for ipv6:
```
I1121 16:08:27.915904109  230990 subchannel_list.h:535]      [pick_first 0x3281720] subchannel list 0x3281b40 index 0: Created subchannel 0x3282630 for address uri ipv6:[::1]:50051
I1121 16:08:27.915924766  230990 subchannel_list.h:535]      [pick_first 0x3281720] subchannel list 0x3281b40 index 1: Created subchannel 0x32830e0 for address uri ipv4:127.0.0.1:50051
```

I believe the ipv6 subchannel is failing to connect and the ipv4 subchannel is succeeding. From both the client and server perspectives, the connection looks successful and the requests are being processed. However, when trying to open subsequent connections, we're running into exponential backoff:

```
{ raw: 'FOO BAR BAZ #0' }
0: 11.216ms
{ raw: 'FOO BAR BAZ #1' }
1: 998.730ms
{ raw: 'FOO BAR BAZ #2' }
2: 1328.682ms
{ raw: 'FOO BAR BAZ #3' }
3: 2734.221ms
{ raw: 'FOO BAR BAZ #4' }
4: 3765.556ms
```

If I change the server to accept ipv6 traffic, or change the client to try to connect to an explicit ipv4 address, this backoff behavior is _not_ triggered:
```
{ raw: 'FOO BAR BAZ #0' }
0: 11.141ms
{ raw: 'FOO BAR BAZ #1' }
1: 1.473ms
{ raw: 'FOO BAR BAZ #2' }
2: 1.094ms
{ raw: 'FOO BAR BAZ #3' }
3: 1.185ms
{ raw: 'FOO BAR BAZ #4' }
4: 1.150ms
{ raw: 'FOO BAR BAZ #5' }
5: 0.932ms
{ raw: 'FOO BAR BAZ #6' }
6: 1.117ms
{ raw: 'FOO BAR BAZ #7' }
7: 0.918ms
{ raw: 'FOO BAR BAZ #8' }
8: 0.917ms
{ raw: 'FOO BAR BAZ #9' }
9: 0.927ms
```

**Comment by markdroth** [comment]
I don't see why backoff is an issue in the scenario you're describing.  The backoff is per-subchannel, but pick_first should move on to the next subchannel in the list as soon as the first subchannel reports TRANSIENT_FAILURE and goes into backoff.  In other words, the fact that the first subchannel is in backoff should not actually cause any delay in connecting to the second subchannel.

I'm not sure what's actually happening here, but I think we should fully understand it before we decide what to do about it.

**Comment by markdroth** [comment]
Looking at the log in more detail, I think I understand the problem.  It looks like the client code is actually creating a new channel for each request.  On the first request, there is no delay, because (as I mentioned above) pick_first does not wait for the first subchannel's backoff period before moving on to the second subchannel.  However, when the second channel is created, it reuses the same subchannels created by the first channel (due to subchannel sharing), and since the first channel is already in backoff, pick_first waits for that subchannel to make a new attempt before it gives up and moves on to the second subchannel.  (The first subchannel starts in TRANSIENT_FAILURE, and pick_first waits for it to go CONNECTING and then back into TRANSIENT_FAILURE before moving on to the next subchannel.)

Creating a new channel for each request is wasteful and inefficient.  If you change the code to create a single channel and use that single channel for all your requests, this problem should not occur.

I think the behavior here is essentially working as intended.  We've talked before about optimizing this kind of case a little bit by having pick_first check to see whether any of the subchannels are already in READY state when it starts up, in which case it can immediately pick the first READY one and not bother trying any of the previous ones.  And we could still do that, but I don't really feel any urgency about this, since this is kind of an artificial problem -- it's only being triggered because the application is inappropriately creating multiple channels for the same server name.

Also, with respect to the IPv6 vs. IPv4 thing, we've talked about possibly doing an implementation of Happy Eyeballs (https://tools.ietf.org/html/rfc8305), but we haven't had time to look into it in any detail.  For now, I agree that we should advise people to not give their clients IPv6 addresses if those addresses are not going to actually work.

**Comment by AspirinSJL** [comment]
Yes, I should have mentioned that the user is creating multiple channels to the same server. (And in nodejs the channel created in one iteration won't be destroyed immediately when exiting that iteration.)

I think the reason that @ryanpbrewster is creating multiple channels to the same server is that they need to do this in some test.

The Happy Eyeballs algorithm seems the optimal solution to this issue. But before we implement that, is there a good place to document this issue or add some warning? [Here](https://github.com/grpc/grpc/blob/master/include/grpcpp/create_channel.h#L38) and all the counterparts in other languages?

**Comment by markdroth** [comment]
It's not clear to me why you would need to create multiple channels, even in a test.  I'd like to understand why that's justified before putting any effort into this.

I'd like input from @ejona86 and @dfawley as to the right place to document the IPv6/IPv4 issue across languages.

**Comment by ryanpbrewster** [comment]
Our SDK is a heavy wrapper around a gRPC connection. We do not expose that gRPC connection to end users; it is entirely contained inside of the SDK classes.

These tests create multiple SDK instances (to enable testing how multiple clients will behave). Without major refactoring, this use-case requires us to set up multiple gRPC connections (one per SDK instance).

**Comment by markdroth** [comment]
Okay, I guess we should go ahead and change pick_first to check to see if any of its subchannels are already in READY state when it starts up.  If it finds one in READY state, it can pick that one immediately without checking any of the others.

**Comment by ejona86** [comment]
@markdroth, do Go and Java suffer from this problem, since backoff is done differently in those languages?

It seems like this is simply another case that would be solved by changing where the backoff is done in C. In Go/Java, 1) the backoff is only applied after trying all addresses and 2) there is no subchannel sharing to pollute the backoff. It seems like each of those independently avoid this problem.

**Comment by markdroth** [comment]
Yes, I agree -- this is an issue only in C-core.  If we were either (a) doing the backoff at a higher level instead of in the subchannel or (b) not doing subchannel sharing, this would not be an issue.

We can fix this either by moving the backoff up to a higher level or by changing pick_first to check if any of its subchannels are already in READY state when it comes up.  We do intend to move the backoff code anyway, but that's probably a more invasive change; I think we can fix this more quickly with the pick_first change, and I think that's a useful optimization in its own right, which is why I proposed that course of action above.

As a short-term work-around, users can avoid this by inhibitting subchannel sharing.  There's no clean way to do this right now (although we plan to offer a better way to do this; see discussion in #15841), but there's a hack you can use, which is to specify a bogus channel arg with a different value for each channel that you create.  Because the channel args are part of the unique ID that we use internally for the subchannel, this will mean that each channel will have disjoint sets of keys for its subchannels, so they won't be shared.  But note that the result of this will be creating duplicate connections to each address.

**Comment by ejona86** [comment]
> I think we can fix this more quickly with the pick_first change, and I think that's a useful optimization in its own right, which is why I proposed that course of action above.

Yeah, that sounded good to me; I should have mentioned it. I was bringing up the rest just to verify we are on the same page, which it seems we are.
