### ISSUE TITLE
C# decimal type

### ISSUE THREAD

**Issue by Sigvaard** [grpc/grpc#17293]
I'm not sure whether grpc is the right repo for this (more like a protobuf issue?)

I'm currently struggling how to serialize monetary amounts using protobuf, the only option I see is now is to use string but that is very inconvenient because you need additional code that maps those strings to decimals now.

It would be nice if deserialization to decimals was provided out of the box, or some way to customize the generator and deserializer so it could generate classes using decimal and deserialize from decimal. 

I found this: https://github.com/googleapis/googleapis/blob/master/google/type/money.proto (representing monetary amounts in "nanos") but no guidance how to use it.

**Comment by jtattermusch** [comment]
This is more of a protobuf question (https://github.com/protocolbuffers/protobuf) rather than gRPC question. 

Ad usage:
1. just take a copy of money.proto and make your .proto files import it. Then make sure you also generate C# code for the money.proto. After that, you should be able to use the Money message in your C# code no problem.
2. (alternative) import the googleapis repository as a git submodule and use the steps above.
