### ISSUE TITLE
C# build linker error in Unity app for UWP, il2cpp

### ISSUE THREAD

**Issue by MohsenneChaverdie** [grpc/grpc#17318]
### What version of gRPC and what language are you using?
 1.16. C#
 
### What operating system (Linux, Windows, …) and version?
 Windows
 
### What did you do?
I think I cannot be more specific as in this [post](https://stackoverflow.com/questions/53488605/unity-cannot-build-grpc-project-for-uwp-with-il2cpp-backend).
 
### What did you expect to see?
 To Compile without LNK errors.
 
### What did you see instead?
LNK Errors.
 
### Anything else we should know about your project / environment?
Unity Environment, UWP, IL2CPP.

**Comment by MohsenneChaverdie** [comment]
Solved. I documented it in [StackOverflow](https://stackoverflow.com/questions/53488605/unity-cannot-build-grpc-project-for-uwp-with-il2cpp-backend/53600402#53600402).

**Comment by jtattermusch** [comment]
https://github.com/grpc/grpc/pull/18039 should be at least partially fixing this.

According to the stackoverflow post https://stackoverflow.com/questions/53488605/unity-cannot-build-grpc-project-for-uwp-with-il2cpp-backend/53600402#53600402, there might be a few other places that need fixing.

**Comment by darshitg** [comment]
Having the same LNK Errors when building gRpc from Unity for uwp target. i've followed the steps from [stackoverflow](https://stackoverflow.com/questions/53488605/unity-cannot-build-grpc-project-for-uwp-with-il2cpp-backend/53600402#53600402) to solve these errors but still facing please help to solve this problem.

**Comment by MohsenneChaverdie** [comment]
> Having the same LNK Errors when building gRpc from Unity for uwp target. i've followed the steps from [stackoverflow](https://stackoverflow.com/questions/53488605/unity-cannot-build-grpc-project-for-uwp-with-il2cpp-backend/53600402#53600402) to solve these errors but still facing please help to solve this problem.

Are you using gRPC 1.16. version?

**Comment by darshitg** [comment]
> > Having the same LNK Errors when building gRpc from Unity for uwp target. i've followed the steps from [stackoverflow](https://stackoverflow.com/questions/53488605/unity-cannot-build-grpc-project-for-uwp-with-il2cpp-backend/53600402#53600402) to solve these errors but still facing please help to solve this problem.
> 
> Are you using gRPC 1.16. version?

i've grabbed from the main branch latest so it is version 1.22 or 1.23

**Comment by MohsenneChaverdie** [comment]
Aha, I see. So, the StackOverflow answer cannot help you, since they are changing gRPC rapidly. 

- try it with the newest Unity Version, 2019.2,~ or something. 
- be sure, you are using the newest Windows SDK.

Personal experience -> try to find a workaround instead of implementing gRPC in Unity: e.g. route it over UDP, it makes Unity app perform better using less code and calculation.

**Comment by jtattermusch** [comment]
Is this still a problem?

**Comment by Surabhivaghela** [comment]
> Is this still a problem?

yes

**Comment by jtattermusch** [comment]
I'm going to close issue this since we're not going to pursuit Unity/Xamarin support in `Grpc.Core` anymore.
- The `Grpc.Core` implementation is now in maintenance mode and we're only going to focus on critical and security fixes.
- Supporting Unity/Xamarin simply presents too much maintenance overhead and it's also difficult to test with the test infrastructure available to us
- The Unity/Xamarin support has always been classified as "experimental", so discontinuing the support shouldn't be too surprising.

See [the recent update on gRPC C#](https://groups.google.com/g/grpc-io/c/OTj5mb1qzb0/m/-M81UQipAQAJ) for more details.

Note that in practice, running Grpc.Core on Unity/Xamarin might still be possible (there is nothing in principle that would prevent it from working), but it will be completely at your own risk and it's simply not one of the use cases the grpc team will help you with as `Grpc.Core` on Unity/Xamarin is now considered as "not supported" by us (but you might still be able to get help from the community).
