### ISSUE TITLE
C# - Provide ARM version of grpc_csharp_ext.so

### ISSUE THREAD

**Issue by deinok** [grpc/grpc#17451]
Seems like https://www.nuget.org/packages/Grpc.Core/ is not exposing the shared libraries for ARM.

I have also noticed that the package doesn't follow the conventions for autoselect the runtime.
(I mean the /runtime/<rid>/native/*.so)

**Comment by MartinRichards23** [comment]
We'd really need ARM64 as well for our UWP projects.

**Comment by jtattermusch** [comment]
@deinok can you provide more details about the conventions you have in mind?

You're right that we currently don't provide the shared libraries for ARM (mostly because it complicates our package build process and we currently don't have a good way to test on arm), which platforms exactly are you interested in using?

**Comment by MartinRichards23** [comment]
We want to use GRPC in our UWP (Microsoft store app), currently we can't because we need to target ARM and ARM64 as well as x64 and x86.

**Comment by deinok** [comment]
Okey, commonly in C#, native libraries (.so, .dll and .dylib) aka C Libraries. Are stored in /runtimes/<RID>/native/*.{so,dll,dylib}. This way when you publish your App for a specific RID, just the correct libraries are also published, reducing size.
Actualy, for example for linux you have in /runtimes/linux/native/(x64 and x86) meaning that if a computer is x64 it will also contain the native libraries for x86. Having separated /runtimes/linux-x64/native/libgrpc_csharp_ext.x64.so and /runtimes/linux-x86/native/libgrpc_csharp_ext.x64.so

**Comment by deinok** [comment]
@jtattermusch
I don't have too much information about the structure of this project, but in some personal projects i'm working on, I use mix of clang with some tactics to cross-compile.
If you give a bit of information I think that I could generate a version ready for cross-compilation (without testing)

But anyways, I don't understand the usage of native libraries (C,C++) when the project at first look seems that it could be completely written with managed code (C#)

**Comment by jtattermusch** [comment]
@deinok  do you want to create a PR to fix the layout of `/runtimes/` directory with native libraries?

ad native/managed implementations: this topic has be reiterated many times already. We currently use the native library to avoid needing to rewrite and maintain all of gRPC's logic (with all its current and future features, some of which are highly non-trivial) in 10 languages.

**Comment by erikest** [comment]
I was able to get libgrpc_csharp_ext compiling for ARM32 by compiling it on a Raspberry Pi.

There's a repo [here](https://github.com/erikest/libgrpc_csharp_ext) that has the scripts I used.  

I posted a blog about the process [here](https://dev.to/erikest/grpc-on-dotnet-core-preview3-on-raspberrypi-3-4nf4).   The important part about that post is that the file is still named librpc_csharp_ext.x86.so because that's what NativeExtensions looks for as it hasn't been extended yet to support ARM explicitly.   I think it would be the same process to compile it for ARM64, I just haven't tried it yet - though I've seen that people have been able to get a 64 bit version of linux on a Pi, so maybe I'll give that a shot.

I added a nuget package that has the ARM32 version [here](https://www.nuget.org/packages/libgrpc_csharp_ext.arm7/).  That package uses the runtimes/ folder structure, so when you publish to linux-arm RID, it puts the right version with the published files.

Another repo [here](https://github.com/erikest/grpcpi) has the grpc template which is ready for the pi and incorporates the nuget package.

I'd love to contribute in a more formal manner, maybe add the script to the experimental folder along side the others and perhaps determine how to incorporate the ARM32 version into the actual Grpc.Core package. @jtattermusch I was told you head the effort on Grpc.Core, what do you think?

**Comment by jtattermusch** [comment]
@erikest  thank for sharing the blogpost https://dev.to/erikest/grpc-on-dotnet-core-preview3-on-raspberrypi-3-4nf4

Ad upstreaming some of your contributions:  In general, we'd love for gRPC C# to support as many platforms as possible, but there are practical limitations:
- for binaries we ship officially, we need to have test infrastructure setup to be able to build and test (which for libraries built using Pi is not trivial at all) and that's a significant investment. So we need to draw a line somewhere and consider some platforms community-supported.
- currently all the pre-built binaries are shipped as part of Grpc.Core nuget package and that package is already very large and it can't keep growing indefinitely. If we want to add more binaries, we'll need to figure out some way of splitting Grpc.Core in a way that doesn't impact the usability.

I think for now the Raspberry Pi support will need to stay community-owned, but we are open to solutions that would simplify our packaging to a point that would make it possible to upstream support for non-mainstream platforms one day.

**Comment by erikest** [comment]
@jtattermusch OK, I understand those points.  I have put the work for the Pi into a nuget package which compliments the Grpc.Core package - the only hacky part is the naming convention I'm forced to keep because NativeExtensions doesn't differentiate between ARM32 and x86 architectures. 

- Would it make sense to update NativeExtensions to correctly name ARM32/64 versions of libgrpc_csharp_ext, so that the runtime error makes more sense (right now it asks for libgrpc_chsarp_ext.x86.so on a Pi).  Then a community supported package like mine could use the 'correct' naming.

- Perhaps the splitting you're referring to would be along general processor architecture? like  Grpc.Core.Intel,  Grpc.Core.Arm?

- Would it also make sense to put the compile script into the experimental folder? The script is simple and seems to be in the same category as the android, ios and unity scripts that are there.  Or perhaps I am misunderstanding what's going on with experimental?

**Comment by jtattermusch** [comment]
> @jtattermusch OK, I understand those points. I have put the work for the Pi into a nuget package which compliments the Grpc.Core package - the only hacky part is the naming convention I'm forced to keep because NativeExtensions doesn't differentiate between ARM32 and x86 architectures.
> 
> * Would it make sense to update NativeExtensions to correctly name ARM32/64 versions of libgrpc_csharp_ext, so that the runtime error makes more sense (right now it asks for libgrpc_chsarp_ext.x86.so on a Pi).  Then a community supported package like mine could use the 'correct' naming.

Feel free to create a PR to do that.

> * Perhaps the splitting you're referring to would be along general processor architecture? like  Grpc.Core.Intel,  Grpc.Core.Arm?

that wouldn't be very usable, we would need some approach that lets all users depend on the same package Grpc.Core, but the right native libraries for given architecture would be pulled for them.
I currently don't have a good answer for this problem, so I guess it will stay open.

> * Would it also make sense to put the compile script into the experimental folder? The script is simple and seems to be in the same category as the android, ios and unity scripts that are there.  Or perhaps I am misunderstanding what's going on with experimental?

Feel free to start a pull request to add the script.
