### ISSUE TITLE
dotnet crash with System.InvalidOperationException at at Grpc.Core.Server.ShutdownInternalAsync

### ISSUE THREAD

**Issue by clehene** [grpc/grpc#17518]
### What version of gRPC and what language are you using?
 
 1.17.0

### What operating system (Linux, Windows, …) and version?

OSX 
 
### What runtime / compiler are you using (e.g. python version or version of gcc)
 
maven -> dotnet 
 
### What did you do?
If possible, provide a recipe for reproducing the error. Try being specific and include code snippets if helpful.
 
This reproduces randomly, but rather frequently after running unit tests

### What did you expect to see?
 
Succesful output
 
### What did you see instead?
 ```bash
[INFO] --- dotnet-maven-plugin:0.23:test (default-test) @ csharp-sdk.test ---
Build started, please wait...
Build completed.

Test run for [redacted]/src/sdk/csharp/csharp-sdk.test/bin/Release/netcoreapp2.1/csharp-sdk.test.dll(.NETCoreApp,Version=v2.1)
Microsoft (R) Test Execution Command Line Tool Version 15.9.0
Copyright (c) Microsoft Corporation.  All rights reserved.

Starting test execution, please wait...
...
The active test run was aborted. Reason: Unhandled Exception: System.AggregateException: One or more errors occurred. (Operation is not valid due to the current state of the object.) ---> System.InvalidOperationException: Operation is not valid due to the current state of the object.
   at Grpc.Core.Server.ShutdownInternalAsync(Boolean kill) in T:\src\github\grpc\src\csharp\Grpc.Core\Server.cs:line 212
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at Project.Test.TestBase.Finalize() in [redacted]/src/sdk/csharp/csharp-sdk.test/TestBase.cs:line 32

Test Run Aborted.
```

**Comment by jtattermusch** [comment]
It's not clear to me what it is you were trying to accomplish. Looks like you were trying to use maven to use the gRPC C# tests (which is something that we never tested and is not supported).
If you are gRPC C# contributor and you need to run gRPC C# tests, please use run_tests.py script to run them (see https://github.com/grpc/grpc/tree/master/tools/run_tests). If you are gRPC C# user, you don't need to run those, just use the nuget package.

If this is a failure in your unit tests, you need to include a code snippet that triggers the problem, otherwise we can't really do much. 

Just and idea: if you are hitting this assertion https://github.com/grpc/grpc/blob/a0c7ec851e099a625230b369f5de0f616ca9def7/src/csharp/Grpc.Core/Server.cs#L214, that probably means you are trying to invoke server.ShutdownAsync twice.
