### ISSUE TITLE
Python 2.6 support -- question

### ISSUE THREAD

**Issue by samotarnik** [grpc/grpc#17592]
Apologies for bringing this up again, there's already an [existing issue on this topic](https://github.com/grpc/grpc/issues/757) but since I'm not a project collaborator I can't ask the follow-up there.

It's simply not clear to me whether Python 2.6 support was dropped because no one found the time to do the work 4 years ago or because it got an absolute and categoric "no" from project maintainers. In other words, would you guys perhaps consider merging any changes into the repo if someone created a proper pull request?

Thanks.

Quick stats on the current `master` ([c3eb2068](https://github.com/grpc/grpc/commit/c3eb206897dcfc9fa77391501b233d7a2b0c79f7)):
```bash
$ find . -iname "*.py" | wc -l
383
$ find . -iname "*.py" | xargs python pyqver2.py | grep 2.7 | wc -l
78
```

cc/ @nathanielmanistaatgoogle

**Comment by nathanielmanistaatgoogle** [comment]
The question received an absolute and categoric "no". That "no" is even more emphatic today. We will not accept 2.6-compatibility-adding pulls request because we do not accept changes that we cannot test, and we cannot test Python 2.6 without running Python 2.6, and running Python 2.6 in 2018 (or 2019!) is irresponsible on a pretty fundamental level (2.6 hasn't gotten security patches in _how long?_).

If you missed it over in [issue 757](https://github.com/grpc/grpc/issues/757), see [this (now-three-years-old!) guidance about dropping 2.6](https://snarky.ca/stop-using-python-2-6/).

**You should stop using Python 2.6.** [You should also stop using Python 2.7](https://pythonclock.org/).
