### ISSUE TITLE
c-core seems to send aggressive keepalive PING even when not enabled

### ISSUE THREAD

**Issue by ejona86** [grpc/grpc#17667]
The problem was reported for a Python client talking to a Java server: grpc/grpc-java#5188 . The Java server was killing the connection to the client with too_many_pings. The initial comment and the gist at https://github.com/grpc/grpc-java/issues/5188#issuecomment-450033544 are pretty useful.

In short, I don't see any configuration on client-side to enable keepalive (the user linked to the code). But logs show weird PINGs after 146, 126, and 99 seconds of inactivity. The first ping in the 3-strike series could have potentially been triggered due to additional messages sent by the client application. But that does not appear that it could be the case for the second ping. (And the third ping we can't tell if any data arrived after it.)

I'm surprised by this behavior. It's unclear to me how C could have such a bug.

CC @yashykt

**Comment by yashykt** [comment]
I'm unclear too. If keepalive is disabled, the client would not be sending keepalive pings

**Comment by ejona86** [comment]
I just noticed, the pings are exactly 5 seconds apart:
```
11:16:42,784
11:21:42,784
11:26:42,784
```

**Comment by angoenka** [comment]
Thanks for looking into it.
Let me know if more information is needed.

**Comment by yashykt** [comment]
@angoenka Can you please provide the entire log on the client side?

**Comment by angoenka** [comment]
@yashykt 
Logs for one of the failing channel https://gist.github.com/angoenka/d3c56312323934557f2b9849789ff69a

**Comment by yashykt** [comment]
@angoenka That looks like the server side logs. Please share the client side logs. Please note that GRPC_TRACE environment variable would need to be set appropriately. 
GRPC_TRACE=api,http,client_channel,channel should be enough

**Comment by yashykt** [comment]
These look like BDP pings

**Comment by yashykt** [comment]
(I'm also going to add some tracing so that in the future we will know for sure if a ping is a keepalive ping or not. It should also help here)

**Comment by yashykt** [comment]
@angoenka can the experiment be tried again at head?

**Comment by lidavidm** [comment]
We've been observing this with gRPC 1.18.0 and 1.19.1, with a C++ client talking to a Java server (both sides via [Apache Arrow Flight](https://github.com/apache/arrow)). Allowing keepalive pings on the server seems to work around the issue.

**Comment by yashykt** [comment]
Looking at this again after seeing the stalebot ping. 

The pings 5 minute seem to be influenced by the default interval to wait between successive pings when there is no data to be sent. 
One possible thing that might be happening here is that the Java server does not seem to be accepting any pings even if they are 5 minutes apart.

In this case, since the keepalive pings are disabled, these pings are most likely bdp pings. Core does provide a way to disable bdp pings with GRPC_ARG_HTTP2_BDP_PROBE (set to 0) if the server does not accept any pings. Since the BDP ping is helpful for determining flow control windows, I wouldn't recommend doing that though.

**Comment by yashykt** [comment]
@ejona86, should we give some grace period to the minimum duration between pings. Alternatively, the client could just set GRPC_ARG_HTTP2_MIN_SENT_PING_INTERVAL_WITHOUT_DATA_MS to a value higher than 5 minutes and this issue will probably go away.

Keeping this issue alive for discussion.

**Comment by ejona86** [comment]
> The pings 5 minute seem to be influenced by the default interval to wait between successive pings when there is no data to be sent.

What are you talking about? We shouldn't have any such default interval.

> In this case, since the keepalive pings are disabled, these pings are most likely bdp pings.

There's no _receiving_ of data by C core, so these would not be BDP pings either. Unless you're saying you think the BDP ping stuff is the location of the bug.

It seems very strange to me to see pings _exactly_ 5 minutes apart, without user traffic to coincide, with an outstanding and idle RPC, and think it isn't keepalive-related. grpc-java didn't send any data in the 5 minute period, so that is the behavior we'd "expect" if keepalive was configured.

> should we give some grace period to the minimum duration between pings

There is a natural "built-in" grace period of a RTT + processing overhead, in addition to ~+1 of the clock resolution. (Java uses clocks with 30ns-1µs resolution.) This is mainly for clock skew and similar.

It looks like [C is using millisecond precision](https://github.com/grpc/grpc/blob/615cd251b8de723a9ff75ac46db54f5de7bd2ec8/src/core/ext/transport/chttp2/transport/chttp2_transport.cc#L2865). The grace period isn't large enough for 1ms swings. Maybe C should add 1ms to its timer to handle now() being rounded?

> Keeping this issue alive for discussion.

Do you not agree there is obviously a bug somewhere in C core? I can accept there may be a bug in Java as well, but _at least_ C needs a bug fix for these pings-that-should-not-have-been-sent.

**Comment by yashykt** [comment]
To clarify, I'm not suggesting that gRPC should always be sending pings without any reason. What I am saying instead is that if pings were sent even if they were bdp, they would be 5 minutes apart by default. (The default value for GRPC_ARG_HTTP2_MIN_SENT_PING_INTERVAL_WITHOUT_DATA_MS). Wait, so Java doesn't allow any pings if keepalive is disabled?

Someone IS sending the ping. From my reading of the bdp code, it looks like a timer with a backoff mechanism which decides when to send the ping. From that, it seems likely that is the bdp ping. If we have more logs with http trace, we would know for sure. (I had made modifications to the logs so that we know who is starting the ping). Actually, I can start a simple streaming RPC without any activity and see the results myself. (If that is the same scenario as the original reporter). If it is indeed the case that it is the bdp being sent, are you suggesting that it is a bug and that it should not be sending pings so?

**Comment by ejona86** [comment]
It sounds like `GRPC_ARG_HTTP2_MIN_SENT_PING_INTERVAL_WITHOUT_DATA_MS` is based on _received_ DATA frames. There is no point to BDP estimation if you didn't receive any DATA frames. BDP estimation sends a PING _when receiving a DATA frame_. I would expect this only to only be important to keepalive. I would understand how this would apply to BDP if it was for _sent_ DATA/WU frames (to avoid restrictions in some servers).

> Wait, so Java doesn't allow any pings if keepalive is disabled?

"allow pings" and "keepalive enabled" are completely separate. One is receiving, and one is sending. I don't know what this is thinking, so can't respond precisely. But Java does allow pings, but with the server-side restrictions defined in the keepalive doc.

> If it is indeed the case that it is the bdp being sent, are you suggesting that it is a bug and that it should not be sending pings so?

Absolutely. I can't figure out any benefit in sending a PING at that time. I can sort of understand "how you could have gotten here" if the code wanted to send a PING and couldn't at the time so it set a timer and sent the PING later. That is completely useless and should be removed, but I can understand the mistake. But the behavior here is worse, because it keeps sending PINGS, even without any more DATA.

**Comment by yashykt** [comment]
Looking at https://github.com/grpc/proposal/blob/master/A8-client-side-keepalive.md, GRPC_ARG_HTTP2_MIN_RECV_PING_INTERVAL_WITHOUT_DATA_MS (the server side setting) seems to be replicating the behavior of PERMIT_KEEPALIVE_TIME described in the doc. 
> What are you talking about? We shouldn't have any such default interval.
Note that this also falls in line with the default value of 5 minutes that the doc mentions for PERMIT_KEEPALIVE_TIME. Please let me know if I am misinterpreting this.

GRPC_ARG_HTTP2_MIN_SENT_PING_INTERVAL_WITHOUT_DATA_MS seems to be following the client's way of tracking whether the server will accept the ping or not, and hence it tracks whether it has **received** data/header frames or not. Since Core is using pings for other uses including bdp and allowing the application to send pings, it limits the number of pings sent by this. This also means that for a KEEPALIVE_TIME of less than 5 minutes, the client should also set GRPC_ARG_HTTP2_MIN_SENT_PING_INTERVAL_WITHOUT_DATA_MS to that period, so that keepalives can work properly. (Ofcourse, the server's PERMIT_KEEPALIVE_TIME would also need to be adjusted accordingly.)

> But Java does allow pings, but with the server-side restrictions defined in the keepalive doc.
I would then assume that the java server is allowing pings to be atleast 5 minutes apart.

For BDP pings, I agree that there is no benefit for bdp pings to exist when there are no data frames being exchanged, and it seems that gRPC Core is using GRPC_ARG_HTTP2_MIN_SENT_PING_INTERVAL_WITHOUT_DATA_MS to limit bdp pings, which does not seem ideal. This along with the resulting window size of 4MB when BDP ping is enabled might not be ideal and would need to be looked at.

**Comment by yashykt** [comment]
For the current bug, I set up a test client-server environment and verified that bdp pings are indeed being sent even if there is no data being received and it is bottlenecked by both GRPC_ARG_HTTP2_MIN_SENT_PING_INTERVAL_WITHOUT_DATA_MS and GRPC_ARG_HTTP2_MAX_PINGS_WITHOUT_DATA. (Refer https://github.com/grpc/grpc/blob/master/doc/keepalive.md for explanation)

**Comment by ejona86** [comment]
@yashykt and I investigated this. This is due to BDP pings and GRPC_ARG_HTTP2_MIN_SENT_PING_INTERVAL_WITHOUT_DATA_MS. The BDP ping is based on a _period_, not incoming data. That period is increased or decreased depending if the BDP is seen to increase. I was not aware of this behavior when designing keepalive.

So what's happening is the BDP is at its smallest default period, 5 minutes. Since that period is locally-decided, it has no slack and will upset some gRPC servers monitoring for keepalive pings.

In the short term, you can change GRPC_ARG_HTTP2_MIN_SENT_PING_INTERVAL_WITHOUT_DATA_MS to be 5 minutes and 1 second, or change the server to allow pings every 4 minutes 59 seconds (you can choose to change them by more than a second; 5 seconds is good, too).

During this investigation, we found a couple different things that need to be improved. We're still working on figuring out what all we want to change.

**Comment by yashykt** [comment]
The BDP fix PR finally got merged. Waiting on https://github.com/grpc/proposal/pull/203 and then we should be able to deprecate GRPC_ARG_HTTP2_MIN_SENT_PING_INTERVAL_WITHOUT_DATA_MS too.
