### ISSUE TITLE
Evaluate supported operating systems for pthread_t cast safety

### ISSUE THREAD

**Issue by bbarenblat** [grpc/grpc#17713]
[log_posix.cc currently defines `gettid`](https://github.com/grpc/grpc/blob/75b8b1e2c6a1e27167e288c858c35b389215d75a/src/core/lib/gpr/log_posix.cc#L33) as

```c
static intptr_t gettid(void) { return (intptr_t)pthread_self(); }
```

[Per POSIX.1-2017](http://pubs.opengroup.org/onlinepubs/9699919799/basedefs/pthread.h.html), `pthread_self` returns `pthread_t`, so this is a cast from `pthread_t` to `intptr_t`.

It would be nice to know that this cast is safe. POSIX allows `pthread_t` to be a struct (see “Issue 6” in [sys/types.h](http://pubs.opengroup.org/onlinepubs/9699919799/basedefs/sys_types.h.html)), so there’s no guarantee in the standards that casting `pthread_t` to `intptr_t` is okay. However, macOS, FreeBSD, and OpenBSD all define `pthread_t` as a pointer, so the cast is at least safe there. I have no idea about Solaris and AIX, which are also listed in [port_platform.h](https://github.com/grpc/grpc/blob/75b8b1e2c6a1e27167e288c858c35b389215d75a/include/grpc/impl/codegen/port_platform.h).

**Comment by 54markov** [comment]
Hi. The Glibc-2.29 implementation told us that `pthread_t` is an arithmetic type.

- can't find official link: [link to glibc 2.29](https://github.com/lattera/glibc/blob/master/sysdeps/nptl/bits/pthreadtypes.h#L27)
- `typedef unsigned long int pthread_t`

So casting from `pthread_t` to `intptr_t` is okay.

But from my view this output is not correct (for just logging function).

```
static intptr_t gettid(void) { return (intptr_t)pthread_self(); }
printf("%7tu\n", gettid());
> 140434488452864
```

Instead of `pthread_self()` we might use:

```
#include <sys/syscall.h>
#include <unistd.h>
#include <stdlib.h>
#include <stdio.h>

static intptr_t gettid_syscall(void)
{
    return (intptr_t)syscall(SYS_gettid);
}
```

Because the ID generated by `pthread_self()` is reused by the threading implementation after the thread completion.

So the difference between `SYS_gettid()` and the `pthread_self()` is:
- POSIX thread IDs are assigned and maintained by the threading implementation. The thread ID returned by `gettid()` is a number (similar to a process ID) that is assigned by the kernel.
- ID generated by the `pthread_self()` can be used after the completion of the thread but  the ID genereated by the kernel can't be used even after the completion of the thread.
