### ISSUE TITLE
What does this assert mean?

### ISSUE THREAD

**Issue by dsafreno** [grpc/grpc#17767]
Maybe I'm just incompetent at Google'ing but I can't figure out what it means that I'm failing this assert...

It happens rarely, but crashes our application when it does happen. Basically, just creating a stub and then trying to call a stream method.

Assert:
https://github.com/grpc/grpc/blob/2cd1dcfd51a9d2b1a7d58bb20432ba4a0a69f992/src/cpp/client/channel_cc.cc#L159

Our usage:
```
ClientContext context;
context.AddMetadata(<X>, <Y>);
std::shared_ptr<SeDatastoreRpc::Stub> sub_stub = SeDatastoreRpc::NewStub(grpc_channel_);
std::shared_ptr<ClientReaderWriter<SeDatastoreSeVersion, SeDatastoreNotification> > stream(sub_stub->Subscribe(&context));
```

Our service:
```
service SeDatastoreRpc {
    rpc Subscribe(stream SeDatastoreSeVersion) returns (stream SeDatastoreNotification);
    ...
}
```

Does this mean a usage issue?

Let me know if there's anything else I can provide!

**Comment by yang-g** [comment]
If it is easy for you, you can print the return value of the `grpc_call_start_batch` call, which may give you a better idea.

Most of the issues I saw are related to API mis-use, for example you cannot do a stream `Write` before the previous `Write` is done, or similarly for `Read`. Since you are using metadata, it could also be that your metadata key contains illegal characters etc.

**Comment by AspirinSJL** [comment]
@dsafreno Feel free to reopen this issue if you have further question.
