### ISSUE TITLE
check_on_pr.py fails with KeyError: 'token'

### ISSUE THREAD

**Issue by rmstar** [grpc/grpc#18028]
```
Traceback (most recent call last):
  File "tools/profiling/ios_bin/binary_size.py", line 150, in <module>
    check_on_pr.check_on_pr('Binary Size', '```\n%s\n```' % text)
  File "tools/profiling/ios_bin/../../run_tests/python_utils/check_on_pr.py", line 116, in check_on_pr
    'summary': summary,
  File "tools/profiling/ios_bin/../../run_tests/python_utils/check_on_pr.py", line 67, in _call
    'Authorization': 'Bearer %s' % _access_token(),
  File "tools/profiling/ios_bin/../../run_tests/python_utils/check_on_pr.py", line 57, in _access_token
    'token': resp.json()['token'],
KeyError: 'token'
```
https://source.cloud.google.com/results/invocations/04352595-7beb-4d90-9393-719ccfc95f33/targets/grpc%2Fcore%2Fpull_request%2Fmacos%2Fgrpc_ios_binary_size/log

**Comment by rmstar** [comment]
CC @lidizheng

**Comment by gnossen** [comment]
I'm betting this was a transient error on Github's side. We should probably add a call to [`raise_for_status`](http://docs.python-requests.org/en/master/api/#requests.Response.raise_for_status) for a more descriptive error message.

**Comment by lidizheng** [comment]
@rmstar  Thank you for pointing out. I checked latest failures of `grpc/core/pull_request/macos/grpc_ios_binary_size`, and `check_on_pr` does introduce flakiness into the test.

https://source.cloud.google.com/results/invocations/04352595-7beb-4d90-9393-719ccfc95f33/targets/grpc%2Fcore%2Fpull_request%2Fmacos%2Fgrpc_ios_binary_size/log
https://source.cloud.google.com/results/invocations/89e0c5d4-fb5c-4408-974e-2600450565bc/targets/grpc%2Fcore%2Fpull_request%2Fmacos%2Fgrpc_ios_binary_size/log
https://source.cloud.google.com/results/invocations/6ca1d1e5-98cb-4586-ae9c-1ce6874e1940/log

It might due to Github API error as suggested by @gnossen. I think I will add a retry mechanism to make it more robust, also add more logging.
