### ISSUE TITLE
Maybe remove kokoro:force-run or kokoro:run?

### ISSUE THREAD

**Issue by AspirinSJL** [grpc/grpc#18026]
What's the difference of these two labels?

If they are the same, please move one of them.

**Comment by jtattermusch** [comment]
kokoro:run  runs the tests if they haven't run yet for given commit - this is useful for external pull requests as a signal that the PR code is safe run on our test infrastructure.

kokoro:force-run  forcibly re-runs the tests even if they have already run for given commit.

**Comment by AspirinSJL** [comment]
What bad can happen if we kokoro:force-run on an external PR to trigger the initial testing?

**Comment by jtattermusch** [comment]
It would work but I consider using the kokoro:force-run to be a bad practice that's only needed because our tests are not as stable as they should be.  In the ideal world one should never need to use kokoro:force-run - but currently we're relatively far from that state. Deflaking the tests and the test infrastructure should be our focus.

**Comment by AspirinSJL** [comment]
I see. Thanks for the explanation!
