### ISSUE TITLE
Python Protobuf deserialize creates a new type and because of this does not work isinstance

### ISSUE THREAD

**Issue by Valentin-Miroshnichenko** [grpc/grpc#18139]
I use Protobuf in my project. When I send data through the network and deserialize it. I got a new type **'google.protobuf.reflection.ActorPidRequest'** instead of **'protoactor.remote.protos_remote_pb2.ActorPidRequest'** and **isinstance** don’t work for me. How Can I Fix It?.

![2019-02-22_11-40-46](https://user-images.githubusercontent.com/10279529/53232877-1f099d80-369d-11e9-9610-c71182c8f8db.png)

**Comment by lidizheng** [comment]
Normally, if you use `grpcio-tools` to generate `*_pb2_grpc.py` file, the servicer method will be bound with the serialization and deserialization method of `*_pb2.py` file. It will work fine if you try to compare proto message that sent to the method or instantiated from the imported `*_pb2.py` file.

Your `type(msg2)` seems instantiated by the imported `*_pb2.py` , but `type(msg)` is constructed through reflection API. Unfortunately, the even with reflection ProtoBuf can not transmit accurate message type information.

It is a feature that ProtoBuf message only transmit content of message but no type information, which means same bytes can potentially be transformed into different message types. That's why the ProtoBuf message type is enforced in the gRPC layer, so you can be certain that a servicer method will always receive the specified type of ProtoBuf message.

Back to your case, there is no way to use `isinstance` for two message type that come from different module. Please consider using the content of the message in flow control, for example, if you would to identify different type of `Pid`, you can use add an enum field in `ActorPidRequest`.

If this doesn't solve your problem, please post more detail about your use case.

**Comment by zengzhengrong** [comment]
Do without changge the proto file , try to str(msg.__class__) == str(msgclass)
