### ISSUE TITLE
NuGet install grpc package issue

### ISSUE THREAD

**Issue by xyting** [grpc/grpc#1813]
Visual Studio 2013 Target Framework 4.5
PM> Install-Package grpc
The source at api.nuget.org [https://api.nuget.org/v3/index.json] is unreachable. Falling back to NuGet Local Cache at C:\Users\**\AppData\Local\NuGet\Cache
Attempting to resolve dependency 'Grpc.Core (≥ 0.5.0)'.
Attempting to resolve dependency 'Microsoft.Bcl.Immutable (≥ 1.0.34)'.
Attempting to resolve dependency 'Ix-Async (≥ 1.2.3)'.
Attempting to resolve dependency 'grpc.native.csharp_ext (≥ 0.9.0.0)'.
Attempting to resolve dependency 'grpc.dependencies.zlib.redist (≥ 1.2.8.9)'.
Attempting to resolve dependency 'grpc.dependencies.openssl.redist (≥ 1.0.2.2)'.
Install-Package : External packages cannot depend on packages that target projects.
At line:1 char:1
+ Install-Package grpc
+ ~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Install-Package], InvalidOperationException
    + FullyQualifiedErrorId : NuGetCmdletUnhandledException,NuGet.PowerShell.Commands.InstallPackageCommand

**Comment by jtattermusch** [comment]
Does this also happen when Nuget.org is reachable? 
"The source at api.nuget.org [https://api.nuget.org/v3/index.json] is unreachable" 

Did you start off of a empty project and just tried to add Grpc package dependency?

**Comment by jtattermusch** [comment]
I just tried that and ran into the same issue (it happens when you start with a fresh project, not for the helloworld or routeguide tutorials). Thanks for reporting this!

I think this is because the Grpc package contains only contains tools/ subdirectory and no specific files,  so it is considered "external", while it depends on Grpc.Core (which actually contains an assembly so it is a project specific package).

See also this issue:
http://nuget.codeplex.com/workitem/595

An immediate workaround it to install package "Grpc.Core" instead of "Grpc", that will work and it will give you exactly the same functionality.

In the meantime, I will work on a fix for this.

**Comment by jtattermusch** [comment]
I uploaded new version of Grpc package (0.5.0.1) that should be fixing this. Please try again and let me know.

**Comment by xyting** [comment]
@jtattermusch thanks
