### ISSUE TITLE
Significant latency regression in both unary and streaming benchmarks on 2/19

### ISSUE THREAD

**Issue by adelez** [grpc/grpc#18167]
https://performance-dot-grpc-testing.appspot.com/explore?dashboard=5685265389584384

On 2/19, there was a ~50% increase in unary benchmark and ~100% in streaming. Same regression didn't seem to occur to internal benchmarks.

@jtattermusch @nicolasnoble

**Comment by jtattermusch** [comment]
@mhaidrygoog

**Comment by jtattermusch** [comment]
![download](https://user-images.githubusercontent.com/9939684/53394935-efaaa780-39a0-11e9-9953-062080902d06.png)

**Comment by jtattermusch** [comment]
![frz8ed4gvsc](https://user-images.githubusercontent.com/9939684/53395005-179a0b00-39a1-11e9-8bea-bd45d137b0aa.png)

**Comment by hcaseyal** [comment]
Re internal regressions: on 2/19, we had a couple of regressions in internal benchmarks as well. It's unclear to me if they are related at all.

**Comment by mhaidrygoog** [comment]
I can't run custom queries to access the older data on the dashboard. The data from the current snapshot has been overwritten. @jtattermusch  Please provide access.

**Comment by mhaidrygoog** [comment]
@jtattermusch Thanks for the pointers with the dashboard, proceeding ahead

**Comment by mhaidrygoog** [comment]
I was able to edit the dashboard data to see the range of starting commit  ids where we start seeing the performance regression. I am going to setup a script to run the last few commits before that and see which commit exactly may have caused the issue
![dashboard-commits](https://user-images.githubusercontent.com/42048362/53443352-5d1a0080-39c0-11e9-9ee9-f79795d3cac6.png)
![dashboard-latencies](https://user-images.githubusercontent.com/42048362/53443353-5d1a0080-39c0-11e9-9e89-13139e3a5d08.png)

**Comment by mhaidrygoog** [comment]
I've run a couple of experiments that suggest that reason for this regression may be the environment the benchmarks are running on and not necessarily any PR within gRPC

The first observation was after modifying the dashboard query to display git the commit id in addition to the latency and display this as a table vs a graph. I saw that the benchmarks ran on the same commit for 3 consecutive days (Feb-17-Feb19) and the change in the performance numbers all occurred on the same commit.

![dashboard-commit-latency-1](https://user-images.githubusercontent.com/42048362/53529442-72b32700-3aa1-11e9-98bf-9c1c5d0f6edf.png)
![dashboard-commit-latency-2](https://user-images.githubusercontent.com/42048362/53529440-7050cd00-3aa1-11e9-9374-9ec215a24b17.png)
![dashboard-commit-latency-3](https://user-images.githubusercontent.com/42048362/53529437-6e870980-3aa1-11e9-851b-dbba9f33938d.png)

The second experiment was to run unary and streaming scenarios in a separate GCE setup on the las 20 commits before the commit I identified above and see if there is a performance regression because of any particular commit. My analysis didn't pinpoint any particular commit.

**Comment by mhaidrygoog** [comment]
The regression is also noticeable for other languages in the multi-language dashboard
![multilamg-dashboard](https://user-images.githubusercontent.com/42048362/53657459-0e13db80-3c0b-11e9-9686-62f32a019601.png)

[link](https://performance-dot-grpc-testing.appspot.com/explore?dashboard=5652536396611584&widget=1274284569&container=695104531)

**Comment by mhaidrygoog** [comment]
Based on the analysis up till now I'm ruling out gRPC C++ as the root cause and downgrading this bug to P1
