### ISSUE TITLE
MacOS make test: segmentation fault at resolve_address_using_ares_resolver_posix_test

### ISSUE THREAD

**Issue by sab24** [grpc/grpc#18334]
### What version of gRPC and what language are you using?
 1.19.1
 
### What operating system (Linux, Windows,...) and version?
 MacOs 10.14.3
 
### What runtime / compiler are you using (e.g. python version or version of gcc)
 clang version is 
Apple LLVM version 10.0.0 (clang-1000.11.45.5)
Target: x86_64-apple-darwin18.2.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin

 
### What did you do?
If possible, provide a recipe for reproducing the error. Try being specific and include code snippets if helpful.
CC=/usr/local/cellar/llvm/7.0.1/bin/clang CCX=/usr/local/cellar/llvm/7.0.1/bin/clang++ make
CC=/usr/local/cellar/llvm/7.0.1/bin/clang CCX=/usr/local/cellar/llvm/7.0.1/bin/clang++ make test
 
### What did you expect to see?
Succeeded tests
 
### What did you see instead?
 segfault

Make sure you include information that can help us debug (full error message, exception listing, stack trace, logs).

See [TROUBLESHOOTING.md](https://github.com/grpc/grpc/blob/master/TROUBLESHOOTING.md) for how to diagnose problems better.
 
### Anything else we should know about your project / environment?

/bin/sh: line 1: 60757 Segmentation fault: 11  /Users/user/Downloads/grpc/bins/opt/resolve_address_using_ares_resolver_posix_test
test resolve_address_using_ares_resolver_posix_test failed
make: *** [test_c] Error 1

LLDB shows
Process 61049 resuming
Process 61049 stopped
* thread #1, queue = 'com.apple.main-thread', stop reason = EXC_BAD_ACCESS (code=1, address=0x0)
    frame #0: 0x000000010009ea60 resolve_address_using_ares_resolver_posix_test`gpr_stricmp(a=0x0000000000000000, b="native") at string.cc:288 [opt]
   285 	int gpr_stricmp(const char* a, const char* b) {
   286 	  int ca, cb;
   287 	  do {
-> 288 	    ca = tolower(*a);
   289 	    cb = tolower(*b);
   290 	    ++a;
   291 	    ++b;
Target 0: (resolve_address_using_ares_resolver_posix_test) stopped.

clang version is 
Apple LLVM version 10.0.0 (clang-1000.11.45.5)
Target: x86_64-apple-darwin18.2.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin

Same error with clang version:
clang version 7.0.1 (tags/RELEASE_701/final)
Target: x86_64-apple-darwin18.2.0
Thread model: posix
InstalledDir: /usr/local/Cellar/llvm/7.0.1/bin

Same error with gcc:
gcc-8 (Homebrew GCC 8.3.0) 8.3.0
Copyright (C) 2018 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

**Comment by apolcyn** [comment]
Seeing that you invoked this test using `make test`, it looks like the problem is just that (the Makefile invokes that test with a simple `$(BINDIR)/$(CONFIG)/resolve_address_using_ares_resolver_test`, which is incorrect).

That test requires a flag to be passed to it: `--resolver=<ares|native>`, and it will definitely crash if that flag is not provided.

Note that our CI test system doesn't actually use `make test` to run tests - it uses the `run_tests.py` test script and `bazel` to run tests, and these test systems are configured to pass the `--resolver=<ares|native>` flag to the test correctly.

However, it is interesting that we have a `make test` target at all. cc @nicolasnoble - it seems that the `test` Makefile target is unused and also won't work, does it make sense to delete it?

**Comment by sab24** [comment]
Running tests is done by 

./tools/run_tests/run_tests.py -l c -c dbg

Couldn't find this being documented, so adding this for future viewers. 

Does it make sense to let make test run this command?

**Comment by apolcyn** [comment]
There's some documentation on the `run_tests.py` script, but you do have to know where to find it - https://github.com/grpc/grpc/blob/master/tools/run_tests/README.md

I'm not sure it makes sense to adapt the `make test` target, since there's other ways of running the tests that we naturally spend effort maintaining for our pull request tests, etc.
