### ISSUE TITLE
Invoking grpc_ssl_credential_create with nonnull pem_root_certs causes large memory consumption

### ISSUE THREAD

**Issue by muxi** [grpc/grpc#18335]
When using `grpc_ssl_credential_create` function, if `pem_root_certs` parameter is provided, huge memory consumption was reported during a call (~10MB extra memory space was consumed for a ~272KB string provided).

**Comment by muxi** [comment]
According to offline discussions related to #18336, when `pem_root_certs` is provided, the certificates are not cached in core. Likely certificate cache related.

**Comment by jiangtaoli2016** [comment]
This issue is somewhat misleading. Let me explain how root certificate works in gRPC. 

If `grpc_ssl_credential_create` has `pem_root_certs = nullptr` as input, the default root certificates will be used. gRPC not only cache the root certificate string, but also cached the root certificate in `X509_STORE` if using BoringSSL or OpenSSL 1.1+.

If user decides to pass his or her own `pem_root_certs`, then gRPC could not use the default cached `X509_STORE`. Instead, gRPC will create `X509_STORE` from the user inputted `pem_root_certs` and used it in `SSL_CTX` of each sub-channel.

For example, if user provided `pem_root_certs` is about 270KB, then `X509_STORE` would be ~1MB. If gRPC creates 10 sub-channels in parallel, then ~10MB will be created.

**Comment by jiangtaoli2016** [comment]
I would says it is intended behavior for now. One possible way to improve is if user provides his/her own pem_root_certs, gRPC tries to create one copy of X509_STORE and share between all sub-channels. It is quite hard to do based on the current security API in gRPC.

**Comment by muxi** [comment]
Ah that makes much more sense! Thanks for explaining it. In that case I agree it's intended behavior.

**Comment by gnossen** [comment]
@muxi Sounds like this issue is resolved. Closing for now. Please feel free to reopen if anything else comes up.

**Comment by muxi** [comment]
@gnossen thanks but there's still some enhancement that could be done. Let's keep it open to keep track of it.
