### ISSUE TITLE
Support C++ access to JSON fields of JSON key

### ISSUE THREAD

**Issue by Capstan** [grpc/grpc#18433]
In some cases, a client needs to know the principal they are acting as for other business logic (e.g., calling [`google.iam.credentials.v1.IAMCredentials.GetGoogleIdToken`](https://cloud.google.com/iam/credentials/reference/rest/v1/projects.serviceAccounts/generateIdToken)). For JSON keys, this is in the `client_email` field.  However, if you use [`grpc::ServiceAccountJWTAccessCredentials`](https://grpc.io/grpc/cpp/namespacegrpc.html#a92a9f959d6102461f66ee973d8e9d3aa) with the JSON key, you're stuck with an opaque `CallCredentials` and have to re-parse the JSON yourself with a separate JSON library to retrieve the `client_email` field.

Is it reasonable to promote the JSON token to be a public C++ object s.t. `grpc::ServiceAccountJWTAccessCredentials` has an overload that takes the token class, but also allows the client to retrieve fields out of it?

**Comment by nicolasnoble** [comment]
We've never intended the internal json parser to be a public utility, for many different reasons, which is why its API doesn't surface.

**Comment by nicolasnoble** [comment]
@vjpai: what's your sentiment here?

**Comment by markdroth** [comment]
FWIW, I'm of two minds about this.  On one hand, I am not at all enthusiastic about the idea of adding a JSON API to the gRPC library, since this would be a whole API surface that we'd need to expose and maintain.  But on the other hand, we may need to do something like this for the LB policy API anyway, since we need to provide a way for LB policy implementations to parse the JSON from the service config.

So, I see a few possible options here:

1. Bite the bullet and provide a JSON API as part of the C++ gRPC API.  (This is my least favorite option.)
2. Provide a JSON API as part of the LB policy API but not the public gRPC API.  The difference may be important, because we may want to offer different API guarantees for the two APIs.
3. Find some third party OSS JSON library (or maybe open-source some existing code we have internally) and take a dependency on it.  It could then be used in both the LB policy code and in the public API.  This has the advantage that we're not supporting this as part of the gRPC API directly, but it has the disadvantage that we'd need another external dependency.  And this may not be feasible if the external JSON library requires a link-time dependency on the C++ standard library, because we can't tolerate that in core.
4. Punt on the broader issue of exposing a JSON API and instead provide a way for the JWT credentials to expose the underlying JSON as a string.  It then becomes the application's problem to figure out how to parse it themselves.

From a tactical perspective, option 4 is probably the easiest.  But we might want to give some thought to whether we could make the other options work.

Also, we should get input from @jiangtaoli2016 on this.

**Comment by jiangtaoli2016** [comment]
+1 on option 4 and let application parse it.

**Comment by nicolasnoble** [comment]
There's technically option 5 where, in the upper C++ layers, we call into our own json decoder, and expose a readonly `std::map<std::string, std::string>` object which loosely represents the contents of the jwt object that we decode ourselves. A `map<string, string>` doesn't fully map json, but it maps jwt. This wouldn't be us exposing json, but jwt.

**Comment by yang-g** [comment]
Isn't the json_key passed by the application? Could the application parse the client_email field and keep that around along with the credentials object?

**Comment by sanjaypujare** [comment]
The `map<string, string>` solution is not future proof. If JWT has nested JSON structures the `map` won't work, right?

**Comment by nicolasnoble** [comment]
Does it? I didn't think so, but I'm not an expert on the structure of JWT. I was under the impression it actually didn't have nested information.

**Comment by yang-g** [comment]
I believe Nathan is talking about the client_email in the service account key, not the generated jwt token.

**Comment by sanjaypujare** [comment]
@nicolasnoble that's why I said "future proof" - so if JWT (in future) contains a nested JSON structure,  the `map<string, string>` won't work.

**Comment by nicolasnoble** [comment]
Oh, right, I see what you're saying now. Yeah, that's true.

**Comment by Capstan** [comment]
For comparison:
* [Go gRPC](https://godoc.org/google.golang.org/grpc/credentials/oauth#NewServiceAccountFromFile) has the same model (input JSON string, output opaque [`PerRPCCredentials`](https://godoc.org/google.golang.org/grpc/credentials#PerRPCCredentials)). Its predecessor [HTTP/JSON discovery-based clients](https://github.com/googleapis/google-api-go-client) use [oauth2/jwt.Config](https://godoc.org/golang.org/x/oauth2/jwt#Config) which exposes fields on the JWT.
* [Java gRPC](https://grpc.io/grpc-java/javadoc/io/grpc/auth/MoreCallCredentials.html#from-com.google.auth.Credentials-) allows conversion from `com.google.auth.Credentials` whose child [`ServiceAccountCredentials`](http://googleapis.github.io/google-auth-library-java/releases/0.9.1/apidocs/com/google/auth/oauth2/ServiceAccountCredentials.html) allows retrieving fields off the JWT.

So perhaps it's unreasonable to export a generic JSON or JWT surface, especially as a competitor to perhaps other libraries in this space, given the additional maintenance burden, etc., but it seems reasonable, if there's a common OAuth2 JWT library that exists for C++, to provide overloads that take creds from that. Maybe the [older Google API client OAuth2](https://github.com/google/google-api-cpp-client/blob/master/src/googleapis/client/auth/oauth2_service_authorization.h) isn't suitable, but perhaps there is an alternative? FTR, that last reference uses [open-source-parsers/jsoncpp](https://github.com/open-source-parsers/jsoncpp/) under the covers.

As it stands now, I can certainly use such a library and work around (see option 4), but it seems like both C++ and Go could take a page from Java here.

**Comment by Capstan** [comment]
Hm, I stand corrected on Go: You can use [`oauth2.TokenSource`](https://godoc.org/golang.org/x/oauth2#TokenSource) to build [grpc's oauth.TokenSource](https://godoc.org/google.golang.org/grpc/credentials/oauth#TokenSource) to get a `PerRPCCredentials` in lieu of the native [`NewServiceAccountFromFile`](https://godoc.org/google.golang.org/grpc/credentials/oauth#NewServiceAccountFromFile).
