### ISSUE TITLE
CPP example error

### ISSUE THREAD

**Issue by fanwz** [grpc/grpc#18453]
### What version of gRPC and what language are you using?
 C++
 
### What operating system (Linux, Windows,...) and version?
 Centos 7
 
### What runtime / compiler are you using (e.g. python version or version of gcc)
 gcc 4.8.5

I have installed the grpc in my system with the source code downloading from github.
I want to test the example,when I use "make " to complie the sample in the "example/cpp" dir,the error show below.

> make: *** [greeter_async_client] Error 1
> /usr/local/lib/libgrpc.so: undefined reference to `ares_strsplit'
> /usr/local/lib/libgrpc.so: undefined reference to `ares_strsplit_free'
> collect2: error: ld returned 1 exit status

**Comment by apolcyn** [comment]
The upstream c-ares library only created the `ares_strsplit`/`ares_strsplit_free` functions and started using them since https://github.com/c-ares/c-ares/pull/211, which is only in the latest c-ares releases.

gRPC still depends on an old version of the c-ares in the git submodule, for which those functions aren't used at all, so I'm not exactly sure how this is happening.

Does a `git submodule update` from the grpc git repo make a difference?

**Comment by fanwz** [comment]
> The upstream c-ares library only created the `ares_strsplit`/`ares_strsplit_free` functions and started using them since [c-ares/c-ares#211](https://github.com/c-ares/c-ares/pull/211), which is only in the latest c-ares releases.
> 
> gRPC still depends on an old version of the c-ares in the git submodule, for which those functions aren't used at all, so I'm not exactly sure how this is happening.
> 
> Does a `git submodule update` from the grpc git repo make a difference?

I have tried this, it is OK. 
but I think it do not use thle  "latest c-ares releases.". the first I complie source code by copy the lastest c-ares source to the thirdparty/cares/ by myself,and generate this issus.
I check the submodule, the grpc project use the branch is "cares-1_12_0".
So I think may be this problem.
Thank you!

**Comment by apolcyn** [comment]
We do plan to upgrade our c-ares dependency to get upstream bug fixes. However, upgrading to a new submodule version tends to require some manual changes, and it also comes with a risk of regression, which is why we have the submodule pinned at a specific version.

Thanks for the update though, this seems to be WAI
