### ISSUE TITLE
Expose AuthMetadataProcessor to Python?

### ISSUE THREAD

**Issue by lihalite** [grpc/grpc#18459]
### What version of gRPC and what language are you using?
gRPC 1.18.0, Python
 
### What operating system (Linux, Windows,...) and version?
Linux
 
### What runtime / compiler are you using (e.g. python version or version of gcc)
Python 3.6
 
### What did you do?

We'd like to implement a custom authentication method in Python. While we can implement `AuthMetadataPlugin` on the client side, there is not a convenient API on the server side. gRPC C++/Core have `AuthMetadataProcessor`, but this is not exposed to gRPC.

Also see https://github.com/grpc/proposal/pull/101. 
 
### What did you expect to see?

Either a well-supported way to pass data from an interceptor to an RPC method handler, or a way to hook into [`ServicerContext.peer_identities`](https://grpc.io/grpc/python/grpc.html#grpc.ServicerContext.peer_identities) such as via [`AuthMetadataProcessor`](https://grpc.io/grpc/cpp/classgrpc_1_1_auth_metadata_processor.html) (presumably).
 
### What did you see instead?

We instead created an interceptor, but there is not an obvious way to pass data from an interceptor to the RPC handler. It could be done in a decorator instead, but then it is easy to forget to annotate methods (which should be secure-by-default). Alternatively, the interceptor can wrap the `RpcMethodHandler` and then wrap `ServicerContext`, but this is a lot of boilerplate.

**Comment by gnossen** [comment]
This use case is currently difficult out of the box. It has been called out in the past as a [potential application of full-featured server-side interceptors](https://github.com/grpc/grpc/issues/18191), which are unfortunately not yet available in gRPC Python.

As you mentioned, decorators can be used to supply data to the application handlers. In order to solve the secure-by-default problem, you could try a metaclass to decorate the methods automatically.

**Comment by lihalite** [comment]
Thanks for the follow up! I do see the difficulties in the full-featured server interceptor API, and I have wished for the same level of control as in Java. For us, wrapping ServicerContext is an OK solution, as then it doesn't require modifying servicer code (whether with decorators or with a metaclass).

Is there a reason why the processor API won't or can't be supported, though? To me, it feels odd to treat in-tree auth implementations (using ServerCredentials) differently than out-of-tree ones (using a hypothetical interceptor). I suppose Java has the same asymmetry, but it seems C-core and C++ don't.

If it's mostly an implementation effort issue, we have been interested in contributing upstream to unblock these use cases for us.

**Comment by gnossen** [comment]
PRs are always welcome! Thank you for volunteering. :smile:

After a little more thought, barring your concern about different auth configurations for different handler methods, is there any reason that the [`ServerCredentials`](https://github.com/grpc/grpc/blob/af283b3183eca452733e5eb7ac767cb17242199d/src/python/grpcio/grpc/__init__.py#L634) interface doesn't meet your needs? It seems like if you implement that and subclass [`grpc_server_credentials`](https://github.com/grpc/grpc/blob/af283b3183eca452733e5eb7ac767cb17242199d/src/core/lib/security/credentials/credentials.h#L215), you should have a full python implementation.

Am I missing some of the complexity here?

**Comment by lihalite** [comment]
Yes, ServerCredentials is exactly the interface we'd like to use! But there's no way to implement it within Python, as it's an opaque wrapper for a C struct. If we bind [auth_metadata_processor](https://grpc.io/grpc/core/structgrpc__auth__metadata__processor.html), that would give an extension point that automatically exposes the right data in ServicerContext. I think the main complexity is in calling back into Python from the C callback.

**Comment by gnossen** [comment]
I think this is possible using the `ServerCredentials` interface. Here's an implementation sketch.

 - Implement GSSAPI Support in Core
    - Subclass [`grpc_server_credentials`](https://github.com/grpc/grpc/blob/af283b3183eca452733e5eb7ac767cb17242199d/src/core/lib/security/credentials/credentials.h#L215) just like [ALTS](https://github.com/grpc/grpc/blob/af283b3183eca452733e5eb7ac767cb17242199d/src/core/lib/security/credentials/alts/alts_credentials.h#L52) and [SSL](https://github.com/grpc/grpc/blob/af283b3183eca452733e5eb7ac767cb17242199d/src/core/lib/security/credentials/ssl/ssl_credentials.h#L60) have done.
   - Write a [factory function](https://github.com/grpc/grpc/blob/af283b3183eca452733e5eb7ac767cb17242199d/src/core/lib/security/credentials/ssl/ssl_credentials.cc#L311) for your new type returning `grpc_server_credentials*`
   - Add the factory function to `include/grpc/grpc_security.h` like [`grpc_ssl_server_create_with_options`](https://github.com/grpc/grpc/blob/af283b3183eca452733e5eb7ac767cb17242199d/include/grpc/grpc_security.h#L476). This will add GSSAPI support to the core surface API, making it available to all wrapped languages, including Python.
- Implement GSSAPI Support in Cython
  - Pull the new core functions into the cython layer by [adding their signatures to `src/python/grpcio/grpc/_cython/_cygrpc/grpc.pxi`](https://github.com/grpc/grpc/blob/af283b3183eca452733e5eb7ac767cb17242199d/src/python/grpcio/grpc/_cython/_cygrpc/grpc.pxi#L458)
   - [Wrap the new core functions with Cython](https://github.com/grpc/grpc/blob/af283b3183eca452733e5eb7ac767cb17242199d/src/python/grpcio/grpc/_cython/_cygrpc/credentials.pyx.pxi#L233), resulting in a Python interface.
- Implement GSSAPI Support in Python
   - Add a GSSAPI [factory function returning an instance of `ServerCredentials` to the `grpcio` public API](https://github.com/grpc/grpc/blob/af283b3183eca452733e5eb7ac767cb17242199d/src/python/grpcio/grpc/__init__.py#L1579)

I'm still not clear on what exactly you need access to from inside of the service handler. Could you provide a code snippet of what you think a service handler integrating with GSSAPI might look like? If the issue is just calling back into python from core, you can probably solve that with a thread hop.

**Comment by lihalite** [comment]
Sorry, I think I'm mixing up two things here!

For GSSAPI specifically, I'm waiting on the proposal…I'm glad to hear that implementation should be relatively straightforward, though.

However, that proposal has been waiting for a few months now, so I'm exploring an alternate mechanism - namely, the AuthMetadataProcessor API, which would allow us to implement GSSAPI (or any other auth mechanism) without explicit gRPC support for it. This would also let us implement something that exposes the ServerCredentials interface in pure Python. The corresponding client side API, AuthMetadataPlugin, is already exposed in gRPC/Python. So I'm wondering if there's interest in also exposing AuthMetadataProcessor to gRPC/Python.

The reason why I'd like to do this over using ServerInterceptor is to expose a uniform API to servicer implementations - namely, that in Python, they should still be able to access the authenticated user identity via the ServicerContext. This is possible with ServerInterceptor, but requires some boilerplate, plus I'm not sure if it will remain compatible with future versions of gRPC. (Namely: the interceptor creates its own call handler that wraps the given ServicerContext in another object, overriding the peer_identity method and others, then calls the original handler.)

**Comment by lihalite** [comment]
Hi @gnossen, just to follow up; does my previous comment make sense? Essentially, I'd like to bind [`auth_metadata_processor`](https://grpc.github.io/grpc/core/structgrpc__auth__metadata__processor.html) to Python so that we can implement auth mechanisms in Python, rather than in Core, but still have it look and feel like the other mechanisms in Core (which hook into [`peer_identities()`](https://grpc.github.io/grpc/python/grpc.html#grpc.ServicerContext.peer_identities))
