### ISSUE TITLE
What the purpose of ThreadPoolExecutor in Python gRPC server?

### ISSUE THREAD

**Issue by yutkin** [grpc/grpc#18535]
When we instantiate gRPC server we pass `ThreadPoolExecutor` to its constructor:

```
grpc.server(futures.ThreadPoolExecutor(max_workers=1))
```

As I know, Python has GIL that makes useless usage of threads for CPU-bound tasks.

For example, my gRPC server serves Tensorflow model and gRPC health checking service. Are there any benefits for me to increase the number of threads in thread pool?

**Comment by lidizheng** [comment]
@yutkin In modern server architecture, usually the bottleneck will more likely be database, network bandwidth. In those scenario, increasing threads number in Python works because when one thread is blocked by IO, another thread can continue its execution.

For CPU-bound tasks, your statement is correct. The GIL makes multi-threading in Python useless. If you want Python utilize all of your cores, you may want to spawn multiple processes (one example [here](https://github.com/grpc/grpc/tree/master/examples/python/multiprocessing)). I don't have much detail about your case, if your TensorFlow model does not depend on certain server state, I will recommend use subprocess to invoke another Python interpreter to perform the computation and send the response back.

**Comment by yutkin** [comment]
@lidizheng Thank you for your answer! I'm not trying to speed up my service using threads (of course, threads won't speed up model inference). I just want to figure out how this thread pool is used inside gRPC. 

For example, If I set `max_workers=1`, will health-check servicer block while another servicer is running?

**Comment by lidizheng** [comment]
@yutkin gRPC Python server currently will package each RPC request as a future, and submit it to the thread pool. If the thread pool runs out of available thread, it will spawn a new one and process the future. In another word, each RPC will run in a dedicated thread, and if the RPC is blocked the thread will be blocked as well.

Back to your example, if you set `max_workers=1` and you are using the [Watch](https://github.com/grpc/grpc/blob/master/src/proto/grpc/health/v1/health.proto#L62) Health-Check method, you will end up deadlocking. The `max_workers=1` will only work, if your method handlers will end soon and only use [Check](https://github.com/grpc/grpc/blob/master/src/proto/grpc/health/v1/health.proto#L45) Health-Check method.

**Comment by lidizheng** [comment]
I'm closing this issue. If you have more questions, feel free to open it again.
