### ISSUE TITLE
React to breaking changes in System.Interactive.Async

### ISSUE THREAD

**Issue by JamesNK** [grpc/grpc#18592]
`System.Interactive.Async` 4.0 preview removes its copy of `System.Collections.Generic.IAsyncEnumerator<T>`.

https://www.nuget.org/packages/System.Interactive.Async/4.0.0-preview.1.build.745

`Grpc.Core.Api` will need to react to this or will be broken by anyone who uses `System.Interactive.Async` 4.0 preview or later.

**Comment by jtattermusch** [comment]
How exactly should we react in order not to break the API compatibility?
https://github.com/grpc/grpc/blob/906c12568e9bdf1d8306a2f2ab45efe8beb43f74/src/csharp/Grpc.Core.Api/IAsyncStreamReader.cs#L53

**Comment by JamesNK** [comment]
Anyone referencing `IAsyncEnumerator<T>`, or APIs that use that type will be broken.

Moving the `IAsyncEnumerator<T>` methods to `IAsyncStreamReader<T>` might keep existing code that references the reader working, but I'm not sure.

**Comment by JamesNK** [comment]
> Moving the IAsyncEnumerator<T> methods to IAsyncStreamReader<T> might keep existing code that references the reader working, but I'm not sure.

I tested out what happens and unfortunately the IL references the members on the base interface (in our case, `IAsyncEnumerator<T>.MoveNext(CancellationToken)`). Moving MoveNext and Current from the third-party assembly to `IAsyncStreamReader<T>` will be a breaking change. There is nothing you can do.

![image](https://user-images.githubusercontent.com/303201/57592369-7166a600-758a-11e9-9344-93bd4793fd98.png)

Keeping the status quo will not work either. Referencing a newer version of `System.Interactive.Async` will break gRPC because the type is not present.

Additionally, any code that has an `IAsyncEnumerable<T>` will get errors if they are in .NET Core 3 and they have a reference to Grpc.Core.Api. `IAsyncEnumerable<T>` will exist in multiple assemblies with the same name and namespace. The compiler will not know which version to use. The only fix is to setup an extern alias which is not easy to figure out by yourself.

**Comment by veblush** [comment]
How about having two gRPC .net dll as a solution?

gRPC nuget package :=
  - for .NETFramework 4.6.1, .NETStandard 2.0
    - srcs: use old [IAsyncEnumerator](https://github.com/dotnet/corefx/blob/master/src/Common/src/CoreLib/System/Collections/Generic/IAsyncEnumerator.cs) as is
    - deps: System.Interactive.Async = 3.2
  - for .NETCoreApp 3.0. .NETStandard 2.1
     - srcs: use new [IAsyncEnumerator](https://github.com/dotnet/reactive/blob/rel/v3.2/Ix.NET/Source/System.Interactive.Async/IAsyncEnumerator.cs
)
     - deps: System.Interactive.Async >= 4.0

At lease, we can provide binary compatibility for the existing users who are satisfied with pre C# 8 and pre .NET Core 3. New users who want to use C# Core 3 will face a sort-of breaking changes in API but it doesn't matter because they already changed the target framework.

This may not address the case where C# 8 and pre-.NET Core 3 are used. C# 8 may require System.Interactive.Async >= 4.0 in this case but we can forward them to the breaking changes that System.Interactive.Async made. :)

**Comment by jtattermusch** [comment]
https://github.com/grpc/grpc/pull/19400
