### ISSUE TITLE
C# Support for null response messages

### ISSUE THREAD

**Issue by szehetner** [grpc/grpc#18654]
### What version of gRPC and what language are you using?
1.19.1, C# 
 
### What operating system (Linux, Windows,...) and version?
Windows 10 
 
### What runtime / compiler are you using (e.g. python version or version of gcc)
.NET Framework 4.7.2
 
### What did you do?
We recently tried to upgrade form 1.16.0 to 1.19.1, but encountered a new error.
We use a custom serializer (based on protobuf-net instead of Google.ProtoBuf), which can produce null byte arrays as response messages. Returning a null as the serialized byte[] worked in 1.16.0, but in 1.17.0+ it throws the following exception on the client side: 
`Status(StatusCode=Internal, Detail="Failed to deserialize response message.")`

The actual (unfortunately swallowed) inner exception is thrown here:
https://github.com/grpc/grpc/blob/5344c81f3c7701a6b1864faa2da91041c1e29e03/src/csharp/Grpc.Core/Internal/DefaultDeserializationContext.cs#L49
This check was introduced with https://github.com/grpc/grpc/pull/17167/commits/5344c81f3c7701a6b1864faa2da91041c1e29e03
 
### What did you expect to see?

I understand that supporting a null byte[] as response is probably not a design goal as the default tooling with Google.ProtoBuf does not allow it anyway, but would it be possible to support this in the SerializationContext?

I have also considered a workaround, namely sending an empty byte[] and setting a flag in the response trailers, something like "IsResponseNull". This would then allow the client to distinguish between null and an empty byte[]. Unfortunately this only works for async calls, not for sync calls (which we also need). This is because the response trailers are only available via the AsyncCall class and this is only returned for the async methods in CallInvoker, but not for CallInvoker.BlockingUnaryCall (which returns just the response).https://github.com/grpc/grpc/blob/af283b3183eca452733e5eb7ac767cb17242199d/src/csharp/Grpc.Core/CallInvoker.cs#L33
Is there another way to get the response trailers for successful sync calls? Or would it be possible to add a variant of BlockingUnaryCall that returns an AsyncUnaryCall (or something similar, that particular name combination would be a bit strange)?

**Comment by jtattermusch** [comment]
Returning null as a response message was always meant to me illegal, we just started enforcing that more strictly. The problem with null messages is that grpc as a protocol actually doesn't support them. 
It is of course possible to send a zero-length message, which translates to a byte buffer of length zero, but a "null" message is illegal (see https://github.com/grpc/grpc/blob/master/doc/PROTOCOL-HTTP2.md). It seems like it's something that just happened to work in your case, but it's not a supported use case, so I'd strongly recommend to stop trying to use "null" payloads (
and use "empty" messages that serialize to a zero-length byte array instead). 

The workaround you're suggesting seems fragile - if you really need to support null responses, why don't you just wrap the response in another layer of protobuf message that allows a nested message to be null, but will never be null itself?

```
message NullableResponse
{
    MyResponse myResponse = 1;
}
```

Btw, because of the way the proto binary format works, if myResponse = null, the message will still serialize as an empty byte array (= you won't waste any bandwidth).
