### ISSUE TITLE
1.20.0.pre3 can't connect to server behind ELB (ALPN check)

### ISSUE THREAD

**Issue by mdehoog** [grpc/grpc#18710]
### What version of gRPC and what language are you using?
1.20.0.pre3, Ruby.
 
### What operating system (Linux, Windows,...) and version?
Mac OS X 10.14
 
### What runtime / compiler are you using (e.g. python version or version of gcc)
Ruby 2.5.3
 
### What did you do?
Upgraded from 1.19 or 1.20.0.pre2 to 1.20.0.pre3.
 
### What did you expect to see?
Connection success.
 
### What did you see instead?
Connection failure. Debug logs:
```
D, [2019-04-10T06:54:54.472008 #9217] DEBUG -- : Failing with status #<struct Struct::Status code=14, details="Connect Failed", metadata={}>
```

#18563 re-enabled ALPN checks, which is causing our Ruby clients (and other implementations that use the C core stack) to experience connection failures to a gRPC server running behind an AWS ELB. This is not an issue with Go clients. Related: #9991.
 
Something like #18666 would allow us to opt-in to this behavior. Currently we need to run an Envoy proxy locally on the client to get around this, which is not ideal.

### Anything else we should know about your project / environment?

Stacktrace:
```
GRPC::Unavailable: 14:Connect Failed
  ~/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/grpc-1.20.0.pre3/src/ruby/lib/grpc/generic/active_call.rb:31:in `check_status'
  ~/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/grpc-1.20.0.pre3/src/ruby/lib/grpc/generic/active_call.rb:181:in `attach_status_results_and_complete_call'
  ~/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/grpc-1.20.0.pre3/src/ruby/lib/grpc/generic/active_call.rb:377:in `request_response'
  ~/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/grpc-1.20.0.pre3/src/ruby/lib/grpc/generic/client_stub.rb:178:in `block in request_response'
  ~/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/grpc-1.20.0.pre3/src/ruby/lib/grpc/generic/interceptors.rb:170:in `intercept!'
  ~/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/grpc-1.20.0.pre3/src/ruby/lib/grpc/generic/client_stub.rb:177:in `request_response'
  ~/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/grpc-1.20.0.pre3/src/ruby/lib/grpc/generic/service.rb:170:in `block (3 levels) in rpc_stub_class'
  app/client.rb:24:in `main'
  app/client.rb:116:in `<top (required)>'
```

**Comment by Hardtack** [comment]
Same as Python 1.20.0rc3, Python 3.6, docker `python:3.6-stretch`

**Comment by Ten0** [comment]
Same issue here.
It would be useful for many proxy configurations to have an option that disables enforcing ALPN.

**Comment by yihuazhang** [comment]
@dfawley @ejona86 @jiangtaoli2016 @markdroth  

gRPC java has a similar feature request: https://github.com/grpc/grpc-java/issues/5543. 

If we decide to support the feature - allowing users to configure whether or not to perform ALPN check, I think we should make the behavior consistent across different languages (C core, Java, Go, and wrapped languages).

**Comment by lidizheng** [comment]
Apologies @mdehoog @Hardtack @Ten0. We are sorry that you are depending on this buggy behavior. The ALPN is in the spec of HTTP2. We thought we have enforced it always. However, during a refactor of v1.17.0, the ALPN check was lost in C-Core. In the long term, we hope we can do the correct thing which is enforcing the ALPN check.

About the load balancer side, it will fail if your application is using the TLS termination feature of AWS ELB, which doesn't have ALPN support. The solution will be migrating to:

1. Don't use TLS termination in your server architecture.
2. Use TLS connection between your load balancer and your backend.
3. (Come use Google Cloud Platform.)

| Protocol Type: Client->LB, LB->Backend | TLS Termination ON | TLS Termination OFF |
|---|---|---|
|plain text, plain text |  :white_check_mark:|:white_check_mark:|
| TLS, plain test |:x:|:white_check_mark:|
| TLS, TLS |:white_check_mark:|:white_check_mark:|

We are here to help you to migrate. Potentially, we are able provide some workaround in the short term. To better understand what you need, can you please tell us more about the impact of this bug, like is it in production, what's current QPS, what's the use case, is it possible to migrate, how long will it need?

PS. Thanks to @ejona86 for providing details.

Related issues across three implementations:
* Golang https://github.com/grpc/grpc-go/issues/2742
* Java https://github.com/grpc/grpc-java/issues/5543
* C/Wrapper Languages https://github.com/grpc/grpc/issues/9991 https://github.com/grpc/grpc/pull/18587 https://github.com/grpc/grpc/issues/18549

**Comment by Ten0** [comment]
The *Application-Layer Protocol Negotiation* check is indeed marked as mandatory in HTTP/2 ([RFC 7540 - 3.4](https://tools.ietf.org/html/rfc7540#section-3.4)).

It is also explained why : in order to prevent cross-protocol attacks. ([RFC 7540 - 10.2](https://tools.ietf.org/html/rfc7540#section-10.2))
However I strongly beleive that for *at least* some people (including us) the cost **and risk** of setting up our own certificate management infrastructure and securing the certificates/signing/private keys/etc within our applications is **much higher** than that of cross-protocol attacks in a grpc client[1], that is, some attacker managing to have a grpc client connect *securely* to a non-http2 server, and the request "to *appear as a valid transaction* in the second protocol", leading it to unwanted behaviour.[2]

I hence beleive that being able to disable ALPN at runtime by passing the non-enforcing of ALPN as an option would not only cost less time (no need to assign work force to setting things up "properly") but also be overall more secure for many people.

Apart from that, -correct me if I'm mistaken- I'm under the impression that (Client->LB,LB->Backend)=(TLS,plain text) with TLS Termination OFF represents that the LB has to know to what kind of service exactly it is transferring requests to, so that it's not considered TLS "Termination". Doesn't this somewhat defeat the main advantage of TCP load balancing that is : it does not know enough to break things, everything will work ? Also, in the context of TCP TLS termination, it makes sense to me that the Load Balancer does not support *Application-Layer Protocol Negotiation*, because it's simply not supposed to know to what Application-Layer it's going to be talking to.

--
[1] Because we are talking about a client-side change here, since the server already accepts that kind of load-balancing
[2] Note that if considering to refuse that kind of connection on the server side (which is not done as of now, and not what this feature request is about), we are looking at the scenario of some attacker managing to have a non-http2 client connect *securely* to a grpc server, and the request "to *appear as a valid transaction* in [the grpc server]", leading it to unwanted behaviour, which, though more likely, is again less dangerous for many people than managing their own PKI.

**Comment by ejona86** [comment]
The basic problem is that TLS terminators are incompatible with HTTP/2. We agree that it makes little sense for TLS terminators to support ALPN, although this is predominantly because they have no way to communicate the selected protocol to the backend.

For gRPC, we require ALPN also to keep the HTTP/2 ecosystem healthy. gRPC clients should require ALPN, at least by default. But if we give an option for clients to disable ALPN, then the _client_ needs configuration based on the deployment architecture of the _server_. That's weird and is not-great. It also would make it dangerous to migrate from a TLS terminator to L7 proxy in the future, because you could have clients that don't support ALPN and the L7 proxy would end up speaking HTTP/1 to them, which would break. But we are also worried that services with third-party clients will start telling their clients to disable ALPN, which is just bad.

TCP load balancers still work. L7 (HTTP+HTTP/2) load balancers still work. But TLS terminating LBs don't work with HTTP/2. This is true independent of whether the server supports HTTP/1 fallback or not or whether you are using gRPC; you can't get HTTP/2.

You could set up your own L7 LB infrastructure based on nghttpx/nginx/etc, which would keep the certs separate. Yes, that isn't great because it isn't managed, but that's a problem because AWS does not provide HTTP/2 to the backend with their ALB.

**Comment by Ten0** [comment]
> gRPC clients should require ALPN, at least by default

Though it only has minor advantages (see the single scenario it protects against in my previous message), I would agree with that.

> It also would make it dangerous to migrate from a TLS terminator to L7 proxy in the future, because you could have clients that don't support ALPN and the L7 proxy would end up speaking HTTP/1 to them, which would break. We are also worried that services with third-party clients will start telling their clients to disable ALPN, which is just bad.

However I feel like there may be a misunderstanding here : I wrote about *non-enforcing* of ALPN, not of permanently disabling it as the build argument already allowed (and has these downfalls). Is there anything that prevents us from having the connection fall back to non-ALPN when ALPN appears to not be supported by the server ? That's not the impression I had from reading [the code](https://github.com/grpc/grpc/pull/18563/files#diff-4a4e7fca968f2ee74726253ea3359e0b).

> For gRPC, we require ALPN also to keep the HTTP/2 ecosystem healthy. [...] But if we give an option for clients to disable ALPN, then the client needs configuration based on the deployment architecture of the server. That's weird and is not-great.

That is true, and hopefully most people wouldn't need it. However since the current situation forces people to build solutions where either :
- > Currently we need to run an Envoy proxy locally on the client to get around this, which is not ideal.
- They build their own PKI which is both time consuming and a very important security risk, while also putting more load on the final servers
- > set up your own L7 LB infrastructure based on nghttpx/nginx/etc [...] that isn't great because it isn't managed

I feel like this would be worth the trade.

Also, even with the availability of an HTTP/2 L7 load balancer, using an L4 Load balancer could still be worth for some people for performance reasons.

**Comment by ejona86** [comment]
> I wrote about non-enforcing of ALPN

So was I. Look what happened in 3ish months where the client was failing to require ALPN. Servers were introduced that didn't support ALPN; when we "fixed the glitch" they broke. The reverse happens for servers. If the server doesn't support ALPN, then clients can accumulate that don't support ALPN. If the server starts requiring ALPN (like they are required to do per the spec), then they break. Then we would need a server-side option to ignore ALPN as well!

None of this is "new." The issues with TLS terminators are as old as HTTP/2. ALPN compatibility issues are as old as HTTP/2. There used to be _many_ more issues with ALPN, but most have been addressed at this point.

I do see where you are coming from. It is seriously unfortunate that you can't leverage TLS terminators. But it's not clear that avoiding ALPN is the best solution, as it is hacky and weakens the ecosystem. It is also something that all grpc implementations would need to support (see https://github.com/grpc/grpc-java/issues/5543 for evidence), and some of them won't be able to (e.g., if they use a generic HTTP client that has HTTP/2 support).

Supporting non-ALPN servers isn't out of the question. But it's also something that seems bad to be forced to make a decision on quickly. If we _have_ to make a decision quickly, I'd personally lean toward "no." This is still something I need to discuss with other implementations. I want to see how Go will handle this problem, since it _never_ verified ALPN. But some people are on vacation at the moment and some of this will take time.

As @lidizheng mentioned, we are willing to give you some time to migrate. We could introduce a temporary way to disable the ALPN check. But to make that effective we would make it very clear it is temporary. We want to get an idea of "how big of a hole are we in" to get an idea of how long it will take to get out of it.

**Comment by jiangtaoli2016** [comment]
The ALPN is in the spec of HTTP2, we shall enforce it by default if OpenSSL supports it. OpenSSL 1.0.2 and above support ALPN.

It is a bad argument that key management is complicated, thus it is more secure to most users to disable ALPN. It is unfortunate that many users rely on perimeter security and use plaintext inside the perimeter. This is not a good security principle.

**Comment by ejona86** [comment]
I had a conversation with others on grpc team. We are all against allowing to ignore ALPN. Again, I understand the pain, but this just isn't the solution.

At present it looks like we won't provide a temporary workaround for C core. If it becomes clear this issue is impacting many users then we could reconsider.

**Comment by Ten0** [comment]
I had not seen these potential ecosystem problems indeed. Thanks you for having seriously handled the issue :)
