### ISSUE TITLE
keepalive.md documentation is confusing

### ISSUE THREAD

**Issue by tnie** [grpc/grpc#18738]
### GRPC_ARG_HTTP2_MIN_SENT_PING_INTERVAL_WITHOUT_DATA_MS
[keepalive.md][1]
> If there is no data **being sent** on the transport, this channel argument controls the minimum time (in milliseconds) gRPC Core will wait between successive pings.

Does "data **being sent** on the transport" mean "there are data frame  in flight - Starting from home, have not arrived at the destination "? 

For client,  does "**data** being sent on the transport" mean 
- "data sent by client" or 
- "data sent by server" or 
- both ? or
- "data to be sent" (same with `GRPC_ARG_HTTP2_MAX_PINGS_WITHOUT_DATA`)

But [grpc_types.h][2] comment
> Minimum time between sending successive ping frames **without receiving** any data frame, Int valued, milliseconds.

### GRPC_ARG_HTTP2_MIN_RECV_PING_INTERVAL_WITHOUT_DATA_MS
[keepalive.md][1]
> If there is no data **being sent** on the transport, ...

But [grpc_types.h][2] comment
> Minimum allowed time between receiving successive ping frames without sending any data frame.

### GRPC_ARG_HTTP2_MAX_PINGS_WITHOUT_DATA
[keepalive.md][1]
> This channel argument controls the maximum number of pings that can be sent when there is no other data (data frame or header frame) **to be sent**. GRPC Core will not continue sending pings if we run over the limit. Setting it to 0 allows sending pings without sending data.

[grpc_types.h][2] comment
> How many pings can we send before needing to send a data frame or header frame?

So, "WITHOUT_DATA" of `GRPC_ARG_HTTP2_MIN_SENT_PING_INTERVAL_WITHOUT_DATA_MS` **is different from** "WITHOUT_DATA" of `GRPC_ARG_HTTP2_MAX_PINGS_WITHOUT_DATA` ?

"WITHOUT_DATA" of `GRPC_ARG_HTTP2_MIN_RECV_PING_INTERVAL_WITHOUT_DATA_MS` **is same with** "WITHOUT_DATA" of `GRPC_ARG_HTTP2_MAX_PINGS_WITHOUT_DATA` ?

[1]:https://github.com/grpc/grpc/blob/master/doc/keepalive.md
[2]:https://github.com/grpc/grpc/blob/master/include/grpc/impl/codegen/grpc_types.h

**Comment by karthikravis** [comment]
Hey Yash - can you please take a look?

**Comment by yashykt** [comment]
I have updated the doc. Thanks for pointing out the inconsistency!

Data being sent/recv is data that is sent/recv from the endpoint where this argument is used.

The without data in GRPC_ARG_HTTP2_MIN_RECV_PING_INTERVAL_WITHOUT_DATA_MS is same as that of GRPC_ARG_HTTP2_MAX_PINGS_WITHOUT_DATA - 
When data frames are sent, we reset counters so that when sending the next ping, we won't need to wait for the ping interval to expire.
Similarly, when these counters are reset, we also reset the counters for the ping strikes.

In case of GRPC_ARG_HTTP2_MIN_SENT_PING_INTERVAL_WITHOUT_DATA_MS, we are taking frames being received into consideration. Whenever we receive data frames, the next ping to be sent would not need to wait for this interval.

I hope that clarifies it.
