### ISSUE TITLE
GRPCRequestHeaders subclasses NSMutableDictionary and has an NSMutableDictionary ivar

### ISSUE THREAD

**Issue by stephanemoore** [grpc/grpc#18767]
GRPCRequestHeaders subclasses NSMutableDictionary:
https://github.com/grpc/grpc/blob/7897ae9/src/objective-c/GRPCClient/private/GRPCRequestHeaders.h#L23

GRPCRequestHeaders also has an NSMutableDictionary ivar:
https://github.com/grpc/grpc/blob/7897ae9/src/objective-c/GRPCClient/private/GRPCRequestHeaders.m#L59

The rationale for this design is not clear to me but I think that **something** is wrong and should be fixed.

**Comment by muxi** [comment]
Agree that this does not look right. This is some pretty old code that we didn't got a chance to clean up. Will take a look later. Thanks for reporting the finding Stephane.

**Comment by muxi** [comment]
I just took a look on this issue. The reason for both inheriting `NSMutableDictionary` and having an `NSMutableDictionary` ivar is because `GRPCCall` wants a property with `NSMutableDictionary` interface but wanted to add a few other functionalities. `NSMutableDictionary` looks to be a class cluster (or something alike; did not find doc proof but experiments showed so). With inheritance `GRPCRequestHeaders` does not get somewhere to store the key/value pairs and does not get implementation of some methods. So it uses an ivar of type `NSMutableDictionary` to delegate `setObject:forKey:` and `removeObjectForKey:`.

The solution looks a bit bizarre, but I find it makes sense and I did not come up with a better idea. If there's a better idea I would love to discuss more.
