### ISSUE TITLE
Continuous integration for homebrew-grpc

### ISSUE THREAD

**Issue by jtattermusch** [grpc/grpc#1883]
In the future we should setup CI for our formulas:
Jenkins that would try to install our formulas on Linux and Mac anytime we touch them. We shouldn't rely on hand testing when making sure we didn't break the formulas.

**Comment by ctiller** [comment]
+1

**Comment by jtattermusch** [comment]
Tim, Jenkins should be ready to handle this.

**Comment by stanley-cheung** [comment]
Status:
 * A grpc linuxbrew project has been added to Jenkins for the following languages: core, python, nodejs, ruby and php.
 * The grpc formula has been updated to 0.10 release
 * All language tests are passing as of just now.
 * Next up: add the same tests for homebrew on mac on Jenkins

**Comment by jtattermusch** [comment]
When thinking of it, it doesn't make much sense to build this on every push to  upstream/master  because the homebrew formulas refer to tagged versions of gRPC (or published distribution packages).

We should probably make this build on pushes to grpc/homebrew-grpc repo instead (= basically same effect and less computing power needed).

Ideally, we would want solution that builds the grpc packages for each language and then tries to install them and makes sure if they work. For such test it would make sense to run it on every push to master (and maybe also enable parametrized build so can everyone can test whatever branch he wants).

**Comment by stanley-cheung** [comment]
Started a project on Jenkins to continously test our [homebrew](https://github.com/grpc/homebrew-grpc) formula on a Mac machine.

https://grpc-testing.appspot.com/job/gRPC%20mac%20homebrew/

**Comment by stanley-cheung** [comment]
Status:
 * We consolidated this into a single project under jenkins: [gRPC distribution](https://grpc-testing.appspot.com/job/gRPC_distribution/), which test our [homebrew installation script](https://github.com/grpc/homebrew-grpc) in both linux and macos.
 * [Currently](https://grpc-testing.appspot.com/job/gRPC_distribution/347/) only "macos,ruby" is failing, because of #2462. All other 9 combos are passing.

@jtattermusch anything else for this issue, or is good to close?

**Comment by jtattermusch** [comment]
Yeah! Sounds good, thanks for all the hard work.
