### ISSUE TITLE
Service Config Selection is under specified

### ISSUE THREAD

**Issue by carl-mastrangelo** [grpc/grpc#18890]
The [service config error handling](https://github.com/grpc/proposal/blob/master/A21-service-config-error-handling.md) proposal describes some, but not all of the cases of how to handle service config updates.  Questions brought up in the [Java implementation](https://github.com/grpc/grpc-java/pull/5642) PR need to be resolved before it can continue.  From Java's POV, state management of the service config is updated by a hypothetical 3 argument function:

```
enum nameResolverUpdate {
  UNKNOWN_CONFIG, // The name resolver does not support service config, the value here does not have meaning
  NO_SERVICE_CONFIG, // The name resolver understands service config, but it says to not use it.  
  SERVICE_CONFIG, // The name resolver has produced a valid and usable service config
  ERROR; // There was an error with the service config parsing or retrieval. 
}

enum channelExistingConfig {
  NO_CONFIG, // there is no service config,
  EXISTING_CONFIG, // There is a valid config on the channel, it is being applied to RPCs
  FAILURE; // There is a failure, causing the channel to fail RPCs.
}

update(nameResolverUpdate, defaultServiceConfig, lookupServiceConfig, channelExistingConfig) {
  // ...
}
```

There are 48 permutations of arguments to pass to this (4 x 2 x 2 x 3), with the defaultServiceConfig being either present or absent, and lookupServiceConfig being either true or false.

The current question is what to do if the name resolver returns UNKNOWN_CONFIG, and there is a defaultServiceConfig.  This is not covered, as it isn't really an error scenario.

@zhangkun83 @yashykt

**Comment by carl-mastrangelo** [comment]
Also, NO_SERVICE_CONFIG and SERVICE_CONFIG  are distinct in that NO_SERVICE_CONFIG should not override the default load balancer on the channel.  Both choices SHOULD override the default service config, if present.

**Comment by zhangkun83** [comment]
> Also, NO_SERVICE_CONFIG and SERVICE_CONFIG are distinct in that NO_SERVICE_CONFIG should not override the default load balancer on the channel. Both choices SHOULD override the default service config, if present.

I think they are the same. NO_SERVICE_CONFIG is basically SERVICE_CONFIG with an empty config, because it meets the criterion for using default load balancing policy, which is "the service config doesn't specify a policy".

**Comment by zhangkun83** [comment]
/cc @dfawley @ejona86 

I guess we can treat absence-of-config in a similar way we handle parse errors. The question is what if there isn't a previous config nor default config. Assume empty config?

The spec should also call out what an "empty service config" is, which I suppose is "{}". Empty string is probably invalid service config.

**Comment by yashykt** [comment]
If the system is configured such that service config are to not be used, then no service config is applied, which is the same as an empty config or {}.

I still don't understand what UNKNOWN_CONFIG means. As per https://github.com/grpc/grpc/blob/master/doc/naming.md resolvers are supposed to return a service config. If the resolver does not support service config and if we assume that the resolver is supposed to be a valid grpc resolver, then we would need to assume that it always returns an empty service config, i.e., the same as NO_SERVICE_CONFIG

**Comment by markdroth** [comment]
Yash, not all resolvers support service config, and in the case where a resolver does not support service config, we should fall back to using the default service config provided via the client API instead of assuming that the resolver has returned an empty config.

Also, note that gRPC implementations should support a channel arg that tells the resolver not to fetch the service config, even if it is supported by the resolver implementation.  This is intended for use mainly in testing (i.e., it forces the channel to use the default service config specified via the client API), but the semantics should be the same as if the resolver did not support service config at all.

Kun, I agree with you that `NO_SERVICE_CONFIG` and `SERVICE_CONFIG` should not be different; sending an empty config should be handled the same way as sending a non-empty config.  We should *not* treat absence-of-config the same way as a parse error, because absence-of-config is likely to be the common case.  Service config is intended to be an optional feature, not a required one.

That having been said, one minor problem that just occurred to me is that the mechanism we're using internally to distribute service configs doesn't actually have a way to remove a config once it's created; the best that can be done is to convert it to an empty config.  But since we need to treat those two things differently, that means that anyone who creates a config for their service can't ever remove it, which seems sub-optimal.  Yash, this may be something we should consider further internally, although it doesn't affect the overall design of the service config feature.

Stepping back, I think the rules here should be as follows:
- If the resolver returns `SERVICE_CONFIG`, use the service config it specified.
- If the resolver returns `ERROR`, if the channel still has a valid config from a previous resolver result, continue using that.  Otherwise, use the default config provided via the client API, if specified.  Otherwise, put the channel in TRANSIENT_FAILURE.
- If the resolver returns `UNKNOWN_CONFIG` (either because it does not support service config or because the channel arg to inhibit service config lookup was used), use the default config specified via the client API.  If there is no default config, assume the empty config.

Does that seem reasonable to everyone?

**Comment by yashykt** [comment]
That sounds reasonable. We should also make clear that if we end up using a default config provided by the client API, and the default config has parsing errors, the channel would be put in TRANSIENT_FAILURE

**Comment by carl-mastrangelo** [comment]
@yashykt I think @markdroth and I informally agreed on invalid config causing the channel to fail at creation time, rather than fail the incoming RPCs.  I think the spec should be updated to reflect this.

**Comment by markdroth** [comment]
Carl, in C/C++, channel creation cannot fail.  Instead, when something fundamental goes wrong in channel creation, we create a lame channel that fails all RPCs.

But actually, now that I think about it, this might not be the best approach.  Even if the default config set via the client API is bad, the channel might still recover if we get a valid config from the resolver, so maybe we should give it the opportunity to do that?

**Comment by carl-mastrangelo** [comment]
@markdroth   I don't think so.  I don't think it can recover, because the only time the default config is relevant is if the name resolver returns an error on first resolution, or lookup is disabled, and no new config will ever come.  

I guess if the first resolution results is UNKNOWN_CONFIG, it *may* in the future return SERVICE_CONFIG, but that sounds degenerate.  I can't imagine it being common that an NR would vary between UNKNOWN_CONFIG and SERVICE_CONFIG over the lifetime of the program.   To me, the default is for bootstrapping the channel towards functionality.  It *should* have been a compile time error.

**Comment by zhangkun83** [comment]
> Yash, not all resolvers support service config, and in the case where a resolver does not support service config, we should fall back to using the default service config provided via the client API instead of assuming that the resolver has returned an empty config.
> 
> Also, note that gRPC implementations should support a channel arg that tells the resolver not to fetch the service config, even if it is supported by the resolver implementation. This is intended for use mainly in testing (i.e., it forces the channel to use the default service config specified via the client API), but the semantics should be the same as if the resolver did not support service config at all.
> 
> Kun, I agree with you that `NO_SERVICE_CONFIG` and `SERVICE_CONFIG` should not be different; sending an empty config should be handled the same way as sending a non-empty config. We should _not_ treat absence-of-config the same way as a parse error, because absence-of-config is likely to be the common case. Service config is intended to be an optional feature, not a required one.
> 
> That having been said, one minor problem that just occurred to me is that the mechanism we're using internally to distribute service configs doesn't actually have a way to remove a config once it's created; the best that can be done is to convert it to an empty config. But since we need to treat those two things differently, that means that anyone who creates a config for their service can't ever remove it, which seems sub-optimal. Yash, this may be something we should consider further internally, although it doesn't affect the overall design of the service config feature.
> 
> Stepping back, I think the rules here should be as follows:
> 
> * If the resolver returns `SERVICE_CONFIG`, use the service config it specified.
> * If the resolver returns `ERROR`, if the channel still has a valid config from a previous resolver result, continue using that.  Otherwise, use the default config provided via the client API, if specified.  Otherwise, put the channel in TRANSIENT_FAILURE.
> * If the resolver returns `UNKNOWN_CONFIG` (either because it does not support service config or because the channel arg to inhibit service config lookup was used), use the default config specified via the client API.  If there is no default config, assume the empty config.
> 
> Does that seem reasonable to everyone?

@markdroth this SGTM.

**Comment by ejona86** [comment]
> If the resolver returns ERROR, if the channel still has a valid config from a previous resolver result, continue using that. Otherwise, use the default config provided via the client API, if specified. Otherwise, put the channel in TRANSIENT_FAILURE.

I had expected this not to have the fallback to "the default config provided via the client API". Why isn't that considered a failure? In my mind setting "the default config via the client API" was just _changing_ the default config to something non-empty. Does this mean we'd be happy with users explicitly configuring "{}" just to avoid the TRANSIENT_FAILURE?

**Comment by markdroth** [comment]
@carl-mastrangelo Any time a service adds a config in their name service after the time that the clients have started up, the resolver will switch from `NO_SERVICE_CONFIG` to `SERVICE_CONFIG`, so that seems like a completely legitimate case.

In C/C++, our general principle for channels is that they should always be in a state that tries to recover if conditions change.  That's why, for example, an initial DNS resolution failure causes us to retry.  I'm not sure if Java has the same principle; if you actually have a way for channel creation to fail, then maybe your API is providing different guarantees?

That having been said, I am sympathetic to the problem of needing a clean way for users to determine that the config they provided to the client API is invalid.  @yashykt, can you suggest an approach for making that more visible to users?

**Comment by markdroth** [comment]
> > If the resolver returns ERROR, if the channel still has a valid config from a previous resolver result, continue using that. Otherwise, use the default config provided via the client API, if specified. Otherwise, put the channel in TRANSIENT_FAILURE.
> 
> I had expected this not to have the fallback to "the default config provided via the client API". Why isn't that considered a failure? In my mind setting "the default config via the client API" was just _changing_ the default config to something non-empty. Does this mean we'd be happy with users explicitly configuring "{}" just to avoid the TRANSIENT_FAILURE?

@ejona86 Yes, that's exactly the goal here.  The idea is that if the user didn't provide a default config, we go into TRANSIENT_FAILURE to avoid doing anything bad by accident, but users that want to avoid that can do so by providing a default config.  The empty config is just one example of a default config that the user could provide.

**Comment by ejona86** [comment]
> Yes, that's exactly the goal here.

What is the driving requirement? To me we're watering down the TRANSIENT_FAILURE case even more than we were already. If we're going in this direction it seems likely the same argument would apply for killing the TRANSIENT_FAILURE handling.

**Comment by yashykt** [comment]
@markdroth Since the default service config is being set through the client API, setting the channel to a lame channel does not seem like a bad idea. This way it should get caught in their tests since all RPCs would fail. In the error message, we could provide the parsing error.

**Comment by markdroth** [comment]
@ejona86 

> What is the driving requirement? To me we're watering down the TRANSIENT_FAILURE case even more than we were already. If we're going in this direction it seems likely the same argument would apply for killing the TRANSIENT_FAILURE handling.

This is the case we discussed with SRE way back at the beginning of the service config error handling design.  The goal is that by default, newly started clients will not function with an invalid service config.  However, in cases where the resolver has a feedback mechanism to provide monitoring for bad configs without causing clients to fail, users can avoid having the client fail by providing a default config via the client API.

**Comment by markdroth** [comment]
I think all the open questions here are addresses, so I'm going to close this.  Please re-open if there are still questions.  Thanks!
