### ISSUE TITLE
Latency in SynthesizeSpeech() response

### ISSUE THREAD

**Issue by cewong-genesys** [grpc/grpc#18990]
### What version of gRPC and what language are you using?
 1.3.x and C++
 
### What operating system (Linux, Windows,...) and version?
 Windows Server 2012 R2 (2 virtual cores, 8G memory)
 
### What runtime / compiler are you using (e.g. python version or version of gcc)
 VS2013
 
### What did you do?
We just call Google cloud Text-to-Speach function 
::grpc::Status SynthesizeSpeech() 
in our program.
 
### What did you expect to see?
 SynthesizeSpeech() should come back with a response within a second.
 
### What did you see instead?
If it is the first call after program startup or idling (> 20 mins), there is a latency (anywhere from 7s to 2 mins) in the response from SynthesizeSpeech(). If the call is made immediately after a previous call, there is no such latency. We have captured gRPC console output to a file (attached) and it seems that gRPC connection was not made immediately resulting in the latency. The output is for one call after program startup immediately followed by 2 quick calls. The first call has latency but not the other calls.

See [TROUBLESHOOTING.md](https://github.com/grpc/grpc/blob/master/TROUBLESHOOTING.md) for how to diagnose problems better.
 
### Anything else we should know about your project / environment?
None
[MCP_console_test01a.log](https://github.com/grpc/grpc/files/3157345/MCP_console_test01a.log)

**Comment by cewong-genesys** [comment]
Any update on this issue? Thanks.

**Comment by AspirinSJL** [comment]
I checked the log. I see that the connection attempt is not started until ~8s has passed since the first call is started. In between, I don't see any meaningful log other than some timer log. If we can have some resolver and load balancing policy related log, we can debug it more easily. But we don't have such tracers in v1.3.x.

Stepping back a little, could you update to some more recent version of gRPC and see if this issue still exists? https://github.com/grpc/grpc/releases

**Comment by cewong-genesys** [comment]
Thank you for your update. Unfortunately, we need to use VS2013 so we are unable to upgrade to higher version of gRPC libraries since they do not build on vs2013.

Is there something else we can do to debug the issue on the current version?

**Comment by AspirinSJL** [comment]
There are several steps before connection attempt is started:
1. the resolver (by default, [native DNS resolver](https://github.com/grpc/grpc/blob/v1.3.x/src/core/ext/filters/client_channel/resolver/dns/native/dns_resolver.c)) resolves the name to an address list
2. the resolver passes the address list to the load balancing policy (by default, [pick_first](https://github.com/grpc/grpc/blob/v1.3.x/src/core/ext/filters/client_channel/lb_policy/pick_first/pick_first.c))
3. pick_first LB policy will create a subchannel list from the address list

then pick_first will start to connect to the first subchannel.

v1.3.x is really old, so the log info is very limited. I suggest adding some logs to the above steps to see which step is costly. In normal cases, those steps should finish very quickly. If the resolving is slow, the root cause may be the network environment. Otherwise it's a bug in gRPC.

gdb may not be very helpful in this case because the stopping at breakpoints may interfere with the  timing in gRPC operations.
