### ISSUE TITLE
C Core returns trailers with headers when the stream is empty

### ISSUE THREAD

**Issue by JamesNK** [grpc/grpc#19003]
I am writing a new gRPC client and I have a question about one of the interop tests. In the `empty_stream` test case the C Core server returns trailers with headers in one HEADERS frame.

![image](https://user-images.githubusercontent.com/303201/57488355-f3df3380-7306-11e9-9ad9-a198577cf428.png)

Blue: headers, red: trailers

Is this expected? If so it might be worth expanding the spec - https://github.com/grpc/grpc/blob/master/doc/PROTOCOL-HTTP2.md#responses - to mention it.

**Comment by jtattermusch** [comment]
I think this case is covered under the "Trailers-Only" case: `Trailers-Only → HTTP-Status Content-Type Trailers`. I'll try to find out more, but this doesn't strike me as wrong.

**Comment by jtattermusch** [comment]
Quoting from spec: *Response-Headers & Trailers-Only are each delivered in a single HTTP2 HEADERS frame block. Most responses are expected to have both headers and trailers but Trailers-Only is permitted for calls that produce an immediate error. Status must be sent in Trailers even if the status code is OK.*

**Comment by JamesNK** [comment]
> Response-Headers & Trailers-Only *are each delivered* in a single HTTP2 HEADERS frame 

I wasn't sure if this part of the spec was covering this situation or not. It sounds like they each have there own single frame, rather than being delivered in a single frame together.

**Comment by jtattermusch** [comment]
ok, so are you saying the issue is that you've confirmed that they are both delivered in a single http2 headers frame and the spec seems to be saying that they each of them should be delivered in two separate http2 frames?

I think that might be a misunderstanding, as for given RPC, you'll never have both Response-Headers and Trailers-Only (it's either-or).
 the grammar: 
`Response → (Response-Headers *Length-Prefixed-Message Trailers) / Trailers-Only`

`Trailers-Only → HTTP-Status Content-Type Trailers`

so ti seems that the HEADERS frame you received is "Trailers-Only". It has http-status, content-type and the usual trailers in it. Just as the spec says, it should be delivered in a single frame.

**Comment by JamesNK** [comment]
Ok, I see. Thanks for providing some certainty.
