### ISSUE TITLE
How C# base service returns error (in the generated stub code).

### ISSUE THREAD

**Issue by JamesNK** [grpc/grpc#19110]
The generated code throws an error from a method returning Task. This is fine if the method has the async keyword, but it introduces small behavior different for non-async methods.

Current:

```cs
  [grpc::BindServiceMethod(typeof(Topics), "BindService")]
  public abstract partial class TopicsBase
  {
    public virtual global::System.Threading.Tasks.Task Subscribe(global::SubscribeRequest request, grpc::IServerStreamWriter<global::Event> responseStream, grpc::ServerCallContext context)
    {
      throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
    }

  }
```

https://stackoverflow.com/questions/40653561/c-sharp-async-exception-wrapping

Consider returning a faulted task instead:

```cs
  [grpc::BindServiceMethod(typeof(Topics), "BindService")]
  public abstract partial class TopicsBase
  {
    public virtual global::System.Threading.Tasks.Task Subscribe(global::SubscribeRequest request, grpc::IServerStreamWriter<global::Event> responseStream, grpc::ServerCallContext context)
    {
      return Task.FromException(new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, "")));
    }

  }
```

Note: This isn't breaking anything. Low priority.

**Comment by jtattermusch** [comment]
@JamesNK  is this still worth addressing?

**Comment by jtattermusch** [comment]
It turns out we actually have a test for the unimplemented methods in base service and the behavior seems to be as expected (when I use a service with and I don't override the handler method implementation, I will get a service than consistently returns StatusCode.Unimplemented when invoking the service by a client).
https://github.com/grpc/grpc/blob/3bfe761a6e59c11c44789c5b1887d87c496b9699/src/csharp/Grpc.IntegrationTesting/GeneratedServiceBaseTest.cs#L61

**Comment by tonydnewell** [comment]
From reading https://stackoverflow.com/questions/40653561/c-sharp-async-exception-wrapping it does appear that the existing behaviour of throwing the exception immediately rather than returning in a Task is acceptable for a coding errors (e.g. unimplemented methods) - what Microsoft calls [boneheaded](https://learn.microsoft.com/en-us/archive/blogs/ericlippert/vexing-exceptions) exceptions.

**Comment by jtattermusch** [comment]
@JamesNK  can this be closed?
