### ISSUE TITLE
Enable fork support for Python by default

### ISSUE THREAD

**Issue by lidizheng** [grpc/grpc#19158]
Fork support has been added for more than half a year. However, users constantly found it challenging to find documentations about this feature. Yet this feature is made specifically for open source.

To enable fork support, we have several items to finish:

1. Investigate performance impact to initialization time, RPC latency, etc.
2. Resolve existing issues related to fork support.
    * https://github.com/grpc/grpc/issues/18075

Advices are welcomed.

**Comment by mehrdada** [comment]
Can you please verify/add a test/confirm it will not work for the following use case:

- Create channel
- Invoke RPC on channel
- Close channel
- Fork
- Make RPCs

We have a test case that does the following (not complete code as it needs dependencies, but basically conveys the picture) that consistently times out on 2.7:

```
from multiprocessing import Process, Queue
client = common.get_test_client(...)
common.make_unary_stream_rpc(client)
client.close()
q = Queue()  # type: Queue
p = Process(target=common.make_rpcs, args=(q,)) # invokes RPCs and enqueues stuff in q
p.start()  # deadlocks here, I believe
p.join()
assert q.get() is True
```

**Comment by mehrdada** [comment]
P.S. https://github.com/grpc/grpc/blob/master/doc/fork_support.md document which predates `Channel.close` vaguely documents fork to be unsupported when a "channel is active" or "after it is used". Before `close` they mostly meant the same thing, but after `close` it is important to differentiate the two: i.e. what happens if we fork after closing the channel?

**Comment by lidizheng** [comment]
TBO, this is the first time I know we have problem forking even after the channel is closed. Thank you for giving the context and action items for verification :)

**Comment by mehrdada** [comment]
Yeah, in general, `close()` is not quite well-thought-out.

**Comment by srini100** [comment]
In client-side fork support, child process will not have any access to parent channels as those channels are closed in the child post fork handler. In fact, the child post fork handler in Python will free all the Core resources and cancel all in flight calls. This will not interfere with parent channels or calls as the FDs on child are replaced with -1 so no resets are sent on the wire. I don't think it is possible to support cases where parent and child can share the channels. Not sure if there is any practical use for it. In the current solution, parent can continue to use channels and calls that were created before fork. Essentially, parent process remains unaffected by fork.

**Comment by mehrdada** [comment]
@srini100 The specific behavior that seems in question here is not sharing channels, but what if the original channel is used and closed and then you fork and create a *new* channel and try sending RPCs. The intent is for that to work, correct?

**Comment by srini100** [comment]
Yes. Parent and child can create channels after fork. They should be totally independent of each other. BTW, in you above example are you setting GRPC_ENABLE_FORK_SUPPORT=true?

**Comment by mehrdada** [comment]
@srini100 Not sure about that; will check and report back

**Comment by mehrdada** [comment]
So, this is super confusing: `GRPC_ENABLE_FORK_SUPPORT=1` does not seem to make a difference in the test case, but very weirdly, removing the final `assert` statement that makes use of the queue makes the test pass, but it is not because that assertion gets to run at all (turning assertion into a simple `xx = q.get() is True` has exactly the same effect)! If you add print statements between each line, adding and removing the assertion makes the whole thing block on `p.start` and not even `p.join`.  Removing that line which is not even executed makes `p.start()` operate normally. This might involve some weird interaction of gil/grpc/fork or a bug in the interpreter/multiprocessing, or potentially a corruption issue.

This is not a use case we actually have in production, simply a quarantined continuously failing test case, so it is not a priority for us, but if you're working to clean this up, it might be worthwhile to add a test case to gRPC for fork and then utilizing gRPC under a new channel after a used channel is closed.
