### ISSUE TITLE
Reusability of SPIFFE TLS objects

### ISSUE THREAD

**Issue by euroelessar** [grpc/grpc#19237]
Please clarify if `grpc_tls_credential_reload_config` can be safely re-used between different channels/servers.

Based on the implementation it looks like it's not the case.

Also please clarify if single SPIFFE-created `grpc_channel_credentials` and `grpc_server_credentials` can be re-used between different channels/servers.

Would upstream be willing to accept patches to make this objects shareable? It feels like relatively simple change and would simplify users a lot.

**Comment by euroelessar** [comment]
@jiangtaoli2016 can you have a look, please?

**Comment by jiangtaoli2016** [comment]
@markdroth @yihuazhang FYI

**Comment by jiangtaoli2016** [comment]
SPIFFE `grpc_channel_credentials` and `grpc_server_credentials` can be re-used for different channels and servers. In other words, you can create channel credentials once and use this object to create multiple channels.

For grpc_tls_credential_reload_config, once you create it, you can re-use it to create different grpc_tls_credentials_options. It is [refcounted](https://github.com/grpc/grpc/blob/master/src/core/lib/security/credentials/tls/grpc_tls_credentials_options.cc#L117). 

Let me know if it does not meet your expectation.

**Comment by euroelessar** [comment]
While `grpc_tls_credential_reload_config` is refcounted it doesn't preserve the last value by itself.

It means that every instance of `SpiffeServerSecurityConnector`/`SpiffeChannelSecurityConnector` calls `Schedule` independently and only the first one sees the key material, all other instances of `SpiffeServerSecurityConnector` see "no changes yet" status and fail creation.

More over as every instance queries the condig independently it's possible that there are multiple concurrent calls to `Schedule` from different threads and documentation doesn't specify the behavior in this case.

**Comment by yihuazhang** [comment]
@euroelessar 
Each time before `Schedule` is invoked, the [code](https://github.com/grpc/grpc/blob/master/src/core/lib/security/security_connector/tls/spiffe_security_connector.cc#L63) always creates a new `grpc_tls_credential_reload_arg` which further creates a new place holder for the key materials. So no key materials will be shared across different instances. Also, the current behavior will not fail if it sees "no changes", but rather keeps using the existing credential.

PLMK what you think.

**Comment by euroelessar** [comment]
@yihuazhang Let me provide a step-by-step model:
1. `grpc_tls_credential_reload_config` object is created, let's call it `reload_config`.
2. First `SpiffeServerSecurityConnector` object is created based on the config which uses `reload_config`.
3. First `SpiffeServerSecurityConnector`'s constructor creates a new `grpc_tls_credential_reload_arg` and calls `Schedule` on `reload_config`. As it's the first call `reload_config` returns new `key_material` and `GRPC_SSL_CERTIFICATE_CONFIG_RELOAD_NEW` status.
4. On TLS handshake `SpiffeServerSecurityConnector::PopulateSpiffeCredentials` creates a new `grpc_tls_credential_reload_arg` and calls `Schedule` on `reload_config`. As there were no changes yet `reload_config` returns `GRPC_SSL_CERTIFICATE_CONFIG_RELOAD_UNCHANGED` status.
5. Second `SpiffeServerSecurityConnector` object is created based on the config which uses `reload_config`.
6. Second `SpiffeServerSecurityConnector`'s constructor creates a new `grpc_tls_credential_reload_arg` and calls `Schedule` on `reload_config`. As there were no changes yet `reload_config` returns `GRPC_SSL_CERTIFICATE_CONFIG_RELOAD_UNCHANGED` status. As it's non-new status `SpiffeServerSecurityConnector` creation fails.

Similar behavior would be observed on `SpiffeChannelSecurityConnector` creation.

**Comment by yihuazhang** [comment]
Thanks @euroelessar for the explanation. I agree that it is indeed a bug in the current implementation. I think the correct behavior should be if a new credential is reloaded, it needs to be stored at the option's `key_materials_config_` field and next time if credential reload returns `GRPC_SSL_CERTIFICATE_CONFIG_RELOAD_UNCHANGED `, instead of returning empty key materials, it should return the one stored in the option.

**Comment by euroelessar** [comment]
That should work.
As noticeable optimization I would recommend checking that value did not change, and only re-create handshaker (e.g. SSL_CTX object) on actual changes.

In https://github.com/grpc/grpc/pull/16567 I've used version-based schema for it (see `VersionedClientSslConfig` object).

**Comment by yihuazhang** [comment]
Yes, that's good point. There is no need to re-create SSL_CTX objects if key materials did not change. 

@euroelessar, if you already have a patch PR to fix the issue, feel free to send it on my way.

**Comment by euroelessar** [comment]
@yihuazhang I currently don't have a patch for adding this logic to SPIFFE TLS implementation.

**Comment by yihuazhang** [comment]
@euroelessar, sure, let me work on it next week.

**Comment by euroelessar** [comment]
@yihuazhang thank you!

**Comment by yihuazhang** [comment]
@euroelessar 

I am currently working on https://github.com/grpc/grpc/pull/19346 that attempts to ix the issues in #15735 and #19237. After thinking twice, I need to take back the idea that I proposed w.r.t storing the reloaded credential in the option's `key_materials_config_` field because `grpc_tls_credentails_options` object is designed to be read-only in order to avoid race condition. Instead I propose the following: 

1) In each security connector, we will keep a copy of  `key_materials_config` that stores the key materials that will be used just for this security connector. Each invocation of credential reload will only update the credential belonging to the corresponding security connector. 

2) Each time `Schedule` is called, it will take the copy of key materials as an input (will be a part of `grpc_tls_credential_reload_arg`) and gets it reloaded. And once it is reloaded with a new credential, it will update its local copy. Furthermore, `Schedule` API should be stateless in a sense that it should return the reload result just based on the input `grpc_tls_credential_reload_arg`. So in your example, when the second security connector is called, since it will have empty key materials as an input to `Schedule`, the result he should get back  should be `GRPC_SSL_CERTIFICATE_CONFIG_RELOAD_NEW`. 

PLMK what you think.

**Comment by euroelessar** [comment]
@yihuazhang 

> After thinking twice, I need to take back the idea that I proposed w.r.t storing the reloaded credential in the option's `key_materials_config_` field because `grpc_tls_credentails_options` object is designed to be read-only in order to avoid race condition.

Did you consider adding a lock around `grpc_tls_credentails_options`'s state?
For instance:
1. Make the latest `key_materials_config_` a shared pointer (so that copy is cheap).
2. Add `Schedule` function with approximately the following logic:
```
struct VersionedKeyMaterials {
  int version;
  key_materials_config config;
};

SharedPtr<VersionedKeyMaterials> grpc_tls_credentails_options::KeyMaterials() {
  auto arg = grpc_tls_credential_reload_arg::Create();
  grpc_core::MutexLock lock(&mu_);
  options.credential_reload_config()->Schedule(arg);
  if (arg->status == GRPC_SSL_CERTIFICATE_CONFIG_RELOAD_NEW) {
    key_materials_config_ = MakeSharedPtr<VersionedKeyMaterials>(version_++, arg->key_materials);
  }
  return key_materials_config_;
}
```
3. Caller can compare the version to make a decision if handshake factory has to be re-created.

Note that it relies on `Schedule` to be a cheap call (compared to the cost of TLS handshake itself), but it's likely that alternative approaches imply the same restrictions.

>  1. In each security connector, we will keep a copy of  `key_materials_config` that stores the key materials that will be used just for this security connector. Each invocation of credential reload will only update the credential belonging to the corresponding security connector.

Size of TLS certs is in a range of ≈10KB. Size of CA certs in standard linux distribution is ≈230KB.
It feels unnecessary expensive to compare few hundreds of kilobytes of data on every TLS handshake.

There are few ways to mitigate this cost while preserving the logic:
1. Use `grpc_slice` instead of `char*` to store key material. In this case `Schedule` implementation can compare slices as a pointers (`grpc_slice_is_equivalent`). However it is unclear how to expose this API to the wrapped languages (as grpc_slice may not be a part of the public api).
2. Add some per-caller user-data to `grpc_tls_credential_reload_arg`. It could be simple integer `nonce`/`version`, or more generic `void*` (but that would require to provide its destructor).

**Comment by yihuazhang** [comment]
@euroelessar Sorry for the late response. 

I think what you proposed are all nice ways to avoid the race condition. But I would still insist that `grpc_tls_credentials_options` should be read-only. Because it can be shared by multiple credentials, and it does not make sense to me to store connection-specific information (i.e., key_materials) in that global storage. 

To avoid expensive comparison, I think we can add a key version number to the `grpc_tls_key_materials_config` which will be written and read by `Schedule` implementations.

**Comment by euroelessar** [comment]
@yihuazhang Thanks, having a version solves performance concern and is relatively simple to use.

**Comment by AspirinSJL** [comment]
Looks like this issue is resolved. If not, please reopen.
