### ISSUE TITLE
Signal Handlers not Run While Client Iterates over Server-Streaming or Bidi RPC

### ISSUE THREAD

**Issue by gnossen** [grpc/grpc#19464]
```python
stub = foo_pb2_grpc.FooStub(channel)
result_generator = stub.StreamingRPC(foo_pb2.FooReques())

def cancel_request(unused_signum, unused_frame):
    result_generator.cancel()

signal.signal(signal.SIGINT, cancel_request)
for result in result_generator:
    do_stuff(result)
```

At the moment, iterating over `result_generator`  can block the main thread indefinitely, not allowing the signal handler to run.

After discussing with @lidizheng , we believe that the main thread is caught up performing a blocking operation in Core, probably waiting on a completion queue. The thread should be yielded periodically so that signal handlers may be run.

**Comment by lidizheng** [comment]
I presume we need to `gdb` the un-responsive process.

My guess about the completion queue block could be wrong since we already set 200 ms timeout for each wait, and checking signal in Cython explicitly. The blocking I think should be caused by other function call.

**Comment by lidizheng** [comment]
As discussed offline, we are doing the periodical check in #19481. As suggested by @gnossen , the infinite timeout solution isn't ideal since it depends on CPython's implementation. However, if we perform the spin check in Python layer, we could have more control.

Related Python bug: https://bugs.python.org/issue35935.

**Comment by gnossen** [comment]
Fixed by https://github.com/grpc/grpc/pull/19481
