### ISSUE TITLE
OpenSSL 1.0.1 compatibility

### ISSUE THREAD

**Issue by opello** [grpc/grpc#19483]
It seems that in #4395 a precedent for OpenSSL backward compatibility to 1.0.1 was set.  It certainly worked for the previous version I was using, 1.14.1.  In trying to move forward to 1.19.1 I ran into a build failure:
```
.../src/core/tsi/ssl_transport_security.cc:659:52: error: 'X509_V_FLAG_TRUSTED_FIRST' was not declared in this scope
```

This is from 5a0699c705177d4a3c6a35c95a92d0be3ec378a6, which is presumably a desirable change.  In order to work around the issue, I simply reverted the commit.  That doesn't seem very safe to me, since I didn't investigate the implications or assumptions of the surrounding code.

The flag (X509_V_FLAG_TRUSTED_FIRST) [seems to have been added in OpenSSL 1.0.2a][1], and is [in the 1.0.2 documentation][2], as early as I can find.

[1]: https://www.openldap.org/lists/openldap-devel/201506/msg00014.html
[2]: https://www.openssl.org/docs/man1.0.2/man3/X509_VERIFY_PARAM_set_hostflags.html

**Comment by a11r** [comment]
It might be time to drop OpenSSL 1.0.1 . Requesting opinion from jiangtaoli2016

**Comment by jiangtaoli2016** [comment]
OpenSSL 1.0.2 has been released since Jan 2015. I think it is time to stop supporting OpenSSL 1.0.1 or older versions in gRPC. @nicolasnoble What do you think?

**Comment by jtattermusch** [comment]
Dropping OpenSSL 1.0.1 support due to its age sounds reasonable. We might be able to do some cleanup in our repo if that's approved.
https://github.com/grpc/grpc/blob/master/tools/openssl/use_openssl.sh

Btw, it would be good to come up with a list with OpenSSL versions in stable distros we support (e.g. debian / ubuntu / centos / fedora / alpine / arch / opensuse ). If all of them have OpenSSL 1.0.2+, we should be good.

I also remember that v1.0.2 is the first version that supports ALPN, so by dropping 1.0.1 support, we might be able to get rid of some complexity in C-core?

**Comment by Croydon** [comment]
I think that we might be fine when
  * #21293 is solved
  * and this https://github.com/grpc/grpc/blob/master/tools/openssl/use_openssl.sh script is updated to use 1.1.1

**Comment by jtattermusch** [comment]
@Croydon  I don't think the "use_openssl.sh" script is used for anything. AFAIK it's a remaining piece of tests we no longer run.
Also, we no longer recommend building with `Makefile` (which is what use_openssl.sh) does.

**Comment by Croydon** [comment]
Okay, understood. Are there any tests running with OpenSSL currently?

Thanks for pushing this forward

**Comment by jtattermusch** [comment]
> Okay, understood. Are there any tests running with OpenSSL currently?
> 
> Thanks for pushing this forward

Some portion of our CMake distribtests actually uses pre-installed openssl instead of boringssl
(this is actually a requirement if you set -DgRPC_SSL_PROVIDER=package for cmake build, because boringssl doesn't provide a standalone installation).

See e.g. here:
https://github.com/grpc/grpc/blob/2b200d2313e739fa1841edf3ea86ab8532862505/test/distrib/cpp/run_distrib_test_cmake.sh#L24
https://github.com/grpc/grpc/blob/2b200d2313e739fa1841edf3ea86ab8532862505/test/distrib/cpp/run_distrib_test_cmake.bat#L30

**Comment by yashykt** [comment]
This issue is being closed because it has been marked with the label kind/question. This form is for bug reports and feature requests ONLY!
Please post questions on https://groups.google.com/g/grpc-io so that the wider community can help answer.
