### ISSUE TITLE
Add Jenkins test for Bazel based builder

### ISSUE THREAD

**Issue by ctiller** [grpc/grpc#1951]

**Comment by yang-g** [comment]
I found this may depend on #6318. Currently grpc does not seem to build on bazel out of the box. I will try a user level BUILD to see how it goes.

**Comment by yang-g** [comment]
The user level bazel build does not seem to work because we have a #include "third_party/nanopb/pb.h" somewhere and I assume when the nanopb is pulled in by the user from a git_repo in his WORKSPACE, bazel cannot resolve the include. Even if a init_submodules is added to grpc git_repo, the nanopb is pulled into third_party, but bazel still complains about not finding the header.

**Comment by yang-g** [comment]
Found #6083 for the nanopb issue.

**Comment by yang-g** [comment]
#6851 is part of the effort to resolve #6083.
