### ISSUE TITLE
csharp: philosophical - should received Metadata be frozen? (ties into perf PRs)

### ISSUE THREAD

**Issue by mgravell** [grpc/grpc#19565]
`Metadata` has popsicle immutability.

In many scenarios, `Metadata` is empty; but right now it gets allocated anyway at both client and server.

Question: should **received** `Metadata` (request headers at the server; response headers and trailers at the client) be immutable (frozen)?

Reasoning: it it were frozen, then if we get an empty table, we could just return a `static` empty+frozen `Metadata` instance. And at the client, even the `Task<Metadata>` could be singleton.

Result: no allocations at all when receiving empty metadata.

Notable change: you'd no longer be able to manipulate received `Metadata`.

Good? Bad? Other?

**Comment by jtattermusch** [comment]
Note that the received metadata is not always empty:
- most of the times the headers would contain the user-agent entry: `[Entry: key=user-agent, value=grpc-csharp/1.17.0 grpc-c/7.0.0 (osx; chttp2; gizmo)]` that's injected by C-core (and all other gRPC implementations).

Response headers and response trailers might actually be often empty as indicated. I agree that caching and empty frozen Metadata instance would save allocations, but because this is technically a breaking change, I'd postpone it until we run out of other optimization ideas (there's still plenty of possible improvements that are fully trasparent to the user). If at that point we can prove (with numbers) that the proposed change increases performance, we can consider it.
