### ISSUE TITLE
Flake: cloud_to_cloud:go:java_server:timeout_on_sleeping_server:tls

### ISSUE THREAD

**Issue by apolcyn** [grpc/grpc#19626]
Log snippet:

```
2019-07-11 19:28:16,378 FATAL: 2019/07/12 02:28:16 &{0xc0000e7680}.Recv() = _, rpc error: code = Canceled desc = stream terminated by RST_STREAM with error code: CANCEL, want error code 4
exit status 1
2019-07-11 19:28:16,378 FAILED: cloud_to_cloud:go:java_server:timeout_on_sleeping_server:tls [ret=1, pid=26901, time=2.6sec]
```

https://source.cloud.google.com/results/invocations/b44beca7-311d-4204-bc59-a3bd5d6f1da8/targets/grpc%2Fcore%2Fpull_request%2Flinux%2Fgrpc_interop_tocloud/log from pr: https://github.com/grpc/grpc/pull/19623

**Comment by dfawley** [comment]
It seems like the java server sent a RST_STREAM w/cancel when we were expecting a deadline exceeded error.  This is unlikely, but it can be caused by clock skew.  We have a workaround implemented in https://github.com/grpc/grpc-go/pull/2211 to mitigate these situations, but it's not a 100% perfect solution.

Should the test be updated to expect either behavior?

@ejona86

**Comment by ejona86** [comment]
@dfawley, the Go code is setting DEADLINE_EXCEEDED when `d.After(time.Now())`. Wouldn't that only be true if the deadline had not yet expired? Should it be inverted with a `!`?

While not a 100% perfect solution, the server's RST will be delayed by at least one full RTT, assuming the timeout sent on the wire did not truncate to 8 digits but instead rounded up[1]. To fail it requires a long enough call to accumulate enough clock drift to overcome the RTT+server and client processing time.

The timeout for this test is 1ms which would not have truncation concerns, and is too short to accumulate enough drift to compensate for the network+processing (assuming 10µs RTT, that'd require 1% drift which would be a drift of minutes per day). That only leaves clock precision and if it was poor that would be ~1µs which is still enough to hide within the RTT. So this test should not be flaky due to clocks.

1. Java does not do this, and hasn't seen flakes to my knowledge. But depending on the test that flaked, that'd be a potential fix

**Comment by dfawley** [comment]
Is java using wall clock time to determine when to send the RST_STREAM?  If so, things like ntpd could cause the time to change much faster than skew.  If not, your assessment sounds accurate.  (I just double-checked Go's time package and the context package, and it should be immune to such changes.)

You are right, the code I added is wrong.  Unfortunately this condition is extremely hard to stimulate for us, so I didn't add any tests.  Fix incoming.

**Comment by ejona86** [comment]
Java uses `System.nanoTime()`, which is similar to CLOCK_MONOTONIC. It would be impacted by rate-of-time adjustments from ntpd, but it wouldn't be impacted by jump-in-time adjustments from ntpd/ntpdate.

**Comment by vjpai** [comment]
Hi @dfawley @ejona86 any further thoughts on this flake? Is it still arising or was it fixed by Doug's "fix incoming"?

**Comment by dfawley** [comment]
The fix was submitted.  https://github.com/grpc/grpc-go/pull/2906

Is the test still flaky?
