### ISSUE TITLE
Cronet Framework Publish

### ISSUE THREAD

**Issue by drcapulet** [grpc/grpc#19697]
I'm trying to get the gRPC-Core.podspec to pass the CocoaPods linter (along with some changes to CocoaPods) but right now I'm having an issue with the `Cronet-Implementation` subspec. When the linker tries to build the final object for the framework, it can't find the implementation for the methods defined in `third_party/objective_c/Cronet/bidirectional_stream_c.h`. I noticed there used to be a dependency on the `CronetFramework` pod, but that's no longer present.

I noticed the version in `src/objective-c/CronetFramework.podspec` is at 0.0.4 and when downloading the framework, it satisfies the linker. Can y'all publish it?

**Comment by muxi** [comment]
Cronet is currently only for testing purpose in our library; we do not have a plan to publish it at this time (though Cronet framework is public as part of Chromium project). Technically you can make it work on a simulator (and not on a device) by playing with Chromium build and Cocoapods but we do not recommend it.

If you use the pod `gRPC`, it should not pull in the `Cronet-Implementation` since it is not a default subspec.

**Comment by drcapulet** [comment]
@muxi That doesn't solve the problem of getting `gRPC-Core.podspec` to pass the CocoaPods linter. What if I moved the cronet pieces into their own podspec so that the primary podspec passes?

**Comment by muxi** [comment]
Ah yes! The linter! It does look like we should have a dependency to `CronetFramework`. I am not sure why our linter did not complain about it. I can publish the v0.0.4 version.

**Comment by muxi** [comment]
It's pushed to Cocoapods

**Comment by drcapulet** [comment]
Thanks a ton @muxi !
