### ISSUE TITLE
.Net Core3.0 HTTP/2 over TLS was not negotiated on an HTTP/2-only endpoint

### ISSUE THREAD

**Issue by MishaVernik** [grpc/grpc#19707]
### What version of gRPC and what language are you using?
"Grpc.Tools" Version="1.22.0"
"Grpc.AspNetCore.Server" Version="0.1.22-pre1"
"Google.Protobuf" Version="3.8.0"
"Grpc" Version="1.22.0"
 .net core 3.0 / C#

 
### What operating system (Linux, Windows,...) and version?
 Windows 10
 
### What runtime / compiler are you using (e.g. python version or version of gcc)
 Visual Studio Professional 
 
### What did you do?
**Problem:** 
On the server side 
```
Microsoft.AspNetCore.Server.Kestrel[0]
      HTTP/2 over TLS was not negotiated on an HTTP/2-only endpoint.

```
**Server**
![Screenshot 7_21_2019 12_46_53 PM (2)](https://user-images.githubusercontent.com/41151124/61590218-b247f000-abb5-11e9-84b5-27ea5d26b518.png)
**Client**
![Home page - Tasly - Google Chrome 7_21_2019 10_52_06 PM](https://user-images.githubusercontent.com/41151124/61596957-45ab1080-ac0a-11e9-85e8-630ecf14cf85.png)

**Attempts to solve:**
1. With .cshtml
```
@page
@model IndexModel
@{
    ViewData["Title"] = "Home page";
}
<h1>Hello, gRPC!</h1>
@using Tasly.Service
@using Grpc.Core

<button class="btn btn-primary" onclick="@SayHello()">RUN</button>

<hr />

<p>@Greeting</p>

@functions {

    private string Greeting;

    async Task SayHello()
    {
        var channel = new Channel("localhost:5001", ChannelCredentials.Insecure);
        var client = new Greeter.GreeterClient(channel);

        var reply = await client.SayHelloAsync(new HelloRequest { Name = "Blazor gRPC Client" });
        Greeting = reply.Message;

        await channel.ShutdownAsync();
    }

}
```
2. The same with .razor (but it doesn't work) or I used it incorrectly. 
-----
**If you have any suggestions about how to fix, or if you need more information, please let me know.** 
 
### What did you expect to see?
 Expect to receive a response message. (e.g. "Hello ...")
 
### What did you see instead?
 Microsoft.AspNetCore.Server.Kestrel[0]
      HTTP/2 over TLS was not negotiated on an HTTP/2-only endpoint.
 ).
### Anything else we should know about your project / environment?
Please, let me know if you need any additional information! 

Best,
Misha

**Comment by JamesNK** [comment]
Your server is setup to require HTTPS. `ChannelCredentials.Insecure` on the Grpc.Core client means it won't use HTTPS.

You have three options:
1. Turn off HTTPS on the server (note: not good for security)
2. Use SslCredential with Grpc.Core client
3. Switch to using grpc-dotnet client. It will automatically use the certificates in your cert store. See tutorial [here](https://docs.microsoft.com/en-us/aspnet/core/tutorials/grpc/grpc-start?view=aspnetcore-3.0&tabs=visual-studio#create-the-grpc-client-in-a-net-console-app) (note that you should have a BaseAddress that is https instead of http)
