### ISSUE TITLE
ImportError: cannot import name 'proto_pb2' from 'grpc'  in python

### ISSUE THREAD

**Issue by mehrdad-dev** [grpc/grpc#19730]
Hi everyone  : D

**I create a proto.proto file and then create proto_pb2.py and proto_pb2_grpc,py with protoc :** 
`>> python3 -m grpc_tools.protoc -I. grpc/proto.proto  --python_out . --grpc_python_out . `

but when run the server.py it's **bug** is shown : 
```
Traceback (most recent call last):
  File "server.py", line 3, in <module>
    import proto_pb2_grpc as proto_pb2_grpc
  File "/home/mehrdad/Downloads/profile-dgraph/grpc/proto_pb2_grpc.py", line 4, in <module>
    from grpc import proto_pb2 as grpc_dot_proto__pb2
ImportError: cannot import name 'proto_pb2' from 'grpc' (/home/mehrdad/anaconda3/lib/python3.7/site-packages/grpc/__init__.py)

```

**the server.py include :** 
```
import grpc
import proto_pb2
import proto_pb2_grpc 
and ...
```

Can you help me ?!

**Comment by gnossen** [comment]
What you're seeing here is that the generated code expects that the path to the proto file mirrors the module structure of your python project. So the file path `grpc/proto.proto` generates the modules `grpc.proto_pb2` and `grpc.proto_pb2_grpc`. It appears that `grpc` is not actually a module in your project, and so the import is failing.

**Comment by XuanYang-cn** [comment]
It went wrong because your own module `grpc`'s name  is identical to thridparty `grpc` , and your own grpc directory seems not having `__init__.py`, so python try to import this module from `grpc` package(in **site-packages** you downloaded via pip)

       from grpc import proto_pb2 as grpc_dot_proto__pb2
    ImportError: cannot import name 'proto_pb2' from 'grpc' 
    (/home/mehrdad/anaconda3/lib/python3.7/site-packages/grpc/__init__.py)

#### Solu 1
**Avoid naming your own package name the same as thrid party libraries**

  1. You can change your directory `grpc/proto.proto` to `grpc_gen/proto.proto`, and don't forget to add `__init__.py` in `grpc_gen` to make it a package

  2.  regenerate

    python3 -m grpc_tools.protoc -I. grpc_gen/proto.proto --python_out . --grpc_python_out .

#### Solu2
If your `server.py` is in the same directorys with `proto_pb2.py` and `proto_pb2_grpc.py`,  you can generate inside the directory `grpc`

    $ cd grpc
    $ python3 -m grpc_tools.protoc -I. ./proto.proto --python_out . --grpc_python_out .
