### ISSUE TITLE
Name resolver support for C#/Android missing

### ISSUE THREAD

**Issue by Falco20019** [grpc/grpc#19874]
### What version of gRPC and what language are you using?
GRPC 1.19.0 C# from NuGet package
 
### What operating system (Linux, Windows,...) and version?
Android 7.0
 
### What runtime / compiler are you using (e.g. python version or version of gcc)
* C# compiler from within VS2019
* Xamarin.Android 9.5
 
### What did you do?
Access dns://localhost:8001/my-service
 
### What did you expect to see?
Resolve the DNS through c-ares.
 
### What did you see instead?
c-ares on Android is disabled as of #18046
 
### Anything else we should know about your project / environment?
This is a follow-up for #11879

We still need an option to resolve names with C#. We are still not able to write our own name resolver. For our .NET Core application on Windows, we just use c-ares and GRPCLB to resolve the names to the dynamic endpoint. On Android, we can't resolve the name right now at all since we are still not allowed to configure a specific DNS server on the devices in the customers infrastructure.

Are there any news on adding custom name resolvers to C-Core from C#?

**Comment by gnossen** [comment]
CC @lidizheng

**Comment by apolcyn** [comment]
cc @markdroth about the name resolver core API

FWIW the use of c-ares on Android was paused due to the issue brought up and fixed in https://github.com/c-ares/c-ares/pull/148, which hasn't made it into a c-ares release tag yet (last I checked). c-ares on Android is currently prevented at compile time, though for experimental purposes, I could imagine that disabling happen at runtime, with switch to turn it on.

**Comment by Falco20019** [comment]
What’s the state here?

**Comment by yashykt** [comment]
C-Core itself has not exposed a proper stable API for adding name resolvers. (Though none of C Core is actually stable API.) C-Core does have ways to add resolvers to it though. Please refer to fake_resolver.h and fake_resolver.cc for details on how one might go about implementing their own resolver. Though, it probably won't be an ideal solution since you would probably need to fork your own copy of gRPC.

It also looks like the root issue here is c-ares support for those platforms. It looks like fixing that hasn't seen much attention. Hence, I am going to mark this as disposition/help wanted for fixing c-ares support for those platforms, though I'm not sure if there's anything gRPC specific we can do here. I am also going to close this, since this has gotten stale. This can be re-opened if someone decides to implement this.
