### ISSUE TITLE
Eliminate as much as possible Python API's manual object lifecycle management

### ISSUE THREAD

**Issue by nathanielmanistaatgoogle** [grpc/grpc#2008]
Currently the Python API has a lot of context management and "start"/"stop" pairing directly corresponding to the gRPC C Core's many "X object must be destroy before Y time" semantics.

I think I smell an opportunity to eliminate a lot of that manual object lifecycle management, but I'd have to know a lot more about Python's garbage collection semantics and then turn that knowledge into well-formed and plausible feature requests against the gRPC C Core API.

If this happens at all it will happen in a post-beta time frame.

**Comment by soltanmm** [comment]
IIRC, Python's GC doesn't actually 'collect' anything so much as breaks reference cycles at arbitrary locations and lets the `__del__` functions run from there. That said, there's no reason for us to necessarily have reference cycles, because the dependencies are *basically* acyclic in the C core, with temporary 'sibling' dependencies according to events (which can correspondingly be tracked by tags).

I don't think we actually need to make any feature requests against the gRPC C core API to handle this. We'd just need to entirely refactor `grpc._adapter` and especially make more sophisticated our tagging mechanism.

**Comment by hsaliak** [comment]
@soltanmm what's the latest on this issue?

**Comment by soltanmm** [comment]
This is addressed as far as the API is concerned; we don't *require* explicit closing anymore.
