### ISSUE TITLE
Generated Python code doesn't seem to be package-qualified

### ISSUE THREAD

**Issue by nathanielmanistaatgoogle** [grpc/grpc#2010]
It looks like a .proto file's having a "package" directive has no effect on generated code. It should probably have the effect of placing the generated Python module inside a package hierarchy created from the .proto file's "package" directive.

I'm not sure and we'll probably want to work with the proto team on this. @haberman, what am I getting wrong here? Given that we've only written a protoc plugin, is this behavior even under our control? Are we doing something simple and silly like forgetting to pass a flag?

Exit condition for this bug: given "package grpc.testing" in python_plugin_test's test.proto file, python_plugin_test should have "from grpc.testing import test_pb2" statements where it currently has "import test_pb2" statements.

**Comment by haberman** [comment]
It's true that "package" does not affect the module hierarchy in Python. It is surprising, but when you fully work through all of the implications, you realize that this behavior is the only behavior that will actually work.

The necessity of this behavior derives from these two inherited constraints:

- Python requires a 1:1 correspondence between module names and filenames.
- Protocol Buffer codegen requires a 1:1 correspondence between `.proto` filenames and generated filenames (ie. `_pb2.py`).

If we respected "package", imagine that we had these two .proto files:

```protobuf
// foo/a.proto

package mypackage;

message M1 {}
```

```protobuf
// bar/a.proto

package mypackage;

message M2 {}
```

In the status quo, this will produce two output files `foo/a_pb2.py` and `bar/a_pb2.py`.

If we used the package name instead of the directory name, both of these files would try to generate `mypackage/a_pb2.py`!

The `package` keyword can only be respected in languages that let source files declare symbols in any namespace, regardless of the filename (eg. C++, Ruby, JavaScript, etc). In these cases, a file called `foo/a.h` can declare a symbol in the `mypackage` namespace.

**Comment by soltanmm** [comment]
IIRC, there was some thought towards using insertion points in `*_pb2.py` files to allow multiple files to 'generate' `mypackage/a_pb2.py`, but that would require insertion points being stabilized among other things. We're currently using insertion points for our generated GRPC code, though, and haven't yet been slapped on the wrist.

There was also some pressure from the other language subteams regarding consistency, wherein everyone else appears to be generating entirely separate files for GRPC code rather than using insertion points in the usual `protoc`-generated files.

**Comment by nathanielmanistaatgoogle** [comment]
@tbetbetbe, would you read over @haberman's response on this issue? Does it forecast complication for the versioning behavior we discussed at the Tuesday morning meeting?

**Comment by soltanmm** [comment]
@haberman Would it be reasonable to enforce in the `protoc` Python plugin behavior that requires the package, if specified, to be the same as the paths along which the `.proto` files exist?

**Comment by haberman** [comment]
I don't think the Python generator could enforce this unless all generators did, and I think it's too late to try enforcing any kind of rule like this.

**Comment by nathanielmanistaatgoogle** [comment]
Despite being the individual who opened this issue... I'm not actually sure that there's a problem here. I certainly am not aware of a Beta-required need being tracked here. Do you agree @tbetbetbe?

**Comment by tbetbetbe** [comment]
I agree, I think we can close this.
