### ISSUE TITLE
How to Use C++ Callback in Stream Mode

### ISSUE THREAD

**Issue by ml232528** [grpc/grpc#20239]
### What version of gRPC and what language are you using?
v1.23, C++

### What operating system (Linux, Windows,...) and version?
N/A

### What runtime / compiler are you using (e.g. python version or version of gcc)
N/A

### What did you do?
In the proto file, I add the method：
RPC SubscribeCurrentLineChange (MsgNull) returns (stream CommonReply);

### What did you expect to see?
In ExperimentalWithCallbackMethod_SubscribeCurrentLineChange, the form of SubscribeCurrentLineChange function is as follows:
virtual void SubscribeCurrentLineChange（::grpc::ServerContext* context, const MsgNull* request,  ::grpc::ServerWriter<CommonReply>*  response, ::grpc::experimental::ServerCallbackRpcController* controller）

### What did you see instead?
A function without client parameters：
 virtual ::grpc::experimental::ServerWriteReactor< ::PosSetSever::MsgNull, ::PosSetSever::CommonReply>* SubscribeCurrentLineChange()
How can I get the client parameters and overload the function。

### Anything else we should know about your project / environment?
N/A

**Comment by sheenaqotj** [comment]
virtual void SubscribeCurrentLineChange（::grpc::ServerContext* context, const MsgNull* request, ::grpc::ServerWriter* response, ::grpc::experimental::ServerCallbackRpcController* controller）

is what it would look like if you were doing a unary call (changing soon, BTW).

For that, you need to take out the "stream" in your proto file, so change to:
RPC SubscribeCurrentLineChange (MsgNull) returns (CommonReply);

Otherwise, if you want to implement server streaming, you're going to get the signature you see and need to define a reactor that inherits from the ServerWriteReactor you see, then override the methods you care about.
