### ISSUE TITLE
C#: Generate client interface

### ISSUE THREAD

**Issue by bluetentacle** [grpc/grpc#20373]
Currently, the grpc tool chain generates a client class but not an interface, such as:

```csharp
public partial class GreeterClient : grpc::ClientBase<GreeterClient>
```

This makes the generated code very unfriendly to dependency injection and mocking. In a typical application that makes good use of dependency injection, you'd expect to be able to inject an `IGreeterClient` into a class that needs to make the RPC call:

```csharp
public class MyClass
{
  public MyClass(IGreeterClient greeterClient)
  {
      ...
  }
}
```

...so that in unit tests, IGreeterClient can easily be replaced with a mock.

I'd like to see grpc-dotnet generate the interface which is implemented my the class. To carry on the GreeterClient example:

```csharp
public interface IGreeterClient
{
  grpc::AsyncServerStreamingCall<global::server.HelloReply> SayHello(global::server.HelloRequest request, grpc::CallOptions options);
}

public partial class GreeterClient : grpc::ClientBase<GreeterClient>, IGreeterClient
{
  ...
}
```

Is such a feature already available, or does it need to be implemented?

**Comment by jtattermusch** [comment]
We intentionally generate an abstract class instead of an interface to avoid breaking changes when new methods are added to the .proto file. See the reasoning https://github.com/grpc/grpc/issues/5416.

C# 8 now has default implementation for interfaces, but that's a very new feature so it's going to take a while before we can rely on it. We can revisit in the future but now it's way too early.
