### ISSUE TITLE
Grpc.Tools fails when used in a .NET Core 3.0 WPF project

### ISSUE THREAD

**Issue by JamesNK** [grpc/grpc#20402]
Copied from https://github.com/grpc/grpc-dotnet/issues/488.

Moved here because the issue is inside `Grpc.Tools`. Code generation is not working correctly when used in a .NET Core 3.0 WPF project. WPF projects have unusual build steps (I think it involves multiple compilations), and that is causing `Grpc.Tools` to fail.

---

### What version of gRPC and what language are you using?

- C#

I use following packages.
- Google.Protobuf 3.9.1
- Grpc.Net.Client 0.1.22-pre3
- Grpc.Tools 2.23.0

### What operating system (Linux, Windows,...) and version?

- Windows 10

### What runtime / compiler are you using (e.g. python version or version of gcc)

- WPF on .NET Core 3.0 (.NET Core 3.0.100-preview8-013656)

### What did you do?

I just create a simple `.proto` file, and generate C# code.
When use the generated code on WPF on .NET Core project, then compile errors is occurred.
On Console App on .NET Core project, there is no compile error.

### What did you expect to see?

No compile error.

### What did you see instead?

Following message:

```
> dotnet build
Microsoft (R) Build Engine version 16.3.0-preview-19377-01+dd8019d9e for .NET Core
Copyright (C) Microsoft Corporation. All rights reserved.

  Restore completed in 51.27 ms for C:\Users\k_ota\source\repos\GrpcErrorRepro\WpfApp\WpfApp.csproj.
  You are using a preview version of .NET Core. See: https://aka.ms/dotnet-core-preview
MainWindow.xaml.cs(35,55): error CS0246: The type or namespace name 'MyGrpcServices' could not be found (are you missing a using directive or an assembly reference?) [C:\Users\k_ota\source\repos\GrpcErrorRepro\WpfApp\WpfApp_v4a1l2r4_wpftmp.csproj]
MainWindow.xaml.cs(36,47): error CS0246: The type or namespace name 'MyGrpcServices' could not be found (are you missing a using directive or an assembly reBuild FAILED.

MainWindow.xaml.cs(35,55): error CS0246: The type or namespace name 'MyGrpcServices' could not be found (are you missing a using directive or an assembly reference?) [C:\Users\k_ota\source\repos\GrpcErrorRepro\WpfApp\WpfApp_v4a1l2r4_wpftmp.csproj]
MainWindow.xaml.cs(36,47): error CS0246: The type or namespace name 'MyGrpcServices' could not be found (are you missing a using directive or an assembly reference?) [C:\Users\k_ota\source\repos\GrpcErrorRepro\WpfApp\WpfApp_v4a1l2r4_wpftmp.csproj]
    0 Warning(s)
    2 Error(s)
```

### Anything else we should know about your project / environment?

This is a sample project:
https://github.com/runceel/GrpcErrorRepro

**Comment by JamesNK** [comment]
FYI, if you update all the packages to the latest versions then you'll need to update the gRPC client code because of changes since the preview.

Update it to the following to avoid a compilation error:

```csharp
public async void HelloWorldButton_Click(object sender, RoutedEventArgs args)
{
    var c = Grpc.Net.Client.GrpcChannel.ForAddress("https://example.com");
    var s = new MyGrpcServices.HelloWorldService.HelloWorldServiceClient(c);
    var r = await s.SayHelloAsync(new MyGrpcServices.HelloWorldRequest { Name = "xxx" });
    MessageBox.Show(r.Message);
}
```

**Comment by jtattermusch** [comment]
CC @kkm000

**Comment by JamesNK** [comment]
I have talked with the WPF folks about this issue and there is no way to fix it in `Grpc.Tooling`. The fix has to be made inside the WPF build process.

**Workaround:**

Move code generation with `proto` files to a regular class library. You can then reference the class library from the WPF app and use the generated types inside it.

**Comment by kkm000** [comment]
@itshemant09, @ghord, /cc @jtattermusch, my apologies again for keeping my issues open for such long a time (not this one--my luck spared me this time--but there is limited supply of this rare stuff in the Universe). But being a senior SWE+scientist+IT planner+everything else in a startup-size company is really a feat to pull. I understand that ever postponed promises do not really cut it, real fixed do, and I am doing my best to carve off a week to work on my piling gRPC issues uninterrupted. I do remember of them (holy guacamole, and it does not help that I need to finish my taxes by October 15, too--all I had time for back in April is file for an extension!). We are dogfooding NuGet packages on the C# client size, but our C++ servers have not been upgraded since gRPC 1.6.7 (and I think that was the only upgrade since gRPC was in alpha... :))

I am so glad we are being helped by @JunTaoLuo and other guys from MS--thank you folk for your attention.

This is a note mostly to confirm I'm still around, read every new issue, and do feel responsible for them.
