### ISSUE TITLE
FLAKE: cpp_macos_dbg_native.bins/dbg/bm_chttp2_transport --benchmark_filter=BM_StreamCreateSendInitialMetadataDestroy<RepresentativeClientInitialMetadata>$  GRPC_POLL_STRATEGY=poll

### ISSUE THREAD

**Issue by markdroth** [grpc/grpc#20421]
https://source.cloud.google.com/results/invocations/bbca8bb1-4f47-4c61-9687-169e1a79f966/targets/github%2Fgrpc%2Frun_tests%2Fcpp_macos_dbg_native/tests

```
D0930 14:29:08.202689000 140735962575744 ev_posix.cc:174]              Using polling engine: poll
D0930 14:29:08.204061000 140735962575744 dns_resolver_ares.cc:485]     Using ares dns resolver
2019-09-30 14:29:08
Running bins/dbg/bm_chttp2_transport
Run on (8 X 2473 MHz CPU s)
CPU Caches:
  L1 Data 32K (x8)
  L1 Instruction 32K (x8)
  L2 Unified 262K (x8)
  L3 Unified 6291K (x8)
Load Average: 6.32, 6.16, 5.51
***WARNING*** Library was built as DEBUG. Timings may be affected.
third_party/benchmark/src/benchmark_runner.cc:120: RunInThread: Check `st.iterations() >= st.max_iterations' failed. Benchmark returned before State::KeepRunning() returned false!
```

**Comment by yashykt** [comment]
All of the failures are in bm_chttp2_transport. The failure is due to an issue with how the benchmark is written. The issue is that we were exiting the benchmark before the work was actually done. This was happening because the closures were getting scheduled on the executor thread, which meant that the main thread could exit. The fix was to add a simple cond var wait to not exit till the benchmark work is done.
