### ISSUE TITLE
Skip SSL Verification?

### ISSUE THREAD

**Issue by donpdonp** [grpc/grpc#20430]
I'm re-implementing a Go app (in rust) that uses grpc-go which uses the tls.Config{InsecureSkipVerify: true} option in the Go TLS library.

example usage:
https://github.com/grpc/grpc-go/blob/4abb3622b0fb97df222670b189869b44d0c2454d/credentials/credentials_test.go#L178

I'm using the rust wrapper for the C implementation for gRPC and its come down to the SslCredentialsOptions. Is there a way to get the same Skip-Verify behavior from the C library? I'm trying to connect to a gRPC server that is using TLS with a self-signed cert.

**Comment by jiangtaoli2016** [comment]
There are two options

1. If you want skip verify because the target name that client connects to is different from hostname in the server TLS certificate, you can use  GRPC_SSL_TARGET_NAME_OVERRIDE_ARG.

2. You can use grpc_tls_spiffe_credentials_create(). It will create SPIFFE style channel credentials, which will skip hostname verification by default, but you can implement your own customized server authorization callback to verify peer. We are working on C++ wrapper now. https://github.com/grpc/grpc/pull/19778

What is the use case that you want to skip verification?

**Comment by jiangtaoli2016** [comment]
@yihuazhang @ZhenLian FYI.

**Comment by donpdonp** [comment]
To allow connection to a self-signed cert means skipping the entire certificate validation step and continuing with the ssl handshake. The hostname or SNI verification is usually for http connections so I dont think that authorization callback will help. I'm working on an open source client for the storj project and the public endpoint is tls with a selfsigned cert.

**Comment by yihuazhang** [comment]
A similar feature is requested in https://github.com/grpc/grpc/pull/20530

**Comment by yashykt** [comment]
The feature request seems to have been fulfilled in #21423.
