### ISSUE TITLE
error MSB4062: The "Grpc.Tools.ProtoToolsPlatform" task could not be loaded from the assembly

### ISSUE THREAD

**Issue by khteh** [grpc/grpc#20501]
https://github.com/grpc/grpc-dotnet/issues/561

### What version of gRPC and what language are you using?
GRPC 2.23.0, ASP.Net Core 3.0 C#.

### What operating system (Linux, Windows,...) and version?
Ubuntu 19.04

### What did you do?
`dotnet run --project src/myproject`
If possible, provide a recipe for reproducing the error. Try being specific and include code snippets if helpful.

### What did you see instead?
```
/home/khteh/.nuget/packages/grpc.tools/2.23.0/build/_protobuf/Google.Protobuf.Tools.targets(64,5): error MSB4062: The "Grpc.Tools.ProtoToolsPlatform" task could not be loaded from the assembly /home/khteh/.nuget/packages/grpc.tools/2.23.0/build/_protobuf/netstandard1.3/Protobuf.MSBuild.dll. Assembly with same name is already loaded Confirm that the <UsingTask> declaration is correct, that the assembly and all its dependencies are available, and that the task contains a public class that implements Microsoft.Build.Framework.ITask. [/usr/src/AspNetCoreApiStarter/src/Web.Api.Core/Web.Api.Core.csproj]

```
Make sure you include information that can help us debug (full error message, exception listing, stack trace, logs).

See [TROUBLESHOOTING.md](https://github.com/grpc/grpc/blob/master/TROUBLESHOOTING.md) for how to diagnose problems better.

**Comment by khteh** [comment]
Found out that this happens when there are orphaned `dotnet` processes running in the background. `killall dotnet` and it disappears!

**Comment by thefringeninja** [comment]
I noticed this happened to me when I had my ide open and I upgrading my version of the tools.

**Comment by jtattermusch** [comment]
Can this be closed then?

**Comment by khteh** [comment]
What's the reason to close it?

**Comment by jtattermusch** [comment]
According to https://github.com/grpc/grpc/issues/20501#issuecomment-544397682 it doesn't look like it's a grpc issue.

**Comment by khteh** [comment]
Then where does "error MSB4062" belong to? Who is supposed to fix the "error"?

**Comment by thefringeninja** [comment]
dotnet/cli#9458

This is a consequence of these optimizations. I don't think there is much you can do other than kill any dotnet processes that are hanging around. The canonical way to do this is `dotnet build-server shutdown`.

**Comment by enif-lee** [comment]
For someone reach in here, I leave this comment. 


## Why this problem is made.
1. [.NET Core have 3 persistent process to optimize there build time.](https://github.com/dotnet/cli/issues/9458#issuecomment-396324918)

2. [MsBuild does not allow tasks with same assembly name but different version yet.](https://github.com/Microsoft/msbuild/issues/3572#issuecomment-409705624)
    - [Each MsBuild task does not have AssemblyLoadContext yet.](https://github.com/microsoft/msbuild/issues/1754)

3. You have different versions of grpc references by multiple project.

So, MsBuild One Persistent host try to load `Protobuf.MSBuild.dll.` from the different versions assembly, But this is not allow currently. Because, Each MsBuild Task does not have own AssemblyLoadContext(In my think, msbuild might share single context to build for all projects in solution).

## How to resolve it.

All Grpc related references should be have same version (particular `Grpc.AspNetCore` and `Grpc.Tools`) in solution.
