### ISSUE TITLE
IL2CPP crashes randomly when using ConcurrentDictionary

### ISSUE THREAD

**Issue by hefesto84** [grpc/grpc#20553]
### What version of gRPC and what language are you using?
1.16 for c#

### What operating system (Linux, Windows,...) and version?
Android / iOS (any version)

### What runtime / compiler are you using (e.g. python version or version of gcc)
il2cpp

### What did you do?
If possible, provide a recipe for reproducing the error. Try being specific and include code snippets if helpful.

### What did you expect to see?
Random crashes when an application compiled with IL2CPP for Unity is using GRPC.

### What did you see instead?
We are getting random crashes and we suspect that in the creation of the Channel in c#, (where ConcurrentDictionary is being used) is the root cause. 

This is an example of the stack trace and some users has fixed the issue removing all references and uses of ConcurrentDictionary. Is it possible to change it or make it optionable?

(Link)[https://forum.unity.com/threads/il2cpp-build-high-crash-rate-on-il2cpp-os-fastmutex-lock.755597/#post-5049437]

Regards,

Dani

See [TROUBLESHOOTING.md](https://github.com/grpc/grpc/blob/master/TROUBLESHOOTING.md) for how to diagnose problems better.

**Comment by jtattermusch** [comment]
Looks like the real issue is Unity/il2cpp having problems with ConcurrentDictionary support (which is part of the base class library, so it really should work just fine)?

Also, Grpc c# hasn't been using ConcurrentDictionary starting from release 1.8.x (which is 2 years old now).
See the PR that remove ConcurrentDictionary 2 years ago: https://github.com/grpc/grpc/pull/13439
I'd highly recommend upgrading to the latest version of gRPC.
