### ISSUE TITLE
Expose grpc_byte_buffer so that Flatbuffers can be used again

### ISSUE THREAD

**Issue by sab24** [grpc/grpc#20594]
Flatbuffers uses grpc_byte_buffer to write its data, but this is no longer exposed when grpc started using grpc::ByteBuffer. 

### Describe the solution you'd like
Add a public method to access this grpc_byte_buffer, which is a private variable of grpc::ByteBuffer.

### Describe alternatives you've considered
Patching the code with pr #17603

**Comment by tudor** [comment]
We'd love this as well. We're using generic methods and a custom serialization format for our data messages (performance critical, and going from our internal representation to protobuf to wire is significantly slow), but `grpc::ByteBuffer` doesn't have any of the useful `grpc_slice_buffer_*` methods :)

(We used some horrible hack to expose the `grpc_byte_buffer` member)

**Comment by yashykt** [comment]
It is unlikely that grpc_byte_buffer will be exposed as is since it is part of the Core API which is unstable and we don't want to expose something unstable through the C++ API. This is also true for grpc_slice_buffer.

Instead, if there is some particular functionality that you want available, we might be able to wrap that in the C++ API.

**Comment by tudor** [comment]
We'd love zero-copy access to the slices (not `ByteBuffer::Dump`), the ability to append individual slices to the buffer one by one (`grpc_slice_buffer_add`) and the ability to trim the buffer's head (`grpc_slice_buffer_take_first`, `grpc_slice_sub_no_ref`).

**Comment by aardappel** [comment]
Not only was this working fine before, it seems to me that being able to implement zero-copy protocols is an important feature for gRPC, so I am not sure why it isn't possible to expose this in the API.

For reference: https://grpc.io/blog/grpc-flatbuffers/ :)

**Comment by tudor** [comment]
I don't want to publicly admit to the horrible hacks that we've had to do to actually get this working at Rockset, but it looks like this:

```
// grpc declares grpc::internal::GrpcByteBufferPeer as a friend, but only
// defines it in a test. We'll abuse this for our purposes.
namespace grpc::internal {
class GrpcByteBufferPeer {
  public:
    static void setBuffer(grpc::ByteBuffer* dest, grpc_byte_buffer* p) {
        dest->set_buffer(p);
    }
    static grpc_byte_buffer** getBufferPtr(grpc::ByteBuffer* buf) {
        return buf->c_buffer_ptr();
    }
};
}  // namespace grpc::internal
```

**Comment by yashykt** [comment]
@vjpai ping?

**Comment by adityajaltade** [comment]
I would consider this to be an essential feature where flatbuffers + grpc work with zero copies and is something that led us to using this combo in the first place. To not be able to upgrade without breaking this support is currently hindering us. Would love to see some movement on this.

**Comment by adityajaltade** [comment]
@vjpai @yashykt Any update on this?
This really needs to be fixed in a clean way. Please take a look at https://github.com/google/flatbuffers/pull/6338 which may be checked-in to flatbuffers. The latest comments there mention similar concerns.
Today the grpc+flatbuffers integration is very fragile and in most cases it is not possible to mix and match (even reasonably) the versions of grpc and flatbuffers because it requires a hack and rebuild to get them working.

Can this please be bumped up in priority?
As it stands, this link: https://grpc.io/blog/grpc-flatbuffers/ is no longer accurate and is misleading.
CC'ing @aardappel here in case there are any ideas about how the grpc and the flatbuffers team may collaborate.

This seems like something that would be extremely tough to fix by the community as it involves two code-bases that need to be in agreement.

**Comment by aardappel** [comment]
I pinged someone internally again, let's see.

**Comment by veblush** [comment]
I think this is now addressed by https://github.com/grpc/grpc/pull/26014/files so closing it. Please reopen this if it needs more work.
