### ISSUE TITLE
Build Error: Waring level 4 and Warning treated as error fails to compile

### ISSUE THREAD

**Issue by noahdav** [grpc/grpc#20633]
After running the protoc.exe which was built from source using the Ninja build instructions at https://github.com/grpc/grpc/blob/master/BUILDING.md the generated files are unable to compile with visual studio 2017 compiler when setting Warning level to 4 (/W4) and well as Treat warning as error (/WX) option enabled.

### What version of gRPC and what language are you using?
I am using master from https://github.com/grpc/grpc.git at commit 

### What operating system (Linux, Windows,...) and version?
Windows

### What runtime / compiler are you using (e.g. python version or version of gcc)
Compiling with MSVC 2017 + ninja 

### What did you do?
protoc.exe -I ..\proto --grpc_out=output --plugin=protoc-gen-grpc=grpc_cpp_plugin.exe test.proto WorkingDirectory="src\grpc\.build"

protoc.exe -I ..\proto --cpp_out=output test.proto WorkingDirectory="src\grpc\.build"

### What did you expect to see?
Compile cleanly in MSVC at error level 4 and treat warnings as errors turned on.

### What did you see instead?
Compilation errors since treat warnings errors as and warning level 4 are specified.

**Comment by noahdav** [comment]
https://github.com/grpc/grpc/issues/10725 looks similar but never resolved

**Comment by pweyzen** [comment]
I would love to see these warnings resolved too.  It's super messy code that's being generated, and when you actually look at the code, I start seeing items where this mixed incompatible types -- and though no actual bug is happening,  it's still a warning.   Warnings should be eradicated!

Or at least stick some directives into your generated code to suppress the warnings you create.
https://docs.microsoft.com/en-us/cpp/preprocessor/warning?view=vs-2019
