### ISSUE TITLE
Grpc.Tools: using ProtoRoot property messes up Visual Studio

### ISSUE THREAD

**Issue by sudsy** [grpc/grpc#20637]
### What version of gRPC and what language are you using?
GRPC.Tools 2.24
using Build Integration specified at `https://github.com/grpc/grpc/blob/master/src/csharp/BUILD-INTEGRATION.md` and #13207

### What operating system (Linux, Windows,...) and version?

Windows 10 Pro 18362.356

### What runtime / compiler are you using (e.g. python version or version of gcc)

GRPC.Tools integrated compiler

### What did you do?

I have created a repo that demonstrates the issue https://github.com/sudsy/GRPC.Tools.Issue

If you open the solution in Visual Studio 2019 you will see that the project ConsoleApp1 imports a proto file from the Messages project. To make this work, ProtoRoot=".." was added to ConsoleApp1.csproj

Adding ProtoRoot=".." requires the include path to be specified relative to the ProtoRoot however visual studio then shows a folder marked with a cross within the Consoleapp1 project

### What did you expect to see?

I did not expect to see the phantom folder within ConsoleApp1

### What did you see instead?

I saw the phantom folder with a cross

**Comment by jtattermusch** [comment]
@kkm000  any ideas?

**Comment by jtattermusch** [comment]
@sudsy  I cloned the repo you provided and I'm also seeing the "ConsoleApp1" phantom folder with a cross. Nevertheless
- building the solution still works just fine
- the "phantom folder" can easily be removed by setting `Link` attribute on your Protobuf item: `<Protobuf Include="ConsoleApp1/Protos.proto" Link="Protos.proto" ProtoRoot=".." />`

The structure of the projects and protos in your example is actually quite odd so I'm not really all that surprised that VS has trouble handling that layout, but since setting the `Link` attribute fixes this (rather cosmetic) problem, I'm going to close as "working as intended".
