### ISSUE TITLE
C# .Net Framework client not connecting .Net Core server

### ISSUE THREAD

**Issue by LoicBovo** [grpc/grpc#20696]
### What version of gRPC and what language are you using?
Language C#
Grpc 2.23

### What operating system (Linux, Windows,...) and version?
Windows 10 Enterprise - 1903

### What runtime / compiler are you using (e.g. python version or version of gcc)
C# .Net Core 3.0 for the server
C# .Net Framework 4.7.2 / 4.8 for the client

### What did you do?
If possible, provide a recipe for reproducing the error. Try being specific and include code snippets if helpful.

### What did you expect to see?
I was assuming the .NET Framework client would have been able to connect to the .net core server.
I manage to connect a .net core client but not .net framework client to the .net core server

### What did you see instead?
The .net Framework clients refuses to connect giving me a stream removed error. 
My goal is to connect a mix of .net framework client (v4.7.2 or 4.8) and .net core client (v3.0) to a .net core server (v3.0).

As I stated I managed to connect the .net core clients but not the .net framework. Reading on the gRPC forum I understand it should be possible... is it ? 

Tanks a lot for the help. 

See [TROUBLESHOOTING.md](https://github.com/grpc/grpc/blob/master/TROUBLESHOOTING.md) for how to diagnose problems better.

**Comment by jtattermusch** [comment]
Please include some logs and/or code examples - otherwise we cannot help.

And yes, you're right that Grpc.Core client should be able to connect to grpc-dotnet server (many others have tested that and we do have continuous tests for that and they're passing - so it's more likely that you've missed something).

have you tried https://docs.microsoft.com/en-us/aspnet/core/grpc/troubleshoot?view=aspnetcore-3.0  or https://github.com/grpc/grpc/blob/master/TROUBLESHOOTING.md

**Comment by jtattermusch** [comment]
Closing for now, I can reopen if there's more input.
