### ISSUE TITLE
possible memory leak in async c++ client.

### ISSUE THREAD

**Issue by ppLorins** [grpc/grpc#20692]
### What version of gRPC and what language are you using?
grpc 1.21.x     c++

### What operating system (Linux, Windows,...) and version?
Windows 10pro 1903

### What runtime / compiler are you using (e.g. python version or version of gcc)
Microsoft (R) C/C++ Optimizing Compiler Version 19.00.24215.1 for x86

### What did you do?
I build a broadcasting model where A is the proxy server(asynchronous) accepting requests from clients, and broadcast requests to B & C where B & C are simple ping-pong server:

                  Client
                      |
                     A
                   /    \
                 /       \
                B        C

### What did you expect to see?
Memory usage of A is reasonable.

### What did you see instead?
Memory usage of A keeps increasing about 5m~9m for each 40k requests. 

The A 's code is [here](https://gist.github.com/ppLorins/942874631457a7f982411ea0f2b60048).

### Anything else we should know about your project / environment?
If I comment out the broadcasting logic, it recovers to normal level. So there must be something wrong with the broadcasting logic, but I cannot find anything abnormal.

**Comment by yang-g** [comment]
Do you have a memory profile or something to show what is being used?

I think there is an error in https://gist.github.com/ppLorins/942874631457a7f982411ea0f2b60048#file-proxy_adventurer-cc-L238 as well, since at this point the server call data may have already been destroyed.

**Comment by ppLorins** [comment]
I did the experiment again and got some snapshots, visual studio cannot export the result as excels or something, so there is only snapshots...

This is the memory gain after did sending 40k requests to the serverA:
![image](https://user-images.githubusercontent.com/5534049/67314956-30f75500-f538-11e9-9c78-e1da07917688.png)

This is the memory gain details in vs diagnostic tool which is informative :
![image](https://user-images.githubusercontent.com/5534049/67315009-479dac00-f538-11e9-92e4-3e11dece053d.png)

This is the result of expanding "ucrtbased.dll!_CrtMemBolckHeader":
![image](https://user-images.githubusercontent.com/5534049/67315073-6734d480-f538-11e9-90bc-9341882d9027.png)


Yes. There is the problem that call data may have already been destroyed, I'll fix it later.  But it rarely happened and has no effect on our problem.

**Comment by ppLorins** [comment]
Forget the grpc_1.8.x_svr.... , it's actually 1.21.x.

**Comment by yang-g** [comment]
I am not sure there is a problem here.
I can imagine this is caused by some memory allocator implementation details like holding the released memory in a pool rather than returning back to the system.
Also grpc may have some global cache of commonly used strings etc which may be the source of last picture. (Note it is from registering a call on a channel).

A better way to test the memory usage might be either giving it a larger flow of traffic and compare the peak memory usage and after the peak. Or you can give the server a constant flow of traffic to see the memory does not go up unbounded.

**Comment by ppLorins** [comment]
I'll try it later.

**Comment by ppLorins** [comment]
@yang-g  

I've tried both the methods, here are the result:

#### Method1

 I gave a large flow to the server, and the memory usage is like this:

![image](https://user-images.githubusercontent.com/5534049/67693687-13653800-f9dd-11e9-98e5-acdde0ecd336.png)

4.9MB (before receiving large flow requests)
187.7MB(peak)
17.4MB(after memory stable)

#### Method2
I continuously give a moderate traffic flow to the server, observed it's memory usage continue increasing, finally hit the 2GB memory usage limit for a 32-bit program on window.  I think this can demonstrate that it'll go up unbounded, and it's still unreasonable to use 2GB memory even if it's not.

Anyone who even report this before?  If this is a bug, I can hardly believe that I'm the first one who encountered this.

**Comment by chanilino** [comment]
I have the same issue with async client on linux, the memory go up until 16 GB RAM.

**Comment by wnch** [comment]
I have the same issue with async client on linux, but not issue with sync client on linux.

**Comment by yashykt** [comment]
I think what you are interested in here is the ResourceQuota which allows you to set the amount of memory gRPC uses for a channel or a server.
Please look at SetResourceQuota() https://github.com/grpc/grpc/blob/cc4017255d3e1685344e6ef853f38ed7a733b3e1/include/grpcpp/support/channel_arguments_impl.h#L90

Also, the nature of the issue seems to be a question that the wider community would have probably answered faster. Please redirect questions to https://groups.google.com/g/grpc-io
