### ISSUE TITLE
Make Empty in gRPC calls from .NET client an optional argument

### ISSUE THREAD

**Issue by JamesNK** [grpc/grpc#20823]
Today you have to include Empty when making gRPC calls with a codegened client:

```csharp
var response = await client.SayHelloAsync(new Empty());
```

In codegen you could detect when Empty is the argument and make it [optional](https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/classes-and-structs/named-and-optional-arguments). Passing it in could then be skipped, in which case codegen would handle creating it in the method. The final result is a nicer client experience:

```csharp
var response = await client.SayHelloAsync();
```

@jtattermusch @davidfowl

**Comment by jtattermusch** [comment]
I'm not sure in how many cases this would be useful (I'm not sure how many services actually have methods with Empty request in practice).

To clarify: the proposed signature  of e.g. DivAsync
https://github.com/grpc/grpc/blob/40955d2cb4d8f73a4c87df0052921eb28c090277/src/csharp/Grpc.Examples/MathGrpc.cs#L184
would change to 
```
public virtual grpc::AsyncUnaryCall<global::Math.DivReply> DivAsync(Empty request = null, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
{
...
}
```

(adding `request = null`)?

Potential problems:
- generally request and responses are assumed to be not null in the grpc codebase so suddenly having  a null request passed to a method could cause problems (e.g. when an interceptor is used). At the same time, empty is a class, so the only possible default value we can use is `null`.
- this would introduce some level of inconsistency because on server-side one still needs to return new Empty() on the server side even for services that return an Empty value 
- which piece of code would actually populate the null response to become an instance of Empty is an important consideration.


Overall, I'm not sure how much of a usability gain this feature is and I see potential for introducing problems and inconsistencies, so I'm a bit sceptical.
