### ISSUE TITLE
grpc/third_party/boringssl/crypto/fipsmodule/rand/urandom_test.cc:179:23: error: 'PTRACE_O_EXITKILL' was not declared in this scope

### ISSUE THREAD

**Issue by qingtiandalaoye** [grpc/grpc#20909]
### What version of gRPC and what language are you using?

v1.21.3
### What operating system (Linux, Windows,...) and version?

Linux
### What runtime / compiler are you using (e.g. python version or version of gcc)

gcc 9
### What did you do?
If possible, provide a recipe for reproducing the error. Try being specific and include code snippets if helpful.

### What did you expect to see?

compile pass
### What did you see instead?

[ 92%] Building CXX object third_party/boringssl/crypto/CMakeFiles/urandom_test.dir/fipsmodule/rand/urandom_test.cc.o
In file included from /root/grpc/third_party/boringssl/third_party/googletest/include/gtest/gtest.h:375,
                 from /root/grpc/third_party/boringssl/crypto/fipsmodule/rand/urandom_test.cc:15:
/root/grpc/third_party/boringssl/crypto/fipsmodule/rand/urandom_test.cc: In function 'void GetTrace(std::vector<Event>*, unsigned int, std::function<void()>)':
/root/grpc/third_party/boringssl/crypto/fipsmodule/rand/urandom_test.cc:179:23: error: 'PTRACE_O_EXITKILL' was not declared in this scope
                       PTRACE_O_EXITKILL | PTRACE_O_TRACESYSGOOD))
                       ^~~~~~~~~~~~~~~~~

.................
make[2]: *** [third_party/boringssl/crypto/CMakeFiles/urandom_test.dir/fipsmodule/rand/urandom_test.cc.o] Error 1
make[1]: *** [third_party/boringssl/crypto/CMakeFiles/urandom_test.dir/all] Error 2
make: *** [all] Error 2

### Anything else we should know about your project / environment?

even in current grpc version, this error is still exist

**Comment by HarmonyAngel** [comment]
also meet this problem

**Comment by plinnie** [comment]
Same here. Using tag 1.25.0, CMake3. CentOS7 x64. gcc 4.8.5

**Comment by sheenaqotj** [comment]
Esun, do you know anything about this BoringSSL error?

**Comment by creynia-mythic** [comment]
Hitting this issue also. gRPC is from git src (9b1f8e427478c9460aead4e9e63929e040d5675b). cmake 3.15.4, centos7, gcc 4.8.5

**Comment by cashlalala** [comment]
same here, grpc v1.26.0, cmake 3.16, centos7, gcc 4.8.5.

**Comment by d-hoke** [comment]
grpc v1.25.0, centos7 release 7.7.1908 (Core)
same issue

appears to be because /usr/include/sys/ptrace.h is being included rather than 
/usr/include/linux/ptrace.h which is where PTRACE_O_EXITKILL is defined, at least on my system.

from my top-level grpc directory, executed something like following and examined the *.I file versus the ptrace.h files on my system...
cd /home/user1/dev/grpc-1.25.0/cmake/build/third_party/boringssl/crypto && /usr/bin/c++  -E -DBORINGSSL_DISPATCH_TEST -DBORINGSSL_IMPLEMENTATION -I/home/user1/dev/grpc-1.25.0/third_party/boringssl/third_party/googletest/include -I/home/user1/dev/grpc-1.25.0/third_party/boringssl/crypto/../include  -Werror -Wformat=2 -Wsign-compare -Wmissing-field-initializers -Wwrite-strings -Wvla -ggdb -Wall -fvisibility=hidden -fno-common -Wno-free-nonheap-object -Wmissing-declarations -std=c++11 -fno-exceptions -fno-rtti -Wshadow -fPIE   -o CMakeFiles/urandom_test.dir/fipsmodule/rand/urandom_test.cc.I -c /home/user1/dev/grpc-1.25.0/third_party/boringssl/crypto/fipsmodule/rand/urandom_test.cc

default g++ searches on my system
 gcc -xc++ -E -v -
Using built-in specs.
COLLECT_GCC=gcc
Target: x86_64-redhat-linux
Configured with: ../configure --prefix=/usr --mandir=/usr/share/man --infodir=/usr/share/info --with-bugurl=http://bugzilla.redhat.com/bugzilla --enable-bootstrap --enable-shared --enable-threads=posix --enable-checking=release --with-system-zlib --enable-__cxa_atexit --disable-libunwind-exceptions --enable-gnu-unique-object --enable-linker-build-id --with-linker-hash-style=gnu --enable-languages=c,c++,objc,obj-c++,java,fortran,ada,go,lto --enable-plugin --enable-initfini-array --disable-libgcj --with-isl=/builddir/build/BUILD/gcc-4.8.5-20150702/obj-x86_64-redhat-linux/isl-install --with-cloog=/builddir/build/BUILD/gcc-4.8.5-20150702/obj-x86_64-redhat-linux/cloog-install --enable-gnu-indirect-function --with-tune=generic --with-arch_32=x86-64 --build=x86_64-redhat-linux
Thread model: posix
gcc version 4.8.5 20150623 (Red Hat 4.8.5-39) (GCC) 
COLLECT_GCC_OPTIONS='-E' '-v' '-mtune=generic' '-march=x86-64'
 /usr/libexec/gcc/x86_64-redhat-linux/4.8.5/cc1plus -E -quiet -v -D_GNU_SOURCE - -mtune=generic -march=x86-64
ignoring nonexistent directory "/usr/lib/gcc/x86_64-redhat-linux/4.8.5/include-fixed"
ignoring nonexistent directory "/usr/lib/gcc/x86_64-redhat-linux/4.8.5/../../../../x86_64-redhat-linux/include"
#include "..." search starts here:
#include <...> search starts here:
 /usr/lib/gcc/x86_64-redhat-linux/4.8.5/../../../../include/c++/4.8.5
 /usr/lib/gcc/x86_64-redhat-linux/4.8.5/../../../../include/c++/4.8.5/x86_64-redhat-linux
 /usr/lib/gcc/x86_64-redhat-linux/4.8.5/../../../../include/c++/4.8.5/backward
 /usr/lib/gcc/x86_64-redhat-linux/4.8.5/include
 /usr/local/include
 /usr/include
End of search list.

**Comment by yong422** [comment]
Same here. grpc v1.25.0, gcc 4.8.5, cmake 3.16.1, centos 7.3.1611

grpc/third_party/boringssl/crypto/fipsmodule/rand/urandom_test.cc: In function ‘void GetTrace(std::vector<Event>*, unsigned int, std::function<void()>)’:
grpc/third_party/boringssl/crypto/fipsmodule/rand/urandom_test.cc:179:23: error: ‘PTRACE_O_EXITKILL’ was not declared in this scope
                       PTRACE_O_EXITKILL | PTRACE_O_TRACESYSGOOD))

**Comment by d-hoke** [comment]
follow-up - partial workaround (avoidance) for my particular situation... others' mileage may vary.

The error seems to occur building the test code of that subsystem.
I was able to perform 'make -k' (-k, keep going when some targets can't be made) and get enough of what I personally needed built for my use.

**Comment by LoveULin** [comment]
Also meet this problem. But if I add `-DBUILD_SHARED_LIBS=ON` when run cmake, i.e. `cmake -DBUILD_SHARED_LIBS=ON ../..`, compile can pass and helloworld can run successfully.

Using grpc 1.27.0, centos 7.7.1908, cmake 3.16.4,  gcc 4.8.5.

**Comment by LittleFall** [comment]
> Also meet this problem. But if I add `-DBUILD_SHARED_LIBS=ON` when run cmake, i.e. `cmake -DBUILD_SHARED_LIBS=ON ../..`, compile can pass and helloworld can run successfully.
> 
> Using grpc 1.27.0, centos 7.7.1908, cmake 3.16.4, gcc 4.8.5.

Thanks, this solution works on my server.
