### ISSUE TITLE
Support Unity/webGL platform

### ISSUE THREAD

**Issue by IcyEagle** [grpc/grpc#20917]
Hi there!

I'm so glad to hear gRPC is available for Unity projects as well. It works like a charm on mobiles and macOS!

I wonder if it's possible to use the library if I would want to publish my project into web (webGL platform). I suppose it would be necessary to pass gRPC traffic via websocket connections. Anyway, as far as I see the platform isn't supported yet. Do you plan to implement it or, maybe you can get some recommendations about how it could be made, so I could make it by myself and provide PR?

Thanks.

**Comment by nicolasnoble** [comment]
What you're asking is in fact very complex.

The browser doesn't have what it takes to talk "gRPC" out, because of its lack of the appropriate network APIs. We have [gRPC-Web](https://github.com/grpc/grpc-web) which is a reduced version of the protocol and features that can work on the browser, but also requires a specific server as a gateway to an actual gRPC server.

Which also means that the full C#/Unity API won't be implementable straight.

The most relevant way to do what you're asking for would be to support gRPC-Web in C#/Unity, which we don't have any plans for at the moment.

**Comment by IcyEagle** [comment]
@nicolasnoble thank you for the answer! I'll take a look at gRPC-Web and try to find out what I can do for it.
