### ISSUE TITLE
Update 1.22.0 -> 1.24.3 breaks projects depending on grpc

### ISSUE THREAD

**Issue by yurivict** [grpc/grpc#20915]
For example, TensorFlow is now failing: http://beefy6.nyi.freebsd.org/data/120amd64-default/516377/logs/errors/py36-tensorflow-1.14.0_2.log

Also: you obviously changed something significant in the interface and didn't bump the SONAME of the shared library.

**Comment by vjpai** [comment]
@karthikravis The logs indicate something related to build-switching (and probably an IWYU issue as well)

**Comment by yurivict** [comment]
Any easy way to unbreak the TensorFlow build now?

**Comment by nicolasnoble** [comment]
As @vjpai said, this looks like you're not including some headers properly. You can't rely on transitive inclusion; that's not proper behavior. The issue here is that the code was relying on transitive inclusion from generated code. The solution usually is to properly include the headers for the classes you're using in your code.

The more interesting part here is that I'm not sure which version of TensorFlow you're trying to compile. This may already be fixed for TensorFlow's head. In all cases, that's a TensorFlow issue, not a gRPC's.

**Comment by nicolasnoble** [comment]
I take it back, it's still there in TensorFlow:

https://github.com/rockchip-linux/tensorflow/blob/master/tensorflow/core/distributed_runtime/rpc/eager/grpc_eager_service.h#L30-L36

This code is invalid. You can't forward declare classes from a third party project.

**Comment by nicolasnoble** [comment]
I just checked, I've personally fixed this in TensorFlow's code back in February. They need to export that to github somehow.

**Comment by vjpai** [comment]
@jhseu it looks like there's some outdated code at oss-head in TF that's failing after a gRPC upgrade. Any thoughts?

**Comment by vjpai** [comment]
Cc @jing-dong

**Comment by yurivict** [comment]
@nicolasnoble Do you have a URL with the patch? At this point I'm mostly interested in fixing the port that is broken. Perhaps I can apply the same patch?

**Comment by nicolasnoble** [comment]
The patch is in the private Google repository. It hasn't been made public yet, which is why we're trying to address this with the Tensorflow people. I'll have to let them disclose it.

The gist is that TensorFlow used to forward declare our API, which isn't proper. I've cleaned the headers to remove all of these forward declares, and include the corresponding headers instead.

**Comment by karthikravis** [comment]
@yurivict : can you please try it again?

**Comment by yashykt** [comment]
From a brief look, this issue seems to have been fixed, and we have been waiting on reporter confirmation. Please re-open/comment if the issue still persists.
