### ISSUE TITLE
[Question] Using the Python gRPC client from a ThreadPoolExecutor

### ISSUE THREAD

**Issue by burk** [grpc/grpc#20954]
Hey!

Python question:

I'm trying to speed up some existing code which does a lot of gRPC calls. I tried submitting these calls to a ThreadPoolExecutor since they are mostly IO, but I didn't get any speedup compared to the synchronous code. I also tried making a new channel or a new stub in each thread, but that did not help.

I've used the `stub.Method.future(...)` before and it works well but in this case there is a lot of code wrapping the gRPC requests, and I didn't want to refactor it all to handle futures.

Should the gRPC client normally work well from a ThreadPoolExecutor?

My code goes something like this:
```
def do_call():
    return stub.Call(something)

futures = []
thread_pool = concurrent.futures.ThreadPoolExecutor(workers=10)
for _ in range(100):
    futures.append(thread_pool.submit(do_call))

for future in concurrent.futures.as_completed(futures):
    print(future.result())
```

**Comment by lidizheng** [comment]
The server side is using `ThreadPoolExecutor`. It gives you speed up for I/O in your application logic, but not in gRPC logic. The implementation of gRPC has a poller thread, which handles majority of the I/O in gRPC space. It might be the bottleneck for what you are observing.

If you are using unary calls, I would recommend to perform calls directly instead of using futures. We optimized that code path specifically. Several more questions, what is your expected performance? Can you provide the profile for your application (to identify bottlenecks)? A useful tool would be https://github.com/sumerc/yappi.

**Comment by burk** [comment]
It seems it was my use/understanding of the ThreadPoolExecutor that was a bit flawed. The test above actually works fine when I run it now. I had a previous version where I opened the ThreadPoolExecutor in a context, and I didn't consider that it would wait for the results of the threads when exiting the context...

Thanks for the tips about `yappi`! It might help me with similar issues in the future.
