### ISSUE TITLE
alts_concurrent_connectivity_test is failing consistently on master

### ISSUE THREAD

**Issue by jtattermusch** [grpc/grpc#21142]
Is failing 100%

In the run_tests.py suites:

https://source.cloud.google.com/results/invocations/62b2de00-7609-4780-8ea4-fc0c44342eff/targets/github%2Fgrpc%2Frun_tests%2Fcpp_linux_dbg_native/tests
https://source.cloud.google.com/results/invocations/848ad153-361b-4510-894a-8e83fa24bc96/targets/github%2Fgrpc%2Frun_tests%2Fcpp_linux_dbg_native/tests
https://source.cloud.google.com/results/invocations/0bf2350e-d345-47ca-99a5-880e1b71ab30/targets/github%2Fgrpc%2Frun_tests%2Fcpp_linux_dbg_native/tests

Probable root cause:
https://github.com/grpc/grpc/pull/20929

**Comment by jtattermusch** [comment]
Failing both linux/grpc_basictests_c_cpp_dbg and linux/grpc_basictests_c_cpp_opt

**Comment by apolcyn** [comment]
This can be repro'd locally.

The test that's failing is one particular test of the set that exists in `alts_concurrent_connectivity_test`, which can be ran with:

```
GRPC_POLL_STRATEGY=poll bins/opt/alts_concurrent_connectivity_test --gtest_filter=AltsConcurrentConnectivityTest.TestHandshakeFailsFastWhenHandshakeServerHangsAfterAccepting
```

I think this new test is making a fundamentally racey assertion (with a high chance of losing the race):

This test itself repeatedly, in a loop:
1) creates a channel with a 100ms reconnect backoff.
2) attempts to connect via ALTS to a backend that accepts TCP connections but from then on is non-responsive
3) The ALTS handshake server is also non-responsive
4) After the 100ms connect deadline fires, the subchannel shuts down the ongoing ALTS handshake. The subchannel shuts down the handshake and "fails" it's connect attempt, and sets it's connectivity state to "transient failure"
5) Because the full 100ms deadline has been used up, the subchannel immediately reconnects, and sets its connectivity state to "connecting"
6) The test wakes up for it's call to `watch_connectivity_state` due to the subchannel changing state to "transient failure" earlier. However, when the test now checks it's connectivity state, with a call to `grpc_channel_check_connectivity_state`, the state has since changed back to "connecting". The test's while loop will never terminate so long as it continues to hit this race.

I think the fix is just in the test: the test should probably assert that connectivity state changes (and doesn't become ready), but it probably shouldn't require introspection of the connectivity state to necessarily be "transient failure"
