### ISSUE TITLE
Add nullable reference type metadata to Grpc.Core/Grpc.Core.Api

### ISSUE THREAD

**Issue by JamesNK** [grpc/grpc#21323]
Should add nullable reference type metadata to .NET gRPC libraries: https://devblogs.microsoft.com/dotnet/embracing-nullable-reference-types/

This feature requires C# 8.0. What is the allowed version of C# at the moment?

**Comment by jtattermusch** [comment]
Right now we are using this SDK:
https://github.com/grpc/grpc/blob/e29f3b27b18717c7c3dba27c3bd4008200f01390/templates/tools/dockerfile/csharp_dotnetcli_deps.include#L2

The SDK would have to be updated in multiple places, but in principle it's doable.
The problem is that some internal projects still only support C# 7.2 so we cannot really upgrade at this point.
