### ISSUE TITLE
xamarin.android x86_64 missing dlls 

### ISSUE THREAD

**Issue by jingliancui** [grpc/grpc#21325]
Now i have use the x86_64 android emulator,but grpc not provide the dlls about this platform , can you add this for this platform?

**Comment by jtattermusch** [comment]
We are not planning to provide more pre-compiled grpc_csharp_ext native libraries to Grpc.Core nuget package because the package is already too big. We'd need to figure out a way to slim down the Grpc.Code package first.

Currently the nuget has a x86 version of android binary, you should be able to use it (or build the x86_64 version yourself).
https://github.com/grpc/grpc/blob/8174dbdd50303107a0d0827202d0a42532392406/tools/run_tests/artifacts/artifact_targets.py#L359
