### ISSUE TITLE
how to create a long time stream by loadbalance round_robin

### ISSUE THREAD

**Issue by lantian20060901** [grpc/grpc#21432]
### Is your feature request related to a problem? Please describe.
I have many client and many server ,I use the fakeResolver to update the sever ip and port.
Now the client need long time stream to watch the server ， the server don't close the stream and can send the data to client without delay.
`rpc Listen (Command) returns (stream Data)`

the lb_policy is round_robin, so the Listen stream is random，how client  send the listen to all the server(and the server is change sometimes) to wath all the server

### Describe the solution you'd like
I want server can actively send data to client

### Describe alternatives you've considered
Do I need to do load balancing myself ，to solve the problem

### Additional context
Add any other context about the feature request here.

**Comment by stanley-cheung** [comment]
What language is this for?

**Comment by lantian20060901** [comment]
I use the cpp

**Comment by karthikravis** [comment]
@lantian20060901 : Can you please explain why you would want all the servers to get the "Listen()" RPC call? Is this a requirement?

**Comment by muxi** [comment]
Your requirement looks valid but it looks like you are doing it in a strange way. There seems to be two things you probably want to reconsider
* Fake resolver is usually for tests. If you have dynamic server ip and port, consider making the addresses available to gRPC with either your DNS or [grpclb](https://github.com/grpc/grpc/blob/master/doc/load-balancing.md).
* `round_robin` policy seems to be achieving what you want in terms of "to watch all the servers". It is NOT random. Say you have 100 servers for a channel and start 100 stream calls on the channel, each server will serve exactly 1 stream. Note that in case you want to be able to tell which stream is for which server, you will need to have some application-level metadata; gRPC does not tell you that by definition of "load balancing".

I am closing this issue since this looks more like a question than an issue. Following gRPC process, if you have further question related to this thread, please post the question on the [mailing list](https://groups.google.com/forum/#!forum/grpc-io).
