### ISSUE TITLE
C#: Allow async interceptor methods 

### ISSUE THREAD

**Issue by sherrman** [grpc/grpc#21489]
### Using await inside of an Interceptor method

I can't use await inside of an Interceptor method because they aren't `async`.

I'm attempting to add a Polly circuitbreaker to something like `AsyncUnaryCall`, but that requires completing the `ResponseAsync` task. While I think that `GetAwaiter().GetResult()` works, it's not ideal.

### Describe the solution you'd like

Create an `AsyncMethodBuilder` and put the `AsyncMethodBuilderAttribute` on all of the return types like `AsyncUnaryCall<TResponse>`.
### Describe alternatives you've considered

All of the return types are already `await`able, but because the `AsyncUnaryCall` isn't task-like, you can't have it as an `async` return type.

**Comment by jtattermusch** [comment]
Can you provide a concrete example of what you're trying to achieve and why exactly it is not possible with the current interceptor API?

Having async interceptor code is possible like this:
1. you inherit from Interceptor to provide your own interception logic.
2. In e.g. `YourInterceptor.AsyncUnaryCall` override instead of returning the object representing the call itself, you return a wrapper instance that redirect all the functionality to the original call, but overrides any behavior you'd like to change. Because the call's result is a task, you can definitely include async logic (such as awaits etc.), you don't need the method itself to return a Task<AsyncUnaryCall> (which would make little sense IMHO).

**Comment by sherrman** [comment]
Thanks for the help @jtattermusch . I've accomplished what I'm trying to do with this:

``` csharp
using Polly.CircuitBreaker;

public class CbInterceptor : Interceptor
{
    private CircuitBreaker _Cb;

    public CbInterceptor()
    {
        _Cb = new AsyncCircuitBreaker(exceptionsAllowedBeforeBreaking: 2, durationOfBreak: TimeSpan.FromMinutes(1));
    }

    public override AsyncUnaryCall<TResponse> AsyncUnaryCall<TRequest, TResponse>(TRequest request,
        ClientInterceptorContext<TRequest, TResponse> context,
        AsyncUnaryCallContinuation<TRequest, TResponse> continuation)
    {
        if (_Cb.CircuitState == CircuitState.Open || _Cb.CircuitState == CircuitState.Isolated) {
            throw new BrokenCircuitException("circuit open", _Cb.LastException);
        }

        var ctn = continuation(request, context);
        var wrappedResponse =_Cb.ExecuteAsync(async () => await ctn.ResponseAsync);
        return new AsyncUnaryCall<TResponse>(wrappedResponse, ctn.ResponseHeadersAsync, ctn.GetStatus, ctn.GetTrailers, ctn.Dispose);
    }
}
```
