### ISSUE TITLE
Ruby flake in unknown test

### ISSUE THREAD

**Issue by murgatroid99** [grpc/grpc#2161]
This line appeared after all of the tests passed and after a large number of queues shut down and the coverage report was generated:

```
E0622 18:45:05.091512865    9516 completion_queue.c:113] assertion failed: cc->queue == NULL
```

The log is [here](https://s3.amazonaws.com/archive.travis-ci.org/jobs/67882550/log.txt)

**Comment by ctiller** [comment]
It (most likely) means new work was requested after
completion_queue_shutdown was called, which is illegal.

We don't have a good way of checking it currently (the check would be
too-high overhead), but we can hack up a client to fail whenever this is
done fairly easily.

**Comment by tbetbetbe** [comment]
There is a bit of a puzzle here:
- the ruby extension only invokes completion_queue_shutdown when it GC's the ruby-level completion queue object
  - that's why the line only appeared after all the tests had passed, the tests and ruby-layer code that they used had completed and were being GCed
- I.e, at that point, the completion queue should not reachable from ruby-interpreter level code

**Comment by ctiller** [comment]
So the way to push new work is via:
- grpc_call_start_batch
- grpc_server_shutdown_and_notify
- grpc_server_request_call

One hypothetical way this could be happening is by starting a batch on a
completion queue that's getting gc'd.

**Comment by tbetbetbe** [comment]
@jayantkolhe, @hsaliak:  removing from Beta label, as this could not be reproduced

**Comment by tbetbetbe** [comment]
Closing this:
- It has not been reproduced
- There have been significant changes to both the c-core and the ruby-wrapping w.r.t to server shutdown
so its unlikely that it's possible to reproduce this
