### ISSUE TITLE
Mac compilation for Core is broken

### ISSUE THREAD

**Issue by pfreixes** [grpc/grpc#21656]
### What version of gRPC and what language are you using?
Language: Core
Version: Master

### What operating system (Linux, Windows,...) and version?
Mac, Mojave 10.14.4

### What runtime / compiler are you using (e.g. python version or version of gcc)
```bash
$ clang --version
Apple LLVM version 10.0.1 (clang-1001.0.46.4)
Target: x86_64-apple-darwin18.5.0
Thread model: posix
InstalledDir: /Library/Developer/CommandLineTools/usr/bin
$ clang++ --version
Apple LLVM version 10.0.1 (clang-1001.0.46.4)
Target: x86_64-apple-darwin18.5.0
Thread model: posix
InstalledDir: /Library/Developer/CommandLineTools/usr/bin```
```

### What did you do?
Since this commit [1] Im not longer able to build the Core of the gRPC having always symbol error as you can see in the following snippet

```
$ make
....
[LD]      Linking /Users/paufreixes/skyscanner/grpc/libs/opt/libgrpc_unsecure.dylib
[LD]      Linking /Users/paufreixes/skyscanner/grpc/libs/opt/libupb.dylib
[LD]      Linking /Users/paufreixes/skyscanner/grpc/libs/opt/libgrpc++.dylib
[LD]      Linking /Users/paufreixes/skyscanner/grpc/libs/opt/libgrpc++_alts.dylib
Undefined symbols for architecture x86_64:
  "_gpr_log", referenced from:
      grpc::experimental::GetAltsContextFromAuthContext(std::__1::shared_ptr<grpc::AuthContext const> const&) in alts_util.o
  "_grpc_gcp_AltsContext_msginit", referenced from:
      grpc::experimental::GetAltsContextFromAuthContext(std::__1::shared_ptr<grpc::AuthContext const> const&) in alts_util.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make: *** [/Users/paufreixes/skyscanner/grpc/libs/opt/libgrpc++_alts.dylib] Error 1
```

Using the previous commit to [1], the core can be build without any problem

[1] https://github.com/grpc/grpc/commit/618771dc6aa33c38fe4499fee2c3acebef96b04d

### What did you expect to see?
Being able to compile the master version of Core without any issue. 

### What did you see instead?
As was mentioned above, a symbol error is raised and the compilation does not finish

**Comment by ZhenLian** [comment]
@pfreixes 
Hi Pau, Thanks for identifying and reporting the issue here. I created a patch PR(https://github.com/grpc/grpc/pull/21670) and it worked well on my end. I am working on getting this PR merged. In the meantime, could you please also manually patch that PR to your local machine to see if `make` works as expected? Thanks in advance for your assistance!

**Comment by pfreixes** [comment]
Confirmed that the issue has been fixed, thanks!

PD: how are we gonna prevent to have a failure in the future like this? Why is not the current CI detecting this kind of regressions?

**Comment by ZhenLian** [comment]
I am not quite familiar with how the Kokoro build works in general. After talking to the team, the issue might because `libgrpc++_alts.dylib` is new and there is no specific test for it. It didn't get caught by the pre-submit probably because most of unit-tests already have a dependency against grpc.

It seems more unit tests needed in the future, but the detail is still unknown and need to be discussed. I will keep an eye on this to see if same thing happens in the future. Thanks again for all the work here!
