### ISSUE TITLE
grpc as submodule conflicts with existing abseil submodule (C++ / CMake)

### ISSUE THREAD

**Issue by pieter3d** [grpc/grpc#21719]
My project already has abseil-cpp, which works just fine in my external directory and the following in CMakeLists.txt
`add_subdirectory(abseil-cpp EXCLUDE_FROM_ALL)
`
If I then also add grpc, I get build errors like this:
```
 CMake Error at external/grpc/third_party/abseil-cpp/CMake/AbseilHelpers.cmake:148 (add_library):
  add_library cannot create target "absl_atomic_hook" because another target
  with the same name already exists.  The existing target is an interface
  library created in source directory
  "/path/to/project/external/abseil-cpp/absl/base".  See
  documentation for policy CMP0002 for more details.
Call Stack (most recent call first):
  external/grpc/third_party/abseil-cpp/absl/base/CMakeLists.txt:19 (absl_cc_library)
```
Clearly duplicate targets.

Looking at the abseil cmake files in grpc/cmake, I tried setting ABSL_ROOT_DIR so that grpc can use my abseil-cpp submodule instead of its own.
`set(ABSL_ROOT_DIR "${PROJECT_SOURCE_DIR}/external/abseil-cpp")
`
But that yields the following similar error:
```
CMake Error at external/abseil-cpp/CMake/AbseilHelpers.cmake:148 (add_library):
  add_library cannot create target "absl_atomic_hook" because another target
  with the same name already exists.  The existing target is an interface
  library created in source directory
  "/path/to/project/external/abseil-cpp/absl/base".  See
  documentation for policy CMP0002 for more details.
Call Stack (most recent call first):
  external/abseil-cpp/absl/base/CMakeLists.txt:19 (absl_cc_library)
```
Because grpc always adds abseil-cpp in grpc/cmake/abseil-cpp.cmake, there's no clean way to avoid this double-add.

So far the only way I have found is to set `gRPC_ABSL_PROVIDER` to something other than "module" or "package", since that will cause it just not include absl at all, but with the top project including it separately it's still found. 
Would be nice if abseil-cpp.cmake could detect if abseil was already available before trying to add it locally.

**Comment by veblush** [comment]
First of all, there is a [directory](https://github.com/grpc/grpc/tree/master/test/distrib/cpp) which contains a couple of scripts testing cmake usage of gRPC, which might be helpful to see an idea to solve the issue.

I guess having a similar thing to [include guard](https://en.wikipedia.org/wiki/Include_guard) could be one of feasible solutions but I want to know this is the right way to solve the problem since we encourage to use `ExternalProject_Add` instead of `add_subdirectory` but it doesn't mean that we cannot have an include guard anyway.

@jtattermusch What do you think?

**Comment by jtattermusch** [comment]
The only clean solution to this problem is to set gRPC_ABSL_PROVIDER=package and have both grpc and your project depend on a pre-installed absl library (which you previously installed with cmake).
It's not ideal from the usability perspective, but unfortunately that's how C++ dependencies work (if two cmake projects import the same dependency independently of each other, of course it's going to fail)

One idea would be to remove absl dependency from your project and depend on absl that's brought in by gRPC (i.e. omit `add_subdirectory(abseil-cpp ...` from your project)

Also perhaps you could get around this with cmake's FetchContent? https://github.com/grpc/grpc/tree/master/src/cpp#fetchcontent

It would also help if you shared how exactly your CMakeLists.txt looks like (do you add grpc using add_subdirectory()? )

**Comment by nicolasnoble** [comment]
Ping on this one. It can be alienating for users.

**Comment by jtattermusch** [comment]
I already provided my opinion (and hopefully a way to workaround the problem) in my comment https://github.com/grpc/grpc/issues/21719#issuecomment-578172856, but haven't got a response.

**Comment by kalman5** [comment]
I tried to use a precompiled 1.32 grpc, compiled with:

cmake -DBUILD_SHARED_LIBS=ON -DgRPC_INSTALL=ON -DgRPC_BUILD_TESTS=OFF -Dprotobuf_WITH_ZLIB=ON ../..

in a project using abseil-cpp as internal target ( add_subdirectory(abseil-cpp) )

and I get a bad_alloc exception when calling BuildAndStart, I tried to create an abseil library but the .a targets are kinda incomplete, for instance I'm not even able to link a simple main using flat_hash_map

To create the abseil lib I do:

mkdir build
cd build
cmake ..
make -j8
make install

main is:

#include "absl/container/flat_hash_map.h"

int main () {
  absl::flat_hash_map<int, int> myMap;
  myMap[1] = 1;
}

I tried to link all the produced .a but it doesn't link as example of error:

/usr/local/lib/libabsl_synchronization.a(waiter.cc.o): In function `absl::lts_2020_02_25::synchronization_internal::MaybeBecomeIdle()':
waiter.cc:(.text+0x9): undefined reference to `absl::lts_2020_02_25::base_internal::CurrentThreadIdentityIfPresent()'

**Comment by mingwandroid** [comment]
.. for me, attempting to build against my own `abseil 20200923.2` package on conda and `gRPC_ABSL_PROVIDER=package` I get:
```
/opt/conda/conda-bld/grpc-cpp_1606769946124/_build_env/bin/../lib/gcc/x86_64-conda_cos6-linux-gnu/7.3.0/../../../../x86_64-conda_cos6-linux-gnu/bin/ld: libgrpc.a(xds.cc.o): in function `grpc_core::(anonymous namespace)::XdsLb::LocalityMap::Locality::UpdateLocalityStats()':
xds.cc:(.text._ZN9grpc_core12_GLOBAL__N_15XdsLb11LocalityMap8Locality19UpdateLocalityStatsEv+0x213): undefined reference to `absl::lts_2020_09_23::optional_internal::throw_bad_optional_access()'
```
