### ISSUE TITLE
GRPC streams in Unity blocking all other calls

### ISSUE THREAD

**Issue by cg-adam** [grpc/grpc#21734]
### What version of gRPC and what language are you using?
C#

grpc_unity_package.2.27.0-dev.zip 
Build ID: e16de21b58e5421da248c1c91c0456860ce999b870a7e9e13e55272c48be42ff

### What operating system (Linux, Windows,...) and version?
Mac OS & Windows 10

### What runtime / compiler are you using (e.g. python version or version of gcc)
Unity 2019.2.17

### What did you do?
Started a stream which runs indefinitely on the server until it is requested to be cancelled. Once running the stream no other calls (unary or streams) can be made, they all timeout. When trying to cancel the stream, still no other calls can be made until Unity is quit and restarted.

### What did you expect to see?
Streams should not block any other calls (should be able to run multiple streams and make unary calls at the same time).

**Comment by jtattermusch** [comment]
Can you provide a code snippet that reproduces the problem? Otherwise this is basically impossible to debug.

**Comment by cg-adam** [comment]
Sure. Here is an example of what I am doing, the two public methods can be called via UI buttons in the game scene when testing.

```
public class StreamTester : MonoBehaviour
{
    private Channel mGameChannel;
    private Channel mStreamChannel;
    private Game.GameClient mClient;
    private Game.GameClient mStreamClient;
    private Task mInitRequestTask;
    private CancellationTokenSource mStreamCTS;

    public void StartStream()
    {
        Task.Run(RunStreamTask);
    }

    public void SendInitRequest()
    {
        Task.Run(RunInitTask);
    }

    private async void RunStreamTask()
    {
        mStreamChannel = new Channel("IP_HERE", ChannelCredentials.Insecure);
        mStreamClient = new Game.GameClient(mStreamChannel);
        mStreamCTS = new CancellationTokenSource();
        var streamRequest = new TestStreamRequest {GameId = "GAME_ID_HERE"};

        try
        {
            using (var streamCall = mStreamClient.TestStream(streamRequest, cancellationToken: mStreamCTS.Token))
            {
                var responseStream = streamCall.ResponseStream;

                while (await responseStream.MoveNext())
                {
                    Debug.Log("Response received");
                }
            }
        }
        catch (RpcException e)
        {
            Debug.Log("Stream RPC failed: " + e);
            throw;
        }
        finally
        {
            Debug.Log("Shutting down channel...");
            await mStreamChannel.ShutdownAsync();
        }

        Debug.Log("Stream is done!!!");
    }

    private async void RunInitTask()
    {
        mGameChannel = new Channel("IP_HERE", ChannelCredentials.Insecure);
        mClient = new Game.GameClient(mGameChannel);

        try
        {
            var gameInitRequest = new GameInitRequest();
            using (var initCall = mClient.GameInitAsync(gameInitRequest, deadline: DateTime.UtcNow.AddSeconds(10)))
            {
                var response = await initCall.ResponseAsync;
                Debug.Log("INIT RESPONSE RECEIVED : " + response);
            }
        }
        catch (RpcException e)
        {
            Debug.LogException(e);
            throw;
        }
    }
}
```

**Comment by Katori** [comment]
@cg-adam I don't have this library installed at the moment and my Unity installations are a bit messy, so I can't compile your code right now, but I have important advice about something that is jumping out at me immediately.

What I can tell you as an experienced .NET developer with a focus on Unity is that "async void" is known to be bad news, in all impls of .NET. The only purpose of an async void is as an asynchronous entry point where you can await Tasks.

All critical async functions should be defined in async Tasks. This however presents another problem: Unity API that interacts with native world (which comprises a large portion of their API surface, including most of the `Component` and `Transform` APIs) must be executed on the MAIN THREAD ONLY (a concept known as `SynchronizationContext`).

This is critical as their code is not threadsafe. Luckily, there is an easy way to ensure your code is always executed on the desired thread. Using [this package](https://github.com/Katori/UnityAsync/tree/UnityPackage) (which was not developed by me, but my fork is linked, as you can install it with UPM simply by [adding it to your manifest](https://docs.unity3d.com/Manual/upm-git.html)), whenever you need a Unity native API (let's say for example you want to get or assign a `.transform.position`), you can simply insert `await Await.UnitySyncContext();` and you are back synchronized properly with Unity.

If you are not using Unity native API (`Debug.Log` is fine) then you do not need this. But with this you will be totally equipped to handle any needs of your code and reap the benefits of async (which there are many).

So, with these tools in hand, you can totally remove `async void` for `async Task` and `Task.Run` for `await TheTaskIWant();`. Also, for your "entry point", you can make a MonoBehaviour message (like `Start()` or `Awake()`) into "async void" so that you can `await` Tasks on it, just don't put any critical async code in that method.

Alright, my diatribe is done, please try my advice and update us if it still does not work.

**Comment by cg-adam** [comment]
Thanks @Katori I will have another stab at the code taking on your advice and see if I can get it working. The code I supplied will likely not compile (as it is just the C# portion, no server or generated proto files) it was more just to showcase what I was doing. I will aim to do some more tests today on this.

**Comment by filharveyrobin** [comment]
Did this fix your issue with the Async calls? as I'm currently seeing the same.

**Comment by filharveyrobin** [comment]
Actually just tried, and UnityAsync, fixed my issues with the Async call freezing.

**Comment by jtattermusch** [comment]
Is this still an issue?

**Comment by cg-adam** [comment]
We had to switch how we were making calls as we had no fix in time for a release we had to make. Not managed to test this since as other priorities have taken over. If I get a chance I will try and test it soon. We were using UniTask (UniRx library) but are looking at switching over to UnityAsync to see if this improves things.

**Comment by jtattermusch** [comment]
I'm going to close issue this since we're not going to pursuit Unity/Xamarin support in `Grpc.Core` anymore.
- The `Grpc.Core` implementation is now in maintenance mode and we're only going to focus on critical and security fixes.
- Supporting Unity/Xamarin simply presents too much maintenance overhead and it's also difficult to test with the test infrastructure available to us
- The Unity/Xamarin support has always been classified as "experimental", so discontinuing the support shouldn't be too surprising.

See [the recent update on gRPC C#](https://groups.google.com/g/grpc-io/c/OTj5mb1qzb0/m/-M81UQipAQAJ) for more details.

Note that in practice, running Grpc.Core on Unity/Xamarin might still be possible (there is nothing in principle that would prevent it from working), but it will be completely at your own risk and it's simply not one of the use cases the grpc team will help you with as `Grpc.Core` on Unity/Xamarin is now considered as "not supported" by us (but you might still be able to get help from the community).
