### ISSUE TITLE
Bi-directional streaming in Python closes prematurely

### ISSUE THREAD

**Issue by johnbywater** [grpc/grpc#21737]
I'm guessing this is the same issue as #16234, when @srini100 said, "Will help if someone can post a minimal reproduction of this issue." So I thought it would help to share this code. :-)

### What version of gRPC and what language are you using?
Python, grpcio v1.26.0.

### What operating system (Linux, Windows,...) and version?
MacOS High Sierra

### What runtime / compiler are you using (e.g. python version or version of gcc)
Python 3.7.3.

### What did you do?
Use bi-directional RPC in the recommended way.

### What did you expect to see?
Streaming response.

### What did you see instead?
Server errors about connection being closed. Exactly the same as #16234. It seems the request is dropped before the streaming starts, then the connection is closed, so the response is broken.  Since clients in other languages don't fail like this, it feels like a bug in the Python implementation? I found a workaround by preventing the request iterator from exiting before the response has begun, but it involves a threading Event, and a sleep hack. I haven't seen my code fail since I discovered the workaround, but 'm not entirely satisfied my workaround will always work, especially if server response is slower that it happens to be in the environments I'm using.

### Anything else we should know about your project / environment?
This is reproducible by using this commented line of code in this module, instead of the following alternative lines which feel like a hack that seems to make it work. There are some tests, and a Travis config file to show how to setup and run the tests:
https://github.com/johnbywater/python-axon-client/blob/master/axonclient/client.py#L217

**Comment by johnbywater** [comment]
@gnossen did you have any thoughts about this?

**Comment by gnossen** [comment]
@johnbywater Sorry for the long wait on this issue. It got buried.

I believe this works as intended. When the request iterator is exhausted, the RPC ends. If you require the RPC to last long enough to consume response messages, then the iterator must not terminate until the desired messages have been consumed.

Since your workaround `request_iterator` depends on an arbitrary timeout, you're right that this could fail during an unlucky execution. Namely, if it takes longer than 100 milliseconds for the desired response message to arrive.

Based on your service definition, it looks like a single `GetEventsRequest` message results in the server streaming back an indeterminate number of `EventWithToken` messages. Since the contents of a response message are not sufficient to determine whether the responses corresponding to an individual `GetEventsRequest` message have finished, the only indication you have that it's safe to exit the iterator is the server itself ending the stream. To do better than this, you'd have to get some indication from the server that it's finished sending all of the events for an individual request, either by preceding the message contents with a count or by returning a sentinel value indicating that the server has finished transmitting events for an individual request.

But, leaving the protocol as is, a solid fix would be simply removing the sleep from your iterator and only setting the `stop_event` after the server has closed the connection.

**Edit**: Scratch that last suggestion. I tried it out and found that your server does not close the connection until the client closes *its* connection. That's a circular dependency, resulting in deadlock. Maybe the client should send a sentinel value to indicate that it has finished sending requests? I'm happy to advise if you provide a bit more information about your protocol.

**Comment by johnbywater** [comment]
Thanks for your thoughtful consideration of this. I really appreciate it.
