### ISSUE TITLE
Clean Up Manylinux1 Special Cases

### ISSUE THREAD

**Issue by gnossen** [grpc/grpc#21787]
https://github.com/grpc/grpc/pull/21780 drops support for `manylinux1`. We need to identify areas in the codebase that can be cleaned up since support is no longer required and perform the cleanup.

**Comment by mehrdada** [comment]
Can you please let us know what the minimum platform requirements are?

**Comment by gnossen** [comment]
@veblush can elaborate, but yes; this should enable C++11. The new bottleneck is [manylinux2010](https://www.python.org/dev/peps/pep-0571/), which supports up to glibc 2.12 and glibcxx 3.4.13.

**Comment by veblush** [comment]
You can find platform requirements for `manylinux2010` from [PEP 571](https://www.python.org/dev/peps/pep-0571/).

We've been using C++11 with some restrictions, though. This (partially) gives us a chance to bump the version of C++ to 14 or even 17 in future since `manylinux2010` official docker images go with gcc 7 and 8 meanwhile `manylinux1` was bundled with gcc 4.8.
