### ISSUE TITLE
 Dynamic creation of executable .dll files in %tmp% folders

### ISSUE THREAD

**Issue by echopolarfox** [grpc/grpc#21788]
Hello gRPC team,

This ticket is a result of a customer issue: 
https://partnerissuetracker.corp.google.com/issues/147360513

For security reasons, the customer would like to revoke the execution permission from /tmp folder.
However, gRPC uses Netty library, which unpacks and executes .dll files into temp folder [1]. We don't use Netty directly but it comes as a dependency with gRPC.
This behavior can be replicated in Linux and Windows.

As a workaround setting -Djava.io.tmpdir=/none-temp-folder works for this customer, but may not be the be optional solution long-term solution.

Is there a way to change this behavior? 

-----------------------------------------
[1]Netty will unpack the shared library provided by the netty-tcnative-XXX artifact into a temporary directory and load it using java.lang.System.load(String)
https://netty.io/wiki/forked-tomcat-native.html

versions used:
com.google.cloud:google-cloud-core-grpc:jar:1.63.0
 io.grpc:grpc-core:jar:1.18.0
io.grpc:grpc-netty-shaded:jar:1.18.0

**Comment by veblush** [comment]
Eric, can you take a look at this issue since it's a gRPC Java Issue.

**Comment by ejona86** [comment]
> Is there a way to change this behavior?

What do you have in mind? We must extract the .dll to _a_ writable directory that allows execution.

I'll note that in Java 9+ netty-tcnative is not required; if running on Java 9+ with a noexec /tmp, the dll would still be extracted but would fail to be loaded so gRPC should fall back to using the JDK. (So everything would appear to "just work".)

**Comment by adamulrich** [comment]
We have customers with the same temp directory problem, and Applocker can be set to disallow code execution from temp, causing our app to fall over. But we do rely on netty, so silently failing isn't good.  

What I was thinking was I would place the native libraries in a path at install time (since I have admin permissions at install time to do that), and grpc could reference them if they are there, instead of extracting them to temp.

**Comment by ejona86** [comment]
@adamulrich, and you would be able to keep them up-to-date as you upgrade the app? If you use the wrong version, you may not get a clear error message.

But you can do that. Netty will first try to load the library from the system, so if you put the .dll/.so in the normal system loading location (%PATH%, $LD_LIBRARY_PATH, etc) then the tmp location shouldn't be used. You can also change the loading location with `-Djava.library.path`.

**Comment by adamulrich** [comment]
Yes, I would be able to keep them up to date. I can extract it from the jar as part of building my installers, so it should always be on the latest version. I have to do some wonky stuff with these libs on the osx side (we build both mac and windows) due to apple notarization; they don't get codesigned before being placed in the jar, so I have to break the jar open to get that lib out. codesign it, then put it back in the jar. So I have to be aware of what version we are using for that process anyway.

**Comment by adamulrich** [comment]
@ejona86 this has solved my windows problem nicely, and I have it working. We have a separate but related problem on the osx side. Apple requires notarization for all desktop apps. Notarization requires that all executables and libraries be codesigned, and the problem being that the netty libraries are not codesigned prior to them being placed in the jar, and their is no way to codesign the file within the jar (that is within another jar). To solve the osx problem, I thought to now delete the native library from the jar (because the file is now baked into the installer), which I have done. But grpc falls over because the jnilib (that it no longer needs because it s in the library path) is not embedded in the jar anymore.

**Comment by ejona86** [comment]
> But grpc falls over because the jnilib (that it no longer needs because it s in the library path) is not embedded in the jar anymore.

Can you share the error you see? It should work fine...

**Comment by ejona86** [comment]
Looks like this was resolved with https://github.com/grpc/grpc/issues/21788#issuecomment-641350338 . The code signing would take place as part of the Netty project and is tracked at https://github.com/netty/netty/issues/10569

If that's wrong, comment and I can reopen.
