### ISSUE TITLE
Fix the tagline... "The C based gRPC" is no longer valid.

### ISSUE THREAD

**Issue by coryan** [grpc/grpc#21862]
The repository reads: "The C based gRPC (C++, Python, ...", I think it should be "The C++ based gRPC (..." because it is, right?

**Comment by gnossen** [comment]
CC @nicolasnoble

**Comment by coryan** [comment]
AFAICT this is still a problem.  I assume there are some branding considerations, but the actual fix should take 2 minutes with the right permissions.  What gives?

**Comment by jtattermusch** [comment]
I think "C based gRPC" is still correct in the broader sense. The core library is still being called "C core" (even though it internally uses C++) - mostly because everyone's used to that name now and re-naming doesn't really seem that important.
Also C-core still only exposes all the public API as a C API (and not C++). The language of the public API (still C) is arguably more important than the implementation language (which to some extent is an implementation detail).

So I don't think the wording is the repository's subtitle is really that important to warrant an issue being filed for it (we have more important issues to deal with and our resources are limited).
