### ISSUE TITLE
Fix _invocation_defects_test

### ISSUE THREAD

**Issue by mehrdada** [grpc/grpc#21998]
It it not clear what https://github.com/grpc/grpc/blob/master/src/python/grpcio_tests/tests/unit/_invocation_defects_test.py is actually trying to test (it mostly predates me and looks like the failures are due to calling `next` on iterable as opposed to iterator, but I am not sure if that failures are even intended.)  There's `_Callback` and `self._control` in the test object that remains unused.  I suspect it might be worthwhile to see if there's a legitimate behavior we want to test and fix the tests and remove the unused code.

**Comment by mehrdada** [comment]
My guess is the test is *accidentally* raising `RpcError` due to `TypeError` and the original intent may have been to raise `Defect()`

**Comment by mehrdada** [comment]
@lidizheng I have; just wanted to run by you for sanity check/elimination -- my take on this is it's pretty useless and redundant with other tests except for `testDefectiveGenericRpcHandlerUnaryResponse` (which we may be able to move to another file).

**Comment by lidizheng** [comment]
@mehrdada After took a closer look, my interpretation of the test intent is make sure exception-raising user code not going to break us.

About the `RpcError`, it is converted by a try-catch in the iterator logic ([code](https://github.com/grpc/grpc/blob/master/src/python/grpcio/grpc/_channel.py#L198)).

I think the type error might be intended, otherwise, there isn't any code that injects error. I searched through `_rpc_test.py` and not finding a test case that guard this behavior. So, there is value keeping this test file.

I added some comment and assertions in https://github.com/grpc/grpc/pull/22026, if that can resolve your concern.
