### ISSUE TITLE
hope grpc can allow using struct defined by uses or protobuf data type, when make rpc method in service

### ISSUE THREAD

**Issue by 87ZGitHub** [grpc/grpc#22107]
### Is your feature request related to a problem? Please describe.
I think grpc violate one  principle of IDL RPC: making rpc method like some method in the way like python, GO. when we define a rpc method, we must use a meesage as request, and a message as reply.

### Describe the solution you'd like
Maybe, grpc can make some change like  thrift(made by facebook) as pictrue below.

![企业微信20200222054751](https://user-images.githubusercontent.com/28796660/75090195-7cc81280-559b-11ea-8dc7-35c8e0e1d04d.png)
or :
``` golang
rpc getUsers() returns (repeated User users);

message User{}
```
We can directly using a struct we defined as request or reply, as well as protobuf data type like string, int32 and so on

**Comment by tnngo** [comment]
I hope so.

**Comment by yashykt** [comment]
gRPC does allow use of generic RPCs where the user can serialize and deserialize payloads however they want. This way you can use whatever struct you want, you would just need to be able to serialize and deserialize the data. 

I am not sure I completely understood the suggestion, so please feel free to correct me.

**Comment by markdroth** [comment]
Defining messages for request and response types is actually better, because it allows forward compatibility as parameters and return types evolve.  And it's still fully possible to do what you want by defining an empty message or a message with just one field.

We don't have any plan to allow supporting parameters or return values of types other than message with protobuf.  But you don't have to use protobuf as the IDL; you can define your own for use with gRPC using something other than protobuf.  Or, as Yash said, you can bypass the IDL completely and use our generic API to do your own serialization and deserialization.

I hope this info is helpful.
