### ISSUE TITLE
How to write a method that uses basic data type?

### ISSUE THREAD

**Issue by off99555** [grpc/grpc#22219]
Suppose I want to define a method which accepts a float and returns a float,
I can do it like this:
```
message Number {
    float value = 1;
}

service Calculator {
    rpc SquareRoot(Number) returns (Number) {}
}
```

But it means that I need to define `message` for every basic data types like `double`, `int`, `bool`, etc.
Is there a way to define the method to use basic data types like `float` without defining a new message?
E.g. ```rpc SquareRoot(float) returns (float) {}```

**Comment by markdroth** [comment]
I'm not sure why this issue didn't get assigned to the default assignee, but that's why no one noticed it until now.

You could use the existing wrappers that ship with the protobuf library:

https://github.com/protocolbuffers/protobuf/blob/master/src/google/protobuf/wrappers.proto

If you have further questions, please ask on the grpc.io mailing list.  Thanks!
