### ISSUE TITLE
Floating Point Precision (Node)

### ISSUE THREAD

**Issue by CWSpear** [grpc/grpc#2227]
Using the Node `grpc` module, when things go through the `encode`/`decode` functions, floating point precision is lost.

Reduced test case:

**index.js**
```js
'use strict';

var assert = require('assert');

var grpc = require('grpc');

var rawProto = require.resolve('./float.proto');
var FloatTest    = grpc.load(rawProto).test.FloatTest;

var data = {
	float: 11.11
};

var floatTestInstance = new FloatTest(data);

// same result if the .toBuffer() is left off
var buffer = floatTestInstance.encode().toBuffer();

var decoded = FloatTest.decode(buffer);

assert.deepEqual(decoded, data);
```

--

**float.proto**
```proto
syntax = "proto3";

package test;

message FloatTest {
	float float = 1;
}
```

--

**Result**
```
$ node index
```
```js
// expected:
{"float":11.11}

// actual
{"float":11.109999656677246}
```

--

I'm not a JavaScript "Floating Point Precision" expert, but is there anything that can be done on the `grpc` end? We are using `encode` and `decode` to put messages into `kafka` and the other end doesn't necessarily know what the precision should be.

Tested on Node `0.10.38` and `grpc` versions `0.8.0` and `0.9.2` (latest at the time of this writing).

**Comment by murgatroid99** [comment]
The problem is exactly as you put it: JavaScript Floating Point Precision. JavaScript uses standard (IEEE 754 double precision) floating point numbers, the same type that most major languages call `double`. That type cannot precisely represent all numbers, and what you are seeing is just an artifact of that.

If you need to communicate a precise decimal number, your best bet is to represent it as a string.

**Comment by CWSpear** [comment]
@murgatroid99 yeah, that's what I figured. This is stuff above my paygrade, so I didn't know if it was possible to use https://github.com/dtrebbien/BigDecimal.js behind the scenes or something.

Very interesting sidenote: my buddy convinced me to try it with `double` instead of `float` and I was like 100% sure it was on the JS side and wouldn't make a difference since JS doesn't distinguish between those types.

...but lo and behold, using the same exact code above, but using `double` instead of `float`, the assertion passes!

**Comment by murgatroid99** [comment]
Upon re-reading your code, I realize that using `double` should work, but not because it actually represents the number precisely. When you `encode`, you convert the number to a `float`, which is a narrowing conversion (because floats are only 32 bits long, and doubles are 64 bits long), and than changes the value. On the other hand, when you use `double`, it's using the same representation throughout. Basically, you're confirming that when you take the `double` representation of `11.11`, convert it to a `double`, then convert it back to a `double`, you end up with the same number.

**Comment by CWSpear** [comment]
So the loss of precision is in the *encoding*, not in the *decoding* (which is what I assumed)...? Cuz like you said, JavaScript doesn't *have* a distinction between `double` and `float`.

**Comment by murgatroid99** [comment]
Yes, it effectively has to round the number to fit it in a `float`.

**Comment by CWSpear** [comment]
Alright. Well, hopefully at least this ticket helps someone else in the future!

To future posterity: `float` and `double` *can* make a difference in the Node implementation of `grpc`!
