### ISSUE TITLE
Missing interceptor changes to metadata for streaming requests(Ruby)

### ISSUE THREAD

**Issue by glupo** [grpc/grpc#22448]
### What version of gRPC and what language are you using?
Lang: Ruby
Version: reproduces on 1.27 and master

### What operating system (Linux, Windows,...) and version?
MacOs

### What did you do?
Tried to modify client streaming request metadata by interceptor while calling `client_streamer` on ClientStub with `request_op: true`

### What did you expect to see?
Added interceptor changes in request

### What did you see instead?
Request comes to server without any changes to metadata made by interceptors

### Anything else we should know about your project / environment?
This happens because of
https://github.com/grpc/grpc/blob/30f88e8b762be8bb677c5edd3ae6c20439d7a0d6/src/ruby/lib/grpc/generic/client_stub.rb#L249
lacking metadata in it. Having that all streaming actions has this code(in case `request_op` is selected - metadata merged into `ActiveCall` instance before interceptor run and then never passed) I'd assume this is intended but I'm struggling to find a reason why

**Comment by nplusp** [comment]
@apolcyn hey, me too wants to understand this. 
Can you please share some information with us?

**Comment by zFlux** [comment]
Reviving this issue — I've opened a fix in #42073 that addresses the root cause. It follows the same approach as @apolcyn's earlier attempt in #25072, which was closed by the stale bot before being merged. The fix ensures interceptor metadata is correctly passed through for all three streaming call types when `return_op: true` is used. Would appreciate any review or feedback.
