### ISSUE TITLE
ASAN failures in SSL-related tests

### ISSUE THREAD

**Issue by markdroth** [grpc/grpc#22454]
https://source.cloud.google.com/results/invocations/ed10fe5c-bd90-42b9-8f7c-d900f51a1f90/targets

A huge number of core end2end tests seem to be failing under ASAN.  Is this the result of some recent change to the SSL code?

**Comment by ZhenLian** [comment]
I  will take a look right now. Thanks for pointing it out!

**Comment by ZhenLian** [comment]
It looks like the explicit reason for this error is [here](https://github.com/grpc/grpc/blob/master/src/core/lib/security/credentials/ssl/ssl_credentials.cc#L234), which is due to the failing of [this line](https://github.com/grpc/grpc/blob/master/src/core/lib/gpr/string.cc#L45). It looks like the failure is due to some changes in test certificates.
Hi @jiangtaoli2016 , could you please take a look if this is because of some recent changes we have in test credential?

**Comment by jiangtaoli2016** [comment]
Fix here https://github.com/grpc/grpc/pull/22456

**Comment by markdroth** [comment]
Thanks for fixing!
