### ISSUE TITLE
build_docker_node failure

### ISSUE THREAD

**Issue by markdroth** [grpc/grpc#22522]
https://source.cloud.google.com/results/invocations/87aaac90-6141-41b0-944c-d3dd296b30af/targets/github%2Fgrpc%2Finterop_docker_build/tests

```
Failed to recurse into submodule path 'packages/grpc-native-core/deps/grpc/third_party/protobuf'
Failed to recurse into submodule path 'packages/grpc-native-core/deps/grpc'
Stopping at 'packages/grpc-native-core/deps/grpc'; script returned non-zero status.
```

**Comment by donnadionne** [comment]
build_docker_node has been healthy for the past 14+ days.

There has been failures in toprod https://fusion.corp.google.com/projectanalysis/summary/KOKORO/prod%3Agrpc%2Fcore%2Fmaster%2Flinux%2Fgrpc_interop_toprod
as well as tocloud
https://fusion.corp.google.com/projectanalysis/summary/KOKORO/prod%3Agrpc%2Fcore%2Fmaster%2Flinux%2Fgrpc_interop_tocloud

But it has not been due to Node
