### ISSUE TITLE
Latest Unity Build Bitcode Disabled

### ISSUE THREAD

**Issue by cg-adam** [grpc/grpc#22534]
### What version of gRPC and what language are you using?
GRPC Unity 2.29.0

### What operating system (Linux, Windows,...) and version?
MacOS 10.14.6

### What runtime / compiler are you using (e.g. python version or version of gcc)
Unity 2019.2.17f1

### What did you do?
Built unity project using latest GRPC version (2.29.0)

### What did you expect to see?
Generated XCode project would build with Bitcode support enabled

### What did you see instead?
Generated XCode project complained that the GRPC libraries were not built with Bitcode support

### Anything else we should know about your project / environment?
A working version was found under an Issue or PR thread on GitHub, but was for 2.24.0 and was custom built and uploaded by a community member. Please can we get a version supported with Bitcode?

**Comment by jtattermusch** [comment]
The bitcode embedding was disabled in https://github.com/grpc/grpc/pull/20233 because 
it lead to a huge increase in size for libgrpc.a (which is part of Grpc.Core nuget and we're trying to keep it small).

Until we figure out a way to enable bitcode without impacting the size of Grpc.Core nuget that much, bitcode will stay disabled.

https://github.com/grpc/grpc/blob/f7591a3426becbed20dbd1a80beb9c1e2ca1a738/src/csharp/experimental/build_native_ext_for_ios.sh#L31

**Comment by jtattermusch** [comment]
Workaround: You can build a custom version of libgrpc.a with a one line change of the build script (see #20233 for details)

**Comment by bartutiryakioglu** [comment]
I am trying to build the latest available unity package with bitcode enabled. When I tried to follow the instructions in the commit #6753812278. I only get macOS native libgrpc.a file under makefile folder by running python3.9 run_tests.py -l csharp -c dbg --build_only. Should I run something else or look for somewhere else to build unity package?
