### ISSUE TITLE
C++ v1.19.0 and v1.28.0 Segfault at MetadataMap::destroy() when trying to unit test

### ISSUE THREAD

**Issue by rainerillichmann** [grpc/grpc#22551]
### What version of gRPC and what language are you using?
Currently using v1.19.0 but also tried in v1.28.0

### What operating system (Linux, Windows,...) and version?
CentOS Linux release 7.7.1908

### What runtime / compiler are you using (e.g. python version or version of gcc)
gcc 7.3.1

### What did you do?
Trying to unit test grpc functions in gtest

```
TEST_F(ServerFunctionTest, ServerFunctionOK){
    Request req;
    Reply Rep;
    ServerContext ctx;
}
```

### What did you expect to see?
no Segfault

### What did you see instead?
 ServerContext Destructor throws a SegFault at grpc::internal::MetadataMap::destroy()

![image](https://user-images.githubusercontent.com/15648617/78236150-e8c26280-74d9-11ea-9485-531b14faf564.png)

**Comment by vishnu3649m** [comment]
Hi! I encountered the same issue when unit testing my service like so:

```cpp
TEST_F(ImageDetectionServiceTest, CheckIfSomethingWorks) {
    ImageDetectionService service;
    grpc::ServerContext context;
    VA::Grpc::ImageDetectionRequest request;
    VA::Grpc::ImageDetectionResponse response;

    grpc::Status status = service.SomeRpc(&context, &request, &response);

    ASSERT_TRUE(status.ok());
}
```

The segfault occurs at the exact same place reported by @rainerillichmann because of this in `include/grpcpp/impl/codegen/metadata_map.h` line 84:
```cpp
void Destroy() {
    g_core_codegen_interface->grpc_metadata_array_destroy(&arr_);
}
```
When `MetadataMap` is destroyed, it is attempting to access the global instance `g_core_codegen_interface` which is only initialized when a server is built and started (which I am not doing for the purpose of merely testing my service's logic).

I got around this by doing:
```cpp
void Destroy() {
    if (g_core_codegen_interface != nullptr)
        g_core_codegen_interface->grpc_metadata_array_destroy(&arr_);
}
``` 
but this global instance is being referenced in 119 places within the codebase. So I'm not sure if this should be done throughout the codebase?

Or is it fine to put in a nullptr check here to allow people to unit test this way? If not, are there any suggestions for how we could unit test services?

**Comment by veblush** [comment]
@vishnu3649m Thank you for the detailed information. I think your change would be dangerous by having memory_leak  so initializing `g_core_codegen_interface` would be the right way to address it. Can you cherry-pick #25759 to see if it's actually working for you?

**Comment by vishnu3649m** [comment]
Yes this fixed it! Thanks!

**Comment by HuaxinTang** [comment]
@rainerillichmann，@vishnu3649m , Could you share the complete unit test case which you found this issue to me? I want to repreduce this issue. thanks.
