### ISSUE TITLE
grpcio-1.28.1 fails to install for manylinux1_compatible

### ISSUE THREAD

**Issue by somethingnew2-0** [grpc/grpc#22581]
### What version of gRPC and what language are you using?
grpcio-1.28.1 Python

### What operating system (Linux, Windows,...) and version?
Linux Alpine

### What runtime / compiler are you using (e.g. python version or version of gcc)
Python 3.7

### What did you do?
Please provide either 1) A unit test for reproducing the bug or 2) Specific steps for us to follow to reproduce the bug. If there’s not enough information to debug the problem, gRPC team may close the issue at their discretion. You’re welcome to re-open the issue once you have a reproduction.

### What did you expect to see?
Something like the previous version that installs correctly
```
 docker run -it python:3.7-alpine /bin/sh
/ # echo "manylinux1_compatible = True" > /usr/local/bin/_manylinux.py
/ # pip install grpcio==1.27.2
Collecting grpcio==1.27.2
  Downloading grpcio-1.27.2-cp37-cp37m-manylinux1_x86_64.whl (2.7 MB)
     |████████████████████████████████| 2.7 MB 1.6 MB/s
Collecting six>=1.5.2
  Downloading six-1.14.0-py2.py3-none-any.whl (10 kB)
Installing collected packages: six, grpcio
Successfully installed grpcio-1.27.2 six-1.14.0
```

### What did you see instead?
```
docker run -it python:3.7-alpine /bin/sh
/ # echo "manylinux1_compatible = True" > /usr/local/bin/_manylinux.py
/ # pip install grpcio
Collecting grpcio
  Downloading grpcio-1.28.1.tar.gz (19.5 MB)
     |████████████████████████████████| 19.5 MB 14.3 MB/s
    ERROR: Command errored out with exit status 1:
     command: /usr/local/bin/python -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-lpvj8z0n/grpcio/setup.py'"'"'; __file__='"'"'/tmp/pip-install-lpvj8z0n/grpcio/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-install-lpvj8z0n/grpcio/pip-egg-info
         cwd: /tmp/pip-install-lpvj8z0n/grpcio/
    Complete output (11 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-lpvj8z0n/grpcio/setup.py", line 191, in <module>
        if check_linker_need_libatomic():
      File "/tmp/pip-install-lpvj8z0n/grpcio/setup.py", line 152, in check_linker_need_libatomic
        stderr=PIPE)
      File "/usr/local/lib/python3.7/subprocess.py", line 800, in __init__
        restore_signals, start_new_session)
      File "/usr/local/lib/python3.7/subprocess.py", line 1551, in _execute_child
        raise child_exception_type(errno_num, err_msg, err_filename)
    FileNotFoundError: [Errno 2] No such file or directory: 'cc': 'cc'
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.

```
Make sure you include information that can help us debug (full error message, exception listing, stack trace, logs).

See [TROUBLESHOOTING.md](https://github.com/grpc/grpc/blob/master/TROUBLESHOOTING.md) for how to diagnose problems better.

**Comment by gnossen** [comment]
@somethingnew2-0 This is intended. See [the announcement](https://groups.google.com/g/grpc-io/c/VdoTPMT5WwU) from December. In order to take advantage of newer features in the gRPC C extension, we've dropped support for `manylinux1` starting with the 1.28 release and have moved to `manylinux2010` instead.

CC @veblush

**Comment by somethingnew2-0** [comment]
@gnossen that announcement is a 404 for me, but thanks for the information and the quick response!

I'll use the `manylinux2010` artifact for now, but we'll probably be moving from alpine to distroless for our docker image soon which is based on Debian10.

Thanks again @veblush and @gnossen!

**Comment by veblush** [comment]
This [link](https://groups.google.com/d/msg/grpc-io/VdoTPMT5WwU/fMmXxFiBAwAJ) would work.

**Comment by veblush** [comment]
FYI, gRPC python can be built from a source package, too. This can be done by installing prerequisite packages before installing grpcio on the same alpine docker image.

```
/ # apk get g++ linux-headers
/ # pip install grpcio
...
Installing collected packages: grpcio
Successfully installed grpcio-1.28.1
```

**Comment by xijiz** [comment]
> This [link](https://groups.google.com/d/msg/grpc-io/VdoTPMT5WwU/fMmXxFiBAwAJ) would work.

It works. Thank you!!

**Comment by leon0204** [comment]
> > This [link](https://groups.google.com/d/msg/grpc-io/VdoTPMT5WwU/fMmXxFiBAwAJ) would work.
> 
> It works. Thank you!!

pip3 install --upgrade pip && pip3 install grpcio==1.28.1
WARNING: pip is being invoked by an old script wrapper. This will fail in a future version of pip.
Please see https://github.com/pypa/pip/issues/5599 for advice on fixing the underlying issue.
To avoid this problem you can invoke Python with '-m pip' instead of running pip directly.
Looking in indexes: https://pypi.tuna.tsinghua.edu.cn/simple
Collecting grpcio==1.28.1
  Downloading https://pypi.tuna.tsinghua.edu.cn/packages/f3/97/f74da84d4db8cfe95f9b6aa2469be79af1873fec1adb80405105ed99a0a8/grpcio-1.28.1-cp36-cp36m-manylinux2010_x86_64.whl (2.8 MB)
     |████████████████████████████████| 2.8 MB 114 kB/s
Requirement already satisfied: six>=1.5.2 in /usr/lib/python3.6/site-packages (from grpcio==1.28.1) (1.11.0)
Installing collected packages: grpcio
Successfully installed grpcio-1.28.1


Successfully ~
