### ISSUE TITLE
C++ Async APIs should receive 'const void *' tags rather than 'void *'

### ISSUE THREAD

**Issue by hedayat** [grpc/grpc#22782]
In my code, I use const objects as tags, but since current API receives 'void *' tags, I should cast away constness; which is not nice. As GRPC doesn't actually even reference the tag, it seems reasonable that it receives `const void *` tags rather than 'void *'

**Comment by vjpai** [comment]
That's reasonable. It doesn't break API. Technically, it's just the tiniest extension to API so it does need a gRFC but I imagine that it would be a small gRFC and a small PR. The history is that the gRPC core API has to just use `void *` because it is C89, but there is no reason why the C++ layer can't use `const void*` and then drop the constness internally like we do with other core interactions (e.g., grpc_byte_buffer usages).
