### ISSUE TITLE
How to set window size 

### ISSUE THREAD

**Issue by NicoChenyt** [grpc/grpc#22889]
### Is your feature request related to a problem? Please describe.

When client receiving a large messages, it report: 

```
Incoming frame of size 96014 exceeds local window size of 65535.
The (un-acked, future) window size would be 4194304 which is not exceeded.
This would usually cause a disconnection, but allowing it due tobroken HTTP2 implementations in the wild.
See (for example) https://github.com/netty/netty/issues/6520
```

### Describe the solution you'd like

Make window size configurable like [this](https://github.com/grpc/grpc-go/pull/1210)

### Additional context

language: php
grpc version: 1.27

**Comment by markdroth** [comment]
Yash, it doesn't look like we have a way to set the initial HTTP/2 window size.  Go obviously has this, but maybe check with Java too and decide if this is something that we should support across languages.

**Comment by yashykt** [comment]
@ejona86 @dfawley Thoughts on this?

**Comment by ejona86** [comment]
I thought y'all already had a knob, because I remember discussing with Craig how the knob interacted with BDP estimation. It looks like `GRPC_ARG_HTTP2_STREAM_LOOKAHEAD_BYTES` may tune the window size?

Although changing the window size doesn't seem like it would fix the error reported, as the race is possible any time the size changes. `GRPC_ARG_HTTP2_BDP_PROBE` would avoid the issue, but I would not recommend that at all.

Since that issue in the message text is from 2017, I wouldn't expect people to hit it today. @NicoChenyt, do you know the grpc server language and version? Are there any proxies being used? I am suspicious there is a newcomer to the HTTP/2 world that has a bug.

**Comment by yashykt** [comment]
Haha! GRPC_ARG_HTTP2_STREAM_LOOKAHEAD_BYTES (iirc) does not work as expected with BDP enabled (which is the default). I assumed that the want was to control the initial window size even when bdp is enabled.

Also, BDP is enabled in gRPC Core by default, and has been our recommendation for quite some time now  :D

**Comment by dfawley** [comment]
In Go the window size can be set explicitly, which overrides our BDP estimation.  We don't recommend this option for most users for that reason.

**Comment by ejona86** [comment]
> GRPC_ARG_HTTP2_STREAM_LOOKAHEAD_BYTES (iirc) does not work as expected with BDP enabled (which is the default)

What do you mean "as expected"? How does it behave and what would be expected?

I thought it set the initial window size, and then BDP could increase the window size further.

**Comment by NicoChenyt** [comment]
> @NicoChenyt, do you know the grpc server language and version? Are there any proxies being used? I am suspicious there is a newcomer to the HTTP/2 world that has a bug.

@ejona86  PHP 7.x + [Swoole](https://github.com/swoole/swoole-src) 4.4.17 ,  no proxy

**Comment by ejona86** [comment]
@NicoChenyt, just for sanity, can you confirm that grpc-java is version than 1.4+ (which wouldn't have the bug).

If it is a direct connection between grpc-php and grpc-java, then a bug has cropped up. That said, I'm suspicious as to why we haven't heard more reports about such an issue.

> Incoming frame of size 96014 exceeds local window size of 65535.

This is weird. How is the window 64k. @yashykt, will C _reduce_ its window size over time?

**Comment by yashykt** [comment]
@dfawley @ejona86 Sorry for the confusion here.

I said GRPC_ARG_HTTP2_STREAM_LOOKAHEAD_BYTES does not work as expected since the value provided is quickly overwritten by the value calculated by BDP, and hence we see the number 4194304 in the log message. Just from that number being present, I am assuming that bdp ping has been enabled.

@NicoChenyt , can you confirm what kind of gRPC server we are using here? @ejona86's last message seems to suggest that grpc java is being used here.

>This is weird. How is the window 64k. @yashykt, will C reduce its window size over time?
@ejona86 , why do you think that C has reduced the window size here? I believe what is happening here is that the php client has not yet received the ack for the initial window size of 4MB. Consequently, the acked window size (default of 64k) is smaller than the window size of 4MB which the client has advertised.

@NicoChenyt This would also mean that being able to configure the window size is not going to help avoid the log message that you are seeing. (Note that even though the message is being logged out the php client would still have accepted the message.)

**Comment by ejona86** [comment]
> I believe what is happening here is that the php client has not yet received the ack for the initial window size of 4MB

Ah, no SETTINGs ack would bring in the default 64k for INITIAL_WINDOW_SIZE. That seems fair, since nothing else is using 64k.

**Comment by NicoChenyt** [comment]
Sorry, it's my mistake.
@yashykt   we use [swoole](https://github.com/swoole/swoole-src) + php as gRPC server.
I set 'http_compression' as false in swoole. And when I set it as true it works well

**Comment by yashykt** [comment]
@NicoChenyt I would caution you that simply enabling compression is not going to fix the issue at hand here. The actual issue is that the server is potentially reordering frames such that it uses the new window size before sending the settings ack frame.

**Comment by yashykt** [comment]
This should be raised as an issue with the swoole implementation. Is this https://github.com/swoole/grpc what you are referring to?

**Comment by MartinKosicky** [comment]
If latency is bigger and the payload is larger, setting initial window size larger can lower the request time significantly.  That is what helped us when we had let's say 15 seconds timeout on whole request, and the destination server was in another continent, and payload was large.  The 64k window size caused the request to take like 60 seconds and more,  decreasing it was like few seconds (1GB ethernet link and send 20 MB for 60 seconds is insane)
