### ISSUE TITLE
Adhoc interop tests are running out of space

### ISSUE THREAD

**Issue by nicolasnoble** [grpc/grpc#23008]
I've poked at it a bit, but without too much happy result. #22967 is currently failing due to running out of space when downloading the new docker image files: https://source.cloud.google.com/results/invocations/dc61bd22-6253-48e8-b99c-e5cab1831f27/log (the failure is far up the log, one needs to download the full log to see it properly)

**Comment by jtattermusch** [comment]
Basically the issue is that we already have too many versions that are being tested and the way the test script works is to download all the images for a language first and after that we run all the tests for that language:
https://github.com/grpc/grpc/blob/a43082112f5a2e4ef475c8b9c364ca08349e201b/tools/interop_matrix/run_interop_matrix_tests.py#L302
https://github.com/grpc/grpc/blob/a43082112f5a2e4ef475c8b9c364ca08349e201b/tools/interop_matrix/run_interop_matrix_tests.py#L206

We'd need to modify the script to only download a bunch of releases for a given language at a time

**Comment by jtattermusch** [comment]
@gnossen  can you take a look?

**Comment by gnossen** [comment]
#23285 should resolve this.
