### ISSUE TITLE
Grpc.Core.targets dependency chain issue

### ISSUE THREAD

**Issue by mrtristan** [grpc/grpc#23059]
lang: c#
area: packaging/distribution
version: 2.28.1
platform: windows

this still seems to be a problem:
https://github.com/grpc/grpc/issues/12926
https://github.com/grpc/grpc/pull/13772

I have a netstandard2.0 class library that has grpc components in it. when this library is consumed by a netframework472 class library and then ultimately a net472 app, the files mentioned in `Grpc.Core.targets` get dropped at the root of the app project. ~My app devs are also mentioning some crashes when it gets to the point of trying to interact with some grpc functions of the app, not sure yet if that's related.~

the files that are landing at the root of the app are also getting project references added:

![image](https://user-images.githubusercontent.com/1546181/83040235-0a892300-a00d-11ea-9e99-289d83f8a97d.png)

---
sidebar unrelated crash issue: https://github.com/grpc/grpc/issues/18203
grpc does not play nice on windows if there is a reference to unity it seems? we had a reference to 
https://github.com/codebude/QRCoder at 1.3.3 which internally has a unity reference so grpc would blow up. grpc stopped internally throwing once updating qrcoder to 1.3.9 as they've removed the unity reference

**Comment by mrtristan** [comment]
cc @jtattermusch

**Comment by jtattermusch** [comment]
I think my PR https://github.com/grpc/grpc/pull/13772 got closed because I tested the changes and they didn't work. The thing about <Content> items is that they are included transitively (if a project gets reference by another project), which matches the behavior we need for copying the native libraries (if a project B depends on project A and project A needs grpc, project B also needs the grpc native libraries and the <Content> tag is the only way I know of to make that work for .NET desktop projects).
Unless there's a suggestion how to avoid the native libraries showing the VS UI, but still making sure they are added as a transitive dependency, this issue is not actionable.

**Comment by mrtristan** [comment]
@jtattermusch definitely agree with it being a transitive dependency. i think the issue is just that they're landing at the root of the project _in addition_ to landing in the bin.

if that's what you're saying, then apologies.

I'm not familiar with every nuance of the build processes, but feeling like it must be as simple as changing how they're being included to achieve this. However, i noticed jon skeet had a hand in the inclusion of these files so perhaps that really is the way that it is... 😉

**Comment by yashykt** [comment]
Closing this issue, but feel free to reopen it if you feel that there is something to be done here.

**Comment by jtattermusch** [comment]
@mrtristan  if we come up with a way to change the .targets file to make native libraries copying work transitively and prevent them from showing up in the VS UI at the same time, we can do it.
But as said, I am aware of such way.
Also note that this problem only exists for .NET desktop framework projects (which are going away at some point), not for the .NET core apps.
