### ISSUE TITLE
Decryption error: TSI_DATA_CORRUPTED

### ISSUE THREAD

**Issue by sjkummer** [grpc/grpc#23144]
# What version of gRPC and what language are you using?
grpc-node 1.24.2

### What operating system (Linux, Windows,...) and version?
```
  Operating System: Debian GNU/Linux 10 (buster)
            Kernel: Linux 5.4.42-v8+
      Architecture: arm64

openssl:arm64/buster 1.1.1d-0+deb10u3 uptodate
```

### What runtime / compiler are you using (e.g. python version or version of gcc)
node

### What did you do?
As GRPC-Client, connecting to a Server using Server-Side SSL encryption. Using duplex streaming.

### What did you expect to see?
A stable connection.

### What did you see instead?
recurring disconnects:
```
ssl_transport_security.cc:483] Corruption detected.
ssl_transport_security.cc:459] error:14187180:SSL routines:ssl_do_config:bad value
secure_endpoint.cc:208]     Decryption error: TSI_DATA_CORRUPTED
```

### Anything else we should know about your project / environment?

This seems to be related to the environment. I can reproduce this on a Raspberry Pi 3 having Debian 10 (arm64) installed. When using Ubuntu 18 (arm64) instead on the same device, the problem does not occur.

Therefore my question: 
_What system libraries (or certs) are used by the C++ layer? And which version of this library would you recommend to use?_

Additional info:
Seems like unary calls are working, just (duplex) streaming is affected.

I have seen this decryption error was already mentioned in other tickets / environments, but seems like they never got fixed: #12642 #15506

**Comment by sjkummer** [comment]
@veblush Does GRPC use a system SSL library (e.g. openssl) or not?

**Comment by fallard84** [comment]
We also started to encounter this issue a few days ago. It seems to correlate around the time `curl` was also installed as a middleware on the same Docker image. We will upgrade our dependencies which depends on grpc to use the latest version of the pure JS implementation of grpc (@grpc/grpc-js).

**Comment by andu1c** [comment]
We started seeing a lot of these `TSI_DATA_CORRUPTED` errors for the past two weeks on our python client that makes grpc calls to a `go` service. If it is helpful, I could provide more details but just want to flag that this seems to be a rising issue.

**Comment by ZhenLian** [comment]
@sjkummer Did you see the error message on server or client side? And were your client and server both written in nodejs? If before you made changes in openssl config, the connections failed consistently, we probably could start from solving that issue first.

**Comment by andu1c** [comment]
We see the error messages on the client side, which is written in `python`. The server is written in `go`. The `TSI_DATA_CORRUPTED` doesn't come up all the time. Some time it comes up a couple of times and our client can get through them by retrying. However, there are times that it comes up repeatedly and retry won't work. The client ended up failing after hundreds of tries.

**Comment by sjkummer** [comment]
@ZhenLian Thanks for looking into the issue.

The error occurs on client side. Both, client and server use Node.js (common code project).
At the beginning (clean OS install), the error occured conistently (every duplex streaming request failed).
Later, I realized the default openssl config on Debian 10 is different from Ubuntu 19.10 (which worked fine for months). Debian 10 got an additional `MinProtocol` and `CipherString` entry. After I removed both, the connection is pretty stable.

To clarify: Debian 10 was used on client side when the problem occured. Server is Ubuntu 19.10.

**Comment by ZhenLian** [comment]
@sjkummer thanks for the clarification! And glad to know the issue went away. I will surely document this somewhere once I sort all this out. 
AFAIK, the underlying core has two options for doing the TLS operations: use a built-in BoringSSL third-party dependency, or a system OpenSSL lib. I am not familiar with the wrap languages, but apparently your node environment is using system OpenSSL. Since the system OpenSSL lib is something out of our control, (I think) maybe it's more preferable to use built-in BoringSSL if possible?

@jtattermusch Hi Jan, can I know in Node, is there a way to know what's the currently using SSL library(built-in BoringSSL or system OpenSSL)? and is there a way to switch between the two? Thanks!

**Comment by ZhenLian** [comment]
@andu1c @fallard84 Can I know if the problem is still there? Could it be possible that it was due to the same OpenSSL misconfigurations, as mentioned above?

**Comment by andu1c** [comment]
I'm not sure if it's due to OpenSSL misconfigurations as we didn't go deep on that direction (maybe we should have!). We ended up not using TLS for that one specific connection to get around this `TSI_DATA_CORRUPTED` error. We're good for now but we know that turning off TLS is not the long term solution. Fortunately for us, we will retire this connection soon as a part of a bigger architecture change in our services so we're not pursuing this further for the time being. 

I'm still interested in following up to see how this will be resolved though.

**Comment by devjgm** [comment]
We're seeing these same errors with C++ libraries using grpc and openssl on debian buster, which is causing us to have to disable one of our builds/tests. See https://github.com/googleapis/google-cloud-cpp/issues/4018.

Should we expect that gRPC is _supposed_ to work on Debian buster with OpenSSL? Are we doing something wrong, or is this a gRPC/OpenSSL bug?

**Comment by ZhenLian** [comment]
@devjgm Thanks for bringing up the error! From the original issue page, it seems the issue was solved by using CMake or Bazel? IIUC, these two are the recommended ways to build gRPC(https://github.com/grpc/grpc/blob/master/BUILDING.md#clone-the-repository-including-submodules). Can I know what was the build tool that caused the problem?

About the OpenSSL, if I understand correctly, both the CMake and Bazel will "build the dependency using sources from git submodule"(reference for CMake: https://github.com/grpc/grpc/blob/364461aab0a352c43ed93f77a18907f95be709dc/templates/CMakeLists.txt.template#L178-L192), so it won't actually use the system-installed OpenSSL, but will use the BoringSSL built inside gRPC, if not provided with some custom configurations. 
The error message is about encryption, but most of the root causes under this page were actually some misconfiguration of system-installed OpenSSL. I am guessing that's due to gRPC somehow uses system-installed OpenSSL, which is not properly configured, and hence caused that encryption error. The easiest way might be just switching to a build system that will use built-in BoringSSL.
CC @veblush in case I misunderstand the way how OpenSSL/BoringSSL is linked in...

**Comment by prashantskit** [comment]
I am also getting this error. I am not directly using grpc, I am using google api python package to generate text to speech that package internally uses grpc. What is the solution I can try, since the thread is already closed?
Python version is 3.7 
Go version - go1.18.2
google-cloud-texttospeech==2.14.1

**Comment by nanonyme** [comment]
@prashantskit open new issue with high-quality problem description and preferably easy way for grpc developers to repro?
