### ISSUE TITLE
gRPC for c (not cpp)

### ISSUE THREAD

**Issue by lioriz** [grpc/grpc#23160]
Hi,
I'm i have server/client written in c.
I don't see any support for c, only cpp.

**Comment by gnossen** [comment]
Juniper has written [gRPC C bindings](https://github.com/Juniper/grpc-c) that you may be interested in.

**Comment by lioriz** [comment]
I seen Juniper Project, it haven't been updated since May 2018.
I can't rely on it in my project.
For now my best solution is to convert my code to CPP or to wrap gRPC-C++ in C code mtself.

**Comment by lioriz** [comment]
> We've talked about doing this several times, but it's never been a high enough priority to actually make it happen. And unfortunately, I don't see this changing any time soon. If you want to contribute something, feel free to start by putting together a [gRFC](https://github.com/grpc/proposal) for a C API.
> 
> Sorry that we can't be of more help.

Hi
Will be happy to contribute gRPC C API.
How can I start?

**Comment by markdroth** [comment]
This would be a pretty significant undertaking.  You'd have to write a gRFC proposing the C API, go through the review process for that, and then implement the whole C API.  If you want to use this with protobuf, you would probably also need to write a protobuf compiler plugin to generate a C protobuf API (or maybe use something like upb for that).

**Comment by lioriz** [comment]
I would like to take part of something like that.
where do you think it would be best to start?
protobuf or gRPC?

**Comment by markdroth** [comment]
I don't think the protobuf folks are interested in providing a C API, but there are libraries like upb that have a C API.  Unfortunately, upb does not yet offer a stable API, but you could talk to @haberman about when that might happen.  Alternatively, if all you need is a C API (i.e., it's okay for the underlying implementation to still be C++, which I assume is true if you're able to use a C wrapper around gRPC, since it's also written in C++), then you might be able to write a protobuf compiler plugin to generate that.  I'm not sure whether or not that would be sufficient, but you'd probably need to do one of those two things if you want to use protobuf via a C API.

Separately from that, you will need to write a gRFC to design the gRPC C API.  The gRPC API should be independent of protobuf, because it should be able to work with any IDL, just like the gRPC API in other languages.

These two pieces are more or less independent, so I don't think it matters where you start.
