### ISSUE TITLE
Cannot check peer: missing selected ALPN property in python client (grpcio)

### ISSUE THREAD

**Issue by hjwp** [grpc/grpc#23172]
### What version of gRPC and what language are you using?
python grpcio `1.29.0`

### What operating system (Linux, Windows,...) and version?
bug seen on debian buster and ubuntu focal

### What runtime / compiler are you using (e.g. python version or version of gcc)
Python 3.8

### What did you do?
connecting to a grpc server with self-generated ssl certs.  full repro available at https://github.com/hjwp/eventstoreio/tree/alpn-bug, should be a single command to repro (`make test`) using docker.

### What did you expect to see?
a successful connection

### What did you see instead?

Python stack trace:
```
E   grpc._channel._MultiThreadedRendezvous: <_MultiThreadedRendezvous of RPC that terminated with:
E   	status = StatusCode.UNAVAILABLE
E   	details = "failed to connect to all addresses"
E   	debug_error_string = "{"created":"@1591774926.055334184","description":"Failed to pick subchannel","file":"src/core/ext/filters/client_channel/client_channel.cc","file_line":3962,"referenced_errors":[{"created":"@1591774926.055331102","description":"failed to connect to all addresses","file":"src/core/ext/filters/client_channel/lb_policy/pick_first/pick_first.cc","file_line":394,"grpc_status":14}]}"
E   >
```

debug logs:

```
D0610 07:42:06.051285883       1 dns_resolver_ares.cc:503]   Using ares dns resolver
I0610 07:42:06.051583095       1 socket_utils_common_posix.cc:385] Disabling AF_INET6 sockets because ::1 is not available.
I0610 07:42:06.052095702      10 socket_utils_common_posix.cc:341] TCP_USER_TIMEOUT not supported for this platform
I0610 07:42:06.052187919      10 tcp_client_posix.cc:326]    CLIENT_CONNECT: ipv4:192.168.128.2:1113: asynchronously connecting fd 0x5608db1e1c40
I0610 07:42:06.052204158      10 tcp_client_posix.cc:143]    CLIENT_CONNECT: ipv4:192.168.128.2:1113: on_writable: error="No Error"
I0610 07:42:06.052214803      10 tcp_client_posix.cc:106]    CLIENT_CONNECT: ipv4:192.168.128.2:1113: on_alarm: error="Cancelled"
I0610 07:42:06.052235207      10 ssl_transport_security.cc:222]      HANDSHAKE START -       TLS client start_connect  - !!!!!!
I0610 07:42:06.052264721      10 ssl_transport_security.cc:222]                 LOOP -    TLS client enter_early_data  - !!!!!!
I0610 07:42:06.052269364      10 ssl_transport_security.cc:222]                 LOOP -   TLS client read_server_hello  - !!!!!!
I0610 07:42:06.052278849      10 tcp_posix.cc:1566]          WRITE 0x7f6e980063e0 (peer=ipv4:192.168.128.2:1113)
D0610 07:42:06.052285548      10 tcp_posix.cc:1570]          DATA: [snip]
I0610 07:42:06.052308562      10 tcp_posix.cc:1616]          write: "No Error"
I0610 07:42:06.052314530      10 tcp_posix.cc:541]           TCP:0x7f6e980063e0 notify_on_read
I0610 07:42:06.054173605      10 tcp_posix.cc:887]           TCP:0x7f6e980063e0 got_read: "No Error"
I0610 07:42:06.054183765      10 tcp_posix.cc:869]           TCP:0x7f6e980063e0 alloc_slices
I0610 07:42:06.054191069      10 tcp_posix.cc:850]           TCP:0x7f6e980063e0 read_allocation_done: "No Error"
I0610 07:42:06.054198411      10 tcp_posix.cc:680]           TCP:0x7f6e980063e0 call_cb 0x7f6e98003958 0x7f6eab7b1020:0x7f6e98003790
I0610 07:42:06.054211086      10 tcp_posix.cc:683]           READ 0x7f6e980063e0 (peer=ipv4:192.168.128.2:1113) error="No Error"
D0610 07:42:06.054227933      10 tcp_posix.cc:689]           DATA: [snip]
I0610 07:42:06.054254150      10 ssl_transport_security.cc:222]                 LOOP - TLS client read_server_certifi  - !!!!!!
I0610 07:42:06.054288928      10 ssl_transport_security.cc:222]                 LOOP - TLS client read_certificate_st  - !!!!!!
I0610 07:42:06.054293858      10 ssl_transport_security.cc:222]                 LOOP - TLS client verify_server_certi  - !!!!!!
I0610 07:42:06.054323654      10 ssl_transport_security.cc:222]                 LOOP - TLS client read_server_key_exc  - !!!!!!
I0610 07:42:06.054386032      10 ssl_transport_security.cc:222]                 LOOP - TLS client read_certificate_re  - !!!!!!
I0610 07:42:06.054394707      10 ssl_transport_security.cc:222]                 LOOP - TLS client read_server_hello_d  - !!!!!!
I0610 07:42:06.054399817      10 ssl_transport_security.cc:222]                 LOOP - TLS client send_client_certifi  - !!!!!!
I0610 07:42:06.054404562      10 ssl_transport_security.cc:222]                 LOOP - TLS client send_client_key_exc  - !!!!!!
I0610 07:42:06.054752050      10 ssl_transport_security.cc:222]                 LOOP - TLS client send_client_certifi  - !!!!!!
I0610 07:42:06.054760016      10 ssl_transport_security.cc:222]                 LOOP - TLS client send_client_finishe  - !!!!!!
I0610 07:42:06.054775387      10 ssl_transport_security.cc:222]                 LOOP -       TLS client finish_flight  - !!!!!!
I0610 07:42:06.054782998      10 ssl_transport_security.cc:222]                 LOOP - TLS client read_session_ticket  - !!!!!!
I0610 07:42:06.054787910      10 tcp_posix.cc:1566]          WRITE 0x7f6e980063e0 (peer=ipv4:192.168.128.2:1113)
D0610 07:42:06.054796339      10 tcp_posix.cc:1570]          DATA: [snip]'
I0610 07:42:06.054818859      10 tcp_posix.cc:1616]          write: "No Error"
I0610 07:42:06.054824701      10 tcp_posix.cc:887]           TCP:0x7f6e980063e0 got_read: "No Error"
I0610 07:42:06.054828075      10 tcp_posix.cc:879]           TCP:0x7f6e980063e0 do_read
I0610 07:42:06.054832197      10 tcp_posix.cc:541]           TCP:0x7f6e980063e0 notify_on_read
I0610 07:42:06.055157301      10 tcp_posix.cc:887]           TCP:0x7f6e980063e0 got_read: "No Error"
I0610 07:42:06.055168218      10 tcp_posix.cc:879]           TCP:0x7f6e980063e0 do_read
I0610 07:42:06.055175776      10 tcp_posix.cc:680]           TCP:0x7f6e980063e0 call_cb 0x7f6e98003958 0x7f6eab7b1020:0x7f6e98003790
I0610 07:42:06.055179917      10 tcp_posix.cc:683]           READ 0x7f6e980063e0 (peer=ipv4:192.168.128.2:1113) error="No Error"
D0610 07:42:06.055189106      10 tcp_posix.cc:689]           DATA: [snip]
I0610 07:42:06.055205044      10 ssl_transport_security.cc:222]                 LOOP - TLS client process_change_ciph  - !!!!!!
I0610 07:42:06.055211849      10 ssl_transport_security.cc:222]                 LOOP - TLS client read_server_finishe  - !!!!!!
I0610 07:42:06.055221738      10 ssl_transport_security.cc:222]                 LOOP - TLS client finish_client_hands  - !!!!!!
I0610 07:42:06.055227526      10 ssl_transport_security.cc:222]                 LOOP -                TLS client done  - !!!!!!
I0610 07:42:06.055230842      10 ssl_transport_security.cc:222]       HANDSHAKE DONE -                TLS client done  - !!!!!!
I0610 07:42:06.055239580      10 ssl_transport_security.cc:279] Could not get common name of subject from certificate.
D0610 07:42:06.055268495      10 security_handshaker.cc:184] Security handshake failed: {"created":"@1591774926.055262608","description":"Cannot check peer: missing selected ALPN property.","file":"src/core/lib/security/security_connector/ssl_utils.cc","file_line":142}
```

### Anything else we should know about your project / environment?

found this SO post from sept 2019 claiming the latest python client is built against a broken version of openssl https://stackoverflow.com/questions/57397723/grpc-client-failing-to-connect-to-server-with-tls-certificates  -- could that still be true?

[update] - it looks like reverting to grpcio 1.19 may fix/bypass the issue. yes

**Comment by niya3** [comment]
I got `Cannot check peer: missing selected ALPN property` error message while connecting via python client (debian 10, python 3.7, grpc 1.37 build with system openssl lib via https://github.com/grpc/grpc/issues/24252#issuecomment-823092600 )

Fixed it when added `h2` to [`Config.NextProtos`](https://github.com/golang/go/blob/5f1df260a91183c605c08af7b00741d2761b84e4/src/crypto/tls/common.go#L620-L622) to manually specified TLS listener on server like this: [`tls.Config{NextProtos: []string{"h2"}}`](https://github.com/jefferai/golang-alpn-example/blob/cbdded88af1629b75bc320b366df4f51ef83685f/alpnexample.go#L303-L304)

**Comment by ZhenLian** [comment]
Sorry, I somehow missed this issue here. Thanks @niya3 for adding the solution!
Adding a "h2" metadata header could be a temporary solution, but it seems the root cause is actually Python is linked to an older version of OpenSSL/BoringSSL, as pointed out in https://stackoverflow.com/questions/57397723/grpc-client-failing-to-connect-to-server-with-tls-certificates. 
@gnossen @lidizheng I am not very familiar with how Python got linked to its OpenSSL/BoringSSL libraries. Can you please verify if the linking is correct? I suspect this might also be the cause of the "signature algorithm not supported" problem @lidizheng is working on(see the link in the last comment for details)...

**Comment by shireresident** [comment]
I am using the google-ads python package 10.0.0 with Python 3.8 on RHEL7 with openssl version 1.0.2k-fips.

It uses grpcio 1.37.0

When I try to access any functionality I get this error when I turn GRPC debug on.

D0421 16:57:15.427572080 23420 security_handshaker.cc:183] Security handshake failed: {"created":"@1619038635.427538310","description":"Cannot check peer: missing selected ALPN property.","file":"src/core/lib/security/security_connector/ssl_utils.cc","file_line":161}

I am operating in a corporate setting that intercepts all external communication and inserts its own certificates.

It works fine on my local Windows 10 desktop that is also in the same corporate setting.

**Comment by gnossen** [comment]
@ZhenLian 

This is from the 1.37.0 release:

```
00000000003effd0 <OpenSSL_version_num>:
  3effd0:       b8 7f 10 10 10          mov    $0x1010107f,%eax
  3effd5:       c3                      retq   
  3effd6:       66 2e 0f 1f 84 00 00    nopw   %cs:0x0(%rax,%rax,1)
  3effdd:       00 00 00 
```

So [according to their version schema](https://www.openssl.org/docs/man1.1.0/man3/OPENSSL_VERSION_NUMBER.html), we're linked against 1.1.7, [which is the most up-to-date version](https://github.com/google/boringssl/blob/94b477cea5057d9372984a311aba9276f737f748/include/openssl/base.h#L191). I think there's something besides the Boringssl version going wrong here.

**Comment by ZhenLian** [comment]
@gnossen Thanks for the information!
Does python use a hermetic build, such that all users can only use the latest version of BoringSSL that comes within the gRPC repo?
I just wanted to rule out the case where the underlying security library is actually linked to a system-installed out-dated OpenSSL/BoringSSL on users' local machines. As far as I know, it could happen in C++, since C++ allows users to link to their own OpenSSL/BoringSSL by specifying some CMake args. Not sure if Python is in a similar situation here.

**Comment by niya3** [comment]
@gnossen my output is slightly different, but not sure if it is the case. IDK how to decode OpenSSL version from value `0x10107fb8`

```bash
$ pip install -U --force --no-cache grpcio==1.37.0
Collecting grpcio==1.37.0
  Downloading grpcio-1.37.0-cp37-cp37m-manylinux2014_x86_64.whl (4.2 MB)
...
Successfully installed grpcio-1.37.0 six-1.15.0

$ ldd $venv/lib/python3.7/site-packages/grpc/_cython/cygrpc.cpython-37m-x86_64-linux-gnu.so | grep -i -c ssl
0

$ gdb -batch -ex 'x OpenSSL_version_num' $venv/lib/python3.7/site-packages/grpc/_cython/cygrpc.cpython-37m-x86_64-linux-gnu.so
0x428a90 <OpenSSL_version_num>: 0x10107fb8
```

**Comment by gnossen** [comment]
@ZhenLian It's hermetic in the sense that we use a git submodule to pull it in. Updating it to the latest version is part of our release process, but we may not be 100% successful in that. Regardless, I don't think we've ever fallen more than a couple of months behind.

@niya3 You've got the `mov` instruction (`b8`) mixed into the same integer as the version number. That is actually the same as what I posted above. Take a look at the disassembly for that instruction in my comment.

**Comment by gnossen** [comment]
Quick update on my end. I have not been successful in reproducing this so far. It seems that the eventstore image doesn't come up properly in https://github.com/hjwp/eventstoreio/tree/alpn-bug. It complains about an unrecognized "Dev" argument. I tried copying the certs as generated by the example and dropping them into our secure connection example. I couldn't get this working unmodified because neither the CA nor the server cert had a CN. By adding these, I was able to get a passing test, but still no repro.

@niya3 @shireresident Any tips on how we might be able to reproduce?

**Comment by shireresident** [comment]
@gnossen I got the error when I was accessing the google-ads python client library which in turn uses grpcio. All I was doing was making a call to the API. Now we do seem to use SSL bridging because I see the certificate is issued by my company when I access any googleads.googleapis.com from the server. I am going to check out with our network team.

**Comment by niya3** [comment]
@gnossen i've created MVP and reproduced the issue using docker image. Please take a look at this repo with code and instructions https://github.com/niya3/grpc_tls_alpn_h2_issue

**Comment by niya3** [comment]
i've [updated](https://github.com/niya3/grpc_tls_alpn_h2_issue/commit/cac1d02a181fb4436d1d54c70770370998a1942f?branch=cac1d02a181fb4436d1d54c70770370998a1942f&diff=unified#diff-366e46a40f6f60b4f7614eb0976bb51820364bf5ca6ccc4787eb49d7bdbef3e6R51-R53) demo repo - issue can be easily mitigated passing TLS config not via `tls.NewListener` but via `grpc.Creds`:

```golang
	tlsCredentials := credentials.NewTLS(tlsConfig)
	opts = append(opts, grpc.Creds(tlsCredentials))
	srv := grpc.NewServer(opts...)
```

**Comment by gnossen** [comment]
@niya3 I was able to reproduce using your example! Thanks for the help! 🙂 

 I'll keep you updated as we figure out more.

**Comment by eckara** [comment]
@gnossen Any updates on this? I recently started running into this issue as well? Is there a known workaround that solves the issue? Thanks!

**Comment by michael4338** [comment]
same here, it looks so common usage, like Python client simply just cannot connect to gRPC server.  Any update is much appreciated.

**Comment by chirupan** [comment]
Hi, I'm facing a similar issue when try to use SSL certificates in my C++ client and server applications along with SAN(subject alternative names).There is no issue if donot use the SAN feature for the certificate generations.

GRPC Version - 1.37.0-dev
openssl version - 1.1.1

Steps to reproduce :-

Generate CA root, server and client keys/certificates for mutual SSL authentication using the steps as attached in gen_certs.sh
Provide an extension file named server
[certificates.zip](https://github.com/grpc/grpc/files/6906571/certificates.zip)
-ext.cnf/client-ext.cnf so that alternate subject domain names can be inserted while generating server/client certificates.
Both pairs of server and client certificates are used in c++ server & client applications.
Expected result :-
API's should be triggered without any errors.

Actual result :-
Get the below error message on the client side

Handshake failed with fatal error SSL_ERROR_SSL: error:1416F086:SSL routines:tls_process_server_certificate:certificate verify failed.
14: failed to connect to all addresses
RPC failed

On enabling GRPC_VERBOSITY=DEBUG and GRPC_TRACE=ALL , I see the below messages
Security handshake failed: {"created":"@1627636862.516902426","description":"Cannot check peer: missing selected ALPN property.","file":"/home/chirag/grpc/src/core/lib/security/security_connector/ssl_utils.cc","file_line":160}
I0730 14:51:02.516927398   29079 tcp_posix.cc:1219]          TCP:0x7f50b000ec00 got_error: {"created":"@1627636862.516920791","description":"FD Shutdown","file":"/home/chirag/grpc/src/core/lib/iomgr/lockfree_event.cc","file_line":199,"referenced_errors":[{"created":"@1627636862.516902426","description":"Cannot check peer: missing selected ALPN property.","file":"/home/chirag/grpc/src/core/lib/security/security_connector/ssl_utils.cc","file_line":160}]}
I0730 14:51:02.516934247   29079 handshaker.cc:129]          handshake_manager 0x7f50b000f5f0: error={"created":"@1627636862.516902426","description":"Cannot check peer: missing selected ALPN property.","file":"/home/chirag/grpc/src/core/lib/security/security_connector/ssl_utils.cc","file_line":160} shutdown=0 index=1, args={endpoint=(nil), args=(nil) {size=0: }, read_buffer=(nil) (length=0), exit_early=0}
I0730 14:51:02.516937277   29079 handshaker.cc:162]          handshake_manager 0x7f50b000f5f0: handshaking complete -- scheduling on_handshake_done with error={"created":"@1627636862.516902426","description":"Cannot check peer: missing selected ALPN property.","file":"/home/chirag/grpc/src/core/lib/security/security_connector/ssl_utils.cc","file_line":160}
I0730 14:51:02.516941179   29079 timer_generic.cc:470]       TIMER 0x7f50b000f658: CANCEL pending=true
D0730 14:51:02.516944126   29079 chttp2_server.cc:253]       Handshaking failed: {"created":"@1627636862.516902426","description":"Cannot check peer: missing selected ALPN property.","file":"/home/chirag/grpc/src/core/lib/security/security_connector/ssl_utils.cc","file_line":160}
I0730 14:51:02.516962593   29079 resource_quota.cc:953]      RQ anonymous_pool_139984526961248 ipv4:192.168.0.104:57436: free 8192; free_pool -> 8192
I0730 14:51:02.516982234   29079 resource_quota.cc:553]      RU shutdown 0x7f50b000f470

I've been stuck here since past few days and any prompt help would be highly appreciated.
[certificates.zip](https://github.com/grpc/grpc/files/6906573/certificates.zip)

**Comment by zisha** [comment]
Hi, did anyone find a solution to this? 

I'm having the same issue, getting the Cannot check peer: missing selected ALPN property error.
Thanks

**Comment by chirupan** [comment]
Hi,  I solved the above issue by including SAN(Subject alternate Names)  while generating the certificates.
Hope the below certificates help you

[certificates.zip](https://github.com/grpc/grpc/files/7085147/certificates.zip)

**Comment by zisha** [comment]
Thanks for your response. 
I am getting this error while trying to access the google ads API using the python client libraries from behind a corporate firewall so I dont think I can make use of these certificates.

**Comment by simon-anz** [comment]
I am having same issue - attempting to access google-cloud APIs from python from behind a corporate firewall that does MITM on the SSL (and I don't have any way to update the certs).

**Comment by simon-anz** [comment]
The following program demonstrates the issue for me:

```
import logging
import pprint

from google.cloud.resourcemanager_v3 import FoldersClient

logging.basicConfig(level=logging.DEBUG)

client = FoldersClient()
x = client.list_folders(parent=f"folder/123")
pprint.pprint(x)
```

Without $GRPC_DEFAULT_SSL_ROOTS_FILE_PATH set to point to my certs I get

Handshake failed with fatal error SSL_ERROR_SSL: error:1000007d:SSL routines:OPENSSL_internal:CERTIFICATE_VERIFY_FAILED.
(proxy is MITM SSL)

When that is set to my cacerts.pem file (which contains three PEM format certs, dragged from chrome), I get

Security handshake failed: {"created":"@1637818747.566140000","description":"Cannot check peer: missing selected ALPN property.","file":"src/core/lib/security/security_connector/ssl_utils.cc","file_line":162}

**Comment by giejay** [comment]
@simon-anz Did you ever solve it? I'm having the exact same issue with my corporate proxy.

**Comment by shireresident** [comment]
> @simon-anz Did you ever solve it? I'm having the exact same issue with my corporate proxy.

I got around this by bypassing the proxy for the needed google URLs. We had that option in our Corporate settings.

**Comment by lyricnz** [comment]
> @simon-anz Did you ever solve it? I'm having the exact same issue with my corporate proxy.

Nope.  I've since left that client, done another couple of gigs, and now I'm back. Same problem :/

**Comment by gtcooke94** [comment]
I've been attempting to reproduce this on HEAD but I haven't been able to do so. This has sat for a while so I'm not sure if it might've gotten fixed somewhere along the line.

If you create a git repo with the contents of `certificates.zip` (or put the generation script in a gist) like @niya3 did here - https://github.com/niya3/grpc_tls_alpn_h2_issue that would be very useful

**Comment by chirupan** [comment]
[gen_certs.zip](https://github.com/grpc/grpc/files/13244739/gen_certs.zip)

**Comment by lyricnz** [comment]
Nope, I still have the issue if I attempt to use grpc (google cloud APIs seem to do this be default if the API is available via grpc).  The problem appears to be that the trust-store used by grpc isn't the same one as commonly futzed around with by certfi etc, and I couldn't figure out how to add to it without modifying the library. 

In the case of Google cloud apis, when you construct the client, you can pass `transport="rest"` and it uses that, rather then grpc, which is a good-enough workaround for me.

**Comment by gtcooke94** [comment]
@chirupan can you put the contents in a public repo instead of a downloadable zip?

**Comment by chirupan** [comment]
Hope this helps !!
https://github.com/chirupan/TLSCertsgrpc

**Comment by PagarTusharANZ** [comment]
@chirupan  could you pls share the steps to configure these certs?

**Comment by lyricnz** [comment]
@PagarTusharANZ if you're at ANZ (the bank) fixing the certs won't help you - it will just move the problem from a SSL-handshake error (due to our MITM proxy), to an ALPN problem (same).  I don't believe there is any resolution to the ALPN problem, so we have to use REST APIs only.  Hit me up on Teams or #gcp Slack to discuss.

**Comment by gtcooke94** [comment]
I had some time to look at this and still and unable to reproduce using the generated files from your repo @chirupan (thanks for putting these together!) - I was able to use the certificates successfully.

However, the ALPN failure is really caught in a strange codepath that relates it to certificate validation failures - I think this is a red herring to look at certificates.
gRPC currently requires ALPN negotiation and assumes it will be present, so the failure being seen is that there is no ALPN to extract from the handshaker. This would be a configuration up the chain about the ALPN support on your clients and servers. We haven't had a compelling reason to allow disabling this requirement, as ALPN support is useful and extremely widely adopted.


From my read there's another issue being discussed here relating to python and some APIs, but it seems to also root cause down to that something is not configured to support ALPN.

**Comment by IMarvinTPA** [comment]
Is it possible to make it work without ALPN support?  A configuration option somewhere to disable it?  I have no hope of influencing the other ends to fix support whether it is a MitM server problem or just the host isn't configured for it.

What would happen if grpc_ssl_check_alpn were to lie?

How could I get a build that has TSI_OPENSSL_ALPN_SUPPORT not defined?

**Comment by XuanWang-Amos** [comment]
Hi @gtcooke94, can you help follow up?

**Comment by gtcooke94** [comment]
We've been discussing this recently and won't be adding an option to turn off ALPN support. TLS over HTTP/2 must support ALPN (https://datatracker.ietf.org/doc/html/rfc7540#section-3.3).

In addition, for HTTP/2, it'd fall back to HTTP/1 if ALPN does not choose a protocol. Since grpc implementations don't support HTTP/1, they should fail if h2 was not selected.
