### ISSUE TITLE
C# - Deadline being ignored, sudden spike in IAsyncStreamReader call duration

### ISSUE THREAD

**Issue by smflorentino** [grpc/grpc#23244]
### What version of gRPC and what language are you using?
2.29.0, C#

### What operating system (Linux, Windows,...) and version?
Windows Server 2019

### What runtime / compiler are you using (e.g. python version or version of gcc)
.NET Framework 4.6.2 (runtime: 4.7.2)

### What did you do?
Run a cluster of nodes, each node doing < 1000 rps. Bidirectional streaming gRPC.

### What did you expect to see?
All nodes remain in a healthy state if their OS (CPU, Memory) and underlying resources (storage, compute, networking) remain healthy.

### What did you see instead?
On a completely healthy node (50% CPU, 10GB available memory), a large percentage of requests start taking a *very* long time in `IAsyncStreamReader.MoveNext()` (~200 seconds). The RPC deadline of 10 seconds is being **ignored** (yet it is set properly in `ServerCallContext` and I have logged it below) and the `ServerCallContext.CancellationToken` is sometimes being set, sometimes not (also logged). Either way, the calls eventually succeed. This is is a server-to-server call between 2 nodes in the same subnet in the same virtual network. No TLS.

This is very puzzling, as it happens without warning, so I can't repro it. I was wondering what set of traces, if any, could help me diagnose this further. Or which settings I can tweak.

I've verified that my actual server-side processing never takes more than a few seconds, so the requests shouldn't be stuck building in the queue.

Here are my logs for some of the sample requests. You can see some requests take 6 seconds, others take upwards of 200 seconds, all for similarly sized request bodies. They all completed with the same 2 seconds (`ActualRpcCompleteTimeUtc`)

- In green, we have a "healthy" request.
- In orange, we have a request that took ~195 seconds, ignored its deadline, but had `ServerCallContext.CancellationToken` set to `true`
- In red, we have a request that took ~195 seconds, ignored its deadline, but had `ServerCallContext.CancellationToken` set to `false` (!!)
![image](https://user-images.githubusercontent.com/3495150/84960826-8da31380-b0b7-11ea-9885-0fc75b216747.png)

Any pointers would be appreciated.

**Comment by jtattermusch** [comment]
One thing you can try is to set  InlineHandlers=true in https://github.com/grpc/grpc/blob/88af358f9ec9b2a84f82b3f4e795df62c920c29b/src/csharp/Grpc.Core/GrpcEnvironment.cs#L242

Also, you can try to manipulate the number of completion queues and threads in the grpc thread pool:
https://github.com/grpc/grpc/blob/88af358f9ec9b2a84f82b3f4e795df62c920c29b/src/csharp/Grpc.Core/GrpcEnvironment.cs#L222
https://github.com/grpc/grpc/blob/88af358f9ec9b2a84f82b3f4e795df62c920c29b/src/csharp/Grpc.Core/GrpcEnvironment.cs#L205

Potentially, this could indicate some problem with Grpc.Core triggering the notifications about new events (getting the next event to process from completion_queue_next()). It would be interesting to know if the notifications (e.g. a new message being available after reader.MoveNext() has been invoked previously) have already been delivered by completion_queue_next() and they are somehow stuck in the C# layer or if the problem is somewhere in the native library (Potentially you can get that information by setting env GRPC_VERBOSITY=debug GRPC_TRACE=api, but note that that prints a lot of stuff).

Clearly, a reproduction of the problem would be very useful but I understand you're unable to reproduce outside of your system.

**Comment by jtattermusch** [comment]
- Since this is about full-duplex streaming, can you also describe the pattern the messages get sent back and forth?
- does IAsyncStreamReader.MoveNext()  become very slow in the server-side handler (when reading requests from client) or on the client (when reading the responses from the server).

**Comment by smflorentino** [comment]
@jtattermusch this hasn't happened in a while (we aren't sure how to repro, either, and would need to try and replicate our production volume), but we are planning to move to `grpc-dotnet` anyways. I'll close this issue
