### ISSUE TITLE
Invalid TLS handshakes from the grpc cpp client when connecting to a specific IP

### ISSUE THREAD

**Issue by c-ryan747** [grpc/grpc#23274]
### What version of gRPC and what language are you using?
Latest, C++

### What operating system (Linux, Windows,...) and version?
Linux, Centos 7

### What runtime / compiler are you using (e.g. python version or version of gcc)
n/a

### What did you do?
**Background on the TLS Server Name Indication extension**
> Server Name Indication (SNI) is an extension to the Transport Layer Security (TLS) computer networking protocol by which a client indicates which hostname it is attempting to connect to at the start of the handshaking process.[1] This allows a server to present multiple certificates on the same IP address and TCP port number and hence allows multiple secure (HTTPS) websites (or any other service over TLS) to be served by the same IP address without requiring all those sites to use the same certificate.

https://en.wikipedia.org/wiki/Server_Name_Indication

According to the SNI TLS extension spec the SNI in a TLS handshake must be set to a fully qualified domain name, not an IP address:

> "HostName" contains the fully qualified DNS hostname of the server, as understood by the client.  ... Literal IPv4 and IPv6 addresses are not permitted in "HostName".

https://tools.ietf.org/html/rfc6066#section-3

**Bug**

In our setup we have a grpc server running with a valid certificate for the IPv6 address its bound to. 

We're attempting to use the grpc c++ client to connect directly to this server via its IPv6 address and port directly, rather than using a fully qualified domain name. When doing so the grpc client incorrectly sets the Server Name Indicator (SNI) in its TLS handshake to the target IPv6 address.

Our grpc server implementation then rejects the request due to the SNI being invalid.

### What did you expect to see?
I expect grpc to only use the SNI TLS extension when its connecting to a domain name. This will make grpc clients use of SNI spec compliant.

### What did you see instead?
grpc always uses the SNI extension, regardless of whether its connecting to an IP address or a hostname.

### Anything else we should know about your project / environment?
If changing grpc so that it doesn't set the SNI when connecting directly to an IP address sounds like a valid solution I'm happy to implement it. Code pointers or advice is appreciated.

**Comment by rockspore** [comment]
[This](https://github.com/grpc/grpc/blob/a62c2607a64edf9484197172108f6163a45f919e/src/core/tsi/ssl_transport_security.cc#L1755) is where we configure the TLS extension. And the function is called [here](https://github.com/grpc/grpc/blob/a62c2607a64edf9484197172108f6163a45f919e/src/core/lib/security/security_connector/ssl/ssl_security_connector.cc#L108) given the target name.

A fix should be fairly straightforward - we should not pass a target that's detected as a literal IP address.

I understand that after so long, @c-ryan747 you may not be working with gRPC any more? But please let us know if you are still interested in contributing a fix. Otherwise, I will try to send a fix asap.

**Comment by rockspore** [comment]
Fixed in #34878
