### ISSUE TITLE
Python (server) gRPC hiding (most) exception messages

### ISSUE THREAD

**Issue by gitpushdashf** [grpc/grpc#23306]
I'm looking to hide exception messages from clients unless they come from a certain type.

Out of the box, the exception messages get handed to the client. For example, `raise ValueError("Message with secret key")`, sends "Message with secret key" back to the client. Unless I do a `context.set_message("some string")` before the exception is raised.

It'd be nice to have an option (perhaps when envoking the server) to hide exception messages for security reasons and then have a way to return certain exceptions if they are an allowed exception type, paired to specific status codes.

Perhaps:

```
raise CustomNotFound("message") results in StatusCode.NOT_FOUND with "message"
raise CustomUserError("message") results in StatusCode.INVALID_ARGUMENT with "message"
raise CustomException("message") results in StatusCode.UNAVAILABLE with "message"
```

Thank you!

**Comment by lidizheng** [comment]
Option 1: You could make use of `abort` which sets the message and raise an exception at the same time.

Option 2: Please take a look at https://github.com/grpc/proposal/blob/master/L44-python-rich-status.md. For rich error status, you might found `grpcio-status` package useful, if you want the exception itself to carry more information.

**Comment by gitpushdashf** [comment]
Unfortunately, I don't always know what might throw an exception, so I want to be sure that nothing is leaking. If there was a server argument to hide exception messages, it would be quite helpful. I could then manually set them as required.

**Comment by lidizheng** [comment]
I agree that server argument might be helpful. The servicer method implementation could have a catch-all clause to transform any exception into the desired format. Or, it could be implemented as an interceptor.

**Comment by gitpushdashf** [comment]
I'd be quite happy with any of those.

**Comment by lidizheng** [comment]
I meant the masking-exception-message server argument might not happening, since this functionality could be achieved through the ways I suggested. Proxies tend to be in a better position to control this. After all, the error message is just an HTTP2 header (or trailing header).

**Comment by gitpushdashf** [comment]
I see. I think in the case of the proxy, it would see the message but not the exception type, so wouldn't know which to pass unless there was some kind of prefix on the message string.

**Comment by d5h** [comment]
You can do this with an interceptor. If you're not sure how, you can check out the [`ExceptionToStatusInterceptor`](https://github.com/d5h-foss/grpc-interceptor/blob/ad5857d584cfa012f3b4c5b17b5f1cd3a5ade8bd/src/grpc_interceptor/exception_to_status.py#L11) interceptor in the [`grpc-interceptor`](https://pypi.org/project/grpc-interceptor/) package, which does almost exactly what you want. (Disclosure: I'm the author). You would just need to tweak it so that it sets the details to a blank string (or whatever other message you'd like), instead of the default [here](https://github.com/d5h-foss/grpc-interceptor/blob/ad5857d584cfa012f3b4c5b17b5f1cd3a5ade8bd/src/grpc_interceptor/exception_to_status.py#L48).

Then you would need to change the servicer code to use subclasses of [`GrpcException`](https://github.com/d5h-foss/grpc-interceptor/blob/ad5857d584cfa012f3b4c5b17b5f1cd3a5ade8bd/src/grpc_interceptor/exceptions.py#L12) whenever they _do_ want the status code and details to be sent to the client. Any other exception would result in the default status code and details message you set.

You're welcome to use the `grpc-interceptor` package and write your own interceptor, or I'd be happy to extend `ExceptionToStatusInterceptor` to add a `callback_on_unknown_exception` parameter, since it seems generally useful. Or if you'd rather not use the package, you can see how it works [here](https://github.com/d5h-foss/grpc-interceptor/blob/ad5857d584cfa012f3b4c5b17b5f1cd3a5ade8bd/src/grpc_interceptor/server.py#L9).

Hope that helps!

**Comment by gitpushdashf** [comment]
That is fantastic, thank you! For now it turns out there's really just the one call to worry about but if there's multiple I will definitely look into using that.
