### ISSUE TITLE
grpc fails to compile on windows under arm64 architecture

### ISSUE THREAD

**Issue by maxweisel** [grpc/grpc#23310]
### What version of gRPC and what language are you using?
At the time of writing, I've tried both the latest released version (v1.30.0) and the latest master (e4973325a07f576951eea40dc079e4bade0b0f0d)

### What operating system (Linux, Windows,...) and version?
Host machine is Windows 10 - x64
I'm building for Windows 10 - arm64

### What runtime / compiler are you using (e.g. python version or version of gcc)
I'm currently using cmake which is compiling with msvc. I'm using cmake version 3.17.0, and Visual Studio 2019

### What did you do?
```
// Create a build folder
cd grpc; mkdir build-arm64; cd build-arm64

// Configure. This step works fine.
cmake -A ARM64 ..

// Build. I'm only building the crypto / ssl targets because the issue seems to be local to boringssl
cmake --build . --target crypto ssl
```
### What did you expect to see?
```
$ cmake --build . --target crypto ssl
Microsoft (R) Build Engine version 16.6.0+5ff7b0c9e for .NET Framework
Copyright (C) Microsoft Corporation. All rights reserved.

  crypto.vcxproj -> grpc\.build-arm64\third_party\boringssl-with-bazel\Debug\crypto.lib


Microsoft (R) Build Engine version 16.6.0+5ff7b0c9e for .NET Framework
Copyright (C) Microsoft Corporation. All rights reserved.

  ssl.vcxproj -> grpc\.build-arm64\third_party\boringssl-with-bazel\Debug\ssl.lib
```
(This is what it looks like after I successfully compile for x64 on Windows)

### What did you see instead?

```
$ cmake --build . --target ssl
Microsoft (R) Build Engine version 16.6.0+5ff7b0c9e for .NET Framework
Copyright (C) Microsoft Corporation. All rights reserved.

  Building Custom Rule grpc/third_party/boringssl-with-bazel/CMakeLists.txt
  bio_ssl.cc
grpc\third_party\boringssl-with-bazel\src\include\openssl/base.h(122,1): fatal error C1189: #error:  "Unknown target CPU" [grpc\.build-arm\third_party\boringssl-with-bazel\ssl.vcxproj]
  d1_both.cc
grpc\third_party\boringssl-with-bazel\src\include\openssl/base.h(122,1): fatal error C1189: #error:  "Unknown target CPU" [grpc\.build-arm\third_party\boringssl-with-bazel\ssl.vcxproj]
  d1_lib.cc

...

```

### Anything else we should know about your project / environment?

1. If I omit the `-A ARM64` argument (which defaults to x64 on my computer), everything builds perfectly.

2. From looking at base.h, it looks like `__aarch64__` or `__arm64__` should be defined, but it's not.

Max

**Comment by nicolasnoble** [comment]
That's technically not on us, but on BoringSSL. @agl, what would be the proper location for these sort of issues?

**Comment by maxweisel** [comment]
fwiw, it looks like these patches will fix it: https://github.com/microsoft/winrtc/blob/master/patches_for_WebRTC_org/m80/6401-Arm64-is-a-thing-and-has-intrinsic-to-mul-two-64bit-.patch

Max

**Comment by agl** [comment]
The BoringSSL bug tracker is https://bugs.chromium.org/p/boringssl/issues/list

In this case I don't want to look at the linked patch because it's not being submitted under CLA. Aarch64 Windows is not a platform that we have any ability to build, but it sounds like gRPC would like it supported? I'll make the obvious change that should clear the &ldquo;unknown target CPU&rdquo; error, but I don't know if what results will be functional. Maybe, once I do that, someone here can build and run tests?

**Comment by agl** [comment]
https://boringssl-review.googlesource.com/c/boringssl/+/41945 to do the obvious fix.

**Comment by maxweisel** [comment]
That's the fix I tried originally, but it will fail with an error saying "BN_UMULT_LOHI" is not defined

**Comment by maxweisel** [comment]
fwiw, I think BN_UMULT_LOHI just needs to be defined for arm64 when building for Windows as it does have an equivalent built-in.

**Comment by agl** [comment]
> That's the fix I tried originally, but it will fail with an error saying "BN_UMULT_LOHI" is not defined

Thanks. Could you try out the latest version of the same change? (Am coding blind here.)

At best, this will get the NO_ASM version building, but that might be sufficient for gRPC. We'll (i.e. BoringSSL) will look into whether we want to fully support this platform, buy hardware, etc.

**Comment by agl** [comment]
I've blindly attempted a fix in the referenced change.

**Comment by nicolasnoble** [comment]
By the way, regarding our willingness to support AArch64: we don't mind accepting patches to increase compatibility, but we don't want to make any promises, given the poor testability.

**Comment by jtattermusch** [comment]
@maxweisel  is this still an issue? We've upgraded the boringssl version we use several times since this issue was filed, so the boringssl fix @agl has accepted is already in place under third_party/boringssl and there's a good chance that the windows arm64 build already works. 

One possible workaround is to not use boringssl in your cmake build, but instead depend on a pre-installed version of OpenSSL.
See https://github.com/grpc/grpc/blob/0e20a5fce8e53510255fa1a5199544a86ebfcd8e/test/distrib/cpp/run_distrib_test_cmake.bat#L26 and https://github.com/grpc/grpc/blob/0e20a5fce8e53510255fa1a5199544a86ebfcd8e/test/distrib/cpp/run_distrib_test_cmake.bat#L85 for how to depend on a pre-installed version of OpenSSL instead of building boringssl from source.

**Comment by jtattermusch** [comment]
I'm going to close this issue since:
- there's a good chance that the original issue has already been fixed
- the workaround is to build without boringssl and use openssl instead (by setting `-DgRPC_SSL_PROVIDER=package`)
- we don't support win arm64 officially anyway
