### ISSUE TITLE
C# ValueTask based service API to reduce allocations

### ISSUE THREAD

**Issue by MaximGurschi** [grpc/grpc#23389]
Hello,

I am working on a grpc service in dot.net. It is built with high throughput in mind. I have attempted to remove all allocations from requests, and managed to do that for the most part.

The final allocations i have are:
1.Task
2.TaskCompletionSource
3.The async machinery instance
4.The response proto message

I was thinking that maybe i can get rid of the first 3 by using the ValueTask API backed by IValueTaskSource. However this would require the grpc service to return ValueTask to properly avoid allocations.
Is there any initiatives to introduce ValueTask returning service methods? Perhaps i am not the first person to propose this.

As for the allocated proto message, i was thinking to reuse the instances as well, but for that i would require a callback to know that the request is complete. Is there a way to achieve such a notification, so that i can reuse the object for another request?

**Comment by MaximGurschi** [comment]
I've just realised that this is the wrong repo to post this, i am supposed to post this on the grpc-dotnet repo.

**Comment by MaximGurschi** [comment]
Reopened following advice from:
https://github.com/grpc/grpc-dotnet/issues/970

**Comment by jtattermusch** [comment]
We could consider adding a ValueTask-based API in the future, but for now, the API seems adequate (= allocating Task<> instances doesn't not seem to be a significant ovehead in relation to the load a Grpc C# or grpc-dotnet server can achieve).

Note that changing the current API to return ValueTask instead of Task would be a breaking change, so there is not plan to the existing API in the foreseeable future.

I applied the "area/api" label to mark this PR as idea for API improvements should we be designing a new generation of the C# API at some point in the future (not something we are planning - there's more value in staying backwards compatible).
