### ISSUE TITLE
Dropped TSI status from `create_alts_grpc_record_protocol()`

### ISSUE THREAD

**Issue by ErrReporter** [grpc/grpc#23778]
### What version of gRPC and what language are you using?
ec216362a1247c378e9cbab4eecaa19f31837b3b
Latest

### What operating system (Linux, Windows,...) and version?
Linux

### What runtime / compiler are you using (e.g. python version or version of gcc)
GCC 10

### What did you do?
Please provide either 1) A unit test for reproducing the bug or 2) Specific steps for us to follow to reproduce the bug. If there’s not enough information to debug the problem, gRPC team may close the issue at their discretion. You’re welcome to re-open the issue once you have a reproduction.
Examine the code.

### What did you expect to see?
The original status codes should be preserved as `TSI_INVALID_ARGUMENT` or anything else at https://github.com/grpc/grpc/blob/618a3f561d4a93f263cca23abad086ed8f4d5e86/src/core/tsi/alts/zero_copy_frame_protector/alts_zero_copy_grpc_protector.cc#L262-L295, rather than unified to `TSI_INTERNAL_ERROR`. Otherwise, there is no need to generate a `TSI_INVALID_ARGUMENT` error.

Or is there a special motivation behind this change?

### What did you see instead?

Dropped status codes.

**Comment by apolcyn** [comment]
This issue doesn't appear refer to any actual problem, so I'm going to close. If this causes a real issue, then please explain what the problem is that this causes. Ideally in the form of a reproducibly failing test.

For general questions and troubleshooting, please ask/look for answers at StackOverflow, with "grpc" tag: https://stackoverflow.com/questions/tagged/grpc

For questions that specifically need to be answered by gRPC team members, please ask/look for answers at grpc.io mailing list: https://groups.google.com/forum/#!forum/grpc-io
