### ISSUE TITLE
gRPC client disconnection from server

### ISSUE THREAD

**Issue by togis123** [grpc/grpc#23774]
togis123 @togis123 12:38
I bringing up gRPC client-server C ++ application. I have following queries will designing the thread modelling and connection management

-> How do gRPC server knows that if a client got disconnected from the server. Is there any context maintained in the server for each client.?

-> By using the gRPC keep alive server can ping the client as well or its other way alone.?

**Comment by togis123** [comment]
Any updates?

**Comment by apolcyn** [comment]
Closing since this is a question.

For general questions and troubleshooting, please ask/look for answers at StackOverflow, with "grpc" tag: https://stackoverflow.com/questions/tagged/grpc

For questions that specifically need to be answered by gRPC team members, please ask/look for answers at grpc.io mailing list: https://groups.google.com/forum/#!forum/grpc-io

That said:

> -> How do gRPC server knows that if a client got disconnected from the server. Is there any context maintained in the server for each client.?

Outside of application level messaging, you may be able to use the [AsyncNotifyWhenDone](https://github.com/grpc/grpc/blob/18bd62cac2c47106384e68fb04fb8ca49086e8a0/include/grpcpp/impl/codegen/server_context_impl.h#L281) API, if using the C++ completion queue based API.

> -> By using the gRPC keep alive server can ping the client as well or its other way alone.?

Keepalive pings can also be sent from server to client, if the server is configured to send keepalive pings. See https://github.com/grpc/grpc/blob/master/doc/keepalive.md for more details.
