### ISSUE TITLE
Incorrect warnings when multiple paths are specified in `ProtoRoot` attribute

### ISSUE THREAD

**Issue by YSZhuoyang** [grpc/grpc#23852]
### What version of gRPC and what language are you using?

gRPC-dotnet v2.31.0
C#

### What operating system (Linux, Windows,...) and version?

macOS 10.15

### What runtime / compiler are you using (e.g. python version or version of gcc)

dotnet core v3.1

### What did you do?

Compile gRPC contracts with multiple paths specified in `ProtoRoot` attribute, in order to import specific proto files from `googleapis` repository without manually copying them.

Updated info that might help:

Below is my contract folder structure that works:

    contracts/
        <my-service>/
            ... // proto files
        googleapis/
            ... // proto files

in the `.csproj` file:

    <Protobuf Include="contracts/<my-service>/*.proto" ProtoRoot="contracts/<my-service>; contracts/googleapis" ... />

### What did you expect to see?

No warning should show up given the paths in `Include` and `ProtoRoot` attributes are correct.

### What did you see instead?

`/Users/<user>/.nuget/packages/grpc.tools/2.31.0/build/_protobuf/Google.Protobuf.Tools.targets(167,5): warning : Protobuf item 'contracts/<my-service>/<proto-file>.proto' has the ProtoRoot metadata 'contracts/<my-service>;contracts/googleapis' which is not prefix to its path. Cannot compute relative path.`

### Anything else we should know about your project / environment?

This was introduced by commit 5494c54cee7ef72b21cb68014cb6acba3facd3e6 in #22869 , which added a validation against `ProtoRoot` and `Include` path attributes. Yet scenarios where multiple paths are specified correctly in `ProtoRoot` also lead to warnings. Warnings should not show up in those cases.

**Comment by Falco20019** [comment]
@YSZhuoyang Sorry, that was my fault. But should be easy to fix. I will give it a look. Only just stumbled over your issue by chance (not related to gRPC team or google, just a contributor).

**Comment by YSZhuoyang** [comment]
No problem @Falco20019 , thanks for your help.

**Comment by Falco20019** [comment]
@YSZhuoyang Can you try to use `AdditionalImportDirs` on `Protobuf` instead of `ProtoRoot`? 

Looking into the code again ([Grpc.Tools/GeneratorServices.cs#L71](https://github.com/grpc/grpc/blob/master/src/csharp/Grpc.Tools/GeneratorServices.cs#L71)) it is not intended to have more than one entry. This was the behavior in C++ already before my change.

The build target composes the `ProtoPath` for `protoc` from three lists / sources ([Google.Protobuf.Tools.targets#L284](https://github.com/grpc/grpc/blob/master/src/csharp/Grpc.Tools/build/_protobuf/Google.Protobuf.Tools.targets#L284)):
* %(_Protobuf_OutOfDateProto.AdditionalImportDirs)
* $(Protobuf_StandardImportsPath)
* %(_Protobuf_OutOfDateProto.ProtoRoot)

So if you have multiple import paths that are the same for all protos in this project, I would recommend using this:
```
    <Protobuf_StandardImportsPath>$(Protobuf_StandardImportsPath);your-path1;your-path2;...</Protobuf_StandardImportsPath>
  </PropertyGroup>
```

In addition to this, on a per-entry base you can use additionally:
```
  <ItemGroup>
    <Protobuf Include="$(CustomProtoRoot)\my-proto1.proto" ProtoRoot="$(CustomProtoRoot)" AdditionalImportDirs="$(DirsForProto1)" />
    <Protobuf Include="$(CustomProtoRoot)\my-proto2.proto" ProtoRoot="$(CustomProtoRoot)" AdditionalImportDirs="$(DirsForProto2)" />
  </ItemGroup>
```
In this example, `my-proto1.proto` and `my-proto1.proto` are in the folder `$(CustomProtoRoot)` and should be generated according to this root path. All imports in `my-proto1` will then have access to $(CustomProtoRoot) (through `ProtoRoot`), all paths in `$(DirsForProto1)` (through `AdditionalImportDirs`) and any path in $(Protobuf_StandardImportsPath).

I assume, in your case the easiest and most readable way would be something like this:
```
<Protobuf Include="contracts/<my-service>/*.proto" ProtoRoot="contracts/<my-service>" AdditionalImportDirs="contracts/googleapis" ... />
```

Or in case you have multiple different `Protobuf` entries:
```
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    ...
    <Protobuf_ProtoRoot>contracts/<my-service></Protobuf_ProtoRoot>
    <Protobuf_StandardImportsPath>$(Protobuf_StandardImportsPath);contracts/googleapis</Protobuf_StandardImportsPath>
  </PropertyGroup>
  
  <ItemGroup>
    <Protobuf Include="contracts/<my-service>/clients/*.proto" GrpcServices="Client" ... />
    <Protobuf Include="contracts/<my-service>/servers/*.proto" GrpcServices="Server" ... />
  </ItemGroup>
  
</Project>
```

**Comment by YSZhuoyang** [comment]
Thank you @Falco20019 , your solution worked out very well. Problem solved.
