### ISSUE TITLE
Python doesn't compile on master.

### ISSUE THREAD

**Issue by nicolasnoble** [grpc/grpc#2392]
See:

https://grpc-testing.appspot.com/job/gRPC_master/config=opt,language=python,platform=linux/781/console

```
grpc/_cython/_cygrpc/records.c: In function '__pyx_pf_4grpc_7_cython_7_cygrpc_7records_8Timespec___cinit__':
grpc/_cython/_cygrpc/records.c:1501:28: error: too few arguments to function 'gpr_now'
     __pyx_v_self->c_time = gpr_now();
                            ^
In file included from /var/local/git/grpc/include/grpc/support/sync.h:67:0,
                 from /var/local/git/grpc/include/grpc/support/slice.h:37,
                 from grpc/_cython/_cygrpc/records.c:272:
/var/local/git/grpc/include/grpc/support/time.h:78:14: note: declared here
 gpr_timespec gpr_now(gpr_clock_type clock);
```

**Comment by nicolasnoble** [comment]
Anyone ? Anyone ? Bueller ?

**Comment by ctiller** [comment]
Cython is a massive step backwards towards complete unmaintainability.

**Comment by ctiller** [comment]
(that said, fix incoming)

**Comment by ctiller** [comment]
Sent out a partial fix. It doesn't solve the problem. It's however Saturday
and I'm going to spend my time with my family rather than learning some new
programming language.

**Comment by nicolasnoble** [comment]
I didn't assign anyone to that issue for a reason you know :-P

**Comment by soltanmm** [comment]
Cython isn't working on master because #2289 was let through without all relevant tests passing. A backwards incompatible change was made and I wasn't aware of it. Cython caught the error at compilation time as opposed to run-time. The error would be exactly the same had it been in the C code, the only difference being that it would have been in Python-like syntax and not C-like syntax (i.e. meant for people who know Python, not people who know C).

**Comment by soltanmm** [comment]
Apparently I can't edit comments from my cell phone... clarification: I meant that the Cython puts the maintainability issues in Python syntax rather than C syntax.

**Comment by soltanmm** [comment]
I've tried to link the relevant threads of discussion with backlinks to my response above. It's rather difficult to handle github on my phone, it seems...

**Comment by nicolasnoble** [comment]
It's important to note that #2289 WAS green on Jenkins. What happened was a merge race between the two commits. So everyone did their diligence in making sure everything was green before merging. It's just that the two changes were incompatible with each other.

But it doesn't really matter as to what breaks for which reason. What matters is that if compilation breaks, and that the people with the proper knowledge to fix it aren't readily available to fix it, I'm just going to disable features to make compilation happy again, pending a later proper fix.

**Comment by soltanmm** [comment]
The merge 'race' was a day long:
https://github.com/grpc/grpc/pull/2289#event-353410710
vs.
https://github.com/grpc/grpc/pull/2243#event-352454356

Go ahead and disable features, but I'm confused why Cython was the target of this brute force method rather than the root cause (the API breaking change in core) later in the commit history.

**Comment by nicolasnoble** [comment]
The reasoning is simple. We believed that fixing the problem should've been trivial for you or Nathaniel, but wasn't for me or Craig. If we reverted the C-core change instead, it means Craig and others wouldn't have been able to continue working on gRPC until that problem is fixed. However, with disabling Cython, if you were to work over the week-end on the Cython port, you probably could've fixed that problem quite quickly, hence not preventing you to work. So in terms of impact, this was the least impactful solution.
