### ISSUE TITLE
[c++ interceptors] Authentication interceptors unable to signal other interceptors not to process the request

### ISSUE THREAD

**Issue by riking** [grpc/grpc#24017]
### Is your feature request related to a problem? Please describe.
I am designing a server interceptor to process a settings protobuf passed as metadata by the client. Some of these settings are dangerous to act on, so it should only process authenticated requests.

Because server interceptors cannot `Hijack()` requests, there is no available way for the authentication interceptor to signal an authentication failure before the other interceptors (... or application code?) act on the request.

### Describe the solution you'd like
Server interceptors handling authentication can halt requests in the POST_RECV_INITIAL_METADATA or POST_RECV_MESSAGE phase, return the `UNAUTHENTICATED` status code, and prevent the application or later interceptors from processing the request.

### Describe alternatives you've considered
Current workaround idea is to set a metadata field named `cancelled` to halt processing on the downstream interceptors.

### Additional context
C++ interceptors are marked as experimental, probably due to unsatisfaction with the design. This user story should help make a better design.

**Comment by yashykt** [comment]
Thanks for the suggestion!

One of the reasons why server interceptors do not have Hijack() capability is because we did not have a usecase for it. There were also arguments against it suggesting that giving interceptors the ability to Hijack() is too much power since you could potentially write the entire server in the interceptor with that.

I do feel that there is merit in the Hijack() if it is to be used with an authenticating interceptor, but looks like for authentication we already have a way to do this through `ServerCredentials`.

What do you think @vjpai ?

**Comment by igor-sirotin** [comment]
I came up with the same problem. 
It seems that sever-side interceptors are allowed to hijack requessts in other languages, for example in Go.
So i find it a strange solution to forbid this feature in C++.

**Comment by timmotw** [comment]
@yashykt thank you for the information. I think that there are more positives in enabling `Hijack()` rather than preventing it based on the argument:

> much power since you could potentially write the entire server in the interceptor with that.

Documentation could provide some good practices but from there on the responsibility lies with every developer who decides to go for it. As a developer can opt to write a 3000 line procedure, in the same way a developer can decide to write an entire server in the interceptor. A framework cannot be restricted based on a developer's bad implementation decisions. The interceptor API is quite clean when it comes to mis-usage but that does not mean the implementation is a grpc responsibility.

As @igor-sirotin mentioned this is available in other language implementations which renders this as an inconsistency, which is quite bad for a framework.

**Comment by benjaminbendig** [comment]
@yashykt @vjpai same issue here. How to introduce OAUTH2 token based authentication in a c++ server? You bring this even up in your documentation: [https://grpc.io/docs/guides/auth/](https://grpc.io/docs/guides/auth/)

Please reconsider allow Hijack() for server side authentication.
