### ISSUE TITLE
Unity 2020.1 Load error!!

### ISSUE THREAD

**Issue by xxpniu** [grpc/grpc#24056]
#### grpc-unity package
---

### What version of gRPC and what language are you using?
```
grpc_unity_package.2.33.0-dev.zip | 7678c1559df878c98cd77265cf0fa61914e77babd06c6e21f82682cf73d484cf
use it in unity 2020.1
```
### What operating system (Linux, Windows,...) and version?
```
on mac os 
```
### What did you do?

Open unity and Import it, will got error for load dll of 
```
Assembly 'xxx/Runtime/Plugins/Google.Protobuf/lib/net45/Google.Protobuf.dll' will not be loaded due to errors:
Google.Protobuf references strong named System.Memory in a different folder, versions has to match. Assembly references: 4.0.1.0 Found in project: 4.0.1.1.
```
`I think this issue because of Unity 2020.1 use framework of .net is 4.71.`

**Comment by liaozb** [comment]
Google.Protobuf.dll  import  System.Memory  4.5.2
Grpc.Core.dll   import System.Memory  4.5.3
https://github.com/protocolbuffers/protobuf/blob/master/csharp/src/Google.Protobuf/Google.Protobuf.csproj  change to 4.5.3

**Comment by SteveCruise** [comment]
I have this error too!

**Comment by lehmamic** [comment]
I have this problem as well, it still exists in the newest nightly build version. I used an old version: grpc-protoc_linux_x64-1.26.0-dev which works. The problem is, generated clients are not compatible with that version anymore and need some manual correction in order to compile.

**Comment by doctorpangloss** [comment]
This is still an issue

**Comment by jtattermusch** [comment]
I'm going to close issue this since we're not going to pursuit Unity/Xamarin support in `Grpc.Core` anymore.
- The `Grpc.Core` implementation is now in maintenance mode and we're only going to focus on critical and security fixes.
- Supporting Unity/Xamarin simply presents too much maintenance overhead and it's also difficult to test with the test infrastructure available to us
- The Unity/Xamarin support has always been classified as "experimental", so discontinuing the support shouldn't be too surprising.

See [the recent update on gRPC C#](https://groups.google.com/g/grpc-io/c/OTj5mb1qzb0/m/-M81UQipAQAJ) for more details.

Note that in practice, running Grpc.Core on Unity/Xamarin might still be possible (there is nothing in principle that would prevent it from working), but it will be completely at your own risk and it's simply not one of the use cases the grpc team will help you with as `Grpc.Core` on Unity/Xamarin is now considered as "not supported" by us (but you might still be able to get help from the community).
