### ISSUE TITLE
Experimental API exposed in Message property/.ToString() of RpcException

### ISSUE THREAD

**Issue by nycdotnet** [grpc/grpc#24138]
### What version of gRPC and what language are you using?
Using .NET/C# and gRPC 2.30.0 and higher (aka gRPC 1.30 and higher)

### What operating system (Linux, Windows,...) and version?
Linux or Windows

### What runtime / compiler are you using (e.g. python version or version of gcc)
.NET Core 3.1

### What did you do?
Please provide either 1) A unit test for reproducing the bug or 2) Specific steps for us to follow to reproduce the bug. If there’s not enough information to debug the problem, gRPC team may close the issue at their discretion. You’re welcome to re-open the issue once you have a reproduction.

  * Use the C# Greeter quick start for gRPC.
  * Use the gRPC NuGet Packages for gRPC 2.30.0 or higher.
  * Change the server `SayHello` method to have this body:  `throw new RpcException(new Status(StatusCode.PermissionDenied, "You are not authorized."));`  (could be any status code or message, this is just an example)
  * Change the client to have a `try` block around the `SayHello` call, and catch `RpcException ex`.  Add this code to the catch block: `Console.WriteLine(ex.Message);`

### What did you expect to see?
Client outputs this to the console:
`Status(StatusCode=PermissionDenied, Detail="You are not authorized.")`

This has been the behavior of gRPC for many years including gRPC 1.29.

### What did you see instead?
Client outputs this to the console:
`Status(StatusCode="PermissionDenied", Detail="You are not authorized.", DebugException="Grpc.Core.Internal.CoreErrorDetailException: {"created":"@1599928495.744000000","description":"Error received from peer ipv4:127.0.0.1:50051","file":"T:\src\github\grpc\workspace_csharp_ext_windows_x64\src\core\lib\surface\call.cc","file_line":1055,"grpc_message":"You are not authorized.","grpc_status":7}")`

Note there are two separate changes here - the StatusCode is now quoted, and there is a new DebugException included in the Message property.  This is the new behavior as of gRPC 1.30.

### Anything else we should know about your project / environment?

The change is related to a new feature documented in the gRPC 1.30 release notes.  https://github.com/grpc/grpc/releases/tag/v1.30.0

The `DebugException` is documented in the code as an experimental feature on which you should never rely on the value - basically that it's just for supplemental debugging purposes on the client and doesn't go across the wire.  This is fair enough, and it's interesting to get a new feature that may help with debugging.

https://github.com/grpc/grpc/blob/master/src/csharp/Grpc.Core.Api/Status.cs#L71-L81

Unfortunately, this change will result in a fair amount of work for us as we upgrade our services to gRPC 2.30+, as we have many tests that assert that an error message is as expected (test spins up server and connects to it via client and calls in various ways that may work or may return an error); up until now, we've been able to assert that exact error strings get logged in certain situations via the `RpcException.Message` property.  Now, the `RpcException.Message` property includes an experimental debug string on the client side that is explicitly noted in the code that it may change or may even be removed at any time.

I would like a bit of clarity on what the expectation is here.  It would be a lot of work for us to update all tests in our code base to account for this change, but I am willing to do it if this is likely to stick around (not only the change to the quoting of the StatusCode which was arguably an improvement, but still a break, but also the new debug message itself) .  I am wondering if instead of having this be included in the `Message` property of the exception, if it could just be accessed via the `Status` property if possible?  I think this might ultimately be the offending line https://github.com/grpc/grpc/blob/master/src/csharp/Grpc.Core.Api/RpcException.cs#L56  The problem is that this experimental message is going to be in all of our logs now, and this may even break some alerts that we have looking for certain strings in logs/traces.

Until the `Status.DebugException` property is not experimental, I wonder if we could have some sort of way to turn it off (possibly something as simple as a static bool on `Status` to let us opt-out of the new `ToString()` functionality, or if possibly the default could be to not include this in the message and let users pull it directly from the `RpcException.Status.DebugException` and revert the change to `Status.ToString()`?  Thanks.

cc @jtattermusch - I am pinging you since you originally introduced this change.  Thanks so much for all of your hard work on gRPC.

**Comment by jtattermusch** [comment]
What we've done is we added a new `DebugException` field to RpcException, which seems to be a fair incremental change (adding a field to a class is fully backwards compatible). The fact that you are relying on the exact contents of the message exception is unfortunate, because the textual representation of the exception sometimes changes and it's quite natural.

Note that the contents of the `StatusCode` and `Details` stayed exactly the same - perhaps you can use those fields for testing (but be careful about the contents of Details, because that's also a freeform text filed and its content can changes if changes in C-core happen).

Ad removing DebugException from .ToString(): I think it's in user's favor to see also the interesting details in the ToString() without needing to opt-in (otherwise useful debug information is easily missed). I think it would be quite easy for you to only rely on StatusCode and Details fields (and ignore DebugException).

It's hard to predict the future but as far as I'm concerned, the DebugException field is there to stay and we are not planning to remove it. But you should not rely on the exact contents of DebugException for automated testing since the exact debug details are quite clearly an implementation detail and can change anytime).
