### ISSUE TITLE
UDP client/transport underneath GRPC

### ISSUE THREAD

**Issue by tiwariashish86** [grpc/grpc#24130]
Is it possible to use UDP client underneath GRPC?

**Comment by markdroth** [comment]
In principle, yes, although it's tricky to do and requires writing a new transport implementation.  The details can get quite tricky, and it requires messing with our internals; it's not something we allow to be done via public APIs.  We do support QUIC via cronet, but it does have some limitations.

If you want to discuss this further, I suggest you start a thread on the grpc.io mailing list rather than here.
