### ISSUE TITLE
PHP7 distribtest broken on master (failure to pull docker image)

### ISSUE THREAD

**Issue by jtattermusch** [grpc/grpc#24333]
It's been failing for the past ~ 2days.

Failure link:
https://source.cloud.google.com/results/invocations/9a1eeae4-c3ce-4c50-b0fb-3a33856aaede/targets/github%2Fgrpc/tests;group=tasks;test=distribtest.php7_linux_x64_stretch;row=1

Looks like something is wrong with pulling the php7_stretch_x64 image.

I am able to reproduce locally by running:
```
docker pull grpctesting/php7_stretch_x64:8ad39eea13c72af84c0ddd1a265edbce260cf363
8ad39eea13c72af84c0ddd1a265edbce260cf363: Pulling from grpctesting/php7_stretch_x64
4f250268ed6a: Pulling fs layer 
e19108d243ae: Pulling fs layer 
739dcfb11b47: Pulling fs layer 
error pulling image configuration: unknown blob
```

**Comment by jtattermusch** [comment]
Likely caused by https://github.com/grpc/grpc/pull/24311/files?

**Comment by jtattermusch** [comment]
Not being able to pull the dockerimage seemed odd, so I  have rebuilt the docker image locally and force-pushed it to dockerhub. Let's see if that fixes the issue.

**Comment by jtattermusch** [comment]
After I force-pushed the image grpctesting/php7_stretch_x64:8ad39eea13c72af84c0ddd1a265edbce260cf363, the last build is green https://source.cloud.google.com/results/invocations/c9b79568-aa5c-42ba-ad31-6517df9c28a9/targets/github%2Fgrpc/tests

I will wait for a few more green builds before I mark this as fixed.

**Comment by veblush** [comment]
This is interesting because @stanley-cheung pushed the new image and the build became green since then for a while but somehow it started to miss it.

**Comment by jtattermusch** [comment]
> This is interesting because @stanley-cheung pushed the new image and the build became green since then for a while but somehow it started to miss it.

Yeah I agree it's weird. Somehow the existing image went missing or corrupt.

**Comment by stanley-cheung** [comment]
Yea this is weird. I did run the `tools/dockerfile/push_testing_images.sh` script to build the image locally and push to docker hub, in fact twice. First time because I forgot to run it and the build failed with this error
```
+ DOCKER_IMAGE_NAME=grpctesting/php7_stretch_x64:dedbc0925e8bc47d902d700852533731e2c0ce6a
+ docker pull grpctesting/php7_stretch_x64:dedbc0925e8bc47d902d700852533731e2c0ce6a
Error response from daemon: pull access denied for grpctesting/php7_stretch_x64, repository does not exist or may require 'docker login'
```

Note that it says "repository does not exist", not "error pulling image configuration: unknown blob". It wouldn't even get to these lines
```
4f250268ed6a: Pulling fs layer 
e19108d243ae: Pulling fs layer 
739dcfb11b47: Pulling fs layer
```

After my first run of `push_testing_images.sh`, I got to another error but it's on the image itself - some prereqs are missing. So I have to change the dockerfile itself. Then I kick off another build, but I forgot to run `push_testing_images.sh` beforehand. So I got another similar error like this:

```
+ DOCKER_IMAGE_NAME=grpctesting/php7_stretch_x64:8ad39eea13c72af84c0ddd1a265edbce260cf363
+ docker pull grpctesting/php7_stretch_x64:8ad39eea13c72af84c0ddd1a265edbce260cf363
Error response from daemon: manifest for grpctesting/php7_stretch_x64:8ad39eea13c72af84c0ddd1a265edbce260cf363 not found
```

Note that the hash checksum `8ad39eea13c7` matches the one Jan currently has trouble with. I did re-run `push_testing_images.sh` one more time so build and push that `8ad39eea13c7` image and the subsequent run was successful. 

It seems that from these lines:
```
4f250268ed6a: Pulling fs layer 
e19108d243ae: Pulling fs layer 
739dcfb11b47: Pulling fs layer 
```
it seems to indicate that the docker image `8ad39eea13c7` did exist but is somehow corrupted? This is strange.

But it does look like that Jan's force-push has resolved the issue. I will monitoring.

**Comment by jtattermusch** [comment]
All the recent builds are passing. Closing as fixed.
