### ISSUE TITLE
Unity crash-hangs on Play mode exit after gRPC client ends/interrupts/cancels streams.

### ISSUE THREAD

**Issue by DevNMY** [grpc/grpc#24427]
### What version of gRPC and what language are you using?

2.26.0 (out of the box)
2.34.0-dev daily build 5f8415c6-52f3-4b34-ade8-2acdb0b233d6 (https://packages.grpc.io/archive/2020/10/776cf3bc697e01e8f8386fe29c062603005c0d5e-5f8415c6-52f3-4b34-ade8-2acdb0b233d6/csharp/grpc_unity_package.2.34.0-dev.zip hacked with https://github.com/grpc/grpc/issues/22251#issuecomment-643416851 due to the issue described there)
C# (server), Python (client)

### What operating system (Linux, Windows,...) and version?
Windows 10 Home x64 19041.056

### What runtime / compiler are you using (e.g. python version or version of gcc)
Unity 2020.1.9, also tested 2019.4.8
(VS Community 2017 15.9.12) (only as code editor, problem also occurs if VS is never launched)
Python 3.6.9

### What did you do?
Attached example project.
Grpc definitions in Assets\Scripts\Grpc\test_service_template.proto , compiled for Python and C# using Assets\Scripts\Grpc\update_protos.sh
In Unity, load scene "testscene" (=contains only the GrpcServer.cs component) and enter Play mode. The GrpcServer class will create Protobuf messages in LateUpdateCo, and trigger any waiting gRPC Tasks via AutoResetEventManager.SetAll() to send data to any clients.
In a command shell (actually, I am using the Windows Subsystem for Linux), go to Assets\Scripts\Grpc\PythonTestClient and launch `python3 test_client.py -r -r -r -r -r`. This will create 5 threads of the uni-directional server-stream service "StreamMyData". Each thread will receive 50MB per response from the Unity server.
When intrerrupting the client with Ctrl-C, the Unity Editor will continue to run and process any new incoming streams. But after starting/interrupting the Python client repeatedly (usually <=3x), and then stopping the Play mode in Unity, Unity will immediately lock up and not recover.

### What did you expect to see?
All gRPC connections and network transfers should end cleanly/get interrupted, and Unity should exit Play mode.

### What did you see instead?
Unity locks up from time to time when exiting Play mode, and needs to be killed via Task Manager.

### Anything else we should know about your project / environment?
Defining "USE_VARIANT1" in GrpcServer.cs uses the "official" way to send a Protobuf message stream from the server to the client, using simply `await responseStream.WriteAsync(myDataResponse);`.
This will lock Tasks arbitrarily IN that await when the client is interrupted, and these Tasks will never exit, and Unity hangs when exiting Play mode.
Therefore I tried my own variant to ensure cancellation of the StreamMyData() Tasks, via per-Task CancellationTokens, stored in tokenSources. This variant, "USE_VARIANT2", does indeed clean up the StreamMyData() Tasks, so they all exit when Play mode shuts down - but Unity STILL locks up.

The same lock-up occurs outside the Editor (=building the testcene, triggering the problem, and then trying to exit the Player with Alt+F4).

Problem also occurs if the client is not interrupted, but ends cleanly(?) by sending "result.cancel()" for each open stream. To test this, launch `python3 test_client.py -r4 -r4 -r4 -r4 -r4` (=5 threads that only receive 4 responses each, then end) and repeat a few times before trying to exit Unity Play mode.

Thanks for any insights,
Wolfram

[Grpc_Hang_Testcase2020.1.9.zip](https://github.com/grpc/grpc/files/5386778/Grpc_Hang_Testcase2020.1.9.zip)

**Comment by DevNMY** [comment]
I'm interested whether this is truly a grpc bug (or one in the still "experimental" Unity extension), or whether I am doing something wrong.
Is there, for example, a workaround? Is this a network buffer problem (that can be fixed by increasing the buffer size or something)?

Note also that the problem only seems to occur for heavy network stress (such as the 5x 50MB in the example above) - I didn't have a lockup yet for "usual" sizes (i.e., in general <1MB).

**Comment by DevNMY** [comment]
Any news on this, any pointers or workarounds? Is it worth to try the most current daily builds  for both grpc and the Untiy plugin for this (including the workaround for the incorrect version defines in the linkes issue)?
Thank you!

**Comment by doctorpangloss** [comment]
Using streams hangs for me too.

**Comment by minkezhang** [comment]
I am using [NuGetForUnity](https://github.com/GlitchEnzo/NuGetForUnity) and gRPC 2.34.1; I was able to exit the client normally if the `CancellationToken` is explicitly canceled (e.g. `CancellationTokenSource(10000)`). This seems to indicate if you have a global exception handler, you can add the `Cancel()` invocation to global cleanup.

This doesn't seem like a very neat way to approach the problem, but seems to at least be a workaround. It's unclear if this is actually expected behavior or a bug.

Side note: Also investigating, but some basic printf debugging seems to indicate the stream doesn't actually close the gRPC connection on exit (could be a bug with my code).

**Comment by jtattermusch** [comment]
I'm going to close issue this since we're not going to pursuit Unity/Xamarin support in `Grpc.Core` anymore.
- The `Grpc.Core` implementation is now in maintenance mode and we're only going to focus on critical and security fixes.
- Supporting Unity/Xamarin simply presents too much maintenance overhead and it's also difficult to test with the test infrastructure available to us
- The Unity/Xamarin support has always been classified as "experimental", so discontinuing the support shouldn't be too surprising.

See [the recent update on gRPC C#](https://groups.google.com/g/grpc-io/c/OTj5mb1qzb0/m/-M81UQipAQAJ) for more details.

Note that in practice, running Grpc.Core on Unity/Xamarin might still be possible (there is nothing in principle that would prevent it from working), but it will be completely at your own risk and it's simply not one of the use cases the grpc team will help you with as `Grpc.Core` on Unity/Xamarin is now considered as "not supported" by us (but you might still be able to get help from the community).
