### ISSUE TITLE
Please support RedHat 6

### ISSUE THREAD

**Issue by cjdrake** [grpc/grpc#2444]
I am running into some problems building this library on a Centos-6.6 machine.
I realize RedHat-6 is a bit old, but I need to use it b/c of the EDA Consortium interoperability guideline:
http://www.edac.org/initiatives/committees/interoperability

AFAIK, gcc version on RedHat-6 is 4.4.7:

```
$ gcc --version
gcc (GCC) 4.4.7 20120313 (Red Hat 4.4.7-11)
Copyright (C) 2010 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
```

It would be very helpful to me if you could add this to your CI regressions.

**Comment by nicolasnoble** [comment]
We are in the process of adding more testing targets in our Jenkins matrix, and this gcc-4.4 is definitely on our radar, coming in shortly (maybe this week).

**Comment by vjpai** [comment]
Some status updates:
1. PR #2428 makes compiler issues go away in core and C++ library
2. C++ tests are not yet possible because install instructions are too specific to Ubuntu (apt-get vs yum)
3. There's a scary message on make install about only working with libprotoc-3.0.0+ , but Chris can't upgrade beyond libprotoc-2.3.0 . Is the scary message really accurate?

**Comment by vjpai** [comment]
I have done some further investigation here.

1. As I've stated before, the QPS tests will not build on gcc-4.4 as there are too many dependences on lambdas and other advanced features . This is WAI.

2. There is a repeated compiler warning about "dereferencing type-punned pointer". This is coming from the gflags version installed through yum on Centos6, which is gflags-1.3.7. This problem has long been fixed in gflags (since at least 2010 and gflags 1.4) and we should perhaps force a specific dependence on a gflags version.

3. There is also a build error coming through gtest which I need to investigate further.

4. I would recommend not installing protobuf-compiler through yum and instead just getting protobuf through "git submodule update --init" as stated in the instructions. That prevents protobuf from causing any further errors. I hope that this is an option for you.

**Comment by vjpai** [comment]
I am also doing a PR to get rid of some new issues that popped up in recent code and tests.

**Comment by vjpai** [comment]
This issue should be fixed "once and for all" when PR #2771 is merged. At that point, the C and C++ code will fully support gcc-4.4 running on Redhat 6. That said, you still need to get gflags, gtest, and protobuf following the instructions above, not using yum.

**Comment by cjdrake** [comment]
Thanks, guys :)

**Comment by geoyws** [comment]
This would allow for GRPC to work on Amazon's EC2 Linux AMI (based on Red Hat Enterprise Linux).

**Comment by dgquintas** [comment]
@geoyws , why the conditional statement? gRPC should be working under RHEL.

**Comment by jtattermusch** [comment]
We will have tests with gcc4.4 (which is what RHEL6 has) running continuously soon. See #5369

**Comment by ctiller** [comment]
Pinging this thread: we're currently considering what our C++ compiler support story should be for gRPC 1.1. Input at https://goo.gl/jS2Puz would be greatly appreciated.
