### ISSUE TITLE
Scary protoc-3.0.0+ required message - really needed?

### ISSUE THREAD

**Issue by vjpai** [grpc/grpc#2446]
Is this message actually accurate and useful? We have some users who can't upgrade from older libprotoc versions .

We couldn't find protoc 3.0.0+ installed on your system. While this
won't prevent grpc from working, you won't be able to compile
and run any meaningful code with it.

**Comment by nicolasnoble** [comment]
It depends on what they really are going to do, but this is pretty accurate in most cases, since they 1) won't be able to properly run the C++ API, and 2) the plugins won't work.

Only some binding languages such as Node or PHP will have their own parsers. All of the others have their own protoc plugin which wouldn't be useful without protobuf installed:

https://github.com/grpc/grpc/tree/master/src/compiler

**Comment by vjpai** [comment]
What about older protobuf?

**Comment by nicolasnoble** [comment]
It wouldn't work as it doesn't have the API needed to run the plugins.

**Comment by vjpai** [comment]
ok, thanks, that makes sense.

**Comment by vjpai** [comment]
I will try to work this into a more solvable issue.
