### ISSUE TITLE
TLS credential needs a way to use system default certs on client side 

### ISSUE THREAD

**Issue by ZhenLian** [grpc/grpc#24724]
Right now for the TLS credential API, the semantics for using system default certificates is not clear. We want the users to be able to 

1. provide their own root certs via a provider
2. provide only identity certs via a provider
3. not provide any provider at all to use normal TLS

The original idea was to make the provider an optional field on the client side. If the provider is not provided on the client side, we will use the system default certs. But that doesn't include the case when the client want to use identity certs via a provider in combined with the system default roots, and also doesn't include the case when the server side wants to use the system default root certs in mTLS(since the provider is a must on server side).
Another possible solution might be, for any provider implementations(no matter whether it is static data provider, cert watcher provider, etc), we make the rule that if the root certs are watched, but not provided(whose meaning depends on the provider implementation, for example, for data provider "not provided" means an empty cert contents, while for cert watcher provider it means empty root path), we will use the system default roots. 
The above method solves problems mentioned above, but I feel like the above semantics are still a bit vague, and are easy to get wrong. Also, we need to keep this rule in mind when implementing all the provider implementations, which seems to be not a good idea from maintenance's point of view.
A third option might be to add a new bool field in `options` to explicitly saying "I want system default root". If that is set, we will use system default regardless what's set in the provider.
The last option looks preferable to me. It adds minor burdens for users using system defaults to explicitly speak it out, but it makes the API clearer. 
@markdroth this is a bit different than what we talked last time. May I know your opinions on this?
@jiangtaoli2016 @yashykt FYI.

**Comment by markdroth** [comment]
I don't think it makes sense for the provider implementation to have to know or care about whether the system root certs are going to be used.  Provider implementations should just know whether they're being asked for root certs.  They should provide the root certs if they are asked, and they should not provide the root certs if they're not asked.

I think the semantic here should be that the client will use the system root certs whenever it's not told to use a different set of root certs.  So the system root certs will be used both when (a) no provider is configured and (b) a provide is configured for identity certs but not for root certs.  That way, the user is always explicitly configuring when they want to use something other than the system root certs, and we use the system root certs only when the user has not configured anything else.

The semantic on the server side is a little more complicated, because we want to support both the normal TLS case, where no root cert is needed, and the case of using mTLS with the system root certs.  So we would need some signal to differentiate between those two cases, maybe via another option in the TlsServerCredentialOptions.

An alternative approach here could be to allow using a different provider for root certs and identity certs, and to have a special provider SystemRootCertsProvider just for the system root certs.  That way, the client will require a root provider to be non-null, and it can be either the SystemRootCertsProvider or some other one.  And the server can leave the root provider null for the normal TLS case and populate it for the mTLS case, in which case it can be either the SystemRootCertsProvider or some other one.

**Comment by jiangtaoli2016** [comment]
We always treat system roots or gRPC shipped roots are fallback -- in the case application does not provide root certificates.

On client side: the system root certs will be used both when (a) no provider is configured and (b) a provide is configured for identity certs but not for root certs.

On server side: server always needs to provide a TLS certificate in TLS handshake, thus a provider is always needed. Thus the system root certs will be used when a provide is configured for identity certs but not for root certs. 

If a user configures root certs in provider, but does not provide actual root certs, then it should fail. E.g., user provides a root cert file path, but empty file content inside, then it should fail. 

Any problem with that?

**Comment by markdroth** [comment]
> On server side: server always needs to provide a TLS certificate in TLS handshake, thus a provider is always needed. Thus the system root certs will be used when a provide is configured for identity certs but not for root certs.

I believe that we determine whether we are using normal TLS or mTLS by whether the server is configured to use root certs.  So we need some way to differentiate between the cases of (a) we want to use normal TLS and (b) we want to use mTLS with the system root certs.

**Comment by ZhenLian** [comment]
> I believe that we determine whether we are using normal TLS or mTLS by whether the server is configured to use root certs. So we need some way to differentiate between the cases of (a) we want to use normal TLS and (b) we want to use mTLS with the system root certs.

Oh, whether we want mTLS is actually controlled by `grpc_ssl_client_certificate_request_type`, which will be set [here](https://github.com/grpc/grpc/blob/master/src/core/lib/security/credentials/tls/grpc_tls_credentials_options.h#L130-L133)

**Comment by markdroth** [comment]
Ah, okay.  If we have a different option for this, then I agree that the server side can just fall back to the system default root certs if there is no root cert being watched.

**Comment by ZhenLian** [comment]
OK, I think we all agreed that what Jiangtao described is a valid approach. 
I was actually suggesting to have a new bool field in `grpc_tls_credentials_options` to explicitly speak out whether we want the system default roots or not. IMHO, the fallback mechanism was designed for users who don't have much security experience, so that they would run their applications without thinking about this. For users using TLS credential API, I thought a better way is to make the decision to use system default very clear in the API, instead of "hiding" the logic in the comments, since we can assume they have some security knowledge. But I do see it somewhat goes against the original intention, which treats the system default as a fallback or last-resort thing.
@markdroth @jiangtaoli2016 what do you think? I am actually fine with either ways. If the new way proposed doesn't look right, I can also go with the approach we agreed on.

**Comment by markdroth** [comment]
I think that for the normal TLS case, using the system default root certs is actually the right default, and users shouldn't have to think about that or do anything special to make that happen.

I suspect (but please correct me if I'm wrong) that using the system default root certs will not be as common when mTLS is in use.  However, defaulting to the system root certs doesn't seem that bad anyway, since most mTLS users will need to explicitly configure their root certs, and if they forget, things won't work at all, so they should be able to figure out the problem fairly quickly.

**Comment by jiangtaoli2016** [comment]
For mTLS, it depends on whether a private CA is used. In some use case, users may want chain their certificate to the public CAs, in such case, system root certs could be used. In other setting, users config a private CA and distribute a private CA certificate inside their environment, then system root certs won't work.

I think it is unnecessary to add another bool field on tls credentials options. We just need to carefully document the intended behavior of default root cert.

**Comment by ZhenLian** [comment]
OK, sounds good. I will follow the original intention then, which is to treat the default root certs as a default fallback mechanism, and document it somewhere in core API and C++ API.

**Comment by ZhenLian** [comment]
I was revisiting this issue these days, and found one thing that we probably missed during our early discussion:
we (will) allow the case when the certs are originally missing, and fed in later(basically what OnBlockInitialHandshaker does). In the security connector, if it sees the root certs are watched and no root certificates are cached, it has no idea whether to use default system roots, or waiting for it to be filled later. Basically, the particular information of whether to use system default roots got missed as it flowed through the security connector.
I think the main thing is to make sure we are indeed in a need of a default roots. According to our discussion, we can know this information only from the providers - if the provider provides no root contents but in options we are asked to watch roots, then we will need the trust root certs. But the problem is "the provider provides no root contents" means differently for different concrete provider types, and we are using a generic provider types all over the other places....For `StaticDataCertificateProvider` it means empty root cert string, for `FileWatcherCertificateProvider` it means empty root cert path, and it may mean differently for `xDSCertificateProvider`...Can we add a general method like "IsRootEmpty" to the base provider types?

**Comment by markdroth** [comment]
You're right, we did miss that.

If we actually need an explicit "use system root certs" knob, then it should be a field in `grpc_tls_credentials_options`, as you suggested above.  It does not make sense for it to be an attribute of the provider, because the provider should not have to know or care how the creds are configured; its job is just to provide the certs it was asked to provide, not to care how those certs are being used.

It seems like we basically already have the option we need on the server side via the `grpc_ssl_client_certificate_request_type` field.  All we need is to add a similar option for the client side.

**Comment by jiangtaoli2016** [comment]
> It seems like we basically already have the option we need on the server side via the grpc_ssl_client_certificate_request_type field. All we need is to add a similar option for the client side.

Server can config whether it requires client certificate. Client always requires server certificate. I don't see how adding client equivalence of `grpc_ssl_client_certificate_request_type` could help.

Even server configs `GRPC_SSL_REQUEST_AND_REQUIRE_CLIENT_CERTIFICATE_AND_VERIFY`, server can still use default root or provide its own root.

**Comment by markdroth** [comment]
I'm not saying to add `grpc_ssl_client_certificate_request_type` on the client side.  What I'm saying is that on the server side, `grpc_ssl_client_certificate_request_type` already implicitly configures whether or not to use the system root certs.  So we need an equivalent thing on the client side: an option in `grpc_tls_credentials_options` to determine whether to use the system root certs.

**Comment by markdroth** [comment]
Oh, wait, I see what you're saying -- even on the server side, `grpc_ssl_client_certificate_request_type` doesn't really help, because we still can't tell the difference between "provide is not going to provide root cert" and "provider has not yet provided root cert", so we don't know whether to block the handshake or fail.

So yeah, I think we need a new option on both the client and server side that says whether or not to use the system root certs.

**Comment by jiangtaoli2016** [comment]
Security connector needs a clear signal whether it uses default root. It could be internal to gRPC. 

From non-xDS API, we do not have ambiguity as Zhen described: for StaticDataCertificateProvider it means empty root cert string, for FileWatcherCertificateProvider it means empty root cert path. Not sure about xDS use case though. 

If xDS use case needs such clear signal, we can add to `grpc_tls_credentials_options`.

**Comment by markdroth** [comment]
The signal cannot be internal to gRPC.  It needs to be in `grpc_tls_credentials_options` even for the TlsCreds case, because as @ZhenLian mentioned earlier, the security connector needs to be able to tell the difference between the "I am not asking for a non-system root cert" and the "I have not yet received a root cert" cases.

**Comment by jiangtaoli2016** [comment]
You are right, security connector takes grpc_tls_credentials_options as a parameter in ctor. If we add a bool to tell if it needs default roots, it needs to pass through grpc_tls_credentials_options.

**Comment by jiangtaoli2016** [comment]
It makes sense to add a method in `grpc_tls_credentials_options` to indicate whether to use default root. We also need to specify what to do if there is a conflict. E.g., if user specifies to use default root, but still passes a root pem or root filename. In that case, we should fail rather than silently using default root.

**Comment by ZhenLian** [comment]
Perfect! I will expose a new field in `grpc_tls_credentials_options` then. Thanks a lot for the great discussions here!

**Comment by yashykt** [comment]
Why can't we just use `watch_root_certs()` for this?

For the client (always needs root certs), if the options do not say that we need to watch root certs, then it is a clear signal that we need to use default roots.
For the server (only needs root certs if configured with that certificate request type), if configured to require/request client roots but root certs are not watched, then we use default roots.

Am I missing something?

**Comment by markdroth** [comment]
Yash, that existing field basically tells the credentials to ask the cert provider for the root cert.  We need a separate option to tell it to use the system root certs.  Or maybe we can make the existing option an enum instead of a bool.  But either way, we can't just use it as-is.

**Comment by yashykt** [comment]
If we do not ask the cert provider for root certs, and if we still need root certs, isn't that a sufficient signal to use system root certs?

**Comment by jiangtaoli2016** [comment]
I think @yashykt has a good point. `watch_root_cert()` in `grpc_tls_credentials_options` is a good indicator if the security connector needs to use default root. If `watch_root_cert()` is true, then default root should not be used, otherwise, default root should be used.

It looks that FileWatcherCertificateProvider does not call `set_watch_root_cert()`.

**Comment by markdroth** [comment]
Okay, I see what you're saying.  Yeah, `watch_root_cert()` could work on the client side, because we know we need the root cert there, so if we're not asking the provider for it, we must be using the system root cert.

What about on the server side, since we might not be using any root cert there?  Does the combination of `grpc_ssl_client_certificate_request_type` and `watch_root_cert()` allow configuring all of (a) TLS, (b) mTLS with provider, and (c) mTLS with system root cert?

> It looks that FileWatcherCertificateProvider does not call `set_watch_root_cert()`.

No provider ever calls `set_watch_root_cert()`.  Providers never interact with `grpc_tls_credentials_options` at all.

**Comment by jiangtaoli2016** [comment]
Mark, Zhen and I looked at the existing default root cert behavior yesterday. It only applies on client side. Server side never uses default root. We can keep the same behavior.

**Comment by markdroth** [comment]
Why does server side never use the system root certs?  Don't we want some way to configure that, or do we not think that's something that users will ever need to do?

**Comment by jiangtaoli2016** [comment]
It is not clear if we need server side using system root cert yet. 

- Take Google APIs as example, it is one-side TLS, client could use default system root to verify server's cert. But server does not need to verify client cert.
- In many mTLS use cases for workload-to-workload communication, it is likely that the certificates are issued from a private CA (not chained to public roots). Thus server side does not need to use default system root. PSM does not use public root, IIUC.

**Comment by sanjaypujare** [comment]
> Why does server side never use the system root certs? Don't we want some way to configure that, or do we not think that's something that users will ever need to do?

If server needs to use root certs it is the mTLS case (which is TLS + client cert) where server will only accept a trusted client cert and use the client identity (derived from the client cert) in other scenario such as authorization. It doesn't make sense for the server to use system root certs in such a scenario. On the other hand in the TLS case where a client can trust the server based on system root certs and use hostname verification to trust/authenticate the server and establish an encrypted channel for communication which is sufficient in most cases.

**Comment by ZhenLian** [comment]
Sounds good! It seems we have reached an agreement here? From our discussions, I think right now we are making the default system root a behavior only on the client side, and we will apply it only when `watch_root_certs()` is set to "false". It wouldn't be too bad even if later on server wants to use default system roots as well - the server can specify the system default root locations manually from `FileWatcherCertificateProvider`.
I will create a PR for this, but feel free to comment if you think there are still issues we missed in the meantime. Thanks again for all the excellent discussions here!

**Comment by markdroth** [comment]
If we discover a case in the future where we want to use the system root cert on the server side, will we have a way to support that?  Would we be able to use the combination of `grpc_ssl_client_certificate_request_type` and `watch_root_cert()` in that case?

**Comment by jiangtaoli2016** [comment]
In the future, if server side needs to enable default system root, we can just make decision based on `watch_root_cert()`. If `watch_root_cert()` is true, then do not use system root. Otherwise, use default root. If the server configures to not require cert, adding system root won't hurt.

**Comment by markdroth** [comment]
Okay, then this sounds fine to me.
