### ISSUE TITLE
grpc_tools.protoc Import "google/protobuf/timestamp.proto" was not found or had errors

### ISSUE THREAD

**Issue by animesh-sharama** [grpc/grpc#24792]
### What version of gRPC and what language are you using?
1.29.0
### What operating system (Linux, Windows,...) and version?
Linux 5.4.0-53-generic

### What runtime / compiler are you using (e.g. python version or version of gcc)
Python 3.7.1

### What did you do?
Please provide either 1) A unit test for reproducing the bug or 2) Specific steps for us to follow to reproduce the bug. If there’s not enough information to debug the problem, gRPC team may close the issue at their discretion. You’re welcome to re-open the issue once you have a reproduction.
created a proto with timestamp
```
import "google/protobuf/timestamp.proto";

message MyMessage {
  google.protobuf.Timestamp timestamp = 1;
}
```
inside my setup.py
```
import grpc_tools.protoc
if 'PROTOC' in os.environ and os.path.exists(os.environ['PROTOC']):
    protoc = os.environ['PROTOC']
else:
    protoc = find_executable("protoc")

# The below works without any error and generates relevant py file
protoc_command = [protoc, "-I=path/", "--python_out=.", 'proto/mymessage.proto']

# The below does not work with error Import "google/protobuf/timestamp.proto" was not found or had errors.
grpc_tools.protoc.main([
        'grpc_tools.protoc',
        '-I{}'.format('=path/'),
        '--grpc_python_out=.',
        'proto/mymessage.proto'
    ])
```

### What did you expect to see?
Both **grpc_tools.protoc** and **protoc** to generate protos without error.

### What did you see instead?
```
Import "google/protobuf/timestamp.proto" was not found or had errors.
```
Interesting enough when I run the **grpc_tools.protoc** from command line it works without the error
```
python -m grpc_tools.protoc -I=path/ --python_out=. --grpc_python_out=. path/proto/mymessage.proto
```
Make sure you include information that can help us debug (full error message, exception listing, stack trace, logs).

See [TROUBLESHOOTING.md](https://github.com/grpc/grpc/blob/master/TROUBLESHOOTING.md) for how to diagnose problems better.

**Comment by gnossen** [comment]
In general, I wouldn't recommend using `protoc.main` instead of the CLI interface, but the issue you're running into is due to a missing include path pointing to the [well-known types](https://developers.google.com/protocol-buffers/docs/reference/google.protobuf), which are packaged up in the `grpcio-tools` wheel. You'll need to add those to your invocation to make it succeed. See [how the CLI command does it](https://github.com/grpc/grpc/blob/1bf2ab3ab244a7fc7df7fe1d05146842ec61da76/tools/distrib/python/grpcio_tools/grpc_tools/protoc.py#L173) as a reference.
