### ISSUE TITLE
Can this library communicate with Grpc.AspNetCore (2.32.0) NuGet package project and how?

### ISSUE THREAD

**Issue by hovek** [grpc/grpc#24811]
This is the error I get:
Grpc.Core.RpcException: 'Status(StatusCode="Unavailable", Detail="failed to connect to all addresses", DebugException="Grpc.Core.Internal.CoreErrorDetailException: {"created":"@1606025509.864000000","description":"Failed to pick subchannel","file":"T:\src\github\grpc\workspace_csharp_ext_windows_x86\src\core\ext\filters\client_channel\client_channel.cc","file_line":4166,"referenced_errors":[{"created":"@1606025509.864000000","description":"failed to connect to all addresses","file":"T:\src\github\grpc\workspace_csharp_ext_windows_x86\src\core\ext\filters\client_channel\lb_policy\pick_first\pick_first.cc","file_line":398,"grpc_status":14}]}")'

If they can't communicate I would like to know why they can't communicate, why these two projects exist, why not only one, what are the differences, and which one should I use?

**Comment by jtattermusch** [comment]
Grpc.Core is fully interoperable with Grpc.AspNet.Server (and Grpc.Net.Client), which is something that's mentioned in our public docs.
There are many examples available that show that this is something that works very well. Based on your error message, it seems that you're server is listening on the wrong port? Without more details it's impossible to tell exactly what the problem is.

**Comment by hovek** [comment]
Problem was that client (Grpc) can't connect to localhost but directly to 127.0.0.1 and so the server (Grpc..AspNetCore) must also listen on 127.0.0.1 and not localhost. I have localhost setup in the hosts file.

**Comment by hovek** [comment]
"mentioned in our public docs." where is that located exactly?
