### ISSUE TITLE
Failed openSSL call causes subsequent grpc failures

### ISSUE THREAD

**Issue by TobyEalden** [grpc/grpc#24865]
### What version of gRPC and what language are you using?
C++
v1.29.1

### What operating system (Linux, Windows,...) and version?
MacOS 11.01

### What runtime / compiler are you using (e.g. python version or version of gcc)
Apple clang version 12.0.0 (clang-1200.0.32.27)

### What did you do?
Due to a bug in my app, a call was being issued to the openSSL `EVP_DigestVerifyFinal` with an empty signature value, essentially:
```
EVP_DigestVerifyFinal(ctx, validPointer, zeroLength);
```
This call fails as expected. Note that the `EVP_DigestVerifyFinal` call is not being made on a grpc thread or as part of any grpc call.

However the next grpc call always fails with:

```
E1201 07:49:16.759385000 4659805696 ssl_transport_security.cc:488]     Corruption detected.
E1201 07:49:16.759435000 4659805696 ssl_transport_security.cc:464]     error:04091077:rsa routines:int_rsa_verify:wrong signature length
E1201 07:49:16.759441000 4659805696 secure_endpoint.cc:208]            Decryption error: TSI_DATA_CORRUPTED
```

### What did you expect to see?
Failures in openSSL API to not affect subsequent grpc calls.

### What did you see instead?
The openSSL API failed as expected due to the invalid inputs. This error is handled and execution of the app continues as normal. However the failed openSSL API seems to corrupt the grpc stack somehow and the next grpc call fails.

### Anything else we should know about your project / environment?
I am building with `gRPC_SSL_PROVIDER=package`. My openSSL version is 1.1.1d.

As a side note, a Windows 10 build of the same app does not exhibit this behaviour (i.e. the `EVP_DigestVerifyFinal` call fails as expected and grpc carries on as normal).

Out of interest - what is the perceived wisdom with regards to gprc and openSSL - is it recommended one way or the other as to whether to build against the local openSSL package or use the bundled BoringSSL?

**Comment by jiangtaoli2016** [comment]
@ZhenLian could you please take a look?

**Comment by ZhenLian** [comment]
Thanks for reporting the issue!

> Out of interest - what is the perceived wisdom with regards to gprc and openSSL - is it recommended one way or the other as to whether to build against the local openSSL package or use the bundled BoringSSL?

As far as I know, it might be better to use a bundled BoringSSL package, since we have tests to avoid unexpected behaviors like this when using local OpenSSL. If using a local OpenSSL version, it could be difficult to reproduce the error and identify the root cause. maybe @jiangtaoli2016 can confirm.

Regards to this bug, I looked through the code and didn't find anything suspicious. If the application setting the empty signature value is completely separate from gRPC, then probably some static variables or macros are polluted in OpenSSL(I am not very familiar with the OpenSSL code; just my random guess). One possible way to narrow down the problem is to enable more full loggings: https://github.com/grpc/grpc/blob/master/TROUBLESHOOTING.md.
Since this only happens on a particular platform(MacOS), and it only appeared when another application did something wrong to the local OpenSSL, it would be very hard to reproduce the error. Does gRPC work if you solve the empty signature bug in another application? @jiangtaoli2016 How do you suggest we proceed? It would be great if @TobyEalden  can find some ways(like a Docker image) for us to reproduce the error.

**Comment by TobyEalden** [comment]
Thanks for the quick response and info. 

> Does gRPC work if you solve the empty signature bug in another application?

Yes, as soon as I fix the empty signature (i.e. don't call `EVP_DigestVerifyFinal` if the signature length is zero) everything works as expected.

I have attached a verbose log of an entire run - search for `TSI_DATA_CORRUPTED` to find the location of the failure.

It's not feasible for me to share my app but I'll look into producing a more minimal example when I get the chance - but it won't be for the next week or two.

Thanks again.

[verification_failure.log](https://github.com/grpc/grpc/files/5627557/verification_failure.log)

**Comment by erm-g** [comment]
@TobyEalden the [26834](https://github.com/grpc/grpc/pull/26834) PR should have fix the issue - do you still experience it?

**Comment by matthewstevenson88** [comment]
Closing due to no reply and because #26834 likely fixed the issue.
