### ISSUE TITLE
Some absl libraries are missing when building and installing grpc using CMake with `ABSL_ENABLE_INSTALL=ON`

### ISSUE THREAD

**Issue by hungptit** [grpc/grpc#24976]
If I build and install grpc locally using CMake with this option `ABSL_ENABLE_INSTALL=ON` then  I won't be able to use gRPC in my projects because the configuration step is failed with below error messages. Everything will be back to normal if I set `ABSL_ENABLE_INSTALL=OFF`.

```
protobuf_DIR: /home/hungptit/working/grpc-cmake-template/3p/lib64/cmake/protobuf/
gRPC_DIR: /home/hungptit/working/grpc-cmake-template/3p/lib/cmake/grpc
CMake Error at proto/CMakeLists.txt:2 (find_package):
  Found package configuration file:

    /home/hungptit/working/grpc-cmake-template/3p/lib/cmake/grpc/gRPCConfig.cmake

  but it set gRPC_FOUND to FALSE so package "gRPC" is considered to be NOT
  FOUND.  Reason given by package:

  The following imported targets are referenced, but are missing:
  absl::optional absl::time absl::synchronization absl::strings
  absl::str_format absl::status absl::memory absl::base absl::statusor
  absl::bind_front absl::inlined_vector absl::flat_hash_set
  absl::flat_hash_map

**Comment by sunzen** [comment]
Is there any result? I also encounter this.

**Comment by mipac** [comment]
same problem for me

**Comment by vjk1kor** [comment]
Adding 
`find_package(absl CONFIG REQUIRED)`
before
`find_package(gRPC CONFIG REQUIRED)`
solved the issue for me

**Comment by sekharpedamallu** [comment]
> Adding
> `find_package(absl CONFIG REQUIRED)`
> before
> `find_package(gRPC CONFIG REQUIRED)`
> solved the issue for me

In which file of the grpc code, is this change required ?? or is it in your own script ??

**Comment by vjk1kor** [comment]
I don't think your issue is a missing 'find_package'. The line `args "-DgRPC_ABSL_PROVIDER=package"` does exactly that.
Line 38 of [abseil-cpp.cmake](https://github.com/grpc/grpc/blob/master/cmake/abseil-cpp.cmake).
The statements 'gRPC_xx_PROVIDER=package' is telling cmake that you have installed these dependencies and it should look for them. If you actually haven't installed them, then you should change the instruction to 'gRPC_xx_PROVIDER=module', which will make cmake build these dependencies

**Comment by hungptit** [comment]
This issue seems to be fixed in the master branch.

**Comment by mehrshad-kh** [comment]
I had a somewhat similar issue and [this][1] post helped me.

[1]: https://stackoverflow.com/a/76940745/12660318
