### ISSUE TITLE
The C# generated client should use the Interface the service implements.. 

### ISSUE THREAD

**Issue by StingyJack** [grpc/grpc#25015]
### Is your feature request related to a problem? Please describe.
The problem is that I cant properly identify callers to the service. I have to hunt through our codebase as text or guess at the callers when making changes.  Having the client use the service's interface, and not a copy of it, means that all the navigation tools (namely "Find all References" in VS, but others) can locate usages and callers and I can make changes without guessing.

Using a shared contract between client and server was incredibly useful for IChannelFactory<T> 

### Describe the solution you'd like
I'd like the client to utilize the service's c# interface definition automatically if present. 

Or I'd like the proto compiler to also generate an interface if one is not present and use that

Or I'd like to be able to specify an interface to use for the client in the proto file

**Comment by jtattermusch** [comment]
I'm not sure I understand what exactly you're asking for but:

1. we've had a request to use interfaces in the generated code and it's something we've rejected long time ago (for good reasons): see https://github.com/grpc/grpc/issues/5416 and https://github.com/grpc/grpc/issues/5371

2. the gRPC C# API is stable (and has been for long time) and there is a VERY high bar for doing any non-backward-compatible changes in the API (because such change has the potential of breaking all the existing users) - and it looks like you're suggesting something that would require making a breaking change in the API (IIUC) - and it is unlikely that such change would happen without having an extremely good reason (such as a critical security issue or so).

**Comment by StingyJack** [comment]
If you arent sure what someone is asking, is the right thing to do to get clarification or to just tell them to shut up? 

The client generated from the proto file is generated without any linkage back to the service it connects to. I'm asking that if the service is implementing an interface (or multiple) that the client have the option of referencing the same interface contracts, so that discovering callers of a service (in the event it needs a modification and testing) in an enterprise codebase can become a reasonable thing to do.

But I'm open to anything that solves the problem of being able to easily and reliably (and via existing tools) identify clients for a GRPC service in an Enterprise codebase that may have several hundred repos.

**Comment by jtattermusch** [comment]
> If you arent sure what someone is asking, is the right thing to do to get clarification or to just tell them to shut up?
> 
> The client generated from the proto file is generated without any linkage back to the service it connects to. I'm asking that if the service is implementing an interface (or multiple) that the client have the option of referencing the same interface contracts, so that discovering callers of a service (in the event it needs a modification and testing) in an enterprise codebase can become a reasonable thing to do.
> 
> But I'm open to anything that solves the problem of being able to easily and reliably (and via existing tools) identify clients for a GRPC service in an Enterprise codebase that may have several hundred repos.

I closed the issue because it didn't seem actionable - I wasn't sure what exact change you were requesting (it would be better if you provided an example and the exact change you're proposing) but from your description I was pretty clear that such change would require changing the public API (and I explained why that's not something we want to do). Currently, the generated code for the client and the server are different because the method signatures for the client stub method and the server-side handler are different - so these two cannot really inherit from same interface.

client side method signature
https://github.com/grpc/grpc/blob/b7df39f095417754e99558d3c9b277e30274005f/src/csharp/Grpc.Examples/MathGrpc.cs#L190
server-side handler signature
https://github.com/grpc/grpc/blob/b7df39f095417754e99558d3c9b277e30274005f/src/csharp/Grpc.Examples/MathGrpc.cs#L110

**Comment by StingyJack** [comment]
The client does not have to implement the service's interface, it just needs to reference it. I've taken care to say "used" or "reference" and not "implement" WRT the client side. 

Nothing in those links explains to me why its a bad idea to have some way to positively identify clients for a particular service, which is what I'm asking for.

This has been possible with other web service technologies in the past, so I gave those as examples of how its been done before and why its valuable.

**Comment by jtattermusch** [comment]
> The client does not have to implement the service's interface, it just needs to reference it. I've taken care to say "used" or "reference" and not "implement" WRT the client side.

What do you mean by "service's interface"? We don't generate an interface, only an abstract base class (e.g. MathBase class).  And exactly what do you mean by "reference"? As said, I'd be easier if you provided an example of how the exactly the generated code should/could change - you seem to have some idea for a solution in mind.

> 
> Nothing in those links explains to me why its a bad idea to have some way to positively identify clients for a particular service, which is what I'm asking for.
> 
> This has been possible with other web service technologies in the past, so I gave those as examples of how its been done before and why its valuable.

**Comment by StingyJack** [comment]
We continue to actively discuss this, yet it still remains closed. The first thing to do to show you are actually willing and receptive to an idea is to reopen the issue. Otherwise it looks like your mind has already been made up before understanding the request. 

> What do you mean by "service's interface"? We don't generate an interface, only an abstract base class (e.g. MathBase class). And exactly what do you mean by "reference"? As said, I'd be easier if you provided an example of how the exactly the generated code should/could change - you seem to have some idea for a solution in mind.

Generating the abstract base class and totally eschewing the common design by contract artifact for .net - an Interface.is half of the problem (that and all the sealed classes*). I took the Greeter tutorial and added an interface (bottom left) to the service that was generated (top left), and in the client (right side) have highlighted a usage of that service interface.  This was just the first place I found to illustrate what I was looking for, and I'm sure that its probably not the best place to create the reference
![image](https://user-images.githubusercontent.com/15381181/104530314-b5b90d80-55d9-11eb-91dc-f0e692b804f6.png)

Its really a little bit of code linkage/reference that will help bridge an enormous gap. We had this with WSDL and SOAP, then we had it really good with WCF, it managed to be forgotten for the first few years of web API but now thats pretty solid with Swagger/openapi. Now gRPC has come along and is missing this kind of thing. 

\* _the sealed classes are wrong because the generated code does not belong to the author of the tool that generated it. Preventing the owners of that code from extending it is not a decision the toolmaker is ethically allowed to make. The owners code will need to be extended for whatever reason needed to in order to support the business. Professional code design patterns and opinions from someone outside of that team or business are completely irrelevant._

**Comment by jtattermusch** [comment]
> We continue to actively discuss this, yet it still remains closed. The first thing to do to show you are actually willing and receptive to an idea is to reopen the issue. Otherwise it looks like your mind has already been made up before understanding the request.
> 
> > What do you mean by "service's interface"? We don't generate an interface, only an abstract base class (e.g. MathBase class). And exactly what do you mean by "reference"? As said, I'd be easier if you provided an example of how the exactly the generated code should/could change - you seem to have some idea for a solution in mind.
> 
> Generating the abstract base class and totally eschewing the common design by contract artifact for .net - an Interface.is half of the problem (that and all the sealed classes*).

Honestly, the decision not to use interfaces has been made a long time ago and is sufficiently explained in #5416 and #5371 (I posted both links before). Regardless of whether that decision was right or wrong (I don't want to reopen that discussion here), the decision has been made and it's now part of our stable API and I already explained why it's important not to break our current stable API.

 I took the Greeter tutorial and added an interface (bottom left) to the service that was generated (top left), and in the client (right side) have highlighted a usage of that service interface.

Ok, so after I explained why introducing a code generated interface is problematic (it breaks users' code if they add a new method to a .proto file, which is something that should really be a non-breaking change) the first thing you do is you suggest adding a code generated interface - sorry but that doesn't work.

 This was just the first place I found to illustrate what I was looking for, and I'm sure that its probably not the best place to create the reference
> ![image](https://user-images.githubusercontent.com/15381181/104530314-b5b90d80-55d9-11eb-91dc-f0e692b804f6.png)
> 
> Its really a little bit of code linkage/reference that will help bridge an enormous gap. We had this with WSDL and SOAP, then we had it really good with WCF, it managed to be forgotten for the first few years of web API but now thats pretty solid with Swagger/openapi. Now gRPC has come along and is missing this kind of thing.
> 
> * _the sealed classes are wrong because the generated code does not belong to the author of the tool that generated it. Preventing the owners of that code from extending it is not a decision the toolmaker is ethically allowed to make. The owners code will need to be extended for whatever reason needed to in order to support the business. Professional code design patterns and opinions from someone outside of that team or business are completely irrelevant._

Ok, so it looks you think our API design is completely flawed. You have the right to express your opinion but saying our API choices are unethical and unprofessional isn't very constructive. Please understand that we cannot change our public API every time someone comes to us and say they don't like something (and in fact we got plenty of positive feedback about the API in the past).

Since it seems that your focus is to mostly criticise the way we do and have done stuff and since you didn't bring any viable solution to the table (e.g. a PR that clearly shows what you suggest doing and that's compatible with the existing constraints and prior design decisions and is more well thought out than just "maybe we could do this"), I'm going to leave this issue closed since it doesn't seem we are getting anywhere. 

That said, I can see that the general idea you proposed would be a nice improvement to the navigability of the code, but frankly the concern is rather a minor thing and it's not a priority (there's always a lots of things we could improve and our time is limited) for us to actively go ahead and start looking for a solution (IMHO, given the constraints, it might be quite difficult to come up with something that works). So the only way to get this improvement in place is that someone comes up with a design that works (can be surprisingly tricky and I don't see a straighforward solution) and actually creates a pull request with all the necessary code changes.

**Comment by StingyJack** [comment]
> Ok, so it looks you think our API design is completely flawed. 

Don't exaggerate, this is about one missing piece and one extra keyword in the generated output. Its not a critique of the entire work. 

> a PR that clearly shows what you suggest doing and that's compatible with the existing constraints and prior design decisions and is more well thought out than just "maybe we could do this"

So the bar for entry is to submit working code that accomplishes the task and that considers all of the info for the > 9K issues, the 120 current PR's (and commentary within) that could be approved, and the 15K PR's (and commentary within) that have been approved. Thats not including any design discussion had verbally or otherwise outside of GH. Dont you think thats an unrealistically high bar to set, and that the more pragmatic thing would be to state the need and determine feasibility?

**Comment by jtattermusch** [comment]
> > Ok, so it looks you think our API design is completely flawed.
> 
> Don't exaggerate, this is about one missing piece and one extra keyword in the generated output. Its not a critique of the entire work.
> 
> > a PR that clearly shows what you suggest doing and that's compatible with the existing constraints and prior design decisions and is more well thought out than just "maybe we could do this"
> 
> So the bar for entry is to submit working code that accomplishes the task and that considers all of the info for the > 9K issues, the 120 current PR's (and commentary within) that could be approved, and the 15K PR's (and commentary within) that have been approved. Thats not including any design discussion had verbally or otherwise outside of GH. Dont you think thats an unrealistically high bar to set, and that the more pragmatic thing would be to state the need and determine feasibility?

I tried to explain several times that I think making such change is harder than it seems (and I explained what the limitations are) and I have a problem visualizing a solution that would be make sense. Since this is only a nice to have feature, the demand for it doesn't seem high and its priority is low I simply cannot justify spending days thinking about how a perfect solution for this would look like (as you've pointed out, there's >500 other open issues, so of them with much higher priority - and someone also needs to look into those). So if this is a feature that you really want and you're prepared to invest the time and do most of the research to find a solution that works and then implement it, it might happen (and of course there's risk involved that this won't get accepted - but this is how opensource works) but otherwise I'm sorry. So far I've only seen a proposal that was in form of a screenshot and was involving things that I specifically mentioned before as not ok (=interfaces) - and that simply doesn't make the cut.

Feel free to create a PR that shows some acceptable design (e.g. not contradicting to what I've pointed out in my previous comments) and involves the full change (a good description, changes to the codegen, regenerates all the proto sources and perhaps also have an example and a test) and then we can discuss. If you think this too high of a bar for having your change considered, please know that we've accepted many contribution like that in the past and it's clearly not an impossible standard. No one is asking you to know details of 9K past issues, you just need to show something that's reviewable (right now we don't even have a concrete proposal to discuss) and that demonstrates that you're ready to invest your time into making the changes happen. For low priority feature requests this is a totally fair approach - you need to make things so that maintainers can only provide feedback (which I'm am happy to provide, time permitting) and don't have to go actively investigating/experimenting/writing implementation themselves (you wouldn't wanna use a project where maintainers just go chasing after low priority features rather than focusing on high-impact bug and critical features). If you are not willing to buy into this scheme, that's ok but then you cannot be a grpc contributor.

I've already spent too much time on this unproductive discussion, so I don't plan to discuss this further (but I can review a PR). Thanks for you understanding.

**Comment by StingyJack** [comment]
I appreciate you taking the time to articulate. I do read every word and linked issue, so while you may feel this was not productive, your time spent wasn't wasted by me.  I just dont believe the idea that using an interface and making additive only changes would break a client, and thats what I understood after reading all of that. I'll read it again later to make sure.  

I also found the correct repo for the protoc, and where it sticks the sealed modifier on the generated client.

**Comment by jtattermusch** [comment]
> I appreciate you taking the time to articulate. I do read every word and linked issue, so while you may feel this was not productive, your time spent wasn't wasted by me. I just dont believe the idea that using an interface and making additive only changes would break a client, and thats what I understood after reading all of that. I'll read it again later to make sure.

Imagine this scenario:
1. you generate an interface for a service (there's methods for methods in service's .proto files)
2. since the interface is public, the user can decide to implement that interface in their code (e.g in tests). Some users will surely do that.
3. you add a new method to the service (very resonable to do and that's how services evolve) and regenerate .proto files - now the interface has a new method
4. user's implementation of that interface now miss this new method and user's project now doesn't compile anymore
5. we don't want people's builds to break because they've added a single RPC to their .proto.

This scenario is sufficiently described in the issue I've posted before. Note that this isn't intended to start a new discussion, just an explainer why interfaces are not ok.

> 
> I also found the correct repo for the protoc, and where it sticks the sealed modifier on the generated client.

**Comment by StingyJack** [comment]
From the perspective of use there are three generation options. Client or Server, or Both.

In the case where the client and server are generated at the same time from a proto file, using a common interface should not be a problem.  (I'm guessing this will very likely be the overwhelming majority of usages, is there any telemetry on the generation type decision?

In the case where they are generated at different times, the server can have the additional function on it (version 1.1) and that should not break clients that were made using a prior interface/proto (version 1.0). The clients simply wont know about the added function as it wont be in the version of the interface that they reference. 

When they choose to update to v1.1 of the proto/interface is when they will be compelled to add the new function on to any implementations, but it would not be forced on them as a surprise as your scenario describes. 

Also the latter group has chosen to take the path with a greater risk of mismatching client and server, but even with taking on that additional risk, they would not be getting any increase in code management burden other than the deliberation that automatically accompanies the choice of generating client and server at different times.
