### ISSUE TITLE
Xamarin iOS: Error while loading assemblies: /Users/runner/.nuget/packages/grpc.core/2.33.0/runtimes/win/native/grpc_csharp_ext.x64.dll

### ISSUE THREAD

**Issue by smdelacruz** [grpc/grpc#25202]
We want to build our Xamarin iOS using Microsoft Azure Hosted agent with MacOS VM but we are having an error when it tries to load the GRPC assemblies, our Xamarin Android is working well with grpc and grpc core packages but not on Xamarin iOS. 
Any help is greatly appreciated. 
### What version of gRPC and what language are you using?
c# - grpc 2.33.0

### What operating system (Linux, Windows,...) and version?
Windows

### What runtime / compiler are you using (e.g. python version or version of gcc)
OS: Macos-latest
.NET version: 2.0
grpc 2.33
grpc.core 2.33
Xamarin.iOS 14.6.0.15

### What did you do?
Steps of our pipeline 
`pool:
  vmImage: 'macos-latest'

variables:
  buildConfiguration: 'Release'
  outputDirectory: '$(build.binariesDirectory)/$(buildConfiguration)'

- task: NuGetToolInstaller@1

- task: NuGetCommand@2
  inputs:
    restoreSolution: '**/*.sln'

- **task: XamariniOS@2 -- FAILURE HERE **
  inputs:
    solutionFile: '**/*iOS.csproj'
    configuration: '$(buildConfiguration)'
    buildForSimulator: true
    packageApp: true`

### What did you expect to see?
Build success

### What did you see instead?
_CompileToNative:
  /Library/Frameworks/Xamarin.iOS.framework/Versions/Current/bin/mtouch @/Users/runner/work/1/s/ProjectName/ProjectName.iOS/obj/iPhoneSimulator/Release/response-file.rsp "--gcc_flags=-L/Users/runner/.nuget/packages/grpc.core/2.33.0/build/Xamarin.iOS10/../../native/ios/universal -lgrpc_csharp_ext -force_load /Users/runner/.nuget/packages/grpc.core/2.33.0/build/Xamarin.iOS10/../../native/ios/universal/libgrpc_csharp_ext.a -L/Users/runner/.nuget/packages/grpc.core/2.33.0/build/Xamarin.iOS10/../../native/ios/universal -lgrpc -force_load /Users/runner/.nuget/packages/grpc.core/2.33.0/build/Xamarin.iOS10/../../native/ios/universal/libgrpc.a" 
  Xamarin.iOS 14.6.0.15 (d16-8: 87a1b18d8 using framework: /Applications/Xcode_12.2.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator14.2.sdk
MTOUCH : error MT0009: Error while loading assemblies: /Users/runner/.nuget/packages/grpc.core/2.33.0/runtimes/win/native/grpc_csharp_ext.x64.dll. [/Users/runner/work/1/s/ProjectName/ProjectName.iOS/ProjectName.iOS.csproj]

### Anything else we should know about your project / environment?
-Xamarin Android is working well
-The Pipeline is working well if grpc is removed.

**Comment by drfloob** [comment]
I've assigned @jtattermusch, who knows the C# implementation quite well. I'm not familiar with the C# implementation, but I'm curious if https://github.com/grpc/grpc/tree/master/src/csharp/experimental#xamarin has any answers for you. What jumps out to me specifically is that your build shows grpc core v2.31.0, not 2.34.0 as you mentioned. 

> Starting from gRPC C# 2.34.x: in addition to the regular Grpc.Core dependency, you will also need to add Grpc.Core.Xamarin dependency to your project (which has the mobile-specific builds of c# native extension library). The Grpc.Core and Grpc.Core.Xamarin package versions must always match exactly for things to work.

**Comment by smdelacruz** [comment]
Sorry for the confusion, I was trying different kind of grpc  versions just to see any difference on the error log. Unfortunately, if I use 2.34, I will get 106 more errors about grpc. I searched the new errors and its quite similar to this https://github.com/grpc/grpc/issues/19732 (except I dont use tvOS). Hoping for any feedback.

**Comment by jtattermusch** [comment]
What seems weird is that the error says it's trying to load `/Users/runner/.nuget/packages/grpc.core/2.33.0/runtimes/win/native/grpc_csharp_ext.x64.dll.` - it should be trying to load  an iOS specific version of that library (why would a windows specific dll be loaded on a MacOS machine that is running iOS simulator?).

**Comment by jtattermusch** [comment]
I'm going to close issue this since we're not going to pursuit Unity/Xamarin support in `Grpc.Core` anymore.
- The `Grpc.Core` implementation is now in maintenance mode and we're only going to focus on critical and security fixes.
- Supporting Unity/Xamarin simply presents too much maintenance overhead and it's also difficult to test with the test infrastructure available to us
- The Unity/Xamarin support has always been classified as "experimental", so discontinuing the support shouldn't be too surprising.

See [the recent update on gRPC C#](https://groups.google.com/g/grpc-io/c/OTj5mb1qzb0/m/-M81UQipAQAJ) for more details.

Note that in practice, running Grpc.Core on Unity/Xamarin might still be possible (there is nothing in principle that would prevent it from working), but it will be completely at your own risk and it's simply not one of the use cases the grpc team will help you with as `Grpc.Core` on Unity/Xamarin is now considered as "not supported" by us (but you might still be able to get help from the community).
