### ISSUE TITLE
What is the reason to return an exception?

### ISSUE THREAD

**Issue by peter-volkov** [grpc/grpc#25207]
https://github.com/grpc/grpc/blob/3f011c2171612edf1a54ca106a1c092e08534d33/src/python/grpcio/grpc/_interceptor.py#L250
What is the reason to return an exception instead of passing it to the caller code?
It would be a more idiomatic, pythonic way.

We have a custom retry interceptor and we were using exception handing over the continuation call
https://github.com/yandex-cloud/python-sdk/pull/13/files
to catch the error.
Because of the behavior described above our code had problems with catching RPCError until we begun checking continuation return type and raising it if it is an instance RPCError

It seemed to be an intuitive approach.

**Comment by epikhinm** [comment]
@lidizheng any thoughts?

**Comment by lidizheng** [comment]
Sorry for this inconvenient approach. We know the exception handling in the Python interceptors are not ideal for quite a while. But it's kind hard to change since it is released for years and marked as stable. It might need tons of energy to change the behavior.

In your code, it seems the exception handling kind of work, just not as Pythonic.

**Comment by lidizheng** [comment]
For questions, you might find https://groups.google.com/g/grpc-io more useful than GitHub.
