### ISSUE TITLE
Running grpc client and server on separate machines failed

### ISSUE THREAD

**Issue by Thompson-Liu** [grpc/grpc#25281]
### What version of gRPC and what language are you using?
grpcio==1.34.1
grpcio-tools==1.34.1
python

### What operating system (Linux, Windows,...) and version?
MacOS

### What runtime / compiler are you using (e.g. python version or version of gcc)
Python 3.6.5

### What did you do?
Please provide either 1) A unit test for reproducing the bug or 2) Specific steps for us to follow to reproduce the bug. If there’s not enough information to debug the problem, gRPC team may close the issue at their discretion. You’re welcome to re-open the issue once you have a reproduction.
<img width="1486" alt="Screen Shot 2021-01-26 at 11 48 31 PM" src="https://user-images.githubusercontent.com/55003391/105944475-60e1b200-6031-11eb-8707-e1592155a5e0.png">
<img width="1733" alt="Screen Shot 2021-01-26 at 11 48 53 PM" src="https://user-images.githubusercontent.com/55003391/105944487-63dca280-6031-11eb-8681-8ca4daede986.png">

### What did you expect to see?
Client connect to server without error

### What did you see instead?
Failed to pick sub-channel

Make sure you include information that can help us debug (full error message, exception listing, stack trace, logs).

See [TROUBLESHOOTING.md](https://github.com/grpc/grpc/blob/master/TROUBLESHOOTING.md) for how to diagnose problems better.

### Anything else we should know about your project / environment?
The program runs fine under localhost(if localhost hosts both server and client), but failed if hosted on different machines.

**Comment by apolcyn** [comment]
From that error, it looks like the TCP connection is failing to establish. This could be due to a number of reasons, for example because the server address does not correctly locate what address the server is bound to, a firewall, etc.

For debugging purposes, it might help to first see if you can establish a simple TCP connection to the server, from the client's machine, but without using gRPC on the client at all.

For example, leave the server running, and from the client's machine, run something like:

```
$ python -c "import socket; socket.create_connection(['192.168.1.9', 50051], timeout=10)"
```

If that fails, then most likely there is a firewall, or the address is incorrect, or the server isn't running at the moment, etc.
