### ISSUE TITLE
Bazel build doesn't build libgpr

### ISSUE THREAD

**Issue by rlerdorf** [grpc/grpc#25518]
gRPC 1.35.0/Debian bullseye/sid/gcc (Debian 10.2.1-6) 10.2.1 20210110

`bazel build :all`

I was expecting this to build _libgpr.a_ and _libgpr.so_ since this library is built if you use the cmake build chain and upstream things depend on libgpr.
Instead this builds _libgpr_base.a_ and _libgpr_base.so_ with the same symbols, but this means that things like the gRPC PHP extension which explicitly looks for _gpr_now()_ in _libgpr_ will not build without modification against a bazel-built gRPC - https://github.com/grpc/grpc/blob/master/src/php/ext/grpc/config.m4#L63

`bazel query :all`

does include _//:gpr_ and https://github.com/grpc/grpc/blob/master/BUILD#L289-L297 seems like it was intended to produce a _libgpr_, but without sources and just a dependency on _libgpr_base_ the way it is written, that is not going to work.

Perhaps this was never intended to work and bazel-built gRPC is only intended for other bazel-based projects? If so, it would be good to make this clear in the build docs.

**Comment by jtattermusch** [comment]
I think the fact that bazel build is mostly intended for bazel-based is kind of clear. 
Besides bazel, we do support cmake build system (https://github.com/grpc/grpc/tree/master/src/cpp#cmake) and in fact the documentation says "cmake is your best option if you cannot use bazel". With cmake, you can build libgpr, libgrpc and other "public" targets quite easily, so I don't see the need for our bazel build to explicitly support scenarios like "I build grpc with bazel and then use it from other build systems" - which is something that might work but it's not a use that we actively support.

As a workaround (if you really need to use bazel in the way you describe), I believe it would be quite simple to patch the bazel BUILD file to force producing a libgpr library (there are various ways).

Since you're mentioning PHP, please note that PHP extension is not build with bazel - we use a generated Makefile since the PHP extension build system is `make` based:
https://github.com/grpc/grpc/tree/master/src/php#build-from-source

**Comment by jtattermusch** [comment]
I looked at the sources and the difference between gpr and gpr_base is nonexistent and on github we would probably just get rid of gpr_base and just have a gpr library (this would be quite easy to change). The issue is that there are many references to gpr_base in the internal codebase and this is something that would need to be updated first.

**Comment by rlerdorf** [comment]
Ok, no problem. I'll switch to cmake. But, I don't really agree that the build docs make it clear that bazel is only intended for other bazel-based projects. At https://github.com/grpc/grpc/blob/master/BUILDING.md#building-with-bazel-recommended it says:
 `"Bazel is the primary build system for gRPC C++ and if you're comfortable with using bazel, we can certainly recommend it. Using bazel will give you the best developer experience as well as faster and cleaner builds."`
