### ISSUE TITLE
Support loading system root certificates for Win32/OSX

### ISSUE THREAD

**Issue by ikstewa** [grpc/grpc#25533]
### Is your feature request related to a problem? Please describe.
When connecting to a TLS enabled GRPC endpoint the system root certificates are loaded on Linux/Android. When running on Win32/OSX the cert needs to be provided.

Related issue: https://github.com/grpc/grpc/issues/25167

### Describe the solution you'd like
Similar to the grpc impl for java/c# the client should load the trusted certs for operating systems beyond Linux/Android.

### Describe alternatives you've considered
The alternative is for each application to load the system certs and manually specify when creating the channel.

**Comment by ikstewa** [comment]
Please don't close out! It would be really nice to have feature parity for Mac/Win/Linux.

**Comment by RayKoopa** [comment]
I think this should be reopened because:

- The [example provided on the website](https://grpc.io/docs/guides/auth/#with-server-authentication-ssltls-2) doesn't work as provided and only has a rather easy-to-miss "Note" [at another place further up](https://grpc.io/docs/guides/auth/#using-client-side-ssltls) that it indeed won't work on non-POSIX systems.
- There is no example code found for Windows, which would be very helpful. The only hint I got is from a [comment](https://github.com/grpc/grpc/issues/25167#issuecomment-769605799) made on issue https://github.com/grpc/grpc/issues/25167. IMHO that issue should not be closed either, as the problem mentioned in the title is _not_ solved ("_Default_ SSL credentials don't work on Win32/OsX").
- Other implementations like grpc-dotnet don't have this issue with their default `SslCredentials` instances, which at least got me [quite confused](https://stackoverflow.com/questions/71580681/ssl-grpc-client-works-fine-in-c-but-fails-with-unavailable-empty-update-in-c). Once I figured out the WinAPI to manually set up the credentials I'll probably post it as an answer there.

(I originally mentioned running into this trouble at https://github.com/grpc/grpc/issues/25829 but noticed that issue was reported on Linux specifically, while I'm attempting to do this on Windows 10, so I'm not sure if that issue is related.)

**Comment by ikstewa** [comment]
It looks like I don't have the ability to re-open this issue.

While that example code solves windows, we still have a similar issue on OSX as well.

**Comment by RayKoopa** [comment]
Isn't macOS a POSIX OS? The warning in the authentication guide is slightly inaccurate then if it is not working with default SslCredentials.

**Comment by ZhenLian** [comment]
The MacOS support is added in https://github.com/grpc/grpc/pull/29957. Once gRPC has its new release, it should include these changes. Credits to @tdbhacks for bringing that to gRPC!

**Comment by RayKoopa** [comment]
@ZhenLian Great news. Shouldn't this issue be reopened until Windows support is added aswell?

**Comment by tdbhacks** [comment]
@RayKoopa just created #34276 to eventually get your code merged!

**Comment by kkuehl** [comment]
Just adding a comment to say that the provided code sample allowed me to get gRPC / TLS working with opentelemetry-cpp.

**Comment by alexDrinkwater** [comment]
In python grpc I was able to work around this issue of grpc not reading from the windows certificate store using this:

    credentials = grpc.ssl_channel_credentials()
    # On Windows, the default root certificates are not
    # loaded from the system
    # This makes self signed certificates fail handshake
    # even if the certificate is in the windows trusted store
    if sys.platform == "win32":
        certs = ssl.create_default_context().get_ca_certs(True)
        cert_string = ""
        for cert in certs:
            cert_string += ssl.DER_cert_to_PEM_cert(cert)
        credentials = grpc.ssl_channel_credentials(root_certificates=cert_string.encode('utf-8'))
    
    channel = grpc.secure_channel(conn_address, credentials, options=channel_options)

**Comment by matthewstevenson88** [comment]
This was fixed in #34874.

**Comment by coryan** [comment]
#34874 seems to fix the problem for Windows only, this bug is for Win32 and macOS too.  Did I get that wrong?  If not, maybe you should reopen this bug.
