### ISSUE TITLE
[C++] Please consider adding version macros

### ISSUE THREAD

**Issue by pitrou** [grpc/grpc#25556]
### Is your feature request related to a problem? Please describe.

gRPC-C++ currently doesn't seem to expose macros for the version number being compiled against.
gRPC-C++ also seems to remove or modify APIs without any deprecation warning.
This makes life frustrating when third-party code uses such a removed or modified API.
See example at Apache Arrow:
https://github.com/apache/arrow/pull/9569/files#diff-2a4796eff3f25e1b0fd6a0db28bdea1efbc3ec69457705b1069cf70ad5355624R104-R136

### Describe the solution you'd like
Instead of having to write cumbersome configure-time tests for the available gRPC APIs, one should be able to write e.g.:
```c++
#if GRPC_VERSION_MAJOR == 1 && GRPC_VERSION_MINOR >= 36
// use some APIs...
#elif GRPC_VERSION_MAJOR == 1 && GRPC_VERSION_MINOR >= 34
// use some other APIs...
#elif GRPC_VERSION_MAJOR == 1 && GRPC_VERSION_MINOR >= ...
// ...
#else
// ... fallback code if version number macros have not been introduced yet
#endif
```

### Describe alternatives you've considered
See Apache Arrow PR above. For now we have to hand-write feature tests for each API that gRPC decides to break.

**Comment by pitrou** [comment]
(to be fair, the APIs i'm talking about are experimental. Still, it would be nice to have version macros)

**Comment by pitrou** [comment]
Just a comment to avoid autoclose.

**Comment by pitrou** [comment]
Just a comment to avoid autoclose, since this isn't fixed.

**Comment by emkornfield** [comment]
Seeing if I can follow-up internally.

**Comment by emkornfield** [comment]
@ctiller @nicolasnoble any thoughts on this?

**Comment by nicolasnoble** [comment]
@markdroth / @veblush do we want this? And if yes, we'd need a proper policy for those numbers.

**Comment by markdroth** [comment]
I don't have a strong opinion on this.  I'm not necessarily sure how generally useful this would be, since the only APIs where we make breaking changes are experimental APIs, and ideally most users of those APIs will just change their code as they upgrade gRPC.  But on the other hand, I can imagine there being cases where it's useful for application code to be able to build and work with multiple versions of gRPC, in which case something like this would be useful.  If it can be done in a useful way without imposing too much maintenance overhead, I have no objection.

I'll let @veblush make the call on this.

**Comment by veblush** [comment]
New macros are added by https://github.com/grpc/grpc/pull/31033 and the next release will have them.

**Comment by pitrou** [comment]
Thanks a lot for this @veblush !
