### ISSUE TITLE
Offline installer needed due to GitHub rate limiting issues

### ISSUE THREAD

**Issue by jgallucci32** [grpc/grpc#25579]
### Is your feature request related to a problem? Please describe.
The rate limiting on GitHub requests has been causing problems lately trying to download and install gRPC using the methods available in the documentation. All of the native packages (Ubuntu, Debian) are either out of date or not available. Running a `git clone` or `go get` can now take hours to get the gRPC code due to the rate limiting issues on GitHub. This is mostly experience in large corporate environments which are behind a security stack with only a few public IPs available which is why the limit is seen.

### Describe the solution you'd like
Given the growing adoption of gRPC it would be great if there was an offline installer, or at least a full bundle of gRPC with all of the submodules available as a single compressed tarball for download. Having a single, compressed file will be much quicker to download than having to recurse a bunch of submodules with the rate limiting on GitHub.

### Describe alternatives you've considered
Right now we just have to sit and wait for the `git clone` to complete, but everytime we have a new release or we want to provide instructions to developers to build the extra effort can slow productivity.

**Comment by jtattermusch** [comment]
I don't think it's standard for opensource projects to provide full bundle archive that includes all the dependencies. We do provide bundle with gRPC's code (that's generated automatically for every release).
We actually do provide packages for most languages that do have a standard package-manager solution (e.g. C#, python, Java, ruby, ..) and for those you don't need to touch github at all.

For C++ the problem only exists when using cmake - when using bazel, mirrors for archives with dependencies will be used.
But even for C++ when building with cmake, our build is actually designed in a way where you should be able to build just from the source archive without submodules (or without most of them) by pre-installing the dependencies (which is actually the right way of building libraries in the C++ world). (see instructions in https://github.com/grpc/grpc/tree/master/src/cpp#cmake and our installation examples).

Alternatively, since you're mentioning you're in a big corporation, I think it's quite common for corporations to setup their own git mirrors for projects that they actively use for their development. Alternatively, creating a "full bundle" also seems pretty feasible on your end.

I'm going to close this as there seems to be workarounds available and it also seems that it's more of a problem with youre company's network architecture, rather than a problem related to gRPC itself.
