### ISSUE TITLE
Unreasonably large storage space required for published solution with grpc.core reference

### ISSUE THREAD

**Issue by pavlexander** [grpc/grpc#25598]
(originally wrongly created a ticket in https://github.com/grpc/grpc-dotnet/issues/1217)

### What version of gRPC and what language are you using?
`C#` in `.Net 5`. I am using `Google.Cloud.TextToSpeech.V1` v`2.1.0`, which depends on `Grpc.Core 2.31 < 3`

### What operating system (Linux, Windows,...) and version?
  **- OS:** `Windows Pro Version 10.0.19042 Build 19042` **(building on `Windows` for `Linux`)**

### What runtime / compiler are you using (e.g. .NET Core SDK version `dotnet --info`)

  **- .NET version:**
 ```
 .NET SDK (reflecting any global.json):
 Version:   5.0.103
 Commit:    72dec52dbd
Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.19042
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\5.0.103\
Host (useful for support):
  Version: 5.0.3
  Commit:  c636bbdc8a
.NET SDKs installed:
  5.0.103 [C:\Program Files\dotnet\sdk]
.NET runtimes installed:
  Microsoft.WindowsDesktop.App 5.0.3 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
```

### What did you do?
1. Create a new project in `VisualStudio` in `.Net`. In my case I am using `Blazor WASM` with `Asp.net core hosted` option
2. Add a `nuget` package reference to `Google.Cloud.TextToSpeech.V1` and reference any part of the library in project. I used the `var _client = new TextToSpeechClientBuilder { ChannelCredentials = googleCredential.ToChannelCredentials() }.Build();`
2. open csproj folder location (in my case - Server project)
3. run `dotnet publish MySolution.Server.csproj --configuration Release -r linux-x64 --mydestinationfolder`
4. check the folder size of `mydestinationfolder`

### What did you expect to see?
**Expected:** reasonable size

### What did you see instead?
**Actual: 255mb** (**143mb** of which belong to `grpc` binaries)

![image](https://user-images.githubusercontent.com/20644772/109714280-e1ed1580-7baa-11eb-91be-0a01d837c003.png)

without `-r` flag

![image](https://user-images.githubusercontent.com/20644772/109715714-a9e6d200-7bac-11eb-8bde-6a31c9fb1209.png)

looks like `grpc` assembly size on `windows` is "normal" - only 16 megs.. So the abnormality only affects `linux` distributions.

![image](https://user-images.githubusercontent.com/20644772/109716956-20380400-7bae-11eb-960a-d89f6fe26275.png)

### Anything else we should know about your project / environment?

Once you have referenced the `Grpc.core`  package - the solution size becomes awfully big for `linux` users. (more than double the size of all of the rest of the solution). If you think that every bit of data of `grpc` binaries deserve all the storage space, fine, then I would like to suggest looking into the ways of slitting the `nuget` package into sub-packages, so you could also split the binaries proportionally.

Some people might me using 1% of the `Grpc.core` package, but still have to download all 140 megs of data that comes along with it.

Alternative option would be applying some compression/minimization methods (unless not applied already?).  Is `Linux` in that much different that binaries weight `140mb` as opposed to `16mb` on `win`?

**Comment by jtattermusch** [comment]
Grpc.Core being quite big in size is a known problem, and unfortunately since we have the grpc_csharp_ext native dependency, our options are pretty limited here.

We actually made some improvements recently (e.g. https://github.com/grpc/grpc/pull/24380 or https://github.com/grpc/grpc/pull/24378) but we need to accept that Grpc.Core will always be of non-trivial size.
In the future we would like to provide an option to use client libraries through grpc-dotnet (without taking a dependency on Grpc.Core), which would solve this problem completely (grpc-dotnet is pure C# and its size is tiny).

Btw, the difference between linux and windows is caused by the fact that for windows we actually provide the debug symbols in a separate package Grpc.Core.NativeDebug  and we can do that since on windows the debug symbols come in a separate .pdb file.  On linux the debug symbols are included in the grpc_csharp_ext.so library (which does take some space but makes debugging much easier since you can still get access to the debug symbols in the native layer).

**Comment by pavlexander** [comment]
Since the situation with the core package is known then I guess there is no reason keeping this thread alive.. I think the topic is more important now than never, with `blazor` in place. We could build applications now, using C#! Reuse the C# code of existing libraries to build web applications.

`Blazor Desktop` is already available in .Net 6 Preview. Imagine publishing your applications that would weight 30 megs under normal circumstances but ending up 200+ megs because of Grpc core library :)

hm, on a second thought it really depends if blazor desktop is ever to be available on linux or not.. if not then forget about what I just said. The point is - 140mb is still too much of a dependency. Glad to hear that optimization process is taken care of.
