### ISSUE TITLE
argumentnullexception

### ISSUE THREAD

**Issue by HppZ** [grpc/grpc#25773]
### What version of gRPC and what language are you using?
grpc 2.36.1 csharp

### What operating system (Linux, Windows,...) and version?
Windows 19042.867

### What runtime / compiler are you using (e.g. python version or version of gcc)
visual studio 16.9.2

### What did you do?
run UWP in release mode. repo: https://github.com/HppZ/grpc-bug

### What did you expect to see?
no argumentnullexception.

### What did you see instead?
argumentnullexception occured.

Make sure you include information that can help us debug (full error message, exception listing, stack trace, logs).

See [TROUBLESHOOTING.md](https://github.com/grpc/grpc/blob/master/TROUBLESHOOTING.md) for how to diagnose problems better.

### Anything else we should know about your project / environment?

![image](https://user-images.githubusercontent.com/12285582/111904602-b6ab6700-8a82-11eb-846f-9a5b84e7e600.png)
related issue:
https://github.com/grpc/grpc/issues/18188

**Comment by tonydnewell** [comment]
@HppZ This appears to be grpc-dotnet from your example code, not the grpc core C# library
https://github.com/HppZ/grpc-bug/blob/cb87a0282c9a5aae748af3c67b49d9b5f516f6aa/TestGrpc/TestGrpc.csproj#L9
```
    <PackageReference Include="Grpc.Net.Client" Version="2.36.0" />
    <PackageReference Include="Grpc.Net.Client.Web" Version="2.36.0" />
```
If so you need to ask in https://github.com/grpc/grpc-dotnet/issues

Or do you somehow have a mixture of grpc-dotnet and grpc core? Otherwise I'm not sure why native methods are trying to be loaded if you are just using grpc-dotnet.

**Comment by jtattermusch** [comment]
> @HppZ This appears to be grpc-dotnet from your example code, not the grpc core C# library https://github.com/HppZ/grpc-bug/blob/cb87a0282c9a5aae748af3c67b49d9b5f516f6aa/TestGrpc/TestGrpc.csproj#L9
> 
> ```
>     <PackageReference Include="Grpc.Net.Client" Version="2.36.0" />
>     <PackageReference Include="Grpc.Net.Client.Web" Version="2.36.0" />
> ```
> 
> If so you need to ask in https://github.com/grpc/grpc-dotnet/issues
> 
> Or do you somehow have a mixture of grpc-dotnet and grpc core? Otherwise I'm not sure why native methods are trying to be loaded if you are just using grpc-dotnet.

at the same time, the LoadNativeMethodsUsingExplicitLoad methods from the screenshot it clearly from Grpc.Core, but I also didn't find any references of Grpc.Core in the example code provided, so the info provided is quite confusing.

At the same time, the user seems to be using UWP, which is no longer supported for Grpc.Core (since Grpc.Core is now in maintenance mode). So I think on the grounds of using an unsupported platform, we can close this issue.
