### ISSUE TITLE
grpc vsock support

### ISSUE THREAD

**Issue by nimajafroodi** [grpc/grpc#25801]
Is there any support for vsock? I couldn't find any documentation and would appreciate any insight. If it's not supported then is there any plan to support it? What are the workarounds?

**Comment by nimajafroodi** [comment]
Any updates on this issue?

**Comment by nicolasnoble** [comment]
We don't have any plan for it at the moment, no.

**Comment by Allen-Webb** [comment]
I would like to revisit this PR since we rely on a VSOCK patch for Chrome OS and it would be preferable to have it upstream. I am in the process of setting up a windows development environment so I can make sure the patches do not break GRPC on windows.

Additionally, it might be good to discuss the test environment (maybe through chat or email) to figure out an acceptable solution to the testing concerns raised before.

I can open another issue if necessary. This is pretty much the same as issue 11734 too.

**Comment by hterik** [comment]
Android has a similar requirement and patch, seem like it is based on the Chrome OS patch. 
https://android.googlesource.com/platform/external/grpc-grpc/+/a0d43cf1a94bc5443ee8ee2499490f6af4da6272
