### ISSUE TITLE
Rename grpc_channel_create

### ISSUE THREAD

**Issue by ctiller** [grpc/grpc#2585]
To grpc_channel_create_insecure

**Comment by nathanielmanistaatgoogle** [comment]
After the discussion in today's meeting, should grpc_channel_create_insecure even exist? What would be the difference between grpc_channel_create_insecure and grpc_secure_channel_create passed the credentials object returned by grpc_fake_transport_security_credentials_create?

**Comment by ctiller** [comment]
It definitely needs to. 

An explanation in four parts:
- there are folks that want grpc insecurely but don't want to link in OpenSSL - this probably isn't a use case for many of our wrapped languages, which have huge environments anyway - but will be useful for folks wanting to run in very constrained environments
- the fake_ credentials should probably be dropped from public API's, as they're really just for testing (@jboeuf - if you don't disagree I'll file bugs)
- knowing we need none of the security infrastructure allows optimizations and simplifications that aren't possible otherwise - and we have some users that need this too
- there are situations where the raw wire protocol provides perfectly adequate security (e.g. via a unix domain socket), and having such a mechanism seems important

**Comment by jboeuf** [comment]
I agree with Craig.

Fake transport security adds a dummy handshake and some framing to (think additional mallocs / copies). It was really useful to put it in the public API at some point because we could test the "secure path" without having to go through SSL (which helped us debug some node issues for example). However it looks like things have now settled down and I'm OK removing it from the public API.
