### ISSUE TITLE
In C++, when building using cmake, got fatal error: absl/synchronization/mutex.h: No such file or directory

### ISSUE THREAD

**Issue by Puneethgr** [grpc/grpc#25949]
### What version of gRPC and what language are you using?
grpc v1.37.0
C++
cmake version: 3.20.1

### What operating system and version?
Inside Docker container (using GCC image pulled from https://hub.docker.com/_/gcc)
Linux version 5.8.8-1.el7.elrepo.x86_64 (mockbuild@Build64R7) (gcc (GCC) 9.3.1 20200408 (Red Hat 9.3.1-2), GNU ld version 2.32-16.el7

### What runtime / compiler are you using (e.g. python version or version of gcc)
GCC version: gcc (GCC) 10.3.0

**Issue description**
In C++, When building using cmake, got fatal error: absl/synchronization/mutex.h: No such file or directory

**Steps to reproduce the issue**
Follow the steps as shown in https://grpc.io/docs/languages/cpp/quickstart/

In the below step:-
![image](https://user-images.githubusercontent.com/36910708/114293156-85d2b680-9ab1-11eb-8424-292fb082bfc4.png)

# Error:

![image](https://user-images.githubusercontent.com/36910708/114293163-9d11a400-9ab1-11eb-9225-8c7274264225.png)

# Solution:
I copied the absl folder from ```grpc/third_party/abseil-cpp/absl``` and pasted it into ```/usr/local/include/``` as shown below:

``` cp -r /grpc/third_party/abseil-cpp/absl /usr/local/include/ ```

Later, it worked fine:
![image](https://user-images.githubusercontent.com/36910708/114293285-7dc74680-9ab2-11eb-8aad-c75a044af560.png)

### Please fix this bug (So that we need not manually copy-paste the absl folder)

**Comment by ahesford** [comment]
I also saw this when attempting to update the `grpc` package for Void Linux; we have a `sysdig` dependant that fails to build against the new version because the abseil headers are a hard dependency of `grpcpp/impl/codegen/sync.h` but are not installed alongside the `grpc` headers.

**Comment by veblush** [comment]
@ahedberg It looks like gRPC repo doesn't have submodules that it requires to build. Can you try to run `git submodule update` on grpc directory? If this doesn't solve your answer, can you share exact commands you run when building it?

**Comment by cjcox17** [comment]
I'm also having this issue. I just updated a forked repository to the latest commit, and this popped up.

I can reproduce on a blank install of Debian by cloning this repo, then running

`cd grpc
git submodule update --init
mkdir -p cmake/build
cd cmake/build
cmake ../.. cmake ../.. -DgRPC_INSTALL=ON                \
              -DCMAKE_BUILD_TYPE=Release       \
              -DgRPC_ABSL_PROVIDER=package     \
              -DgRPC_CARES_PROVIDER=package    \
              -DgRPC_PROTOBUF_PROVIDER=package \
              -DgRPC_RE2_PROVIDER=package      \
              -DgRPC_SSL_PROVIDER=package      \
              -DgRPC_ZLIB_PROVIDER=package
make
make install`

**Comment by ahesford** [comment]
Yes, this is not an issue with the gRPC build process, but the fact that a public gRPC header depends on an abseil header that is not installed. The Void build system (`xbps-src`) does not handle git submodules in this template, but instead downloads a tarball of the specific abseil commit referenced by the gRPC release and replaces the `third_party/abseil-cpp` subdirectory with the contents of the tarball. For other third-party libraries, we prefer the system version. (Void does not attempt to provide a system package for abseil, mostly because it is only used by gRPC and would need its version pegged to whatever gRPC requires.)

The Void build process is described in the template at https://github.com/void-linux/void-packages/blob/master/srcpkgs/grpc/template. The only non-standard change to the build process is to [disable `BUILD_SHARED_LIBS`](https://github.com/void-linux/void-packages/blob/master/srcpkgs/grpc/template#L46-L47) because we prefer static linking for this vendored library.

**Comment by veblush** [comment]
@ahedberg Oh I see. As a reference, gRPC uses the [LTS version](https://abseil.io/about/releases) of Abseil so it might be reasonable to install it because it's carefully written not to interfere with other versions of Abseil.

@Puneethgr Can you share exact commands you run when building it for the reproduction?

**Comment by ahedberg** [comment]
@veblush You might want to double-check who you're tagging; I (ahedberg) and ahesford are not the same person, and I have no context for this issue. Thanks!

**Comment by veblush** [comment]
@ahedberg Oops my bad. Sorry about that.

**Comment by Puneethgr** [comment]
@veblush 

I used GCC docker image as base image and installed GRPC as per the documentation (https://grpc.io/docs/languages/cpp/quickstart/)
```
docker pull gcc
docker run -itd --name gcccpp gcc   
docker exec -it gcccpp /bin/bash

export MY_INSTALL_DIR=$HOME/.local
mkdir -p $MY_INSTALL_DIR
export PATH="$PATH:$MY_INSTALL_DIR/bin"

wget -q -O cmake-linux.sh https://github.com/Kitware/CMake/releases/download/v3.19.6/cmake-3.19.6-Linux-x86_64.sh
sh cmake-linux.sh -- --skip-license --prefix=$MY_INSTALL_DIR
rm cmake-linux.sh

apt-get update
apt install -y build-essential autoconf libtool pkg-config

git clone --recurse-submodules -b v1.37.0 https://github.com/grpc/grpc

cd grpc
mkdir -p cmake/build
pushd cmake/build
cmake -DgRPC_INSTALL=ON \
      -DgRPC_BUILD_TESTS=OFF \
      -DCMAKE_INSTALL_PREFIX=$MY_INSTALL_DIR \
      ../..
make
make install
popd


cd examples/cpp/helloworld

mkdir -p cmake/build
pushd cmake/build
cmake -DCMAKE_PREFIX_PATH=$MY_INSTALL_DIR ../..
make
```

**Comment by cjcox17** [comment]
So, while I have the same issue, after I copy and pasted the absl folder, it seems that linking against grpc in another makefile failed because absl_base cannot be found.

The .pc files do exist, but they're all prefixed with absl_ so absl_base is actually absl_absl_base.

<img width="662" alt="Screen Shot 2021-04-20 at 00 50 35" src="https://user-images.githubusercontent.com/1725282/115308408-525bf000-a173-11eb-8afb-9b1a8d206768.png">

**Comment by veblush** [comment]
@Puneethgr Thanks for the commands to reproduce it. I saw the same error and it turns out that the doc needs to update. In the meantime, you can fix it by installing abseil in advance.

Before building example on grpc directory,
```
mkdir -p "third_party/abseil-cpp/cmake/build"
pushd "third_party/abseil-cpp/cmake/build"
cmake -DCMAKE_INSTALL_PREFIX=$MY_INSTALL_DIR -DCMAKE_POSITION_INDEPENDENT_CODE=TRUE ../..
make -j4 install
popd
```

**Comment by ahesford** [comment]
Does this mean that the hard dependency on abseil headers in gRPC is not going away?

**Comment by veblush** [comment]
@ahesfold Yes it will keep the abseil dependency. gRPC C++ will use more Abseil features in future.

**Comment by justinpchang** [comment]
Hi @veblush when I try to install abseil using the commands you put here, I got the following long error.
[error.log](https://github.com/grpc/grpc/files/6360312/error.log) do you know what the problem could be here?

**Comment by JonsKou** [comment]
this happen again on v1.39 ref https://grpc.io/docs/languages/cpp/quickstart/#install-grpc

**Comment by warent** [comment]
I'm getting this error too. Maybe we can consider re-opening this issue, it took me ages to find it 😩

**Comment by warent** [comment]
Looks like it might be related to this https://github.com/abseil/abseil-cpp/issues/703 ?
