### ISSUE TITLE
System.DllNotFoundException: 'grpc_csharp_ext assembly

### ISSUE THREAD

**Issue by Rishantkr** [grpc/grpc#25973]
System.DllNotFoundException: 'grpc_csharp_ext assembly:<unknown assembly> type:<unknown type> member:(null)'

Can someone help me why i am getting this error ?
Xamarin Forms project
Trying to access google firebase db.

**Comment by Aaron-Gemperline** [comment]
I am also running into this issue in xamarin forms  Message | "grpc_csharp_ext assembly:<unknown assembly> type:<unknown type> member:(null)" | string

I am running a C# client trying to connect to a .aspnetcore 2.37 server. This issue is only showing up when the client is in my xamarin project. It runs a C# client in .netcore 3.1 so I don't think its a configuration of the client or anything like that.

**Comment by Rishantkr** [comment]
I got a small fixed for this error. I have switched from latest version to previous version of nuget package using for this.
