### ISSUE TITLE
some questions about build libabsl_dynamic_annotations.so

### ISSUE THREAD

**Issue by SamFisher940425** [grpc/grpc#25970]
I noticed that the libabsl_dynamic_annotations.so will not be compiled in versions after 1.34.0. What is the reason for this? Which functions will be affected?

thanks for helping.

**Comment by veblush** [comment]
Since upgrading Abseil to the latest LTS ([20210324.0](https://github.com/abseil/abseil-cpp/releases/tag/20210324.0)), it started not to depend on `libabsl_dynamic_annotations.so` because they removed it. ([commit](https://github.com/rongjiecomputer/abseil-cpp/commit/c90d54f9ee32e011ef54ca87bddb726fda1d5bf3))
