### ISSUE TITLE
TlsCredentialsOptions's "watch" APIs must be called even when no watching is necessary.

### ISSUE THREAD

**Issue by matthewstevenson88** [grpc/grpc#26133]
When configuring a `TlsChannelCredentialsOptions` object, the following configuration results in a failed handshake when it should not:
```
grpc::experimental::TlsChannelCredentialsOptions options;
options.set_certificate_provider(std::make_shared<grpc::experimental::StaticDataCertificateProvider>(...));
```
and the fix is to call both of `options.watch_identity_key_cert_pairs();` or `options.watch_root_certs();`, even though the data is static and no refreshing has been requested or is required. 

Similarly, when configuring a `TlsServerCredentialsOptions` object, the following configuration results in a failed assertion when it should not:
```
  grpc::experimental::TlsServerCredentialsOptions options(std::make_shared<grpc::experimental::StaticDataCertificateProvider>(...));
options.set_cert_request_type(GRPC_SSL_REQUEST_AND_REQUIRE_CLIENT_CERTIFICATE_AND_VERIFY);
```
and the fix is to call both of `options.watch_identity_key_cert_pairs();` or `options.watch_root_certs();`, even though the data is static and no refreshing has been requested or is required. The failed assertion is [here](https://github.com/grpc/grpc/blob/b1955c89bb210b667b4c977c39ea54eac7fafa90/src/core/lib/security/credentials/tls/grpc_tls_certificate_distributor.cc#L184).

This was observed on an internal CL written by @jdtw and reviewed by @ZhenLian and myself. cc: @jiangtaoli2016

**Comment by ZhenLian** [comment]
As I replied to the internal thread, `watch_root_certs()` and `watch_identity_key_cert_pairs` are not specific to  `FileWatcherCertificateProvider`. They are applied to all the provider implementations. Even if a `StaticDataCertificateProvider` is used, in mTLS, users are required to call both `watch_root_certs()` and `watch_identity_key_cert_pairs. Otherwise they will see the error you just described.

`watch_XXX()` means we are watching the *contents* of XXX stored in the provider, instead of the *updates* of XXX. `StaticDataCertificateProvider` is also a provider, so we will need to watch the contents if certain credentials will be used.

In other words, the only reason for not setting `watch_root_certs()` or `watch_identity_key_cert_pairs` is that we are not going to use them. For example, in single TLS, the server doesn't need to watch trust cert, and the client doesn't need to watch identity pairs. Except from these two cases, in a normal scenario, they are both needed on both sides.

Does that answer your question? I did notice that [the comments of these two functions](https://github.com/grpc/grpc/blob/fd3bd70939fb4239639fbd26143ec416366e4157/include/grpcpp/security/tls_credentials_options.h#L163-L172) are not precise(I shouldn't say "updates" but just say "contents", but as you can see, these two fields are not specific to `FileWatcherCertificateProvider`, as I didn't mention it). I will change it accordingly. Would that solve your problem?

**Comment by matthewstevenson88** [comment]
Thanks for clarifying Zhen! Sorry if I misunderstood your reply in our conversation. :)

At a minimum, could you add a comment to the effect of "if you want to do mTLS, then you MUST call this API"? This was not clear to me when reading the documentation.

I'm not sure what the best fix is, but I'll just explain my 2 confusions as a user. Feel free to incorporate this feedback or not. :)

1. These 2 APIs are telling us what to do with root certs and keypairs, which are owned by the certificate provider, so it's a little confusing that these APIs are owned by `TlsCredentialsOptions` instead.

2. The use of the word "watch" seems to be a bit of a misdirection, since we're not watching anything (in the sense of waiting for a notification that an update occured) but rather we're indicating how to use credentials (e.g. in the case of `watch_root_certs`, we're either using the default roots or the roots provided in the cert provider).
