### ISSUE TITLE
Insecure server construction should be explicit in python

### ISSUE THREAD

**Issue by a11r** [grpc/grpc#2616]
Constructing a server that does NOT use SSL should follow an API where there is an explicit insecure credential object passed during server construction. This ensures that server authors learn the API for building a secure server, and that they never build an insecure server implicitly.

**Comment by nathanielmanistaatgoogle** [comment]
This seems to completely violate the spirit of the conversation that I had with @ctiller in #2585. That was client-side and this is server-side, but shouldn't the same philosophy apply?

Or am I entirely missing something important?

**Comment by ctiller** [comment]
I think it entirely agrees with that conversation: the intent is to make
sure that doing something that's insecure means typing out something that
clearly says that this is insecure.

Think:

server.AddPort(ThisIsInsecure(), "localhost:8080")

versus

server.AddPort("localhost:8080")

**Comment by ctiller** [comment]
(I don't think anyone would care if you had
server.AddInsecurePort("localhost:8080") if that fit better with something
else)

**Comment by nathanielmanistaatgoogle** [comment]
@ctiller: what about "there are folks that want grpc insecurely but don't want to link in OpenSSL - this probably isn't a use case for many of our wrapped languages, which have huge environments anyway - but will be useful for folks wanting to run in very constrained environments" - is that not applicable on the server-side?

What I'm getting at is that the proposal on the table in this issue seems to be
(1) insecure client-side:
  (a) call grpc_insecure_channel_create passing no credentials object. "Lightweight" and doesn't require OpenSSL.
  (b) call grpc_secure_channel_create passing a fake credentials object - this is disfavored and going away.
(2) insecure server-side:
  (a) call a method that adds a port, passing an explicitly insecure credentials object.
  (b) there is no (b) which is to say that there is no way to add an explicitly insecure port while not passing any kind of (real or fake or in-between) credentials object.

Is that not asymmetric between the sides? If passing a phony credentials object is disfavored and going away on the client side, why is it explicitly being requested on the server side in this issue?

**Comment by ctiller** [comment]
So the change in #2585 is all about the C api. In C++ we end up expressing
this as passing in insecure credentials - which in C++ look like a normal
credentials object, but they're subtly different. We use deep C++ magic to
ensure that we don't link in OpenSSL (I can go through the details if
you're interested).

So... the C++ wrapping of credentials adds something that the C credentials
system doesn't have (and that's ok).

**Comment by nathanielmanistaatgoogle** [comment]
This was fixed in 9e4d0610ea5e2bb3.
