### ISSUE TITLE
C# Xamarin: Error when calling grps methods on Xamarin.ios

### ISSUE THREAD

**Issue by DanilStepa** [grpc/grpc#26195]
## Exception: ##
`"Method not found: System.Buffers.IBufferWriter'1<byte> Grpc.Core.SerializationContext.GetBufferWriter()"`

## Technologies used: ##
```
NUGET:
  -  Grpc.Core, Grpc.Core.Api and Grpc.Core.Xamarin - 2.37.1 and earlier
  -  Xamarin.Forms - 4.8.0.1687 and later
 IOS 14.4.2 
 MACOS BIG SUR 11.2
 VISUAL STUDIOS FOR MAC Latest Release
```

## Description ##
The error presumably appeared after updating macos to big sur version
Previously worked fine.
Before the Grpc.Core.Xamarin library came along, the solution was [Fixing gRPC Xamarin iOS linking errors](https://techblog.livongo.com/fixing-grpc-xamarin-ios-linking-errors/)
After the release of Grpc.Core.Xamarin built without additional solutions

### When building from Windows, I get this error: ###
```
Unknown command line argument: '/Users/{MyUserName}/Library/Caches/Xamarin/mtbs/builds/{MyProjectName}.iOS/79473c737e8c8d9b0aa02afef81762802e6976d389d702a1384c1ab21b8076c1/bin/iPhone/Debug/device-builds/ipad7.5-14.4.2/{MyProjectName}.iOS.exe'	{MyProjectName}.iOS			
```
### The command that caused the error: ###
```
 /Library/Frameworks/Xamarin.iOS.framework/Versions/Current/bin/mtouch @/Users/{MyUserName}/Library/Caches/Xamarin/mtbs/builds/{MyProjectName}.iOS/79473c737e8c8d9b0aa02afef81762802e6976d389d702a1384c1ab21b8076c1/obj/iPhone/Debug/device-builds/ipad7.5-14.4.2/response-file.rsp "--gcc_flags=-LC:/Users/{MyUserName}/.nuget/packages/grpc.core.xamarin/2.37.1/build/Xamarin.iOS10/../../native/ios/universal -lgrpc_csharp_ext -force_load C:/Users/{MyUserName}/.nuget/packages/grpc.core.xamarin/2.37.1/build/Xamarin.iOS10/../../native/ios/universal/libgrpc_csharp_ext.a -LC:/Users/{MyUserName}/.nuget/packages/grpc.core.xamarin/2.37.1/build/Xamarin.iOS10/../../native/ios/universal -lgrpc -force_load C:/Users/{MyUserName}/.nuget/packages/grpc.core.xamarin/2.37.1/build/Xamarin.iOS10/../../native/ios/universal/libgrpc.a -ObjC -lc++ -lsqlite3 -lz -ObjC -lc++ -lsqlite3 -lz -lc++ -ObjC -ObjC -lc++ -ObjC -lc++ -ObjC -lc++ -ObjC -lc++ -ObjC -lc++ -ObjC -lc++ -ObjC -ObjC -lc++ -ObjC -lc++ -ObjC -lc++ -lz -ObjC -ObjC -lc++ -lsqlite3 -lz -ObjC -lc++ -lsqlite3 -lz -ObjC -lc++ -lsqlite3 -lz -lc++ -ObjC -ObjC -lc++ -ObjC -lc++ -ObjC -lc++ -ObjC -lc++ -ObjC -lc++ -ObjC -lc++ -ObjC -ObjC -lc++ -ObjC -lc++ -ObjC -lc++ -lz -ObjC -ObjC -lc++ -lsqlite3 -lz -LC:/Users/{MyUserName}/.nuget/packages/grpc.core.xamarin/2.37.1/build/Xamarin.iOS10/../../native/ios/universal -lgrpc_csharp_ext -force_load C:/Users/{MyUserName}/.nuget/packages/grpc.core.xamarin/2.37.1/build/Xamarin.iOS10/../../native/ios/universal/libgrpc_csharp_ext.a -LC:/Users/{MyUserName}/.nuget/packages/grpc.core.xamarin/2.37.1/build/Xamarin.iOS10/../../native/ios/universal -lgrpc -force_load C:/Users/{MyUserName}/.nuget/packages/grpc.core.xamarin/2.37.1/build/Xamarin.iOS10/../../native/ios/universal/libgrpc.a" 

```

the method described above and other methods found did not help

Everything works just fine in Xamarin.Android, thanks a lot!

Sorry for my English

- [ ]

**Comment by jtattermusch** [comment]
I'm going to close issue this since we're not going to pursuit Unity/Xamarin support in `Grpc.Core` anymore.
- The `Grpc.Core` implementation is now in maintenance mode and we're only going to focus on critical and security fixes.
- Supporting Unity/Xamarin simply presents too much maintenance overhead and it's also difficult to test with the test infrastructure available to us
- The Unity/Xamarin support has always been classified as "experimental", so discontinuing the support shouldn't be too surprising.

See [the recent update on gRPC C#](https://groups.google.com/g/grpc-io/c/OTj5mb1qzb0/m/-M81UQipAQAJ) for more details.

Note that in practice, running Grpc.Core on Unity/Xamarin might still be possible (there is nothing in principle that would prevent it from working), but it will be completely at your own risk and it's simply not one of the use cases the grpc team will help you with as `Grpc.Core` on Unity/Xamarin is now considered as "not supported" by us (but you might still be able to get help from the community).
