### ISSUE TITLE
Ruby's RPC stubs leak threads

### ISSUE THREAD

**Issue by drewhoskins-stripe** [grpc/grpc#26228]
### What version of gRPC and what language are you using?
ruby, latest

### What operating system (Linux, Windows,...) and version?
MacOS or Linux

### What runtime / compiler are you using (e.g. python version or version of gcc)
ruby 2.6.3p62 (2019-04-16 revision 67580) [x86_64-darwin19]

### What did you do?
Please provide either 1) A unit test for reproducing the bug or 2) Specific steps for us to follow to reproduce the bug. If there’s not enough information to debug the problem, gRPC team may close the issue at their discretion. You’re welcome to re-open the issue once you have a reproduction.
repro:
```
#!/usr/bin/env ruby
require 'grpc'

class Service

  include GRPC::GenericService

end

puts(Thread.list)
client = Service.rpc_stub_class.new(
  "localhost:7233",
  :this_channel_is_insecure,
  timeout: 3
)
puts("Stubbed")
puts(Thread.list)
```

### What did you expect to see?
A method or technique  to free these resources.  
### What did you see instead?

```
$ ./bin/repro
#<Thread:0x00007fa5e50640b8 run>
Stubbed
#<Thread:0x00007fa5e50640b8 run>
#<Thread:0x00007fa5e5016c00 sleep>
#<Thread:0x00007fa5e5016110 sleep>
```
The threads have no callstacks so I assume they're created in another language than ruby inside the grpc library.

Make sure you include information that can help us debug (full error message, exception listing, stack trace, logs).

See [TROUBLESHOOTING.md](https://github.com/grpc/grpc/blob/master/TROUBLESHOOTING.md) for how to diagnose problems better.

**Comment by apolcyn** [comment]
The grpc-ruby library uses two ruby threads for handling certain asynchronous events.

One is started [here](https://github.com/grpc/grpc/blob/8bdbb74425d6ac13ea7823be41e9297fddd629aa/src/ruby/ext/grpc/rb_event_thread.c#L144) and the other is started [here](https://github.com/grpc/grpc/blob/8bdbb74425d6ac13ea7823be41e9297fddd629aa/src/ruby/ext/grpc/rb_channel.c#L759).

So, the two threads are not leaked, but are instead persistent background threads used by the library.

The reason you see these threads only after creating a stub is because the grpc-ruby library is initialized lazily: one-time library initializes procedures run when the first grpc-ruby object is created.
