### ISSUE TITLE
Documentation about C++ function AddMetadata() is unclear with respect to format

### ISSUE THREAD

**Issue by rainerschoe** [grpc/grpc#26454]
Hi, The AddMetadata() [Documentation](https://grpc.github.io/grpc/cpp/classgrpc_1_1_client_context.html#a816af6cf0b2999da00e32a5027e23da4) specifies a format to use.

However it is not clear how to read the format specification:

> Metadata must conform to the following format: Custom-Metadata -> Binary-Header / ASCII-Header Binary-Header -> {Header-Name "-bin" } {binary value} ASCII-Header -> Header-Name ASCII-Value Header-Name -> 1*( x30-39 / x61-7A / "_" / "-" / ".") ; 0-9 a-z _ - . ASCII-Value -> 1*( x20-x7E ) ; space and printable ASCII 

Could you update the documentation to be more specific and/or use some standard CFG/Regex language to describe the desired grammar?

It is also not clear if the format requirements are for `metadata_key` or for `metadata_value` content.

**Comment by drfloob** [comment]
Thanks for pointing this out, part of the issue is that Doxygen stripped newlines from the method's comments. In the [code comment itself](https://github.com/grpc/grpc/blob/master/include/grpcpp/impl/codegen/client_context.h#L226-L231), the formatting is the same ABNF used in RFCs (replacing `=` with `->`. [See rfc5234](https://datatracker.ietf.org/doc/html/rfc5234)). We could make the docs more readable by updating the comments to wrap the format definition in `\code{.unparsed} ... \endcode` or `\verbatim ... \endverbatim` tags. I'd gladly accept a pull request for that if you'd like to fix it.

I believe `metadata_key` needs to conform to the `Header-Name` format (`0-9a-z_-.`)
