### ISSUE TITLE
Python: Metadata iterator must iterate over Mapping keys to comply with abc.Mapping

### ISSUE THREAD

**Issue by MHDante** [grpc/grpc#26498]
This is a concern regarding the python AIO implementation of Metadata. 

https://github.com/grpc/grpc/blob/master/src/python/grpcio/grpc/aio/_metadata.py

In other implementers of the `abc.Mapping` class, the implementation of `__iter__` should return an iterator over the keys.

See https://docs.python.org/3.7/library/stdtypes.html#dict

Currently, `__iter__` on `Metadata` returns an iterator on items (keys and values), which contradicts the standard for `Mapping` as mappings are generally accepted to inherit a collection of their keys.

I would suggest one of 2 options:
1) replace the `__iter__` implementation so that it returns the keys (breaking change, but the iterator is undocumented)
2) to not inherit from `abc.Mapping`. This would allow `Metadata` to retain most of its methods intact, and instead it can implement `Collection[Tuple[MetadataKey, MetadataValue]]`

**Comment by MHDante** [comment]
Upon more investigation, it seems that solution 2 would be preferred since it would allow this AIO class to easily be used alongside non-AIO metadata, since both can be cast to Collection[Tuple[str, MetadataValue]]

**Comment by lidizheng** [comment]
Related PR: https://github.com/grpc/grpc/pull/26499

This is indeed a bug in implementation. `MetadataType` should be `Tuple[Tuple[MetadataKey, MetadataValue]]`.  The expected behavior of `__iter__` should be returning key-value pairs. This is the behavior of sync API's metadata. It's better to keep asyncio API and sync API on the same page.

Solution 2 sounds good.

**Comment by BatmanAoD** [comment]
As far as I can tell, this makes the `opentelemetry-instrumentation-grpc` package completely unusable with asyncio when the initial metadata is non-empty.

This line attempts to convert an `aio.Metadata` instance into an `OrderedDict`: https://github.com/open-telemetry/opentelemetry-python-contrib/blob/main/instrumentation/opentelemetry-instrumentation-grpc/src/opentelemetry/instrumentation/grpc/_aio_client.py#L56

But the `OrderedDict` construction apparently does this by iterating over what it thinks are the "keys" of the input object, then indexing on those keys to get the values. Since `aio.Metadata.__iter__` returns key/value pairs rather than just keys, this results in a call to `__getitem__` with a `(key, value)` pair rather than an actual key, which will always result in a `KeyError`.

**Comment by BatmanAoD** [comment]
Here's a quick demonstration:

```
>>> from collections import OrderedDict
>>> from grpc.aio import Metadata
>>> m = grpc.aio.Metadata({"foo", "bar"})
>>> OrderedDict(m)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "<path>/.venv/lib/python3.9/site-packages/grpc/aio/_metadata.py", line 64, in __getitem__
    return self._metadata[key][0]
KeyError: ('bar', 'foo')
```

**Comment by XuanWang-Amos** [comment]
Looks like we agreed on the fix but didn't fix it yet, we'll put out a PR to change the inheritance soon.
