### ISSUE TITLE
Annotate copied Content native lib items with package id to enable customization (i.e. in Pack)

### ISSUE THREAD

**Issue by kzu** [grpc/grpc#26724]
The [Grpc.Core.targets](https://github.com/grpc/grpc/blob/master/src/csharp/Grpc.Core/build/net45/Grpc.Core.targets#L12-L33) declare `Content` items for the purpose of copying to output directory of the files needed at run-time. These files should not be imported when packing, however, for example. 

Since these items are imported without any metadata that distinguishes them from "regular" `Content` files added by a library/package author, it makes it difficult to exclude them without resorting to hardcoding their filenames in a target, which makes this workaround brittle if those ever change names, paths or new runtime libs are ever added. 

When NuGet packages include content items, these always contain the package Id metadata item, so that other targets can reliably detect and act on items contributed by various packages in a standard way:

![image](https://user-images.githubusercontent.com/169707/126207403-d8b0de7a-1bd3-44ff-b6bc-98d9590c5475.png)

It would be extremely valuable to also provide that metadata in those `Content` items provided by the target, so they follow the same pattern and allow project/lib/package authors to customize their inclusion as needed.

> NOTE: it's not really possible to just not import these items "when packing", since sometimes the packing happens as part of build, and there is also no way of knowing what "top-level" target was the one run either (i.e. no way to condition to `$(Target) != 'Pack'`, say)

**Comment by jkrahn3** [comment]
@kzu Can you point me to any help on how I would use this metadata to prevent the content files from making it into my package? We are making an internal package that has GRPC.Core as a dependency. For now, the only way I'm able to not have the grpc_csharp_ext.dll files get included in our package is to add `-Exclude "**/grpc_chsarp*.dll"` to our nuget pack call. I would prefer to have this in a .csproj or .nuspec file so that we only have to call nuget pack.

We're using .NET Framework, so we're not using SDK-style projects yet. We have a .nuspec file to specify some additional files to include in the package, but the pack command targets the .csproj file so that the nuspec file can use build variables like $TargetDir.

**Comment by kzu** [comment]
I'd advise dropping the (super old) .nuspec and switch to full MSBuild for packing (even directly from your .csproj). For that, there's no match to [NuGetizer](https://github.com/devlooped/nugetizer) (shameless plug)
