### ISSUE TITLE
Can't build .unitypackage outside of kokoro

### ISSUE THREAD

**Issue by MHDante** [grpc/grpc#27024]
Hi. Perhaps I'm a bit out of my depth, but I'm unable to build the .unitypackage from a cloned repo. 

I'm looking to do this so I can make archived .unitypackages for each minor and patch version.
Currently, they're only being automatically made for the main branch nightlies which can be a bit of a hit and miss
with regards to stability. My intention is to set up an NPM server (Unity uses NPM to distribute packages) so that users can reference the Unity files through the Unity package manager.

However, I'm unable to make builds for specific revisions. This is mainly due to the fact that the build_unitypackage.sh script relies on a mysterious folder named `input_artifacts` that it then copies into a folder named `nativelibs`. I should note that I've tried to run the process through both ./build_unitypackage.sh as well as 

I've tried multiple approaches to generate those files, but I'm a bit lost wrt on how to do so. It appears that the script relies on being run later in a series of build steps, which I'm not sure on how to run. Some instruction would be useful.

What I'm doing:

 - Fresh gcp vm running Debian 10 buster.
 - Install docker, git, python, python-pip, six, uuid-runtime (implicit dependencies)
 - Clone repo (--recursive)
 - Follow [c++ build instructions](https://github.com/grpc/grpc/blob/master/BUILDING.md) 
```
   apt-get install build-essential autoconf libtool pkg-config
   apt-get install cmake
   apt-get install clang libc++-dev
```
 - install [c# build pre-reqs](https://github.com/grpc/grpc/blob/master/src/csharp/README.md#build-from-source) 
   - [dotnet SDK](https://www.microsoft.com/net/core)
   - [Mono 4+](https://www.mono-project.com/) (only needed for Linux and MacOS)

 - Build the c++ project (I think this might be necessary to get the `input_artifacts` )
 ```
  mkdir -p cmake/build
  cd cmake/build
  cmake ../..
  make
```
 - Build the c# assemblies 
   - `python tools/run_tests/run_tests.py --build_only -l csharp`
 - try to build the unitypackage
   - `python tools/run_tests/task_runner.py -b unity`
   
That said, it appears that the last script is looking for the input artifacts in `/var/local/jenkins/grpc` there are also sections associated with kokoro (which i assume is google's internal jenkins system). 

log:
```
+ cd src/csharp
+ mkdir -p ../../artifacts
+ mkdir -p nativelibs
+ cp -r '/var/local/jenkins/grpc/input_artifacts/csharp_ext_*' nativelibs
cp: cannot stat '/var/local/jenkins/grpc/input_artifacts/csharp_ext_*': No such file or directory
+ true
+ ./expand_dev_version.sh
++ grep -o '<GrpcCsharpVersion>.*</GrpcCsharpVersion>' build/dependencies.props
++ sed 's/<GrpcCsharpVersion>//'
++ sed 's/<\/GrpcCsharpVersion>//'
+ UNITYPACKAGE_VERSION=2.40.0-dev202108161543
+ dotnet restore Grpc.sln
[...dotnet restore logs] 
    Restore completed in 19.63 sec for /var/local/git/grpc/src/csharp/Grpc.Microbenchmarks/Grpc.Microbenchmarks.csproj.
+ mkdir -p ../../cmake/build
+ cp nativelibs/csharp_ext_linux_x64/libgrpc_csharp_ext.so ../../cmake/build
cp: cannot stat 'nativelibs/csharp_ext_linux_x64/libgrpc_csharp_ext.so': No such file or directory
+ FAILED=true
+ '[' artifacts '!=' '' ']'
+ mkdir -p /var/local/jenkins/grpc/artifacts
+ docker cp build_and_run_docker_6bf59229-e8d7-4433-bc75-5da2b50d2652:/var/local/git/grpc/artifacts /var/local/jenkins/grpc
+ docker rm -f build_and_run_docker_6bf59229-e8d7-4433-bc75-5da2b50d2652
build_and_run_docker_6bf59229-e8d7-4433-bc75-5da2b50d2652
+ '[' true '!=' '' ']'
+ exit 1

```

Is there any way to compile this package without access to the internal ci? If so, can you give me some pointers?

I believe it would be @jtattermusch who can help point me in the right direction. 

-------

If that is too much work at the moment, perhaps this other approach can be followed:
As part of the artifact submission process for numbered releases(where nuget gets updated), could the .unitypackage be uploaded to a publicly available server (github artifacts maybe)? This would allow me to poll for changes and release the version on the package manager.

There are marked benefits here:
 - Unity bug reports can now be tied to a grpc version
 - users can install and update grpc through the unity package manager ui. (even non-technical unity users)
 - users can install and upgrade to different versions of grpc
 - unity packages can be built on top of grpc, and avoid dependency mismatch

Thank you for your time. I understand unity support is still experimental, but I hope this can bring it a bit closer to a usable standard. 🙂

**Comment by MHDante** [comment]
Hi @jtattermusch. Sorry to ping, but have you had any time to look at this?

**Comment by jtattermusch** [comment]
So in order to build the Unity package, you need to first build the grpc_csharp_ext library on multiple platforms, and then to put them in the right subdirectory (in form of `input_artifacts/csharp_ext_*`)

Basically, you'll need all the variants listed here:
https://github.com/grpc/grpc/blob/cd9730d2d28626c57431253208f23507d466c825/src/csharp/build_unitypackage.sh#L52
and
here:
https://github.com/grpc/grpc/blob/cd9730d2d28626c57431253208f23507d466c825/src/csharp/build_unitypackage.sh#L58

(e.g. `csharp_ext_linux_x64/libgrpc_csharp_ext.so`, `csharp_ext_macos_x64/libgrpc_csharp_ext.dylib`, `csharp_ext_windows_x86/grpc_csharp_ext.dll` and others).

This is the difficult step, since you need to build on 3 operating systems (linux, mac, windows) - internally the CI runs 3 different build jobs on 3 machines and combines the results in the "input_artifacts" directory. 

Once you have that, you can simply follow the steps in build_unitypackage.sh (build the assemblies using dotnet and then create the zip archive for unity).

Unfortunately, building the unity package from scratch is quite time intensive, as you can see.

I'll try to see if we can give folks access to the released version of unitypackage zip (we do build the unity package zip with each release, they are just not being deployed anywhere since there is no such things as nuget.org for unity).

Out of curiosity, can you access this link?
https://storage.googleapis.com/grpc-testing-kokoro-prod/test_result_public/prod/grpc/core/master/linux/grpc_build_packages/17923/20211117-030958/github/grpc/artifacts/grpc_unity_package.2.42.0.zip

Btw, note that Grpc.Core is now in maintenance mode and that Unity support has never been supported officially.
