### ISSUE TITLE
any io_uring supporting in plan？

### ISSUE THREAD

**Issue by luochen52** [grpc/grpc#27097]
### Additional context
Add any other context about the feature request here.

**Comment by TylerBrock** [comment]
@markdroth was this actually completed?

**Comment by markdroth** [comment]
No, I think github just says "completed" by default when you close an issue.  I closed this because it's not actionable -- I have no idea what io_uring is, and the text of the feature request didn't fill in any of the template fields with any details.

If you want to file a feature request with some actual information, we'll be happy to look at it.
