### ISSUE TITLE
Unity HoloLens2: Windows Store support ("unsupported APIs" when trying to publish to Windows Store)

### ISSUE THREAD

**Issue by pawelzgorecki** [grpc/grpc#27707]
### Is your feature request related to a problem? Please describe.
When publishing, Windows Store complains about unsupported APIs:

- ConvertThreadToFiber in kernel32.dll, used in grpc_csharp_ext.dll
- CreateFiber in kernel32.dll, used in grpc_csharp_ext.dll

### Describe the solution you'd like
Remove the use of these APIs or provide guidance on how to achieve Windows Store conformance.

### Additional context
At this moment I'm using version 1.25 of grpc, built for HL2/arm64 along the lines of this SO answer:
https://stackoverflow.com/a/63832240

**Comment by jtattermusch** [comment]
Given that the Grpc.Core implementation is based on the C-core native library, removing the use of the above mentioned APIs is probably a lot of work (since we'd have to remove the usage from C-core, where we are using those APIs for a good reason most likely).
Also, considering that Grpc.Core is in maintenance mode (see https://grpc.io/blog/grpc-csharp-future/) and Unity is only supported experimentally, I don't think we can realistically expect to fix this, so I'm going to close.

That said, it would still be interesting to find out which code in C-core leads to using the forbidden APIs and when it was introduces (by which change), for the record - free free to post more info on that topic to this thread.
