### ISSUE TITLE
grpc python code style

### ISSUE THREAD

**Issue by limohanlmh** [grpc/grpc#27723]
About grpc-python code style
I'm following the code examples in grpc/examples/python. I came across the code style as shown in image. The capital style method name made me really confused. Is there any considerations about the naming style of class methods? Thank you
<img width="617" alt="截屏2021-10-14 21 48 44" src="https://user-images.githubusercontent.com/16740997/137332774-c3794f0e-faad-4277-875d-44f987f3d1e0.png">

**Comment by LanDinh** [comment]
Since the other two issues are closed, I'm jumping in on here: This is not PEP8 compliant, meaning that any file implementing a RPC service (which should be checked by linters since it's hand-written!) will complain about it, e.g.:

```
Method name "SayHello" doesn't conform to snake_case naming style (invalid-name)
```

In other words: *this isn't restricted to the generated code*. I'm talking about the files that subclass the generated `GreeterServicer` in order to provide implementations to the generated stubs.
