### ISSUE TITLE
FLAKE: xds_end2end_test UseOriginalDstNotSupported test

### ISSUE THREAD

**Issue by markdroth** [grpc/grpc#27892]
From the test history, it looks like this started flaking on 2021-10-26, and it's failed a whopping 187 times since then.  The earliest failure was:

https://source.cloud.google.com/results/invocations/8ad167c0-a191-439d-8236-225037414002/targets/%2F%2Ftest%2Fcpp%2Fend2end%2Fxds:xds_end2end_test@poller%3Depoll1/tests

```
test/cpp/end2end/xds/xds_end2end_test.cc:1313: Failure
Value of: status.ok()
  Actual: true
Expected: false
test/cpp/end2end/xds/xds_end2end_test.cc:1315: Failure
Expected equality of these values:
  options.expected_error_code
    Which is: 14
  status.error_code()
    Which is: 0
```

**Comment by yashykt** [comment]
The reason for the failure is that `WaitForNack()` function in xds_end2end_test expects a failure status for the RPCs that it tries. There are cases where RPCs can succeed even if a resource is NACKed. One case where this happens is when servers NACK a LDS resource but they continue serving requests since they already have a valid LDS resource. This is exactly the case that is causing the flakiness in this test.

The flakiness was introduced in https://github.com/grpc/grpc/pull/27715. The changes in this PR set a default valid listener for servers leading to the scenario described above.
