### ISSUE TITLE
gRPC start too many timer thread and cause process hang

### ISSUE THREAD

**Issue by leeyiw** [grpc/grpc#28039]
### What version of gRPC and what language are you using?
grpc-1.28.1, C++

### What operating system (Linux, Windows,...) and version?
Linux CentOS 7.2

### What runtime / compiler are you using (e.g. python version or version of gcc)
gcc 4.9.2

### What did you do?
Make some async client request with deadline. The frequence is about 300r/s.

### What did you expect to see?
Only one timer thread running. 

### What did you see instead?
There is about 100 timer thread running. And those thread is created in the same moment. It some how cause other thread  
hang for more than 10 seconds. 

Is there any documents about how timer thread is managed?

`g_thread_count == 102`

![image](https://user-images.githubusercontent.com/3157740/141772577-4759b145-c64b-4c4c-b270-8a2184316843.png)

![image](https://user-images.githubusercontent.com/3157740/141772770-ac61fa0f-c76c-4c18-a984-8220783d037c.png)

**Comment by veblush** [comment]
@leeyiw Would you please make a small sample to reproduce the problem? And I recommend you to use the latest version of gRPC. gRPC timers can spawn many threads if all timer threads are busy running the callback. If your timer callback is blocked, it's possible to have many threads spawned.

**Comment by leeyiw** [comment]
> @leeyiw Would you please make a small sample to reproduce the problem? And I recommend you to use the latest version of gRPC. gRPC timers can spawn many threads if all timer threads are busy running the callback. If your timer callback is blocked, it's possible to have many threads spawned.

It's hard to reproduce this issue with a small sample, because this crash is not happen every time. Is there any changes with timer and timer thread management between 1.28.1 and the latest version?

I'm using `CompletionQueue` for async gRPC response, Is there any particular reason could block the timer callback?

**Comment by ccppoo** [comment]
does this issue have any relation with thread spwaning when blocking CLI print while running example codes?

**Comment by leeyiw** [comment]
> I'm using `CompletionQueue` for async gRPC response, Is there any particular reason could block the timer callback?

Nope.

**Comment by drfloob** [comment]
Hi @leeyiw . The timer thread spawning strategy has changed a lot since v1.28 (3 years ago). This will be quite difficult to debug, I'd like to suggest you try with the latest gRPC release and check the behavior if you are still interested.

Currently, gRPC uses an auto-scaling thread pool that will spawn new threads (rate-limited) when all threads are occupied for too long. If you try the latest release and see the thread count grow significantly over time, that likely means your callbacks are doing too much work, possibly blocking.

Since this bug is 2 years old, I am guessing this is obsolete. Please reopen the bug if you want to continue investigating this further.

**Comment by leeyiw** [comment]
@drfloob Thanks, We have update to grpc-1.50.1 and no more bug case shows up. I think newer version somehow fixed this bug.
