### ISSUE TITLE
gRPC C# on unity: The iOS library seems unusually large

### ISSUE THREAD

**Issue by StephenHodgson** [grpc/grpc#28183]
### What version of gRPC and what language are you using?
[Artifacts for gRPC Build 846a3b5c-b7da-4709-8136-e1f065b4865b](https://packages.grpc.io/archive/2021/11/78a4d21f9be3ab8b6bc56316f1d41fb681a541ac-846a3b5c-b7da-4709-8136-e1f065b4865b/index.xml)

Unity for GRPC C#
[grpc_unity_package.2.43.0-dev202111221058.zip](https://packages.grpc.io/archive/2021/11/78a4d21f9be3ab8b6bc56316f1d41fb681a541ac-846a3b5c-b7da-4709-8136-e1f065b4865b/csharp/grpc_unity_package.2.43.0-dev202111221058.zip)

### What operating system (Linux, Windows,...) and version?
iOS

### What did you expect to see?
A much much much smaller library.

### What did you see instead?
A 692.2 MB library for iOS.

In comparison the Android libraries are ~100 mb instead.
![image](https://user-images.githubusercontent.com/13334553/142966813-d2c84adc-f202-4514-acbb-7e9430979262.png)

**Comment by StephenHodgson** [comment]
bump. Anything we can do to make this library smaller?

**Comment by ctiller** [comment]
How many of those bytes end up as part of your application?

**Comment by StephenHodgson** [comment]
> How many of those bytes end up as part of your application?

0

I just find it a little concerning that the size of the library is so large compared to the others

**Comment by ctiller** [comment]
I suspect most of it is debug symbols, and in the trade between ease of
implementation and binary bytes on disk I'm strongly leaning towards ease
of implementation.

**Comment by StephenHodgson** [comment]
Is there anything we can do to reduce the size of this library for production builds?

**Comment by jtattermusch** [comment]
I'm going to close issue this since we're not going to pursuit Unity/Xamarin support in `Grpc.Core` anymore.
- The `Grpc.Core` implementation is now in maintenance mode and we're only going to focus on critical and security fixes.
- Supporting Unity/Xamarin simply presents too much maintenance overhead and it's also difficult to test with the test infrastructure available to us
- The Unity/Xamarin support has always been classified as "experimental", so discontinuing the support shouldn't be too surprising.

See [the recent update on gRPC C#](https://groups.google.com/g/grpc-io/c/OTj5mb1qzb0/m/-M81UQipAQAJ) for more details.

Note that in practice, running Grpc.Core on Unity/Xamarin might still be possible (there is nothing in principle that would prevent it from working), but it will be completely at your own risk and it's simply not one of the use cases the grpc team will help you with as `Grpc.Core` on Unity/Xamarin is now considered as "not supported" by us (but you might still be able to get help from the community).

**Comment by StephenHodgson** [comment]
Personally I think that's a terrible decision your team made in this issue. There are a large amount of developers that probably utilize or want to utilize this.

Nothing with doing is easy.
