### ISSUE TITLE
1.42.0 not published on rubygems.org

### ISSUE THREAD

**Issue by mttkay** [grpc/grpc#28186]
1.42.0 has been out for a week now, but is not yet published on rubygems.org

* https://github.com/grpc/grpc/releases/tag/v1.42.0
* https://rubygems.org/gems/grpc

Is there a way to align these better so that a release is available for all platforms simultaneously?

**Comment by TomA-R** [comment]
👍 This would be really good to have

**Comment by stanhu** [comment]
@jtattermusch Do you know what's holding the release of this gem? Is https://github.com/grpc/grpc/pull/25992#issuecomment-974474593 related?

**Comment by apolcyn** [comment]
1.42.0 has just been published.

Note that some changes were made between the 1.42.0.pre1 and the 1.42.0 release considering the reports in #25992 (comment) and https://github.com/grpc/grpc/issues/28085:

- The arm64-darwin gem was not published in 1.42.0 (because of the problem mentioned in #25992 (comment))

- The universal-darwin gem was not published, so the x86_64-darwin gem and source code packages are the only mac packages

Please ping if there are issues around this.
