### ISSUE TITLE
C# Unity on mac: macOS library's suffix replaces .bundle when copying

### ISSUE THREAD

**Issue by m-yukio** [grpc/grpc#28412]
### What version of gRPC and what language are you using?
A gRPC from the master branch for Unity.

### What operating system (Linux, Windows,...) and version?
macOS

### What runtime / compiler are you using (e.g. python version or version of gcc)
Unity 2020.3.23.f1
Target Platform: macOS
Scripting Backend: IL2CPP
Api Compativbility Level: .NET 4.x

### What did you do?
I got an error in the macOS IL2CPP build, so I checked the contents of the repository.

macOS library's suffix replaces .bundle when copying.

https://github.com/grpc/grpc/blob/master/src/csharp/build_unitypackage.sh#L54

cp nativelibs/csharp_ext_macos_x64/libgrpc_csharp_ext.dylib unitypackage/unitypackage_skeleton/Plugins/Grpc.Core/runtimes/osx/x64/grpc_csharp_ext.bundle

Also, I have the following concerns about the macOS native library:

* Does it need to be a shared library?
  As with iOS, static libraries are fine. 

* Isn't it wrong to make it into  macOS's Bundle Structures format?

**Comment by pspgit** [comment]
@m-yukio 
I'm also having issue, building il2cpp on MacOS.
Full error is here:
https://github.com/grpc/grpc/issues/25522#issuecomment-1002075078

Did you find a way to workaround/fix it?

**Comment by m-yukio** [comment]
@pspgit
I haven't solved it yet.
Considering security, I think IL2CPP is appropriate instead of mono build, so I am investigating the cause.

**Comment by jtattermusch** [comment]
I'm going to close issue this since we're not going to pursuit Unity/Xamarin support in `Grpc.Core` anymore.
- The `Grpc.Core` implementation is now in maintenance mode and we're only going to focus on critical and security fixes.
- Supporting Unity/Xamarin simply presents too much maintenance overhead and it's also difficult to test with the test infrastructure available to us
- The Unity/Xamarin support has always been classified as "experimental", so discontinuing the support shouldn't be too surprising.

See [the recent update on gRPC C#](https://groups.google.com/g/grpc-io/c/OTj5mb1qzb0/m/-M81UQipAQAJ) for more details.

Note that in practice, running Grpc.Core on Unity/Xamarin might still be possible (there is nothing in principle that would prevent it from working), but it will be completely at your own risk and it's simply not one of the use cases the grpc team will help you with as `Grpc.Core` on Unity/Xamarin is now considered as "not supported" by us (but you might still be able to get help from the community).
