### ISSUE TITLE
Stream is closed for idle connection

### ISSUE THREAD

**Issue by rochaudhari** [grpc/grpc#28551]
I have bidirectional streaming rpc between server and client. If data is not exchanged over the stream, after certain time, on the server, it seems that stream is disconnected or stream-Read() returns false.

Currently I am not using keepalive flags for the channel on server and client.
There is a flag:
GRPC_ARG_KEEPALIVE_PERMIT_WITHOUT_CALLS
: This channel argument if set to 1 (0 : false; 1 : true), allows keepalive pings to be sent even if there are no calls in flight.
what is meaning of "no calls in flight" ?

Is this the option will help me out to solve my issue? What are the performance penalties? 

I found that there is an alternative idleTimeout in Java, however, is there any similar option in C++? Also, how to set it to infinite?

**Comment by yashykt** [comment]
>This channel argument if set to 1 (0 : false; 1 : true), allows keepalive pings to be sent even if there are no calls in flight.
what is meaning of "no calls in flight" ?
It means that there are no RPCs on the channel at the time when the ping would have been sent normally. Since there is already a bidrectional streaming RPC on the channel, this would not matter to you.

It does seem like you are facing idle timeouts in which case enabling keepalive should help. https://github.com/grpc/proposal/blob/master/A8-client-side-keepalive.md talks more about this.

Also, this form is not meant for questions. Please use grpc-io or stack overflow instead.
