### ISSUE TITLE
1.43.1 seems to use universal gem on mac arm

### ISSUE THREAD

**Issue by abrausch** [grpc/grpc#28631]
### What version of gRPC and what language are you using?
1.42.0
1.43.1
ruby

### What operating system (Linux, Windows,...) and version?
mac (arm64)

### What did you do?
gem install grpc -v "1.42.0"
gem install grpc -v "1.43.1"

Installing the newest version of grpc

### What did you expect to see?
Using it in ruby works

### What did you see instead?
Problem with grpc_c.bundle

I think the problem is that there is some kind of regression bug between 1.42.0 and 1.43.1
If I search locally in my gem folder for grpc_c.bundle this is the result:

grpc-1.42.0/src/ruby/lib/grpc/grpc_c.bundle
grpc-1.42.0/src/ruby/ext/grpc/grpc_c.bundle
grpc-1.43.1-universal-darwin/src/ruby/lib/grpc/2.5/grpc_c.bundle
grpc-1.43.1-universal-darwin/src/ruby/lib/grpc/3.0/grpc_c.bundle
grpc-1.43.1-universal-darwin/src/ruby/lib/grpc/2.6/grpc_c.bundle
grpc-1.43.1-universal-darwin/src/ruby/lib/grpc/2.7/grpc_c.bundle

As you can see the 1.43.1 is again universal.
The file command gives me the following result:

ruby/2.7.3/gems
➜ file grpc-1.42.0/src/ruby/lib/grpc/grpc_c.bundle
grpc-1.42.0/src/ruby/lib/grpc/grpc_c.bundle: Mach-O 64-bit bundle arm64

ruby/2.7.3/gems
➜ file grpc-1.43.1-universal-darwin/src/ruby/lib/grpc/3.0/grpc_c.bundle
grpc-1.43.1-universal-darwin/src/ruby/lib/grpc/3.0/grpc_c.bundle: Mach-O 64-bit bundle x86_64

So you can see the 1.43.1 is x86_64 which is wrong 

Make sure you include information that can help us debug (full error message, exception listing, stack trace, logs).

See [TROUBLESHOOTING.md](https://github.com/grpc/grpc/blob/master/TROUBLESHOOTING.md) for how to diagnose problems better.

**Comment by bfad** [comment]
I know that adding a new architecture can take time, but it would be helpful if you stopped publishing the `universal-darwin` version of the compiled gem until you've added Arm support. With MacOS dropping 32-bit support in 10.15 and the advent of Arm Macs, Apple now uses "universal" to mean x86_64 and arm64. When I use bundler to install this gem with a lock file that has `arm64-darwin` as a platform on my Arm Mac, it sees "universal" and uses the current definition to download your "universal" build. Unfortunately, this doesn't work, but allowing it to install and build from source does.

**Comment by jpfourny** [comment]
> 

Universal = lies 😸

**Comment by mpalmer** [comment]
Is there anything that I can do to help this issue towards resolution?  This issue is quite important for us, at least, as it makes installation of our code (which depends on `grpc`) an annoyingly fiddly task on an arm64 Mac, as the user has to install `grpc` manually from source, and then install our gem on top -- which is a pretty bad UX.

The interim fix -- pending support for adding arm64 into the build, which I totally understand is probably not trivial -- could potentially be as simple as replacing the `universal` label with `x86_64` on the Darwin arch spec.  Forcing the (probably very few, by now) PPC users to build `grpc` from source is a reasonable trade-off, IMO, in order to allow arm64 users to also build from source, as compared to the current situation where `grpc` fails with a fairly inscrutable error message at runtime for arm64 users.

If a PR for the above would be accepted, please let me know and I'll whip something up ASAP.

**Comment by haines** [comment]
Worth noting that @mpalmer's suggested interim fix is exactly what the google-protobuf gem (which also does not have a working darwin-arm64 native gem yet) has done since v3.19 (https://rubygems.org/gems/google-protobuf/versions), so it seems sensible!

**Comment by hakusaro** [comment]
A lot of issues are being created on this project all to work around the same problem (https://github.com/grpc/grpc/issues/24846, https://github.com/grpc/grpc/issues/29100, etc). Is there a maintainer I can sponsor or some equivalent who can make progress on this?

**Comment by alto-ruby** [comment]
Mac arm should be supported now, though it takes some time to build the extension.
Can you verify if latest releases work for you?
