### ISSUE TITLE
Support parsing response protos outside the main thread

### ISSUE THREAD

**Issue by jcanizales** [grpc/grpc#2869]
At least a non-breaking design is needed before Beta.

**Comment by jcanizales** [comment]
@jayantkolhe I have a design and this won't be involve an API change; it'll be the default behavior as expected.

**Comment by makdharma** [comment]
The burden of proto parsing has not come up in any discussion with Mobile users. Proposing closing of this feature request.

**Comment by jcanizales** [comment]
@ThomasVL, what do you think?

In my mind I see someone facing a UI-responsivity problem, wasting plenty of time debugging it to find it's due to this, and cursing us and our ancestors for deeming it acceptable. It's also variable in that you might get lucky, or you might get several big server responses all together making your UI janky. Protobuf parsing is faster than JSON, but is it so fast we can afford to always send it to the main thread?

**Comment by thomasvl** [comment]
It is always going to depend on the proto and the data going into the proto.  Yes, I'd hope it is always faster than JSON, but since it is data specific, I'm not sure one can always say it is fast enough to always do on the main thread.

The Protobuf library can parse on any thread; it just follows normal platform conventions that an object can be inspected on any thread, but only mutated from a single thread at a time (and not mutated while another is inspecting it).  Is there a reason grpc has to be more limiting?

**Comment by jcanizales** [comment]
None, we just haven't gotten to it.

**Comment by muxi** [comment]
Done

**Comment by jcanizales** [comment]
PR#?

**Comment by jcanizales** [comment]
Oh, #10505 .

**Comment by muxi** [comment]
Yep #10505.
