### ISSUE TITLE
HTTP/2 stream 0 was not closed cleanly: INTERNAL_ERROR (err 2)

### ISSUE THREAD

**Issue by kevinashaw** [grpc/grpc#28814]
I'm implementing a HealthCheck for a container that will run in a cluster.
I followed the best-practices documented here:
- https://github.com/grpc-ecosystem/grpc-health-probe
- https://github.com/grpc/grpc/blob/master/doc/health-checking.md

When I run the grpc-health-probe from a nearby instance in the same subnet on a container with this code, I get the correct response: SERVING.
But when I run curl on it, I get this (note the HealthCheck is implemented on port 8499)

```
ubuntu@ip-10-0-0-128:~$ curl -v -H "Content-Type: application/grpc" http://10.0.12.209:8499/grpc.health.v1.Health/Check --http2-prior-knowledge
*   Trying 10.0.12.209:8499...
* TCP_NODELAY set
* Connected to 10.0.12.209 (10.0.12.209) port 8499 (#0)
* Using HTTP2, server supports multi-use
* Connection state changed (HTTP/2 confirmed)
* Copying HTTP/2 data in stream buffer to connection buffer after upgrade: len=0
* Using Stream ID: 1 (easy handle 0x55d783825860)
> GET /grpc.health.v1.Health/Check HTTP/2
> Host: 10.0.12.209:8499
> user-agent: curl/7.68.0
> accept: */*
> content-type: application/grpc
>
* Connection state changed (MAX_CONCURRENT_STREAMS == 4294967295)!
* HTTP/2 stream 0 was not closed cleanly: INTERNAL_ERROR (err 2)
* stopped the pause stream!
* Connection #0 to host 10.0.12.209 left intact
curl: (92) HTTP/2 stream 0 was not closed cleanly: INTERNAL_ERROR (err 2)
```

My question: why the curl error shown above?

The protobuf definition is exactly that same as referenced in the health-checking.md document.
The python implementation code is listed below. It is running on Ubuntu/R20 instance in AWS ECS.

```
import logging
from concurrent import futures

import grpc

import healthcheck_pb2
import healthcheck_pb2_grpc


class HealthServicer(healthcheck_pb2_grpc.HealthServicer):

    def Check(
            self,
            request: healthcheck_pb2.HealthCheckRequest,
            context: grpc.aio.ServicerContext) -> healthcheck_pb2.HealthCheckResponse:
        return healthcheck_pb2.HealthCheckResponse(status=healthcheck_pb2.HealthCheckResponse.ServingStatus.SERVING)


def serve() -> None:
    server = grpc.server(futures.ThreadPoolExecutor(max_workers=10))
    healthcheck_pb2_grpc.add_HealthServicer_to_server(HealthServicer(), server)
    listen_addr = '[::]:8499'
    server.add_insecure_port(listen_addr)
    logging.info("HealthCheck::Starting server on %s", listen_addr)

    # start the gRPC server to handle requests
    server.start()

    # block the calling thread until the server terminates
    server.wait_for_termination()
```

**Comment by gnossen** [comment]
There are a few problems here, but let me start by cutting to the chase with the working curl invocation:

```
curl -v -XPOST \
  -H "Content-Type: application/grpc" \
  -H "TE: trailers" \
  http://10.0.12.209:8499/grpc.health.v1.Health/Check \
  --http2-prior-knowledge \
  --data @<(printf '\x0\x0\x0\x0\x0')
```

Let's go over the differences one by one.

### POST

gRPC uses the HTTP/2 POST method only. Many HTTP proxies cache responses to GET requests. For RPC, this is unacceptable since RPCs are not idempotent by default.

### Trailers

The gRPC wire protocol requires trailers. HTTP/2 requires that clients advertise their ability to handle trailers with the [transfer encoding header "TE".](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/TE)

### Request Body

This gets complicated since it's all binary and it's dependent on the exact proto. Follow along with these resources:

- [The health check protocol buffer](https://github.com/grpc/grpc/blob/master/src/proto/grpc/health/v1/health.proto)
- [The gRPC wire protocol](https://github.com/grpc/grpc/blob/master/doc/PROTOCOL-HTTP2.md)
- [The Protocol Buffer Serialization Format](https://developers.google.com/protocol-buffers/docs/encoding)

The relevant BNF from the gRPC wire protocol is here:

```
Length-Prefixed-Message → Compressed-Flag Message-Length Message
Compressed-Flag → 0 / 1 # encoded as 1 byte unsigned integer
Message-Length → {length of Message} # encoded as 4 byte unsigned integer (big endian)
Message → *{binary octet}
```

We want to send an uncompressed message and the contents will be an instance of [`HealthCheckRequest`](https://github.com/grpc/grpc/blob/master/src/proto/grpc/health/v1/health.proto) with `service` set to "" (to represent "all services"). Luckily for us, "" is the default value for the string type, so we can omit it from the serialization entirely. So our protobuf message will be zero bytes long.

Going back to our date frame, we'll need 1 zero byte to indicate an uncompressed body. Then, 4 zero bytes to indicate a message length of 0. This is how I arrived at `printf "\x0\x0\x0\x0\x0"`.


---

But I view all of this as more or less an academic exercise. Is there any reason you're not using a tool like [`grcurl`](https://github.com/fullstorydev/grpcurl)?

**Comment by kevinashaw** [comment]
Thank you for the excellent response.
Using the command you provided (and updating to the latest container IP address), we get the following:

```
ubuntu@ip-10-0-0-128:~$ curl -v -XPOST \
>   -H "Content-Type: application/grpc" \
>   -H "TE: trailers" \
>   http://10.0.11.76:8499/grpc.health.v1.Health/Check \
>   --http2-prior-knowledge \
>   --data @<(printf '\x0\x0\x0\x0\x0')
Note: Unnecessary use of -X or --request, POST is already inferred.
*   Trying 10.0.11.76:8499...
* TCP_NODELAY set
* Connected to 10.0.11.76 (10.0.11.76) port 8499 (#0)
* Using HTTP2, server supports multi-use
* Connection state changed (HTTP/2 confirmed)
* Copying HTTP/2 data in stream buffer to connection buffer after upgrade: len=0
* Using Stream ID: 1 (easy handle 0x560dc4861860)
> POST /grpc.health.v1.Health/Check HTTP/2
> Host: 10.0.11.76:8499
> user-agent: curl/7.68.0
> accept: */*
> content-type: application/grpc
> te: trailers
> content-length: 0
>
* Connection state changed (MAX_CONCURRENT_STREAMS == 4294967295)!
< HTTP/2 200
< content-type: application/grpc
< grpc-status: 12
< grpc-message: "b'/grpc.health.v1.Health/Check'" requires exactly one request message.
<
* Connection #0 to host 10.0.11.76 left intact
```

I only just heard about `grpcurl` this afternoon and will install it later today to test it.
Do you have any idea why the grpc service is returning with a grpc-status of 12 ("UNIMPLEMENTED")?
Thank you again!!
-K

**Comment by gnossen** [comment]
> "b'/grpc.health.v1.Health/Check'" requires exactly one request message.

This error message indicates that the server was unable to successfully read a data frame from the request. In other words, there's something going wrong with the `--data` flag. The "content-length: 0" portion of your request also confirms this.

It's possible that your shell does not fully implement file-like redirection. Maybe try using `printf` to first output to an actual named file and using that?

**Comment by norbjd** [comment]
Hello @gnossen !

I have the same error as @kevinashaw : `grpc-message: "b'/helloworld.Greeter/SayHello'" requires exactly one request message.`

To give context of my issue, I was doing some stuff with envoy, grpc-web filter, and a Python gRPC server, and I couldn't get a response from envoy (`requires exactly one request message`). So I decided to debug manually with curl my gRPC server and notice the same error.

**Comment by gnossen** [comment]
@norbjd My response is the same as above. @kevinashaw 's log above clearly shows that 0 bytes are sent in the payload, which is incorrect. It should be sending 5 bytes, as I explain above. The problem is likely that the shell being used does not support file=-like redirection, so the workaround I explain above should be sufficient.
