### ISSUE TITLE
The "HelloworldXamarin" demo link error too when building with Xamarin.iOS 

### ISSUE THREAD

**Issue by liuzhenLz** [grpc/grpc#29116]
/Users/liuzhen/Downloads/grpc-master/examples/csharp/HelloworldX
<img width="1510" alt="截屏2022-03-16 下午3 27 22" src="https://user-images.githubusercontent.com/19431635/158538151-da181171-d2f4-4484-8a01-f0bc9d048023.png">
amarin/HelloworldXamarin.iOS/MTOUCH: Error MT5213: Duplicate symbol in: /Users/liuzhen/.nuget/packages/grpc.core.xamarin/2.44.0/build/Xamarin.iOS10/../../native/ios/universal/libgrpc.a(status.upb.o) (Location related to previous error) (MT5213) (HelloworldXamarin.iOS)

**Comment by liuzhenLz** [comment]
maybe not set gcc linkerFlags?

**Comment by jtattermusch** [comment]
I'm going to close issue this since we're not going to pursuit Unity/Xamarin support in `Grpc.Core` anymore.
- The `Grpc.Core` implementation is now in maintenance mode and we're only going to focus on critical and security fixes.
- Supporting Unity/Xamarin simply presents too much maintenance overhead and it's also difficult to test with the test infrastructure available to us
- The Unity/Xamarin support has always been classified as "experimental", so discontinuing the support shouldn't be too surprising.

See [the recent update on gRPC C#](https://groups.google.com/g/grpc-io/c/OTj5mb1qzb0/m/-M81UQipAQAJ) for more details.

Note that in practice, running Grpc.Core on Unity/Xamarin might still be possible (there is nothing in principle that would prevent it from working), but it will be completely at your own risk and it's simply not one of the use cases the grpc team will help you with as `Grpc.Core` on Unity/Xamarin is now considered as "not supported" by us (but you might still be able to get help from the community).

**Comment by liuzhenLz** [comment]
What does this mean? Is there any ready-made plan? Your example is unavailable.

**Comment by sandros06** [comment]
Hey @liuzhenLz 
Do you find a solution ?
