### ISSUE TITLE
ResourceWarning: unclosed SSLSocket

### ISSUE THREAD

**Issue by parthea** [grpc/grpc#29227]
### What version of gRPC and what language are you using?
grpcio==1.44.0.
Python

### What operating system (Linux, Windows,...) and version?
Linux (Google)

### What runtime / compiler are you using (e.g. python version or version of gcc)
Python 3.9.9
```
gcc --version
gcc (Debian 11.2.0-16) 11.2.0
```

### What did you do?
Please provide either 1) A unit test for reproducing the bug or 2) Specific steps for us to follow to reproduce the bug. If there’s not enough information to debug the problem, gRPC team may close the issue at their discretion. You’re welcome to re-open the issue once you have a reproduction.
I ran the code example from [this issue](https://github.com/googleapis/python-secret-manager/issues/271).

### What did you expect to see?
I didn't expect to see warnings.

### What did you see instead?
I saw a similar warning as reported [this issue](https://github.com/googleapis/python-secret-manager/issues/271).
```
.../lib/python3.8/site-packages/grpc/_channel.py:1548: ResourceWarning: unclosed <ssl.SSLSocket fd=10, family=AddressFamily.AF_INET6, type=SocketKind.SOCK_STREAM, proto=6, laddr=('2a02:1210:22bd:8300:2b23:d126:3a74:f57b', 46782, 0, 0), raddr=('2a00:1450:400a:801::200a', 443, 0, 0)>
  self._channel.close(cygrpc.StatusCode.cancelled, 'Channel closed!')
ResourceWarning: Enable tracemalloc to get the object allocation traceback
```

Make sure you include information that can help us debug (full error message, exception listing, stack trace, logs).

See [TROUBLESHOOTING.md](https://github.com/grpc/grpc/blob/master/TROUBLESHOOTING.md) for how to diagnose problems better.

### Anything else we should know about your project / environment?
I'm able to reproduce the issue every time. I also tried debugging and wrapping the code in `contextlib.closing` but the warning persisted.
```
with contextlib.closing(secretmanager.SecretManagerServiceClient()) as client:
        response = client.create_secret(
            request={
                "parent": parent,
                "secret_id": "test2",
                "secret": {"replication": {"automatic": {}}},
            }
        )
 ```

**Comment by lidizheng** [comment]
The good news is that I can reproduce this warning.

The bad news is that I can't locate this "leaked" resource. Strangely, the "leaked" resource is an `ssl.SSLSocket`, which is not used by gRPC Python library itself:

```
/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/grpc/_channel.py:1548: ResourceWarning: unclosed <ssl.SSLSocket fd=8, family=AddressFamily.AF_INET6, type=SocketKind.SOCK_STREAM, proto=0, laddr=('2601:646:8a81:a950:b577:1f7c:204a:8cff', 62141, 0, 0), raddr=('2607:f8b0:4005:813::200a', 443, 0, 0)>
  self._channel.close(cygrpc.StatusCode.cancelled, 'Channel closed!')
Object allocated at (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/ssl.py", lineno 1033
    self = cls.__new__(cls, **kwargs)
```

After using `pdb` to trace the repro application, I didn't observe any call to create `ssl.SSLSocket`.

**Comment by lidizheng** [comment]
@parthea The owner of this `SSLSocket` might be `google-auth`. My theory is that the warning is populated here because gRPC is diving into C-Extension, so any issue in the tear down phase got assigned here. I tried to use the AsyncIO version of the client library, it passed without any warning.

```python
async def work():
    async with SecretManagerServiceAsyncClient() as client:
        response = await client.access_secret_version(name='blah')
        print(f"GET {response}")

if __name__ == "__main__":
    asyncio.run(work())
```

I also tried with our advanced auth example: https://github.com/grpc/grpc/tree/master/examples/python/auth. No warning is observed. So, the warning is not generated by gRPC in normal workflow.

In `google-auth`, the application default credentials require getting token (see [code](https://github.com/googleapis/google-auth-library-python/blob/c99350455d0f7fd3aab950ac47b43000c73dd312/google/auth/transport/grpc.py#L69) from Google endpoint, which should create a SSLSocket as transport.

There might be a fix to explicitly close the token-refreshing socket when it's finished.

CC @busunkim96 can you advice on the life cycle of the token-refreshing socket? (I dug into the google-auth code, but yet to find the exact place the outbound call is started.)

**Comment by parthea** [comment]
Fixed in https://github.com/googleapis/google-auth-library-python/pull/1007

**Comment by j05070415** [comment]
谢谢，您的邮件我已收到！
