### ISSUE TITLE
When reading the properties of `RpcException`, an unrelated exception may be thrown

### ISSUE THREAD

**Issue by allyn-psyonix** [grpc/grpc#29237]
I found this in 2.36.4 but it appears to still be an issue in the latest. When reading the properties of `RcpException`, an unrelated exception can be thrown. Specifically, `RpcException.Trailers` is of type `Metadata` and `Metadata.Value` can throw an exception from its getter.

This is generally bad practice, and is recommended against by Microsoft. The fact that exceptions are often serialized for logging exacerbates the issue, as this would obfuscate the initial exception. Whether or not to call this a "bug" is subjective since this appears to be by design, but I think it's clearly a flaw that should be addressed either way.

From a more general design perspective, it's generally a bad idea to throw an exception inside a property getter or setter. If the behavior involved could explicitly throw an exception, it's better to use a method instead of a property. Microsoft's guidance on this [can be found here](https://docs.microsoft.com/en-us/dotnet/standard/design-guidelines/property?redirectedfrom=MSDN). Relevant excerpt (emphasis mine):

> ❌ AVOID throwing exceptions from property getters.
> 
> Property getters should be simple operations and should not have any preconditions. If a getter can throw an exception, **it should probably be redesigned to be a method**. Notice that this rule does not apply to indexers, where we do expect exceptions as a result of validating the arguments.

`RpcException.Trailers` is of type `Metadata`. `Metadata.Value` is a property as follows:
```
public string Value
{
    get
    {
        GrpcPreconditions.CheckState(!IsBinary, "Cannot access string value of a binary metadata entry");
        return value;
    }
}
```

When the metadata is recognized as binary, an exception is thrown. This can interrupt exception handling for the RpcException and make it difficult to diagnose the issue. In our case, when our logger attempts to parse one of these during serialization, the resulting exception obfuscates the real exception.

One option would be to change it to a getter method such as `bool TryGetValue(out string value)`
- Prevents it from being read automatically by serializers
- Method name makes it clear to the caller that it may fail
- Fails safely (return `false` instead of throwing an exception)

**Comment by jtattermusch** [comment]
While I agree with the sentiment that property getters should not throw, I don't quite understand how you'd get from handling RpcException to an exception being raised while reading the metadata.
- When reading the metadata entries from RpcException.Trailers (or from anywhere else), you need to consult  `metadataEntry.IsBinary` ([here](https://github.com/grpc/grpc-dotnet/blob/ad67dc8d27eb2738f4a7c6af9df49b856cbbc177/src/Grpc.Core.Api/Metadata.cs#L367) property first and then either ask for `metadataEntry.Value` (a string value for non-binary metadata) or `metadataEntry.ValueBytes` (for binary metadata). So you need to use the API incorrectly to get an exception thrown.

In retrospect, the MetadataEntry API might have been designed differently, but even when it formally doesn't comply with the microsoft guidance, the existing API works quite well in practice and changing it would mean a breaking change, potentially breaking all the existing users - and I don't think the nature of this issue would warrant doing some costly as that.

The issue is marked with "area/api" label and if we ever look into re-redesigning the C# API in the future (note currently there is no such plan), we will include the API feedback into account.

**Comment by allyn-psyonix** [comment]
It happens during serialization, in our case for logging purposes. When the exception is serialized this property is read and the exception is thrown. This happens during logging, so it's outside the normal exception handling scopes, which is why it's so dangerous.

Personally I would consider this a big enough risk that it should be addressed. It risks occurring outside normal exception handling blocks by generic code.
