### ISSUE TITLE
How can i get the grpc include dir in my CMakelists.txt

### ISSUE THREAD

**Issue by wuleistarrocks** [grpc/grpc#29366]
How can i get the grpc include dir in my CMakelists.txt? gRPC_INCLUDE_DIRS seems useless!

**Comment by yashykt** [comment]
Can you give some more details as to what you are trying to accomplish please?

**Comment by jtattermusch** [comment]
I think the "use gRPC from a cmake project" use case is pretty well documented here: https://github.com/grpc/grpc/tree/master/src/cpp#cmake (which also links to full examples of how include gRPC).

Since this issue doesn't provide any detail about what's wrong with the documentation and there's no clear indication that there's a bug/issue somewhere, I'm going to close.
