### ISSUE TITLE
etcd3 and python: UNAUTHENTICATED: Established channel does not have a sufficient security level to transfer call credential

### ISSUE THREAD

**Issue by eliminyro** [grpc/grpc#29643]
### What version of gRPC and what language are you using?
grpc v1.45.0+

### What operating system (Linux, Windows,...) and version?
Ubuntu 20.04

### What runtime / compiler are you using (e.g. python version or version of gcc)
python 3.8.10

### What did you do?
Update grpc from 1.44.0 to 1.45.0 (also 1.46.0) and run it against etcd v3 server with authentication enabled using python-etcd3 module.

### What did you expect to see?
No errors.

### What did you see instead?
```
>>> etcd = etcd3.client(host='etcd_host', port=2379, user='user', password='password')
>>> etcd.get('key_name')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/venv-path/lib/python3.8/site-packages/etcd3/client.py", line 283, in get
    range_response = self.get_response(key, **kwargs)
  File "/venv-path/lib/python3.8/site-packages/etcd3/client.py", line 48, in handler
    _translate_exception(exc)
  File "/venv-path/lib/python3.8/site-packages/etcd3/client.py", line 46, in handler
    return f(*args, **kwargs)
  File "/venv-path/lib/python3.8/site-packages/etcd3/client.py", line 257, in get_response
    return self.kvstub.Range(
  File "/venv-path/lib/python3.8/site-packages/grpc/_channel.py", line 946, in __call__
    return _end_unary_response_blocking(state, call, False, None)
  File "/venv-path/lib/python3.8/site-packages/grpc/_channel.py", line 849, in _end_unary_response_blocking
    raise _InactiveRpcError(state)
grpc._channel._InactiveRpcError: <_InactiveRpcError of RPC that terminated with:
        status = StatusCode.UNAUTHENTICATED
        details = "Established channel does not have a sufficient security level to transfer call credential."
        debug_error_string = "{"created":"@1652261814.087167077","description":"Error received from peer etcd_host:2379","file":"src/core/lib/surface/call.cc","file_line":952,"grpc_message":"Established channel does not have a sufficient security level to transfer call credential.","grpc_status":16}"
```

**Comment by eliminyro** [comment]
Thanks for getting back to me, Richard.

Could you let me know, how can I check if the library uses the security channel?
Additionally, did grpcio version 1.44.0 require it as well or is it a new feature?
The version of grpcio is the only thing that changed in my setup. I used python-etcd3 version 0.12.0 in both instances (with 1.44.0 and 1.45.0+).

**Comment by gnossen** [comment]
No, this should always have been a requirement. [`grpc.insecure_channel`](https://grpc.github.io/grpc/python/grpc.html#grpc.insecure_channel) will create an insecure channel and [`grpc.secure_channel`](https://grpc.github.io/grpc/python/grpc.html#grpc.secure_channel) will create a secure channel. You'll want to check to see which of these two functions is being used.

If `secure_channel` is indeed the one being used, then this is a regression.

**Comment by eliminyro** [comment]
I've checked the code of python-etcd3 library itself, and it seems that secure_channel is used for HTTPS connections only.
I've tried using the etcd library with the newest grpcio with TLS enabled on etcd server, and it seems to be working alright.
I wasn't obvious that it is mandatory though.

However, if someone else stumbles upon this issue, they might find this useful. I'll close the issue, since everything seems to be working just fine.

**Comment by cunningr** [comment]
I am just hitting the same issue and also had this working previously.  By using the same version as [eliminyro](https://github.com/eliminyro) I was able to get it to work without TLS:

```
etcd3==0.12.0
grpcio==1.44.0
```

The change does indeed seem to be in `grpcio`

**Comment by ZhenLian** [comment]
I am not sure the current status of Python. Just explaining what I know in the realm of core implementation:
The call credential previously had to be tied to a secure credential. The rationale was that when doing authentication based on call credential(e.g. JWT token authentication), it is important to also encrypt the token being transferred on the wire, so there was no security risks.
At some point, we realized that it was actually up to the user to set the security level of the call credential, so that the call cred implementation can choose whether it wants to bind to the secure credential. So in gRPC C core right now, the call credential has a field to override the call credential default security level, to ask it to be transmitted on an insecure channel.
I am not sure if that option is exposed to python though. If you are using some gRPC-implemented call credential, then very likely it requires to be transmitted over a secure channel; if you are writing your own call cred and python exposes that field, then probably it's possible to update its default security level settings.
You can read more at this gRFC: https://github.com/grpc/proposal/blob/master/L62-core-call-credential-security-level.md for more.

**Comment by bashar94** [comment]
Getting error on `grpcio==1.44.0` installation. It is not getting built into my MacBook Pro M1 Pro. Does anyone know the fix?

**Comment by FengYe-cxy** [comment]
您的问题在时隔三年，也解决了我一样的问题，我是从grpcio==1.68.0降到了grpcio==1.44.0才解决
