### ISSUE TITLE
Being able to open a secure channel in python without any client side certificates

### ISSUE THREAD

**Issue by prnvbn** [grpc/grpc#29682]
### Is your feature request related to a problem? Please describe.
It seems like there is no way to open a secure channel without a client side cert. This is particularly annoying when your server is configured for server side TLS only and does not even request a certificate. What it makes it further a pain is that other gRPC implementations like Go allow for this.

In Go you can do the following

```go
conn, err := grpc.DialContext(
    ctx,
    gRPCAddr,
    grpc.WithTransportCredentials(credentials.NewClientTLSFromCert(nil, "")),
)
```

In python when I create a secure channel using `grpc.ssl_channel_credentials()` It still requires me to have a client cert.

### Describe the solution you'd like
When creating a channel like so 
```python3
channel = grpc.secure_channel(grpc_addr, grpc.ssl_channel_credentials())
```
The `grpc.ssl_channel_credentials()` retrieves the SSL credentials from a default location chosen by gRPC runtime (this is mentioned in the docs [here](https://grpc.github.io/grpc/python/grpc.html#create-client-credentials)). It would be ideal if instead of the current default behaviour when `None` is passed into `ssl_channel_credentials` to mimic the one in Go.

### Describe alternatives you've considered
An alternative that I have considered is providing a client side cert by using the `GRPC_DEFAULT_SSL_ROOTS_FILE_PATH` environment variable, but I don't see why I should have to provide one when It is not going to be requested by the server.

### Additional context
When implementing server-side TLS, I want to be able to allow clients without any certs to be able to connect to my gRPC server.

**Comment by lidizheng** [comment]
The same issue is reported on StackOverflow: https://stackoverflow.com/questions/72230151/how-to-open-a-secure-channel-in-python-grpc-client-without-a-client-ssl-certific

There are a few decent answers there, I will close this issue for now. If there are still unanswered parts, feel free to comment or reopen.

CC @gnossen

**Comment by tinez** [comment]
I'd like to reopen this bug with additional context. The TL; DR; of the problem is - when using `grpcio` package version from pypi I cannot make grpc use OS-provided root certificates.

Here's my use case. You work for a big IT company. Every computer that belongs to the company has a set of internal root certificates installed. They are not based on a publicly trusted CA. When I e.g. open up my browser and go to some internal company website, there are no issues - the browser respects the additionally installed OS-level root certificates and is able to verify the identity of the website. That is not true for a python script that uses `grpcio`.

The workaround is to pass the private root certificate as an argument to `ssl_channel_credentials` and then everything works as expected.

I dug a bit into the code on how it's implemented and landed [here](https://github.com/grpc/grpc/blob/065aa63d1754a0271a88b762d02d7b049a39c4e8/src/core/lib/security/security_connector/ssl_utils.cc#L568). The first condition for loading the certs is:
```
if (!default_root_certs_path.empty())
```
so I though, "OK, if I set the env var `GRPC_DEFAULT_SSL_ROOTS_FILE_PATH`" to an empty string I should fall back to the [line that loads the OS-level certs](https://github.com/grpc/grpc/blob/065aa63d1754a0271a88b762d02d7b049a39c4e8/src/core/lib/security/security_connector/ssl_utils.cc#L599). That didn't work - turns out that the python package is shipped with an override defined [here](https://github.com/grpc/grpc/blob/065aa63d1754a0271a88b762d02d7b049a39c4e8/src/python/grpcio/grpc/_cython/_cygrpc/security.pyx.pxi#L20) and used [here](https://github.com/grpc/grpc/blob/065aa63d1754a0271a88b762d02d7b049a39c4e8/src/python/grpcio/grpc/_cython/cygrpc.pyx#L84).

I can't find any (non-hacky) way to disable setting those overrides. Given the set of conditions in `ssl_utils.cc` that effectively means I'll never be able to reach the code that reads OS-level certs.

Is this behavior intentional? Can we add an option for the users to opt-out of the overrides?

CC @gnossen @AvlWx2014

**Comment by msibaev** [comment]
I think what tinez found is a bug and hope it will be fixed. 

In the meantime, here is a workaround that loads default ssl configs using `ssl` module.

```python
import ssl
from OpenSSL import crypto

ssl_context = ssl.create_default_context()
certs_der = ssl_context.get_ca_certs(binary_form=True)
certs_x509 = [crypto.load_certificate(crypto.FILETYPE_ASN1, x) for x in certs_der]
certs_pem = [crypto.dump_certificate(crypto.FILETYPE_PEM, x) for x in certs_x509]
certs_bytes = b"".join(certs_pem)

cred = grpc.ssl_channel_credentials(certs_bytes)
```
