### ISSUE TITLE
Cannot use cmake to build Release

### ISSUE THREAD

**Issue by aaron-michaux** [grpc/grpc#29737]
### What version of gRPC and what language are you using?
Tried both
TAG=v1.45.2
TAG=v1.39.1

### What operating system (Linux, Windows,...) and version?
Linux, Ubuntu 20.04

### What runtime / compiler are you using (e.g. python version or version of gcc)
gcc 9.4.0
cmake version 3.23.1

### What did you do?

```
    cd "grpc"
    git fetch
    git checkout v1.45.2
    git submodule update --init --recursive
    mkdir build
    cd build
    cmake -DCMAKE_CXX_STANDARD=17 \
          -DgRPC_INSTALL=ON                \
          -DgRPC_BUILD_TEST=OFF \
          -DCMAKE_INSTALL_PREFIX=/usr/local \
          -DCMAKE_POSITION_INDEPENDENT_CODE=TRUE \
          -DABSL_PROPAGATE_CXX_STD=ON \
          -CMAKE_BUILD_TYPE=Release \
          ..
```

### What did you expect to see?

cmake should finish

### What did you see instead?

Cmake fails. The error log shows this:

```
Determining if the function __system_property_get exists failed with the following output:
Change Dir: /home/.../Development/cple/contrib/grpc/build/CMakeFiles/CMakeTmp

Run Build Command(s):/usr/bin/make -f Makefile cmTC_ebdae/fast && /usr/bin/make  -f CMakeFiles/cmTC_ebdae.dir/build.make CMakeFiles/cmTC_ebdae.dir/build
make[1]: Entering directory '/home/.../Development/cple/contrib/grpc/build/CMakeFiles/CMakeTmp'
Building C object CMakeFiles/cmTC_ebdae.dir/CheckFunctionExists.c.o
/usr/bin/cc -D_GNU_SOURCE -D_POSIX_C_SOURCE=199309L -D_XOPEN_SOURCE=600  -DCHECK_FUNCTION_EXISTS=__system_property_get -fPIE -o CMakeFiles/cmTC_ebdae.dir/CheckFunctionExists.c.o -c /usr/local/share/cmake-3.23/Modules/CheckFunctionExists.c
Linking C executable cmTC_ebdae
/usr/local/bin/cmake -E cmake_link_script CMakeFiles/cmTC_ebdae.dir/link.txt --verbose=1
/usr/bin/cc   -DCHECK_FUNCTION_EXISTS=__system_property_get -rdynamic CMakeFiles/cmTC_ebdae.dir/CheckFunctionExists.c.o -o cmTC_ebdae  -lnsl -lrt 
/usr/bin/ld: CMakeFiles/cmTC_ebdae.dir/CheckFunctionExists.c.o: in function `main':
CheckFunctionExists.c:(.text+0x14): undefined reference to `__system_property_get'
collect2: error: ld returned 1 exit status
make[1]: *** [CMakeFiles/cmTC_ebdae.dir/build.make:99: cmTC_ebdae] Error 1
make[1]: Leaving directory '/home/.../Development/cple/contrib/grpc/build/CMakeFiles/CMakeTmp'
make: *** [Makefile:127: cmTC_ebdae/fast] Error 2
```

**Comment by nicolasnoble** [comment]
The error snippet you're showing is a red herring, it's just showing that one of the things cmake was trying to check for wasn't present, which is irrelevant. The actual problem is with the combination of options you're asking to build with.

Here, building with

`-DgRPC_BUILD_TESTS=OFF -DgRPC_INSTALL=ON -DCMAKE_BUILD_TYPE=Release`

works properly on an ubuntu 20.04 docker image with only the packages `git build-essential cmake` installed. I'm not going to start bisecting what option you're specifying exactly that's causing the problem, but it's likely it's one of them. If you manage to find the exact option that's causing the trouble, and you need it, please open a new bug with the exact option that's failing, and the rationale why you need it.

**Comment by aaron-michaux** [comment]
Just needed to add `-DgRPC_BUILD_TESTS=OFF` to build in release mode. May be worth editing the cmakelists to catch that, and/or updating the documentation.
