### ISSUE TITLE
Removing Visual Studio 2015

### ISSUE THREAD

**Issue by veblush** [grpc/grpc#29753]
Per new C++ support policy, Support for Visual Studio 2015 is going to be dropped. So let's remove it.

**Comment by veblush** [comment]
@jtattermusch Jan, would you update Windows RBE to use Visual Studio 2017?

**Comment by jtattermusch** [comment]
> @jtattermusch Jan, would you update Windows RBE to use Visual Studio 2017?

Sure, I'll look into that.

**Comment by jtattermusch** [comment]
FTR, the windows RBE docker image setup is here:
https://github.com/grpc/grpc/tree/master/third_party/toolchains

The docker file is here:
https://github.com/grpc/grpc/blob/master/third_party/toolchains/rbe_win2019/Dockerfile

We'd want to upgrade it with newer version of visual studio, but likely also a new version of python (right now it has python2.7), and perhaps other stuff.

CC @nicolasnoble  for visibility (since he's working on the new windows kokoro image)

@nicolasnoble  perhaps what's in the docker file is a good start for a script to initialize the windows kokoro image?

**Comment by ctiller** [comment]
Pinging on the status of this

**Comment by jtattermusch** [comment]
Windows RBE builds now use VS2019: https://github.com/grpc/grpc/pull/30072

**Comment by jtattermusch** [comment]
@veblush  it sounds like the combination of https://github.com/grpc/grpc/pull/29754 and https://github.com/grpc/grpc/pull/30072 makes us VS2015-free? Please double check and close if so.
