### ISSUE TITLE
How to avoid Unity IL2CPP build errors on macOS

### ISSUE THREAD

**Issue by m-yukio** [grpc/grpc#29817]
For macOS, the linker will fail if the static library does not exist.

The following code is the problem.

```
    internal class DllImportsFromStaticLib
    {
        private const string ImportName = "__Internal";

        [DllImport(ImportName)]
        public static extern void grpcsharp_init();

        ...
    }
```

Modify this as follows:

```
    internal class DllImportsFromStaticLib
    {
        private const string ImportName = "__Internal";

        // [DllImport(ImportName)]
        // public static extern void grpcsharp_init();

        ...
    }
```

I know it's wasteful because I don't want to change the code in gRPC.Core, and even if I have a static library, I can't avoid the error.

I need to change the name specified in DllImport from __Internal to a static library name.

```
    internal class DllImportsFromStaticLib
    {
        private const string ImportName = "grpc_csharp_ext";

        [DllImport(ImportName)]
        public static extern void grpcsharp_init();

        ...
    }
```

After all, I'll need to change the gRPC.Core source code.

Apple silicon compatibility is explained here.
https://github.com/grpc/grpc/issues/29815

**Comment by jtattermusch** [comment]
I'm going to close issue this since we're not going to pursuit Unity/Xamarin support in `Grpc.Core` anymore.
- The `Grpc.Core` implementation is now in maintenance mode and we're only going to focus on critical and security fixes.
- Supporting Unity/Xamarin simply presents too much maintenance overhead and it's also difficult to test with the test infrastructure available to us
- The Unity/Xamarin support has always been classified as "experimental", so discontinuing the support shouldn't be too surprising.

See [the recent update on gRPC C#](https://groups.google.com/g/grpc-io/c/OTj5mb1qzb0/m/-M81UQipAQAJ) for more details.

Note that in practice, running Grpc.Core on Unity/Xamarin might still be possible (there is nothing in principle that would prevent it from working), but it will be completely at your own risk and it's simply not one of the use cases the grpc team will help you with as `Grpc.Core` on Unity/Xamarin is now considered as "not supported" by us (but you might still be able to get help from the community).
