### ISSUE TITLE
max_workers not working. No effect from increasing the value from 1 to 30.

### ISSUE THREAD

**Issue by psydok** [grpc/grpc#30478]
With an increase in the number of max_workers, the number of processed messages per second does not change under load.
```
import asyncio
from concurrent import futures

import grpc
from core.utils.log import get_logger

import dto.stt_pb2_grpc as stt_pb2_grpc
import utils.config as settings
from services.stt_service import SpeechToTextService

LOGGER = get_logger(__name__)
MAX_MESSAGE_LENGTH = 1024 * 1024 * 100


async def run_serve(host: str, port: str):
    server = grpc.aio.server(
        futures.ThreadPoolExecutor(max_workers=10),
        options=[
            ('grpc.max_send_message_length', MAX_MESSAGE_LENGTH),
            ('grpc.max_receive_message_length', MAX_MESSAGE_LENGTH),
            ('grpc.keepalive_timeout_ms', 1000000)
        ]
    )

    stt_pb2_grpc.add_SpeechToTextServiceServicer_to_server(
        SpeechToTextService(), server
    )
    address = f"{host}:{port}"
    server.add_insecure_port(address)
    await server.start()
    await server.wait_for_termination()


if __name__ == "__main__":
    asyncio.run(run_serve(settings.GRPC_HOST, settings.GRPC_PORT))
```

Result: RPS 3.5 - with a load of 10-20 users at the same time. 

--------
Python 3.7
grpcio 1.43.0

**Comment by wuranxu** [comment]
How to solve it? I'm facing the same question(low qps) .
😭I have set workers to a large number.

**Comment by gnossen** [comment]
[The argument you're using here is `migration_thread_pool`](https://grpc.github.io/grpc/python/grpc_asyncio.html?highlight=aio%20server#create-server). This is only used by the asyncio server for handlers that are _not_ asyncio. If your handlers are all asyncio , then you're correct that there should be no effect, because _asyncio runs on only a single thread_.

To increase performance, you'll likely need to make some changes to your server handler, but you don't seem to have included that code here, so I can't make any suggestions.
