### ISSUE TITLE
tvOS support for Unity and C#.

### ISSUE THREAD

**Issue by SamPaladin** [grpc/grpc#30527]
I know Grpc.Core is being no longer maintained but I was wondering if you guys can help me. 

With some help from the issues I've been reading I've been able to compile a .a library for tvOS support. You can read details of it here: https://stackoverflow.com/questions/73210972/grpc-in-unity-and-tvos-support

But I am unable to make it run. Generate Xcode project and when deploying I get the same error. It seems it doesn't get loaded through a static but a shared library but it doesn't matter because forcing the code doesn't seems to have different output. 

No matter if setting "__Internal" or "grpc_csharp_ext" for `ImportName` on DllImport I get always the same error. 

Thanks, Regards.

**Comment by jtattermusch** [comment]
I'm going to close issue this since we're not going to pursue Unity/Xamarin support in `Grpc.Core` anymore.
- The `Grpc.Core` implementation is now in maintenance mode and we're only going to focus on critical and security fixes.
- Supporting Unity/Xamarin simply presents too much maintenance overhead and it's also difficult to test with the test infrastructure available to us
- The Unity/Xamarin support has always been classified as "experimental", so discontinuing the support shouldn't be too surprising.

See [the recent update on gRPC C#](https://groups.google.com/g/grpc-io/c/OTj5mb1qzb0/m/-M81UQipAQAJ) for more details.

Note that in practice, running Grpc.Core on Unity/Xamarin might still be possible (there is nothing in principle that would prevent it from working), but it will be completely at your own risk and it's simply not one of the use cases the grpc team will help you with as `Grpc.Core` on Unity/Xamarin is now considered as "not supported" by us (but you might still be able to get help from the community).
