### ISSUE TITLE
Pick First load balancer does not retry to re-resolve if the first address resolution has 0 addresses

### ISSUE THREAD

**Issue by daichij** [grpc/grpc#30803]
### What version of gRPC and what language are you using?

C++
v1.46.4
v1.36.4

### What operating system (Linux, Windows,...) and version?

Linux

### What runtime / compiler are you using (e.g. python version or version of gcc)

gcc 7

### What did you do?

gRPC was attempting to connect using the Pick First load balancer and received a list of 0 addresses from the cARES resolver.

When trying to reproduce the issue consistently we passed an empty address list along so that we would fall into the block handling the case when there are 0 subchannels in AttemptToConnectUsingLatestUpdateArgsLocked in both [v1.36.4](https://github.com/grpc/grpc/blob/v1.36.4/src/core/ext/filters/client_channel/lb_policy/pick_first/pick_first.cc#L192) and [v1.46.4](https://github.com/grpc/grpc/blob/v1.46.4/src/core/ext/filters/client_channel/lb_policy/pick_first/pick_first.cc#L191).

### What did you expect to see?

gRPC automatically retrying address resolution to continue attempting to connect even when it receives 0 addresses.

### What did you see instead?

_On gRPC v1.36.4_ the following logs before gRPC stopped attempting to connect:
```
2022-04-12_04:43:14.45451 I0412 04:43:14.454464756 5638 pick_first.cc:147] Pick First 0x3bf5400 created.
2022-04-12_04:43:14.45455 I0412 04:43:14.454521631 5638 pick_first.cc:266] Pick First 0x3bf5400 received update with 0 addresses
2022-04-12_04:43:14.45461 I0412 04:43:14.454584964 5638 subchannel_list.h:363] [pick_first 0x3bf5400] Creating subchannel list 0x3c5a6c0 for 0 subchannels
```

When reproducing the issue on v1.46.4 gRPC stopped attempting to connect as well.

### Anything else we should know about your project / environment?

Relevant [gRPC mailing list email chain](https://groups.google.com/g/grpc-io/c/P-b8NQEkTr0/m/Eu9uygMKAgAJ) with @markdroth

**Comment by caohoangha126** [comment]
Hello, I seem to run into this issue on version 1.49.1 and it happens non-deterministically. In an attempt to reproduce the issue, the k8s pods that run the service are manually marked as not ready, and the DNS list becomes empty. However, from the attached log, it does seem that after the first DNS resolution attempt resulting in empty address list, another DNS resolution attempt is made. In fact, it keeps making attempt after attempt.
In the bug filed above, does it just make a single DNS resolution attempt before it stops trying? Based on my understanding of the bug, it gets stuck in TRANSIENT_FAILURE because there is no attempt to resolve DNS after the first attempt resulting in empty address list. 
[dns resolution grpc log.txt](https://github.com/user-attachments/files/16887351/dns.resolution.grpc.log.txt)
