### ISSUE TITLE
Signficant unnecessary but avoidable allocations when TCP trace enabled at ignored log-level

### ISSUE THREAD

**Issue by mgravell** [grpc/grpc#30979]
There are multiple code-paths that follow the pattern:

```
        if (grpc_tcp_trace.enabled()) {
          size_t i;
          for (i = 0; i < tcp->read_slices->count; i++) {
            char* dump = grpc_dump_slice(tcp->read_slices->slices[i],
                                         GPR_DUMP_HEX | GPR_DUMP_ASCII);
            gpr_log(GPR_INFO, ... blah ..., dump);
            gpr_free(dump);
          }
        }
```

where `grpc_dump_slice` builds a nul-terminated string of the fragment; this applies to most network read/write; useful for debugging.

However! If the log-level is low (meaning: less logging - for example ERROR only), but the trace is enabled: this performs a **LOT** of unnecessary CPU and memory overhead, including allocating/releasing the memory for the chunks, and performing hex+ascii dumps - only to have it all ignored by the log-level check.

Proposal: add a log-level test earlier, so that expensive work is not performed for no reason; for example:

```
if (grpc_tcp_trace.enabled() && gpr_should_log(GPR_LOG_SEVERITY_INFO)) // whatever the relevant log-level is
```

or, perhaps more cleanly (but with a new overload):

```
if (grpc_tcp_trace.enabled(GPR_LOG_SEVERITY_INFO)) // whatever the relevant log-level is
```

Candidate scenarios:

- https://github.com/grpc/grpc/blob/c6ebbb5482cf93623a73e54c31277c174c97222f/src/core/lib/iomgr/endpoint_cfstream.cc#L122 (DEBUG)
- https://github.com/grpc/grpc/blob/c6ebbb5482cf93623a73e54c31277c174c97222f/src/core/lib/iomgr/endpoint_cfstream.cc#L229 (DEBUG)
- https://github.com/grpc/grpc/blob/70dd34b4382632b4e668c3d968ca49bb3a67076c/src/core/lib/iomgr/tcp_windows.cc#L364 (INFO)
- https://github.com/grpc/grpc/blob/70dd34b4382632b4e668c3d968ca49bb3a67076c/src/core/lib/iomgr/tcp_windows.cc#L211 (INFO)
- https://github.com/grpc/grpc/blob/32bc9a86562353372968bdf45e13bfeed57b00e8/src/core/lib/security/transport/secure_endpoint.cc#L401 (INFO)
- https://github.com/grpc/grpc/blob/c3c4159d243687a81fe48f32fc91ba061a987c58/src/core/lib/iomgr/tcp_posix.cc#L818 (DEBUG)
- https://github.com/grpc/grpc/blob/c3c4159d243687a81fe48f32fc91ba061a987c58/src/core/lib/iomgr/tcp_posix.cc#L1838 (DEBUG)

However, there may be many more

(aside: this was discovered via the C#/.NET `Grpc.Core` package when using "all" trace and "ERROR" verbosity; in a perfect world, this would be worthy of a bump there, but I do understand the current state of `Grpc.Core`, so I don't know whether that will happen without a fight; I'd like to raise a humble vote for "yay" on that: sadly, not everyone can use the managed version `grpc-dotnet` yet)

**Comment by mgravell** [comment]
darn; I've just realised that I've tagged this wrong - I think I should have selected "core"; my bad - can someone fix?

**Comment by yashykt** [comment]
Looks like you pretty much have the code ready :) Contributions are welcome

**Comment by mgravell** [comment]
@yashykt ^^^

**Comment by tomersh26** [comment]
Is there any chance you can port this fix also to Grpc.Core package where this issue was found?
The impact of these traces is significant, and the fix is pretty simple and has a very low risk.
Here is a simple benchmark test that we ran, comparing WCF vs Grpc.Core, by running 19 different queries sequentially, with a parallelism of 50 users (which is fairly low based on the size of the cluster and the SKU type) where in 3 different queries we can see a significant degradation when using Grpc.Core:

![GrpcCore_Vs_WCF](https://user-images.githubusercontent.com/8223197/195081232-2b694f8b-701b-4ae3-9982-0ec25cc05e85.png)

When running PerfView in the background, we can see that around 19% of the CPU is busy just on dump_out_append (or practically busy in parameters calculations which are passed to tracing methods that aren't going to trace anything eventually):

![dump_out_append](https://user-images.githubusercontent.com/8223197/195082359-e6f7f166-7492-41b2-9fe9-609fa4efbf26.png)

When focusing on inclusive CPU time, we see that 51% of the CPU is busy at grpc_csharp_ext.x64!grpc_core::ExecCtx::Flush.
The cost of this Flush method is split to two methods, where each one of these methods eventually calls two other methods: hexdump and asciidump:

![Flush1](https://user-images.githubusercontent.com/8223197/195082608-37bd3411-314f-485b-8da9-1580c3303155.png)

![Flush2](https://user-images.githubusercontent.com/8223197/195082714-3a6eaf97-290c-456e-b697-efb2cbccf1f9.png)

![Flush3](https://user-images.githubusercontent.com/8223197/195082723-c51b0fa1-7b30-42d7-a046-b98c3e2042df.png)

**Comment by yashykt** [comment]
@jtattermusch would be able to help you with that

**Comment by jtattermusch** [comment]
> @jtattermusch would be able to help you with that

It seems that to get the fix available in Grpc.Core (which is in maintenance mode btw), it would be enough to simply backport the fix (https://github.com/grpc/grpc/pull/31098) to the v1.46.x branch (which is the LTS branch for Grpc C# 2.46.x).
So once https://github.com/grpc/grpc/pull/31098 is merged, I'd be happy to accept a backport PR.
