### ISSUE TITLE
gRPC Ruby 1.48.0 Not Working on MACBOOK PRO M1 PRO ARM ARCHITECTURE

### ISSUE THREAD

**Issue by javierdev-pro18** [grpc/grpc#31215]
### What version of gRPC and what language are you using?
1.48.0
### What operating system (Linux, Windows,...) and version? 
Apple M1 pro
MacOS monterrey
### What runtime / compiler are you using (e.g. python version or version of gcc)
Ruby installation

### What did you do?
Please provide either 1) A unit test for reproducing the bug or 2) Specific steps for us to follow to reproduce the bug. If there’s not enough information to debug the problem, gRPC team may close the issue at their discretion. You’re welcome to re-open the issue once you have a reproduction.
- gem install grpc
- bundle install
both fails to install GRPC

### What did you expect to see?
succesfull instalation of gem

### What did you see instead?
<img width="986" alt="Captura de Pantalla 2022-10-03 a la(s) 1 11 56 p m" src="https://user-images.githubusercontent.com/114938895/193648604-c94a44d3-8516-49ad-9d59-cffbebc4431d.png">
Make sure you include information that can help us debug (full error message, exception listing, stack trace, logs).

See [TROUBLESHOOTING.md](https://github.com/grpc/grpc/blob/master/TROUBLESHOOTING.md) for how to diagnose problems better.

### Anything else we should know about your project / environment?
Problems to install GRPC in ruby on macbook pro m1 pro, when I try to run bundle install, does not find GRPC 1.48.0

**Comment by Anmol92verma** [comment]
Same problem here! Do we have any update on this ?

**Comment by javierdev-pro18** [comment]
@apolcyn please can you give us any update on this!

**Comment by tawrelkate** [comment]
Have the same problem. Any updates here?
----
1.49.0 and 1.48.0 versions
MacOS monterrey

**Comment by Anmol92verma** [comment]
worked for me with xcode 13.0 on monterey!

**Comment by ziyi-yang8** [comment]
1.49.1 and 1.48.0 are not working.  @apolcyn any updates?

**Comment by rromanchuk** [comment]
Went  backwards until I could compile, ended up at `gem 'grpc', '1.47.0'`

**Comment by yongfook** [comment]
> Went backwards until I could compile, ended up at `gem 'grpc', '1.47.0'`

Can confirm this also worked for me 👍

**Comment by asadakbar** [comment]
I was able to fix this by reinstalling Xcode 13. Upgrading to 14 is what caused this issue for me.

**Comment by monfresh** [comment]
As others have said, your best options right now are to either revert to version 1.47.0 of `grpc`, or revert to version 13.4 of the command line tools.

The issue with the latest version of `grpc` is a known issue with version 14 of the Apple Command Line Tools. You can check which version you have by running `brew config`. The good news is that this issue was fixed in the Ruby GitHub repo on October 1, but they haven't released Ruby 3.1.3 and 2.7.7 yet. 

I can confirm that I successfully installed `grpc` with Ruby 2.7 and 3.1.3 that I compiled from the Ruby repo. However, they recently introduced a bug in the 3.1 branch that causes grpc installation to fail again, but I fixed it on my local machine and I let them know.

I've written about this in lots of detail in this blog post, including step-by-step instructions for reverting to v13.4 of the command line tools:

https://www.rubyonmac.dev/how-to-install-ruby-on-macos-12-6-apple-silicon

**Comment by monfresh** [comment]
Update: What I thought was a bug in Ruby 3.1.3 was actually a bug in grpc that was hidden. The recent change in Ruby 3.1.3 was necessary, and it uncovered a bug in grpc that is fixed in this PR: https://github.com/grpc/grpc/pull/31151

I confirmed this fix by building the grpc gem locally with the changes in that PR, and I am able to install it fine with the current Ruby 3.1.3 branch. In fact, I can also install it fine in Ruby 3.1.2, so it sounds like when that fix is merged and a new grpc version is released, everything should be back to normal.
