### ISSUE TITLE
TryCancel crashes with segment fault.

### ISSUE THREAD

**Issue by springile** [grpc/grpc#31403]
### What version of gRPC and what language are you using?

1.47
### What operating system (Linux, Windows,...) and version?

CenOS 7.9
### What runtime / compiler are you using (e.g. python version or version of gcc)

gcc 7.3
### What did you do?

TEST(ServerContextTest, TryCancelTest) {
    grpc::ServerContext mock_context;

    mock_context.TryCancel();    
}

### What did you expect to see?
it should run normally.

### What did you see instead?

Segment fault.

Make sure you include information that can help us debug (full error message, exception listing, stack trace, logs).

See [TROUBLESHOOTING.md](https://github.com/grpc/grpc/blob/master/TROUBLESHOOTING.md) for how to diagnose problems better.

**Comment by springile** [comment]
![image](https://user-images.githubusercontent.com/50204931/196963082-198704b2-8200-491b-9a7b-5e337b45e361.png)
It's the callback.

**Comment by markdroth** [comment]
If you haven't actually started a call on the `ServerContext`, then doing a `TryCancel()` is not expected to work.  I don't think this is actually a bug; it's just not a correct use of the API.

**Comment by springile** [comment]
Hi Markdroth

What should be called before TryCancel is called ?

Thanks.

**Comment by markdroth** [comment]
You need to actually have the server report an incoming call first, because you can't cancel a call that doesn't exist.  The details depend on which API you're using.

For the sync API, the `ServerContext` is created for you instead of you needing to do it yourself, and it will be passed into the request handler function (see [example](https://github.com/grpc/grpc/blob/7ab2a959793304f9b039878303b023ce9e9f0079/examples/cpp/helloworld/greeter_server.cc#L43)).

For the CQ-based async API, you need to declare your own `ServerContext` for each call, which you pass into the "request" function to request an incoming call ([example](https://github.com/grpc/grpc/blob/7ab2a959793304f9b039878303b023ce9e9f0079/examples/cpp/helloworld/greeter_async_server.cc#L95)), but you can't actually cancel the call until you get back the CQ event telling you that a call has started.

For the callback-based async API, a `CallbackServerContext` is created for you and passed into the function that returns the reactor to be used for the call ([example](https://github.com/grpc/grpc/blob/7ab2a959793304f9b039878303b023ce9e9f0079/examples/cpp/helloworld/greeter_callback_server.cc#L44)), and since that function is called whenever a new call comes in, you can immediately cancel it if you want.
