### ISSUE TITLE
Non-deterministic behaviour in the server side APIs when client resets HTTP2 after partially receiving server's response

### ISSUE THREAD

**Issue by va7ish** [grpc/grpc#31745]
### What version of gRPC and what language are you using?
C++ Library version 1.46.3
### What operating system (Linux, Windows,...) and version?
Ubuntu 20.04 

### What runtime / compiler are you using (e.g. python version or version of gcc)
g++ 9.3.0
clang 12.0.0

### What did you do?

We encountered a non-deterministic behaviour in the server side APIs. The “ok” flag will be `false` (indicating failure), when the completion event for the sent response is picked up, if gRPC failed to send the trailers on the HTTP2 stream. This could happen on the service side if the client resets the HTTP2 stream before the trailers are sent. There appears to be a race condition here, and if the trailers are sent before the reset is received the "ok" for the event is set to `true`. 

### What did you expect to see?
We expect to see "ok" reliably reflecting the successful completion of the response. 

Perhaps best way to resolve this is to communicate back (in the completion event) additional information to reflect what response stages were completed successfully. 

### What did you see instead?
Non-determenistic behaviour on the status returned in the "ok" result.

**Comment by sjoerddal-pti** [comment]
I believe this also happens on 1.51.1. Noticed that `ok` is sometimes `false` when killing a client application while it's receiving a large response from a unary RPC call. I'd love to see some kind of mechanism to be able to tell  why `ok` is false and handle accordingly.

**Comment by yashykt** [comment]
A write failing means that the stream was already closed. If the client for some reason cancels the RPC (resulting in an RST_STREAM being sent on the wire), the stream will be closed, and writes will fail.

> We expect to see "ok" reliably reflecting the successful completion of the response.
I'm not sure what you mean here, since the "ok" flag is properly indicating that the write failed, meaning that the stream is already closed, and the server should not try to perform more writes.

**Comment by yashykt** [comment]
With the network being involved, there is always some amount of non-determinism involved, especially in regards to operations like cancellation. If the server completes the write before the client cancels the stream, then there is no reason for the write to fail, and on the other hand, if the stream is already closed, we would want the application to know that the write failed.

Consider a streaming RPC where the server writes at regular intervals. If a write fails, the server application would know that it does not need to continue and can end the RPC.

**Comment by yashykt** [comment]
Perhaps it might be useful to talk about the specific thing that you are trying to achieve.

**Comment by newerloo** [comment]
Thank you for your response.

I work with @va7ish and have encountered this issue repeatedly.

We are using the "ok" flag for our internal accounting on the server side. The problem seems to be that the client side is fine and consumes the response, but it closes the HTTP2 stream with a RST_STREAM. From what I could tell there seems to be a race between when the server finishes sending the trailers, and when it receives the RST_STREAM from the client. If it receives the RST_STREAM first, "ok" is false, but if it sends the trailers first, "ok" is true. In both cases the response has long been sent and consumed by the client.

I understand that we would need some form of ACK mechanism to reliably detect failure of the delivery of the response, but in this case if more information were given to the server by the library it may be able to respond differently to it. For example if instead of a bool, it was some sort of status code, the server could ignore the "RST_STREAM after sending response but before sending trailers" error if it chooses.

What I've described here is for unary RPC calls. From the service's perspective it's a single write, and then a wait for the done event.

**Comment by yashykt** [comment]
So, a few points - 
1) Why is the client closing the stream with a RST_STREAM before the server finishes sends the trailers? I think if we are able to avoid this, the entire issue goes away.
2) If there were a failure somewhere in the pipeline, it is hard for the server to know where exactly the error occurred and what information was seen by the client. Just the fact that the server was able to send trailers does not mean that it knows for sure that the client was able to receive the trailers. The same applies for the message. This raises the question - In your specific usecase, how does the server's behavior differ based on whether it saw a RST_STREAM before sending the trailers or after?

**Comment by newerloo** [comment]
Thank you for your reply @yashykt.

1. The client is the envoy implementation of gRPC. I guess we could look into whether that behaviour can be controlled by the application.
2. I understand that there's no guarantee. In my previous message I was referring to an "ACK mechanism" that would need to be added at the application layer or something like that. However, in this case the gRPC implementation is differentiating between the two cases, and telling us it failed using the "ok" flag. I did not investigate the difference in behaviour between the "RST_STREAM frame" being received case, and the "END_STREAM flag" being received case.

In our case we were originally using it to track "success" of replies. And, yes, as we've said before it's not guaranteed, but it gives us a good approximation. We essentially count the two cases, but when observing the counters, we ignore the failure cases because we're seeing that the vast majority of them are a result of this race between trailers and RST_STREAM. So in our particular case, if we were being told by the library about the RST_STREAM being received after the response is sent but before the trailers are sent, we'd be left with a more accurate count of the "real" failures.

**Comment by yashykt** [comment]
I think I am currently on the side that says that it makes the most sense for this kind of observability to happen on the client side, and on the client-side, you would usually see this in the status.

The server-side is best effort as we have talked about, and we could use https://github.com/grpc/grpc/blob/7b3977e9f13721a47d126a0a2399ca177f934d89/include/grpcpp/server_context.h#L197 to check if an RPC was cancelled. I do think we should try to figure out why the client is cancelling the RPC.

I am going to close the issue, but if you think there might be something more we can do here, we could maybe schedule a meeting.
