### ISSUE TITLE
cmake config step fails when building version 1.51.0 from source

### ISSUE THREAD

**Issue by donnachaforde** [grpc/grpc#31760]
## Environment
Version: gRPC C++ 1.51.0
Operating System: macOS monterey
Tools/Compiler: cmake version 3.25.0, clang version 14.0.0

## Issue
The `thirdparty/cares/cares` directory is empty in the source code (tar.gz) distribution.

## Detail

I downloaded the source code tar.gz file for the 1.51.0 release from [here](https://github.com/grpc/grpc/releases/tag/v1.51.0) but the first build step - i.e. `cmake` configuration - fails because the `thirdparty/cares/cares` is empty and doesn't contain a `CMakeLists.txt` file. 

Here's the build output:
```
CMake Error at cmake/cares.cmake:25 (add_subdirectory):
  The source directory

    /src/grpc-1.51.0/third_party/cares/cares

  does not contain a CMakeLists.txt file.
Call Stack (most recent call first):
  CMakeLists.txt:321 (include)
```

And, that directory is indeed empty. Perhaps the tar gzip'd file didn't pick up this directory?

### What version of gRPC and what language are you using?

gRPC 1.51.0 / C++

### What operating system (Linux, Windows,...) and version?

macOS

21.6.0 Darwin Kernel Version 

### What runtime / compiler are you using (e.g. python version or version of gcc)

cmake version 3.25.0
clang version 14.0.0

### What did you do?
I followed the build instructions, created a subdirectory called 'build' under the 'cmake' directory. Ran `cmake ../..`

### What did you expect to see?

cmake configuration run to completion.

### What did you see instead?

```
CMake Error at cmake/cares.cmake:25 (add_subdirectory):
  The source directory

    /src/grpc-1.51.0/third_party/cares/cares

  does not contain a CMakeLists.txt file.
Call Stack (most recent call first):
  CMakeLists.txt:321 (include)
```

Make sure you include information that can help us debug (full error message, exception listing, stack trace, logs).

See [TROUBLESHOOTING.md](https://github.com/grpc/grpc/blob/master/TROUBLESHOOTING.md) for how to diagnose problems better.

### Anything else we should know about your project / environment?

The 'thirdparty/cares/cares` directory is empty in the tarball distribution. So is version 1.49.1 though earlier version ~1.3.x has a populated directory and includes a CMakeLists.txt file.

**Comment by Japan50079** [comment]
Donnacha Forde ***@***.***>于令和4年11月25日周五22:06写道：

**Comment by veblush** [comment]
I think you missed to run `git submodule update --init`. You may want to read [BUILDING](https://github.com/grpc/grpc/blob/master/BUILDING.md) for further information.

**Comment by donnachaforde** [comment]
Thanks for looking at this. Please note that the `git submodule update --init` fails because it's not a git repo - I unpacked the tarball from the Release page. 
```
fatal: not a git repository (or any of the parent directories): .git
```

Perhaps I'm mis-understanding and you can only successfully build from a `git clone`?

**Comment by jtattermusch** [comment]
> Thanks for looking at this. Please note that the `git submodule update --init` fails because it's not a git repo - I unpacked the tarball from the Release page.
> 
> ```
> fatal: not a git repository (or any of the parent directories): .git
> ```
> 
> Perhaps I'm mis-understanding and you can only successfully build from a `git clone`?

You should be able to build with the tar.gz release archive, but you need to set cmake's `gRPC_*_PROVIDER=package` if you don't want use the git submodules.

See https://github.com/grpc/grpc/blob/31fc452b68e429c029f00b5fcc54292a303be0c6/test/distrib/cpp/run_distrib_test_cmake.sh#L70-L81

**Comment by pavel-odintsov** [comment]
Hello!

I believe I hit exactly same issue and spent quite a lot of time to find out that official tar.gz package even for latest versions of gRPC has mostly empty third_party folder. 

I've tried my best to find way to pull git modules from folder which is not git repo and failed same way as @donnachaforde 

@jtattermusch thank you for your recommendation to use modules. 

Unfortunately, I do not think that this advice can be applied in all cases. 

For some dependencies it does make sense. For example I prefer link with external OpenSSL as we use it from many apps but I do not observe other apps / components using ABSL or CARES and I just want to use version supplied in third_party folder.

Even if I want to link with custom built ABSL and CARES what is the recommended version? Git repos has such information as commits but tar.gz clearly misses it.

tar.gz or zip offer great capability to make cryptographic checksum validation to confirm that it did not change since last check / review but git does not offer reliable ways to confirm that library is genuine

Supply chain attacks are one of the most common vectors and I find lack of options to compile gRPC without pulling dependencies from git quite frustrating. 

May I kindly request to review my feedback?

Would be really great to have external dependencies in third_party folder in same archive or separate archive published for new releases.

Thank you!

**Comment by flyflyhe** [comment]
mark
