### ISSUE TITLE
Unable to install/build older grpc versions on python 3.11

### ISSUE THREAD

**Issue by jkgenser** [grpc/grpc#31934]
### What version of gRPC and what language are you using?
grpcio>=1.37.0,<1.49

### What operating system (Linux, Windows,...) and version?
Linux

### What runtime / compiler are you using (e.g. python version or version of gcc)
N/A

### What did you do?
Attempt to install grpcio>=1.37.0,<1.49 on python 3.11

### What did you expect to see?
Be able to build with gcc/build-essentials or ideally download a wheel from pypi

### What did you see instead?
Unable to build and no wheel available to install

In particular, the ability to install a grpcio wheel for python 3.11 for slightly older but still very actively used (and officially supported) versions of grpcio.

Make sure you include information that can help us debug (full error message, exception listing, stack trace, logs).

See [TROUBLESHOOTING.md](https://github.com/grpc/grpc/blob/master/TROUBLESHOOTING.md) for how to diagnose problems better.

### Anything else we should know about your project / environment?
python3.11

**Comment by XuanWang-Amos** [comment]
Hi, can you specify what command you ran and what's the error you're seeing?
And also, if normal `pip install` failed, you can also try [install from source](https://github.com/grpc/grpc/tree/master/src/python/grpcio#installing-from-source).

**Comment by jkgenser** [comment]
> Hi, can you specify what command you ran and what's the error you're seeing? And also, if normal `pip install` failed, you can also try [install from source](https://github.com/grpc/grpc/tree/master/src/python/grpcio#installing-from-source).

My goal is to help the dapr project update their grpcio version under python 3.11. In the link below you can see the log for the failure to build the wheels under the `Run Linter` section of the `build (3.11) step.

The github workflow linked below is able to use the same environment to build multiple python versions but fails to build 3.11 using the same command.

@XuanWang-Amos : Does this help?

https://github.com/dapr/python-sdk/actions/runs/3414054158/jobs/5681502895

**Comment by gnossen** [comment]
@jkgenser I'm more inclined to fix the underlying issue that keeps these projects from updating. https://github.com/grpc/grpc/issues/28513 fell off my radar, but I'm actively looking at it now. If necessary, I will backport the fix to older branches.

In general, we don't want to expand Python interpreter version support in old version of gRPC unless we absolutely have to.

**Comment by jkgenser** [comment]
> @jkgenser I'm more inclined to fix the underlying issue that keeps these projects from updating. #28513 fell off my radar, but I'm actively looking at it now. If necessary, I will backport the fix to older branches.
> 
> In general, we don't want to expand Python interpreter version support in old version of gRPC unless we absolutely have to.

@gnossen, the issue linked prevents this project from building python wheels for older grpc versions?

**Comment by gnossen** [comment]
No, the issue linked is (based on some digging)( why the project pinned to an older version of gRPC to begin with.

The reason why old versions of gRPC aren't building with Python 3.11 seems to be simply that their version pin of Cython hasn't been updated.

**Comment by berndverst** [comment]
Hi folks -- I'm one of the maintainers of Dapr (a CNCF incubated project) and among other things maintain its Python SDK.

## Background

The dilemma we are facing is this:

1. `protobuf` introduced a major breaking change between versions which requires protos to be regenerated with newer versions of `protoc`.
2. Newer versions of `grpcio` (from 1.49 onwards) require the version of `protobuf` with this breaking change in `protobuf`.
3. Updating `grpcio` in my (`dapr`) Python SDK forces the breaking change in (1) onto users, which in many ML libraries (e.g. Nvidia Triton inferencing client / runtime, and others) is expressly marked as incompatible.

## The problem

As a result I had to pin `grpcio` to `<1.49`. The highest version I successfully tested was `grpcio==1.48.2`.

This works great, but compiling `1.48.2` for Python 3.11 is impossible. The only way I could manage to do this is by checking out the grpcio source code and manually compiling several of the dependencies with all kinds of compiler flags. Not something a Python 3.11 user running `pip3 install dapr` can or would do.

I struggled to compile this on M1 Mac and on Ubuntu (amd64) by the way.

## My request

For the sake of many many projects affected by this, please provide wheels for Python 3.11 for `grpcio==1.48.2`.

As you can imagine, as the SDK maintainer of a cloud native / distributed microservices framework it is very unreasonable for me to contact and work with every possible ML library maintainer out there which may be used by the cloud native community. I too am swamped as a OSS maintainer as is :)

**Comment by berndverst** [comment]
@gnossen I am not requesting any ongoing patches for 1.48.X - just precompiled wheels for Python 3.11 1.48.2 due to the protobuf breaking change. This would help immensely!

Sadly as a Python SDK maintainer, `grpcio` is the one library that causes me the most headaches :(

**Comment by gnossen** [comment]
@berndverst Thank you very much for the context.

> protobuf introduced a major breaking change between versions which requires protos to be regenerated with newer versions of protoc.

Yes. Unfortunate.

> Newer versions of grpcio (from 1.49 onwards) require the version of protobuf with this breaking change in protobuf.

I don't think that's right. `grpcio` itself has no dependency on protobuf. Only `grpcio-tools` does, which generates the `_pb2_grpc.py` files. The API surface of `grpcio` is backward-compatible. If we ever made a breaking change, it would be as a 2.X. I think you could use `grpcio-tools==1.48.2` with `protobuf==3.20.3` the latest version of `grpcio` without any issues.

> As a result I had to pin grpcio to <1.49. The highest version I successfully tested was grpcio==1.48.2.

Was there an issue with versions greater than 1.48.2? If so, would you be willing to give any more information on it?

> Updating grpcio in my (dapr) Python SDK forces the breaking change in (1) onto users, which in many ML libraries (e.g. Nvidia Triton inferencing client / runtime, and others) is expressly marked as incompatible.

I believe this is due to [this issue](https://github.com/grpc/grpc/issues/28513), which I'm currently trying to resolve so Triton can unpin.

> I struggled to compile this on M1 Mac and on Ubuntu (amd64) by the way.

We just recently started building universal2 wheels, so there shouldn't be a need to compile that from source going forward.

> As you can imagine, as the SDK maintainer of a cloud native / distributed microservices framework it is very unreasonable for me to contact and work with every possible ML library maintainer out there which may be used by the cloud native community. I too am swamped as a OSS maintainer as is :)

I understand and can totally relate.

> I am not requesting any ongoing patches for 1.48.X - just precompiled wheels for Python 3.11 1.48.2 due to the protobuf breaking change. This would help immensely!

This seems reasonable to me. We can backport the Cython bump to enable 3.11 builds as well as the change to publish M1-compatible universal2 wheels.

My concern though is that people may never update. In which case, 1.48 would become a long-running fork akin to Python 2.7.  But I understand that's not something you're in control of. What I would appreciate though is a list of all libraries you're aware of who currently have a pin so I can try to contact them myself and resolve the issue.

> Sadly as a Python SDK maintainer, grpcio is the one library that causes me the most headaches :(

I'm sad to hear that and would like to do what I can to address your issues. If you'd be willing, I'd love to do [a short video call](https://grpc.io/meet/) to hear what's been the most difficult for you. If not, an email would probably be just as good.

**Comment by berndverst** [comment]
@jkgenser this might be the answer I needed. For some reason I thought I needed `grpcio-tools` and `grpcio` to be on the same version.

Yes my apologies - `grpcio-tools` is the culprit requiring the new `protobuf`. Let me take a look to see whether bumping just `grpcio-tools`.

I vaguely remember something that `grpcio-tools` required me to use a newer version of protoc, or the protos generated using it themselves were only compatible with a newer version of `protobuf` which put me into this dependency hell. I don't know whether that is accurate -- I'll have to give this another try in a bit.

With our last SDK release I had to make several hotfix releases because I used newer versions of `grpcio-tools` which then forced newer `protobuf` and that causes all kinds of pains for users wanting to use our SDK with other SDKs.

As for the video call - I don't think it's really necessary. I don't have a problem using the grpc library, but I must support Python 3.7 through Python 3.11 on everything from Windows to  M1/M2 Mac. I often often been in a position where `grpcio` wheels didn't exist for my platform / OS / Python version combo, and compiling grpcio has been tricky -- especially on M1 Mac I ran into all kinds of problems, after every XCode or MacOS update it seems.

The best thing that can be done to avoid all these problems is to provide wheels quickly after new Python releases are out or significant OS updates comes out.

**Comment by berndverst** [comment]
I am only directly aware of this project having a protobuf / grpc version conflict:
https://github.com/triton-inference-server/

Though I am told that there are many other ML libraries.

**Comment by berndverst** [comment]
Probably the best candidates for projects that might be impacted - though it would be a bit of work to see which actually use `grpcio`:

protobuf<3.20.X:
https://github.com/search?q=%22protobuf%3C3.20%22&type=code

protobuf<4.X.X
https://github.com/search?q=%22protobuf%3C4%22&type=code

**Comment by berndverst** [comment]
Looks like tensorflow pins `protobuf 3.19.3` and `grpcio 1.49.1`, so as long as I can indeed stay on `grpcio-tools 1.48.2` I should be good here.

**Comment by gnossen** [comment]
>  I thought I needed grpcio-tools and grpcio to be on the same version.

This is standard practice, but in reality, the only think you'd potentially lose out on by pinning `grpcio-tools` is access to _new_ features that are only accessible via a generated code API.

> The best thing that can be done to avoid all these problems is to provide wheels quickly after new Python releases are out or significant OS updates comes out.

Agreed. We release new Python versions _before_ the final CPython release is cut, but only at the latest version of `grpcio`.

As for OS support, I think our arm64 MacOS support came pretty late. This was due to a combination of an underestimate for the demand, CI inflexibility, and an unlucky bug in the Python standard library. But transitions like this are once-in-a-decade, so I don't anticipate that being a recurring problem.

> I am only directly aware of this project having a protobuf / grpc version conflict:
https://github.com/triton-inference-server/

Yes. I'm trying to get Triton unstuck at the moment.

> Looks like tensorflow pins protobuf 3.19.3 and grpcio 1.49.1

Thanks for the pointer. I'll try to reach out to them as well.


It sounds like your immediate problem has been resolved, so I'm going to close this issue out. Please feel free to comment if there are any issues and I'll reopen.

**Comment by berndverst** [comment]
Thanks @gnossen. Much appreciated, and thanks for the quick responses!
