### ISSUE TITLE
gRPC PyPI project description

### ISSUE THREAD

**Issue by chinmaychahar** [grpc/grpc#31976]
The [PyPI](https://pypi.org/project/grpc/) project page of gRPC provides no description of the project as well as the latest release versions. This should ideally be fixed

**Comment by XuanWang-Amos** [comment]
This is actually not the 'real' gPRC project, you should use `grpcio` instead.

To add more context, we (gRPC team) don't own this project at the beginning, that's why we created `grpcio` package in pypy, after we manage to own this project, the main purpose of it is just telling people they should install `grpcio` instead (like we mentioned in title: `Please install the official package with: pip install grpcio`).
