### ISSUE TITLE
how to build grpc use openssl in bazel

### ISSUE THREAD

**Issue by xiedeacc** [grpc/grpc#32113]
my project use bazel, and import grpc and brpc as  dependency, for some reason, brpc must use openssl, but grpc use boringssl default, so link will failed for duplicate symbols, so how to compile grpc use openssl in bazel? or can make boringssl only visible to grpc?

**Comment by jtattermusch** [comment]
When using bazel, you can only use boringssl, since AFAIK openssl doesn't have any bazel support. 
If you somehow got openssl to support bazel, you could simply remove boringssl from grpc's bazel dependencies and use openssl instead (AFAIK in principle grpc is buildable against openssl just fine) - but at that point you're modifying the grpc build, which means you need to find solutions for issues that come up.

Alternatively, you can build grpc against openssl with cmake (and skip boringssl altogether), you can find an example here:
https://github.com/grpc/grpc/blob/3e70a163e2162673bf7116a620b3bda7d83393a3/test/distrib/cpp/run_distrib_test_cmake_pkgconfig.sh#L21
https://github.com/grpc/grpc/blob/3e70a163e2162673bf7116a620b3bda7d83393a3/test/distrib/cpp/run_distrib_test_cmake_pkgconfig.sh#L85
