### ISSUE TITLE
Add support to ppc64le architecture in grpc.tools 

### ISSUE THREAD

**Issue by Sapana-Khemkar** [grpc/grpc#32522]
.NET7 includes support for Linux on Power (ppc64le) and Power customers would like to have GRPC C# plugin supported on Power. Hence would like to have ppc64le support in grpc.tools.

We have started working on it and would like to have feedback/comments from community.

**Comment by tonydnewell** [comment]
@Sapana-Khemkar we don't directly support ppc64le as we don't have access to PPC machines so cannot build and test to provide the `protoc` and` grpc_csharp_plugin` binaries for ppc64le.

You can still use the MSBuild integration provided by Grpc.Tools for other architectures if you are able to provide your own binaries and then define a couple of environment variables so that Grpc.Tools knows where to find them.

For example,
```bash
# install or build binaries for your architecture
# e.g. for grpc-plugins package to get tools built for Alpine linux
#        See https://pkgs.alpinelinux.org/package/edge/community/ppc64le/grpc-plugins
apk add grpc-plugins

# set environment variables for the tools
export PROTOBUF_PROTOC=/usr/bin/protoc
export GRPC_PROTOC_PLUGIN=/usr/bin/grpc_csharp_plugin

# do the .NET build
dotnet build
```

**Comment by Amit-Sirohi** [comment]
@tonydnewell We have tried this by installing protoc and grpc_csharp_plugin using below commands 
apt install -y protobuf-compiler
apt-get install protobuf-compiler-grpc

and then set environment variables for protoc and grpc_csharp_plugin
export PROTOBUF_PROTOC=/usr/bin/protoc
export gRPC_PluginFullPath=/usr/bin/grpc_csharp_plugin

dotnet build 

Get error related to channel namespace 
error CS0234: The type or namespace name 'Channel' does not exist in the namespace 'Grpc.Core' (are you missing an assembly reference?)

So we moved to build Grpc repo to get binaries of protoc and grpc_csharp_plugin for ppc64le. Done the changes related to power architecture and change the target framework to Net7.0.
As Net7.0 is supported on ppc64le. Created a Grpc.Tools nuget package and use it on ppc64le.
I will raise draft PR soon for comments. Also do you have any plan to move to .NET7?

**Comment by Amit-Sirohi** [comment]
@tonydnewell We have tried this by installing protoc and grpc_csharp_plugin using below commands 
apt install -y protobuf-compiler
apt-get install protobuf-compiler-grpc

and then set environment variables for protoc and grpc_csharp_plugin
export PROTOBUF_PROTOC=/usr/bin/protoc
export gRPC_PluginFullPath=/usr/bin/grpc_csharp_plugin

dotnet build 

Get error related to channel namespace 
error CS0234: The type or namespace name 'Channel' does not exist in the namespace 'Grpc.Core' (are you missing an assembly reference?)

So we moved to build Grpc repo to get binaries of protoc and grpc_csharp_plugin for ppc64le. Done the changes related to power architecture and change the target framework to Net7.0.
As Net7.0 is supported on ppc64le. Created a Grpc.Tools nuget package and use it on ppc64le.
I will raise draft PR soon for comments. Also do you have any plan to move to .NET7?

**Comment by tonydnewell** [comment]
@Amit-Sirohi I think your error is not related to `Grpc.Tools`, but to `Grpc.Core` not supporting ppc64le.

 `Grpc.Core`  is the C# version of gRPC that is built on top of the gRPC c-core library and that library does not support ppc64le. `Grpc.Core` is in maintenance mode - see https://github.com/grpc/grpc/blob/master/src/csharp/README.md

You should use the gRPC-dotnet instead - https://github.com/grpc/grpc-dotnet which is a pure .NET implementation of gRPC for C#.

**Comment by tonydnewell** [comment]
@Amit-Sirohi `Grpc.Tools` does live in the Grpc/Grpc repository but it is not dependent on `Grpc.Core.` It may move to the Grpc-dotnet repository sometime.

The workaround in https://github.com/grpc/grpc/issues/32522#issuecomment-1455909819 does work and the error that you are seeing in https://github.com/grpc/grpc/issues/32522#issuecomment-1456146632 :
  _error CS0234: The type or namespace name 'Channel' does not exist in the namespace 'Grpc.Core' (are you missing an assembly reference?)_ )
is not because of `Grpc.Tools` but because your project file is using `Grpc.Core`. Either you are including unnecessary NuGet packages in your build file or you are still using _grpc-core_ rather than _grpc-dotnet_ in your code.  If possible give an extract from your project file showing the NuGet packages.

**Comment by Amit-Sirohi** [comment]
@tonydnewell We have try to build Greeter example on ppc64le architecture. Its source code is available [here ](https://github.com/grpc/grpc-dotnet/tree/master/examples/Greeter)

In [Client.csproj](https://github.com/grpc/grpc-dotnet/blob/master/examples/Greeter/Client/Client.csproj)and [Server.csproj](https://github.com/grpc/grpc-dotnet/blob/master/examples/Greeter/Server/Server.csproj) it does not use Grpc.Core package directly. But I have found in one of the file it used Grpc.Core https://github.com/grpc/grpc-dotnet/blob/master/examples/Greeter/Server/Services/GreeterService.cs#L21

In Client.csproj it uses Grpc.Tools package and it is not available for ppc64le. So we build Grpc on ppc64le and generated a Grpc.Tools nuget package for ppc64le. By using this Grpc.Tools local nuget package we have successfully build Greeter example on ppc64le.
      
In a similar way we need to build aspnetcore (https://github.com/dotnet/aspnetcore) on ppc64le and it need Grpc.Tools nuget package internally which is mentioned [here ](https://github.com/dotnet/aspnetcore/blob/main/eng/Versions.props#L265.)

So this is the reason we need to generate Grpc.Tools nuget package for ppc64le architecture.

**Comment by jtattermusch** [comment]
> @tonydnewell We have try to build Greeter example on ppc64le architecture. Its source code is available [here ](https://github.com/grpc/grpc-dotnet/tree/master/examples/Greeter) In [Client.csproj](https://github.com/grpc/grpc-dotnet/blob/master/examples/Greeter/Client/Client.csproj)and [Server.csproj](https://github.com/grpc/grpc-dotnet/blob/master/examples/Greeter/Server/Server.csproj) it does not use Grpc.Core package directly. But I have found in one of the file it used Grpc.Core https://github.com/grpc/grpc-dotnet/blob/master/examples/Greeter/Server/Services/GreeterService.cs#L21
>

That's actually a misconception. The grpc-dotnet doesn't use Grpc.Core, it simply imports the namespace that contains the shared API layer used by both grpc-dotnet and Grpc.Core. The shared API layer is in the Grpc.Core.Api nuget package and unlike Grpc.Core it doesn't have any native dependency, so depending on Grpc.Core.Api (which grpc-dotnet does) isn't really a problem on any platform and works everywhere.
 
> In [Client.csproj](https://github.com/grpc/grpc-dotnet/blob/master/examples/Greeter/Client/Client.csproj) it uses Grpc.Tools package and it is not available for ppc64le. So we build Grpc on ppc64le and generated a Grpc.Tools nuget package for ppc64le. By using this Grpc.Tools local nuget package we have successfully build Greeter example on ppc64le.
> 
> In a similar way we need to build aspnetcore (https://github.com/dotnet/aspnetcore) on ppc64le and it need Grpc.Tools nuget package internally which is mentioned [here ](https://github.com/dotnet/aspnetcore/blob/main/eng/Versions.props#L265.)
> 
> So this is the reason we need to generate Grpc.Tools nuget package for ppc64le architecture.

As explained above, we don't have access to ppc64le hardware and we don't have any integration for it in our CI, at which point adding any support for it is basically impossible (since we can't ship stuff we can't test). That includes shipping Grpc.Tools with pre-build ppc64 codgen binaries.
That said, there is a workaround mentioned above (to provide your own `protoc` and `grpc_csharp_ext` binaries built on ppc64) - which really should work, the errors you are mentioning seem unrelated and probably an example of you including Grpc.Core somewhere by mistake.
