### ISSUE TITLE
grpcio dependency definition for grpcio-status

### ISSUE THREAD

**Issue by eavelardev** [grpc/grpc#32601]
### What version of gRPC and what language are you using?
`grpcio==1.48.2` python

### What operating system (Linux, Windows,...) and version?
Ubuntu 22.04

### What runtime / compiler are you using (e.g. python version or version of gcc)
python 3.10

### What did you do?
I had a conflict of dependencies with the most recent version of `grpcio-status` because it uses `protobuf>=4.21.6` so I decided to downgrade to `grpcio-status<1.49`. But I noticed that `grpcio` that is a dependency of `grpcio-status`, doesn't downgrade a the same version, this keeps the latest because [`grpcio>={version}`](https://github.com/grpc/grpc/blob/v1.51.3/src/python/grpcio_status/setup.py#L67). My doubt is if this doesn't generate incompatibility between the libraries, because let's say, I could install the oldest version of `grpcio-status` and `grpcio` remains the same.

### What did you expect to see?
`grpcio` version == `grpcio-status` version when `grpcio-status` is downgraded

### What did you see instead?
`grpcio` remains the same and I don't know if this could generate incompatibility.

My proposal is defining `grpcio=={version}` or if the difference of versions doesn't generate an issue just forget what I said.

**Comment by gnossen** [comment]
It is safest to have the version of `grpcio` match the version of `grpcio-status`, but in practice, there shouldn't be any issue with the two versions differing because `grpcio-status` only uses public APIs of `grpcio` and `grpcio` does not break backwards compatibility. Note also that `grpcio` itself does not have a dependency on `protobuf`. Only the generated code (i.e `_pb2_grpc.py` files) has this dependency.

**Comment by XuanWang-Amos** [comment]
Closing this issue, please let us know if you need any further help.
