### ISSUE TITLE
Please continue to support grpc.core because there is no alternative for Windows 10 using the NET Framework

### ISSUE THREAD

**Issue by chuchu** [grpc/grpc#32719]
As documented [here](https://grpc.io/blog/grpc-csharp-future/) Grpc.Core will be EOL in May 2023. For clients the proposed replacement is Grpc.Net.Client which supports .NET Core and .NET Framework.

Unfortunately Grpc.Net.Client does not support HTTP/2 on Windows 10 with the NET Framework. As documented [here](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/grpc/netstandard.md) only Windows 11 is supported. 
For hosting gRPC services in NET Framework there is no alternative at all.

**This means that there is no real replacement Grpc.Core.**

Windows 10 is widely used and is supported until October 2025 according to [here](https://learn.microsoft.com/en-us/lifecycle/products/windows-10-home-and-pro). We (and most likely other) have a big .NET Framework code base. 

We have considered gRPC has a kind of bridge technology between the legacy .NET Framework stuff and new .NET Core Services. In the past we have used a lot of WCF but this is deprecated as well. If gRPC cannot be used on Windows 10 with the NET ecosystem one can use REST and Web Sockets internally. For services from external parties which come with gRPC only, this is not possible. Grpc-web can only be used when the server supports it. This is not always the case.

Please continue to support grpc.core as long as Windows 10 us supported.

### What version of gRPC and what language are you using?
Using the C# version of Grpc with Grpc.Core 2.44.0

### What operating system (Linux, Windows,...) and version?
Windows 10 21H2
Windows Server 2019

### What runtime / compiler are you using (e.g. python version or version of gcc)
msbuild 17.2.1.25201

### What did you do?
n/a

### What did you expect to see?
A live time of grpc.core which is aligned with Windows 10.

### What did you see instead?
Grpc.core is EOL without real alternative.

### Anything else we should know about your project / environment?
I already created a [ticket](https://github.com/dotnet/core/issues/8094) in the dot net core repo which was closed.

**Comment by zaphodstardust** [comment]
I agree, there are more software projects that (still) have the same needs.

e.g. WCF is used in project based on .NET Framework. 
The transition to modern .NET shall be done to move the project out of obsolescence zone. 
One of the best alternatives to WCF for a migration path is Grpc (for many scenarios, and in many aspects also superior).
So, it is very sensible to remove WCF and use Grpc.Core while still being on .NET Framework to remove roadblock after roadblock for migration to modern .NET.
I know that the decision for maintenance and deprecation (since May 2023) of Grpc.Core has been explained and I understand the drivers from an OSS project maintenance (overhead) and technical point of view.
In my project, however, I have no valid Grpc path available and need to use alternative technologies and software stacks like plain Websockets or Rest (which fit less and have limitations compared to grpc).

@jtattermusch Maybe if you could spend the time, I had a question on google groups (https://groups.google.com/g/grpc-io/c/OTj5mb1qzb0): I understand, that now the "maintenance mode" of Grpc.Core is over.
That means Grpc.Core is now officially deprecated, correct?
What are the rules / support policies that apply now?
-> No fixes (even for security) anymore (besides contributed by OSS community, but no maintainer for releases)?
Thanks for clarifying!

**Comment by jtattermusch** [comment]
While I appreciate the popularity of Grpc.Core and I'm sure extended support would be welcome by some users, we also need to be realistic.
- At this point, users have been given 2+ years notice of planned deprecation (and we already extended the support in 2022). Continuing official support of Grpc.Core has its costs and we cannot continue extending the support forever. I agree there's some logic in continuing support until EOL of Windows 10, but you could use the same logic to demand continued support until .NET Framework 4.8 is EOL (and AFAIK .NET Framework 4.8.1 won't be EOL in the next 4 years and very possibly for even much longer), so we have to draw a line somewhere.
- Grpc.Core has been living on 1.46.x LTS branch of C-core repository for the past year and as such, performing maintenance gets harder as time passes (as the gap between C-core development head and Grpc.Core increases).
- By declaring Grpc.Core deprecated, we're not preventing people from using Grpc.Core "with immediate effect" but it will probably take quite some time before it becomes actually unusable. The nuget packages will stay where there are and will continue to be usable by everyone. In the past we've had pretty good track record with only requiring critical and security fixes very rarely (and even more rarely, if ever, for subsets of functionality such as gRPC C# client), so it seems fair to expect that Grpc.Core will remain usable (without cutting corners in terms of security) for perhaps a few more years. It just won't have the official stamp of being actively maintained by the gRPC team. That might not work for some users (as with any policy change), but it will likely be just fine for many others and unfortunately this is just the risk of being on an outdated stack.

Regarding the question of what's the current status of Grpc.Core (maintained/deprecated):
- as you pointed out the official maintenance period has technically ended in May 2023, but we haven't officially confirmed that Grpc.Core is deprecated now.  So yes, we are currently in some kind of intermediate state where we're evaluating usage numbers (at least the ones we have access to) and migration options before we finally declare Grpc.Core deprecation as official.
- So in practice, Grpc.Core is still "maintained", but it might get declared deprecated any day now, without any extra notice. There's still some small chance that we'll reconsider (based on the data available to us) and continue supporting Grpc.Core for some more time, but AFAICT this seem unlikely and I definitely wouldn't count on it.

Hope this makes sense.

One more question is about Windows 10:
- since Grpc.Net.Client works fine on .NET Framework on Windows 11, what prevents your .NET Framework applications from migrating to Windows 11? It seems that if your applications is tightly bound to .NET Framework (to an extent that you can't migrate to .NET5+), the act of migrating from Windows 10 to Windows 11 would be a much simpler migration path, given that Windows 11 supports Grpc.Net.Client. (and Windows 11 still support .NET Framework so I don't see why your existing apps won't run there).

**Comment by jtattermusch** [comment]
@chuchu  regardless of my previous post, I'd be curious to know what your .NET Framework stack looks like at what are the current challenges 1) migrating to windows 11  2) migrating to .NET5+ 3.) what role does Grpc.Core vs grpc-dotnet play in all that. If you don't mind sharing more insights, feel free to send them privately via email (my @google.com email address can be found in the git commit log in this repo).

**Comment by jtattermusch** [comment]
Since this thread isn't an "issue" but rather a question, I'm going to close this as per rules for this repository.

**Comment by Onkelborg** [comment]
On the topic of not working on Windows 10 - I've been part of a project to migrate away from .NET framework to Core for a very complex product, and replacing Remoting with gRPC was the first step. I know that additional work has been done since I left, migrating one of the services with not that many external dependencies. However, it's a product used by network administrators, even partially delegated - and Windows 11 is not that common, especially since there are not that many computers that actually comply with the rather high hardware requirements for Windows 11.

**Comment by Falco20019** [comment]
We as a company have the same issue. Migrating to Windows 11 is not possible, since our customers are defining what devices they use to run our software on and limiting it to Windows 11 would (right now) still be an issue leading to the software not being bought by the customer. We are in a field where a lot of embedded devices were used.

The second issue we still have is the missing support for Android (due to ASP.NET Core Framework not being available) which is discussed at https://github.com/dotnet/aspnetcore/issues/35077 where @JamesNK is currently looking into options.

**Comment by jtattermusch** [comment]
Please see the latest [update on Grpc.Core deprecation](https://groups.google.com/g/grpc-io/c/iEalUhV4VrU)

**Comment by chuchu** [comment]
Hi @jtattermusch, 
Thank you very much for extending the maintenance mode! Is there meanwhile an update on the grpc.core deprecation time line? You mention the “support of one of the legacy platforms (e.g. Windows 10 goes EOL)”. I fear the legacy OS platforms is not the problem, but the runtime is. Even with Windows Server 2022 there is no feature parity in grpc.net.client. When the .NET Framework is used, client and bidirectional streaming is not supported. See [here](https://learn.microsoft.com/en-us/aspnet/core/grpc/netstandard?view=aspnetcore-8.0#net-framework).

Companies might have a big .NET Framework code base which is slowly moved to net core or other frameworks. Until this is done (and afterwards 😊) gRPC is a great solution for bridging the worlds. I think we may need grpc.core as longs as the .NET Framework is supported or when grpc.net.client has really reached feature parity.
