### ISSUE TITLE
Client disconnect from asynchronous bidirectional streaming server

### ISSUE THREAD

**Issue by aneurysm02** [grpc/grpc#32943]
Hi,
I experienced a problem described in another (old) issue https://github.com/grpc/grpc/issues/16234.
I have a python gRPC client and i try to communicate using bidirectional streaming with C++ gRPC server. 
I call code below:
```
async def login(mcptt_client_address):
    async with grpc.aio.insecure_channel(target=mcptt_client_address) as client_channel:
        stub = ClientOperations_pb2_grpc.McpttClientServiceApiStub(channel=client_channel)
        async for server_reply in stub.serviceRequest(login_generator()):
            print(server_reply)
```
```
async def login_generator():
    init_request = ClientOperations_pb2.McpttRequest(initRequest=Mcpttclient_pb2.InitRequest(
        config=setup.CONFIG,
        requestId=str(uuid.uuid4())))
    yield init_request
    login_request = ClientOperations_pb2.McpttRequest(login=ClientOperations_pb2.LoginRequest())
    yield login_request
```
After sending `login_request` i should receive many messages with _stage: PRS_Progress_ and wait for _Success_ message. It last about 100ms, but python client disconneting after few _Progress_ messages (not all _Progress_ messages and _Success_ one can be received). I attached some log from this event:
[grpc_python_issue.log](https://github.com/grpc/grpc/files/11332369/grpc_python_issue.log)

**Comment by XuanWang-Amos** [comment]
Hi, from the logs I saw that client send `SEND_CLOSE_FROM_CLIENT` operation which means client closed the connection on purpose.

In Aio, client will call `_done_writing` and send close operation after exhausted the request iterator so it's expected behavior if you only have two `yield` in `login_generator`: https://github.com/grpc/grpc/blob/master/src/python/grpcio/grpc/aio/_call.py#L414,L424

If you want to keep the connection open, one thing to try is keep the iterator until you received a success message from the server.

**Comment by aneurysm02** [comment]
Thanks for answer. 
I'll try the suggested solution - keep iterator as long as i receive success messgae.
