### ISSUE TITLE
Feature request C#: include headers in SerializationContext\DeserializationContext

### ISSUE THREAD

**Issue by osexpert** [grpc/grpc#32997]
https://grpc.github.io/grpc/csharp/api/Grpc.Core.Marshaller-1.html
public Marshaller(Action<T, SerializationContext> serializer, Func<DeserializationContext, T> deserializer)

I am using different serializers\compressors (home brew) based on attributes on the service interface and service methods (home brew). I previously used a passthru byte[] marshaller and created byte[] messages, but moving to using real marshaller and SerializationContext\DeserializationContext to lower memory use. I use a single duplex method for all communication, effectively using grpc only as a transport.
Problem arises:
I no longer can get access to what serializer and compressor to use in the marshaler. Client send this info in the headers. I had easy access to this when I simply sent byte[] messages, but now when trying to do it correctly and serialize\compress in the marshaller, the marshaller has no way to get this info.

Suggestion: include headers in SerializationContext\DeserializationContext.
Serializer code would emit header entries for serializer\compressor into SerializationContext.Headers (fetched from the message).
Deserializer code would extract header entries for serializer\compressor from DeserializationContext.Headers (sent from client).

PS: This would only work if the headers themself are not marshalled too. I don't know if they are. If they are, I guess this can not be solved.

Hope this was understandable.
Thanks.

**Comment by tonydnewell** [comment]
@osexpert I think what you are asking is for there to be some meta data sent with the serialized data so that you know how to deserialize the data. Is that correct? If not can you give a more concrete example.

The SerializationContext and DeserializationContext is not sent on the wire and is local to the client/server. I'm not sure how adding headers here would help unless I've misunderstood your request.

**Comment by osexpert** [comment]
@tonydnewell Adding access to headers in SerializationContext\DeserializationContext would make it possible for the marshaller to tell\know what format the data is in, without reading\adding this information to the payload itself. Here is pseudo code of how I would have use it:

```
class MyRequestMessage
{
 public string Serializer;
 public string Compressor;
 public MyData Payload; 
}

class MyResponseMessage
{
 public string Serializer;
 public string Compressor;
 public MyData Payload;
}

var MySingleMethod = new Method<MyRequestMessage, MyResponseMessage>(
 type: MethodType.DuplexStreaming,
 serviceName: "MySingleService",
 name: "MySingleMethod",
 requestMarshaller: Marshallers.Create<MyRequestMessage>(SerializeMyRequest, DeserializeMyRequest),
 responseMarshaller: Marshallers.Create<MyResponseMessage>(SerializeMyResponse, DeserializeMyResponse));
				

private void SerializeMyRequest(MyRequestMessage m, SerializationContext ctx)
{
 MySerialize(m.Serializer, m.Compressor, ctx.GetBufferWriter(), m.Payload),

 ctx.Headers.Add("my-serializer", m.Serializer);
 ctx.Headers.Add("my-compressor", m.Compressor);  
}

private MyRequestMessage DeserializeMyRequest(DeserializationContext ctx)
{
 
 try
 {
  var serializer = ctx.Headers["my-serializer];
  var compressor = ctx.Headers["my-compressor];
  var payload = MyDeserialize(serializer, compressor, ctx.PayloadAsReadOnlySequence());
  return new MyRequestMessage{ Payload = payload, Serializer = serializer, Compressor = compressor};
 }
 finally
 {
  ctx.Complete();
 }
}
```
Serializer and compressor will be different for every message so it can't be hard coded.

It is possible to add this info to the payload itself, but it feels wrong when there are headers where I really want to put this info (and is currently putting this info today, but then with messages that are simply byte[]). But in the marshaller, I have no access to headers or any other info that would allow this info to not be in the payload itself.

**Comment by tonydnewell** [comment]
@osexpert This is what I think you are asking for:
-  meta data (headers) to be sent alongside the serialized data, and for this meta data to be made available on the remote peer before deserializing the data to give the deserializer information to enable it to do its job. 
- these headers to be set in the serialization context, and read in the deserialization context

As I said previously the contexts are not transmitted on the wire and are only local.

Do you need this because each call can have different serialization implementations and you don't know in advanced what is being used?

I'll let others discuss whether this feature request is generally useful.  My feeling is that this is an application problem that you should solve either by adding information at the start of the serialized data or by some out-of-band mechanism to know the serialization encoding in advanced.

**Comment by osexpert** [comment]
"Do you need this because each call can have different serialization implementations and you don't know in advanced what is being used?"
Exactly

"My feeling is that this is an application problem that you should solve either by adding information at the start of the serialized data"
It is possible and probably what I end up doing. But I thought the Headers thing was a good idea so I wanted to share\suggest\request it:-)

**Comment by tonydnewell** [comment]
My comments to add to discussion for deciding on this feature:

- If a custom serializer/deserializer needs extra meta data to be sent/received then that should really be part of their implementations
- Transmitting meta data from the serialization context will affect the existing protocol and would need to be done in a backwards compatible way and may affect performance
- APIs for all supported languages would need to be changed to handle the new meta data

**Comment by tonydnewell** [comment]
Additional note: you can set request headers and response headers and have access to them in the call if you want extra meta data per call.

**Comment by jtattermusch** [comment]
This is somewhat related to https://github.com/grpc/grpc-dotnet/issues/1983, but asks for even more flexibility.

While I think I understand what you want to achieve (have a flexible serialization format and decide e.g. how a message is encoded based on a header's value e.g. `my-custom-serialization-format:A` or `my-custom-serialization-format:B`), but this is not the primary use case for grpc. Most users would use protobuf, where the serialization format is given (and you have to agree on what message is being sent based on the service definition anyway) and we have no plans to make headers accessible from marshallers while deserializing messages (since it's not useful for vast majority of users).

As a workaround, you can use a custom serialization format that is self-descriptive. E.g. if the first byte of a message is 0, the following data would be encoded in format A and if it's e.g. 1, the following data is in format B. This is completely doable with the existing serialization/deserialization API.

I'm going to close this issue as "won't fix".

**Comment by osexpert** [comment]
> As a workaround, you can use a custom serialization format that is self-descriptive. E.g. if the first byte of a message is 0, the following data would be encoded in format A and if it's e.g. 1, the following data is in format B. This is completely doable with the existing serialization/deserialization API.
> 
Yes, this is what I am currently doing.

The reason for the wish was that I originally used a dummy byte[]-to-byte[] marshaller and did all the serialize\compression logic at the message-level (byte[] messages). But to take advantage of the SerializationContext.GetBufferWriter() to reduce memory use, I moved serialize into a marshaller, but then lost access to headers.

But it is cool, it was just an idea.

Thanks.
