### ISSUE TITLE
[Python Sync] Implement a mechanism to propagate information between interceptors and server handlers.

### ISSUE THREAD

**Issue by XuanWang-Amos** [grpc/grpc#33071]
We recently discovered a bug where interceptors and server handlers were running in different threads. This made it difficult to pass information between them, we need fix it and also and an example for how to propagate information between interceptors and server handlers.

Related issue: https://github.com/grpc/grpc/issues/24470

#### Note
Before we fix it, as a workaround, we recommend pass data using serialized [metadata](https://github.com/grpc/grpc/blob/v1.56.0/src/python/grpcio/grpc/__init__.py#L415).

**Comment by jenstroeger** [comment]
> Before we fix it, as a workaround, we recommend pass data using serialized [metadata](https://github.com/grpc/grpc/blob/master/src/python/grpcio/grpc/__init__.py#L1315).

Unfortunately, in my case these objects can’t be serialized (like managed db session). So… please hurry 😇

**Comment by mehrdada** [comment]
The ability for gRPC to schedule callbacks on any thread in the threadpool is very much by design--applications should not rely on which thread gRPC decides to schedule callbacks on. That should be an implementation detail and subject to change. It sets a dangerous precedent if users start relying on such guarantees. The interceptor can wrap the incoming context and pass its own implementation to share information. If that is not super convenient, there needs to be an explicit facility to make that particular task easier.  Encouraging users to shove objects in thread locals is unwise.

**Comment by jenstroeger** [comment]
@mehrdada as the linked issue details, the original question was about sharing data between multiple interceptors and the request handler as they process an incoming request — i.e. what’s the best way to pass data down that call chain and back up?

**Comment by mehrdada** [comment]
@jenstroeger I understand your concern. If I recall the discussion from many years ago, for the sync case, the idea was for the interceptor to create and pass a custom `ServicerContext`-derived object that wraps the incoming context and delegates its methods (probably easiest way to implement through some decorator like pattern) and carry satellite data in its extra custom-defined methods for the request handler to use (if modifying the request object did not make sense). I agree that this may be cumbersome and perhaps the solution may be for the library to provide a first party decorator facility to make it easier to accomplish, or perhaps directly a satellite data dictionary to the context object. However, in my opinion, this problem that does not justify making the library guarantee to the user which thread it is running which interceptor/handler on; that's a low-level implementation detail and will be brittle and scary (imagine a grpc update changes its underlying behavior intentionally or accidentally, and a user program suddenly runs a request handler with a different thread local associated with a separate request potentially exposing PII).

**Comment by jenstroeger** [comment]
@mehrdada that’s interesting — but how does your recommendation play together with static types? See also comment https://github.com/grpc/grpc/issues/24470#issuecomment-1223867769.

**Comment by XuanWang-Amos** [comment]
Thanks for the suggestion @mehrdada! We agree that it's not a good idea to guarantee that interceptors and handles will be run in the same thread.

We plan to use an alternative solution for this issue:
Similar to the suggested use of `ServicerContext`, the gRPC library will create a new `contextVar` to store custom context and maintain it by propagating it across different threads. This way, the user will have a way to pass information around, and it also hides the thread implementation.

**Comment by rootux** [comment]
> 
@XuanWang-Amos Is the link to metadata L1315 correct? Not sure I understand how to achieve this.

**Comment by kcooney** [comment]
I'm a bit puzzled by some of the responses. I don't think anyone is requesting that interceptors and handlers be run in the same thread, and contextvars doesn't require it (one could temporarily associate a `Context` with a thread via `contextvars .Context.run()`).

I think something [like this](https://github.com/grpc/grpc/compare/master...kcooney:grpc:context-vars) might work (I can't confirm since I can't seem to run tests grpc on my MacOS laptop)

**Comment by kcooney** [comment]
@XuanWang-Amos would you be a good person to review this?
