### ISSUE TITLE
ruby: Server stream reports "grpc_call_start_batch failed with outstanding read or write present (code=8)" instead of DeadlineExceeded

### ISSUE THREAD

**Issue by stanhu** [grpc/grpc#33283]
### What version of gRPC and what language are you using?

grpc v1.55.0

### What operating system (Linux, Windows,...) and version?

Linux Ubuntu 20.04

### What runtime / compiler are you using (e.g. python version or version of gcc)

Ruby 3.1.4, 3.0.6

### What did you do?

I reproduced the error with this example:

```proto
syntax = "proto3";

option ruby_package = "hello_pb";

service HelloService {
  rpc SayHello (HelloRequest) returns (stream HelloResponse) {}
}

message HelloRequest {
  string name = 1;
}

message HelloResponse {
  repeated string messages = 1;
}
```

```ruby
require 'grpc'
require_relative 'hello_services_pb'

class HelloServer < HelloPb::HelloService::Service
  def say_hello(request, _call)
    sleep 5
  end
end

def main
  server = GRPC::RpcServer.new
  server.add_http2_port('0.0.0.0:50051', :this_port_is_insecure)
  server.handle(HelloServer)
  server.run_till_terminated_or_interrupted([1, 'int', 'SIGQUIT'])
end

main
```

```ruby
require 'grpc'
require_relative 'hello_services_pb'

def main
  stub = HelloPb::HelloService::Stub.new('127.0.0.1:50051', :this_channel_is_insecure)
  request = HelloPb::HelloRequest.new(name: 'World')
  response = stub.say_hello(request, deadline: Time.now + 1)

  response.each do |response|
    puts "response: #{response.messages}"
  end
end

main
```

### What did you expect to see?

With grpc v1.45.0, I see `GRPC::DeadlineExceeded`:

```
$ ruby -I. client.rb
/home/stanhu/.asdf/installs/ruby/3.0.6/lib/ruby/gems/3.0.0/gems/grpc-1.42.0-x86_64-linux/src/ruby/lib/grpc/generic/active_call.rb:29:in `check_status': 4:Deadline Exceeded. debug_error_string:{"created":"@1685516791.527016274","description":"Deadline Exceeded","file":"src/core/ext/filters/deadline/deadline_filter.cc","file_line":81,"grpc_status":4} (GRPC::DeadlineExceeded)
        from /home/stanhu/.asdf/installs/ruby/3.0.6/lib/ruby/gems/3.0.0/gems/grpc-1.42.0-x86_64-linux/src/ruby/lib/grpc/generic/active_call.rb:180:in `attach_status_results_and_complete_call'
        from /home/stanhu/.asdf/installs/ruby/3.0.6/lib/ruby/gems/3.0.0/gems/grpc-1.42.0-x86_64-linux/src/ruby/lib/grpc/generic/active_call.rb:169:in `receive_and_check_status'
        from /home/stanhu/.asdf/installs/ruby/3.0.6/lib/ruby/gems/3.0.0/gems/grpc-1.42.0-x86_64-linux/src/ruby/lib/grpc/generic/active_call.rb:337:in `each_remote_read_then_finish'
        from client.rb:9:in `each'
        from client.rb:9:in `main'
        from client.rb:14:in `<main>'
```

### What did you see instead?

Starting with grpc v1.46.2 and up, I see `grpc_call_start_batch failed with outstanding read or write present (code=8)`:

```
$ ruby -I. client.rb
/home/stanhu/.asdf/installs/ruby/3.0.6/lib/ruby/gems/3.0.0/gems/grpc-1.46.3-x86_64-linux/src/ruby/lib/grpc/generic/active_call.rb:169:in `run_batch': grpc_call_start_batch failed with outstanding read or write present (code=8) (GRPC::Core::CallError)
        from /home/stanhu/.asdf/installs/ruby/3.0.6/lib/ruby/gems/3.0.0/gems/grpc-1.46.3-x86_64-linux/src/ruby/lib/grpc/generic/active_call.rb:169:in `receive_and_check_status'
        from /home/stanhu/.asdf/installs/ruby/3.0.6/lib/ruby/gems/3.0.0/gems/grpc-1.46.3-x86_64-linux/src/ruby/lib/grpc/generic/active_call.rb:343:in `each_remote_read_then_finish'
        from client.rb:9:in `each'
        from client.rb:9:in `main'
        from client.rb:14:in `<main>'
```

**Comment by stanhu** [comment]
Reverting https://github.com/grpc/grpc/pull/29155 fixes the issue. For some reason, setting `RECV_INITIAL_METADATA` changes the error message?

**Comment by alto-ruby** [comment]
When deadline exceed, [CallError raised](https://github.com/grpc/grpc/blob/v1.55.0/src/ruby/ext/grpc/rb_call.c#L864), then [remote_read](https://github.com/grpc/grpc/blob/v1.55.0/src/ruby/lib/grpc/generic/active_call.rb#L259) aborted without setting `@metadata_received = true`.
With https://github.com/grpc/grpc/issues/33283, [receive_and_check_status](https://github.com/grpc/grpc/blob/v1.55.0/src/ruby/lib/grpc/generic/active_call.rb#L168) finds out  `@metadata_received` is false, so RECV_INITIAL_METADATA is sent again and caused the `grpc_call_start_batch failed with outstanding read or write present (code=8)` error.

The complexity here is that there is not enough information propagated to active_call.rb that whether `RECV_INITIAL_METADATA` was sent or not when there was a CallError.

However send `RECV_STATUS_ON_CLIENT` alone without `RECV_INITIAL_METADATA` (although against grpc protocol) indeed can correctly get the deadline exceed error.

As a result I think reverting https://github.com/grpc/grpc/pull/29155 might be a good idea, and it appeared didn't solve the mentioned test failure in the PR, which was also a deadline exceed error I think may actually caused by test running slow.

CC: @apolcyn

**Comment by stanhu** [comment]
Thanks, I've submitted a revert in https://github.com/grpc/grpc/pull/33408.

**Comment by stanhu** [comment]
@apolcyn @ctiller This issue actually caused a significant regression in production because we handle `DeadlineExceeded` and other `StandardError` types gracefully, but `GRPC::Core::CallError` does NOT inherit from `StandardError`: https://github.com/grpc/grpc/blob/14c63c70afdb52d94f6cf8c2a163f205156d4ba1/src/ruby/ext/grpc/rb_call.c#L989-L991

I believe the revert in https://github.com/grpc/grpc/pull/33408 solves this issue, so I would appreciate a quick review. Thanks!
