### ISSUE TITLE
allow stream carry custom metadata after stream is built 

### ISSUE THREAD

**Issue by fengyeall111** [grpc/grpc#33322]
### Is your feature request related to a problem? Please describe.
Now grpc loadbalance is not message level loadBalance,  but just stream level.For bidistream,
grpc stream must encode metadata in http2 header frame. For bidistream client can not send extra metadata after the stream is built: grpc encode customdata in http2 header frame, http2 does not allow send header frame before send frame end flag.

### Describe the solution you'd like
allow stream carry custom metadata after stream is built. metadata is bind to http2 data frame, so,we can have more chance to pass metadata.

### Describe alternatives you've considered
This would be useful for traffic management and loadbalance:unshackled from HTTP/2 header frame restrictions.
Think about this scene:
we want to send msg to some pod byBidiStream grpcCall, we just want to do loadbalance for msg，not in stream level:we must build many streams with pods in client side. This can not be spilted in service mesh.

### Additional context
Bidistream is useful for continuous asynchronous bidirectional stream that a client-side endpoint must bind to a server-side endpoint.
Actually, here are also use cases for this：
The client continuously sends a stream of messages，for every msg，we want add extra metadata."The client doesn't need response  from the same server-side.

**Comment by fengyeall111** [comment]
Maybe metadata can be carried by custom frames，not header frame or data frame.

**Comment by yashykt** [comment]
I think what we would suggest here is to just encode the metadata in your message.

**Comment by markdroth** [comment]
I don't think this feature request makes any sense.  It sounds like what you want is for each individual message you send to have its own metadata and to be load-balanced independently of any other message.  But metadata and load balancing are things that happen on a per-stream basis, not on a per-message basis, so you can already do what you want simply by using a separate stream for each message instead of sending all messages on a single stream.

gRPC is intentionally designed such that one gRPC stream corresponds to one HTTP/2 stream.  Note that bidi streaming is actually the most general form of an RPC in gRPC; unary and the other forms of streaming are actually just special cases of bidi streaming.  We are not going to change that design.
