### ISSUE TITLE
gRPC protobuf PHP bug

### ISSUE THREAD

**Issue by genosmrpg7899** [grpc/grpc#33402]
### What version of gRPC and what language are you using?
php_grpc-1.43.0-8.1-ts-vs16-x64

### What operating system (Linux, Windows,...) and version?
Windows

### What runtime / compiler are you using (e.g. python version or version of gcc)
VS16

### What did you do?
Please provide either 1) A unit test for reproducing the bug or 2) Specific steps for us to follow to reproduce the bug. If there’s not enough information to debug the problem, gRPC team may close the issue at their discretion. You’re welcome to re-open the issue once you have a reproduction.

$client = new ThumbnailsRelayServiceClient('127.0.0.1:64992', [
	'credentials' => \Grpc\ChannelCredentials::createInsecure(),
]);

$req = new ThumbnailRequest();

### What did you expect to see?
Blank response

### What did you see instead?
Hangs and browser gives me NETWORK_CHANGED. Caused by init of ThumbnailRequest or any class extending to \Google\Protobuf\Internal\Message
Make sure you include information that can help us debug (full error message, exception listing, stack trace, logs).

See [TROUBLESHOOTING.md](https://github.com/grpc/grpc/blob/master/TROUBLESHOOTING.md) for how to diagnose problems better.

### Anything else we should know about your project / environment?
I cannot compile new binaries nor have I been able to find latest binaries for either the gRPC extension or the protobuf extension. Anything on that part would be appreciated. This code is in a Laravel controller, and I am not using the protobuf extension, rather the composer library.

**Comment by Jan-E** [comment]
@genosmrpg7899 I regularly build some versions of PHP with a few extensions:
https://www.apachelounge.com/viewtopic.php?t=6359

While waiting for https://github.com/grpc/grpc/pull/33478 to be merged, I saw this issue and decided to build php_grpc.dll (1.55.0), protobuf and phalcon for PHP 8.1 as well. Permalinks to the builds with grpc:

https://phpdev.toolsforresearch.com/php-8.1.20-nts-Win32-vs16-x64.htm 
https://phpdev.toolsforresearch.com/php-8.1.20-nts-Win32-vs16-x64.zip
https://phpdev.toolsforresearch.com/php-8.1.20-Win32-vs16-x64.htm
https://phpdev.toolsforresearch.com/php-8.1.20-Win32-vs16-x64.zip

The compiled extensions are inside the zips.

**Comment by Erutan409** [comment]
@Jan-E Do you know if there are any plans to get a build out for 8.2 for Win?

**Comment by Erutan409** [comment]
@Jan-E I should have opened the link first.

**Comment by Jan-E** [comment]
PHP 8.2 

https://phpdev.toolsforresearch.com/php-8.2.7-nts-Win32-vs16-x64.htm 
https://phpdev.toolsforresearch.com/php-8.2.7-nts-Win32-vs16-x64.zip
https://phpdev.toolsforresearch.com/php-8.2.7-Win32-vs16-x64.htm
https://phpdev.toolsforresearch.com/php-8.2.7-Win32-vs16-x64.zip

PHP 8.3 

https://phpdev.toolsforresearch.com/php-8.3.0alpha1-nts-Win32-vs16-x64.htm 
https://phpdev.toolsforresearch.com/php-8.3.0alpha1-nts-Win32-vs16-x64.zip
https://phpdev.toolsforresearch.com/php-8.3.0alpha1-Win32-vs16-x64.htm
https://phpdev.toolsforresearch.com/php-8.3.0alpha1-Win32-vs16-x64.zip

I won’t be building php_grpc.dll every time, because it takes a lot of time and increases the size of the doenloads significantly. Just take a look at the php_grpc.pdb.
