### ISSUE TITLE
Add support for HTTP CONNECT for L7 load balancing

### ISSUE THREAD

**Issue by markdroth** [grpc/grpc#33518]
Note that this is use-case 2 as defined in [gRFC A1](https://github.com/grpc/proposal/blob/master/A1-http-connect-proxy-support.md#use-cases).  See also the similar feature request in Java in https://github.com/grpc/grpc-java/issues/10022.

We want to add two options, which need to be configured via channel args but may also be configured via env vars:
1. The IP address of an HTTP CONNECT proxy to use.  If set, this will enable using the proxy in a mode where we use the proxy for each individual backend connection, using the backend IP address as the argument to the HTTP CONNECT request.  Note that this needs to be a different option from the existing options that we use to enable use-case 1, which are described in [Enabling HTTP Proxy](https://github.com/grpc/grpc/blob/master/doc/core/default_http_proxy_mapper.md#enabling-http-proxy).
2. A list of CIDR ranges for which the proxy should *not* be used, similar to the existing `grpc_no_proxy` env var described in [Disabling HTTP Proxy](https://github.com/grpc/grpc/blob/master/doc/core/default_http_proxy_mapper.md#disabling-http-proxy).  In this case, we could just reuse the existing env var, but we also need a channel arg for it.

Internally, this should be implemented as a [`ProxyMapper`](https://github.com/grpc/grpc/blob/2c336ac7fdecef91fc98e5349cc15fa80c29af5a/src/core/lib/handshaker/proxy_mapper.h#L34) that provides a [`MapAddress()`](https://github.com/grpc/grpc/blob/2c336ac7fdecef91fc98e5349cc15fa80c29af5a/src/core/lib/handshaker/proxy_mapper.h#L47) method.  That method can check the channel args or env vars described above, and if set, it can set the [`GRPC_ARG_HTTP_CONNECT_SERVER` channel arg](https://github.com/grpc/grpc/blob/2c336ac7fdecef91fc98e5349cc15fa80c29af5a/src/core/lib/transport/http_connect_handshaker.h#LL28C9-L28C37) to the original IP address, which will trigger use of the HTTP CONNECT handshaker.

CC @yashykt @ejona86

**Comment by ejona86** [comment]
It probably doesn't matter much, because backends are probably consistently using/not using the proxy so IP-based matching is probably of limited need, but it may make sense to reverse the matching to IPs that _should_ go through the proxy (and default to "0.0.0.0/0,::/0" if not specified).

For case 1 most of the Internet is on the other side of the proxy, so you list internal addresses as "no proxy." For the cases of case 2 we've seen, the client has access to the internet, and uses the proxy to get _in_. So if we follow the same "no proxy" configuration for case 2, that'd mean you'd need to list all Internet addresses except the internal addresses.

Again, probably doesn't matter much, but may be worth thinking about for a minute.

**Comment by eugeneo** [comment]
Landed in core:
1. Env var and channel arg for specifying the use-case 2 proxy address.
2. Env var and channel arg for the addresses/subnets that require use of said proxy.

Are there any remaining items for this issue?

**Comment by markdroth** [comment]
No, I think the changes you made in #34617 address this feature request.
