### ISSUE TITLE
System.IO.IOException is thrown when cancelling AsyncDuplexStreamingCall

### ISSUE THREAD

**Issue by voroninp** [grpc/grpc#33922]
### What version of gRPC and what language are you using?
NuGet Grpc.Core 2.46.6 C#

### What operating system (Linux, Windows,...) and version?
Client: Windows 11 client, 
gRPC Server: docker image .NET runtime, Debian 11

### What runtime / compiler are you using (e.g. python version or version of gcc)
Client: .NET 4.6.2
Server: .NET 7

### What did you do?
Here's a code sample:
```
var client = new RadioDataService.RadioDataServiceClient(channel);
var cts = new CancellationTokenSource();
AsyncDuplexStreamingCall<IdRequest, AdBreak> call = client.GetBreaks(cancellationToken: cts.Token);
await call.RequestStream.WriteAsync(new IdRequest { Ids = { new[] { 1 } } });
cts.Cancel();
```

### What did you expect to see?
I expect to see `OperationCancelledException` thrown on the server.

### What did you see instead?
I see `System.IO.IOException` with the message `The client reset the request stream.`

**Comment by jtattermusch** [comment]
cc @tonydnewell

**Comment by tonydnewell** [comment]
@voroninp I'm not able to reproduce this behaviour. I modified the RouteGuide example so that the client behaved as you described above but I did not see exactly the same behaviour.  If the server tried to send a response after the cancel then I did see a `System.InvalidOperationException: Already finished.` exception.

Is the server also Grpc.Core 2.46.6 or are you using Grpc.AspNetCore.Server?

Are you able to provide a short but complete example (maybe in a GitHub repository) that I can run?

It is not clear from you example code above if/when the call gets disposed or the channel gets shutdown.

**Comment by voroninp** [comment]
@tonydnewell , ok, thanks, I'll try to create a small solution.

We use ` Grpc.AspNetCore.Server` server.

**Comment by tonydnewell** [comment]
Might be related to https://github.com/grpc/grpc-dotnet/issues/1219

**Comment by voroninp** [comment]
Indeed, looks like it is. Thanks. I should search there first, before bothering you.
