### ISSUE TITLE
Release `arm64` binaries on Rubygems

### ISSUE THREAD

**Issue by jeremiahrose** [grpc/grpc#33954]
### Is your feature request related to a problem? Please describe.
Installing gRPC in Docker on mac M1 is very slow. It takes upwards of 25 minutes to compile on my machine.

### Describe the solution you'd like
It would be really nice if `arm64` binaries were available on Rubygems so that we could skip this compilation step.

### Describe alternatives you've considered
Can use a different architecture with QEMU, or just put up with the slow build. Neither options are great.

**Comment by lloeki** [comment]
I feel like it's more than that, the gem appears to break several rubygems expectations:

The gem is published as `ruby` (which means "pure ruby", or abusively "compatible with _any_ platform because it builds native components on the spot") but is in fact thin packaging for target-specific binaries:

```
$ env GEM_HOME=fake gem install grpc-tools
1 gem installed

$ ls -1 fake/gems/grpc-tools-1.56.2 fake/gems/grpc-tools-1.56.2/bin

fake/gems/grpc-tools-1.56.2:
README.md
bin
platform_check.rb
version.rb

fake/gems/grpc-tools-1.56.2/bin:
grpc_tools_ruby_protoc
grpc_tools_ruby_protoc_plugin
x86-linux
x86-windows
x86_64-linux
x86_64-macos
x86_64-windows
```

None but the one it ultimately runs on would be executable (without `binfmt_misc` trickery + a compatible userland), and so are dead weight.

Each one of these should be published as individual binary platform gems:

- `x86-linux`
- `x86_64-linux`
- `x86_64-darwin` (NOT `x86_64-darwin-22` or something, the missing platform version component acts as a wildcard)

For Windows I'm less certain, could be mswin or mingw thingies:

-https://github.com/rubygems/rubygems/blob/8af163866564c6a2afb9fd3cd51f452459dd9f06/lib/rubygems/platform.rb#L103-L127
- https://docs.ruby-lang.org/en/master/windows_md.html

And in addition, what this issue requests:

- `aarch64-linux`
- `arm64-darwin` (NOT `arm64-darwin-22` or something)

The `ruby` gem platform should be attempting to build binaries from source upon install, or worst case, be a shim.

In addition, this bit of code falls through to return `x86` on `aarch64-linux`:

```
  def PLATFORM.architecture
    host_cpu = RbConfig::CONFIG['host_cpu']

    # When we're on arm in macOS, we can rely on Rosetta and use the x86_64 binary
    return 'x86_64' if RbConfig::CONFIG['host_os'] =~ /darwin/ && host_cpu =~ /arm|aarch/

    case host_cpu
      when /x86_64/
        'x86_64'
      else
        'x86'
    end
  end
  ```

The `java` gem platform should include all binaries because it cannot be known which platform it will run on. But then I suppose JRuby is not a current target because the code above fails for JRuby.

For reference, here are some implementations:

- https://rubygems.org/gems/libv8-node/versions
- https://github.com/rubyjs/libv8-node/blob/4db6396edce91a5c17224c7c41a4b514dea1c85e/Rakefile
- https://github.com/DataDog/libddwaf-rb/blob/913c4083ab3db2f5b755079af171ec32ba06b015/Rakefile
- https://rubygems.org/gems/libddwaf/versions

**Comment by alto-ruby** [comment]
@apolcyn We should be able to release arm64 binary gems for Linux and MacOS starting from 1.57.0
I have verified artifacts from #33826 for 1.57.0-pre1 works with arm64 Linux and MacOS.

artifacts link: https://source.cloud.google.com/results/invocations/3cd1f0ca-ffed-4d80-9c10-46b0e225e754/targets

**Comment by alto-ruby** [comment]
@lloeki grpc-tools is different from grpc gem and it does have the problems you described, there is #25755 to track it and discussions from there. I did some experiments to build arm64 native binaries but so far not much progress unfortunately.

**Comment by lloeki** [comment]
Thanks @alto-ruby, I came here from the rubygems.org Homepage link, did a quick search, and stumbled upon this issue. Apologies for the noise.

**Comment by stanhu** [comment]
@alto-ruby Ah, I see the `arm64-darwin` binaries are being [generated already](https://source.cloud.google.com/results/invocations/3cd1f0ca-ffed-4d80-9c10-46b0e225e754/targets/github%2Fgrpc%2Fbuild_artifacts/tests;group=tasks;test=build_artifact.ruby_native_gem_linux_arm64-darwin;row=8). 

Where is the script that publishes these artifacts to RubyGems? Is there anything we can do to expedite this?

**Comment by moracca** [comment]
I was wondering the same thing about releasing pre-built binaries for BSD platforms, in my case amd64.  I don't see BSD in any of the build output.  When installing this gem or upgrading it, having to compile the native extensions from source means  a 20-30 minute delay on some systems before the rest of the rails app can come up.  I'd love to avoid this delay by being able to grab the pre built binaries, even if I need to host them myself elsewhere, although I'm not 100% clear on what the process would be to get bundler to use an alternate URL for the binaries.

**Comment by stanhu** [comment]
I think we can close this issue now. From https://rubygems.org/gems/grpc/versions, I see that grpc v1.60 started quietly publishing `arm64-darwin` and `aarch64-linux`:

![image](https://github.com/grpc/grpc/assets/963826/258fa407-53dd-44df-82a9-b952480bcb58)
