### ISSUE TITLE
csharp_names.h not found

### ISSUE THREAD

**Issue by proteneer** [grpc/grpc#3395]
When running make:

```
In file included from src/compiler/csharp_generator.cc:39:
./src/compiler/csharp_generator.h:39:10: fatal error: 
      'google/protobuf/compiler/csharp/csharp_names.h' file not found
#include <google/protobuf/compiler/csharp/csharp_names.h>
```

Running on OSX Yosemite, 0.11 Beta release. Is there a way to disable the C# wrappers in the mean time?

**Comment by anubhavnidhi** [comment]
Hi,
I am facing the same problem. I see the file in thirdparty/protobuf/src/google/protobuf/compiler/csharp/ . So what did you do to fix this problem?

**Comment by proteneer** [comment]
you need to install protocol buffers from source (and its headers).

**Comment by jgeewax** [comment]
This doesn't seem fixed....

If I follow the instructions in INSTALL, things should work :(

Here's what I did that seemed to fix things... But I'm not happy about it...

```bash
$ git clone https://github.com/google/protobuf.git
$ cd protobuf
$ ./autogen.sh
$ ./configure
$ make
$ sudo make install

$ git clone git clone https://github.com/grpc/grpc.git
$ cd grpc 
$ git submodule update --init
$ make
$ sudo make install
```

**Comment by murgatroid99** [comment]
I am having trouble reproducing this. Just the second part of that sequence of commands, starting with `git clone https://github.com/grpc/grpc.git`, is enough for me to build it.

This problem may be caused by having an older release of protobuf 3 installed. Due to the way the releases are numbered, we sometimes fail to detect that we cannot use the installed protobuf.

**Comment by jgeewax** [comment]
Gotcha -- so it could've been an old protobuf install... I'll give it another test on a fresh install and report back :)
