### ISSUE TITLE
When the asynchronous service receives a large number of client connections, assertion failed: ok

### ISSUE THREAD

**Issue by wfangyan** [grpc/grpc#34084]
What version of gRPC and what language are you using?
protobuf 3.19.4.0，Using gRPC 1.46.3 , c++
What operating system (Linux, Windows,...) and version?
Linux version 3.10.0-693.21.1.el7.x86_64
What runtime / compiler are you using (e.g. python version or version of gcc)
gcc9.4
What did you do?
When the asynchronous service receives a large number of client connections, or  ctrl+c for clients frequently, assertion failed: ok.
Then program received signal SIGABRT, Aborted.
for example:
    while (true)
    {
      GPR_ASSERT(cq_->Next(&tag, &ok));
      GPR_ASSERT(ok);
      static_cast<CallData *>(tag)->Proceed();
    }

Please provide either 1) A unit test for reproducing the bug or 2) Specific steps for us to follow to reproduce the bug. If there’s not enough information to debug the problem, gRPC team may close the issue at their discretion. You’re welcome to re-open the issue once you have a reproduction.

reference code:
https://github.com/grpc/grpc/blob/v1.38.0/examples/cpp/helloworld/greeter_async_server.cc

the proto is infer.proto:
syntax = "proto3";

option java_multiple_files = true;
option java_package = "io.grpc.examples.helloworld";
option java_outer_classname = "HelloWorldProto";
option objc_class_prefix = "HLW";

package infer;

service Result {
  rpc get_result (InferRequest) returns (InferResponse) {}
}

message InferRequest {
  string name = 1;
  bytes frame = 2;
  string ext = 3; 
}

message InferResponse {
  string data = 1;
  string code = 2;
  string message = 3;
}

What did you expect to see?
running, no aborted , when the asynchronous service receives a large number of client connections, or  ctrl+c for clients frequently
What did you see instead?
aborted, service stop
Make sure you include information that can help us debug (full error message, exception listing, stack trace, logs).

See [TROUBLESHOOTING.md](https://github.com/grpc/grpc/blob/master/TROUBLESHOOTING.md) for how to diagnose problems better.
Anything else we should know about your project / environment?

**Comment by drfloob** [comment]
Take a look at the meaning of `ok` for Server-side read in the API docs https://grpc.github.io/grpc/cpp/classgrpc_1_1_completion_queue.html#a86d9810ced694e50f7987ac90b9f8c1a. 

> For the server-sider operation, though, [ok=false] could happen because the client has done a WritesDone already.

You may be seeing expected behavior, depending on what your code is actually doing. If you think there is a gRPC bug here, please produce a complete example (a github branch, with bazel build file preferably) that would allow us to reproduce the problem.

**Comment by Tradias** [comment]
Since you are referring to unary RPCs this part of the documentation applies to you:

> Client-side Write, Client-side WritesDone, Server-side Write, **Server-side Finish**, Server-side SendInitialMetadata (which is typically included in Write or Finish when not done explicitly): ok means that the data/metadata/status/etc is going to go to the wire. If it is false, it not going to the wire because the call is already dead (i.e., canceled, deadline expired, other side dropped the channel, etc).

https://grpc.github.io/grpc/cpp/classgrpc_1_1_completion_queue.html#a86d9810ced694e50f7987ac90b9f8c1a

Which means if the client has disconnected before the server can send its finish then `Next` will produce a non-ok status. In that case, this line:

https://github.com/grpc/grpc/blob/54dc182082db941aa67c7c3f93ad858c99a16d7d/examples/cpp/helloworld/greeter_async_server.cc#L156-L156

causes the server abort. Just remove it to resolve the issue.
