### ISSUE TITLE
C#: Bad performance of the client library (Grpc.Core is much slower compared to grpc-dotnet)

### ISSUE THREAD

**Issue by voroninp** [grpc/grpc#34570]
### What version of gRPC and what language are you using?
Grpc.Core 2.46.6

### What operating system (Linux, Windows,...) and version?
Windows 11

### What runtime / compiler are you using (e.g. python version or version of gcc)
.NET Framework 4.6

### What did you do?
I am comparing the performance of Grpc.Core and Grpc.Net.Client libraries.

```
public static async Task Main(string[] args)
{
    ChannelBase channel = new Grpc.Core.Channel(..., ChannelCredentials.SecureSsl);
    var client = new RadioDataService.RadioDataServiceClient(channel);

    var sw = Stopwatch.StartNew();
    await client.GetAllChannels(new Empty()).ResponseStream.ToListAsync();
    sw.Stop();
    Console.WriteLine($"Grpc.Core client took {sw.Elapsed}.");

    channel = GrpcChannel.ForAddress(..., new GrpcChannelOptions
    {
        HttpHandler = new WinHttpHandler()
    });
    client = new RadioDataService.RadioDataServiceClient(channel);
    sw.Restart();
    await client.GetAllChannels(new Empty()).ResponseStream.ToListAsync();
    sw.Stop();
    Console.WriteLine($"Grpc.Net.Client took {sw.Elapsed}.");
}
```

Here are the timings:
> Grpc.Core client took 00:00:10.2794571.
Grpc.Net.Client took 00:00:00.4492665.

### What did you expect to see?
I am surprised by this enormous difference. 

### What did you see instead?
I am expecting to see more or less the same performance for these libraries.

**Comment by jtattermusch** [comment]
@tonydnewell  can you take a look please?

My observations:
- enable extra logging in Grpc.Core https://github.com/grpc/grpc/blob/master/TROUBLESHOOTING.md to help determine what's slow.
- This is probably not the Grpc.Core logic itself, but perhaps it takes long time to create the connection to the backends (need to investigate why) or there might be something wrong with your test scenario.
- A "small" RPC taking 10 seconds is completely unrealistic (and it's also suspicious that it's almost exactly 10 seconds), so I doubt this problem is you Grpc.Core, but there might be something odd with your setup.

**Comment by voroninp** [comment]
[GrpcTrace.txt](https://github.com/grpc/grpc/files/12790322/GrpcTrace.txt)

@jtattermusch , here's the trace.

**Comment by tonydnewell** [comment]
It looks like the DNS resolution is taking a long time.

Try changing the DNS resolver to use the native resolver using the GRPC_DNS_RESOLVER environment variable and see if that helps. (See https://github.com/grpc/grpc/blob/master/doc/environment_variables.md ).  If that does then it looks like something in your local environment.

**Comment by voroninp** [comment]
@tonydnewell. This helped. Thanks.
