### ISSUE TITLE
gRPC C++ performance regression

### ISSUE THREAD

**Issue by jjyao** [grpc/grpc#34645]
### What version of gRPC and what language are you using?
1.59.0, c++

### What operating system (Linux, Windows,...) and version?
Linux

### What did you do?
I'm looking at the benchmark dashboard: https://grafana-dot-grpc-testing.appspot.com/?orgId=1&from=now-2y&to=now. Seems we have perf regression over the time for c++:

<img width="1712" alt="Screenshot 2023-10-10 at 10 30 00 AM" src="https://github.com/grpc/grpc/assets/898023/8e5863ae-13ef-4a7a-9293-1a1287c92ab9">

<img width="561" alt="Screenshot 2023-10-10 at 10 30 40 AM" src="https://github.com/grpc/grpc/assets/898023/c8a2cfd5-a152-43b2-86f1-ba8af2b3d212">

I know one cause is #29160 but seems there are other causes as well?

Is this perf regression expected?

### What did you see instead?

Make sure you include information that can help us debug (full error message, exception listing, stack trace, logs).

See [TROUBLESHOOTING.md](https://github.com/grpc/grpc/blob/master/TROUBLESHOOTING.md) for how to diagnose problems better.

**Comment by jjyao** [comment]
This also matches what we observed in our project when we upgrade grpc from 1.46 to 1.59. We saw 10%-20% regression for some of our benchmarks.

**Comment by pcmoritz** [comment]
This is quite bad and unless it will be fixed means Ray can't use an up-to-date gRPC version. If there are no plans to fix it, we might need to use a different RPC solution going forward.

**Comment by drfloob** [comment]
Hello! First off, I am curious if the performance changes actually impact your production gRPC usage. We have not heard any complaints yet, and it has been over a year. We have seen benchmark regressions, same as you, but we suspect that the implementation is still performant enough that the vast majority of applications are not even close to being bottlenecked on gRPC.

But yes, we are aware. We had to take some performance hits for stability/reliability, and most are temporary and expected to be recouped soon.

The first and largest drop was the removal of the `epollex` poller, which we found to have an fd leak - a problem for long-lived processes under heavy utilization. The code was complex, easy to get wrong, and the original authors had moved on. We opted to remove it for stability, with an expectation that we'll release something more performant in the future - sooner if the need for more performance was apparent and significant.

Otherwise, gRPC is going through a few significant changes under the hood, and there are some emulation and compatibility layers that we expect to go away within a few releases. Those layers do not come for free, but it does mean a mostly seamless transition for users. This is temporary, and the benefits will be significant.

**Comment by jjyao** [comment]
HI @drfloob,

Thanks for the detailed explanation. Glad to hear that the grpc team has plans to bring back (some of) the perf in the near future.

> I am curious if the performance changes actually impact your production gRPC usage

For our Ray serve workload (model serving), we saw about 3% drop for qps and also ~10% increase for latency.

**Comment by drfloob** [comment]
Closing this as non-actionable. The performance solutions are being tracked independently.
