### ISSUE TITLE
Rails 6.1 with Docker, error loading shared library ld-linux-x86-64.so

### ISSUE THREAD

**Issue by JustinusJJ** [grpc/grpc#34884]
### What version of gRPC and what language are you using?
- gRPC Version: 1.59.2
- Ruby: 3.03.

### What operating system (Linux, Windows,...) and version?
- OS: macOS Sonoma 14.0.
- Chip: Apple M1 Pro.

### What runtime / compiler are you using (e.g. python version or version of gcc)
- Ruby on Rails version 6.1.
- Docker: `FROM ruby:3.0.3-alpine.`

### What did you do?
1. Added `gem 'grpc'` to a RoR (6.1) project's Gemfile.
2. Run `docker compose up --build` in a terminal (in the project's Dockerfile, `bundle install` is included).

### What did you expect to see?
No error message, and gRPC is successfully added in the project, able to use gRPC in the project.

### What did you see instead?
In the terminal, this error message is shown:

<img width="934" alt="Screenshot 2023-11-06 at 16 33 08" src="https://github.com/grpc/grpc/assets/61934213/aa9ddef9-ca1b-429f-8896-12983547178f">

### Anything else we should know about your project / environment?
EDIT: My workaround to solve this is changing the docker image to `ruby:3.0.3`.

**Comment by alto-ruby** [comment]
You are running with Docker on M1 Mac, which should be aarch64 Linux, and for now you'll need to build GRPC from source.
However according to your log, you appears have a x86_64 grpc installed, which is why if failed to load. To solve this you can try either
1. check your docker file and make sure you are installing GRPC from source, or
2. run docker in x86 emulation by passing `--platform linux/amd64` (could be very slow)

**Comment by chadlwilson** [comment]
I think the problem is mainly that the image the OP says they were using is Alpine based, which is why the workaround was to use a non-alpine image.

There’s no glibc on alpine so these SOs and symlinks aren’t there. Even with the right architecture, that won’t work. While compatibility layers like gcompat sometimes work, and some folks add glibc into alpine against the alpine maintainers’ advice, generally this is unsupported. Would need to compile grpc from source against must libc (if supported by grpc) but probably more hassle than it’d be worth.

this ticket should probably be closed?

**Comment by JustinusJJ** [comment]
Ah right, I'll close this because it's resolved by changing the docker image.
