### ISSUE TITLE
PubSub Python Library version 2.18.4 on Raspberry Pi creates error GLIBCXX_3.4.29 not found

### ISSUE THREAD

**Issue by samskiter** [grpc/grpc#34888]
I also ran into the bug reported in this SO post:
https://stackoverflow.com/questions/77131535/pubsub-python-library-version-2-18-4-on-raspberry-pi-creates-error-glibcxx-3-4-2

### What version of gRPC and what language are you using?
2.18.4 python

### What operating system (Linux, Windows,...) and version?
Raspbian

```
$ cat /etc/os-release
PRETTY_NAME="Raspbian GNU/Linux 11 (bullseye)"
NAME="Raspbian GNU/Linux"
VERSION_ID="11"
VERSION="11 (bullseye)"
VERSION_CODENAME=bullseye
ID=raspbian
ID_LIKE=debian
HOME_URL="http://www.raspbian.org/"
SUPPORT_URL="http://www.raspbian.org/RaspbianForums"
BUG_REPORT_URL="http://www.raspbian.org/RaspbianBugs"
```

### What runtime / compiler are you using (e.g. python version or version of gcc)

python 3.12.0

### What did you do?
Please provide either 1) A unit test for reproducing the bug or 2) Specific steps for us to follow to reproduce the bug. If there’s not enough information to debug the problem, gRPC team may close the issue at their discretion. You’re welcome to re-open the issue once you have a reproduction.

```
pip install google-cloud-pubsub
python
>>> from google.cloud.pubsub_v1 import PublisherClient
```

### What did you expect to see?

Nothing

### What did you see instead?

```/home/samskiter/<project>/venv/bin/python /home/samskiter/<project>/telemetry_forwarder/telemetry_forwarder.py
Traceback (most recent call last):
  File "/home/samskiter/<project>/telemetry_forwarder/telemetry_forwarder.py", line 7, in <module>
    from google.cloud.pubsub_v1 import PublisherClient
  File "/home/samskiter/<project>/venv/lib/python3.12/site-packages/google/cloud/pubsub_v1/__init__.py", line 17, in <module>
    from google.cloud.pubsub_v1 import types
  File "/home/samskiter/<project>/venv/lib/python3.12/site-packages/google/cloud/pubsub_v1/types.py", line 27, in <module>
    from google.api_core import gapic_v1
  File "/home/samskiter/<project>/venv/lib/python3.12/site-packages/google/api_core/gapic_v1/__init__.py", line 16, in <module>
    from google.api_core.gapic_v1 import config
  File "/home/samskiter/<project>/venv/lib/python3.12/site-packages/google/api_core/gapic_v1/config.py", line 23, in <module>
    import grpc
  File "/home/samskiter/<project>/venv/lib/python3.12/site-packages/grpc/__init__.py", line 22, in <module>
    from grpc import _compression
  File "/home/samskiter/<project>/venv/lib/python3.12/site-packages/grpc/_compression.py", line 20, in <module>
    from grpc._cython import cygrpc
ImportError: /lib/arm-linux-gnueabihf/libstdc++.so.6: version `GLIBCXX_3.4.29' not found (required by /home/samskiter/<project>/venv/lib/python3.12/site-packages/grpc/_cython/cygrpc.cpython-312-arm-linux-gnueabihf.so)```

### Anything else we should know about your project / environment?

**Comment by samskiter** [comment]
Wondering outloud... Could this be related to this: https://github.com/rust-lang/rustup/issues/3342

**Comment by samskiter** [comment]
I have downgraded my python back to raspbian default of 3.9 and no-longer see this issue.

Testing 3.11 now...

**Comment by XuanWang-Amos** [comment]
This looks like the same issue mentioned here: https://forums.raspberrypi.com/viewtopic.php?p=2120017&hilit=glibcxx#p2120017

To quote: `The precompiled package wants a newer libstdc++ than is provided with Bullseye. Options are to compile it yourself or to wait for the release of Raspberry Pi OS Bookworm.`

You can try couple of things:
* Since the library is part of gcc compiler, you can try Install a newer version of gcc (Table of versions of gcc and versions of appropriate libstdc++ can be found [here](https://gcc.gnu.org/onlinedocs/libstdc++/manual/abi.html)).
* Try downgrade grpc version.
* Wait for the release of Raspberry Pi OS Bookworm.


Other useful command:
* Get details of system libstdc++: `ls /lib/arm-linux-gnueabihf/libstdc++.so.6`
* Check GLIBCXX versions: `strings /lib/arm-linux-gnueabihf/libstdc++.so.6 | grep GLIBCXX`
