### ISSUE TITLE
gRPC client gets a "settings timeout" when accessing an older server

### ISSUE THREAD

**Issue by chrisse74** [grpc/grpc#35380]
### What version of gRPC and what language are you using?
gRPC 1.60.0 against 1.36.1
C++ (cmake build)

### What operating system (Linux, Windows,...) and version?
Redhat Enterprise Linux 9.3

### What runtime / compiler are you using (e.g. python version or version of gcc)
clang 17.0.6

### What did you do?
Issued a call to the remote server (1.36.1) which waits 2 Minutes, then returns.

### What did you expect to see?
The call returns successfully.

### What did you see instead?
After 1 Minute:
```
    Server side error message:
    settings timeout

    gRPC error 'unavailable' (status code 14) received in MyProgram on host myHost
```

### Anything else we should know about your project / environment?
**Configuration**
We set 
* channelArguments.SetInt(GRPC_ARG_KEEPALIVE_TIME_MS, 10 * 60 * 1000); // 10 minutes
* but do not set GRPC_ARG_KEEPALIVE_TIMEOUT_MS (to keep the default value)

Seems to me, that the Server using gRPC Version 1.36.1 does not send a settings ACK back and thus the 'settings timeout' is triggered on the client side.

**Workaround**
we set "grpc.http2.settings_timeout" to a sufficiently high value, effectively disabling it.
`channelArguments.SetInt("grpc.http2.settings_timeout", 1000U * 60U * 60U * 48U); // deactivate 'setting timeout' error: using 2 days`

**Comment by markdroth** [comment]
It's actually waiting for the initial SETTINGS frame itself, not the ACK.  The server is supposed to send that immediately as soon as the client connects, and all gRPC versions should be doing that.

That having been said, 1.36.1 is a very old version of gRPC, so even if there was a bug there, we're not going to patch it at this point.  Can you please try with the most recent version and see if this problem is still occurring?

**Comment by markdroth** [comment]
Sorry, I take back part of what I said there -- I was initially thinking that this was related to the changes we made a while back to wait for the initial SETTINGS frame before we considered the connection establishment to be successful, but it looks like you are actually talking about code that was added more recently to impose a timeout on the SETTINGS ACK.

@ctiller, can you think of any reason why an older version of gRPC would not be sending a SETTINGS ACK?

Either way, I think upgrading from 1.36.1 is appropriate at this point, since it's really old.  But it would be good to know if we expect this to be a problem.

**Comment by ctiller** [comment]
I'm unaware of any bugs relating to not sending settings ack (though I could believe it), but we have seen cases where very low-bandwidth connections can queue ping acks (and likely settings acks) for quite a long period of time with older versions of gRPC.

The settings ack enforcement is a necessary part of our [HTTP/2 Rapid Reset](https://cloud.google.com/blog/products/identity-security/how-it-works-the-novel-http2-rapid-reset-ddos-attack) mitigations so I can't see us dropping it, and so if it's causing trouble I'd also encourage upgrading.

**Comment by chrisse74** [comment]
Well if a newer client contacts an older one (the 1.36.1 version for example - we did not test for other versions) then it will get disconnected after 2 minutes. As the caller does not always have a say, which gRPC version is unsed on the server, there has to be some mechanims to prevent that disconnect on the client side. Maybe that mechanism is setting the "grpc.http2.settings_timeout" to a very high value and thereby deactivating the feature...

For us its an issue where we have to provide backward compatibility.

**Comment by chrisse74** [comment]
Thanks for pointing us to the rapid-reset attack, btw. I can see why you can't just deactivate the feature.

**Comment by markdroth** [comment]
We could consider exposing the "grpc.http2.settings_timeout" channel arg for others to use (i.e., defining the arg in an include file instead of in the src tree).  But I don't think there's anything else we can really do about this.

And I do think you should upgrade from 1.36.1 on that server.  That version is extremely old and probably has quite a few bugs.

**Comment by markdroth** [comment]
Doesn't look like there's anything immediately actionable here, so I'm going to close.  Please reopen if needed.
