### ISSUE TITLE
[ARM64-AMD64][Dockerfile] - cant install grpcio using alpine python

### ISSUE THREAD

**Issue by kfirfer** [grpc/grpc#35446]
Hello

I'm trying to build docker image from this Dockerfile:
```
FROM python:3.11-alpine
ENV GRPC_PYTHON_BUILD_SYSTEM_OPENSSL=1
ENV GRPC_PYTHON_BUILD_SYSTEM_ZLIB=1
RUN apk add python3-dev
RUN apk add gcc g++ linux-headers
RUN pip install --upgrade pip
RUN pip install --upgrade wheel
RUN pip install --upgrade setuptools
RUN pip install grpcio==1.60.0
```

But its stuck forever on:
```
Building wheel for grpcio (setup.py): still running... 
```

Im trying to build `linux/arm64` on an `linux/amd64` machine
This is the commands im running under docker desktop latest version v4.26.1, ubuntu 22.04.3 LTS, amd64:
```
docker context create builder-context
docker buildx create --name builderx --driver docker-container --use builder-context
docker buildx build --provenance false --no-cache --platform linux/arm64 --tag python-grpcio-test .
```

How can I fix this ? what have I did wrong ?
Thanks !

**Comment by XuanWang-Amos** [comment]
I think it's the same issue mentioned here: https://github.com/grpc/grpc/issues/34998

Because we don't have wheels for musllinux aarch64, it will take a long time to build from source and eventually timeout.

Again, adding wheels for musllinux aarch64 it's not on our roadmap right now, please leave a comment to the issue mentioned above so we can adjust priorities based on reactions.

**Comment by XuanWang-Amos** [comment]
Closing this one assume it's a duplicate, feel free to reopen if it's not.
