### ISSUE TITLE
tests.py.test fails

### ISSUE THREAD

**Issue by ctiller** [grpc/grpc#3577]
https://grpc-testing.appspot.com/job/gRPC_master/7727/config=opt,language=python,platform=macos/consoleFull

**Comment by dgquintas** [comment]
Failing. Seems to be due to coverage issues? https://grpc-testing.appspot.com/job/gRPC_master/7773/config=dbg,language=python,platform=linux/console

**Comment by dklempner** [comment]
https://grpc-testing.appspot.com/job/gRPC_master/7801/config=opt,language=python,platform=linux/console

**Comment by ctiller** [comment]
Occurs on pull requests also, upgrading to P0.

https://grpc-testing.appspot.com/job/gRPC_pull_requests/3487/config=dbg,language=python,platform=linux/

**Comment by nathanielmanistaatgoogle** [comment]
In https://grpc-testing.appspot.com/job/gRPC_master/7773/config=dbg,language=python,platform=linux/console does `Slave 'gw3' crashed while running 'grpc_test/_adapter/_intermediary_low_test.py::EchoTest::testManyOneByteEchoes'` indicate a py.test-level failure or a Jenkins-level failure? Also earlier in that same output there's `Replacing crashed slave gw3`; does that indicate that the tool attempted to recover from the crash but still reported overall failure?

In all of these the output feels like a mess - @soltanmm, do you agree and do we have any options for improving it? (https://grpc-testing.appspot.com/job/gRPC_master/7801/config=opt,language=python,platform=linux/console says `FAILED: Some tests failed` - is there any way of determining which test(s) failed (timed out)?)

At least https://grpc-testing.appspot.com/job/gRPC_pull_requests/3487/config=dbg,language=python,platform=linux/console is a timing-related failure of the alpha API - I've been planning to simply kill those tests rather than deflake them; now may be the time for that.

**Comment by ctiller** [comment]
RE: FAILED: Some tests failed

This is generated by run_tests.py which doesn't currently (but easily
could) track a list of failed tests and print a list (bazel style) on exit.
I'd happily review a PR to have it do so.

**Comment by soltanmm** [comment]
@nathanielmanistaatgoogle That `gw3` thing is a `py.test`-level failure. `py.test` recovers slaves to continue performing testing jobs, but does not recover the jobs themselves AFAIK.

Yes, the output is a mess. Options to have it be nicer include redirection of stderr w/o filtering `py.test` output (to filter out gRPC-core level information), having `run_tests.py` somehow become aware of what tests are running and individually taking up time (which'd also require, I *think*, another custom `py.test` plug-in to have it speak with `run_tests.py`), writing our own coverage support and moving back to running all unittests from `run_tests.py`, enumerating all tests and invoking `py.test` on each test while aggregating coverage information (as opposed to outright overwriting it per `py.test` invocation; I think this is possible), and perhaps others that might arise after looking deeper at `py.test` configuration options...

... Improving our testing output needs a bit of thought, methinks, to avoid writing way more than we should.

Are we killing the alpha tests?

**Comment by ctiller** [comment]
https://grpc-testing.appspot.com/job/gRPC_pull_requests/3548/config=opt,language=python,platform=linux/testReport/junit/(root)/tests/py_test/

**Comment by soltanmm** [comment]
https://grpc-testing.appspot.com/job/gRPC_pull_requests/3558/config=dbg,language=python,platform=linux/testReport/junit/(root)/tests/py_test/

I didn't think through the print-more-things-out deal. The output needs to mention which tests were started...

**Comment by murgatroid99** [comment]
https://grpc-testing.appspot.com/job/gRPC_master/7965/config=dbg,language=python,platform=macos/console

**Comment by ctiller** [comment]
Any strategy for fixing this?

**Comment by soltanmm** [comment]
cc #3787

**Comment by a11r** [comment]
Another failure on macos.
config=dbg,language=python,platform=macos

https://grpc-testing.appspot.com/job/gRPC_master/12375/config=dbg,language=python,platform=macos/testReport/(root)/tests/py_test/

**Comment by soltanmm** [comment]
The tests shouldn't even be running on Mac OS at the moment...

**Comment by jtattermusch** [comment]
Seen timeout on linux today.

https://grpc-testing.appspot.com/job/gRPC_master/12733/config=opt,language=python,platform=linux/testReport/(root)/tests/py_test/

**Comment by soltanmm** [comment]
Once #4005 is finished and goes through that particular one shouldn't happen again, methinks.

**Comment by jcanizales** [comment]
Pinging per the build pony's policy (https://grpc-testing.appspot.com/job/gRPC_master/12763/config=opt,language=python,platform=linux/testReport/(root)/tests/py_test/).

**Comment by murgatroid99** [comment]
Seen again, I think: https://grpc-testing.appspot.com/job/gRPC_master/13042/config=dbg,language=python,platform=linux/testReport/junit/(root)/tests/py_test/
