### ISSUE TITLE
"Sent message larger than max (X vs. Y)" - Error Message shows correct value for Y only if X is close to value, otherwise reverts to 4194304

### ISSUE THREAD

**Issue by pjchungmd** [grpc/grpc#35805]
### What version of gRPC and what language are you using?
1.60.1
Python

### What operating system (Linux, Windows,...) and version?
OSX 14.2.1, M1 Macbook

### What runtime / compiler are you using (e.g. python version or version of gcc)
Python 3.10
Apple clang version 14.0.3 (clang-1403.0.22.14.1)

### What did you do?
I am attempting to send a gRPC request to a ray server. I have been unable to send requests of sizes >4 MB. On the ray server side the grpc.max_send_message_length and grpc.max_receive_message_length values are both 512 * 1024 * 1024. I have attempted to increase the limits on the client side using:

````
channel = grpc.insecure_channel("localhost:9000", options=[('grpc.max_send_message_length', 512 * 1024 * 1024),  ('grpc.max_receive_message_length', 512 * 1024 * 1024),])
stub = MyServiceStub(channel)
````

and then call with

````
response, call = stub.__call__.with_call(request=request)
````

Initially this always gave the following:

````
_InactiveRpcError: <_InactiveRpcError of RPC that terminated with:
	status = StatusCode.RESOURCE_EXHAUSTED
	details = "Received message larger than max (154535992 vs. 4194304)"
````

But if I change the options to: `('grpc.max_send_message_length', 147 * 1024 * 1024),` I get the following message:

````
_InactiveRpcError: <_InactiveRpcError of RPC that terminated with:
	status = StatusCode.RESOURCE_EXHAUSTED
	details = "Sent message larger than max (154535992 vs. 154140672)"
````

This repeatable for other values provided that the request size (X) and limit size (Y) are close to each other, but X > Y. If X >> Y then the error message returns `4194304` instead. (I have not calculated the exact value that X-Y needs to be for this to occur).

Also, the ray serve logs do not show any errors on the server side, therefore it seems that there is an issue is on the client side preventing me from increasing the `'grpc.max_send_message_length'` value.

### What did you expect to see?

Successfully send larger requests to my server (which has a receive limit of 512 MB).

### What did you see instead?

Errors such as:

````
_InactiveRpcError: <_InactiveRpcError of RPC that terminated with:
	status = StatusCode.RESOURCE_EXHAUSTED
	details = "Sent message larger than max (154535992 vs. 154140672)"
````

### Anything else we should know about your project / environment?

Using `ray[serve]` 2.9.1.

**Comment by gnossen** [comment]
@yashykt Can you please take a look? This channel arg is piped straight to core.

**Comment by yashykt** [comment]
I am unfamiliar with the RPCs used by a ray server. Can you shed some details please? Is it a unary RPC? 
Are the clients and the servers both sending large messages?

From the error "Received message larger than max (154535992 vs. 4194304)", it's not clear to me whether it is the client complaining about it or the server.

From you description, it seems like the client is the one trying to send larger messages, so it is possible that this is error is coming from the server.

The error "Sent message larger than max (154535992 vs. 154140672)" makes sense since your send limits are now lower than the size of the message you are sending. (Note the difference between the error messages around sent vs received.)

If I assume that gRPC doesn't have a bug, there are two possibilities I can think of here - 
1) The server is not actually configured to higher receiving limit.
2) The server is receiving the higher limit message, accepting it and responding with a big message as well, which is then getting rejected by the client.

My suspicion is that the first scenario is the more likely one here.

**Comment by yashykt** [comment]
I've just opened #36103 to make the error message clear
