### ISSUE TITLE
Obj-C cannot resolve nodename nor servname provided or not known

### ISSUE THREAD

**Issue by mdering** [grpc/grpc#3682]
When I try to run an the helloworld objective-C client and a python server, I get 

> [resolve_address_posix.c:119] getaddrinfo: nodename nor servname provided, or not known.

OSX El Capitan, xcode 7.0.1 Simulator version 9.0

**Comment by mdering** [comment]
it appears that this is happening because you're trying to force people to use SSL. Is there a reason for this? Was that the intention?

**Comment by mdering** [comment]
to clarify, if i modify the gRPCHosts.m file to not force SSL, it works. By default all connections even ones starting with http: are added as secure, and the addition of https:// to the beginning breaks the parsing mechanism. I've made changes for my own purposes but this isnt a long term solution, so I don't want to push. Was there an intent behind these changes? they appear to have been made months ago.

**Comment by murgatroid99** [comment]
`gRPCHosts.m` doesn't decide whether the connection is TLS or not. That `https://` there is kind of a red herring in this investigation; the `hostURL` object is just used to parse a provided address, which should not have a protocol specifier.

For an example of how to make a connection without TLS, see [`tests/InteropTestsLocalCleartext.m`](https://github.com/grpc/grpc/blob/master/src/objective-c/tests/InteropTestsLocalCleartext.m).

**Comment by mdering** [comment]
I've been basing it off of the helloworld example (which does not currently work for me, nor for a coworker). It seems like the _secure=YES tries to enforce something.

**Comment by mdering** [comment]
the problem with the adding the https:// I think is that it messes up the host parsing later so that it thinks that the host address is "http" instead of whatever its supposed to be

**Comment by murgatroid99** [comment]
Well, I am having trouble getting the example to work, but I'm getting a different error than you're describing. And you're right, it looks like the `_secure` variable is in fact used to determine whether to initiate a secure connection. And the API used in the file I referenced is only available in tests.

**Comment by mdering** [comment]
Life is a rich tapestry. My fix was to change _secure to NO, which isn't right either (and to take http:// out of the host name). I don't know objective-c at all, otherwise I'd make a pull request and fix it myself.

**Comment by jcanizales** [comment]
> it appears that this is happening because you're trying to force people to use SSL. Is there a reason for this? Was that the intention?

The intention isn't to force using SSL, rather than using cleartext requires explicit opt in that's easy to spot on a code review. That's why the switch was made from having people specify `"http://"` to having them call `[GRPCCall useInsecureConnectionsForHost:myHost]` (as in the test Michael pointed to). The reason is we don't want anybody using cleartext inadvertently.

The scheme part of the server's URL doesn't need to be specified anymore.

I'm currently going over all samples to ensure they're up-to-date (#3371). Sorry for the time it's costed you.

**Comment by murgatroid99** [comment]
As far as I can tell, `useInsecureConnectionsForHost` is only in `GRPCCall+Test.h`. Is that intended to be a public header?

**Comment by jcanizales** [comment]
Yes, it's a public header, as used in the test; all private headers are under `private/`.

**Comment by mdering** [comment]
so I should be using GRPCCall+Test.h for unsecured communication from now on? Will the examples be updated to reflect this?

**Comment by murgatroid99** [comment]
The `+Test` suffix in the name seems to imply that it's only there to be used by the tests. If we expect actual users to call it, we should probably just put it in `GRPCCall.h`.

**Comment by jcanizales** [comment]
I agree that it being in the Test category is misleading. Both methods there have use cases outside of tests when the user controls the server or the network. We should find a better name for the category and have `GRPCCall+Test.h` just import that other one.

The biggest problem for now is fixing the samples, though. I reckon the majority of users find how to do these things through them rather than exploring the library's headers.

**Comment by jcanizales** [comment]
@mdering: Yes and yes. Please give it a try and, if it works as intended, we can close this issue (there's already #3371 for the samples).

**Comment by mdering** [comment]
I'm not 100% sure how this would look. how would I swap this out, would it be on client creation, would that be the only change?

**Comment by jcanizales** [comment]
You have to call it once for every host address, before creating any client object to that host:

```objective-c
[GRPCCall useInsecureConnectionsForHost:myHost];
...
[MyProtoService serviceWithHost:myHost];
```

That's the only thing you should need to do to renounce to TLS. Because we're using sockets directly, you currently won't need to add an [App Transport Security exception](https://developer.apple.com/library/prerelease/ios/technotes/App-Transport-Security-Technote/) to the `Info.plist` file of your app. But you should anyway, because we might move to using `NSURLSession` under the hood if it supports gRPC in the future.

**Comment by jcanizales** [comment]
@mdering, I've [updated the hellow_world sample](https://github.com/grpc/grpc/pull/3808/files#diff-511080d40641aa50f162b2d3c4590b2f) to reflect these changes and tested it. Please give it a try and let us know if you're still having trouble.

**Comment by mdering** [comment]
that seems to have worked. Thanks so much.
