### ISSUE TITLE
BoringSSL-GRPC podspec is incompatible with Xcode 16b1

### ISSUE THREAD

**Issue by sergiocampama** [grpc/grpc#36888]
### What version of gRPC and what language are you using?
BoringSSL-GRPC 0.0.24

### What operating system (Linux, Windows,...) and version?
macOS

### What runtime / compiler are you using (e.g. python version or version of gcc)
Xcode 16b1 (recently launched on WWDC)

### What did you do?
Used the BoringSSL-GRPC dependency (through Firebase)

### What did you expect to see?
The project to compile

### What did you see instead?

`clang: error: unsupported option '-G' for target 'arm64-apple-ios15-simulator'`

Was able to trace this to the usage of the `-GCC_WARN_INHIBIT_ALL_WARNINGS` compiler flag, by removing this flag, I am able to compile succcessfully. This flag is being added in the BoringSSL-GRPC.podspec file.

It is not clear whether the right solution is to remove the flag from the podspec, I've also filed a radar to Apple to look into this.

**Comment by sergiocampama** [comment]
```
The option appears to get ignored in Xcode 15: 

❯ clang -GCC_WARN_INHIBIT_ALL_WARNINGS main.c   
clang: warning: argument unused during compilation: '-G CC_WARN_INHIBIT_ALL_WARNINGS' [-Wunused-command-line-argument]

But in 16 it has become an error:

❯ clang -GCC_WARN_INHIBIT_ALL_WARNINGS main.c
clang: error: unsupported option '-G' for target …

So this was most likely always being passed incorrectly by the underlying library and has just now been surfaced because of a change to clang, but ultimately not a bug.
```

that's the answer I got from Apple, so it looks like we should indeed remove the `-GCC_WARN_INHIBIT_ALL_WARNINGS` flag from the podspecs

**Comment by Knapiii** [comment]
```
    installer.pods_project.targets.each do |target|
      target.build_configurations.each do |config|
        config.build_settings['GCC_WARN_INHIBIT_ALL_WARNINGS'] = "NO"
      end
    end
```

Can this be a fix in the Podfile?

**Comment by Knapiii** [comment]
Can I manually fix this on my project?

**Comment by Knapiii** [comment]
I have looked through BoringSSL-GRPC folder in my `/Pods` folder. cant locate the `.podspec` file

**Comment by OscarHedeby** [comment]
@Knapiii you can remove it from the Pods/project.pbxproj file, just remove all occurrences and it should run.

**Comment by Knapiii** [comment]
> @Knapiii you can remove it from the Pods/project.pbxproj file, just remove all occurrences and it should run...
> 
> Or follow the guide in this issue (which is definitely the better solution) #36904

This solution worked perfectly. Thanks!

**Comment by Megabyte94** [comment]
> @Knapiii you can remove it from the Pods/project.pbxproj file, just remove all occurrences and it should run...
> 
> Or follow the guide in this issue (which is definitely the better solution) #36904

Hi.

I added `post_install do |installer|
  installer.pods_project.targets.each do |target|
    if target.name == 'BoringSSL-GRPC'
      target.source_build_phase.files.each do |file|
        if file.settings && file.settings['COMPILER_FLAGS']
          flags = file.settings['COMPILER_FLAGS'].split
          flags.reject! { |flag| flag == '-GCC_WARN_INHIBIT_ALL_WARNINGS' }
          file.settings['COMPILER_FLAGS'] = flags.join(' ')
        end
      end
    end
    flutter_additional_ios_build_settings(target)
    target.build_configurations.each do |config|
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '13.0'
    end
  end
end` to the end of my Podfile, as suggested in the StackOverflow forum, but now I'm getting this error (instead of what I was getting before: "unsupported option '-G' for target '<target>'"): `Launching lib/main.dart on iPhone 15 Pro in debug mode...
Running pod install...                                             88.3s
Running Xcode build...                                                  
 └─Compiling, linking and signing...                        27.8s
Xcode build done.                                           1011.6s
Failed to build iOS app
Lexical or Preprocessor Issue (Xcode): Include of non-modular header inside framework module 'firebase_auth.FLTAuthStateChannelStreamHandler':
'/Users/kenneth_busta/Desktop/Coding/Learning/Dart-Flutter/notes/ios/Pods/Headers/Public/Firebase/Firebase.h'
/Users/kenneth_busta/.pub-cache/hosted/pub.dev/firebase_auth-5.1.0/ios/Classes/Private/FLTAuthStateChannelStreamHandler.h:12:8


Lexical or Preprocessor Issue (Xcode): Include of non-modular header inside framework module 'firebase_auth.PigeonParser':
'/Users/kenneth_busta/Desktop/Coding/Learning/Dart-Flutter/notes/ios/Pods/Headers/Public/Firebase/Firebase.h'
/Users/kenneth_busta/.pub-cache/hosted/pub.dev/firebase_auth-5.1.0/ios/Classes/Private/PigeonParser.h:6:8


Lexical or Preprocessor Issue (Xcode): Include of non-modular header inside framework module 'firebase_auth.FLTIdTokenChannelStreamHandler':
'/Users/kenneth_busta/Desktop/Coding/Learning/Dart-Flutter/notes/ios/Pods/Headers/Public/Firebase/Firebase.h'
/Users/kenneth_busta/.pub-cache/hosted/pub.dev/firebase_auth-5.1.0/ios/Classes/Private/FLTIdTokenChannelStreamHandler.h:12:8


Lexical or Preprocessor Issue (Xcode): Include of non-modular header inside framework module 'firebase_auth.FLTPhoneNumberVerificationStreamHandler':
'/Users/kenneth_busta/Desktop/Coding/Learning/Dart-Flutter/notes/ios/Pods/Headers/Public/Firebase/Firebase.h'
/Users/kenneth_busta/.pub-cache/hosted/pub.dev/firebase_auth-5.1.0/ios/Classes/Private/FLTPhoneNumberVerificationStreamHandler.h:12:8


Lexical or Preprocessor Issue (Xcode): Include of non-modular header inside framework module 'firebase_auth.FLTFirebaseAuthPlugin':
'/Users/kenneth_busta/Desktop/Coding/Learning/Dart-Flutter/notes/ios/Pods/Headers/Public/Firebase/Firebase.h'
/Users/kenneth_busta/.pub-cache/hosted/pub.dev/firebase_auth-5.1.0/ios/Classes/Public/FLTFirebaseAuthPlugin.h:6:8


Could not build the application for the simulator.
Error launching application on iPhone 15 Pro.`


Do you know why I'm getting this and how to solve it? Thank you very much.

**Comment by PyDeKa** [comment]
My solution for this problem, works well with debug and release. :) 

https://stackoverflow.com/a/78651666/25662983

**Comment by ostatnicky** [comment]
Or this is enough https://stackoverflow.com/a/78633109/1054550
```
post_install do |installer|
  installer.pods_project.targets.each do |target|
    if target.name == 'BoringSSL-GRPC'
      target.source_build_phase.files.each do |file|
        if file.settings && file.settings['COMPILER_FLAGS']
          flags = file.settings['COMPILER_FLAGS'].split
          flags.reject! { |flag| flag == '-GCC_WARN_INHIBIT_ALL_WARNINGS' }
          file.settings['COMPILER_FLAGS'] = flags.join(' ')
        end
      end
    end
  end
end
```

**Comment by HannahShiSFB** [comment]
Fixed in 1.65.2 and 1.66.0-pre1 release

**Comment by smanzini** [comment]
> @Knapiii you can remove it from the Pods/project.pbxproj file, just remove all occurrences and it should run...
> 
> Or follow the guide in this issue (which is definitely the better solution) #36904

@OscarHedeby I cannot find BoringSSL-GRPC files in my /Pods folder and neither Pods/project.pbxproj, can you help me?

**Comment by smanzini** [comment]
> -GCC_WARN_INHIBIT_ALL_WARNINGS

hi @Knapiii I cannot find as well, have you solved? can you help me? thanks

**Comment by mario-bermonti** [comment]
> My solution for this problem, works well with debug and release. :)
> 
> https://stackoverflow.com/a/78651666/25662983

I was able to fix this issue that had given me a headache for the past week following @PyDeKa's solution. Thank you so much!

I did not have to remove pods, DerivedData, or any of those steps, just had to `pod install —repo-update`, though.

**Comment by NayakKrish** [comment]
I am getting this issue in my react-native project after updating Xcode (Xcode 16.0). i tried to do this solution [https://github.com/firebase/firebase-ios-sdk/issues/13115](https://github.com/firebase/firebase-ios-sdk/issues/13115) from paulb777 but my 'ssl_transcript.cc' file is different.

**Comment by HaraldNordgren** [comment]
Seems what works for now is to ignore errors:

https://stackoverflow.com/a/78633109/4237316

**Comment by umairyaqub31** [comment]
Hi! If anyone having this issue in react native with xcode 16.2, Here is a fix for you

Put these lines in podfile

pod 'gRPC-C++', '~> 1.65.0'
pod 'gRPC-Core', '~> 1.65.0'

if you are using below version set it to 1.65.0 or higher may be 1.66.0

Now upgrade your firebase libraries to latest 

    "@react-native-firebase/app": "^21.12.0",
    "@react-native-firebase/auth": "^21.12.0",
    "@react-native-firebase/firestore": "^21.12.0",
    "@react-native-firebase/messaging": "^21.12.0",
    "firebase": "^11.4.0",

here is an example the versions i have used

Run following commands

rm -rf pods
rm -rf ios/Podfile.lock 
pod repo update 
pod install

Open project in xcode

Clean build folder
Remove DerivedData 
Run build 

And you are good to go.

**Comment by kenstack-ltd** [comment]
<img width="591" alt="Image" src="https://github.com/user-attachments/assets/6f2a08d2-c321-483e-886d-681d3320b1a8" />

I applied your solution but it doesn't work.

**Comment by umairyaqub31** [comment]
Can you share you podfile

**Comment by umairyaqub31** [comment]
> <img alt="Image" width="591" src="https://private-user-images.githubusercontent.com/100079397/424784176-6f2a08d2-c321-483e-886d-681d3320b1a8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NDI0NDA0OTIsIm5iZiI6MTc0MjQ0MDE5MiwicGF0aCI6Ii8xMDAwNzkzOTcvNDI0Nzg0MTc2LTZmMmEwOGQyLWMzMjEtNDgzZS04ODZkLTY4MWQzMzIwYjFhOC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjUwMzIwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI1MDMyMFQwMzA5NTJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0zYzMyYmE1NzNiNWNkNDQ2NTY2MzBhZWZjYWMyZjM3NjcwODkxNDkyYmY4ZmIwYmM1NmIzMWQ0ZTQ3MmY2YmJmJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.ILQ90r6WXXuTPYyNRBkxG8VcODncd3WuiOw5vX9yrxY">
> I applied your solution but it doesn't work.

Share your podfile and package json

**Comment by umairyaqub31** [comment]
> <img alt="Image" width="591" src="https://private-user-images.githubusercontent.com/100079397/424784176-6f2a08d2-c321-483e-886d-681d3320b1a8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NDI0NDA0OTIsIm5iZiI6MTc0MjQ0MDE5MiwicGF0aCI6Ii8xMDAwNzkzOTcvNDI0Nzg0MTc2LTZmMmEwOGQyLWMzMjEtNDgzZS04ODZkLTY4MWQzMzIwYjFhOC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjUwMzIwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI1MDMyMFQwMzA5NTJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0zYzMyYmE1NzNiNWNkNDQ2NTY2MzBhZWZjYWMyZjM3NjcwODkxNDkyYmY4ZmIwYmM1NmIzMWQ0ZTQ3MmY2YmJmJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.ILQ90r6WXXuTPYyNRBkxG8VcODncd3WuiOw5vX9yrxY">
> I applied your solution but it doesn't work.

There is an issue in your podfile  you are using >= to with the version use this instead   '~> 1.65.0'
