### ISSUE TITLE
Missed nullptr checks in MaybeUpdateConnectivityStateLocked() RR lb_policy functions

### ISSUE THREAD

**Issue by leeriorio** [grpc/grpc#37673]
In result of static analyse of grpc source code with Svace static analyzer I found two similar error with "null_after_deref" category (situations where first, a pointer is dereferenced, and then it is compared to null) in round_robin LB policy sources.

It affects two similar methods:

https://github.com/grpc/grpc/blob/0aca67e7d63c04b7466432af3597f18d5bf1e279/src/core/load_balancing/round_robin/round_robin.cc#L349

https://github.com/grpc/grpc/blob/0aca67e7d63c04b7466432af3597f18d5bf1e279/src/core/load_balancing/weighted_round_robin/weighted_round_robin.cc#L935

The problem is that there is dereference of `endpoint_list_` to get `num_ready_` value in conditional expressions. But below, in body of this block, `endpoint_list_` is compares with `nullptr`. 

```c++
if ( (...) &&
      ( round_robin->endpoint_list_->num_ready_ == 0 ||
       ... ||
       ... ) {
    if (...)) {
      const std::string old_counters_string =
          round_robin->endpoint_list_ != nullptr
              ? ...
              : ...;
     ...
    }
}
```

So, looking only on function context, I have a question: if `round_robin->endpoint_list_`  (or `wrr->endpoint_list_` ) can be `nullptr`, should we check it before get `num_ready_` value?

If you look at the history of this code, there was this check in this context in line 341

https://github.com/grpc/grpc/blob/1cd6e69347cbf62a012477fe184ee6fa8f25d32c/src/core/ext/filters/client_channel/lb_policy/round_robin/round_robin.cc#L340-L348

**Comment by markdroth** [comment]
I don't believe it's actually possible for `endpoint_list_` to be null there.  That used to be possible, because we used to leave that field unset on the initial update until we promoted `latest_pending_subchannel_list_` to `subchannel_list_`, which would often happen well after `UpdateLocked()` was called.   But I changed it in #28339 such that `UpdateLocked()` will immediately do that promotion on the initial update (that code is currently [here](https://github.com/grpc/grpc/blob/f3ab98e094a2ba7afcf38623498de4db683f84a3/src/core/load_balancing/round_robin/round_robin.cc#L274)), so this edge case no longer occurs.  In that same PR, I removed the now-unnecessary check for `subchannel_list_` being null that you pointed out above, but I forgot to remove the second check when initializing `old_counters_string`.  And I cloned the RR code as a starting point when I implemented the WRR policy, so the additional check wound up getting propagated there as well.

There is no bug here.  We can remove the unnecessary duplicate check when initializing `old_counters_string`, but having it there doesn't really hurt anything.
