### ISSUE TITLE
Use of local time zone

### ISSUE THREAD

**Issue by daniel-eiband-snkeos** [grpc/grpc#37766]
I'm not sure if this is a bug but I was wondering whether using the local time zone [here](https://github.com/grpc/grpc/blob/e0c6055d21b40ed0baccd38472f4c6d7acc517ea/src/core/lib/gprpp/status_helper.cc#L290) and [here](https://github.com/grpc/grpc/blob/e0c6055d21b40ed0baccd38472f4c6d7acc517ea/src/core/lib/security/authorization/stdout_logger.cc#L46) is actually intended? I would have expected something that is server configured or simply the UTC time zone.

**Comment by eugeneo** [comment]
I understand you are reporting this due to performance issue in Abseil. Currently there does not seem any other reason to change the gRPC behavior.

I will close this issue unless Abseil will not fix their perfomance bug due to some issue.

**Comment by daniel-eiband-snkeos** [comment]
From your response I conclude that it is intended that the server logs in its local time, in particular in the class `StdoutAuditLogger` and the return value of the function `StatusToString()` which seems to be used for logging.

**Comment by eugeneo** [comment]
I am not sure if there had ever been a deliberate decision on what TZ to use in logging. Happened to be the local one. We are open to discussing other options but we need to understand the justification to change the current behavior.

**Comment by daniel-eiband-snkeos** [comment]
I understand. I opened this issue because at first it looked like an oversight to me. [Abseil documentation](https://abseil.io/docs/cpp/guides/time#time-zones) says: "Prefer to use an explicit time zone instead" (of `absl::LocalTimeZone()`).

I have no strong opinion on this so we can keep this issue closed.

**Comment by malkia** [comment]
I'm hitting the same perf issue - both in terms of CPU and increased memory allocations, also possibly some antiviruses might kick in more due to LoadLibrary, etc. I've added some profiling info to @daniel-eiband-snkeos 's issue post here - https://github.com/abseil/abseil-cpp/issues/1760#issuecomment-2495698924

I wonder what would be the best way for me to fix it locally, was thinking of caching the timezone, or alternatively just ignore the time zone (if it's that expensive), or commenting out this code - it's not ideal, but it's blocker for me interally to use `grpc` with this. Granted this happens only when there are grpc problems (grpc::Status is not OK).

**Comment by devbww** [comment]
> I am not sure if there had ever been a deliberate decision on what TZ to use in logging. Happened to be the local one. We are open to discussing other options but we need to understand the justification to change the current behavior.

I would at least suggest that gRPC use `absl::FormatTime(absl::Time, absl::TimeZone)` instead of `absl::FormatTime(absl::Time)`, making the timezone explicit and exposing the opportunity for it to be determined just once, ala ...
```
   absl::TimeZone grpc_timezone() {
    static auto tz = absl::LocalTimeZone();  // TODO: Think about using an explicit timezone instead.
    return tz;
   }
```

@eugeneo @malkia @derekmauro
