### ISSUE TITLE
Protoc always generates code for protobuf==5.27.2

### ISSUE THREAD

**Issue by sparky2708** [grpc/grpc#37946]
Python 3.12

Running:
python -m grpc_tools.protoc --proto_path=... --grpc_python_out=...

My protobuf version installed is 5.28.1 but all files generated by the command above are for 5.27.2. Using latest version of grpc_tools.protoc. Expecting the code to be generated using the protobuf version I have installed.

(Reopening as previous issue got closed by bot because I accidentally tagged it wrong)

**Comment by XuanWang-Amos** [comment]
Hi, this is expected. In short, `grpc_tools` have a fixed dependency on protobuf version, currently it's 5.27.2.

This is because we share the same protobuf dependency in this repo, and it's 5.27.2 for v1.67.x: https://github.com/grpc/grpc/blob/74f245857247b4b3e28a753d85d06ae2d5a55434/bazel/grpc_deps.bzl#L58-L73

**Comment by sparky2708** [comment]
Why does grpc_tools.protoc then need a dependency on protobuf if it has it embedded? That makes it confusing...

**Comment by marcindulak** [comment]
Discussed previously in https://github.com/grpc/grpc/issues/37609

**Comment by sparky2708** [comment]
Thank you. Spent 2 days trying to figure out why `pipdeptree` was showing grpcio-tools was dependent on protobuf 5.28.1 yet the code was generated for 5.27.2. Thought maybe I was missing a flag or had a wrong version of a tool that protoc was calling.
