### ISSUE TITLE
Enable caching on Travis when it becomes available

### ISSUE THREAD

**Issue by jcanizales** [grpc/grpc#4015]
Our tests take ~25min to run, of which 5 are spent making protoc and the protoc plugin, which almost never change, 10 compiling Cocoapods' OpenSSL, and another 5 making the C++ interop test server (the biggest part of that being OpenSSL again).

Tracking issue at Travis: https://github.com/travis-ci/travis-ci/issues/4011

**Comment by nicolasnoble** [comment]
That should become irrelevant once we migrate the iOS testing on Jenkins. Blocked on #6117 however.

**Comment by jcanizales** [comment]
@makdharma How long are test runs taking on Jenkins?

**Comment by makdharma** [comment]
few minutes (<10)

**Comment by ejona86** [comment]
I'm now seeing caching for OS X on Travis :). It may be a bug though, because it is causing some build failures since the cache is being shared between OS X and Linux (which I'm more than happy to fix). And I've not seen an update on https://github.com/travis-ci/travis-ci/issues/4011. Granted, it _just_ started happening.
