### ISSUE TITLE
Compile fails on Ubuntu 14.04 ?

### ISSUE THREAD

**Issue by jgeewax** [grpc/grpc#4105]
I've done a bunch of `apt-get install`ing and now the compile seems to fail on the Make command:

```sh
$ make
... snip ...
[MAKE]    Generating cache.mk
[MAKE]    Building protobuf
checking whether to enable maintainer-specific portions of Makefiles... yes
configure: error: cannot find install-sh, install.sh, or shtool in "." "./.." "./../.."
make: *** [/home/jjg/grpc/libs/opt/protobuf/libprotobuf.a] Error 1
```

I've `apt-get install`ed:

- build-essential
- autoconf
- libtool
- python-all-dev
- python-virtualenv
- zlib1g-dev
- clang
- libc++-dev

**Comment by tbetbetbe** [comment]
Just clarifying: was this an attempt to build grpc from source ?

**Comment by jgeewax** [comment]
Yessir - - trying to compile from source on Ubuntu 14.04:

```sh
$ git clone https://github.com/grpc/grpc.git
$ cd grpc
$ git submodule update --init
$ make  # <-- Here's where things exploded
$ make install
```

**Comment by abhijitsbhopale** [comment]
facing same problem on Ubuntu 14.04

**Comment by ctiller** [comment]
Haven't had a chance to test, but I think you need automake installed also.
You'll also want to git clean the third_party/protobuf submodule to blow
away cached configure scripts.

Hoping to spend some time with the protobuf team to simplify this in the
new year.

Out of curiosity which language were you wanting to use? I'm trying to make
sure that the make process is only useful to 5% of developers - nobody
should really need to be exposed to it.

**Comment by larsonmpdx** [comment]
on a clean install for C++ I need to go into third_party/protobuf and run:

sudo ./autogen.sh (not sure why this requires sudo - maybe it has been
fixed now)
sudo ./configure CC=clang CXX=clang++ (requires sudo because previous step
polluted things)  (clang is optional)
sudo make (requires sudo because previous step polluted things)
sudo make install
sudo ldconfig

then make/make install for grpc will work correctly

**Comment by abhijitsbhopale** [comment]
@ctiller  @larsonmpdx 
Thank you very much for the reply.
$ make     gives error saying, 
In function ‘gpr_cv_wait’: src/core/support/sync_posix.c:84:42: error: conversion to ‘__time_t’ from ‘gpr_int64’ may alter its value [-Werror=conversion] abs_deadline_ts.tv_sec = abs_deadline.tv_sec;
cc1: all warnings being treated as errors
I changed Makefile by replacing  -Werror with -Wno-error then could build and install successfully.

If run $ make  command twice get message saying 
Circular grpc/libs/opt/libboringssl.a <- grpc/libs/opt/libboringssl.a dependency dropped. Is this behavior correct?

I am planning to use gRPC for C++ and  C# language.

**Comment by larsonmpdx** [comment]
the time_t conversion error is still an issue on 32 bit machines (checked today)

**Comment by nicolasnoble** [comment]
Are there still issues with the latest releases? (0.13.2)

**Comment by ctiller** [comment]
Assuming fixed.

**Comment by peterhuene** [comment]
I hate resurrecting a zombie a thread, but I run into this today with my experimentation of getting gRPC working on Alpine Linux (with musl libc).

According to https://github.com/google/protobuf/blob/master/src/README.md, protobuf needs `./autogen.sh` run prior to building it, which is why the build fails with `configure: error: cannot find install-sh, install.sh, or shtool in "." "./.." "./../.."` under these conditions:

* protobuf (3) isn't present on the system.
* the `grpc` repository was cloned recursively, creating `third_party/protobuf` and causing gRPC to attempt to build and install it.

This is with today's master of gRPC.  I see no attempt from gRPC to run `autogen.sh` in the generated Makefile.  Manually running `autogen.sh` prior to gRPC's `make` invocation gets past the problem.

**Comment by johndpope** [comment]
https://gist.github.com/johndpope/503029706ed56d5375d1e9469f0135d4

**Comment by rameshdharan** [comment]
Not sure why this was closed but it is definitely not fixed. 

I just wanted **grpc_cli** on a machine running Ubuntu 14.04. Following the instructions, I installed `libgflags-dev`, ran `git submodule update --init` and then issued `make -j12 grpc_cli`. 

The build failed with:
```
configure.ac:94: error: possibly undefined macro: AC_PROG_LIBTOOL
```

I then tried just `make`, and the build failed with: 
```
configure: error: cannot find install-sh, install.sh, or shtool in "." "./.." "./../.."
```

Cobbling together from the suggestions here I then did: 
```
sudo apt-get install libtool
cd third_party/protobuf
./autogen.sh
```

After that I was able to re-run `make grpc_cli` and I have a working binary.

**Comment by mehrdada** [comment]
@rameshdharan I just started from a new Ubuntu 14.04 VM on GCE and did the following:

```bash
sudo apt-get update
sudo apt-get upgrade -y
sudo apt-get install -y build-essential git libgflags-dev libtool shtool autoconf automake
git clone --recursive https://github.com/grpc/grpc
cd grpc
make -j20 grpc_cli
```

and it worked just fine.  You may have had an unclean working tree after your first run of `make` —without `libtool` installed—and I suspect simply `make clean`ing before rerunning `make` would have resolved the issue.

**Comment by grantr** [comment]
> I suspect simply `make clean`ing before rerunning `make` would have resolved the issue.

Came here to report that `make clean` doesn't fix the `cannot find install-sh...` problem after initially running `make` without `libtool`. I had to start over with a new clone.
