### ISSUE TITLE
Python gRPC install for Ubuntu 15.10 requires python-dev

### ISSUE THREAD

**Issue by jgeewax** [grpc/grpc#4109]
On Ubuntu 15.10:

```sh
$ sudo apt-get install libgrpc-dev
$ sudo apt-get install python-pip
$ sudo pip install grpcio==0.9.0a1
# Fails!
$ sudo apt-get install python-dev
$ sudo pip install grpcio==0.9.0a1
```

Can we do a pre-install flight check to make sure that the Python dev libraries are installed? And if they aren't, link to a page on GitHub saying "You probably need the Python dev libraries or you'll see compile errors. More information here: http://....."

A lot of amateur Python devs don't realize that you need development packages to do compiling during a pip install -- it should "just work", so we're opening a door for confusion here.

**Comment by nathanielmanistaatgoogle** [comment]
This smells like an easy thing to do and I suspect @soltanmm will be able to get to it before I would (I could be wrong).

**Comment by soltanmm** [comment]
I can look into it, but nothing immediately obvious springs to mind. The compilation steps for the setup script are internal to `distutils` and `setuptools`.

**Comment by soltanmm** [comment]
For my future reference (because I'll probably forget by the time I look at this again): this can probably be done with yet another custom command redirecting the standard `distutils` build (this seems to be a recurring thing...) that invokes `distutils.ccompiler.CCompiler.compile` and just detecting whether or not the headers can be found. If we recognize the OS and distribution on failure we can spit out something helpful to `stderr` and call it a day.

**Comment by nathanielmanistaatgoogle** [comment]
I believe that just today I reviewed a change from @soltanmm related to this - should this issue still be open?

**Comment by soltanmm** [comment]
#4821 , yeah; this issue should be open until that one goes in (so, Soon™).

**Comment by soltanmm** [comment]
This has been 'fixed' for a while now, with plans in the pipeline to make it not-quote fixed not-quote.
