### ISSUE TITLE
gRPC Packages for Debian wheezy (7.9) 

### ISSUE THREAD

**Issue by hsaliak** [grpc/grpc#4112]
Per #4099 , this bug tracks user (@jgeewax)  request for Debian wheezy packages.

**Comment by mattolson** [comment]
I would love to see a package for Wheezy as well.

**Comment by jgeewax** [comment]
I think this is covered now with pre-compiled binaries, no?

@mattolson : Which language are you interested in using with this?

**Comment by mattolson** [comment]
Primarily Ruby, Java, PHP, Go. We're ok with compiling from scratch (this is what we are doing now), but a package would be much more convenient. I wasn't aware that you had precompiled binaries.

**Comment by jgeewax** [comment]
Yea. Java should be fine without a package. Same for Go.

Ruby 0.13 beta should have a precompiled binary that works on Wheezy, so it shouldn't be necessary :)

**Comment by abhilashgupta** [comment]
Since #4099 is closed, I am commenting here.
I face the same issue stated in #4099 , but on a ubuntu machine.
"uname -a" output:
Linux xxxxxxxxxx 3.13.0-34-generic #60~precise1-Ubuntu SMP Wed Aug 13 15:55:33 UTC 2014 x86_64 x86_64 x86_64 GNU/Linux

I was trying to install for python and followed the same steps as mentioned by @jgeewax on #4099 

Let me know if there's any solution to that issue in particular.

Thanks.

**Comment by a11r** [comment]
Closing as obsolete. Please reopen if still needed.
