### ISSUE TITLE
Consolidate all proto files into a single directory

### ISSUE THREAD

**Issue by ctiller** [grpc/grpc#4123]
We currently have many similar but slightly different proto files scattered across the project.

Move all of them into src/proto, and resolve differences.

Protos in question:
- [x] src/csharp/Grpc.Examples/proto/math.proto
- [x] src/csharp/Grpc.HealthCheck/proto/health.proto
- [x] src/node/health_check/health.proto
- [ ] src/node/test/echo_service.proto
- [x] src/node/test/math/math.proto
- [ ] src/node/test/test_messages.proto
- [ ] src/node/test/test_service.proto
- [ ] src/objective-c/examples/RemoteTestClient/empty.proto
- [ ] src/objective-c/examples/RemoteTestClient/messages.proto
- [ ] src/objective-c/examples/RemoteTestClient/test.proto
- [ ] src/objective-c/generated_libraries/RemoteTestClient/empty.proto
- [ ] src/objective-c/generated_libraries/RemoteTestClient/messages.proto
- [ ] src/objective-c/generated_libraries/RemoteTestClient/test.proto
- [x] src/objective-c/generated_libraries/RouteGuideClient/route_guide.proto
- [x] src/php/tests/generated_code/math.proto
- [x] src/php/tests/interop/empty.proto
- [x] src/php/tests/interop/messages.proto
- [x] src/php/tests/interop/test.proto
- [ ] src/python/grpcio_health_checking/grpc/health/v1alpha/health.proto
- [x] src/python/grpcio_test/grpc_interop/empty.proto
- [x] src/python/grpcio_test/grpc_interop/messages.proto
- [x] src/python/grpcio_test/grpc_interop/test.proto
- [ ] src/python/grpcio_test/grpc_protoc_plugin/test.proto
- [x] src/ruby/bin/math.proto
- [x] src/ruby/pb/grpc/health/v1alpha/health.proto
- [x] test/cpp/qps/perf_db.proto
- [x] test/cpp/util/echo.proto
- [x] test/cpp/util/echo_duplicate.proto
- [x] test/cpp/util/messages.proto
- [x] test/proto/benchmarks/control.proto
- [x] test/proto/benchmarks/payloads.proto
- [x] test/proto/benchmarks/services.proto
- [x] test/proto/benchmarks/stats.proto
- [x] test/proto/empty.proto
- [x] test/proto/messages.proto
- [x] test/proto/test.proto

**Comment by soltanmm** [comment]
The Python files are separate so that we can enable running our tests from within the project package (because it seems that's what most tools in the Python ecosystem expect to happen). Symlinks are still out of the question. It's still unclear how we'll be able to address out-of-tree protos without some arbitrarily, uh, *silly* games with the Python package tooling. Or having the `Makefile` copy the protos into the Python project-package tree. Or... any number of other things.

**Comment by mightyguava** [comment]
I asked a similar, though maybe poorly worded question, about how to handle Python packages in the protobuf mailing list, but have yet to receive a reply https://groups.google.com/d/msg/protobuf/ckHBqWhAm20/83cYJqhhAwAJ

**Comment by jtattermusch** [comment]
@mlumish, can we get rid of the remaining .proto files for node?

**Comment by jtattermusch** [comment]
@makdharma  can we get rid of the remaining .proto files for objective-c?

**Comment by jtattermusch** [comment]
Related #526.

**Comment by murgatroid99** [comment]
The two proto files currently in the Node directory exist specifically for the Node tests, and aren't related to any other protos in the repository. I don't really see a reason to move them into `src/proto`, and I would prefer to keep them in `src/node` so that I can change them freely without worrying about someone else using them.

**Comment by jtattermusch** [comment]
@murgatroid99 sounds fine for test_messages.proto and test_service.proto. How about  src/node/health_check/health.proto and and echo_service.proto?

**Comment by murgatroid99** [comment]
Sorry, I didn't notice those the first time I looked at the list. That copy of `health.proto` no longer exists, so I've checked it off the list. `echo_service.proto` also seems to be a Node-test-specific file, because it only exists in `src/node/test`. And it was written specifically to test a certain functionality related to Protobuf.js.

**Comment by jtattermusch** [comment]
PHP is currently not actionable (no proto3 support). Filed a separate issue FTR #6362

**Comment by jtattermusch** [comment]
I filed a set of language-specific issues that can be addressed separately and I'm going to close this one.
