### ISSUE TITLE
Allow for service binding with path offsetting in clients and servers

### ISSUE THREAD

**Issue by louiscryan** [grpc/grpc#4287]
Implementors need the ability to register the same interface at different path offsets within a server to support common component-oriented service design patterns

See https://groups.google.com/d/msgid/grpc-io/2fe55400-6db5-4ac2-8820-024e7076d4d8%40googlegroups.com

This ability exists in the Java implementation though it requires some effort on the part of the user to make it work. A similar ability should exist for the other languages too.

**Comment by louiscryan** [comment]
Assigning to Jan first as the customer request came from someone interested in C#

**Comment by jcanizales** [comment]
How is this supposed to look at the client side? Is there a spec somewhere?

**Comment by louiscryan** [comment]
The simplest form would be to specify a path offset at stub creation time.

-louis (from phone)

**Comment by Falco20019** [comment]
Disclaimer: I am the customer from the google discussion.

For purpose of local testing, I added an additional logical layer. So my `Server` implementation does not have the `Services` list but a `Components` list.
```csharp
var componentDefinition1 = ComponentDefinition.CreateBuilder("CompA")
	.AddService(Phone.BindService(new PhoneImpl1()))
	.Build();
var componentDefinition2 = ComponentDefinition.CreateBuilder("CompB")
	.AddService(Phone.BindService(new PhoneImpl2()))
	.Build();
Server server = new Server
{
	Components = { componentDefinition1, componentDefinition2 },
	Ports = { new ServerPort("localhost", 50051, ServerCredentials.Insecure) }
};
server.Start();
```
It just uses the component name as offset. So I can address the services with `/CompA/Phone` and `/CompB/Phone`.

The background is, I use the GRPC "server" as a container for multiple microservices. So it also acts somewhat like a service registry. Each microservice/component implements 1 to n proto services. There can be multiple microservices, which implement the same proto service, to be exchangable.

I know that this is not the common case for your customers, but it would be enough for me, if I can at least add the prefix as optional parameter in the BindService method (so that I can add it to every added service that belongs to a component, like @louiscryan wrote). Since I want the components to be addable and removeable at runtime, a grouping like with my `ComponentDefinition` would be the easiest. In the java implementation (grpc-java), it's possible to use a own HandlerRegistry for this purpose.

**Comment by jtattermusch** [comment]
Given some care, you can actually achieve what you are describing with the existing C# API.
java's HandlerRegistry roughly corresponds to ServerServiceDefinition instance.

One way  for you to change the offset of your services would be to build an instance of `ServerServiceDefinition` yourself.  This is the generated code of  BindService method:
```
public static ServerServiceDefinition BindService(MathBase serviceImpl)
{
      return ServerServiceDefinition.CreateBuilder(__ServiceName)
          .AddMethod(__Method_Div, serviceImpl.Div)
          .AddMethod(__Method_DivMany, serviceImpl.DivMany)
          .AddMethod(__Method_Fib, serviceImpl.Fib)
          .AddMethod(__Method_Sum, serviceImpl.Sum).Build();
}
```

If you write your own version of that method, you can recreate `Method` instances that contain the right service name (while leaving all the original fields the same).

**Comment by Falco20019** [comment]
Sure, it would be possible to do this manually. But since I'm developing a framework and have a lot of services, it's not feasable to copy and modify it every time I change a proto file...

I can write a protoc plugin for my purpose if you don't want to support prefixes, but then I would need you to make the generated client classes partial. The encapuslation into a new class was also done because I want to be able to remove services at runtime from the ```Server``` instance. Since I always remove all services of a whole component, this was the easiest way. I will create a fork for this, but it would be easier if the standard would already give the optional possibility to create prefixes, so that I only have to change the ```Server``` implementation and not also the ```grpc_csharp_plugin```.

**Comment by Falco20019** [comment]
I just gave it another thought. Your suggestion would workaround the server binding, but the generated client still would not be able to access it, since the generated ```__Method*``` fields used contain the original service name. For this to work, I would need to change ```__ServiceName``` at compile time.

This still does not solve my problem, since I have multiple parameterized instances of the same class and each is a named microservice. This is why I need a prefix that can be used on the server and on the client side at runtime.

**Comment by Falco20019** [comment]
I tried to solve it implementing my own ```CallInvoker```, wrapping my message into a new message and adding the recipient as a field. So my only service would be the one that unpacks the message and delegates it to the real services. This would work, but since the ```Async*Call``` constructors are internal, it's not possible to do it with the current version. Another problem with this approach is, that the ```ServerCallContext``` always includes the main entry point and I can't change that since there are no setters. It really feels like a workaround. It removes a lot of the comfort that GRPC brings.

So I would prefer if there is some kind of prefix that can be added at client and server side.

**Comment by jtattermusch** [comment]
No action planned here at this point. Closing this as part of issue bankruptcy.
