### ISSUE TITLE
C++ installation is completely undocumented

### ISSUE THREAD

**Issue by ctiller** [grpc/grpc#4520]
Also probably too complex.

**Comment by Attano** [comment]
Under the recommended by the official installation guide MSYS2/mingw environment, it's pretty much impossible to compile grpc. The amount of issues is overwhelming to say the least. You have to edit the makefile, hack multiple defines in headers, manually compile every dependency, manually move the static libraries to the corresponding folders, sort up silly issues such as // comment styles in C files etc. And even after all that, it's still not enough, there are still bugs left to fix because libgrp.dll somehow didn't compile.

**Comment by yang-g** [comment]
This is obsolete.
