### ISSUE TITLE
C# RouteGuide generate_protos.bat errors out without a helpful error message

### ISSUE THREAD

**Issue by vsubramani** [grpc/grpc#4586]
The C# sample errors out without a helpful message to indicate what might be wrong. I replicated this even outside of the batchfile and can see that it has to do with the --grpc_out option, but it is not clear what it is complaining about.

<img width="639" alt="screen shot 2016-01-01 at 2 00 22 pm" src="https://cloud.githubusercontent.com/assets/10506357/12072362/10f3ed36-b090-11e5-8755-485d7de9e64f.png">

**Comment by vsubramani** [comment]
Just to be clear, I checked that all the path that is specified in the params are valid. It is not clear which path it cannot find.

**Comment by toraora** [comment]
I'm getting the same error on `Google.Protobuf.3.0.0-beta2` and `Grpc.Tools.0.7.1`

**Comment by jtattermusch** [comment]
I just tried to run what @vsubramani  has tried and found out that it is because packages\Grpc.Tools.0.7.0\  should actually be packages\Grpc.Tools.0.7.1 (because this is the current version of Grpc.Tools the example depends on).

Changing 0.7.0 to 0.7.1 fixed the problem for me. @vsubramani, can you confirm that?

Btw, I just published nuget package for a newly release version of gRPC C# (version 0.12.0). The examples will be updated to use the new version soon.

**Comment by jtattermusch** [comment]
Is this still an issue?

**Comment by jtattermusch** [comment]
Assuming this has been resolved. Feel free to reopen.
