### ISSUE TITLE
Objective-C implementation should use CFStream

### ISSUE THREAD

**Issue by mackross** [grpc/grpc#4687]
The current sockets implementation in iOS will not activate the cellular radio and just reports the connection as unable to connect. Using CFStream however does start it up. Futhermore, using CFStream allows the the BoringSSL dependency to be dropped. 

See [Apple documentation](https://developer.apple.com/library/ios/documentation/NetworkingInternet/Conceptual/NetworkingTopics/Articles/UsingSocketsandSocketStreams.html)

> Note: POSIX networking does not activate the cellular radio on iOS. For this reason, the POSIX networking API is generally discouraged in iOS.

I think for grpc to be adopted on iOS this is really a necessity.

**Comment by jcanizales** [comment]
Hi @mackross,

you're right to point to that piece of documentation. It's something that worried us when we were deciding the networking stack to use. The experience of the Chrome team, though, that also uses POSIX sockets on iOS, is that that specific worry hasn't been an issue. It matches our (more limited) experience too. But of course we're eager to learn of cases when the current implementation is having problems.

Having said that, there are a number of reasons why it'd be beneficial to use a "less raw" networking stack than POSIX sockets. We've explored using NSURLSession (ideal), and found it can't work due to radars [26843578](https://openradar.appspot.com/26843578), [26845013](https://openradar.appspot.com/26845013), and [26846480](https://openradar.appspot.com/26846480). We've also successfully integrated Chrome's networking layer (Cronet), which gives us today a better handling of connectivity problems, plus the ability to use QUIC.

What are your thoughts / experiences? We can use all help from people that want gRPC for iOS to be adopted :)

**Comment by mackross** [comment]
@jcanizales apologies for the late reply. I found porting POSIX to CFStream was pretty straight forward on a fork of an AMQP client for iOS. However, the read, write, and polling methods were all already abstracted in a similar way to the CFStream APIs.

IMHO, CFStream (layer 6) is probably the right level of abstraction to move up to as it gives the OS a chance to make holistic choices about networking resources and callback timing. Furthermore, it's likely that layer 6 has or will have private implementations optimized for the current device. We already know that it uses private APIs given that it starts the radio gear and [hardware accelerated encryption is probably already on some iDevices](http://stackoverflow.com/questions/4812474/does-iphone-support-hardware-accelerated-aes-encryption). This could have pretty big implications from an energy use perspective for apps that make a lot of gRPC calls. Dropping the BoringSSL dependency makes it easier for new gRPC users to get started and it also means that vulnerabilities in the encryption are now updated with the system rather than the App. Given the very fast adoption of iOS security updates and the way users thinks about security, this is probably a good thing.

Lastly IMHO, going any further up the network stack for gRPC will bring a whole heap of problems with little tangible benefits compared to the well-tested and battle hardened HTTP2 encoder/decoder that already exists in core. Especially given that NSURLSession's HTTP2 support is pretty constraining.

**Comment by mackross** [comment]
I forgot to mention -- the addition of Cronet (QUIC) is very cool even if it's completely at odds to what I was suggesting!

**Comment by mackross** [comment]
Given that majority of TLS overhead is the handshake and negligible -- perhaps I'm way off and QUIC would be better overall than CFNetwork. I think a test is probably better than me speculating.

**Comment by jcanizales** [comment]
CC @muxi FYI

For what it's worth, if NSURLSession supported HTTP/2 properly, it'd bring us a few benefits on top of CFNetwork: Apple's nicest tricks (e.g. for debugging) require NSURLSession, external libraries (like OAuth2 ones) operate at that level, "session configuration" without reinventing the wheel, and it'd make the library much more friendly to contributors.

@jboeuf , what are your experiences/thoughts on TLS performance, when hardware-accelerated encryption can be used vs not, and when one uses QUIC vs TCP?

@makdharma does the C implementation use an abstraction over sockets (read, write, poll)? I know it does over the TLS library and over the overall network transport, but not sure if also at that level.

**Comment by jcanizales** [comment]
@timburks FYI too.

**Comment by ctiller** [comment]
Can this be closed?

**Comment by jcanizales** [comment]
I assume you know the answer to the question I asked @makdharma two comments above.

**Comment by stephanemoore** [comment]
What's the status of this issue?

If the use of POSIX APIs is not a concern can we document the reasoning and evidence that supports that? Is there a way to quantify the impact of not being able to leverage certain system networking features provided by higher level APIs so that integrating clients are aware of the impact of integration?

Is there any way we can expose a thinner layer of the gRPC infrastructure (e.g., the RPC infrastructure built on top of HTTP/2) for clients that want to leverage NSURLSession or other iOS SDK networking APIs?

**Comment by jcanizales** [comment]
Hi @stephanemoore,

Sadly NSURLSession can't be used for gRPC, due to the radars mentioned in https://github.com/grpc/grpc/issues/4687#issuecomment-227887528. For example, the moment your app receives HTTP trailers using NSURLSession, it crashes (CFNetwork asserts). It's really a non-starter.

The reasoning for the use of POSIX APIs not being a concern is what I explained in https://github.com/grpc/grpc/issues/4687#issuecomment-227887528 too: Chrome for iOS hasn't seen any problem related to it in its 4+ years of public deployment. Similarly for the Google apps that have been using gRPC for almost a year.

I would be thrilled to compare implementations in a quantitative way against one using NSURLSession. But that's precisely how I got to discover that we can't use NSURLSession.

@mackross suggestion of a gRPC-ObjC over gRPC-C over CFStream (instead of over POSIX) sounds _feasible_ to me. @ctiller or @makdharma should be able to tell whether the C library uses internally an abstraction over sockets, so that CFStream could be plugged in.

In terms of latency, the use of QUIC makes an important difference that we've measured. That's the direction the current efforts are going.

**Comment by stephanemoore** [comment]
Earlier it was cited that no issues were observed with Cronet? Earlier versions of Cronet had high failure rates for various network requests that caused some applications to disable Cronet for these requests and fall back to the native networking stack. Were the remarks made earlier in regard to this earlier version of Cronet or a newer version of Cronet? Have newer versions of Cronet found a way to resolve these issues?

**Comment by stephanemoore** [comment]
The NSURLSession crashes are unfortunate. I noticed that the bug reports were filed against beta versions of iOS 10. Have all these issues been confirmed to occur in public releases of iOS?

If NSURLSession is indeed unviable for gRPC then I suppose infrastructure built on top of CFStream would be the next best thing.

**Comment by jcanizales** [comment]
Differences between Cronet or gRPC's own HTTP/2 library doesn't tell us anything about POSIX sockets, as both libraries are written on top of them. I'm don't know the failures you refer to, as @makdharma is the one that's been working closely with the apps using gRPC over Cronet.

I found the NSURLSession's bugs on both public iOS 9 and iOS 10-beta. At WWDC'16, the author of Apple's HTTP/2 library (forgot his name) told me not to expect fixes to land on time for the public release of 10, but I haven't tried since. (Unfortunately for us, even if they were fixed now, we won't be able to require iOS 10 as a minimum target for at least a couple of years).

**Comment by jcanizales** [comment]
Also of note is that some gRPC apps don't have the choice to drop Cronet, because they need QUIC. So any problem in the gRPC/Cronet combo has to be solved well and fast. (Similarly for non-Cronet gRPC, because some of the apps are so space-constrained that they can't afford Cronet).

**Comment by muxi** [comment]
This was actually fixed by #15069
