### ISSUE TITLE
[Ruby] Spawn child processes but not doing much work

### ISSUE THREAD

**Issue by zhuochun** [grpc/grpc#4718]
I found setting `pool_size` will cause grpc to spawn the same amount of child processes.

However, looking at the implementation of `GRPC::RpcServer`, it is using a thread pool to handle requests. From `htop`, only the parent process is actually doing the work.

Would like some help to know why this happens?

Besides, any documentations to set up a RpcServer with good practices?

``` ruby
  server = GRPC::RpcServer.new(pool_size: options[:pool_size],
                               poll_period: options[:poll_period],
                               max_waiting_requests: options[:max_waiting_requests])

  server.add_http2_port(options[:host], :this_port_is_insecure)
  server.handle(Rpc::TestService)
  server.run_till_terminated
```

![screen shot 2016-01-14 at 12 10 47](https://cloud.githubusercontent.com/assets/842419/12315667/b1d90826-bab8-11e5-8b98-20d9c9e63d09.png)

Thanks.

**Comment by apolcyn** [comment]
The `pool_size` argument to `GRPC::RpcServer` constructor limits the size of the thread pool that's used to run service callbacks on, and in that way it also limits the maximum number of concurrent requests that the `RpcServer` can handle (since callbacks are ran synchronously).

Nit: note no child <i>processes</i> are spawned, only <i>threads</i>.

A <i>guessed</i> explanation and a note on the threading model:

Currently, the `RpcServer` has one thread that accepts and initializes new calls, and then dispatches them to run their service handler synchronously on a thread-pool thread. Especially in the case that the server isn't heavily loaded, many of the thread-pool threads might be doing nothing but waiting for work.

In general, servers that need to and <i>can</i> handle more concurrent requests should probably increase the max pool size. But there's not a hard guide for fine tuning these at the moment.

Note that `max_waiting_requests` still exists for backward-compatibility but no longer has any effect, as of https://github.com/grpc/grpc/pull/8632.

`poll_period` only affects the amount of time to allow for server shutdown.

Closing as no more action planned
