### ISSUE TITLE
Add support for CoreCLR

### ISSUE THREAD

**Issue by jtattermusch** [grpc/grpc#4732]

**Comment by jtattermusch** [comment]
Related: https://github.com/grpc/grpc/issues/2432

**Comment by vassilvk** [comment]
@jtattermusch, is this the issue to watch for progress on CoreCLR support?

**Comment by jtattermusch** [comment]
@vassilvk yes, this is the issue.

I've already done some work for this: https://github.com/grpc/grpc/pull/6104. It was able to make everything compile and make unit tests pass and was able to create a nuget package.

Some more work is needed to finish this up.
Also, it seems that microsoft will be killing the project.json format and the new format will be xml-based projects.

**Comment by vassilvk** [comment]
@jtattermusch - thank you!
Is there a link out there where Microsoft discuss the decision to deprecate project.json?
I can't find anything on the subject.

**Comment by jtattermusch** [comment]
@vassilvk  https://blogs.msdn.microsoft.com/dotnet/2016/05/06/net-core-rc2-improvements-schedule-and-roadmap/

**Comment by jtattermusch** [comment]
With this PR, it's now possible to build experimental Grpc.Core nuget package.
https://github.com/grpc/grpc/pull/7144

**Comment by jskeet** [comment]
Is the intention that this will be supported in 1.0.0? It's not in 1.0.0-pre2...

**Comment by imiuka** [comment]
I know a bunch of people who have been wanted to try gRPC on .NET Core since the 1.0 a few days ago even if it's as an alpha, but they haven't been able to figure out how.

I've taken a recent commit, and published it under [`X.Grpc.Core`](https://www.nuget.org/packages/X.Grpc.Core) with .NET Core support (in the state that you guys have it in). I'm writing here so that other people who find this issue wanting to try it out have an easy way to do so, and to check with you guys that publishing the package is OK with you. Please let me know if you don't think this is acceptable.

I've been using the packages on CoreCLR without any issues for the past week, so I'm pretty happy with the state that it's in.

You can use it by specifying `"X.Grpc": "1.1.0-dev-20160826"` in your project.json in place of `"Grpc": "1.1.0"` as the examples will direct you, and everything else will work as per the examples.

The complete list of packages is `X.Grpc`, `X.Grpc.Core`, `X.Grpc.Auth`.

Thanks for your work supporting .NET and .NET Core, as always.

**Comment by jtattermusch** [comment]
Update on CoreCLR status as of 2016-08-26:

I believe the support is mostly ready and we have the ability to build NuGet packages that support netstandard15 and net45. These NuGets haven't been published yet and will likely be part of the next release of gRPC (~in a few weeks).

What's left to be done:
- collect some feedback from early testers (I can build the testing nugets upon request).
- a bit more testing to make sure things work as expected with CoreCLR.

**Comment by jtattermusch** [comment]
@imiuka  I think publishing unofficial packages for the features we haven't released yet is fine (and thanks for doing the extra work!), but it might be good idea to make these packages hidden on nuget.org once we release the coreCLR support officially (to prevent user confusion).

Also, I am happy hearing that you haven't had any issues using gRPC C# with coreCLR - thanks for the feedback.

**Comment by imiuka** [comment]
Agreed, will definitely unpublish those packages once support is official. Wish NuGet had a better way to propagate deprecation notices when checking for updates ("this package is obsolete, please go here instead"). I've been left hanging a bunch of times while checking for updates for corefx packages, where new versions of a library are published at a new name and not the old.

On my experience with gRPC on CoreCLR, I've been using it in a system that performs about 500 million RPCs a day and it's been great! No issues whatsoever on the stability side! Thanks so much for making it work.

I'm somewhat concerned about the performance in that I wish it'd scale better and closer to the C++ and Java implementations. The performance dashboard suggests that there's contention somewhere
since the C# implementation tops out at 20k QPS on both 8 and 32 core unary call tests (vs 500k for Java and 1.5m for C++). I haven't yet tried to find and resolve it myself, but before doing so I'm not sure where to ask about how you currently feel about performance and where you want it to be.

**Comment by jtattermusch** [comment]
CoreCLR support has been backported into v1.0.x branch and will be in the next release (no ETA, but probably within the next two weeks?)

**Comment by jtattermusch** [comment]
The official pre-release packages with CoreCLR support are now available on nuget:
https://www.nuget.org/packages/Grpc.Core/1.0.1-pre1
