### ISSUE TITLE
Install friction log: C#, Windows

### ISSUE THREAD

**Issue by jtattermusch** [grpc/grpc#4798]
both 32bit and 64bit.

**Comment by goldenbull** [comment]
:+1:

**Comment by rok987** [comment]
I tried on a Windows 7 machine with Visual Studio 2013 installed.

Everything worked.

**Comment by hsaliak** [comment]
# Detailed instructions:
## Prerequisites

Install Visual Studio 2015 Community (https://www.visualstudio.com/downloads/download-visual-studio-vs?WT.srch=1&WT.mc_id=SEM_kjFqwRJY)


## Step needed for testing unpublished packages only:
Setup local nuget feed - the testing packages from this feed will be used instead of fetching from www.nuget.org 
and copy testing nuget packages (*.nupkg)  into C:\LocalNuGetFeed

Up-to-date testing packages for C# can be downloaded here:
https://grpc-testing.appspot.com/view/Artifacts/job/gRPC_build_packages/platform=windows/82/artifact/artifacts/csharp_nugets.zip


## Run Visual Studio

- Create a new solution (C# console project)
- "Manage nuget packages for the solution" (right click the solution)
- Install gRPC C# package (choose "local" source if you've setup the local nuget feed)
Write some code using gRPC.

Example code
(paste this into Program.cs in your new project)
```

using System;
using Grpc.Core;

namespace TestGrpcPackage
{
    class MainClass
    {
        public static void Main(string[] args)
        {
            // This code doesn't do much but makes sure the native extension is loaded
            // which is what we are testing here.
            Channel c = new Channel("127.0.0.1:1000", ChannelCredentials.Insecure);
            c.ShutdownAsync().Wait();
            Console.WriteLine("Success!");
        }
    }
}

```



Run the project to make sure everything works.

Try to switch the project to x64 Platform (from AnyCPU)  - this is important because this is the first time gRPC C# will work on 64bit projects for windows.

Run the project again to make sure everything works with 64bit.

**Comment by vsubramani** [comment]
The instructions are very clean and simple. Works as expected. Tested on VS 2013 professional and VS 2015 community editions.

**Comment by jtattermusch** [comment]
Thanks @vsubramani  for testing this!
