### ISSUE TITLE
Install friction log: C#, Mac OS X

### ISSUE THREAD

**Issue by jtattermusch** [grpc/grpc#4799]
With clean installation of xamarin studio.

**Comment by rok987** [comment]
Turns out I also tried on Mac with the instructions and the following code worked fine:

// This code doesn't do much but makes sure the native extension is loaded
// which is what we are testing here.
Channel c = new Channel("127.0.0.1:1000", ChannelCredentials.Insecure);
c.ShutdownAsync().Wait();
Console.WriteLine("Success!");

**Comment by hsaliak** [comment]
# gRPC C# on Mac

## Prerequisites
Install Xamarin Studio:
https://xamarin.com/download  (one big package containing mono runtime and the IDE).

### Step needed for testing unpublished packages only:
Setup local nuget feed - the testing packages from this feed will be used instead of fetching from www.nuget.org 
and copy testing nuget packages (*.nupkg)  into ~/LocalNuGetFeed

```
$ nuget sources  # lists existing sources
$ nuget sources add -Name LocalNuGetFeed -Source $HOME/LocalNuGetFeed

```
Up-to-date testing packages for C# can be downloaded here:
https://grpc-testing.appspot.com/view/Artifacts/job/gRPC_build_packages/platform=windows/82/artifact/artifacts/csharp_nugets.zip

Scenario

- Run XamarinStudio
- Create a new solution  (New solution -> .NET -> .NET console project
- Project -> Add -> Nuget packages
- Install gRPC C# package (choose "local" source if you've setup the local nuget feed)
- Write some code using gRPC. See example below.
- Run the project to make sure everything works.



Example code
(paste this into Program.cs in your new project)
```

using System;
using Grpc.Core;

namespace TestGrpcPackage
{
    class MainClass
    {
        public static void Main(string[] args)
        {
            // This code doesn't do much but makes sure the native extension is loaded
            // which is what we are testing here.
            Channel c = new Channel("127.0.0.1:1000", ChannelCredentials.Insecure);
            c.ShutdownAsync().Wait();
            Console.WriteLine("Success!");
        }
    }
}



```

**Comment by sivagar** [comment]
Above instructions worked great for me.  I would add a line making sure people unzip the csharp_nugets.zip in ~/LocalNuGetFeed.. so that it can be picked up.

**Comment by jayantkolhe** [comment]
Jan, Kailash, can you update the instructions?

**Comment by jtattermusch** [comment]
Updated the instructions.

**Comment by jtattermusch** [comment]
@sivagar  thanks for testing this, your feedback is well appreciated.
