### ISSUE TITLE
0.12.0 not buildable on arm64, ppc64el

### ISSUE THREAD

**Issue by andrewpollock** [grpc/grpc#4910]
Hi,

https://buildd.debian.org/status/package.php?p=grpc&suite=unstable shows that version 0.12.0-1 of grpc isn't building successfully on arm64 and ppc64el, two architectures where the previous version did build successfully. Due to this, it won't automatically transition to testing, and I won't be able to provide a backport to jessie.

Please figure out why it isn't building and make a new point release that fixes it, and I'll upload that to unstable and we can try again.

**Comment by islanderjtn** [comment]
Hey all,
I'm on a CentOS 6.3 x86_64 (RHEL) system using GCC 4.4.6 20120305 (Red Hat 4.4.6-4) compiler and I having compile issues on the boringssl build.  
I did a clone of master branch,then got submodules, then make.

The crypto/bio/connect.c file had shadow Warnings about the use of close at line 127, et al.

First question is do I need boringssl on linux cant I just use openssl ?  What do I do to build just delete boringssl directory?  

Is master a stable branch?
Are sandbox branches peer tested before merged  back to master ?

Is 0.12.0 branch stable?

**Comment by andrewpollock** [comment]
Nicolas, could you advise on how to proceed with this issue?

**Comment by nicolasnoble** [comment]
Hm, we shouldn't be compiling boringssl for the Debian build. There's something wrong here. The Makefile should detect we have a working system OpenSSL. Another solution might be to avoid recursively cloning the repository in order to build the Debian package.

I am unfamiliar with the way the Debian build system works. How can I poke at it ?

**Comment by andrewpollock** [comment]
You can see the build log for these architectures here:
https://buildd.debian.org/status/fetch.php?pkg=grpc&arch=arm64&ver=0.12.0-1&stamp=1453766491
https://buildd.debian.org/status/fetch.php?pkg=grpc&arch=ppc64el&ver=0.12.0-1&stamp=1453768208

At a quick glance they both look like they're failing in the same way.

Do you have access to an arm64 or ppc64el system to reproduce on? If you do, I can provide more details, otherwise these build logs is probably your most useful thing.

**Comment by nicolasnoble** [comment]
Oh these are beautiful, thank you.

Turns out that this got fixed at some point by this commit: 069384da5e82b9e4274a967589bdbd58bff44507. We can backport it to 0.12 if needed. But it turns out this is also in the 0.13 release we've tagged, so maybe we could skip 0.12 as a debian package and go straight to 0.13 ?

**Comment by andrewpollock** [comment]
Is 0.13 ready for release? I can package it.

**Comment by sayrer** [comment]
0.13.1 just got released...
