### ISSUE TITLE
Remove git requirement for distribution testing

### ISSUE THREAD

**Issue by ctiller** [grpc/grpc#5020]
(and ideally wider than that)

For distribution at least, it seems possible to mount the artifacts, test scripts directories directly within docker. This would drastically reduce cloning time and increase our confidence that we're not accidentally taking dependencies.

Later, for regular builds, this seems desirable also. Way lower priority.

**Comment by ctiller** [comment]
I think for testing this is going to form a hard requirement: multiple clones coming out of the same directory don't work, so we'll be limited to a single test environment at a time.

**Comment by jtattermusch** [comment]
Actually, what's causing trouble is the with multiple parallel clones is `git branch -f jenkins-docker`. We run it to stop the git clone running inside docker from complaining that `You are in 'detached HEAD' state`.  Git clone can't really cause any trouble because the source repo is mounted as readonly, so there's no way for cloners to lock anything.
