### ISSUE TITLE
Python installation testing - Linux

### ISSUE THREAD

**Issue by hsaliak** [grpc/grpc#5111]
Requirements:

- python 2.7
- pip

Prerequisite steps:
```
pip install enum34 futures six
pip install --pre protobuf>=3.0.0a3
```

Note: unfortunately, being on TestPyPI requires that our dependencies be installed separately. This will not be the case once we get on PyPI.

Potential Pitfalls:
The --pre flag may not be necessary (or even available?) for some versions of pip. If pip whines about it, drop the flag.
Linux
Install w/ User Build
Requirements:

- python-dev
- gcc or clang

Steps:
`pip install -i https://testpypi.python.org/simple --pre grpcio
`

Testing the installation
Launch a python interpreter and run
```
>> import grpc
>> dir(grpc) 
```
Exit the interpreter..

Next, try the hello world example.
`
git clone https://github.com/grpc/grpc`
Navigate to the "hello, world" Python example:
`  $ cd grpc/examples/python/helloworld
`

Run the server

`$ python2.7 greeter_server.py &
`
Run the client
`
$ python2.7 greeter_client.py`
If all goes well, you will receive the message:
Greeter client received: Hello, you!

**Comment by joeholley** [comment]
Had an issue with this on a vanilla Jessie install with attempting to use pip from the repos (apt-get install python-pip). The standard repository version of pip requires six, and the latest version of six in the standard repository is 1.8.  Pip refuses to install over a package installed by apt (so it won't install six 1.10), and uninstalling six via apt uninstalls pip.  Would suggest for the time being that these instructions be updated to suggest installing pip directly via the script on the pip site (https://pip.pypa.io/en/stable/installing/) instead of via apt, which resolves all these issues, and gets you the latest version of pip as a bonus.

**Comment by soltanmm** [comment]
@joeholley We'll probably dodge the user needing to think about the issue by fixing #5247. It's just a question of how low we should be going, methinks...

In the meanwhile, though, this issue has served its original purpose for the relevant milestone. :-)
