### ISSUE TITLE
C# CallOptions.with*() and CallOptions.Normalize() documentation incorrect

### ISSUE THREAD

**Issue by chrisdunelm** [grpc/grpc#5122]
C# CallOptions.with*() and CallOptions.Normalize() methods specify in their documentation that a new instance is returned with the given value updated.
However, the current implementation mutates the existing object, returning the mutated existing instance.

Either the documentation or the implementation should be corrected.

**Comment by mleenhardt** [comment]
I don't think that's correct for the `CallOptions.With*` methods. The implementation first assigns the current instance to a local variable, which performs a shallow copy since `CallOptions` is a struct. Modifying property on the newly created struct won't affect the original instance (this [test ](https://github.com/grpc/grpc/blob/aa1ebffb323e012167d080c8375097e1bd290fc4/src/csharp/Grpc.Core.Tests/CallOptionsTest.cs#L49)verifies it).

#5073 adds some additional fluent methods that allow to set properties that were probably added after the first with* method implementation.

**Comment by chrisdunelm** [comment]
Oops, my mistake. Thanks.
