### ISSUE TITLE
Ruby Installation Friction testing - Mac

### ISSUE THREAD

**Issue by hsaliak** [grpc/grpc#5203]
## System Requirements: Ruby, git
Ensure Ruby is installed. Note: this is installation of a pre-req and issues encountered are not in scope for the friction testing of gRPC.
Install XCode dev tools (which contains Ruby), or curl -sSL https://get.rvm.io | bash -s stable

Installing the gem, from a terminal

```
gem install --pre grpc 
```
Testing it:

Clone the gRPC repository
```
 git clone https://github.com/grpc/grpc
```
Navigate to the Ruby examples directory:
```
$ cd grpc/examples/ruby
```
Run the greeter server/ client

- Run the server

  ```sh
  $ # from this directory
  $ bundle exec ./greeter_server.rb &
  ```

- Run the client

  ```sh
  $ # from this directory
  $ bundle exec ./greeter_client.rb
  ```

**Comment by hsaliak** [comment]
@rok987 - can you please give this a shot?

**Comment by rok987** [comment]
I already had ruby installed (prerequisite was fine).

"gem install --pre grpc" failed at first since I didn't use "sudo". We might want to add an instruction about that perhaps. Otherwise with "sudo" it was fine.

"bundle exec" did not work because my machine didn't recognize the "bundle" command. I believe that "Bundle" is a Ruby thing - so perhaps Ruby developers should have that in their path already? I didn't and I have Ruby installed. I might not have bundle. So we might want to add some text saying that you need to ensure "bundle" is in your Path perhaps?

Doing "./greeter_server.rb &" asked me to Allow incoming connections, which I did, and unsure if that was expected.

Doing "./greeter_client.rb" printed "Greeting: Hello World".
