### ISSUE TITLE
Add server channel affinity

### ISSUE THREAD

**Issue by ctiller** [grpc/grpc#5470]
Currently (on posix systems) we assign every incoming server channel to every server completion queue's pollsets. 

This ends up destroying isolation for servers with multiple completion queues and creates thundering herds on every read on such servers.

The basic thought here is to only bind server channels to the pollset that noticed it was time to call accept(). This will provide some natural load balancing (more idle pollsets are more likely to notice accepts).

To do so:
1. modify `grpc_fd_notify_on_read` to accept a `grpc_pollset** notifier` that it outputs the awaking pollset to - probably only if notifier is non-NULL since most things won't need this
2. in tcp_server_posix.c, replace the loop:
```
    /* TODO(ctiller): revise this when we have server-side sharding
       of channels -- we certainly should not be automatically adding every
       incoming channel to every pollset owned by the server */
    for (i = 0; i < sp->server->pollset_count; i++) {
      grpc_pollset_add_fd(exec_ctx, sp->server->pollsets[i], fdobj);
    }
```
with a single grpc_pollset_add_fd to the pollset that got the accept() awaking.
3. in server.c, remove the loop adding new transports to pollsets, as it's redundant with the code in tcp_server_posix.c (this loop:
```
  for (i = 0; i < s->cq_count; i++) {
    memset(&op, 0, sizeof(op));
    op.bind_pollset = grpc_cq_pollset(s->cqs[i]);
    grpc_transport_perform_op(exec_ctx, transport, &op);
  }
```
)

As a second step, we should probably think about using `SO_REUSEPORT` to create a separate listening fd for each server completion queue.

**Comment by ctiller** [comment]
It's probably best to base this on top of the cleaner-posixN series of pull requests I've been putting out recently.

**Comment by pgrosu** [comment]
This is nice, but can the file descriptor also be sharded so that independent callbacks that are interleaved on one channel would then be serviced by multiple servers performing simultaneous seeks on the same file descriptor, and thus parallelizing the execution of callbacks on the same channel?  Maybe a broker might be required.

**Comment by ctiller** [comment]
Paul: given the expected time doing a read, it would be totally unnecessary
complexity. Application processing will proceed on different threads in
application space, so the main problems in this space are minimizing
contention on shared resources and avoiding thundering herds.

**Comment by pgrosu** [comment]
Hi Craig,

That's understandable, but let's consider a more extreme scenario, which can be realistic.  I try to simulate a 24/7 server that is constantly retrieving data for processing.  For this scenario, I am not assuming that I embed code in the data-stream to execute, but only data for online (stream) analysis:

On one terminal I perform the following command:

```Bash
$ yes > online_data
```

On a second terminal, I changed the `def good(self)` function in `test_server.py` to the following:

```Python
        def good(self):
                self.send_response(200)
                self.send_header('Content-Type', 'text/html')
                self.end_headers()
                for line in sys.stdin:
                        self.wfile.write(line)
                self.wfile.write('<body><p>This is a test</p></body></html>')
```

And then launch it like this:

```Bash
$ test/core/httpcli/test_server.py --ssl < online_data
```

On a third terminal I type the following:

```Bash
$ curl --insecure -X GET https://127.0.0.1:10080/get
```

Then on a fourth terminal I monitor top, and this is what I notice:

![grpc_top_putty-top-3](https://cloud.githubusercontent.com/assets/6555937/13377716/b739223c-ddb4-11e5-8c54-8a1b6eef69be.png)

Notice how extreme the CPU core load becomes, thus being overwhelmed by one client or server per core.  The load balancing, even though would be natural might encounter such bottlenecks.

`p

**Comment by ctiller** [comment]
Sorry but I think I completely fail to see your point. There's no grpc code
here. Is it that reading on one thread and writing on another might be
faster? Because we can do that now. But you seem to be arguing in favor of
more threads and I just don't understand what you hope to achieve beyond
raising contention and contact switch overheads whilst increasing
complexity.

**Comment by pgrosu** [comment]
Ok, maybe my previous post had too many assumptions, and there is definitely no contention, but rather just test cases of some real scenarios :)  Basically, the idea is that the messages are being sent on one channel to the server, and I have different clients processing different messages, which interface with the server - eventually there will be servers interfacing with servers as well:

Let's suppose I start each of these on another terminal session:

First I start the server:

```Bash
$ ./fling_server --bind="127.0.0.1:10080" --no-secure
```

And then I start 3 simultanous `fling_client` like this:

```Bash
$ ./fling_client --target=127.0.0.1:10080 --scenario="ping-pong-request" --payload_size=1
```

Again the server is overwhelmed as noted below:

![fling_server_with_3_clients](https://cloud.githubusercontent.com/assets/6555937/13392304/86cca468-dea7-11e5-9b9a-755a4034710f.png)

Even if I start the client as a stream:

```Bash
$ ./fling_client --target=127.0.0.1:10080 --scenario="ping-pong-stream" --payload_size=1
```

Though the load on the CPU is less, which is nice, the processing seems to still be sequential, rather than simultaneous.  If I assumed or wrote something incorrectly, please let me know.

Thanks,
~p

**Comment by ctiller** [comment]
fling server is explicitly written to be single threaded.

If your interested in this stuff, try exploring the test/cpp/qps framework.

**Comment by ctiller** [comment]
If it's OK with you I'd like to delete this conversation from this bug as
it's really a distraction from what we need to get done.

**Comment by pgrosu** [comment]
No problem, and thank you for the help.  If it's okay, I'll remove everything except my initial post, as your reply has an important piece of information, which will help me as a reference while experimenting with different tweaks to src/core as well.

Sorry for the noise,
~p
