### ISSUE TITLE
Add class prefixes to ProtoRPC classes

### ISSUE THREAD

**Issue by stephanemoore** [grpc/grpc#5548]
The lack of a prefix on these classes presents the risk of naming collisions in Objective-C's global namespace. The result of such collisions could vary from linker errors to rejection in the App Store. We should introduce a class prefix to the ProtoRPC classes to mitigate such risks.

**Comment by jcanizales** [comment]
Hi Stephan! Thanks for raising this. Since the beginning we've just considered `Proto` to be the prefix of those three classes. But you're right that someone, at some point, might write a `ProtoMethod` class in their app and not expect that to be considered prefixed. We've discussed it, and have this in mind:

Rename `ProtoService` --> `GRPCProtoService`, `ProtoMethod` --> `GRPCProtoMethod`, `ProtoRPC` --> `GRPCProtoCall`.

Unfortunately, because our public surface is frozen (since Beta), we have to keep the old three names around. We'll achieve that by making the new ones subclasses of the old ones or vice versa.

This means the collision problem won't be really fixed (at least on v1). But we'll mark the old names as deprecated, and if an app developer in the future writes a class that collides with one of them, after cursing us he'll at least see that we deprecated those names for exactly that reason.

**Comment by makdharma** [comment]
jcanizales@ - Is subclassing Proto* still the best option according to you?

**Comment by jcanizales** [comment]
I think that'll be the best for users. The current three names luckily aren't common ways to name classes. A GitHub code search doesn't find any class named that way except for the gRPC ones.

**Comment by makdharma** [comment]
What is wrong out outright replacing the names? Who uses the ProtoMethod/ProtoService/ProtoRPC classes directly?

**Comment by jcanizales** [comment]
Discussed offline, but for the record: generated libraries use them, and client code uses `ProtoRPC` too for things like setting headers or canceling RPCs.

**Comment by makdharma** [comment]
PR https://github.com/grpc/grpc/pull/6283

**Comment by matti777** [comment]
Hi, is there yet a way to have the `protoc` tool generate these prefixed names so that Xcode would not warn about them?

**Comment by jcanizales** [comment]
@muxi

**Comment by muxi** [comment]
@matti777 - #6826 modified the compilers to generate prefixed names. Are you still meeting this issue?
