### ISSUE TITLE
python test timeout: _beta_features_test.BetaFeaturesTest

### ISSUE THREAD

**Issue by jtattermusch** [grpc/grpc#5564]
https://grpc-testing.appspot.com/job/gRPC_master/15549/config=dbg,language=python,platform=linux/testReport/junit/(root)/tests/py_test__beta_features_test_BetaFeaturesTest/

**Comment by soltanmm** [comment]
Somehow the response iterator times out with an `ExpirationError` and either the test or underlying layers fail to properly raise the error up and out of the test harness (until keyboard interrupt [which is *really weird behavior*]). Then the response iterator wrapper that handles lock-step-execution (to avoid race conditions in the test code), due to the way it was written, continues to loop ad infinitum because it was never signaled.

Stay tuned...

**Comment by soltanmm** [comment]
It's the underlying layers.

**Comment by soltanmm** [comment]
Aaaand the above was the wrong interpretation of debug data.

It **isn't** that the exception is getting passed up, the exception is *registered* with the test runner's collector as a failure, but then some race condition is keeping the test spinning in `tearDown()` indefinitely.

**Comment by soltanmm** [comment]
Gonna record my thoughts here so I'll have something to review after I go think about something else for a bit:

There is something really *really* **really** weird going on in that `tearDown()`. If one forces an expiration error to occur on the response iterator (e.g. turn the timeout on the stub invocation down to `0.01` and put an `import time; time.sleep(0.1)` just before the `next(response_iterator)` line), some indescribable hell breaks loose if you invoke `pdb.set_trace()` and step-over through the code as opposed to step-into the `tearDown` line that waits for the server to finish shutting down: a `TypeError` asserting that a `NoneType` isn't callable is raised on a line that's checking a primitive in an if-statement conditional in `server.pyx.pxi` in the `shutdown` method. Adding `print self; print queue; print self.registered_completion_queues` to the top of that method alleviates the callable error.

Without `pdb`, there's a hang during `tearDown()` *but* hitting ctrl-C results in the test finishing with the proper exception (`ExpirationError`) noted as being raised. This suggests that there's some frozen thread running somewhere at the time of `tearDown`. BUT...

The freeze happens when assigning `self.dynamic_stub = None`. This suggests that the hang is in a `__del__` method, which then suggests that there's likely a `__dealloc__` method that needs to be investigated, if the error can be found in Cython. Except that investigation down that path has proven unreliable due to Schrodinger's spirit deciding to take up software engineering in its spare time.

I think part of the problem is that using `print` statements and `pdb` has side effects that affect Python reference counts and those object references are not necessarily dropped immediately. So... it makes gathering reliable information in this way, ah, difficult...

**Comment by jtattermusch** [comment]
Went through like 10 last builds on master or so and this seems fixed by #5704.

**Comment by soltanmm** [comment]
I'm still concerned with the test-harness-hanging-at-`tearDown` part of this issue, but that perhaps warrants a separate filing...
