### ISSUE TITLE
Doc Fixit: quick start example should be C++ instead of java

### ISSUE THREAD

**Issue by stanley-cheung** [grpc/grpc#5663]
Starting from this section: https://github.com/grpc/grpc/tree/master/examples#get-the-source-code

The quick start example should probably be C++ instead of Java, given we are in grpc/grpc instead of grpc/grpc-java

The website: http://www.grpc.io/docs/tutorials/basic/c.html has the C++ route guide example, but here we probably need one for Hello World.

**Comment by yang-g** [comment]
The helloworld example doc is here: https://github.com/grpc/grpc/blob/master/examples/cpp/helloworld/README.md

If this is decided, we can just copy the file over?

**Comment by stanley-cheung** [comment]
@LisaFC do you want to make a suggestion here?

**Comment by LisaFC** [comment]
This doc is actually a reeeeeeaaaallly early version of this (from back before when we had grpc.io at all, and it's in Java because that was the first Hello World example we wrote): http://www.grpc.io/docs/

I wouldn't replace it with the C++ one because all the other C-based Hello Worlds are in this directory as well. How about a new doc that points to the external doc and then just has quick links to all the language-specific READMEs in the examples folder?
