### ISSUE TITLE
Simplify development environment for PHP - package protoc and grpc protoc plugin.

### ISSUE THREAD

**Issue by hsaliak** [grpc/grpc#5983]
Package and ship protoc and gprc plugin for PHP.
- Figure out how to bundling and distribution for Mac/Linux/Windows.

On resolution of this issue, we should have 1 line install, via packages, for installing protoc, its plugins and the language runtime.

**Comment by stanley-cheung** [comment]
This will have to wait until we have PHP support in protobuf.

**Comment by stanley-cheung** [comment]
Need #6637 to be implemented first.

**Comment by mcos** [comment]
What's the current state of this? I'd be nice to have the plugins available without having to compile from source

**Comment by hsaliak** [comment]
@stanley-cheung is this something doable now?

**Comment by jtattermusch** [comment]
@stanley-cheung  ping - can you respond or close?

**Comment by ZhouyihaiDing** [comment]
I am looking into it. 
I haven't find a good place to place the grpc_php_plugin elegantly like other languages. 
Eg, if downloading the plugin as php extension, the command may look like `php -d extension=protoc_php_plugin.so xxx.php -I ../protos --php_out=lib --grpc_out=lib ../protos/helloworld.proto`, which the user must create an empty `xxx.php` otherwise php program will hang.

**Comment by ZhouyihaiDing** [comment]
My idea to solve this issue is shipping the `protoc` and `grpc_php_plugin` when the user downloads grpc via composer.

For every release, we manually download `protoc` and `grpc_php_plugin` from `artifact` build, and put them under

- tools/bin/x86-linux
- tools/bin/x86_64-linux
- tools/bin/x86-macos
- tools/bin/x86_64-macos
- tools/bin/x86-windows
- tools/bin/x86_64-windows

After users download gRPC-PHP, they should know which tools they should use and go find them in the related directory.

**Comment by hsaliak** [comment]
@ZhouyihaiDing are there any approaches we can take to make the invocation of these binaries same across platforms? That way we can provide platform independent instructions in readme etc?

One simplification is to have a shell script that detects and forwards args for all the linux and OSX use cases and a similar bat file for Windows. @nicolasnoble any other ideas here?

**Comment by ZhouyihaiDing** [comment]
I didn't find tools in PHP which can do the similar thing like python or ruby. 

Provide shell script(or a PHP script) to check platform sounds good to me. For example, `grpc-tools` in [ruby](https://github.com/grpc/grpc/blob/master/src/ruby/tools/platform_check.rb) check the platform before running the `protoc` and `plugin`. We are imitating what it does into the shell script so it looks like a `grpc-tools` for PHP.
