### ISSUE TITLE
ObjC: The writer finished without producing any value

### ISSUE THREAD

**Issue by tkchin** [grpc/grpc#6002]
On average one out of every 30-40 RPCs is failing with "The writer finished without producing any value". The rpc usually succeeds after a retry. However, this is undesirable because it increases latency. Would like to understand why this is happening.

@jcanizales any ideas?

**Comment by jcanizales** [comment]
Backtracking from the code, to make sure I don't miss anything:

* For the writeable to receive `writesFinishedWithError:nil`, and RPC has to call `-[GRXConcurrentWriteable enqueueSuccessfulCompletion]`.
* That only happens when `GRPCCall` receives `finishWithError:nil`.
* Which can only happen if `[_wrappedCall startBatchWithOperations:@[[[GRPCOpRecvStatus alloc] initWithHandler:completionHandler]]];` sends `error == nil` to the `completionHandler`.
* And that only happens when `*grpc_op.data.recv_status_on_client.status` is either:
 * Never written (we initialize the pointed memory to zero).
 * Explicitly written as status code OK.

@ctiller In the context of a single `grpc_call`, what can make a completion queue to return "received status op completed", with status OK, _before_ returning any "received message op completed"?

@nicolasnoble Can the C library made to log the stuff it receives over the wire? Last time I tried WireShark I couldn't make it work for gRPC's HTTP/2, although I remember mentioning it to you and talking about a plugin.

**Comment by makdharma** [comment]
running with GRPC_TRACE=secure_endpoint will dump all read/writes on the
wire in unencrypted form.

**Comment by tkchin** [comment]
Any updates here?

**Comment by jcanizales** [comment]
`GRPC_TRACE=secure_endpoint,api` better, per @ctiller recommendation

**Comment by makdharma** [comment]
I confirmed that this happens on my laptop also, just by executing src/objective-c/tests/run_tests.sh. It happens roughly 20% of the time (1 in 5 tries).

**Comment by jcanizales** [comment]
We've traced this to the C library producing the event for received response after that for received status (which finishes the RPC): Issue #6207. From Makarand's logs, there should be enough information to figure out why is that happening.

**Comment by makdharma** [comment]
This issue has been fixed. Closing.
