### ISSUE TITLE
When compression mechanism used by client is not supported at server, return INTERNAL

### ISSUE THREAD

**Issue by a11r** [grpc/grpc#6219]
Currently the spec says that we should return UNIMPLEMENTED, but that is too broad an interpretation. JAVA already returns INTERNAL. We need to switch C- core to return INTERNAL here.

**Comment by jcanizales** [comment]
That switches the "blame" from the client to the server. It's not great to give clients the ability to trigger server `INTERNAL`s at will.

`UNIMPLEMENTED` also carries the clear meaning that the same request won't succeed if retried, which is something that `INTERNAL` lacks.

Why not change the code used by Java? @ejona86 @louiscryan

**Comment by ejona86** [comment]
The problem is that `UNIMPLEMENTED` means something completely different from its usage here. `UNIMPLEMENTED` is for when the service method is not actually implemented.

It's slightly weak in the documentation for `UNIMPLEMENTED`, but it does say _the_ operation and _this_ service, which implies the actual service method called:
> The operation is not implemented or is not supported/enabled in this service.

**Comment by jcanizales** [comment]
gRPC-the-protocol-independent-of-the-Protobuf-IDL has no notion of services nor methods, only host, path, metadata and messages. The proposal here is for a server to emit `INTERNAL` ("This error code is reserved for serious errors.") whenever it receives a `Message-Encoding` header with a value outside of a fixed set. So if we're going by what we wrote when we documented the error codes, `INTERNAL` doesn't still seem a good choice to me.

But I think picking error codes that way is the wrong approach anyway. We should pick them based on what we expect people to do about the error situation at hand. In the case of trying to use an unsupported compression mechanism:

1. Nobody at the server side should be alerted / paged from a burst of these requests.
2. It should declare that the client is at fault.
3. It should make clear that nothing the user or client does will make an identical retry succeed.
4. We expect the client app developer or the client library developer to prevent it from ever happening.

`INTERNAL` is a bad fit for all of them. Both `INVALID_ARGUMENT` or `UNIMPLEMENTED` serve better those purposes. Abhishek rather reserve `INVALID_ARGUMENT` for app-level errors, which is why we went with `UNIMPLEMENTED`.

**Comment by iamqizhao** [comment]
At for Go, we allow server register custom compressor/decompressor. So if the client sends a compression mechanism which is not supported at server, it seems like the fault is either client (who uses the wrong compressor) or server (who did not install the appropriate decompressor). In either case, INTERNAL does not sound a correct choice because it is not related to grpc internals.

**Comment by ejona86** [comment]
I fully agree that `INTERNAL` is not perfect. But it seems better than all the other options. @iamqizhao, do you have a suggested code?

**Comment by iamqizhao** [comment]
I would suggest NOT_FOUND (the decompressor entity is not found on the server) or INVALID_ARGUMENT (the client specified an invalid argument for decompression).

**Comment by iamqizhao** [comment]
@ejona86 @a11r @jcanizales 
I talked to Abhishek a bit on this. I think it is reasonable to leave both NOT_FOUND and INVALID_ARGUMENT to applications. So now it seems we do not have many choices left. Between INTERNAL and UNIMPLEMENTED, I would prefer UNIMPLEMENTED.

**Comment by dgquintas** [comment]
The conclusion has been to go with *UNIMPLEMENTED*. I will update #6243 accordingly.

**Comment by ctiller** [comment]
Is this done?

**Comment by dgquintas** [comment]
yes. It's in review, https://github.com/grpc/grpc/pull/6481
@sreecha ping :)

**Comment by sreecha** [comment]
I have been looking at it..Will be done with this by end of day today..
