### ISSUE TITLE
PHP: provide an option to pass in a channel override object in stub creation

### ISSUE THREAD

**Issue by stanley-cheung** [grpc/grpc#6231]
In most other wrapped languages, when the user creates an instance from a stub class (generated code), there is usually a way to pass in a `Channel` object.

However, in PHP, there is no such option. One use case might be that a user might want to create a `Channel` object once and pass it to multiple stubs. 

This will involve changing the php protoc codegen and adding an optional parameter to the stub constructor.

[Code](../blob/master/src/php/lib/Grpc/BaseStub.php#L56): right now a new `Channel` object is always created from the Stub constructor.

And if anything, this looks like an API mismatch with other wrapped languages.

**Comment by stanley-cheung** [comment]
@jtattermusch @murgatroid99 @nathanielmanistaatgoogle Do you guys agree that an optional `channel_override` parameter is something we want to add to the PHP client stub constructor?

**Comment by stanley-cheung** [comment]
CC @garrettjonesgoogle

**Comment by murgatroid99** [comment]
Node doesn't have this option. Do the rest of the wrapping languages have it?

**Comment by garrettjonesgoogle** [comment]
Java, Python, and Ruby have it. I haven't checked the remaining ones.

**Comment by jtattermusch** [comment]
C# also has a way to create a stub from an existing channel (actually, it never auto-creates a channel itself).
I think it is strongly recommeded to provide a way to share a channel between multiple stubs because that adds some useful flexibility (without it, how do you reuse the same TCP connection to talk to several different services? imagine your client needs to talk to a large number of services).

So yes, we should add this capability for PHP  (and the argument shouldn't be called `channel_override` but just `channel`) and for Node as well (if possible).

**Comment by stanley-cheung** [comment]
Ruby called the [param](../blob/master/src/ruby/lib/grpc/generic/client_stub.rb#L79) `channel_override`, we might need to fix it.
