### ISSUE TITLE
Why gRPC uses Protobuf and HTTP/2 together?

### ISSUE THREAD

**Issue by RinatMullayanov** [grpc/grpc#6292]
Explain, please, why gRPC uses HTTP/2 with Protobuf together - why not just use a TCP socket?
And if you use HTTP/2 then why Protobuf? Can not I then just all in a JSON serialized and transmitted over HTTP/2 and everything will be super cool compress and stuff ...

**Comment by jtattermusch** [comment]
These are two separate questions:
1. protobuf is used because it has schema, and it is much more efficient and faster than JSON. (proto3 still has JSON bindings). https://developers.google.com/protocol-buffers/docs/overview#what-are-protocol-buffers
2. HTTP2 is used for many good reasons: HTTP2 is a standard and HTTP protocol is well known to proxies, firewalls and many software tools. The streaming nature of HTTP2 suits our needs very well, so no need to reinvent the wheel. We'll probably post more on this topic soon on grpc.io page.

Next time, please consider posting general questions like this on stackoverflow or grpc.io mailing list.

**Comment by RinatMullayanov** [comment]
@jtattermusch Thanks, I would like more details on the grpc.io page.

**Comment by vjpai** [comment]
This particular topic is slated to go up on the grpc.io page in the near future.

**Comment by xinzhg** [comment]
Can someone post the link?

**Comment by vjpai** [comment]
Hi there, [our about page](https://grpc.io/about/) has a link to [a talk that @zinuga and I did](https://www.slideshare.net/VarunTalwar4/grpc-design-and-implementation) , which gives information explaining why gRPC is designed largely to support the HTTP/2 protocol and Protobuf serialization format.

**Comment by simophin** [comment]
I have similar question. Why not websockets? It's HTTP compliant and has wider support.
