### ISSUE TITLE
Channel should implement IDisposable

### ISSUE THREAD

**Issue by FrankGrossmann** [grpc/grpc#6310]
Channel contains a member which is derived from SafeHandle, because of this you should implement IDisposable interface to expose the nature of the class to developers. The developers need this information for proper handling! (e.g.to use using block or to ensure the channel is closed in a try catch finally)

**Comment by jtattermusch** [comment]
The channel already exposes ShutdownAsync operation to shutdown the channel. This is because it is hard to implement the channel shutdown process as a blocking operation and you cannot have a Dispose method that works asynchronously.

Also, the channel is intended to be a long lived object (most likely you'll create one when you start your application and shutdown once your application is shutting down), and with that in mind, I'd argue that being able to use the `using` statement to make sure you dispose the channel becomes much less useful (it would make sense if you were creating lots of channels and disposing them shortly, but that's not really the mainstream use case).

**Comment by jtattermusch** [comment]
No action planned here.
