### ISSUE TITLE
GRPC in Azure

### ISSUE THREAD

**Issue by angshuman** [grpc/grpc#6317]
I have an Azure web app trying to connect to another Azure VM using GRPC. When I run the webapp locally it all works fine and the connection to the VM is complete. However when I run the code as a webapp in cloud the GRPC channel is in TransientFailure state and the communication times out. 

This is very strange because webapp does not have any restrictions on outgoing network calls. Thoughts?

Thanks.

**Comment by louiscryan** [comment]
What do logs say?

**Comment by angshuman** [comment]
I don't see any logs. Any way to enable them?

**Comment by louiscryan** [comment]
Which language are you using?

**Comment by angshuman** [comment]
C#

**Comment by angshuman** [comment]
Also a side question. I suspect that webapp may have issues with HTTP2. Is there an option to use grpc over HTTP?

**Comment by jtattermusch** [comment]
I'll need more info to be able to asses what's going on.

1. are you running client/server on a VM or on a managed serving solution?
2. what app is the client and what app is the server in your case.
3. can you present an example of your code?

**Comment by jtattermusch** [comment]
regarding your http question:  no, gRPC can only work with HTTP/2. It is because we are relying on properties of that protocol to accomplish things like streaming RPCs. Also, HTTP is a text-based protocol and doesn't allow multiplexing over a single connection, so the performance characteristics of such solution would be bad.
