### ISSUE TITLE
Add ability to suppress all log output

### ISSUE THREAD

**Issue by joelnn** [grpc/grpc#6548]
#5967 added an environment variable 'GRPC_VERBOSITY' to control log output. I'd like to see a 'NONE' level, beyond 'ERROR', which would mean that even errors would not be logged.

My expectation was that as a library, grpc would not produce any stdout/stderr output unless explicitly requested/configured. If that's not the preferred behavior for other folks, I think it'd be good to be able to opt-out.

As an aside, is there a way for application developers (e.g. ruby) to access the setting added in #5967 other than through the env var, i.e. through the function that was added?

**Comment by joelnn** [comment]
In case a motivating example is helpful:

I'm writing an etcd client library, and its expected that at times, some of the etcd servers will not be available. My library handles automatically selecting another server to connect to, and so I don't want to log every connection error.

**Comment by peterhuene** [comment]
This issue is preventing me from using gRPC in my project as stdout/stderr output from a third party library is highly undesirable.  `GRPC_VERBOSITY` is a good start to suppress a number of messages, but some bugs in 0.15.0 appear to cause errors to be printed in simple use cases (such as #7267 which happens for me in C++ clients).

I would also like to echo the sentiment that general purpose libraries such as gRPC should ideally be opt-in to stdout/stderr writes (*especially* when defaulting to a debug level), but I'd be satisfied with an opt-out solution provided I can suppress all gRPC stdout/stderr writes.

**Comment by y-zeng** [comment]
[`void gpr_set_log_function(gpr_log_func f)`](https://github.com/grpc/grpc/blob/master/include/grpc/support/log.h#L84) may be used as an opt-out solution:
```
void BlackholeLogger(gpr_log_func_args* args) {}
...
gpr_set_log_function(BlackholeLogger);
```
