### ISSUE TITLE
Ruby: Setting an invalid host will hang the ruby client

### ISSUE THREAD

**Issue by blowmage** [grpc/grpc#6559]
If we connect and specify a host that is either not running or not a GRPC endpoint the client hangs indefinitely. No error is raised. We see the following error message on stdout over and over:

```
E0512 08:55:14.785357000 140735288209408 tcp_client_posix.c:191] failed to connect to 'ipv4:192.30.252.154:443': timeout occurred
```

[refs GoogleCloudPlatform/gcloud-ruby#688]

**Comment by murgatroid99** [comment]
If you make a call to a non-existent server, grpc will keep trying to connect to that server, in case the server starts up. The standard way to keep this from going on forever is to set a deadline on the call and do something appropriate when it times out.

In addition, the issue with Ctrl+C mentioned in the referenced bug has been fixed in the 0.14 release, which is now out.

**Comment by muxi** [comment]
ping. can we close?

**Comment by apolcyn** [comment]
I think this can be closed since it looks like a dup of https://github.com/grpc/grpc/issues/12897
