### ISSUE TITLE
C# - any chance of "don't throw an exception on server status failure"?

### ISSUE THREAD

**Issue by jskeet** [grpc/grpc#6819]
There's a particular use case of "get or create" (e.g. a topic) where it's common to make a get call, and if the result is "not found", then call a create method. At the moment, the "not found" is communicated through an exception, which feels a bit ugly. It's *normally* the right approach, but in some cases we really expect a non-success status code and would like to deal with it without having to catch an actual exception.

Is there already a way of doing this in the C# gRPC client, where *any* server response is returned directly, without error handling? I'd expect I/O errors to still generate exceptions, but if the server received the request and issued a response, we'd like to just get that response and handle the status code ourselves - again, just in some cases.

// cc @chrisdunelm @chrsmith

**Comment by jtattermusch** [comment]
How do you imagine we would decide which status codes throw an exception and which don't? Would that be configurable per channel/call or hardcoded through some grpc-wide option? How would you actually expose the non-ok status code through the existing API (a successful read is expected to return a response that might not be available here). Overall, this seems really problematic to me.

How about we come up with some utility class that helps with this (by catching and handling the expected statuscodes and rethrowing the others?)

**Comment by jskeet** [comment]
I'd expect this to be configured on a per-call basis - and without knowing the guts of gRPC, I'd expect any complete response which is from the server to be passed on... if there _isn't_ a response from the server (because the socket died, for example) or if the response is incomplete, that would still result in an exception.

While a utility class is feasible and could help application code readability, it does still leave the performance problems of unnecessary exceptions, which could be significant in _some_ situations.

**Comment by jtattermusch** [comment]
The problem is once server returns a non-OK status, the semantics is that something went wrong with the call, you're not really guaranteed to receive all the responses. The background of this is quite complicated (there are situations when you are guaranteed to get all the responses and situations when you don't have that guarantee) and besides other things it depends on if you are using a streaming-response call or a unary-response call - for unary call you currently don't have the guarantee that you'll receive the response unless the status is OK. That's is fine with the way the C# API currently works - because awaiting a unary call result throws RpcException instead of returning a response - but it is not fine if we implemented the functionality you are asking for.

**Comment by jskeet** [comment]
By "response" do you mean the proto payload response as declared by the RPC (which I wouldn't expect to get) or a sort of "status" proto (which I *would* expect to get)? I'm fine for any partial response to be discarded, but I'd be worried if any error messages returned by the server were lost.

**Comment by jtattermusch** [comment]
@jskeet  yes, by "response" I mean the proto payload as declared by the RPC. That one you're not guaranteed to get. On the contrary, you are guaranteed to receive the Grpc.Core.Status (consisting of StatusCode and a "details" string) and all the responseTrailers (the trailing metadata) that the server has sent. One of the use cases of trailing metadata is to use a binary-valued metadata entry to pass a serialized custom "errorDetails" proto  (I think that's that "status" proto you had in mind).
