### ISSUE TITLE
Ruby generator doesn't refer to namespaced modules

### ISSUE THREAD

**Issue by nambrot** [grpc/grpc#6835]
I have two protobufs:

```
syntax = "proto3";

package razzleberry.messages;

message MemberId {
    string id = 1;
}
```

```
syntax = "proto3";

package razzleberry.services;

import "patient_messages.proto";
import "claims_messages.proto";

service Claims {
    rpc GetSummaryListFor(razzleberry.messages.MemberId) returns (razzleberry.messages.ClaimsSummaryListResponse) {}
}
```

With the ruby compiler, the first protobuf correctly gets compiled into

```
module Razzleberry
  module Messages
    MemberId = Google::Protobuf::DescriptorPool.generated_pool.lookup("razzleberry.messages.MemberId").msgclass
  end
end
```

However, since the service's protobuf is in a different package, this is the generated code:

```
      # TODO: add proto service documentation here
      class Service

        include GRPC::GenericService

        self.marshal_class_method = :encode
        self.unmarshal_class_method = :decode
        self.service_name = 'razzleberry.services.Claims'

        rpc :GetSummaryListFor, MemberId, ClaimsSummaryListResponse
      end
```

I.e. it should be `Razzleberry::Messages::MemberId` instead of `MemberId`.

I presume the issues is somewhere around https://github.com/grpc/grpc/blob/master/src/compiler/ruby_generator.cc#L70

**Comment by apolcyn** [comment]
This problem seems to be fixed with the latest grpc-ruby-protoc plugins (tried a few `grpc-tools` packages with a `version >= 1.0.0`).

As in the example above, 
used a `message.proto` that looks like:

```
syntax = "proto3";
 
package razzleberry.messages;

message MemberId {
      string id = 1;
}
```

and a `service.proto` that looks like:

```
syntax = "proto3";

package razzleberry.services;

import "message.proto";

service Claims {
      rpc GetSummaryListFor(razzleberry.messages.MemberId) returns (razzleberry.messages.MemberId {}
}
```

compiled with: `grpc_tools_ruby_protoc -I . --ruby_out=repro_lib --grpc_out=repro_lib message.proto service.proto`

and the resulting `repro_lib/services_services_pb.rb` contains:

```
rpc :GetSummaryListFor, Razzleberry::Messages::MemberId, Razzleberry::Messages::MemberId
```

Please reopen if you're still seeing this issue recent `grpc-tools` packages.
