### ISSUE TITLE
not compatible with musl c

### ISSUE THREAD

**Issue by AVVS** [grpc/grpc#6850]
Hi, I've noticed that nodejs gcloud library relies on this one, and, in turn, this relies on glibc, which, is not supported in alpine linux distributions, since it uses musl c.

There are wrappers around muslc that provide semi-compatible API with glibc and make it look like it, but the real question is whether it's planned to support musl c or not, given that it's rapidly rising in popularity (who wouldnt want a 5mb base image vs a bloated debian?)

Hope to hear some positive response, thanks :)

**Comment by keslerm** [comment]
This just got me too - Tried using libc6-compat but it just caused a different error 

`2016-06-21 16:35:38 - LoadError - Error relocating /usr/local/bundle/gems/grpc-0.13.1-x86_64-linux/src/ruby/lib/grpc/grpc_c.so: __strcat_chk: symbol not found - /usr/local/bundle/gems/grpc-0.13.1-x86_64-linux/src/ruby/lib/grpc/grpc_c.so`

**Comment by AVVS** [comment]
0.13.x wont work ever, upgrade to 0.14.x+, then you can use https://github.com/sgerrand/alpine-pkg-glibc inside alpine-linux

**Comment by peterhuene** [comment]
It'd also be nice if we could build grpc from source in Alpine.  I use an Alpine-based docker image for CI and just noticed that it doesn't build with musl libc (`sched_getcpu` isn't implemented).  I guess I'll have to switch to a glibc based distro for now (up to this point I was building a very lightweight docker image for demoing the product too, something not possible with other distros 😢 ).

**Comment by peterhuene** [comment]
I was able to build gRPC on Alpine using `edge`, which has musl libc 1.15.0 implementing `sched_getcpu`.

The following patches to gRPC were needed, though:

* `src/core/lib/support/wrap_memcpy.c` assumes GLIBC for wrapping `memcpy`. Since this appears to be a legacy fix, slapping a `#if defined(__GLIBC__) ... #endif` around the entire thing will solve the issue when building with musl libc.

* `grpc/src/core/lib/iomgr/tcp_posix.c` assumes `msg_iovlen_type` should be `size_t`, but `msghdr::msg_iovlen` is `int` in `/usr/include/bits/socket.h` on Alpine (x86_64).  For a x86_64 build, this results in truncation warnings (turned into errors) from `size_t` to `int`.  A proper fix to set `GPR_MSG_IOVLEN_TYPE` to `int` for Alpine is needed in `include/grpc/impl/codegen/port_platform.h`.

While it now builds, I haven't yet tested the resulting executables.

**Comment by amitripshtos** [comment]
I really hope this will fix someday.. It`s really important since alpine is lightweight and easy to work with.

**Comment by ctiller** [comment]
If it's possible to build this within a docker instance and folks are
willing to contribute some time, we ought to be able to get musl support
into our portability checks and keep things building in the future. Right
now besides giving advice I'm not sure that anyone on the team has
bandwidth to do the work however.

**Comment by soltanmm-google** [comment]
Coalesced to #8899.
