### ISSUE TITLE
Ruby server method handlers cannot send metadata

### ISSUE THREAD

**Issue by murgatroid99** [grpc/grpc#6870]
Ruby servers currently use a single special handler for the whole server to generate response metadata, before the regular handler is even called. This makes it difficult to send different metadata for different methods, and impossible to send metadata after reading any messages.

**Comment by apolcyn** [comment]
Looking into this for the compression settings case so that the server can see the client's metadata and possibly adjust the metadata to send back. There are a few things that I think need to change in the ActiveCall and the ruby Server main loop. 
Plan right now as we partially talked about is:

1. Have the ruby server main loop still first check availability and whether the method request is implemented, but don't send initial metadata yet if it can handle the request. Need to add a "send_trailers_only" method to the ActiveCall so that the available and implemented checks can call that instead of the "send_status" method that they call right now, which if I'm correct works only after already sending the initial metadata.

2. Allow the handler to optionally set or merge initial metadata on the ActiveCall. The server could still initialize the metadata of the active_call from the "connect_md" function before passing the active_call to the handler. When the handler tries to send a method on the active_call, have the active_call first send its initial metadata if it hasn't already, and have future attempts to change its metadata fail.
