### ISSUE TITLE
Correct and test bytes versus native strings in API

### ISSUE THREAD

**Issue by nathanielmanistaatgoogle** [grpc/grpc#6950]
Are the following true? I think that they should be, but we should make sure we're in agreement about what should be the case at the border of gRPC Python and the application and then look in the code to make sure that it is the case:

1. Metadata keys and values passed from gRPC Python to the application are always binary data and never native strings.
2. Status details passed from gRPC Python to the application are always binary data and never native strings.
3. Method names passed from gRPC Python to the application (as happens service-side) are always binary data and never native strings.
4. If we support applications passing either binary data or native strings into gRPC Python ("ad-hoc polymorphism") for things like target, method name (invocation-side), host, and so forth, we have test coverage for both options.

Or tell me I'm wrong?

(@jtattermusch and @ctiller for API comments.)

**Comment by kpayson64** [comment]
1. Yes
2. Yes
3. Yes
4. I agree, but we don't have good coverage on this yet.

**Comment by jtattermusch** [comment]
1. metadata keys should be "string" (in sense of "human-readable text").  metadata values are special and there are two flavors (the binary-value and text-value variant, both use the same C core api but at higher level, they are two distinct things).

2. status details are also a "string" (might be unicode one day).

3. method names are also "string" (might be unicode once day).

4. if we allow that, then we should have tests, but I think in most cases we should only have one API, unless there's a strong incentive from the performance point of view.

A good way how to tell "text" vs "binary" data in C core API is this:

- whatever is null terminated string is text (char *) (because null-terminated string cannot be used for binary data in C).
- whatever is char* with length passed as a second parameter (non-null terminated), is binary data (with the exception of text-valued metadata value)

**Comment by jtattermusch** [comment]
Based on the answers I gave, do we need to adjust the metadata API in python (it seems that the answers had a different outcome than what you've expected).

**Comment by kpayson64** [comment]
I think there might be some confusion here.  Python 'bytes' are definitely human readable text.  And they are capable of supporting unicode characters.

I could be persuaded that we should give the user back str details because it is most likely to be used for informational/display purposes and least likely to be used for matching and dictating logical flow.

However, metadata and method names are likely going to be used in equality comparison, and using the str type instead of the bytes type could introduce ambiguity that causes logical errors in user code.

@jtattermusch @nathanielmanistaatgoogle Does this seem like a reasonable compromise?

**Comment by nathanielmanistaatgoogle** [comment]
We met to discuss this several times today and are now resolved that where gRPC Python passes values to applications, all will be native strings except metadata values associated with keys ending in "-bin". Metadata keys, other metadata values, method names, host names, details strings: all native strings.

**Comment by hsaliak** [comment]
@nathanielmanistaatgoogle given the discussion, can you also document what needs to be changed here, if anything?

**Comment by nathanielmanistaatgoogle** [comment]
At least @kpayson64's [pull request 7091](https://github.com/grpc/grpc/pull/7091). I believe that that will be it for this issue?
