### ISSUE TITLE
Don't use Condition.wait() in the main event loop

### ISSUE THREAD

**Issue by kpayson64** [grpc/grpc#6999]
There is an issue with condition.wait() ignoring SIGINT https://bugs.python.org/issue8844

It has been fixed on Python3, but was not backported to Python2.7.  This can cause clients to hang on SIGINT if there are unfinished streaming calls.

Condition.wait(timeout) does not have this problem, but looking at the implementation, it does a 1-5 ms poll on the lock in Python (with the GIL), so I don't think its justified doing that as part of the main event loop.

**Comment by nathanielmanistaatgoogle** [comment]
Wholey Fish. I regret that I have but one head to desk and but one face to palm.

**Comment by nathanielmanistaatgoogle** [comment]
However galling this may be, it's highly unlikely to have any effect in the real world (as it would require the intersection of response-streaming RPCs or asynchronous response-unary RPCs, Python 2.7, needing to program at the interactive console, and Ctrl-C needing to work because Ctrl-Z-then-kill-the-process isn't good enough for some reason).

Closing with the acknowledgement that this is _in principle_ a problem and we're not going to do anything about it.
