### ISSUE TITLE
Why is NOT_FOUND an AbortionError in python?

### ISSUE THREAD

**Issue by parkan** [grpc/grpc#7002]
It looks like commit https://github.com/grpc/grpc/commit/c09a3580a1e802e92dfc8a1184b9a95fc464b979 changed NOT_FOUND to emit an `AbortionError` instead of `NetworkError`, which seems semantically strange (and also really blew up our app, which caught NetworkError specifically, ouch): request was not aborted by the client.

To be fair, NetworkError also seems wrong, because the network between hosts is fine. `RemoteError` seems marginally better but maybe a `BadRequestError` or something similar should be introduced

**Comment by nathanielmanistaatgoogle** [comment]
Notice that [`AbortionError`](https://github.com/grpc/grpc/blob/60e98ec3feab9cc347d6eacb48fb98cecb88c089/src/python/grpcio/grpc/framework/interfaces/face/face.py#L101) is a "[super type for exceptions indicating RPC abortion](https://github.com/grpc/grpc/blob/60e98ec3feab9cc347d6eacb48fb98cecb88c089/src/python/grpcio/grpc/framework/interfaces/face/face.py#L102)", is a superclass of [`NetworkError`](https://github.com/grpc/grpc/blob/60e98ec3feab9cc347d6eacb48fb98cecb88c089/src/python/grpcio/grpc/framework/interfaces/face/face.py#L142), and is suitable for use with any unsuccessful RPC. The change wasn't API breaking because there are no methods specified to raise `NetworkError`, only `AbortionError`.

It turned out that I wasn't able to make the distinctions between the different `AbortionError` subclasses align with other concepts throughout gRPC so I didn't retain use of them in c09a3580a1e802e92dfc8a1184b9a95fc464b979. The RPC's status code and details are what describe termination of an RPC in an implementation-independent way anyway.

In the GA API there is only [`grpc.RpcError`](https://github.com/grpc/grpc/blob/60e98ec3feab9cc347d6eacb48fb98cecb88c089/src/python/grpcio/grpc/__init__.py#L253) which has no attributes of its own but when used is mixed with a type that affords access to the status code and details.

**Comment by parkan** [comment]
@nathanielmanistaatgoogle NOT_FOUND was definitely wrapped as a `NetworkError` -- I'm not sure what you mean by "specified", is there an specification we can look at? We had to determine the error class by spelunking the cython code and dumping an actual error, because this does not appear to be documented on the python side at all (please point me in the right direction if this is wrong!)

I broadly agree that having a separate exception hierarchy that doesn't clearly map onto core RPC errors is confusing, does this mean that subclasses of `AbortionError` will be removed?

**Comment by nathanielmanistaatgoogle** [comment]
The [`__call__`] method that your application almost certainly calls [is sadly missing from the specification documentation](https://github.com/grpc/grpc/issues/7015) but [here it is](https://github.com/grpc/grpc/blob/60e98ec3feab9cc347d6eacb48fb98cecb88c089/src/python/grpcio/grpc/framework/interfaces/face/face.py#L366) (and [here is its "Raises:" section](https://github.com/grpc/grpc/blob/60e98ec3feab9cc347d6eacb48fb98cecb88c089/src/python/grpcio/grpc/framework/interfaces/face/face.py#L385)) in specification source.

Yes, `AbortionError` will be removed, along with the rest of the Beta API at some point when it's comfortable (six to twelve months from now?). Long after everyone's had several releases' worth of opportunity to migrate to [the GA API](https://github.com/grpc/grpc/blob/60e98ec3feab9cc347d6eacb48fb98cecb88c089/src/python/grpcio/grpc/__init__.py) ([we still haven't yet updated our examples](https://github.com/grpc/grpc/issues/4977)).

**Comment by parkan** [comment]
Thanks @nathanielmanistaatgoogle, looking forward to updated examples so we can move to GA API ASAP.
