### ISSUE TITLE
Implement status_code_and_message interop test in ruby

### ISSUE THREAD

**Issue by a11r** [grpc/grpc#7141]

**Comment by murgatroid99** [comment]
Am I correct in assuming that this issue is referring to both implementing the test case on the client side and the corresponding functionality on the server side?

**Comment by a11r** [comment]
Yes, that is correct.

**Comment by murgatroid99** [comment]
@apolcyn Can you look into this?

**Comment by ncteisen** [comment]
This is related to #8477. I have done a little work on this, which you can see at https://github.com/grpc/grpc/compare/master...ncteisen:ruby_advanced_interop.

I have finished unimplemented_method and unimplemented_service, and I am halfway through status_code_and_message and custom_metadata. I am blocked on the second half due to lack of experience with Ruby. I couldn't get the full duplex call working.

**Comment by yang-g** [comment]
Implemented in https://github.com/grpc/grpc/blob/7fd341746b3fc144a18e8b8491be5264d01eb7f8/src/ruby/pb/test/client.rb#L524
