### ISSUE TITLE
Decompression error is not captured and propagated to upper layers

### ISSUE THREAD

**Issue by muxi** [grpc/grpc#7149]
When the decompression algorithm fails, the current decompression code directly pass compressed data to user. May need to add error report and handing in this part of code.

Code ref: https://github.com/grpc/grpc/blob/1f6faf3725453d45953b2a55feafd7a368f96fff/src/core/lib/surface/byte_buffer_reader.c#L68-L72

**Comment by ejona86** [comment]
https://github.com/grpc/grpc/blob/d0fbba52d6e379b76a69016bc264b96a2318315f/src/core/lib/compression/message_compress.c#L184

Without knowing the code too well, it looks like this can be caused by two things:
 1. Misalignment of different parts of the code. Negotiation chooses a compressor that is unknown in grpc_msg_decompress
 2. If the data was corrupt

In either case it should be an error instead of silent propagation of compressed bytes. I wouldn't expect either case to be very common though.

**Comment by dgquintas** [comment]
Agreed. This issue was created for tracking purposes after an online discussion. I'm currently making changes to propagate the error.
