### ISSUE TITLE
Check the return value of grpc_byte_buffer_reader_init

### ISSUE THREAD

**Issue by dgquintas** [grpc/grpc#7205]
as part of `class ByteBuffer` in records.pyx.pxi

`grpc_byte_buffer_reader_init` returns status since #7190.

**Comment by soltanmm-google** [comment]
@nathanielmanistaatgoogle Does this want to propagate the reader status with an exception? Or is `None` enough?

**Comment by nathanielmanistaatgoogle** [comment]
@soltanmm-google: I don't think I yet know enough to say.

@dgquintas: tell us more about "[otherwise](https://github.com/grpc/grpc/blob/79620aaa1052fd02539a36caa63cbe24a2087b0f/include/grpc/impl/codegen/byte_buffer.h#L97)"? Does zero indicate a programming defect or an operational failure? Is it safe to reattempt the call to `grpc_byte_buffer_reader_init`? If we should raise an exception, what kind of guidance should we offer to Python applications about how to handle it? Should we just crash the process and exit right away with an attitude of "gRPC is over; go home"?

**Comment by soltanmm-google** [comment]
(since e38b917f9ee0e9f801384f6c89fe822f72eefa24)

**Comment by nathanielmanistaatgoogle** [comment]
Well, sure, but this still feels unsolved in a larger sense. We don't yet retry the read or report the problem to the application. Should we do either? Maybe the former a few times and then the other?
