### ISSUE TITLE
C#: grpc_csharp_ext.dll not found using dotnet cli

### ISSUE THREAD

**Issue by jskeet** [grpc/grpc#7230]
Using grpc 0.15.0 on Windows, and dotnet cli 1.0.0-preview2-003121.

This is about as minimal a repro as I can get:

`project.json`:

```json
{
  "buildOptions": { "emitEntryPoint": true },
  "dependencies": { "Grpc.Core": "0.15.0" },
  "frameworks": { "net45": {} }
}
```

`Program.cs`:

```csharp
public class Program
{
    public static void Main(string[] args)
    {
        var channel = new Grpc.Core.Channel("127.0.0.1:50052", Grpc.Core.ChannelCredentials.Insecure);
    }
}
```

Error:

```text
Unhandled Exception: System.IO.FileNotFoundException: Error loading native library. Not found in any of the possible locations c:\Users\jon\Test\Projects\grpctest\bin\Debug\net45\win7-x64\nativelibs\windows_x64\grpc_csharp_ext.dll
   at Grpc.Core.Internal.UnmanagedLibrary.FirstValidLibraryPath(String[] libraryPathAlternatives)
   at Grpc.Core.Internal.UnmanagedLibrary..ctor(String[] libraryPathAlternatives)
   at Grpc.Core.Internal.NativeExtension.Load()
   at Grpc.Core.Internal.NativeExtension..ctor()
   at Grpc.Core.Internal.NativeExtension.Get()
   at Grpc.Core.GrpcEnvironment.GrpcNativeInit()
   at Grpc.Core.GrpcEnvironment..ctor()
   at Grpc.Core.GrpcEnvironment.AddRef()
   at Grpc.Core.Channel..ctor(String target, ChannelCredentials credentials, IEnumerable`1 options)
   at Program.Main(String[] args) in c:\Users\jon\Test\Projects\grpctest\Program.cs:line 5
```

**Comment by jskeet** [comment]
I've been experimenting with this a bit.

I've created a new package `Grpc.Native` (just locally) with a nuspec file containing this:

```xml
  <files>
    <file src="windows-x86\grpc_csharp_ext.dll" target="/runtimes/win-x86/native/grpc_csharp_ext.x86.dll" />
    <file src="windows-x64\grpc_csharp_ext.dll" target="/runtimes/win-x64/native/grpc_csharp_ext.amd64.dll" />
    <file src="linux-x86\libgrpc_csharp_ext.so" target="/runtimes/linux-x86/native/libgrpc_csharp_ext.x86.so" />
    <file src="linux-x64\libgrpc_csharp_ext.so" target="/runtimes/linux-x64/native/libgrpc_csharp_ext.amd64.so" />
    <file src="macosx-x86\libgrpc_csharp_ext.dylib" target="/runtimes/macosx-x86/native/libgrpc_csharp_ext.x86.dylib" />
    <file src="macosx-x64\libgrpc_csharp_ext.dylib" target="/runtimes/macosx-x64/native/libgrpc_csharp_ext.x64.dylib" />
  </files>
```

This was inspired by the layout of `Microsoft.DiaSymReader.Native`, although that has a second copy of each file in `/runtimes/win/native` - it's not clear to me why there have to be two copies.

At that point, if `project.json` in the client project is changed to have this `frameworks` element:

```json
  "frameworks": { 
    "net45": {
      "dependencies": {
        "Microsoft.NETCore.Platforms": "1.0.1"
      }
    } 
  }
```

(and depending on `Grpc.Native` of course) then we end up with `grpc_csharp_ext.amd64.dll` with a plain `dotnet build`, and the x86 dll if I specifically build the x86 runtime version.

The dependency on `Microsoft.NETCore.Platforms` is required - without that, the library doesn't get copied.

That still doesn't work with the current release of gRPC as it's expecting it to be in subdirectories, but it's a start.

I'd strongly suggest that we at least have some way of specifying the library to use at execution time - there's a TODO in `NativeExtension.Load` for this. (Even just an environment variable would be a good start.)

**Comment by jtattermusch** [comment]
Thanks for looking into this, Jon!

It's an interesting problem, because if we want gRPC to work well with both old-style .csproj files and dotnet CLI, we basically need to support two ways of resolving native dependencies - dotnet CLI has its own builtin way (currently not supported by gRPC, but things are only broken for net45 projects). The old .csproj style projects don't have support for native dependencies at all (and that's why gRPC comes with its own custom way to load the native extension).

The only thing we really need to do is to make sure that the native libraries get copied to the output directory when build by dotnet CLI - after that, the gRPC's native extension loading code can be easily adjusted to load the library from a known location relative to the Grpc.Core.dll assembly (the code should already support looking for the native libraries in multiple locations - https://github.com/grpc/grpc/blob/e705dc44a1d850457f700a66089ef9fcd463178b/src/csharp/Grpc.Core/Internal/NativeExtension.cs#L114)

Ad using Microsoft.NETCore.Platforms:  requiring the user to depend on it is still a bit of a workaround but it's probably acceptable (considering this is only to fix dotnet CLI targeting net45 use case). I am wondering what is the magic part of Microsoft.NETCore.Platforms that enables the copying of libraries to the output directory - as that is the only piece we need to complete the puzzle.

**Comment by jskeet** [comment]
Yes, I don't know exactly how `Microsoft.NETCore.Platforms` works - it does seem to be the magic bit though. I quite like the naming scheme used by `Microsoft.DiaSymReader.Native`, with different filenames for different architectures so it would be possible to just xcopy a single directory and have that work on multiple platforms, if necessary.

How many more prereleases are likely for gRPC? I was wondering about at what stage it would be reasonable to drop DNX support (which is the third variant, and currently works). If there are still a couple more releases, we could add support for dotnet cli in the next release but keep DNX, and then remove DNX before the final release.

**Comment by jtattermusch** [comment]
I tried to use the techniques you suggested and was somewhat successful: https://github.com/grpc/grpc/pull/7295
