### ISSUE TITLE
Ruby performance: investigate using subclassing instead of include in generated code

### ISSUE THREAD

**Issue by murgatroid99** [grpc/grpc#7256]
This is a potential performance improvement in the Ruby library.

Information from the Ruby API review indicates that using `include` can cause a performance hit. We should investigate having the generated `Stub` class extend `ClientStub` instead of doing `include ClientStub`. If such a change is non-breaking and would improve performance and/or make more sense semantically, we should make the change.

**Comment by apolcyn** [comment]
Looked into this, but unfortunately didn't see any significant or non-random-looking difference between the two methods, at least when comparing their latency and qps by running the performance tests locally. 

Also, this change would be breaking since GenericService needs to be changed form a module to a class. If not using the generated proto code and just the GenericService directly, then one would have to switch from including to inheriting, which would only be possible if not already inheriting from their own class.

Experimental code for this is on this branch: https://github.com/apolcyn/grpc/tree/extend_service_perf_trial
