### ISSUE TITLE
C++ : how to invoke custom's completion tag in cq running thread

### ISSUE THREAD

**Issue by mike07026** [grpc/grpc#7305]
In our project, we are using grpc async APIs to implement an async-callback framework. To avoid race condiction, We have one CompletionQueue per thread model, say cq_, and one polling thread for it to dispatch callbacks once the result is ready:

cq polling thread: 

```
while (true) {
...
cq_.Next(&got_tag, &ok);
std::function callback = reinterpret_caststd::function<void()>(got_tag);
callback();
...
}
```

We need to do some operations inside and outside RPCs, and we want all these operation to be invoked in the cq polling thread.We want to invoke custom's tag on cq.

for example:

in others thread:

```
void* custom_tag = (void*)1234;
cq_.invoke_custom_tag(custom_tag);     // pseudo-code
```

cq polling thread:

```
...
cq_.Next(&got_tag, &ok);
// got custom_tag and RPCs tag here
...
```

We don't figure out how to achieve these in C++ GRPC APIs,  please help.

**Comment by yang-g** [comment]
C++ CompletionQueue is for grpc events only and you cannot put a custom callback to it.

What you may want to do is to have one or more dedicated thread to call cq_.Next and once you get a callback, dispatch it to a separated thread pool to run instead of running callback() in place. Then for your custom stuff, you can just say thread_pool_->Add(custom_callback).

**Comment by ctiller** [comment]
I'm somewhat open to adding an API for this however. We'd need to plumb it
through the C stack, but I can certainly see the usefulness.

void grpc_completion_queue_push_tag(grpc_completion_queue *cq, void *tag);
