### ISSUE TITLE
error message not surfaced in node.js client

### ISSUE THREAD

**Issue by eddavisson** [grpc/grpc#7382]
From https://github.com/GoogleCloudPlatform/gcloud-node/issues/1378#issuecomment-231152716

To reproduce:

1. Follow the "Installation and Setup" instructions for node.js [here](https://cloud.google.com/datastore/docs/datastore-api-tutorial).
2. Modify line 71 of `tasks.js` to use a reserved kind (e.g. `__kind__`).
3. `export GRPC_TRACE=http`
3. Run `node tasks.js new foo`.

I get:

```
$ node tasks.js  new foo
...
I0713 16:18:32.143006037   32059 parsing.c:657]              HTTP:1:TRL:CLI: grpc-status: 3
I0713 16:18:32.143024278   32059 parsing.c:657]              HTTP:1:TRL:CLI: grpc-message: The kind "__kind__" is reserved.
...
.../nodejs-docs-samples-master/datastore/tasks.js:172
          throw err;
          ^

Error: Bad Request
    at .../nodejs-docs-samples-master/datastore/node_modules/grpc/src/node/src/client.js:417:17
```

The error message from `grpc-message` does not appear in the error thrown by the node.js client.

**Comment by jayantkolhe** [comment]
Based on HTTP:1:TRL:CLI: grpc-message: The kind "__kind__" is reserved.'
This seems to be problem with wrapping layer... Michael, can you confirm?

**Comment by murgatroid99** [comment]
Yes, it seems likely to be a wrapping layer bug, but I will have to investigate to be sure.

**Comment by murgatroid99** [comment]
It looks like the problem in in gcloud-node. Until GoogleCloudPlatform/gcloud-node#1279, [this line in the gcloud source](https://github.com/GoogleCloudPlatform/gcloud-node/blob/b9fadbc807295fe8d44ac5793491ccf2fd6f99b6/lib/common/grpc-service.js#L272) was explicitly replacing the error code and message of errors returned from the gRPC library. That PR has not yet been published to npm, which is why we are still seeing this problem when using the gcloud npm package.

**Comment by stephenplusplus** [comment]
Thanks for catching that! A PR has been sent: https://github.com/GoogleCloudPlatform/gcloud-node/pull/1433
