### ISSUE TITLE
Remove duplicated BuildProtoModules from grpcio_health_checking

### ISSUE THREAD

**Issue by kpayson64** [grpc/grpc#7392]
The 0.15.1 release of grpcio-tools does not contain the command.py containing the BuildProtoModules class.  I've confirmed that command.py will be in the 1.0 release, so we can then pull it in as a setup dependency.

**Comment by soltanmm** [comment]
Note that this'll mean users who want to install `grpcio-health-checking` from the source distribution via `pip` from PyPI will be forced to install `grpcio-tools` first unless we put in some import-this-tool-only-if-we-need-to-generate-the-protos logic and always distribute `sdist`s with pre-generated `pb2`s. `pip` can't grab `setup_requires` automatically since it doesn't play nicely with the feature (it `egg_info`s first, which will choke on a naive import of `grpc.tools.command` without `grpcio-tools` installed).

I think we're okay with that because our primary means of distribution will always be wheels, and `sdist`s will always be second-class citizens for devheads on unusual systems; just making that explicit here.

**Comment by soltanmm** [comment]
Actually... I just looked at the release branch. Isn't this already done?

**Comment by kpayson64** [comment]
Ya I originally opened this issue because the artifact fails to build the way it was set up, so I copied and pasted the build command with a TODO referencing this issue.  I've since removed that hack.
