### ISSUE TITLE
How to generate interface definitions for node?

### ISSUE THREAD

**Issue by sjama** [grpc/grpc#7650]
I am trying to generate interfaces for node. Looking in the example I can see I need two files a `*pb.js and *grpc_pb.js`

I can generate the first file with node plugin
 
`protoc --js_out=import_style=commonjs,binary:. --plugin=grpc_node_plugin hello.proto`

But if I try to use --grpc_out flag to generate the second file
`protoc --js_out=import_style=commonjs,binary:. --grpc_out=.--plugin=protoc-gen-grpc=grpc_node_plugin hello.proto `

I get an error
`protoc-gen-grpc: program not found or is not executable
--grpc_out: protoc-gen-grpc: Plugin failed with status code 1.`

I don't know how to install this protoc-gen-grpc

I'm on  Mac OSX El Captain and I used homebrew then source to install protoc and the plugins.

**Comment by murgatroid99** [comment]
That first command just doesn't use the plugin at all. You don't need it to generate the `*pb.js` file.

The error message you're seeing is ambiguous. It means that it can't execute the program that you named `protoc-gen-grpc` by writing `protoc-gen-grpc=grpc_node_plugin`. The issue is that you have to pass it the full path to the plugin, even if it's in your `PATH`. So, assuming that it is in your path, you can run the command like this:

```sh
protoc --js_out=import_style=commonjs,binary:. --grpc_out=. --plugin=protoc-gen-grpc=$(which grpc_node_plugin) hello.proto
```

**Comment by sjama** [comment]
@murgatroid99 awesome. It works.

**Comment by hbksagar** [comment]
@sjama @murgatroid99 Need help, I am unable to find grpc_node_plugin though i tired installing via `npm install grpc-tools` and `npm install grpc` (Both Installed successfully without any warning and error). When I tried `which grpc_node_plugin`, throwing `grpc_node_plugin not found`.  I want to know how to install it on my mac.

**Comment by hbksagar** [comment]
Well it turned out the solution is mentioned in [sample app](https://github.com/grpc/grpc/tree/v1.6.x/examples/node/static_codegen) by grpc. And I was just looking at generated code! You miss out of many important things when you are tired and/or pissed off!
