### ISSUE TITLE
How to implement general Async Server/Client RPC

### ISSUE THREAD

**Issue by yyh-graphsql** [grpc/grpc#7658]
The requirement for me is to response some kinds of RPC request in another thread to unblock the worker thread in grpc. I cannot find a proper way to reply.
I looked at the example of grpc async server response (https://github.com/grpc/grpc/blob/release-0_14/examples/cpp/helloworld/greeter_async_server.cc), but it seems only can handle one kind of RPC. If I want to wrap a common library for all kinds of RPC, what can I do.
I also think may be we need easier async server/client RPC interface, for example, in client side, when want to async handle a response, just given a callback when initializing.

**Comment by vjpai** [comment]
There is no limitation on the number of methods in an async service -- feel free to add as many as you want to the service definition in the `.proto` file, and the code generation stage will automatically compile that down to a regular synchronous service and also an asynchronous service (as well as the option to separately choose sync/async for each individual method if you want).

We have intentionally steered clear of adding callbacks into the gRPC async API because calling application code from the library is hazardous. If the application code contains any blocking I/O or locks, the library itself could also be blocked in its progress. It's too restrictive to tell the application code to strictly avoid blocking I/O operations since the application may not be able to predict those properly. As a result, we're using the completion queue for notifications. If you want to arrange your program around callbacks, you can easily use the CompletionQueue::Next notification mechanism and then have your application code invoke a callback based on the  tag it receives from Next.

**Comment by jinq0123** [comment]
I am implementing a callback API. See https://github.com/jinq0123/grpc.
Following code is from my greeter_cb_server.cc which runs OK with greeter_client and my greeter_cb_client.
```C++
class GreeterServiceImpl final : public helloworld::Greeter::Service {
  void SayHello(
      const HelloRequest& request,
      ::grpc_cb::ServerReplier<HelloReply> replier_copy) override {
    ...
    HelloReply reply;
    replier_copy.Reply(reply);  // TODO: demo delayed reply.
  }
};
```
My async server will get a replier_copy on request which can be copied and Reply() in any thread at any time. SayHello() can return immediately without Reply().

**Comment by yyh-graphsql** [comment]
@vjpai  Thanks to explain. I thought we could provide a callback while specific its running Threadpool (may be some grpc::Threadpool). Is that against the design purpose? Another question is we cannot provide async and sync service in a service at the same time, is that right?
@jinq0123  Is there any core cpp file I can read, or some high level docs. Thanks a lot. I think I can write a wrapper for callback issues by learning your code.

**Comment by jinq0123** [comment]
ServerReplier is very simple. It just stores a Call object for further use.
See grpc_cb/impl/server/server_replier_impl.h.

Also see the generated CallMethod() in helloworld.grpc_cb.pb.cc:
```C++
void Service::CallMethod(
    size_t method_index, grpc_byte_buffer& request_buffer,
    const ::grpc_cb::CallSptr& call_sptr) {
  switch (method_index) {
    case 0:
      SayHello(request_buffer,
          ::grpc_cb::ServerReplier<::helloworld::HelloReply>(call_sptr));
      return;
  }  // switch
}
```
For docs, see src/cpp_cb/README.md.

**Comment by vjpai** [comment]
@yyh-graphsql : If you use sync methods, your service method code will be called directly by the server's thread pool. That's how the sync examples work. If you want, you can have that sync service code invoke other async work.

You can have sync and async methods in the same service. It's not a common use case, but it is possible. If you define functions that way, then the sync methods will be executed using the gRPC server's thread pool but the async methods will be up to you to implement using explicit completion queues. We don't have that shown in one of the examples, but the syntax for doing this is shown in test/cpp/end2end/hybrid_end2end_test.cc ; just look through the code for examples of "WithAsyncMethod". I hope that helps!

**Comment by yyh-graphsql** [comment]
@vjpai Is there any methods I can try to reply the response in your so called 'other async work'?

**Comment by vjpai** [comment]
I just meant that your service method can issue other RPCs or create other threads if it wants, and those can be sync or async.

**Comment by yyh-graphsql** [comment]
Thanks for helping me. It works for me right now.

**Comment by vinayrao68** [comment]
@vjpai: Can a async client (c++) call into a sync server (java)?
Also can a sync client (java) call into a async server?

**Comment by ncteisen** [comment]
Yes. All gRPC traffic, regardless of sync/async, follows the wire protocol.

**Comment by vw-insti** [comment]
I am looking for the same too.

**Comment by vw-insti** [comment]
Basically how to read the asynch stream reply(multiple messages on a single request but asynch) on client side using the completion queue.
