### ISSUE TITLE
Python compile from source fails on python2 because of threadlocal error.

### ISSUE THREAD

**Issue by virtuald** [grpc/grpc#7767]
For some reason `MACOS_DEPLOYMENT_TARGET` is only set when compiling python 3, and not python 2? See [this line in setup.py](https://github.com/grpc/grpc/blob/master/setup.py#L161).

Specifying it manually fixes the problem, but you should probably update `setup.py`...

```
MACOS_DEPLOYMENT_TARGET=10.7 pip install .
```

**Comment by kpayson64** [comment]
If I remember correctly, there was some explicit check in distutils for Python 3 that verified the MACOS_DEPLOYMENT_TARGET that didn't exist in Python 2.  Its possible that the change was back-ported to newer versions of Python2.7.

What exactly did the error look like that you saw?

**Comment by virtuald** [comment]
Something about "thread-local storage is unsupported for the current target".

As I said, if you set the environment variable, then it works without a problem. If you don't set it, it doesn't work. Currently, setup.py sets it for python3, and not for python2 for some reason.

**Comment by soltanmm** [comment]
It wasn't being set for Python 2 because we were relying on what @kpayson64 mentioned. The Mac OS X target for Python 2.7 is treated (in every Python 2.7 patch-version I've seen thus far) as being the current machine rather than the system Python's original build target (which is usually 10.6 iirc). Given that Python 3.x ensures 10.6 linkage by default, it's thus up for concern that such a target setting may have been backported to Python 2.7 as a bugfix to `distutils`* and we missed it. What's your Python 2.7 patch version? What's the output of `env` in your build shell setup?

\* <sup>though I could have sworn upstream froze `distutils` years ago...</sup>

**Comment by virtuald** [comment]
I'm using Python 2.7.11. There weren't any build-specific settings in env as far as I can tell, just your normal random shell stuff.

**Comment by nathanielmanistaatgoogle** [comment]
Punting from `1.1.0`; this could use a prioritization and possibly a work estimation. @soltanmm-google: any opinions on this?

**Comment by kpayson64** [comment]
If this is still an issue, feel free to reopen.
