### ISSUE TITLE
grpc.secure_channel docstring has copy-pasta text from grpc.insecure_channel

### ISSUE THREAD

**Issue by dhermes** [grpc/grpc#7791]
The [`grpc.secure_channel` docstring][1] says "Creates an insecure Channel to a server." but should say "Creates an secure Channel to a server."

PS Sorry for the bad email, I bumped the enter key way too early

[1]: https://github.com/grpc/grpc/blob/6cfc80edaf8ec1e46c9cbbc1f402a0a8a8259f16/src/python/grpcio/grpc/__init__.py#L1196

**Comment by nathanielmanistaatgoogle** [comment]
Ouch. [Fix drafted](https://github.com/grpc/grpc/pull/7806).

**Comment by nathanielmanistaatgoogle** [comment]
This fix has now landed on both `v1.0.x` and `master`.

**Comment by dhermes** [comment]
SGTM, though I can't find any release after `1.0.0`

**Comment by nathanielmanistaatgoogle** [comment]
We think we'll cut our first post-`1.0.0` release in the next week or two, but don't hold us to that. We think it will be called `1.0.1`, but don't hold us to that either.

Are you looking to verify the fix? GitHub's issue tracker doesn't offer issues a "fixed in source but fix has not yet propagated through released process and reached its users" issue state. :-(

**Comment by dhermes** [comment]
Wasn't trying to dispute that it was fixed in source, just trying to understand your

> now landed on ... `v1.0.x`

comment.

**Comment by nathanielmanistaatgoogle** [comment]
Oh, thank you for clarifying. [`v1.0.x` is a branch](https://github.com/grpc/grpc/branches/active).

**Comment by dhermes** [comment]
Got it.
