### ISSUE TITLE
Node.js - accessing peer certificate

### ISSUE THREAD

**Issue by sackio** [grpc/grpc#7834]
Is it possible to access the peer certificate information for a client in the Node.js module (i.e. checking the certificate properties of the client)?

I'm looking for something similar to the getPeerCertificate method for sockets in the TLS module (https://nodejs.org/api/tls.html#tls_tlssocket_getpeercertificate_detailed) # # @

**Comment by cyberflohr** [comment]
+1 would be great to see this soon :-)

**Comment by murgatroid99** [comment]
@jboeuf Do we have this in core?

**Comment by jboeuf** [comment]
Yes we do through the `auth_context`. @jtattermusch and I are going to work on the server-side auth APIs for wrapped languages this quarter.

**Comment by sackio** [comment]
thanks @jboeuf and @murgatroid99 -- eager to implement something that would use this in node.js asap -- and would be happy to contribute the resulting source as an example in your documentation when it's ready

**Comment by jboeuf** [comment]
Thanks Ben. I'm not quite ready for this effort just yet (probably in Feb
though). When the time comes, we'll probably get back to you so that you
can be one of our first guinea pigs :).

**Comment by Asara** [comment]
I am also volunteering to be a guinea pig for this.  Would love the ability to access the CN via node.js

**Comment by blerest** [comment]
Do you have any news regarding this feature? This would be really useful!

**Comment by jboeuf** [comment]
There's a pull request by @jtattermusch to this work in C# but I guess that given the demand, node should come next. @murgatroid99 what do you think?

**Comment by jtattermusch** [comment]
Here's the PR for C#: https://github.com/grpc/grpc/pull/9632. Opinions are welcome.

**Comment by adam-26** [comment]
I think the same functionality should also be available on the client, the client should be able to inspect the servers peerCertificate data. 

Related, it would be great if some events could be exposed on the nodejs client (see #8117), including an event that enables peerCertificate validation.

Should this be created as a separate PR?

**Comment by jboeuf** [comment]
I agree that this should be exposed on the client side (it is in C and C++). However, by the time it is populated and it is too late to do any checks as the call has basically been made. The server cert validation is done by the inner logic of the gRPC protocol (according to HTTPS semantics in this case) without giving the application the opportunity to change the behavior except for some very limited use cases limited to testing such as the SSL_TARGET_NAME_OVERRIDE and it is probably safer this way.
However logging of the certs used on the server from the client is a good use case for such an API.

**Comment by adam-26** [comment]
Would it be possible to modify the handling of the internal TLS handshake to allow clients to inspect/validate server certificates before continuing with the request?

From a security perspective, it would be beneficial for a client to be able to validate a servers certificate public key (fingerprint) to prevent MITM attacks. I realize that mutual TLS could be used, but that adds the overhead of key management, and is not suitable for all deployments.

**Comment by jboeuf** [comment]
We *could* add a certificate pinning option if there is a high demand for it. However, I don't like it too much since pinning is fragile (what happens if the key for a given domain is rotated for valid reasons). [Certificate transparency](https://www.certificate-transparency.org/) is a much better option for protecting against CAs that issue certs for domains they should not issue certs for. I can see a future where we have a plugin to support certificate transparency on the validation path.

Opening the validation to application code is dangerous because this is not a well understood topic and will lead to applications not doing the right thing. E.g. "My test certificate does not work because it's hosted on localhost: let me hack a custom validator that will be a no-op so that my tests pass. Oh, this shipped into production.... ooops...".

**Comment by adam-26** [comment]
I understand what you're saying, but I don't agree that grpc should be responsible for trying to protect developers from such mistakes. Preventing developers from _improving_ security only to eliminate the risk that some developers accidentally reduce security seems like a poor trade off.

Being able to write plugins for the certificate validation path would be very useful. In terms of protecting developers, providing pre-defined plugins (such as certificate transparency) would be great and reduce the probability of developer mistakes.

**Comment by jboeuf** [comment]
Let's agree to disagree then :). I certainly appreciate the discussion and again, we may add a way to do certificate pinning through credentials options which should take care of your concern. However, as things stand, I will not approve of any APIs that opens the raw validation path to application code. From experience, this leads to developers shooting themselves in the foot.

**Comment by chetmurthy** [comment]
Was there a resolution here?  At a minimum, is it possible for a client Node.JS program to access the server's cert, starting from an established GRPC client-handle? [I recognize that this probably means at least -one- RPC has already transpired; I'm at peace with that.]

**Comment by andrewpmartinez** [comment]
I'm in a situation where I am using grpc and mutual TLS. Seems odd that I can't access the peer certificate to make additional authentication checks. The client certs already aserts the client's identity, I don't really want to assert identity again.

**Comment by chetmurthy** [comment]
Oh, so it still hasn't been fixed, has it?  Sigh.  When I read both the relevant threads, back in October, it seemed clear that the Google guys felt that "our way or the highway" was appropriate.  And given that the *purpose* of GRPC is so you can access Google's servers, and NOT so you can write your own servers, that makes perfect sense.

If you actually want a decent RPC stack, can I suggest Thrift?  B/c really, GRPC's shit is weak.

**Comment by thisisnotapril** [comment]
@chetmurthy I'm really sorry you've had a bad experience with this issue. I've asked project leads for more info on this so we can get you an update and resolution. Please feel free to reach out to me direct at anassi@google.com - I'd really appreciate the opportunity to hear more from you on how we can do better.

**Comment by chetmurthy** [comment]
@thisisnotapril  I think if you look at this comment: https://github.com/grpc/grpc/issues/7834#issuecomment-288785780 wherein @jboeuf says "let's agree to disagree then .... I will not approve of any APIs that opens the raw validation path to application code", it seems clear that the goal of GRPC is a vertically-integrated stack, wherein developers are prevented from "shooting themselves in the foot."  Now, that's great, when you're dealing with people writing clients, and esp. clients that talk to some large body of existing services like ... say .... Google.

But if you're building your own services, that's just inappropriate.  And it isn't just that NodeJS GRPC (1) doesn't allow me to specify logic for mutual TLS auth (via something like Golang's VerifyPeerCertificates), though that's already bad.

(2) more generally, GRPC is (in neither JS nor Golang, and hence, I conjecture in every language) not structured so I can substitute my own "transport", e.g. a transport that uses a different form of encryption.

  --> why might I want this?  Well, SSL is both weak and slow.  There at least some good reasons to think that NaCl (libsodium) is much better.  But I can't use it with GRPC; I -can- use it with Thrift, b/c Thrift as a separation between "transports" (byte-streams), "protocols" (details of type marshaling), Processors (details of RPC service marshaling), and server-skeletons, which take care of threads, connection-initiation and -termination, etc.

  --> BTW, a while back somebody asked if GRPC might be factored so that he could perform the (server-side) "accept" logic (and creation of a connection) and then hand it to GRPC to run RPCs across it.  The answer (of course) was "no way, man".  What this guy wanted, to was to replace the "server-skeleton" with his own; in Thrift, this is trivial.

  --> for instance, I once wrote a thrift application where process A TCP-connects to process B, and then process A accepts and processes RPCs from process B (the backwards of the normal case).  Such a mode would be impossible with GRPC.

  --> another example: process A forks process B, and then wants to run RPCs to process B.  The -safest- way to do this is for process A to create a socketpair() before the fork.  But if you do that, you can't use GRPC to run those RPCs.  With GRPC, process B would have to set up a server-socket, and process A would connect to it.  That's less secure, more cumbersome, more steps, and impossible to test all the failure-modes of.  Gee, that's BRILLIANT!

(3) The fact is, GRPC (in golang & JS) runs over HTTP[S], and nothing but.  And gosh, that means you don't get any sort of thread-affinity between the client & server threads -- b/c it's not guaranteed, and even if it were, it's entirely possible that the connection could be closed and reopened between requests

  --> BTW, this makes Andrew's request even more paramount.  He's thinking "gee, I could do my own phase of authentication after SSL does its stuff" but he's forgetting that he has no visibility to the closing/reopening of TCP/SSL connections.  So even if he did that auth, it might turn out that the NEXT RPC went to a thread where that auth work wasn't known.

  --> Of course, if you write your server in Golang, you don't have any sort of thread-local state, and since the "server-skeleton" doesn't provide any, you basically have to write apps that need conversational state as if they're running in a web server.  Which is the point, isn't it?  B/c GRPC is basically only designed as a way for clients to access web-apps.

  But that's not what it's advertised as, is it?  It's -advertised- as being some general-purpose RPC framework.

(4) I've used Thrift extensively, writing a transport that runs over Infiniband, and doing quite a few other interesting things.  None of that would be possible with GRPC, without doing massive surgery, and hence a massive fork.  Whereas in Thrift, it was just another Transport class.

I'll stop here.  B/c honestly, I can understand why Google does not and will not fix these things.  After all, none of these changes would make it any easier to access Google's services.  Instead, they would make it easier to build services of one's own.

**Comment by cwpetersen1971** [comment]
This feature would be useful

**Comment by fturiot** [comment]
This feature exist or not ?
