### ISSUE TITLE
could gRPC have a plan to support .Net 4.0?

### ISSUE THREAD

**Issue by chinhol** [grpc/grpc#7880]

**Comment by jtattermusch** [comment]
This is tricky for several reasons:

1. we are using async/await feature from .NET 4.5 heavily, and backporting to .NET 4.0 (that doesn't have async/await support) is troublesome and pretty work intensive - probably not worth the effort.
2. we'd rather invest resources into supporting CoreCLR which is where the future of .NET lies instead of trying to backport gRPC to outdated platforms (.NET 4.0 is pretty old).

Do you have anything in particular that prevents you from migrating to .NET 4.5 or CoreCLR?

**Comment by jtattermusch** [comment]
So, we most likely won't work on this unless we get a (very strong) signal from the community that providing .NET 4.0 support is crucial (but I think anyone who's looking into adopting gRPC would already be on 4.5+).

**Comment by sercand** [comment]
One use case for older .NET would be Unity3D but even protobuf does not support it.

**Comment by jtattermusch** [comment]
Unity needs to come up with support with .NET 4.5+ or netstandard (and I believe it's coming at some point).

We don't have any plans to start supporting .NET 4.0 any time in the future.

**Comment by tbillington** [comment]
Unity released [beta support](https://forum.unity3d.com/threads/upgraded-mono-net-in-editor-on-5-5-0b4.433541/) for 4.6 end of last year and it's now an opt-in option as of Unity 2017.1.

Any change of re-investigating this ? :)

**Comment by tbillington** [comment]
@sercand Unity released [beta support](https://forum.unity3d.com/threads/upgraded-mono-net-in-editor-on-5-5-0b4.433541/) for 4.6 end of last year and it's now an opt-in option as of [Unity 2017.1](https://blogs.unity3d.com/2017/07/11/introducing-unity-2017/).

**Comment by jinq0123** [comment]
https://github.com/ahakits/unity-grpc-sample works on Unity 2017.1.

**Comment by boss651** [comment]
Any updates with support .Net 4.0?
