### ISSUE TITLE
Compile error on Red Hat

### ISSUE THREAD

**Issue by thinkerou** [grpc/grpc#7946]
Step1: git clone
Step2: make
The error follow info:

	[thinkerou grpc]$ make
	[MAKE]    Generating /home/users/thinkerou/work/grpc/libs/opt/pkgconfig/grpc.pc
	[MAKE]    Generating /home/users/thinkerou/work/grpc/libs/opt/pkgconfig/grpc_unsecure.pc
	[MAKE]    Generating cache.mk
	[C]       Compiling src/core/lib/profiling/basic_timers.c
	cc1: error: unrecognized command line option "-Wsign-conversion"
	make: *** [/home/users/thinkerou/work/grpc/objs/opt/src/core/lib/profiling/basic_timers.o] Error 1

My sys info:

	[thinkerou grpc]$ cat /proc/version
	Linux version 2.6.32_1-17-0-0 (thinkerou) (gcc version 4.4.4 20100726 (Red Hat 4.4.4-13) (GCC) ) #1 SMP Mon Aug 24 11:14:27 CST 2015

**Comment by pgrosu** [comment]
@thinkerou Change [lines 64-80 in Makefile](https://github.com/grpc/grpc/blob/master/Makefile#L64-L80) to the following to use gcc - I've pretty much had do it all the time:

```
#ifeq ($(HAS_CC),true)
#DEFAULT_CC = cc
#DEFAULT_CXX = c++
#else
ifeq ($(HAS_GCC),true)
DEFAULT_CC = gcc
DEFAULT_CXX = g++
else
ifeq ($(HAS_CLANG),true)
DEFAULT_CC = clang
DEFAULT_CXX = clang++
else
DEFAULT_CC = no_c_compiler
DEFAULT_CXX = no_c++_compiler
endif
endif
#endif
```

**Comment by thinkerou** [comment]
@pgrosu Thank you for replying, but the error still exist.

**Comment by pgrosu** [comment]
@thinkerou Could you type `cc -v` and let me know the version you're using please?

**Comment by thinkerou** [comment]
[thinkerou grpc]$ cc -v
	Reading specs from /usr/lib/gcc/x86_64-redhat-linux/3.4.5/specs
	Configured with: ../configure --prefix=/usr --mandir=/usr/share/man --infodir=/usr/share/info --enable-shared --enable-threads=posix --disable-checking --with-system-zlib --enable-__cxa_atexit --disable-libunwind-exceptions --enable-java-awt=gtk --host=x86_64-redhat-linux
	Thread model: posix
	gcc version 3.4.5 20051201 (Red Hat 3.4.5-2)

**Comment by pgrosu** [comment]
So the first time this warning option appeared was in version 4.3.6:

https://gcc.gnu.org/onlinedocs/gcc-4.3.6/gcc/Warning-Options.html#Warning-Options

The 3.4.5 version does not have this option:

https://gcc.gnu.org/onlinedocs/gcc-3.4.5/gcc/Warning-Options.html#Warning-Options

My recommendation is try to upgrade your GCC to a newer version.

~p

**Comment by thinkerou** [comment]
OK, thanks.

**Comment by nicolasnoble** [comment]
gcc *3.4.5* ?! I haven't seen something that old in a long time. What
distribution are you on ? This seems to be CentOS 4, which has been out of
support since 2012, and we're not going to support something this old. In
fact, our oldest supported compiler version for gcc should be 4.4.

**Comment by nicolasnoble** [comment]
Also, Paul, if you want to force the usage of gcc over cc, you can simply
do `HAS_CC=no HAS_GCC=yes make`, without changing the Makefile.

**Comment by pgrosu** [comment]
Cool, thanks Nico!

**Comment by vjpai** [comment]
We are committed to gcc 4.4+ but our C++ code will not possibly build under any older version. We use a pretty limited subset of C++11, but anything before 4.4 doesn't even support basics like auto variables. As you've seen, we also expect the presence of certain warning levels that weren't in older versions even for building the C library. If you really need such an old version of gcc, you can still build the C library by manually removing undesirable warnings from the Makefile template, but there is essentially no C/C++ API support at that point. Strongly recommend upgrading your gcc.

Meanwhile, I will close this issue since there's nothing further that we can add at this point.

**Comment by nicolasnoble** [comment]
So this is most likely RHEL 4, in fact. Its extended, commercial support ends the 31 March 2017, which is in a few months. Yes, I don't see ourselves going that much out of our way to support it. If you're indeed paying for the extended support of RHEL 4, I would suggest talking with your vendor about this issue instead. Otherwise, you're out of support completely, and we'd strongly suggest moving to a more recent version of your operating system.

**Comment by thaynewalker** [comment]
I found that the makefile is using the "which" command to determine if gcc (or other c compilers) are installed. In my case, I was able to fix this by installing "which". If you already have "which" installed, make sure your $PATH can find the directory where your c compiler is installed.
