### ISSUE TITLE
Grpc Python client performance is slow compared to C++ client in arm Target

### ISSUE THREAD

**Issue by Rajesh1985** [grpc/grpc#7949]
We are using grpc 0.15.1, and we are seeing performance related issue in python at arm target.

We have c++ and python grpc clients which does the same and runs in the arm target and server is in the c++ application. 

In which we are seeing performance issue in the python client, it takes more time than c++ client. 
For example c++ grpc call takes 1 to 3 ms on an average, same functionality in  python grpc call take 55 to 60 ms on an average.

Please provide your feedback. 

Thanks 
Rajesh

**Comment by nathanielmanistaatgoogle** [comment]
Nothing to do with performance, but: what's got you using 0.15.1 rather than 1.0.0?

As to performance: it is expected that gRPC Python will be slower than gRPC C++, but not twenty times as slow. Would it be possible for us to look at your code to see what you might be doing that would slow you down?

**Comment by nathanielmanistaatgoogle** [comment]
This has gone too long unanswered; closing.
