### ISSUE TITLE
Better efficiency in the Python client?

### ISSUE THREAD

**Issue by synaptic** [grpc/grpc#7950]
The code-generated Python for client usage seems to not be built for efficiency, which can be a problem for resource-constrained environments.  It instantiates a series of nested classes every time you do a read.  These classes are full classes instead of space-saving ones via the [`__slots__`](https://docs.python.org/2/reference/datamodel.html#slots) class variable.  Was using `__slots__` ever considered but rejected for some reason?

I added `__slots__` to certain classes in `grpc.beta._client_adaptations.py` and saw a roughly 10% speed-up, anecdotally.  And it didn't seem to break anything (classes that define `__slots__` cannot have new attributes added to instances, nor do they support multiple inheritance.)  Is this something we want to consider adding so that all Python clients see a speed-up, regardless of their resource constraints?

**Comment by kpayson64** [comment]
I don't believe this is something we have considered before.  We are working on improving Python performance, and would welcome a contribution that gives us a 10% speedup.

One thing to note is that the beta api is deprecated and will be removed at some point.  The examples at www.grpc.io have been updated with the 1.0 API, as well http://www.grpc.io/grpc/python/grpc.html.

If __slots__ can be used in some way to get a similar performance gain in the 1.0 API, open a pull request with the needed changes and we can try to integrate it into gRPC Python.

**Comment by synaptic** [comment]
Using `__slots__` may not help as much as I thought.  Further performance testing shows that biggest latency is in the `cygrpc.CompetionQueue.poll()` call.  Here is a narrowly-defined cProfile run (I'm still using grpcio version 0.15.0):

```
   ncalls  tottime  percall  cumtime  percall filename:lineno(function)
       64    0.002    0.000    0.388    0.006 C:\...\site-packages\grpc\_channel.py:467(__call__)
       64    0.003    0.000    0.385    0.006 C:\...\site-packages\grpc\_channel.py:452(_blocking)
       64    0.276    0.004    0.276    0.004 {method 'poll' of 'grpc._cython.cygrpc.CompletionQueue' objects}
```

Is there a reason [this Python call](https://github.com/grpc/grpc/blob/master/src/python/grpcio/grpc/_cython/_cygrpc/completion_queue.pyx.pxi#L83-L107) should make the Python API slower than the C++ API?  We have noticed that it can be up to 3X in latency for resource-constrained environments.

**Comment by nathanielmanistaatgoogle** [comment]
@synaptic: thank you for digging in further! Regarding "biggest latency is in the `cygrpc.CompetionQueue.poll()` call": this is good, because that is where, by system design, we expect most of the work and all of the waiting-for-bytes-off-the-network to be done. Regarding "Is there a reason this Python call should make the Python API slower than the C++ API? [By] up to 3X": there's no reason for that (notice that `cygrpc.CompletionQueue.poll()` doesn't do much of significance other than call `grpc_completion_queue_next`) and we would love to know more - traces, flame graphs, whatever metrics you can throw at us. Please also share the code you're writing that's making these measurements and the details of the systems on which it is running?

If _possible_, we'd love to hear about 1.0.0 rather than 0.15, but given that the code didn't change too much between 0.15 and the present day, this isn't too important.

**Comment by ctiller** [comment]
One reason for CQ poll seeming slower than with C++: the peer may be offering less work to do. Are you testing using the same client against a Python server and a C++ server, or different clients? If they are different clients, then we have an answer.

**Comment by heri16** [comment]
Are there benchmarks or graphs on actual perfromance of python client with c native extensions? Seems missing on the official dashboards.
