### ISSUE TITLE
C#: Grpc.Core.Server Exception while handling RPC. System.InvalidOperationException: Error sending status from server

### ISSUE THREAD

**Issue by amitwaisel** [grpc/grpc#8009]
When sending a large (over 4MB) _response_ message from a _C# server_ to client (C++ in my case), the C# server traces the following error

```
W0907 13:57:45.566540 Grpc.Core.Server Exception while handling RPC. System.InvalidOperationException: Error sending status from server.
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at Grpc.Core.Internal.UnaryServerCallHandler`2.<HandleCall>d__0.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Grpc.Core.Server.<HandleCallAsync>d__11.MoveNext()
```

**The client receives an invalid (empty) result - the data is not really transferred**.
The issue happens in version 1.0.0 from NuGet.

Looks similar to issue #6990 @apolcyn

**Comment by apolcyn** [comment]
This is probably due to the "grpc.max_message_length" channel arg not being changed from its default. Tried c++ client and c# client to c# server, with default message lengths (appeared be about 4mb), and did get that same error on all calls.

This should be able to be fixed by setting the max message length on all of the client channels and grpc servers dealing with those larger messages.

Exact code varies, but for C# server, for example, it can be done like:
```
Server server = new Server(new List<ChannelOption>{ new ChannelOption(ChannelOptions.MaxMessageLength, 8388608) })
...
```

It looks like the exact default max message length varies per grpc implementation. There's more dicussion on this unclearness surrounding the max message lengths of client and server channels in https://github.com/grpc/grpc/issues/7927.

For the error, assuming this is due to a max message length too small I think that InvalidOperationException still makes sense, but perhaps the message could be adjusted somehow.

**Comment by apolcyn** [comment]
closing, please reopen if that was not a fix.
