### ISSUE TITLE
node: ending a server-side stream from the client

### ISSUE THREAD

**Issue by paralin** [grpc/grpc#8023]
In the documentation: http://www.grpc.io/docs/tutorials/basic/node.html

I don't see anything about ending a server-only stream (client requests, server streams back data) from the client cleanly. I have tried calling `.end()` but that returns `TypeError: this.rpcCall.end is not a function`.

**Comment by murgatroid99** [comment]
In general, the assumption of a server-only streaming call is that the initial message from the client contains enough information for the server to know when to stop.

If the client unexpectedly has to stop the stream in the middle, you can cancel the call (`call.cancel()`). Note that this will terminate the call with a CANCELLED status.

If you expect in general that you will only decide when to stop the stream after you have started the stream, then I would recommend using a bidirectional-streaming call, where you send one message from the client to start the stream from the server, and another to end it.

**Comment by paralin** [comment]
Thanks for the clarification. Is `cancel()` documented anywhere? Sorry if I missed it.

**Comment by willdzeng** [comment]
I can't find this `cancel()` function also, which object has cancel()? `ClientReader` or `ClientContext`? I only found `TryCancel()` in `ClientContext`

**Comment by murgatroid99** [comment]
@willdzeng I think you're talking about a different language. The Node.js library does not have `ClientReader` or `ClientContext` types.

**Comment by willdzeng** [comment]
Or, sorry, yeah, I mean in c++.
I guess in c++, the easy way to cancel stream is to destroy the client and check the return of `Write()`
```
if (!writer->Write(reply)){
    break;
}
```
The example of c++ doesn't show how to cancel a stream.

**Comment by murgatroid99** [comment]
The `cancel` method is now documented in the documentation for call objects such as [`ClientReadableStream`](https://grpc.io/grpc/node/grpc-ClientReadableStream.html), which are the return values for the corresponding client method types.

**Comment by shanshanzhu** [comment]
I tried cancelling the ClientWritableStream by `call.cancel()`, and get the `Error: Cancelled`
from the doc it says that `the call will be cancelled and the stream will end with an error`
Is it by design to show an error for cancelled ClientWritableStream?

**Comment by murgatroid99** [comment]
I'm not sure what the problem is. The documentation says the call will end with an error, and the error you got looks like the right error.

**Comment by shanshanzhu** [comment]
@murgatroid99 Sorry typo, changing ClientWritableStream -> ServerWritableStream. I'm finding a way to  end a server-only stream without raising an error.

**Comment by murgatroid99** [comment]
OK, if I'm understanding correctly, this code is on the server, and you don't want to cancel the call, you just want to end the stream. That class is a [Writable stream](https://nodejs.org/api/stream.html#stream_writable_streams), so you can end it with the `.end()` method.

**Comment by shanshanzhu** [comment]
@murgatroid99 our .proto for this particular one is in this format
```
Service ExampleService {
    rpc ExampleRpc(Request) returns (stream Response) {}
}
```
Does that mean the call we get on client side cannot be a writable stream?
```
// ProtoService is from grpc.load code
const call = new ProtoService('0.0.0.0:50051', grpc.credentials.createInsecure())
call.on('data', (response) => {});
call.on('end', (response) => {});
```

To get a client side writable stream, do we need to specify the .proto as this?
```
Service ExampleService {
    rpc ExampleRpc(stream Request) returns (stream Response) {}
}
```

**Comment by murgatroid99** [comment]
The variable named `call` in that code is in fact a client object, not a call object. In order to get a call, you have to invoke a method of the client, in this case `exampleRpc`. Using the first proto definition, you will have to pass an object with the structure of the `Request` type to that method invocation.

In addition, since that is a client, not a server, the correct type for what you have there is `ClientReadableStream`.

**Comment by shanshanzhu** [comment]
@murgatroid99 I think you mean this
```const client = new ProtoService('0.0.0.0:50051', grpc.credentials.createInsecure())
const call = client.exampleRpc({});
call.on('data', (response) => {});
call.on('end', (response) => {});```

And when I try to do 
```
call.cancel()
```
I get this server error message.
```
Error: Cancelled
    at ClientReadableStream._emitStatusIfDone (/node_modules/grpc/src/client.js:255:19)
    at ClientReadableStream._readsDone (/node_modules/grpc/src/client.js:221:8)
    at readCallback (/node_modules/grpc/src/client.js:283:12)
```
Then the server is down. I try to have a try catch there but it is not working
```
try {
    call.cancel()
} catch(e) {
}
```

**Comment by murgatroid99** [comment]
That error you get is the expected behavior. You should be handling the `error` event anyway, and if you're expecting to cancel calls, you shouldn't have to take any action if `error.code` is `grpc.status.CANCELLED`.

**Comment by shanshanzhu** [comment]
Yes we ended up calling this in the client
```
  call.on('error', (error) => {
     if (error.code === grpc.status.CANCELLED) { return; }
  })
  call.on('end', () => {
     // the logic after calls actually end
  }
  call.cancel();
```

and in server we are doing 
```
   call.on('cancelled', () => { call.end() })
```

This feels like additional round trip though. I don't quite get why it is designed this way rather than a simple 'end'. But it works.
@murgatroid99 Many thanks to your help.

**Comment by murgatroid99** [comment]
I think perhaps you are approaching this the wrong way. You seem to be using `cancel` to signal to the server that the client would like to stop reading, but `cancel` should be used when the client needs to unexpectedly terminate the call.

If you want to stop a server stream based on client logic, you should either specify in the initial request message where the stream should end, or use a bidirectional stream, and send another message when you want the server to stop sending.

**Comment by shanshanzhu** [comment]
In our logic, we are not able to know when the stream should end when the initial request message is sent. Also we are concerned with using a bidirectional stream just for the purpose of ending the server stream.

**Comment by murgatroid99** [comment]
It sounds like the semantics of that method implies that the client should send two messages: one to begin the stream from the server, and one to end it. With those semantics, I would strongly recommend using a bidirectional stream.

**Comment by maximilliangeorge** [comment]
I just wanted to chime in to say that this finally solved my headache (an edge case):

`call.on('error', () => {
    console.log('on error test')
  })`
` call.cancel()`

I had a class that established a connection to a server. When developing i use unit tests with a watch flag. The problem was, each time i ran the tests ran all event listeners were added on top of previous event listeners. I tried to resolve this by nullifying the class instance etc, but in the end cancelling the connection between test runs was the only way to go about it. Just leaving this here in case someone runs in to a similar issue.

**Comment by shanshanzhu** [comment]
@maximilliangeorge 
Be careful with this approach. In the callback of 'error', there is no way to tell these two condition apart:
1. grpc server sends a grpc status code 'Canceled' and 'Canceled' message
2. grpc client cancel the workflow.

@murgatroid99 I was exploring if we can pass any arguments to cancel call so that onError callback we can tell these two conditions apart. But there are no way to pass any error message to cancel call. Is it possible that we expose an argument to allow passing in error message on Cancel?

Here is the code of cancel in grpc node:
https://github.com/grpc/grpc-node/blob/master/packages/grpc-native-core/src/client.js#L308-L311
