### ISSUE TITLE
multiple thread can block in poll？

### ISSUE THREAD

**Issue by tashanzhishi** [grpc/grpc#8091]
in ev_poll_posix.c:pollset_work function, multiple thread can block in poll？
why design so that？why not make a thread to do poll。

**Comment by ctiller** [comment]
The work after poll (reading a message, getting control back to the
application) can quickly become dominated by context switches if there are
too many threads involved in processing in the response path (especially if
your network is fast), so we try to design so that there's a minimum number
of thread jumps involved in any path.

**Comment by tashanzhishi** [comment]
thinks to response, and you solve my doubt.
