### ISSUE TITLE
(stream rpc) When server send 'error', client receives the 'error' event after the 'end' event

### ISSUE THREAD

**Issue by assaf-xm** [grpc/grpc#8134]
When using grpc 1.0.0 for node (both client and server), using server streaming like:
rpc LotsOfReplies(HelloRequest) returns (stream HelloResponse){}

When the server returns an error [I used client_stream.emit('error', ...) on the server side to raise the error], the client receives the 'error' event after the 'end' event.
This is problematic since the 'end' callback is used to clean-up stream related data and return a final response to the user. When the error event arrives, it's too late, request is already over and client received a successful response.

Sample client side code (standard streaming):
var rpcResponseStream = grpcClient.lotsOfReplies(requestMsg);
rpcResponseStream.on('error', (err) => self.responseError(err));
rpcResponseStream.on('data', (msg) => self.responseData(msg));
rpcResponseStream.on('end', () => { self.responseEnd() });

Also, I noticed it's not consistent, it happens most of the time, however when there is a pending message from the server to the client, the 'error' event is received before the 'end' event.

Thanks,
Assaf

**Comment by murgatroid99** [comment]
The "end" event just indicates that there are no more incoming messages. It contains no information about whether the call was successful.

If you want the client to receive a single final success or failure response, I would recommend using the "status" event, which contains that information. If you really need the Error object when a stream fails, you can return a success response when you get an OK status event, and a failure response when you get an "error" event. Those two possibilities are mutually exclusive.

Either way, you should do something to handle the "error" event, because the default stream error handler throws the error.

**Comment by assaf-xm** [comment]
Thanks!
Using the 'status' event works great directing the flow to the error handler or success (my old 'end') handler.
So currently the 'error' and 'end' events are empty handlers, and only the 'data' and 'status' events are actually handled.

**Comment by murgatroid99** [comment]
To be clear, you only really need handlers for "error" and "data". You can simply omit the "end" handler entirely.
