### ISSUE TITLE
Node how to use plain javascript objects

### ISSUE THREAD

**Issue by aguerere** [grpc/grpc#8432]
Hello,

I am trying to use grpc to build a Node server and client that will send and receive javascript objects that do not have a known structure.

Can you guys point me in the right direction? I can't seem to find the way to describe a .proto file that has a message with a field for any kind of javascript object.

Thank you!

**Comment by murgatroid99** [comment]
The whole point of protocol buffers is to describe data with a known structure, so you're not going to get what you're looking for from protocol buffers. Fortunately, gRPC is not restricted to protocol buffers. You can use any serialization and deserialization you want.

For this purpose, I would suggest plain old JSON. You can define such a service like this:

```js
function serializeJson(obj) {
  return new Buffer(JSON.stringify(obj));
}
function deserializeJson(buffer) {
  return JSON.parse(buffer.toString());
}
var service = {
  methodName: {
    path: method_path,
    requestStream: false,
    responseStream: false,
    requestSerialize: serializeJson,
    requestDeserialize: deserializeJson,
    responseSerialize: serializeJson,
    responseDeserialize: deserializeJson
  }
};
```

This defines a service with the method `methodName` that can be accessed at `method_path` (this is like the HTTP path, e.g. `"/ServiceName/MethodName"`). The method allows for one message to be sent by the client and one response to be sent by the server, instead of a stream of messages (this is what `requestStream` and `responseStream` mean). And at each end, the message provided by the application is assumed to be JSON-serializable, and is stringified, and the message received from the network is assumed to be serialized JSON, and is parsed as JSON.

You can add this service to a server by calling `server.addService(service, implementation)`, and you can create a client class from it by calling `grpc.makeGenericClientConstructor(service)`.

**Comment by aguerere** [comment]
@murgatroid99 thank you for your thorough reply. I understand what you mean.
But what about [google.protobuf.Struct](https://github.com/google/protobuf/blob/master/src/google/protobuf/struct.proto)?
It looks like that would be a way to have a .proto file like this:

```
syntax = "proto3";

import "struct.proto";

service Engine {
  rpc Execute (ExecuteRequest) returns (ExecuteResponse) {}
}

message ExecuteRequest {
  google.protobuf.Struct context = 1;
}

message ExecuteResponse {
  google.protobuf.Struct context = 1;
}
```
This actually compiles with the grpc dynamic loader. BUT it fails when doing the actual rpc call.

**Comment by murgatroid99** [comment]
The problem there is that the serialization function uses the exact proto types, not their intended JSON representation. So, if you want to represent this JSON object

```js
{
  number: 1,
  word: "test"
}
```

You would need to pass the following value for your `ExecuteRequest`:

```js
{
  context: {
    fields: {
      number: { number_value: 1 },
      word: { string_value: "test" },
    }
  }
}
```

And that object is what the deserializer would give you on the other end. It should be relatively straightforward to convert the simple JSON format to and from that format.

**Comment by aguerere** [comment]
@murgatroid99 thank you! At last I understand how to make that work.
What do you think about just using a string type and storing there the JSON.stringify() of the object, then retrieving it back with JSON.parse() ?
What would you think the best solution, out of all three choices so far?

**Comment by murgatroid99** [comment]
If you need to use protobuf for some reason, I think the google.protobuf.Struct option is the best. If you don't need protobuf, the direct JSON serialization seems like the simplest solution.

I don't think your "JSON string in a proto message" is a good solution, because it has the inconvenience of double serialization without the benefit of protobuf's type safety.

**Comment by aguynamedben** [comment]
Thanks for having this discussion. I'm in the exact same boat and this was helpful.

FWIW I'm using [grpc-promise](https://github.com/carlessistare/grpc-promise) to make RPC calls between Electron processes using ES6 async/await syntax. I don't care as much about being strict on data types, but gRPC + grpc-promise provides a really good API! In my renderer I can do

```jsx
const response = await backendClient.API().execute({ action: 'migrate' });
```

👍 Thanks for the time you put into working on gRPC.
