### ISSUE TITLE
Failed to build project

### ISSUE THREAD

**Issue by yadavparmatma** [grpc/grpc#8536]
Hi Menghanl,

I am facing issue when building my go project with generated proto file. It say's
undefined: proto.ProtoPackageIsVersion2
undefined: proto.RegisterFile

I also updated my protobuf package as you mentioned above but still did not get resolve.
I am using go version - 1.7
protobuf version - 3.1.1

Thanks
Parmatma

**Comment by menghanl** [comment]
Have you checked what I suggested https://github.com/grpc/grpc/issues/6898#issuecomment-256714587?

**Comment by yadavparmatma** [comment]
Yes Meghnal,
 still same issue...

**Comment by menghanl** [comment]
So you mean you found that the variable is defined in you local proto package, but gRPC cannot see the variable?
I'm not sure what the real problem is... Maybe something is wrong with you local go environment?
Please check you settings (gopath and so on) to make sure gRPC finds the correct proto package.
