### ISSUE TITLE
grpc server sometimes silently fails and drops requests

### ISSUE THREAD

**Issue by imiuka** [grpc/grpc#8567]
I've come across some weird behaviour where multiple clients attempted to connect a gRPC server and issued calls, but on some of those connections, the connect appeared to succeed but calls never resolved. It appeared as though the connection had died even though it reported itself as `status == ready`.

I've found a [reliable repro](https://github.com/imiuka/grpc.bugs/tree/racey-concurrents-1), but don't have the time to do a deep dive into gRPC internals right now. I'd really appreciate your help here.

I've taken the `csharp` greeter sample and modified it slightly. Since I'm using the C# binding, II'm not sure if the problem lies in gRPC core library or the C# binding. Anyway, in the problem, we have:
- a client `a` that issues requests against a server `b` (in the demo, this is `GreeterClient`)
- a server `b` that depends on another server `c` (in the demo, this is `GreeterServer`)
- a server `c` (in the demo, this is `GreeterServer2`)

What happens is that the client opens 10 channels to the server `b`. If during `b`'s startup, it attempted to make a call to `c`, then some of the client's channels will be unresponsive and calls will never complete. If we comment out the call in `b`'s startup, then all operates as expected and calls will complete.

It's important to note that it is only the actual call that matters, we can open a channel from `b` to `c` and everything will be OK. [It's only when we make the call itself that things start failing](https://github.com/imiuka/grpc.bugs/blob/racey-concurrents-1/GreeterServer/Program.cs#L29). It seems that it also doesn't matter where the call is made in `b`, whether it's before the server is started or afterwards.

I've tested against [1.0.0](https://www.nuget.org/packages/Grpc/1.0.0) and [1.0.1-pre1](https://www.nuget.org/packages/Grpc/1.0.1-pre1) releases on NuGet, plus master.

In the demo, I spin up 10 channels to issue one call each. Looking at the trace logs, it appears the server (`b`) does actually receive all 10 requests, but only 8 of the 10 requests are ever dispatched to the C# service implementation. The exact number varies every time the server and client are restarted, but almost always at least one, two or three fail.

```
I1030 13:09:43.398660 0 c:\jenkins\workspace\gRPC_build_artifacts\architecture\x64\language\csharp\platform\windows\vsprojects\..\src\core\ext\transport\chttp2\transport\parsing.c:659: HTTP:1:HDR:SVR: :path: /helloworld.Greeter/SayHello
I1030 13:09:43.418174 0 c:\jenkins\workspace\gRPC_build_artifacts\architecture\x64\language\csharp\platform\windows\vsprojects\..\src\core\ext\transport\chttp2\transport\parsing.c:659: HTTP:1:HDR:SVR: :path: /helloworld.Greeter/SayHello
I1030 13:09:43.432184 0 c:\jenkins\workspace\gRPC_build_artifacts\architecture\x64\language\csharp\platform\windows\vsprojects\..\src\core\ext\transport\chttp2\transport\parsing.c:659: HTTP:1:HDR:SVR: :path: /helloworld.Greeter/SayHello
I1030 13:09:43.451698 0 c:\jenkins\workspace\gRPC_build_artifacts\architecture\x64\language\csharp\platform\windows\vsprojects\..\src\core\ext\transport\chttp2\transport\parsing.c:659: HTTP:1:HDR:SVR: :path: /helloworld.Greeter/SayHello
I1030 13:09:43.469711 0 c:\jenkins\workspace\gRPC_build_artifacts\architecture\x64\language\csharp\platform\windows\vsprojects\..\src\core\ext\transport\chttp2\transport\parsing.c:659: HTTP:1:HDR:SVR: :path: /helloworld.Greeter/SayHello
I1030 13:09:43.580289 0 c:\jenkins\workspace\gRPC_build_artifacts\architecture\x64\language\csharp\platform\windows\vsprojects\..\src\core\ext\transport\chttp2\transport\parsing.c:659: HTTP:1:HDR:SVR: :path: /helloworld.Greeter/SayHello
I1030 13:09:43.588295 0 c:\jenkins\workspace\gRPC_build_artifacts\architecture\x64\language\csharp\platform\windows\vsprojects\..\src\core\ext\transport\chttp2\transport\parsing.c:659: HTTP:1:HDR:SVR: :path: /helloworld.Greeter/SayHello
I1030 13:09:43.594299 0 c:\jenkins\workspace\gRPC_build_artifacts\architecture\x64\language\csharp\platform\windows\vsprojects\..\src\core\ext\transport\chttp2\transport\parsing.c:659: HTTP:1:HDR:SVR: :path: /helloworld.Greeter/SayHello
I1030 13:09:43.605308 0 c:\jenkins\workspace\gRPC_build_artifacts\architecture\x64\language\csharp\platform\windows\vsprojects\..\src\core\ext\transport\chttp2\transport\parsing.c:659: HTTP:1:HDR:SVR: :path: /helloworld.Greeter/SayHello
I1030 13:09:43.628824 0 c:\jenkins\workspace\gRPC_build_artifacts\architecture\x64\language\csharp\platform\windows\vsprojects\..\src\core\ext\transport\chttp2\transport\parsing.c:659: HTTP:1:HDR:SVR: :path: /helloworld.Greeter/SayHello
```

```
::got-request 1.0
::got-request 4.0
::got-request 0.0
::got-request 3.0
::got-request 2.0
::got-request 6.0
::got-request 8.0
::got-request 9.0
```

Finally, I've made the client log how many calls have succeeded in its window title, one entry for each thread:

![image](https://cloud.githubusercontent.com/assets/975570/19834163/48904e2c-9ea8-11e6-9b4f-63ca9c23848a.png)

Thanks so much for taking a look.

**Comment by imiuka** [comment]
Interestingly, calling `GrpcEnvironment.SetCompletionQueueCount(1)` seems to work around this problem and allow all calls to complete.

**Comment by apolcyn** [comment]
@imiuka based on the repro, this appears to be due to a mixture of sync and async code in the "main" methods of the clients and servers, but mainly the `Console.Readline()` in `GreeterServer/Program.cs`.

It works as expected if this line is changed to:
```
await Task.Run(() => Console.Readline());
```

Going into why this is happening here, the async client request awaitable completes and gets filled in by one of the threads in the GRPC thread pool. As mentioned in https://github.com/grpc/grpc/issues/8580, this thread is polling for work on a "completion queue" "event source". When the async client request completes, you're running on that GRPC thread. When the server starts up, it's ready to receive requests and run handlers on this same thread pool. But the `Console.Readline()` ends up blocking on that GRPC thread that the client request was completed on, and so requests that wind up arriving on the "completion queue" which that thread was polling on never get seen. Similarly to https://github.com/grpc/grpc/issues/8580, setting the completion queue count to 1 causes other threads to share that same event source, and so the events do get seen.

btw, (though this isn't a part of any API guarantee), this can be seen by looking at the current thread name. For example, running:
```
Console.WriteLine($"running on thread: {Thread.CurrentThread.Name}");
Console.Readline()
```
shows that it's running on GPRC thread 0, polling on "completion queue" 0. 

Looking at the thread names in the `SayHello` handler of that same process shows that all of the requests that do get received are running on different threads, on different "completion queues".
But requests that land on "completion queue 0" won't get seen.

**Comment by imiuka** [comment]
Oh my god, you are totally right and I am an idiot. I'd totally missed that the remaining code post-await would be scheduled on one of the grpc threads. Thank you, there's no bug here.

**Comment by apolcyn** [comment]
closing this, but thanks for posting what looked suspicious anyways!
