### ISSUE TITLE
Can I use grpcio-tools as protobuf compiler in the projects that dose not need grpcio 

### ISSUE THREAD

**Issue by cutewalker** [grpc/grpc#8575]
Well, I have done this,  it seems ok.  But the output pb2.py files  include ``import grpc``,  so I have to install grpcio to run the application. 

So, I have some doubt about whether I could do this,  and whether the dependence of grpc is necessary.

**Comment by nathanielmanistaatgoogle** [comment]
This is currently _possible_, @soltanmm-google will comment on the extent to which we _support_ it (and exactly what would be the supported way of going about it). `import grpc` appears in your generated output because you've passed `--grpc_out` in your invocation of `grpcio-tools` (if this claim is unclear or incorrect, respond with exactly how you are using `grpcio-tools` and what you are passing it). If you stop passing the `--grpc_out` variable/flag, I _think_ it will be the case that your generated files will not include `import grpc`.

**Comment by soltanmm-google** [comment]
As said, this is possible, it's just something I really didn't want to happen because this should be on the protobuf team to provide, not gRPC.

That aside... Yes, you can use it as a vanilla `protoc` if you don't pass `--grpc_python_out` (and instead just pass `--python_out`).

**Comment by soltanmm-google** [comment]
And by vanilla `protoc`, I mean a `protoc` that *only* supports Python. The compiled `protoc` extension has all of the other language plug-ins (intentionally) excluded from the runtime.

**Comment by nathanielmanistaatgoogle** [comment]
Closing with the resolution that although this is something that happens to work today, we don't support it, don't want to support it, and won't support it in the future. We _think_ that the maintainers of `protoc` will eventually formally support this use case in a `tools`-like package of their own.

**Comment by cutewalker** [comment]
@nathanielmanistaatgoogle @soltanmm-google  
yeah,  you are exactly right,  after I remove the ``--grpc_python_out`` option to ``grpcio-tools``,  ``import grpc`` disappeared in the generated output.  Thanks very much.

**Comment by cutewalker** [comment]
And I agree with you,  it's up to the protobuf team to provide such a tool.  I prefer  ``grpcio-tools``  to ``protoc`` just because it is much more accessible by using ``pip``.
