### ISSUE TITLE
c# server does not serve concurrent requests while streaming to a client

### ISSUE THREAD

**Issue by jumar** [grpc/grpc#8580]
I have a setup where a client calls a method on a C# grpc server and the server answers with a stream that last a dozen of seconds (made of a few small successive "replies" every second). If another client (or the same) does another call to the server during this streaming, the server will ignore it until the streaming method completes.
It can be easily reproduced in the route_guide example by adding a Thread.Sleep(10000) in the ListFeatures() method of the RouteGuideImpl class (to simulate some background processing that the server may have to perform before sending a part of its reply). If you then start two instances of RouteGuideClient, you will see that the second client will not get any response from the server until the server finishes to stream ListFeatures() to the first client.

By setting GrpcEnvironment.SetCompletionQueueCount(1), I was able to solves the problem... but this seems totally counter intuitive to me, as, per my understanding, reducing the completion queue count should impair the concurrency performance of the server... whereas in my situation it seems to solve a multi-threading / co-routine deadlock.

**Comment by apolcyn** [comment]
Based on the repro, I think what's happening is a mixture of sync and async code that's causing this.

In general, deadlock could happen easily if doing sync/blocking work in server handler methods.

For details on the internals around this, GRPC C# servers have a thread pool, as described in https://github.com/grpc/grpc/issues/6948. If you block or do a long running task in a server handler method, then that server thread wont be able to make progress on events that are ready to run their continuations for. For example, when repro-ing this with`Thread.Sleep(10000)` and two concurrent client requests, both requests end up showing up in the "event source" of the same worker thread, but the first one occupies it with the sleep and so that thread can't make progress on the second one. E.g., if the sleep is changed to `await Task.Delay(10000)`, then the problem goes away since the GRPC server thread is able to continue polling for work, and the rest the continuation of the handler method is able to run on a .NET runtime task scheduler thread. As for the completion queue setting, "events" that GRPC server threads poll for are tied to "completion queues" as their "source". Setting the completion queue count lower doesn't actually lower the server thread pool size, but instead just makes them all share this same event source, so when the one thread is blocked on `Sleep`, other server thread pool threads are able to pick up the other call (it just happens that the other call ends up on the same completion queue "source" as the first).

But to avoid all of it, it's should be best to run async rather than blocking tasks, and to possibly offload long-running CPU work if its necessary.

cc @jtattermusch if there's more on this

**Comment by apolcyn** [comment]
To add a bit more to this, it is not only the servers that complete their async tasks with a dedicated GRPC thread pool, but also client GRPC calls as well. So basically the same problems with long-running CPU work and blocking calls in server handlers also exist after making a client call. The client call is also completed on one of the GRPC threads, and so when returning from an async client call, blocking or doing long-running CPU work would prevent progress from things that the thread is able to do. 

But for this too, the best thing to do is probably to avoid mixing sync and async calls as it can be prone to deadlock.

**Comment by apolcyn** [comment]
closing as there doesn't look to be a bug

**Comment by jumar** [comment]
Then how can I tell the c# code generator to generate a non async API method in the server ?

**Comment by jtattermusch** [comment]
You cannot. Only async methods are supported on the server side. When implementing them, you either need to implement the async code according to the .NET best practices (e.g. don't block on the threads and use async primitives instead - e.g. use Task.Delay instead of Thread.Sleep), or you can offload the sync operations to a different thread (e.g. using Task.Run and awaiting the result).
