### ISSUE TITLE
How Completion Queue Shutdown works ?

### ISSUE THREAD

**Issue by rllola** [grpc/grpc#8610]
Hello,

I have a done a fully async server and I was wondering how the completion queue shutdown process work ? 
After calling `cq_->Shutdown` do I need to delete the `CallData` instance that have been created but not deleted yet ? If no why and how does it works ?

Thank you

**Comment by dgquintas** [comment]
Summoning @sreecha to the party.

**Comment by sreecha** [comment]
Hi @rllola,
By `CallData`, I am assuming you are referring to the class used in [`greeter_async_server.cc` ](https://github.com/grpc/grpc/blob/master/examples/cpp/helloworld/greeter_async_server.cc#L85).
I wanted to clarify that it is not a standard class exposed by the grpc framework - it is rather an application defined class - and as such any dependency between `cq` and `CallData` are application specific.

Here is completion queue shutdown works:
- Once you call `cq->shutdown` on a completion queue, you can no longer queue any more events on that queue. You will get an assertion failure if you do so.
- You must keep calling `cq->Next()` or `cq->AsyncNext()` on that queue to drain all the pending events. Once all the events are drained, `cq->Next()` will start returning  `false` (or `cq->AsyncNext()` will return `NextStatus::SHUTDOWN`). 
- This is when it is safe to delete/destroy your completion queue object

**Comment by rllola** [comment]
Ok, thank you this more clear now. 

An other question that I have is how the events are deleted in the completion queue. In the example, we just delete it but how is it remove from `cq` ?

**Comment by bedeho** [comment]
I am also wondering about this.

In the ' greeter_async_server.cc' example, assume you have a tag which has been registered, but either

- there has never been a request made
- a request has been made but ServerAsyncResponseWriter<T>::Finish has not yet been called

In this case, there is a dangling CallData object. How does it get properly deleted when when ~ServerImpl() is called?

**Comment by sreecha** [comment]
>how the events are deleted in the completion queue. In the example, we just delete it but how is it remove from cq ?

@rllola, you do not explicitly delete the "events" in the completion queue. You just drain/dequeue all the events by calling `cq->Next()` or `cq->AsyncNext()` as I mentioned earlier.  This is how you get back the `tag` objects you have passed into the completion queue earlier (for example the `CallData` objects in the `greeter_async_server.cc` example) and this is when you can free/delete the `tag` objects - since you are sure that the completion queue no longer has a reference to them.

As a side note:  Notice that both `cq->Next()` or `cq->AsyncNext()`  have an argument called `ok` in them (I am pasting their signatures below for reference). So when you are draining events by calling `cq->Next()` or `cq->AsyncNext()` it is possible that `ok` may be `false` but you will still get the `tag` object back:
- [`NextStatus AsyncNext(void** tag, bool* ok, const T& deadline)`](https://github.com/grpc/grpc/blob/master/include/grpc%2B%2B/impl/codegen/completion_queue.h#L135)
- [`bool Next(void** tag, bool* ok)`](https://github.com/grpc/grpc/blob/master/include/grpc%2B%2B/impl/codegen/completion_queue.h#L147)

So tying this all together:
Lets say you need to release memory of all the tag objects (for example the `CallData` object that @bedeho was mentioning) because you are tearing down the server.  

In this case you would have called `server_->shutdown()` and `cq->shutdown()` on all the completion queues.  Once you do this, you will have to drain all the events in the completion queues by calling `cq->next()` or  `cq->AsyncNext()` and you will get back all the events in the completion queue with either `ok==true` (for any of those events successfully completed) and `ok==false` for those that could not be completed but still returned because your server is shutting down.

Once you get the `tag` back, it is safe to release the memory for that (since you are the one owning it)

Hope this helps.

**Comment by bedeho** [comment]
Thanks you for that response, but I would really appreciate a more direct response to my question also if possible.

In particular, after some more testing it seems like the server will put the tags of all registered unfinished rpc calls into the completion queue when a server shutdown is initiated, and that this is why no CallData objects leak during shutdown. Can you confirm this?

**Comment by sreecha** [comment]
@bedeho,
>it seems like the server will put the tags of all registered unfinished rpc calls into the completion queue when a server shutdown is initiated

Yes. This is correct.

>and that this is why no CallData objects leak during shutdown
You still need to call `cq->Next` or `cq->AsyncNext` to get those `tags` (i.e the `CallData` objects) out. This is what I meant by 'draining'the completion queue. After this, you are free to destroy the `CallData` objects. I am assuming this is what you implied

**Comment by bedeho** [comment]
Thanks!

**Comment by yyh-graphsql** [comment]
@sreecha  have a quick question.
Is there any race condition between Shutdown and Next or AsyncNext?

**Comment by sreecha** [comment]
@yyh-graphsql - There is no race between the two - you can call them in parallel.
However, make sure that you drain the queue after calling shutdown (i.e continue calling Next or AsyncNext until they actually return that the queue has been shutdown)
