### ISSUE TITLE
Extremely vague and confusing setup for Windows/Visual Studio C++ users.

### ISSUE THREAD

**Issue by jmazzola** [grpc/grpc#8710]
I understand the pain of writing documentation however manually building and setting up GRPC for Windows machines and using Visual Studio is an absolute nightmare and has caused several people including me days of frustration.

However, I stumbled upon a savant by the name of plasticbox that has an already made set of scripts to automate the process for you. After fixing paths and settings in Visual Studio, you can get a hello-world application up and running in a half-hour.

https://github.com/plasticbox/grpc-windows

Perhaps you can add this in your 'easy installation' section? 📦

**Comment by apolcyn** [comment]
@y-zeng sorry I'm unfamiliar with the c++ build myself, cc @yang-g?

**Comment by jtattermusch** [comment]
Since the time this issue was created, we actually deprecated the pre-generated VS projects and cmake is now the official way to build on Windows (so the instructions from https://github.com/plasticbox/grpc-windows are now obsolete).

The new instructions to build with cmake are available here
https://github.com/grpc/grpc/blob/master/INSTALL.md#building-using-cmake-recommended

There is still a few known issues with the cmake build (and we are working on fixing them), but things should be simpler now than with the old pre-generated vsprojects.
