### ISSUE TITLE
C++ sync server API: naming for flow-controlled operations

### ISSUE THREAD

**Issue by vjpai** [grpc/grpc#8750]
Cc @shaladdle @ctiller 

Pull requests #7018 and #8365 allow unary and server-only-streaming RPCs, respectively, to be processed at the server-side as though they were bidi-streaming, allowing the separation of RPC initiation from  request processing. These are still considered experimental and not externally-documented, so we should finalize name choices for them before they are officially launched.

1. Methods being handled this way currently have the word "Streamed" prepended to their name rather than just using overloading (since the C++ style guide discourages naked overloading anyway). Should it be done with overloading instead?
2. The real thing going on is that unary or server-only-streaming RPCs are being interpeted as bidi-streaming; the RPC analogy of reinterpet_cast. Would it be helpful to use the word reinterpret in the description?
3. Even if we avoid overloading, the choice of Streamed really represents the fact that it is stream-ified. Would Streamified be better?

Any other issues?

**Comment by shaladdle** [comment]
Thanks for making this issue, Vijay.

I think there's an argument for overloading. The first part of the overloading section in the style guide:

> Use overloaded functions (including constructors) only if a reader looking at a call site can get a good idea of what is happening without having to first figure out exactly which overload is being called.

You could argue that there are no callers here, since these methods are just called by gRPC internals when a message arrives (AFAIK). This makes the issue of confusion at the call site moot. Additionally, most people won't even know about these overloads, you kind of have to go looking for them.

> The real thing going on is that unary or server-only-streaming RPCs are being interpeted as bidi-streaming; the RPC analogy of reinterpet_cast. Would it be helpful to use the word reinterpret in the description?

I'm not a fan of this personally. Does this terminology appear in other languages? Is there any plan for this API in other languages? Even if there isn't, it seems desirable to use language agnostic terms when possible.

> Even if we avoid overloading, the choice of Streamed really represents the fact that it is stream-ified. Would Streamified be better?

Streamified is better than Streamed imo, but I kind of lean towards overloads myself. Another thing to consider is putting the Streamified or whatever at the end, eg 

```c++
grc::Status Foo(grpc::Context*,const FooRequest&,FooReply*)
```

becomes

```c++
grpc::Status Foo_Streamified(grpc::Context*, grpc::ServerUnaryStreamer<FooRequest, FooReply>*)
```

**Comment by vjpai** [comment]
I think the cows left the barn on this one a long time ago. Not sure if these APIs are used widely but it's too late to do anything about these names now (except possibly add new preferred synonyms).
