### ISSUE TITLE
Grpc.Tools codegen not preserving case in c# namespace declaration

### ISSUE THREAD

**Issue by W1zb1t** [grpc/grpc#8781]
Where I define the package in the proto file thus:
`package aBCd.aBCd.aBCd;`

After running the GrpcTools to gen out the code I get the namespace defined as this:
`namespace ABCd.ABCd.ABCd {...`

I would note that the service name is preserved:
`    static readonly string __ServiceName = "aBCd.aBCd.aBCd.MyApi";`

though this is a good general practice, it conflicts with corporate naming conventions... really it should just translate what we have not seek to improve upon it.

**Comment by apolcyn** [comment]
@W1zb1t though I don't think this fixes the main issue yet, I'd note you can control the output namespace by using `option csharp_namespace` in the `.proto` file.

E.g., using `option csharp_namespace = option csharp_namespace = "aBCD.aBCD.aBCD";` should have the final c# namespace be `aBCD.aBCD.aBCD`

**Comment by apolcyn** [comment]
Looking more into it, I think using a custom `option csharp_namespace` should be all that's needed. 

The current behavior for the grpc protoc plugin converts "package names" to "c# namespace" as "snake case" to "camel case". I think that the customer namespace option is the right thing to do for a non-snake-case package name - changing this behavior would be breaking.

AFAIK the __ServiceName is always be the full package name of the proto followed by the service name that's given in the proto file - it can't change since other language code gen does this too but it should be fine that it differs from c# namespace.

**Comment by jtattermusch** [comment]
I agree with @apolcyn.

**Comment by W1zb1t** [comment]
Sorry for the radio silence. Yes this seems perfectly reasonable. I will add the option use.
