### ISSUE TITLE
npm rebuild doesn't work out of the box

### ISSUE THREAD

**Issue by KidkArolis** [grpc/grpc#8887]
What's the reasoning on:

```
[grpc] Success: "/app/node_modules/grpc/src/node/extension_binary/grpc_node.node" already installed
Pass --update-binary to reinstall or --build-from-source to recompile
```

That's not how any other native npm module behaves, making this not work in typical scenarios where `npm rebuild` is useful, e.g. in Docker deployments.

I can workaround by passing `npm rebuild --update-binary`, but now _everyone_ needs to know about this.

**Comment by murgatroid99** [comment]
Basically, gRPC does that because that's how `node-pre-gyp` works. Unfortunately, I can't find a way to hook into `rebuild` without having the same hook for `install`. One solution would be to just always update the binary, but i have to think that the `node-pre-gyp` documentation doesn't suggest that for a reason.
