### ISSUE TITLE
Enable core build against musl

### ISSUE THREAD

**Issue by soltanmm-google** [grpc/grpc#8899]
cf. Alpine Linux

Just coalescing the issues.

#8658
#6850

**Comment by eljefedelrodeodeljefe** [comment]
is there an intention to move forward on this?

**Comment by explicitcall** [comment]
any updates on this issue?

**Comment by ernie** [comment]
I've also been struggling to find a suitable solution for this -- grpc is a dependency of the google-cloud-pubsub Ruby gem, and so I'd very much like to be able to build this under Alpine -- we're building from source for all gems because of issues with the prebuilt version of google-protobuf on Alpine, and to hopefully increase the likelihood that we see potential issues at build time vs runtime.

I'd prefer to avoid adding additional third-party packages via wget (as with alpine-pkg-glibc) if at all possible.

**Comment by andreacalia** [comment]
Hi, even if this feature is under review, I'd like to report that it doesn't work on Alpine:3.5 (docker)

```
docker run -it alpine:latest sh
/ # apk update
/ # apk add python3-dev build-base
/ # python3 -m pip install grpcio-tools

Command "/usr/bin/python3 -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-mf96m1gz/grpcio-tools/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-tij0ogir-record/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /tmp/pip-build-mf96m1gz/grpcio-tools/
```

**Comment by hsaliak** [comment]
@kpayson64 could you please investigate..

@andreacalia could you please provide the output of ` pip list  | grep grpc `

**Comment by kpayson64** [comment]
@hsaliak @andreacalia 
grpcio-tools 1.3.0 will not run on Alpine linux because it depends on protobuf 3.2.x, and protobuf did not support alpine linux until 3.3.0 (which was not available in time for the 1.3.0 release).

In our 1.4.0 release, we will upgrade our protobuf dependency, #10995.  The grpcio package should build under alpine linux.

**Comment by hsaliak** [comment]
@kpayson64 got it, thanks! Since this issue tracks core build against musl, the issue can be closed.
@andreacalia wdyt?

**Comment by andreacalia** [comment]
@hsaliak @kpayson64 thanks!
Indeed python lib grpcio is correctly built in alpine. So we'll wait for the 1.4.0 release :)
