### ISSUE TITLE
Server side connection layer

### ISSUE THREAD

**Issue by abaldeva** [grpc/grpc#8932]
Hi,

My apologies if this is not the right channel. I tried posting my questions on the gRPC Google Group but have not received any answers. I was wondering if someone can provide me with some answers.

1. **Detecting a dead client on server**: Is there a way or recommended mechanism to detect a client who is no longer connected to the server after an abrupt client shutdown? In our current framework, we get a TCP level disconnect which then ends the user session. But looking around the gRPC code base and searching past discussions in the group, the connection layer is hidden away and this information is not exposed. Detecting a dead client early is important in scenarios where client's state may be important to other clients. We have many use cases for it. For example, if two players are connected in a game session and one of them goes away, we'd like to update the status of that person on other client's machine. 

I was wondering if I have a bi-directional streaming RPC for the sole purpose of detecting a disconnect, would I get any error on that stream in case of an abrupt client shutdown? It did not seem like that from the async interface though (async_stream.h).

2. **Server side connection management**: Is there a doc that details the server side connection management? I am trying to figure out details like how long does a socket remain active for an inactive client? Is this a setting that can be customized? Are there any sort of connection metrics that are exposed to the application?

Appreciate your time.

Thanks
Arpit

**Comment by abaldeva** [comment]
Hi,

As for problem 1, My further experiments show that in case a bi-directional stream is broken abruptly, the 'ok' bool on the AsyncNext call returns false. 

`NextStatus AsyncNext(void** tag, bool* ok, const T& deadline) `

If this is a reliable behavior, I could just make a bi-directional ping stream between client and server and detect the connection as dead if that stream runs into an error? Is that a correct approach?

Thanks.

**Comment by neuecc** [comment]
I am having a similar problem and I am planning to take a heartbeat approach in the same way.
I'm making room based games, and in the waiting lobby etc, I want to leave users who have been disconnected.

**Comment by joseAndresGomezTovar** [comment]
I have the same requirement, because:

- I want to run a DLL remotely

Scenary:

- I have a main process and tow dlls
    one of these dll will be run using the gRPC server
- By making a new dll "gRPC client" that is loaded in the main process, I remotely connect the original "dll" with the main process

The gRPC server loads the "original dll" when the connection is established, and downloads it when it breaks

thank you in advance

**Comment by noamyogev84** [comment]
Hi,
I'm currently in the process of exploring `grpc` for server/client application. being able to detect dead client on the server side is crucial for me in order for clean up and resource deallocation.

Is there any plan to implement this kind of hook/handler in the server? maybe an intercpetor to channel events (keep alive pings) on the server?

Thanks :beer:

**Comment by yashykt** [comment]
gRPC does have keepalives. https://github.com/grpc/proposal/blob/master/A8-client-side-keepalive.md and https://github.com/grpc/proposal/blob/master/A9-server-side-conn-mgt.md will provide some useful information on how to configure this.

**Comment by noamyogev84** [comment]
@yashykt thanks.
I've read carefully what you pasted in the last comment. Would you care to ellaborate:
Where do we hook up to events raised due to whatever we configured in the 'keep_alive' options for the channel?

This is not clear, and apparently does not provide any solution. When we peek at the transmitted data over the wire, we see the 'keep_alive' ping packets. But what if the client is dead and now we want to act based on our configured channel policy? There is no server side event for that.

The only way currently known to handle this scenario in gRPC is an applicative bi-directional stream. SO, why configure keep alive in the first place???

Please explain if you can. :beer:
