### ISSUE TITLE
GRPC malformed HTTP response

### ISSUE THREAD

**Issue by tejasmanohar** [grpc/grpc#8945]
If we're getting errors like
```
Post http://localhost:4000: malformed HTTP response \"\\x00\\x00\\x00\\x04\\x00\\x00\\x00\\x00\\x00\\x00\\x00\\x04\\b\\x00\\x00\\x00\\x00\\x00\\x00\\x0e\\xff\\xf1\"
```
after upgrading GRPC (Golang, latest), any ideas where to start debugging? `grpc.SupportPackageIsVersion4` sounds like we're on v4 of the protocol.

**Comment by mehrdada** [comment]
We are cleaning up the gRPC issue backlog and are unable to address this issue with the current information. If you are still experiencing this issue, please open an issue (on the `grpc-go` issue tracker since this seems to affect Go implementation in particular) with information on how to reproduce.
