### ISSUE TITLE
transport: http2Server.HandleStreams failed to read frame: read tcp [::1]:50051->[::1]:58751: wsarecv: An existing connection was forcibly closed by the remote host.

### ISSUE THREAD

**Issue by zplzpl** [grpc/grpc#8998]
transport: http2Server.HandleStreams failed to read frame: read tcp [::1]:50051->[::1]:58751: wsarecv: An existing connection was forcibly closed by the remote host.

How does it happen?

**Comment by RedVinchenzo** [comment]
Same error.
But only on the first minute, after some times requests on services don't generate this error anymore ??

**Comment by mehrdada** [comment]
We are cleaning up the gRPC issue backlog and are unable to address this issue with the current information. If you are still experiencing this issue, please re-open the issue with information on how to reproduce. (If your issue is specifically related to Go or Java implementations, please file an issue on the respective repositories.)
