### ISSUE TITLE
New Server method add_service_rpc_handler

### ISSUE THREAD

**Issue by kpayson64** [grpc/grpc#9015]
Taken from
#8742 
"""
The issue is in avoiding the situation of an application creating a ServiceRpcHandler, registering it with a server using add_generic_rpc_handlers, and then the server having to do dynamic type inspection and special casing along the lines of "well, which of the handlers just registered are ServiceRpcHandlers and which are merely GenericRpcHandlers?" when the application had that information on its side of the API. It's been really nice that we've been able to avoid dynamic type inspection so far and I'd like to keep it up.

With that pushing in the direction of a Server.add_service_rpc_handlers method the question of the design of the ServiceRpcHandler type is raised. How should it be called to service an RPC? By full-size /my_package.my_subpackage.MyService/MyMethod string? Or just by MyMethod string? Should ServiceRpcHandlers be free to refuse service of an RPC?

I think these questions can be answered in a way that allows ServiceRpcHandler to inherit the service method from GenericRpcHandler. Do you foresee any problems?
"""

**Comment by nathanielmanistaatgoogle** [comment]
Stealing this issue because I think it will be affected by whether or not we want to use `grpc_server_request_registered_call` as part of our performance improvement story.

@yang-g, @ctiller: how likely do you think it will be that using `grpc_server_request_registered_call` rather than `grpc_server_request_call` will be part of the Python performance improvement work? @a11r indicated that he suspect it would be but I'd like to hear it from you and to hear if there would be any reason for it other than "of course RPC method dispatch in C will be faster than RPC method dispatch in Python".
