### ISSUE TITLE
Installing grpc 1.01 on Raspberry Pi

### ISSUE THREAD

**Issue by touchardv** [grpc/grpc#9056]
Trying to install the Ruby version of grpc on a Raspberry Pi... (Raspbian GNU/Linux 7 (wheezy))
No success so far after many attempts:
* GCC 4.6: fatal error: stdalign.h: No such file or directory
* GCC 4.7: bunch of errors in sockaddr_utils.c
eg. :98:17: error: conversion to 'int' from 'unsigned int' may change the sign of the result [-Werror=sign-conversion]

What can I try next?
Or is that a lost cause?

**Comment by ctiller** [comment]
C++?

**Comment by touchardv** [comment]
Meaning...?

Some logs from the last attempt (using GCC 4.7):
```
/home/pi/.rbenv/versions/2.1.7/bin/ruby extconf.rb
Building internal gRPC into /opt/myhome-agent/shared/bundle/ruby/2.1.0/gems/grpc-1.0.1/src/ruby/ext/grpc/libs/opt
make: Entering directory '/opt/myhome-agent/shared/bundle/ruby/2.1.0/gems/grpc-1.0.1'
[C]       Compiling third_party/zlib/adler32.c
...
[C]       Compiling src/core/lib/surface/channel_init.c
src/core/lib/iomgr/sockaddr_utils.c: In function 'grpc_sockaddr_is_wildcard':[C]       Compiling src/core/lib/surface/channel_ping.c

src/core/lib/iomgr/sockaddr_utils.c:98:17: error: conversion to 'int' from 'unsigned int' may change the sign of the result [-Werror=sign-conversion]
src/core/lib/iomgr/sockaddr_utils.c:109:17: error: conversion to 'int' from 'unsigned int' may change the sign of the result [-Werror=sign-conversion]
src/core/lib/iomgr/sockaddr_utils.c: In function 'grpc_sockaddr_make_wildcard4':
src/core/lib/iomgr/sockaddr_utils.c:126:24: error: conversion to 'in_port_t' from 'unsigned int' may alter its value [-Werror=conversion]
src/core/lib/iomgr/sockaddr_utils.c: In function 'grpc_sockaddr_make_wildcard6':
src/core/lib/iomgr/sockaddr_utils.c:133:25: error: conversion to 'in_port_t' from 'unsigned int' may alter its value [-Werror=conversion]
src/core/lib/iomgr/sockaddr_utils.c: In function 'grpc_sockaddr_to_string':
src/core/lib/iomgr/sockaddr_utils.c:152:12: error: conversion to 'int' from 'unsigned int' may change the sign of the result [-Werror=sign-conversion]
src/core/lib/iomgr/sockaddr_utils.c:156:12: error: conversion to 'int' from 'unsigned int' may change the sign of the result [-Werror=sign-conversion]
src/core/lib/iomgr/sockaddr_utils.c: In function 'grpc_sockaddr_get_port':[C]       Compiling src/core/lib/surface/channel_stack_type.c

src/core/lib/iomgr/sockaddr_utils.c:199:14: error: conversion to 'int' from 'unsigned int' may change the sign of the result [-Werror=sign-conversion]
src/core/lib/iomgr/sockaddr_utils.c:201:14: error: conversion to 'int' from 'unsigned int' may change the sign of the result [-Werror=sign-conversion]
src/core/lib/iomgr/sockaddr_utils.c: In function 'grpc_sockaddr_set_port':
src/core/lib/iomgr/sockaddr_utils.c:216:48: error: conversion to 'in_port_t' from 'unsigned int' may alter its value [-Werror=conversion]
src/core/lib/iomgr/sockaddr_utils.c:220:50: error: conversion to 'in_port_t' from 'unsigned int' may alter its value [-Werror=conversion][C]       Compiling src/core/lib/surface/completion_queue.c

[C]       Compiling src/core/lib/surface/event_string.c
cc1: all warnings being treated as errors
Makefile:2073: recipe for target '/opt/myhome-agent/shared/bundle/ruby/2.1.0/gems/grpc-1.0.1/src/ruby/ext/grpc/objs/opt/src/core/lib/iomgr/sockaddr_utils.o' failed
make: *** [/opt/myhome-agent/shared/bundle/ruby/2.1.0/gems/grpc-1.0.1/src/ruby/ext/grpc/objs/opt/src/core/lib/iomgr/sockaddr_utils.o] Error 1
make: *** Waiting for unfinished jobs....
make: Leaving directory '/opt/myhome-agent/shared/bundle/ruby/2.1.0/gems/grpc-1.0.1'
*** extconf.rb failed ***
```

**Comment by ctiller** [comment]
Ok, so you're trying to build the Ruby extension?

**Comment by touchardv** [comment]
Yes. Initially I was just trying to deploy my Ruby app but it turned out that the Ruby gem manager (bundler) failed installing some of the necessary dependencies `google-cloud` gem because... this Ruby gem extension compilation was failing.
So right, now I am trying to "build the Ruby extension" via this command:
`bundle exec gem install grpc -v '1.0.1'`
with:
* Bundler version 1.7.9
* ruby 2.1.7p400 (2015-08-18 revision 51632) [armv6l-linux-eabihf]

**Comment by hipcrime** [comment]
Has there been any progress with this?
Months later and facing the same problem; that is, "fatal error: stdalign.h: No such file or directory" ......

Gem::Ext::BuildError: ERROR: Failed to build gem native extension.

    current directory: /usr/local/rvm/gems/ruby-2.3.3/gems/grpc-1.2.2/src/ruby/ext/grpc
/usr/local/rvm/rubies/ruby-2.3.3/bin/ruby -r ./siteconf20170414-14390-112v0cu.rb extconf.rb
Building internal gRPC into /usr/local/rvm/gems/ruby-2.3.3/gems/grpc-1.2.2/src/ruby/ext/grpc/libs/opt
make: Entering directory '/usr/local/rvm/gems/ruby-2.3.3/gems/grpc-1.2.2'
[C]       Compiling third_party/zlib/adler32.c
[C]       Compiling third_party/zlib/compress.c
[C]       Compiling third_party/zlib/crc32.c
[C]       Compiling third_party/zlib/deflate.c
[C]       Compiling third_party/zlib/gzclose.c
[C]       Compiling third_party/zlib/gzlib.c
[C]       Compiling third_party/zlib/gzread.c
[C]       Compiling third_party/zlib/gzwrite.c
[C]       Compiling third_party/zlib/infback.c
[C]       Compiling third_party/zlib/inffast.c
[C]       Compiling third_party/zlib/inflate.c
[C]       Compiling third_party/zlib/inftrees.c
[C]       Compiling third_party/zlib/trees.c
[C]       Compiling third_party/zlib/uncompr.c
[C]       Compiling third_party/zlib/zutil.c
[C]       Compiling src/boringssl/err_data.c
[C]       Compiling third_party/boringssl/crypto/aes/aes.c
[C]       Compiling third_party/boringssl/crypto/aes/mode_wrappers.c
[C]       Compiling third_party/boringssl/crypto/asn1/a_bitstr.c
[C]       Compiling third_party/boringssl/crypto/asn1/a_bool.c
[C]       Compiling third_party/boringssl/crypto/asn1/a_d2i_fp.c
[C]       Compiling third_party/boringssl/crypto/asn1/a_dup.c
[C]       Compiling third_party/boringssl/crypto/asn1/a_enum.c
[C]       Compiling third_party/boringssl/crypto/asn1/a_gentm.c
[C]       Compiling third_party/boringssl/crypto/asn1/a_i2d_fp.c
[C]       Compiling third_party/boringssl/crypto/asn1/a_int.c
[C]       Compiling third_party/boringssl/crypto/asn1/a_mbstr.c
[C]       Compiling third_party/boringssl/crypto/asn1/a_object.c
[C]       Compiling third_party/boringssl/crypto/asn1/a_octet.c
[C]       Compiling third_party/boringssl/crypto/asn1/a_print.c
[C]       Compiling third_party/boringssl/crypto/asn1/a_strnid.c
[C]       Compiling third_party/boringssl/crypto/asn1/a_time.c
[C]       Compiling third_party/boringssl/crypto/asn1/a_type.c
[C]       Compiling third_party/boringssl/crypto/asn1/a_utctm.c
[C]       Compiling third_party/boringssl/crypto/asn1/a_utf8.c
[C]       Compiling third_party/boringssl/crypto/asn1/asn1_lib.c
[C]       Compiling third_party/boringssl/crypto/asn1/asn1_par.c
[C]       Compiling third_party/boringssl/crypto/asn1/asn_pack.c
[C]       Compiling third_party/boringssl/crypto/asn1/f_enum.c
[C]       Compiling third_party/boringssl/crypto/asn1/f_int.c
[C]       Compiling third_party/boringssl/crypto/asn1/f_string.c
[C]       Compiling third_party/boringssl/crypto/asn1/t_bitst.c
[C]       Compiling third_party/boringssl/crypto/asn1/tasn_dec.c
In file included from third_party/boringssl/crypto/asn1/tasn_dec.c:66:0:
third_party/boringssl/crypto/asn1/../internal.h:121:22: fatal error: stdalign.h: No such file or directory
compilation terminated.
[C]       Compiling third_party/boringssl/crypto/asn1/tasn_enc.c
Makefile:2364: recipe for target '/usr/local/rvm/gems/ruby-2.3.3/gems/grpc-1.2.2/src/ruby/ext/grpc/objs/opt/third_party/boringssl/crypto/asn1/tasn_dec.o' failed
make: *** [/usr/local/rvm/gems/ruby-2.3.3/gems/grpc-1.2.2/src/ruby/ext/grpc/objs/opt/third_party/boringssl/crypto/asn1/tasn_dec.o] Error 1
make: *** Waiting for unfinished jobs....
make: Leaving directory '/usr/local/rvm/gems/ruby-2.3.3/gems/grpc-1.2.2'
*** extconf.rb failed ***
Could not create Makefile due to some reason, probably lack of necessary
libraries and/or headers.  Check the mkmf.log file for more details.  You may
need configuration options.

Provided configuration options:
        --with-opt-dir
        --without-opt-dir
        --with-opt-include
        --without-opt-include=${opt-dir}/include
        --with-opt-lib
        --without-opt-lib=${opt-dir}/lib
        --with-make-prog
        --without-make-prog
        --srcdir=.
        --curdir
        --ruby=/usr/local/rvm/rubies/ruby-2.3.3/bin/$(RUBY_BASE_NAME)

extconf failed, exit code 1

Gem files will remain installed in /usr/local/rvm/gems/ruby-2.3.3/gems/grpc-1.2.2 for inspection.
Results logged to /usr/local/rvm/gems/ruby-2.3.3/extensions/armv6l-linux/2.3.0/grpc-1.2.2/gem_make.out

An error occurred while installing grpc (1.2.2), and Bundler cannot continue.
Make sure that `gem install grpc -v '1.2.2'` succeeds before bundling.

**Comment by nbravos** [comment]
I'm having the same error as you, and if I try to install the grpc 1.2.2 I get an error aswell.
No idea what's wrong.

**Comment by jayhill365** [comment]
Having the same issue
