### ISSUE TITLE
Unable to compile on windows (MSVC 2015)

### ISSUE THREAD

**Issue by donalmacc** [grpc/grpc#9084]
Hi there

I'm attempting to compile with MSVC2015 on windows (x64), but it appears to be totally undocumented. The [documentation](https://github.com/grpc/grpc/blob/master/INSTALL.md) doesn't really cover any of the issues (I can run CMake over the CMakeLists.txt file, but I can't compile that solution. There doesn't appear to be a list of libs which are required for gRPC to be used.

Is there a step by step anywhere? I can provide you with a list of a hundred warnings that are treated as errors, but I doubt that will be much help to you.

**Comment by donalmacc** [comment]
For some more information, it appears that many of the issues are related to using boringSSL. Is BoringSSL required to build/use grpc, and if not, how can I build without it?

**Comment by allquixotic** [comment]
BoringSSL is an alternative to OpenSSL. Both work because they are source API compatible, as far as I recall. 

grpc is so difficult to build on Windows, and the maintainers appear to be so indifferent about improving the user compile experience on Windows, that someone has created a repo specifically to ease the building process: https://github.com/plasticbox/grpc-windows

It worked for me; I highly recommend you check out the grpc-windows repo. I am not optimistic that efforts in upstream grpc will yield anywhere _near_ as easy of a build on Windows in the near future.

**Comment by donalmacc** [comment]
Thanks for that! After posting this, I read through the issue tracker some more and noticed that I'm not he first person to note this. 

The maintainers don't seem to be actively engaging with anyone who is interested in using gRPC on Windows either, which is disappointing. I'll take a look!

**Comment by allquixotic** [comment]
I also found this fork which seems to have continued the work of "plasticbox" by adding support for protobuf-3.1 and grpc-1.0. I haven't tried it myself, but you might want to. https://github.com/jozefizso/grpc-windows

It also has a build script to build for *32-bit* Windows. Definitely useful.

**Comment by jtattermusch** [comment]
Are you trying to build gRPC C core or C++? Building C core with MSVC2015 is fully supported (and also gets continuously tested). Building C++ is trickier (mostly because of the gRPC dependencies like protobuf and boringssl rather than gRPC itself), but we are working on improving the situation.

**Comment by allquixotic** [comment]
@jtattermusch Personally I'm using C++, so I built (past tense, yes, using the aforementioned josefizso/grpc-windows repo) grpc++.

First I ran "build_clone.bat". Then I had to do the following:

Find -> Replace (I use Notepad++) all *.vcxproj files in the grpc distribution (recursively) as follows:

`<TreatWarningAsError>true</TreatWarningAsError>` with `<TreatWarningAsError>false</TreatWarningAsError>` (as an aside: seriously, guys, stop it with the `-Werror` already; I know this is very useful for development and ensuring correctness, but real-world compilers are **going** to have warnings that you didn't anticipate; users lack the patience to fix them; most of the time they don't actually hurt anything; and this needs to NOT be the default in code that's being released to *users*!)

Then, because I was linking grpc++ with code that uses `/MD` (dynamic linking to msvcrt and the Visual Studio C++ runtime) and recompiling those binaries is extremely difficult and undesirable for reasons I won't get into, I did another find/replace (recursive, on *.vcxproj) for this:

`<RuntimeLibrary>MultiThreaded</RuntimeLibrary>` with `<RuntimeLibrary>MultiThreadedDLL</RuntimeLibrary>`

and the protobuf dependency in the third_party directory emits Visual Studio projects from CMake, so I had to patch this in third_party/protobuf/CMakeLists.txt:

```
if(${flag_var} MATCHES "/MD")
        string(REGEX REPLACE "/MD" "/MT" ${flag_var} "${${flag_var}}")
      endif(${flag_var} MATCHES "/MD")
```

becomes

```
if(${flag_var} MATCHES "/MT")
        string(REGEX REPLACE "/MT" "/MD" ${flag_var} "${${flag_var}}")
      endif(${flag_var} MATCHES "/MT")
```

Is that all? I can't really remember. Basically, getting a working build of grpc++ to do what I want on Windows is an absolute nightmare, made *slightly* less horrid by josefiszo/grpc-windows, but still requiring significant manual hacking. Bring a powerful text editor with recursive find/replace or you will perish in the attempt.

**Comment by jtattermusch** [comment]
I've made several improvements to our CMake build and it should now be possible to build gRPC C++ with CMake (both Ninja and Visual Studio 2015 should work). Some of the changes still might be in one of my open pull requests.

See instructions here:
https://github.com/grpc/grpc/blob/master/INSTALL.md

Can you please try the instructions and verify if you can achieve your goals now?

**Comment by donalmacc** [comment]
Hi Jan,

Thanks for the improvements. Unfortunately, we've moved on and are using Apache thrift now.

We may revisit in the future.

**Comment by allquixotic** [comment]
I'll test it for you in lieu of donalmacc, if you like, @jtattermusch.

I use grpc++ on 64-bit Windows 10 every day, originally compiled using VS2015. I'd be glad to test your changes and provide feedback!

Look for my response here by the end of the week.

Regards

**Comment by Aneurin** [comment]
@jtattermusch Thanks for this - I was able to build (with VS 2015 on Windows 10 x64) using the CMake instructions without modification, and link the results painlessly into a minimal Qt application.

**Comment by Zeks** [comment]
cmake instruction didnt work for me. it said: 
ninja: error: loading 'build.ninja'
and then something broken by cp866 encoding :(

**Comment by Zeks** [comment]
I can't install using cmake because of: 
 warning C4464: relative include path contains '..' [D:\libs\grpc_latest\.build\third_party\boringssl\crypto\asn1\asn1.vcxproj]

and

 error C2220: warning treated as error - no 'object' file generated [D:\libs\grpc_latest\.build\third_party\boringssl\crypto\asn1\asn1.vcxproj]

there is a lot of these. What do I do?

**Comment by jilayp** [comment]
H

**Comment by jilayp** [comment]
Hey Everyone, I would like to reopen this thread. I have been trying since past couple of days to compile gRPC for C++ for Windows and am receiving some standard aforementioned errors. Can someone from the team please take some time out to provide a documented solution, or maybe explain in a little bit detail about how things should be executed in a step-wise manner. Thanks for the help in Advance. 😀

**Comment by jtattermusch** [comment]
@jilayp can you be more specific (what commands you ran and what was the error)? Otherwise it is hard to help.

**Comment by Varada** [comment]
[builderror.txt](https://github.com/grpc/grpc/files/1993880/builderror.txt)
@jtattermusch - please see logs of building it with VS2017. Bunch of warnings - with warnings being treated as errors

**Comment by nicolasnoble** [comment]
To avoid confusion and conflation of problems, I'd rather have people opening new issues in case issues are different.

In this case, this is a different problem, indeed. The warnings are coming from a subdependency, and there's little we'll be able to do to fix them, meaning that compiling with warning treated as errors won't work.

**Comment by Varada** [comment]
Sorry - I might have done something wrong, and happy to understand what it is. 

The build indeed succeeds if I did a global replace of <TreatWarningAsError>true</TreatWarningAsError> to false.

**Comment by nicolasnoble** [comment]
Wait, is this flag on by default in our CMakefiles ? That's interesting, and would definitely warrant a new issue to open, @jtattermusch.

**Comment by Varada** [comment]
Yes. The default cmake has this flag on by default.
