### ISSUE TITLE
Async GRPC c# await 

### ISSUE THREAD

**Issue by jhayotte** [grpc/grpc#9140]
Hi,

I am wondering about the async methods generated for csharp. It returns a AsyncUnaryCall which is not awaitable.

I don't get the principle. Could you provide us a sample of client working with an async method in c#.

Here is my code that works but I can't make it awaitable:

```
var result = client.GetArticleByIDAsync(new pb.GetArticleByIDRequest{Id = 1});
Console.WriteLine(result.ResponseAsync.Result.Article.Id);
```

Thx in advance,

**Comment by jtattermusch** [comment]
The AsyncUnaryCall object itself actually is awaitable, because it defines GetAwaiter() function.
There's two things you can do (keep in mind you need to be in async context in both cases):
```
// make use of the fact that AsyncUnaryCall defines GetAwaiter() function.
var result = await client.GetArticleByIDAsync(new pb.GetArticleByIDRequest{Id = 1});

```

```
var call = client.GetArticleByIDAsync(new pb.GetArticleByIDRequest{Id = 1});
// use the ReponseAsync property that is of type 
var result = await call.ResponseAsync;
```

Also, using `.Result` as in `result.ResponseAsync.Result` is an antipattern in C# async programming, don't use it.
Use client.GetArticleByID() if you need to invoke the RPC synchronously.
