### ISSUE TITLE
Can't shutdown when there are active calls on client in C#

### ISSUE THREAD

**Issue by neuecc** [grpc/grpc#9202]
The channel receiving StreamingCall can not shutdown.
This causes a deadlock when exiting the client from the outside, such as `GrpcEnvironment.ShutdownChannelsAsync`.

```csharp
var client = new Routeguide.RouteGuide.RouteGuideClient(channel);
var streaming = client.ListFeatures(new Routeguide.Rectangle() { Hi = new Routeguide.Point { Latitude = 1, Longitude = 1 }, Lo = new Routeguide.Point { Latitude = 1, Longitude = 1 } });

// true, streaming is yet connecting.
await streaming.ResponseStream.MoveNext();

// Deadlock in thread.Join() in GrpcThreadPool.StopAsync, can't shutdown from user code.
await GrpcEnvironment.ShutdownChannelsAsync();

Console.WriteLine("don't reach here.");
```

If you try to avoid it (Dispose CompletionQueueSafeHandle without Thread.Join and set the termination condition of RunHandlerLoop to `while (ev.type! = CompletionQueueEvent.CompletionType.Shutdown &&! Cq.IsClosed)`)
But `DebugStats.CheckOK` raises an exception(because it has some pending batch completions).

**Comment by apolcyn** [comment]
Is there more in the surrounding code of the repro? Can you please provide the complete client program?

Seeing the above snippet run successfully when ran
e.g. using `Task.Run(async () => { // repro ...  }).Wait();`

**Comment by neuecc** [comment]
Thank you, generate from `route_guide.proto` of gRPC sample.

Impl Server

```csharp
public override async Task ListFeatures(Rectangle request, IServerStreamWriter<Feature> responseStream, ServerCallContext context)
{
    // return 3 times.
    await responseStream.WriteAsync(new Feature());
    await responseStream.WriteAsync(new Feature());
    await responseStream.WriteAsync(new Feature());
}
```

Impl Client

```csharp
class Program
{
    static void Main(string[] args)
    {
        var _ = Check();
        Console.ReadLine();
    }

    static async Task Check()
    {
        var channel = new Channel("127.0.0.1:12345", ChannelCredentials.Insecure);
        await channel.ConnectAsync();

        var client = new Routeguide.RouteGuide.RouteGuideClient(channel);
        var streaming = client.ListFeatures(new Routeguide.Rectangle());

        // true, streaming is yet connecting.
        await streaming.ResponseStream.MoveNext();

        // Deadlock in thread.Join() in GrpcThreadPool.StopAsync, can't shutdown from user code.
        await GrpcEnvironment.ShutdownChannelsAsync();

        Console.WriteLine("don't reach here.");
    }
}
```

`ShutdownChannelsAsync()` freezes in thread.Join of GrpcThreadPool. https://github.com/grpc/grpc/blob/master/src/csharp/Grpc.Core/Internal/GrpcThreadPool.cs#L111
Thread is wait to complete RunHandlerLoop and shutdown channel sends the Shutdown operation https://github.com/grpc/grpc/blob/master/src/csharp/Grpc.Core/Internal/GrpcThreadPool.cs#L103
but if streaming is opening `cq.Next()` is blocked. https://github.com/grpc/grpc/blob/master/src/csharp/Grpc.Core/Internal/GrpcThreadPool.cs#L175

**Comment by neuecc** [comment]
Te issue I think is `await GrpcEnvironment.ShutdownChannelsAsync();` wait Streaming and user's can't handle its behavior. It would be very nice if there are another method to terminate channel immediately, like `GrpcEnvironment.TerminateChannels();` may be?

**Comment by jtattermusch** [comment]
@neuecc , the way things work currently is that on the client side, one needs to finish or cancel all calls before attempting to shutdown a channel (I can see how that can be limiting in some use cases, on the other hand, it's not unreasonable to expect user code to know what's happening with client calls at any given time).

If you need to shutdown your application unexpectedly, the way you can do it is through cancelling all your outstanding calls and then invoking GrpcEnvironment.ShutdownChannelsAsync()  (we can't really shutdown cleanly when there are inflight calls, because that means an inconsistent state during shutdown and potentially crashing the app).

One way to achieve this, is to use channel.ShutdownToken cancellation token (that gets cancelled whenever the channel is shutdown).

```
var call = client.ListFeatures(new Routeguide.Rectangle(), cancellationToken: channel.ShutdownToken)
```
Such call will be automatically cancelled when the channel shutdown is requested (and your repro code will work fine).
Also, you don't have to use channel.ShutdownToken specifically, but you can have your own application-wide cancellationToken, which you can trigger whenever your application needs to shutdown unexpectedly.

Tracking lifetime of all outstanding calls can represent a performance penalty, which is also the reason why gRPC isn't doing this automatically.

**Comment by jtattermusch** [comment]
Also, the call to `channel.ConnectAsync()` is not necessary in your code. The channel connects automatically once an RPC is started (and that's the recommended way to connect the channel).

**Comment by jozefizso** [comment]
We use `GrpcEnvironment.ShutdownChannelsAsync()` in our unit tests global teardown method to shutdown any outstanding calls that may be around from failed tests.

Unfortunately this hangs test runner forever if we have some `await streaming.ResponseStream.MoveNext();` calls awaiting.

**Comment by JimHume** [comment]
I'm seeing the same behaviour as @jozefizso describes: I have multiple streams connected to downchannel clients but I need to stop the server. The clients should disconnect when I shut my server down but it instead hangs when calling 'await foo.ShutdownAsync()'.

Is there a recommended work around while this gets investigated/worked-on?
