### ISSUE TITLE
Remove VC Runtime dependency from Zlib Native Nuget package

### ISSUE THREAD

**Issue by jozefizso** [grpc/grpc#9239]
The Zlib Native Nuget package (`grpc.dependencies.zlib.redist`) is compiled with DLL version of the VC++ runtime library. For Visual Studio 2015 (platform v140) it requires the VC++ Runtime 2015 to be installed on end user machine, or manual distribution of vcruntime140.dll and ucrtbase.dll and some other DLL files.

Can you update this package to use staticaly linked runtime?

PS: The OpenSSL nuget package `grpc.dependencies.openssl.redist` uses static run-time library so it has not external dependencies.

**Comment by jtattermusch** [comment]
Is this affecting you when using C++ or C#?
Btw, I am currently working on improving our CMake building capabilities on Windows, which might eventually deprecate the current Windows build (generated VS projects + nugets for openssl and zlib) completely.

**Comment by jozefizso** [comment]
Libraries distributed with C# does not need the VC++ 2015 Runtime (AFAIK).

This is affecting only gRPC v1.0 C++ libraries for Windows and only the **zlib** dependency.

**Comment by jtattermusch** [comment]
Using the recent improvement to our CMake build on Windows, you should be able to build gRPC C++  with or without VC++ runtime.

https://github.com/grpc/grpc/blob/f7f25fc01ec75670e9d11c8852b296527837dd9d/CMakeLists.txt#L93

Building with CMake is now the recommended way of building gRPC C++ on Windows, as it uses boringssl instead of older version of openssl and the build in generally cleaner.

We might be deprecating the zlib nuget package, so I will close this issue now.

**Comment by vadimi** [comment]
@jtattermusch this change sort of broke grpc 1.2.0 nuget package on windows as msvc++ runtime is not statically linked anymore, so the services fail to start.

**Comment by jtattermusch** [comment]
@vadimi  you probably need to install https://www.microsoft.com/en-us/download/details.aspx?id=48145 (at least as a workaround that should help).
