### ISSUE TITLE
Implement closed-streaming benchmark

### ISSUE THREAD

**Issue by ctiller** [grpc/grpc#9264]
Send a stream of some small number of messages (1 or 2 or 3), and then wait for the same number of responses. The time for the request is the time of the entire stream.

- [ ] C++
- [ ] Java
- [ ] Go
- [ ] Python
- [ ] C#
- [ ] Node
- [ ] Ruby

**Comment by nathanielmanistaatgoogle** [comment]
Is there somewhere where this is specified precisely enough to implement? Or are we free to choose one message or two messages or three messages, and any size at all for those messages?

Is the "skeleton" for this already in place so that if I implemented this today the measurements that were generated would be taken in and used by another system?

**Comment by nathanielmanistaatgoogle** [comment]
@adelez, @matt-kwong, @jtattermusch: any status update here? Is this still an open gRPC-wide aspiration?

**Comment by jtattermusch** [comment]
AFAIK there are no plans for this.  @ncteisen what is the significance of this benchmark?

**Comment by ncteisen** [comment]
We are not adding a scenario like this, this issue can be clised
