### ISSUE TITLE
Mixing Grpc and Rx leads to an error  - Is IServerStreamWriter forced to be used in one thread only?

### ISSUE THREAD

**Issue by MatthiasWeiser** [grpc/grpc#9442]
I am trying to expose an observable via a GRPC stream.
my simplified code looks like this:

```
    public override async Task Feed(Request request, IServerStreamWriter<Response> responseStream, ServerCallContext context)
            {
                var result = new Result();
                try
                {
                    await Observable.ForEachAsync(async value =>
                    {
                        await responseStream.WriteAsync(value);
                    });
    
                }
                catch (Exception ex)
                {
                    Log.Info("Session ended:" + ex);
                }
            }


I receive the following error:

> W0123 14:30:59.709715
> Grpc.Core.Internal.ServerStreamingServerCallHandler`2 Exception
> occured in handler. System.ArgumentException: Der Wert liegt außerhalb
> des erwarteten Bereichs.    bei
> Grpc.Core.Internal.ServerStreamingServerCallHandler`2.<HandleCall>d__4.MoveNext()
> W0123 14:30:59.732716 Grpc.Core.Server Exception while handling RPC.
> System.InvalidOperationException: Der Vorgang ist aufgrund des
> aktuellen Zustands des Objekts ungültig.    bei
> Grpc.Core.Internal.AsyncCallServer`2.SendStatusFromServerAsync(Status
> status, Metadata trailers, Tuple`2 optionalWrite)    bei
> Grpc.Core.Internal.ServerStreamingServerCallHandler`2.<HandleCall>d__4.MoveNext()
> --- Ende der Stapelüberwachung vom vorhergehenden Ort, an dem die Ausnahme ausgelöst wurde ---    bei
> System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task
> task)    bei
> System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task
> task)    bei Grpc.Core.Server.<HandleCallAsync>d__34.MoveNext()

How would you recommend to handle this?  I guess I would need to process the ForEachAsync in the same thread. I did not see any comments regarding thread/task requirements inside the documentation - thus I am not sure if this is to be documented feature or a bug.

**Comment by MatthiasWeiser** [comment]
I am using the current Nuget version for the Grpc side (1.0.1).

**Comment by jtattermusch** [comment]
Hi, I responded to the issue here: http://stackoverflow.com/questions/41807693/grpc-use-rx-observable/41869217

*With the gRPC streaming API, you are only allowed to write one item at a time. If you start another WriteAsync() operation before the previous one finishes, you'll get an exception. You also need to finish all your writes before returning from the method handler (the Feed method in this case). The reason only one write is allowed at a time is to ensure gRPC's flow control works well.

In your case the Rx API doesn't seem to be capable of ensuring that, so one way to solve this would be to use an intermediate buffer.*

This issue doesn't seem to be a genuine problem in mixing Grpc and Rx, it's more about figuring out the right way to do that - therefore closing. Feel free to share your code once you figure this out and you're happy with it.

**Comment by MatthiasWeiser** [comment]
I will write a RouteGuideServer implementation which leverages the TPL data flow [BufferBlock](https://msdn.microsoft.com/de-de/library/hh160414(v=vs.110).aspx). 
I think that this is the best way for synchronizing gRPC streams inside a server.

**Comment by jtattermusch** [comment]
@MatthiasWeiser  you also might wanna look at Jon's implementation of write buffering here:
https://github.com/googleapis/gax-dotnet/pull/117
