### ISSUE TITLE
Ruby: add example for connection termination detection from server handler

### ISSUE THREAD

**Issue by josselin-c** [grpc/grpc#9455]
Using Ruby, I'm trying to implement a service that returns an infinite stream of events `Watch() Stream`.
Looking at the documentation I wasn't able to understand how I can detect that a client connection is closed from my handler. I need this to release resources/threads so they don't grow forever.

I attached to this issue an example code where I start a thread for each call to Watch(). I would like to be able to stop the thread after the client disconnects.

[grpc_stream_thread.tar.gz](https://github.com/grpc/grpc/files/726894/grpc_stream_thread.tar.gz)

**Comment by apolcyn** [comment]
Does the current [route chat](https://github.com/grpc/grpc/blob/master/examples/ruby/route_guide/route_guide_server.rb#L147) example satisfy?

Otherwise one idea on this:

The first parameter to a server-side stream handler is a ruby `Enumerable`. Reads on this are blocking, and one possibility is that the client could send the `sentinal` of some sort of `Enumerable` (e.g. https://github.com/grpc/grpc/blob/master/examples/ruby/route_guide/route_guide_client.rb#L148) when it's done. On the server side one could basically make a blocking read on the input stream by enumerating through it. This completes once the client has sent the end of it's `Enumerable`
