### ISSUE TITLE
Before & after RPC request handler hook

### ISSUE THREAD

**Issue by Hujun** [grpc/grpc#9576]
I wonder if there is a way to add before and after request handler functions in grpc python? For instance, automatically log request info of each RPC instead of repeatedly logging in callbacks.

**Comment by ctiller** [comment]
Which language are you asking for?

**Comment by nathanielmanistaatgoogle** [comment]
There's not currently a generic mechanism for running code on every RPC. With the API in its current shape, I would recommend implementing the `grpc.Channel` interface with a proxy object that does the logging you want before invoking the RPC on a "real" channel. Would that be sufficient for your case?

**Comment by Hujun** [comment]
I'm doing class decorator as:

```Python
def request_wrapper(func):
    def deco(*args, **kwargs):
        # Before request handlers
        print('Before request')

        rtn = func(*args, **kwargs)
        
        # After request handlers
        print('After request')

        return rtn
    return deco


def GrpcServerWrapper(cls):
    class ClassWrapper(object):
        def __init__(self, *args, **kwargs):
            self.instance = cls(*args, **kwargs)

        def __getattribute__(self, k):
            try:
                v = super(ClassWrapper, self).__getattribute__(k)
            except AttributeError:
                pass
            else:
                return v
            v = self.instance.__getattribute__(k)
            if type(v) == type(self.__init__):
                return request_wrapper(v)
            else:
                v
    return ClassWrapper

@GrpcServerWrapper
class Foo(foo_server_pb2.FooServer):

    def Ping(self, req, ctx):
         .....
 

```

From my view, it would be more elegant if a similar request wrapper could be automatically set in server class when python stub is generated. 

not really understand the grpc.Channel proxy solution mentioned. Could you please give more details?

**Comment by nathanielmanistaatgoogle** [comment]
Oh, so you're looking for this mechanism server-side?

In that case you may want to look at how your generated code constructs a `grpc.ServiceRpcHandler` and passes that to your `grpc.Server`. The best thing to do would be for you to implement a `grpc.ServiceRpcHandler` (or `grpc.GenericRpcHandler`) that delegates to the `grpc.ServiceRpcHandler` constructed by the generated code (and that object delegates to your `Servicer` implementation for ultimate service of RPCs); the problem is that we didn't really leave open the right insertion point for that to easily be done (the function is called `add_<your service's name>_servicer_to_server` and it adds your servicer to the passed server as opposed to being called `construct_service_rpc_handler_from_<your service's name>_servicer` and returning to you a `grpc.ServiceRpcHandler` object that you then additionally have to add to your server). To work around that... if you were like me, you'd implement a delegating `grpc.Server` object that when passed a `grpc.GenericRpcHandler` wraps it before passing it to the delegate `grpc.Server`. But there are other ways to go.

Maybe we should expose a `construct_service_rpc_handler_from_<your service's name>_servicer` function in generated code? It'd be cheap to do and would cover this case very well.

Incidentally, why use `__getattribute__` rather than `__getattr__`?

**Comment by alertedsnake** [comment]
re: `construct_service_rpc_handler_from_<your service's name>_servicer` - is this something that's planned?  The 'adder' function is a bit awkward because of how it restricts things like this, and working around it by using wrapping or delegating objects as you suggest is really awkward.

**Comment by nathanielmanistaatgoogle** [comment]
@alertedsnake: it's not currently planned... and the whole thought of it may be obviated by the recent introduction of interceptors. I'd suggest checking them out.

**Comment by nathanielmanistaatgoogle** [comment]
@mehrdada: is there anything about this issue worth keeping open now that interceptors exist?

**Comment by alertedsnake** [comment]
@nathanielmanistaatgoogle Ah, of course!  That's probably the right way to do it.

**Comment by mehrdada** [comment]
I don't have much to add to this except to agree with @nathanielmanistaatgoogle that interceptors introduced a mechanism to add before and after logic for RPCs. We are not currently planning an ability to intercept the add function though. I'm closing this issue.

**Comment by alertedsnake** [comment]
Actually, I don't think Interceptors clearly solve this use-case.  Unless I'm missing something (the docs could be a lot better here), there's no way within the interceptor to know your position in the chain of interceptors (thus making the "after" case difficult to do reliably), and I don't see a way to inspect the context from within the interceptor, so you can't actually look at the response code or whether the RPC was aborted.

Currently, I took the path that @Hujun took with a decorator, but instead just added a logging function via `context.add_callback()`, but it's not really ideal at all, I was hoping for something I could tack onto a server when I create a subclass of `GrpcServer` with specifics to my needs.

Perhaps you can point out an example?

**Comment by mehrdada** [comment]
@alertedsnake You cannot tell your position within an interceptor, almost entirely by design: it should be a black box to the interceptor where it is, who invokes it, and what the continuation actually invokes, and the interceptor registration process ensures its place in line of interceptors. If you want an interceptor to run first, you should register it as the first interceptor.

I assume you are talking about server interceptors, in which case, the interception process happens when an `RpcMethodHandler` is being resolved. I have an example PR for a related thing (not done yet but might be helpful nevertheless): 
https://github.com/mehrdada/grpc/blob/aa477becd1a7c44f8150ad24539cf6d40af24b37/examples/python/interceptors/service-latency-interceptor/service_latency_interceptor.py

The proper way to run something as the last RPC message ends (applicable for response-streaming RPCs only) is to return an `RpcMethodHandler` that invokes the underlying response-streaming method, but wraps the returned response-iterator such that after the last message is encountered on the stream, performs some action.

**Comment by alertedsnake** [comment]
I found another issue that makes this impossible: you can't actually access the `context` variable within an interceptor, so there are a lot of things you can't see - HTTP headers, for example.  

This is possible with using the `context.add_callback()` method I described, but there's no way within the callback to obtain the `context` either, and so it's also not a useful method for logging information therein.

So again, I disagree that there is an adequate existing solution for the problem that was asked.  Are there plans to address this in some way?

**Comment by mehrdada** [comment]
@alertedsnake the idea is you return a substitute RpcMethodHandler from the intercept_service that has access to context. This way if you're not interested in further interception, you can get out of the invocation path of the RPC. If you are, the interceptor constructs it's own wrapper RpcMethodHandler that does arbitrary things when invoked, and that has access to the full context.

**Comment by alertedsnake** [comment]
@mehrdada Do you have an example of this?  Also, according to what you said earlier, this only works for streaming responses, what about unary?

**Comment by alertedsnake** [comment]
I'm trying your method of returning a substitute RpcMethodHandler, based on the code you linked, and there still isn't a way to get the `context._state` and log the error code, since interceptors happen *before* the business logic in the handler code.  The only way you can get that is *after* the call entirely, which means the callback method I described earlier.  Overall I do like this approach better than the callback, if it actually worked.

Possibly I'm just not seeing what you mean, so if you have an example where this works, that would be great, otherwise again, the question in this issue has not yet been answered.

**Comment by mehrdada** [comment]
@alertedsnake I am OOO for a couple weeks. Will write an example after I come back, but the general pattern is the following:  To intercept the code/details, the idea is to wrap the context *before* passing it to the next `continuation`; that way you can implement your own `set_code`/`set_details`/`abort` calls that keep track of the metadata and then call into the underlying `context`.

**Comment by wkiser** [comment]
@alertedsnake for unary response types you should be able to log the status code in the finally block of @mehrdada's example. `servicer_context._state.code` will be up to date with any changes that occurred in your handler function. One caveat is that code will be None for OK responses.

**Comment by fangyishu** [comment]
Any suggestion about how to do that in Java?
