### ISSUE TITLE
Python interop http2_badserver tests are failing

### ISSUE THREAD

**Issue by adelez** [grpc/grpc#9622]
https://grpc-testing.appspot.com/view/Pull%20requests/job/gRPC_interop_pull_requests/11221/HTML_Report/

Full log: https://grpc-testing.appspot.com/view/Pull%20requests/job/gRPC_interop_pull_requests/11221/consoleFull

@makdharma

**Comment by ncteisen** [comment]
Copying my comment from another thread:

Those tests are now failing due to this commit: [Revert "Revert "Metadata handling rewrite""](https://github.com/grpc/grpc/commit/7c70b6c144a20782b6be4751da68c6aa7b35648d), which takes away more specific debugging prints right [here](https://github.com/grpc/grpc/commit/7c70b6c144a20782b6be4751da68c6aa7b35648d#diff-434e605a287683b6db888d5786b51cb2L115).

My tests asserted that the status details were Received RST_STREAM with error code 0. Now all that is output is RST_STREAM.

Will follow up with @ctiller about why the more verbose error message was removed to determine if the test should change, or if the verbose error message should be re-added.

**Comment by ncteisen** [comment]
My PR fixed the three rst stream errors, but there are still two timeouts I need to sort out.

Reopening

**Comment by ncteisen** [comment]
These have not been seen in about a year
