### ISSUE TITLE
C tests failing under bazel

### ISSUE THREAD

**Issue by yang-g** [grpc/grpc#9624]
In PR bazel full:

//test/core/bad_ssl:bad_ssl_alpn_server                                  FAILED in 0.1s

//test/core/bad_ssl:bad_ssl_cert_server                                  FAILED in 0.1s
 
//test/core/end2end:h2_fd_test@ping                                      FAILED in 0.1s
 
//test/core/end2end:h2_proxy_test@compressed_payload                     FAILED in 0.1s
 
//test/core/end2end:h2_sockpair_1byte_test@ping                          FAILED in 0.1s
  /
//test/core/end2end:h2_sockpair_test@ping                                FAILED in 0.1s
  
//test/core/end2end:h2_ssl_proxy_test@compressed_payload                 FAILED in 0.4s
 
//test/core/end2end:h2_ssl_proxy_test@connectivity                       FAILED in 0.3s
 
//test/core/end2end:h2_ssl_proxy_test@resource_quota_server              FAILED in 0.2s

**Comment by ctiller** [comment]
Needs port server to be running... which means needs a plan for port
server + bazel.

Options:
1. wrapper script (similar to what we have, bad because it's undiscoverable
to bazel users)
2. force starting a port server (have tests complain that it's not running,
with a command line to fix)
3. have tests automatically start port server if it's not running

I'm preferring 2 right now.

**Comment by rjshade** [comment]
These tests have been disabled internally: remember to re-enable them when fixing this issue.

**Comment by nicolasnoble** [comment]
Also maybe use run_test's logic for starting the port server ? We could run bazel through run_test (and its dockerization as well).
