### ISSUE TITLE
Race condition on channel connectivity status

### ISSUE THREAD

**Issue by dgquintas** [grpc/grpc#9646]
Surfaced by the flakiness that #9566 tried to address, there's currently a race condition in the propagation of the connectivity status for the client channel:

1. The (dns) resolver spawns a thread via the executor closure type.
1. This thread creates its own `exec_ctx`. All subsequent callbacks will be scheduled against it.
1. In particular, the `on_lb_policy_state_changed` callback from `client_channel.c`, responsible for propagating the connectivity state of the LB policy (which is a reflection of the conn. state of its subchannels).
1. There are two different `exec_ctx` instances behind the high level call to `grpc_call_start_batch`, with currently no synchronization between them. 
1. Therefore, under load, the resolver's executor `exec_ctx`, running on a separate thread, may run its scheduled closures _after_ the call's `exec_ctx` on the main thread.
1. The race is apparent in the non-deterministic connectivity status update delay for the call's channel. 

## Solutions
- Prevent LB policies from providing picks until the connectivity status of its parent channel is updated to `READY`. This is the preferred solution.
- Add a "grace period" to tests, enough to account for the eventual (albeit non-deterministic) update of the channel's connectivity status.

@ctiller FYI

**Comment by markdroth** [comment]
FWIW, note that the new c-ares resolver code in #7771 does not use a different thread for name resolution, so if that's the cause of the problem here, it might go away with that change.  Although note that we will still have some subsequent work to do to get the c-ares resolver working on Windows and libuv.

**Comment by markdroth** [comment]
I'm not quite clear on which two callbacks are racing each other here.  I gather from the original description that one of them was `on_lb_policy_state_changed()`, although I don't know which other one was the issue.

However, since this issue was filed, the client_channel code has been changed to use a combiner lock, and `on_lb_policy_state_changed()` is now running in the combiner (renamed to `on_lb_policy_state_changed_locked()`).  Given that, is there still a race here, or has this been fixed?
