### ISSUE TITLE
using grpc with asio

### ISSUE THREAD

**Issue by feverzsj** [grpc/grpc#9682]
what's the recommended way to use grpc with async io lib like asio?

**Comment by feverzsj** [comment]
In a typical scene, user side process should happened inside threads managed by asio::io_service. This requires grpc service to be able to send and receive notifications in a thread-safe manner. For example:

 ```cpp
 asio::io_service asioSrv;

// set handler for new request
// streaming request could just be multiple call to same handler
grpcSrv.onXXX([&](auto& reqs){ // could take multiple requests in one batch
    // the actual process handler will be scheduled by asioSrv
    asioSrv.post([reqs = std::move(reqs)](){
        // actual process
        // ...
        // notify we've done with the requests, and pass back the reply
        grpcSrv.finish(std::move(replies), Status::OK);
        // or notify an unfinished streaming reply
        // grpcSrv.stream(std::move(replies), Status::OK);
    });
});
 ```

**Comment by vjpai** [comment]
We aren't currently providing a recommended way to do this; our only async interface for now is through our CompletionQueue API. I imagine that you could make a wrapper around that that calls CQ::Next() from one or more threads and passes the resulting events to your async IO library or invokes the callbacks that you desire. Based on our previous production experience, we intentionally stayed away from having gRPC provide notification threads (since those require a latency-increasing thread-hop), callbacks (since those can tie up a library thread), or multiple buffered messages on the same side of the stream (to reduce the likelihood of OOMing), but I believe that we'd likely welcome contributions to the grpc ecosystem for a shim between our APIs and other async libraries.

**Comment by vjpai** [comment]
I'm going to close this issue for now as we won't address this, but please feel free to tag it if you have a contribution to offer.

**Comment by jamesyonan** [comment]
Any new developments on this?  It would be great if grpc could play well with Asio, especially since Asio is slated to become a part of C++17 with the Networking TS.
