### ISSUE TITLE
Timeline for milestones/releases

### ISSUE THREAD

**Issue by kolmodin** [grpc/grpc#9686]
I'm developing https://github.com/grpc/grpc-haskell against the core C library. So far I've developed against `master` and occasionally pull to make sure I'm up to date.

The [milestone 1.1](https://github.com/grpc/grpc/milestone/45) still has 146 open issues, but then I saw that `1.1.0` was [recently released](https://github.com/grpc/grpc/releases/tag/v1.1.0).

I'm considering developing against `1.1.0` instead of `master`, unless `master` will be part of a release soonish. Will it?

**Comment by hsaliak** [comment]
@kolmodin we are now planning to do 6 weekly releases, this is something we are aspiring toward and we may take longer until we get better at it.
Generally though, I would recommend you develop against master, especially for a port. The moment you start developing against a point release, rebasing forward will become incrementally harder for you. 

Unfortunately for 1.1 -- we pushed forward bugs we wanted fixed ideally but the need to have a release that was not too far off from base took priority, so we chose to stabilize and release a point release instead. Since then we have been looking at better ways to handle this and make our release process and decision making more understandable. Toward this end, we plan to publish backlogs for the point releases using Github projects. This is coming really soon. 
/cc @dgquintas who I am working with to make this happen.

**Comment by kolmodin** [comment]
@hsaliak Nice to see that you're looking into the release process and try to make it easier to understand - it's appreciated!

Will the future `1.2` (or `2.0`) be cut from `master`? I eventually would like to make a release of `grpc-haskell`, and it'd be nice to know that the next release based on `master` is not too far out. Will the 6 weekly releases be done from `master`? I ask since the `master` branch itself states that it is version `3.0.0-dev` which gives the impression that it's not anywhere close at being released.

I guess you don't keep C API compatibility between the `1.x` releases, but you do for the `1.0.x` releases?

**Comment by dgquintas** [comment]
Yes, the next release will be cut from master. I recommend to always develop against master, not against any particular release branch: master moves too quickly, and by the time you wanted your contribution to be merged back into the mainline, it'll likely have diverged significantly.

The 3.0.0-dev version you refer to is for the C-core, which exposes an API to be used only internally and/or by the wrapping languages.

**Comment by kolmodin** [comment]
OK, I guess I'll keep the main development against `master`, and when you branch a release I may have to do the same.
Thanks for clarifying the version of C-core, I thought it was the version of gRPC itself!

**Comment by kolmodin** [comment]
All my questions answered. Closing.
