### ISSUE TITLE
[C#] cannot load lib ported to net45 base on Grpc.HealthCheck1.1 installed by nuget

### ISSUE THREAD

**Issue by vincentshow** [grpc/grpc#9877]
My lib is builded by vs2015, and there're two ported dlls, one is for net45 and another is for netstandard1.6. The netstandard one works ok, while error occurs when load the net45 one. 

It says: Could not load file or assembly 'Google.Protobuf, Version=3.0.0.0, Culture=neutral, PublicKeyToken=a7d26565bac4d604' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040), but I have Google.Protobuf 3.2.0 in bin folder. 

However, after I removing the Grpc.HealthCheck dependency, the error disappeared.  Is this the dependency problem when you build Grpc.HealthCheck.dll in nuget?

**Comment by vincentshow** [comment]
@jtattermusch, how about this? And my project is about to submit to qa, can you resolve it this week? much thanks.

**Comment by jtattermusch** [comment]
I'm not sure how I should reproduces as I don't know enough details about your project, but I tried this:
1. Create an empty console application in VS2015 and try to add Grpc.HealthCheck nuget package. That actually failed with message `Severity	Code	Description	Project	File	Line	Suppression State
Error		Failed to add reference. The package 'Grpc.HealthCheck' tried to add a framework reference to 'System.Runtime' which was not found in the GAC. This is possibly a bug in the package. Please contact the package owners for assistance.`. I'll look into that further. The most likely cause is that the way importing nugets works in VS2015 has recently changed because of .NET core support. 

2. Create an empty console application in VS2013 and try to add Grpc.HealthCheck nuget and that worked just fine. (Can you try using VS2013 instead?).

What is the type of your project?

**Comment by vincentshow** [comment]
I'm using vs2015, and the runtime project is aspnet mvc3 based on netframework4.5.2. 

After adding the dll that ported for net45, there's no error when building, and the error I mentioned above occurs in runtime.

**Comment by jtattermusch** [comment]
Can you try downgrading protobuf to 3.0.0?

**Comment by jtattermusch** [comment]
So you have a fresh ASP.NET project and install  Grpc.HealthCheck nuget, and in the runtime, you get the issue you described?

**Comment by jtattermusch** [comment]
I tried installing Grpc.HealthCheck nuget into an .NET 4.5.2 MVC app and I get the error I describe befored during installation.

**Comment by vincentshow** [comment]
OK, I'll try to downgrade protobuf next week.

**Comment by vincentshow** [comment]
It works! After downgrading Google.Protobuf to 3.0.0, my site works well without building errors and runtime errors.
