### ISSUE TITLE
Synchronous grpc - blocking or polling?

### ISSUE THREAD

**Issue by akshithasriraman** [grpc/grpc#9907]
I was wondering if grpc calls implement thread blocking or polling.
Assume a situation where a client makes a synchronous grpc call to a server, then will the thread making this call go to a "blocked" state while waiting for the response from the server (and might then be woken up by some underlying network kernel thread), or does it continuously poll for the response?

**Comment by ncteisen** [comment]
As per the "view from above" our API, the thread that makes the synchronous call is blocked.

Under the hood, gRPC is free to implement that as it likes. We could make the calling thread be the polling thread, which would involve blocking on a syscall like `epoll_wait`. Or we could have some internal polling thread for that, which would wake up the user thread (waiting on a `gpr_mu`) when the right bytes come off the wire.

The reason I am leaving this vague is because this system has been changing a lot recently.
