### ISSUE TITLE
HTTP parsing broken in interop tests (for large messages)

### ISSUE THREAD

**Issue by jtattermusch** [grpc/grpc#9956]
Multiple Interop tests (Java vs PHP, C#, Node and Ruby) are currently flaky:
https://github.com/grpc/grpc/issues/9937 (java csharp)
https://github.com/grpc/grpc/issues/9762 (java csharp)
https://github.com/grpc/grpc/issues/9878 (java node)
https://github.com/grpc/grpc/issues/9865 (java ruby)
https://github.com/grpc/grpc/issues/9797 (php java)

I believe they all have the same rootcause, and it seems to be connected to HTTP parsing in C core.

*What we know:*
- easy to reproduce (e.g. run java client against C# server locally)
- it happens much more often for large messages (custom_metadata and large_unary  are using a large request).
- it seems not to happen when insecure channel is used
- we see `E0228 14:18:02.422869 139793523537664 src/core/lib/http/parser.c:287: HTTP header max line length (4096) exceeded`  (or lots of instance of `E0228 14:18:02.422869 139793523537664 src/core/lib/http/parser.c:287: HTTP client max line length (4096) exceeded` when run prior to  https://github.com/grpc/grpc/issues/9925)

Here's the log from C# server with `GRPC_TRACE=http,http1,tcp,secure_endpoint,transport_security` https://gist.github.com/anonymous/bb08ca5796e7268d812a2a5fbb262361

*Discussion:*

For some reason, C core seems to be trying to interpret payload (plenty of zeroes because of the interop test spec) as an  HTTP header:
https://github.com/grpc/grpc/blob/f2ac4bd4886c4f8122e7f5b10f28ed7a2cfaa0a8/src/core/lib/http/parser.c#L287
The `addbyte` method never runs for the actual headers (they are parsed by `I0302 15:00:31.959544 140280549340928 src/core/ext/transport/chttp2/transport/parsing.c:477:`). The bytes seen by addbyte are all zeros so grpc_http_parser_parse never sees "end of http header line" and errors out.
The thing I don't understand is why is grpc_http_parser_parse running to parse new slices at all, after we've already read the actual headers and we know the payload should be coming (maybe a data race?)

Disclaimer: I haven't verified that java actually sends well-formed http2 frames as a request, but given the failures are flakes, it seems more likely that there's a problem with http parsing on the C core side.

**Comment by jtattermusch** [comment]
@ctiller, please assign to someone on C core team.

**Comment by jtattermusch** [comment]
CC @murgatroid99 @stanley-cheung @ejona86  @apolcyn

**Comment by dgquintas** [comment]
This is a very important issue, thank you @jtattermusch for creating it. It's been keeping the interop tests broken for a while.

**Comment by ctiller** [comment]
I'm running 'tools/run_tests/run_interop_tests.py -s csharp -l java
--use_docker' and not seeing the failure... any better way to reproduce?

**Comment by jtattermusch** [comment]
It should happen fairly often.

Running manually:
grpc-java client:
```
./gradlew :grpc-interop-testing:installDist -P skipCodegen=true
./run-test-client.sh --use_tls=true --use_test_ca=true --test_case=custom_metadata --server_port=8070 --server_host=localhost --server_host_override=foo.test.google.fr
```

c# server
```
~github/grpc$ tools/run_tests/run_tests.py -l csharp -c dbg --build_only
~/github/grpc/src/csharp/Grpc.IntegrationTesting.Server/bin/Debug$ GRPC_TRACE=http,http1,tcp,secure_endpoint,transport_security GRPC_VERBOSITY=debug mono Grpc.IntegrationTesting.Server.exe --port=8070 --use_tls=true 2>error_output.txt
```

**Comment by ctiller** [comment]
```
++ dirname tools/run_tests/helper_scripts/build_csharp.sh
+ cd tools/run_tests/helper_scripts/../../../src/csharp
+ xbuild /p:Configuration=Debug /p:NativeDependenciesConfigurationUnix=dbg Grpc.sln
tools/run_tests/helper_scripts/build_csharp.sh: line 36: xbuild: command not found
```

any solution that doesn't involve having to maintain a c# installation?

**Comment by jtattermusch** [comment]
you can use https://github.com/grpc/grpc/blob/master/tools/gce/create_linux_performance_worker.sh to get yourself a VM with all the prerequisites installed.

**Comment by jtattermusch** [comment]
Also, I double checked and I can reproduce the issue on my machine with `tools/run_tests/run_interop_tests.py -l java -s csharp --use_docker` very reliably (more than 50% of time).

**Comment by ctiller** [comment]
Can reproduce now.

With GRPC_TRACE=connectivity_state:

D0307 18:47:33.240479 139713217296128
src/core/lib/transport/connectivity_state.c:184: SET: 0x7f1178010e08
server_transport: READY --> SHUTDOWN [close_transport] error=0x7f1178003710
{"created":"@1488912453.240422563","description":"Delayed close due to
in-progress
write","file":"src/core/ext/transport/chttp2/transport/chttp2_transport.c","file_line":517,"grpc_status":14,"referenced_errors":[{"created":"@1488912453.240421565","description":"Failed
parsing
HTTP/2","file":"src/core/ext/transport/chttp2/transport/chttp2_transport.c","file_line":1971,"referenced_errors":[{"created":"@1488912453.240369476","description":"frame
of size 4900 overflows incoming window of
0","file":"src/core/ext/transport/chttp2/transport/parsing.c","file_line":391}]}]}

Looks like a flow control disagreement... not sure as yet which side.

On Tue, Mar 7, 2017 at 9:44 AM Jan Tattermusch <notifications@github.com>
wrote:

Also, I double checked and I can reproduce the issue on my machine
with tools/run_tests/run_interop_tests.py
-l java -s csharp --use_docker very reliably (more than 50% of time).

—
You are receiving this because you were mentioned.


Reply to this email directly, view it on GitHub
<https://github.com/grpc/grpc/issues/9956#issuecomment-284799682>, or mute
the thread

**Comment by ejona86** [comment]
@ctiller tracked down the flow control issue due to SETTINGS updating INITIAL_WINDOW_SIZE. On further investigation it seemed Java was consuming additionally-given window before sending a SETTINGS ACK.

I can confirm it appears Java/Netty is doing the wrong thing. `encoder.remoteSettings()` [is called before](https://github.com/netty/netty/blob/netty-4.1.8.Final/codec-http2/src/main/java/io/netty/handler/codec/http2/DefaultHttp2ConnectionDecoder.java#L452,L455) `writeSettingsAck()`. `encoder.remoteSettings()` [calls](https://github.com/netty/netty/blob/netty-4.1.8.Final/codec-http2/src/main/java/io/netty/handler/codec/http2/DefaultHttp2ConnectionEncoder.java#L113) `flowController().initialWindowSize()` which results in [the flow controller writing pending bytes](https://github.com/netty/netty/blob/netty-4.1.8.Final/codec-http2/src/main/java/io/netty/handler/codec/http2/DefaultHttp2RemoteFlowController.java#L659).

Two immediate changes should probably be made: 1) Send the settings ack immediately before processing the settings frame in the decoder. Any failure in processing would probably result in the connection being closed, so this doesn't seem dangerous. 2) Stop triggering `writePendingBytes()` in the flow controller and instead [wait for the `flush()` like normal](https://github.com/netty/netty/blob/netty-4.1.8.Final/codec-http2/src/main/java/io/netty/handler/codec/http2/Http2ConnectionHandler.java#L166).

We should test to make sure, but we believe grpc-java v1.1 is impacted. That means it's unclear how C should cope with the bug.

We should really have some better way of dealing with this. In spending 2 seconds thinking about the problem, Craig and I are thinking of sending a trash number in the initial SETTINGS. The number could be randomly selected each release. That way, if we find a bug like this, we could workaround it.

**Comment by ejona86** [comment]
We tested and were not able to reproduce the issue with v1.0 but were with v1.1. This agrees with when grpc-java upgraded to Netty 4.1.8 from 4.1.6 (as in v1.0.2; v1.0.1 had an earlier version of netty). We should still check whether v1.0.1 is impacted.

**Comment by jtattermusch** [comment]
https://github.com/netty/netty/issues/6520
